--PROCEDUR UNTUK MENAMPILKAN DATA BRAND YANG BELUM ADA REFERENCY DI TABEL ANAK
IF EXISTS(SELECT NAME FROM [DBO].SYSOBJECTS WHERE NAME = 'Sp_Select_Brand' and Type = 'p')
DROP PROCEDURE Sp_Select_Brand
GO
CREATE PROCEDURE Sp_Select_Brand
AS
SELECT * FROM Nufarm.dbo.BRND_BRAND WHERE BRAND_ID NOT IN(SELECT BRAND_ID FROM BRND_BRANDPACK)
GO
-------------------------------------------------------------------------------
--PROCEDURE UNTUK MEMILIH ALL BRAND
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_SelectAllBrand' AND TYPE = 'P')
DROP PROCEDURE Sp_SelectAllBrand
GO
--CREATE PROCEDURE Sp_SelectAllBrand
--as
--SELECT * FROM BRND_BRAND
--GO
------------------------------------------------------------------------------------
--PROCEDURE UNTUK MENGECEK DATA BRAND YAND ADA DI TABLE ANAKNYA
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Check_Brand_ID' AND TYPE = 'P')
DROP PROCEDURE Sp_Check_Brand_ID
GO
CREATE PROCEDURE Sp_Check_Brand_ID
@BRAND_ID varchar(7)
AS
BEGIN  
IF (SELECT COUNT(BRAND_ID) FROM BRND_BRANDPACK WHERE BRAND_ID = @BRAND_ID) > 0
    return(1)
ELSE IF (SELECT COUNT(BRAND_ID) FROM AGREE_BRAND_INCLUDE WHERE BRAND_ID = @BRAND_ID) > 0
    RETURN(2)
END
return(0)
GO

------------------------------------------------------------------------------------
--PROCEDURE UNTUK MENAMPILKAN DATA BRND_PACK YANG BELUM ADA REFERENCY DI TABEL ANAK
IF EXISTS(SELECT NAME FROM [DBO].SYSOBJECTS WHERE NAME = 'Usp_Select_Pack' AND TYPE = 'p')
DROP  PROCEDURE Usp_Select_Pack
GO
CREATE PROCEDURE Usp_Select_Pack
AS
SELECT * FROM Nufarm.dbo.BRND_PACK WHERE PACK_ID NOT IN(SELECT PACK_ID FROM BRND_BRANDPACK)
GO
--------------------------------------------------------------------------------
--PROCEDURE UNTUK MEMILIH SELURUH DATA BRAND
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_SelectAll_PACK' AND TYPE = 'P')
DROP PROCEDURE Sp_SelectAll_PACK
GO
--CREATE PROCEDURE Sp_SelectAll_PACK
--AS
--SELECT * FROM BRND_PACK
--GO

--------------------------------------------------------------------------------------
--PROCEDURE UNTUK MENGECEK DATA BRAND YANG ADA DI SERVER
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Check_PACK_ID' AND TYPE = 'P')
DROP PROCEDURE Sp_Check_PACK_ID
GO
CREATE PROCEDURE Sp_Check_PACK_ID
@PACK_ID VARCHAR(7)
AS
BEGIN 
IF (SELECT COUNT(PACK_ID) FROM BRND_BRANDPACK WHERE PACK_ID = @PACK_ID) > 0
     	 return(1)
   return(0)
 END
GO
-------------------------------------------------------------------------------------
--PROCEDURE UNTUK MENAMPILKAN DATA ITEM BRANDPACK DI DATAGRID YANG BELUM ADA REFERENSI DI TABLE ANAK
--UNTUK DI BINDING DI DATAGRID EX DAPA MODE ORIGINAL ROWS
IF EXISTS(SELECT NAME FROM [dbo].SYSOBJECTS WHERE NAME = 'Sp_Select_BrandPack' AND TYPE = 'P')
DROP PROCEDURE Sp_Select_BrandPack
GO
CREATE PROCEDURE Sp_Select_BrandPack
AS
SELECT * FROM BRND_BRANDPACK WHERE BRANDPACK_ID NOT IN(SELECT BRANDPACK_ID FROM PROJ_BRANDPACK)
AND BRANDPACK_ID NOT IN(SELECT BRANDPACK_ID FROM ORDR_PO_BRANDPACK) AND BRANDPACK_ID NOT IN(SELECT BRANDPACK_ID
FROM AGREE_BRANDPACK_INCLUDE) AND BRANDPACK_ID NOT IN(SELECT BRANDPACK_ID FROM MRKT_BRANDPACK) AND BRANDPACK_ID NOT IN(
SELECT BRANDPACK_ID FROM BRND_PRICE_HISTORY)
GO

-------------------------------------------------------------------------------------
--PROCEDURE UNTUK MENAMPILKAN SELURUH BRANPACK
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Select_AllBrandPack' AND TYPE = 'P')
DROP PROCEDURE Sp_Select_AllBrandPack
GO
CREATE PROCEDURE Sp_Select_AllBrandPack
AS
SELECT * FROM BRND_BRANDPACK
GO

--------------------------------------------------------------------------------------
--PROCEDURE UNTUK MENGECEK TABEL ANAK DI BRAND_PACK
IF EXISTS(SELECT NAME FROM.DBO.SYSOBJECTS WHERE NAME = 'Usp_Check_Referenced_BRANDPACK_ID' AND TYPE = 'P')
DROP PROCEDURE Usp_Check_Referenced_BRANDPACK_ID
GO
CREATE PROCEDURE Usp_Check_Referenced_BRANDPACK_ID
@BRANDPACK_ID VARCHAR(14)
AS
BEGIN
IF EXISTS(SELECT BRANDPACK_ID FROM BRND_PRICE_HISTORY WHERE BRANDPACK_ID = @BRANDPACK_ID)
	RETURN(1)
ELSE IF EXISTS(SELECT BRANDPACK_ID FROM AGREE_BRANDPACK_INCLUDE WHERE BRANDPACK_ID = @BRANDPACK_ID)
	RETURN(1)
ELSE IF EXISTS(SELECT BRANDPACK_ID FROM MRKT_BRANDPACK WHERE BRANDPACK_ID = @BRANDPACK_ID)
	RETURN(1)
ELSE IF EXISTS(SELECT BRANDPACK_ID FROM ORDR_PO_BRANDPACK WHERE BRANDPACK_ID = @BRANDPACK_ID)
	RETURN(1)
ELSE IF EXISTS(SELECT BRANDPACK_ID FROM PROJ_BRANDPACK WHERE BRANDPACK_ID = @BRANDPACK_ID)
	RETURN(1)
ELSE IF EXISTS(SELECT BRANDPACK_ID FROM DIST_PLANT_PRICE WHERE BRANDPACK_ID = @BRANDPACK_ID)
	RETURN(1)
ELSE IF EXISTS(SELECT BRANDPACK_ID FROM ACCRUED_DETAIL WHERE BRANDPACK_ID = @BRANDPACK_ID)
	RETURN(1)
ELSE IF EXISTS(SELECT BrandPackCode FROM DetailReaching WHERE BrandPackCode = @BRANDPACK_ID)
	RETURN(1)
ELSE 
	RETURN(0)
END
GO

--------------------------------------------------------------------------------------
--PROCEDURE UNTUK MENGECEK REFERENCE DATA DI TABLE BRND_PRICE_HISTORY
IF EXISTS(SELECT NAME FROM.DBO.SYSOBJECTS WHERE NAME = 'Sp_Check_Referenced_BRANDPACK_ID_PRICE' AND TYPE = 'P')
DROP PROCEDURE Sp_Check_Referenced_BRANDPACK_ID_PRICE
GO
CREATE PROCEDURE Sp_Check_Referenced_BRANDPACK_ID_PRICE
@BRANDPACK_ID VARCHAR(14),
@START_DATE DATETIME
AS
BEGIN
IF EXISTS(SELECT TOP 1 OPB.BRANDPACK_ID FROM ORDR_PO_BRANDPACK OPB INNER JOIN ORDR_PURCHASE_ORDER OPO
ON OPO.PO_REF_NO = OPB.PO_REF_NO WHERE OPO.PO_REF_DATE >= @START_DATE
AND OPB.BRANDPACK_ID = @BRANDPACK_ID ORDER BY OPO.PO_REF_DATE ASC)
	BEGIN
		PRINT 'RETURN 1'
	  RETURN(1)
	END
END
RETURN(0)
GO
--exec Sp_Check_Referenced_BRANDPACK_ID_PRICE
--@BRANDPACK_ID = '000059005LD',@START_DATE = '1/9/2008'

--------------------------------------------------------------------------------------
--PROCEDURE UNTUK MENGISI DROPDOWN BUTTON BRANDPACK DI DATAGRID BRANDPACK_HISTORY
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME  = 'Sp_Select_BRAND_BRANDPACK_FOR_DROPDOWN' AND TYPE = 'P')
DROP PROCEDURE Sp_Select_BRAND_BRANDPACK_FOR_DROPDOWN
GO
--IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Select_BRAND_BRANDPACK_FOR_DROPDOWN' AND TYPE = 'P')
--DROP PROCEDURE Usp_Select_BRAND_BRANDPACK_FOR_DROPDOWN
--GO
--CREATE PROCEDURE Usp_Select_BRAND_BRANDPACK_FOR_DROPDOWN
--AS
--SET NOCOUNT ON;
--SELECT BRANDPACK_ID,BRANDPACK_NAME FROM BRND_BRANDPACK WHERE IsActive = 1
--AND
--SELECT BRND_BRAND.BRAND_NAME,BRND_PACK.PACK_NAME,BRND_BRANDPACK.BRANDPACK_ID,BRND_BRANDPACK.BRANDPACK_NAME
--FROM BRND_BRAND,BRND_PACK,BRND_BRANDPACK
--WHERE BRND_BRANDPACK.BRAND_ID = BRND_BRAND.BRAND_ID AND BRND_BRANDPACK.PACK_ID = BRND_PACK.PACK_ID
--GO

-------------------------------------------------------------------------------------
IF EXISTS(SELECT NAME FROM [DBO].SYSOBJECTS WHERE NAME = 'Sp_Select_PriceHistory' AND TYPE = 'P')
DROP PROCEDURE Sp_Select_PriceHistory
GO
CREATE PROCEDURE Sp_Select_PriceHistory
AS
SELECT * FROM BRND_PRICE_HISTORY
GO

--------------------------------------------------------------------------------------
IF EXISTS(SELECT NAME FROM [DBO].SYSOBJECTS WHERE NAME = 'Sp_Select_Territory' AND TYPE = 'P')
DROP PROCEDURE Sp_Select_Territory
GO
CREATE PROCEDURE Sp_Select_Territory
AS
SELECT * FROM TERRITORY
GO

--------------------------------------------------------------------------------------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Select_Territory_Manager' AND TYPE = 'P')
DROP PROCEDURE Usp_Select_Territory_Manager
GO
CREATE PROCEDURE Usp_Select_Territory_Manager
AS
SELECT * FROM TERRITORY_MANAGER
GO
---------------------------------------------------------------------------------------
--PROCEDURE UNTUK MENGECEK REFERENCED DATA TERRITORY
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Select_REFERENCED_TERRITORY' AND TYPE = 'P')
DROP PROCEDURE Sp_Select_REFERENCED_TERRITORY
GO
CREATE PROCEDURE Sp_Select_REFERENCED_TERRITORY
@TERRITORY_ID VARCHAR(10)
AS
BEGIN
IF (SELECT COUNT(TERRITORY_ID) FROM SHIP_TO WHERE TERRITORY_ID = @TERRITORY_ID) > 0
	RETURN(1)
END
RETURN(0)
GO
---------------------------------------------------------------------------------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Select_Referenced_Territory_Manager' AND TYPE = 'P')
DROP PROCEDURE Usp_Select_Referenced_Territory_Manager
GO
CREATE PROCEDURE Usp_Select_Referenced_Territory_Manager
@TM_ID VARCHAR(10)
AS
IF EXISTS(SELECT TM_ID FROM SHIP_TO WHERE TM_ID = @TM_ID)
	RETURN(1)
ELSE
	RETURN(0)
GO

---------------------------------------------------------------------------------------
IF EXISTS(SELECT NAME FROM [DBO].SYSOBJECTS WHERE NAME = 'Sp_Select_Regional' AND TYPE = 'P')
DROP PROCEDURE Sp_Select_Regional
GO 
CREATE PROCEDURE Sp_Select_Regional
AS
SELECT * FROM DIST_REGIONAL
GO
---------------------------------------------------------------------------------
--PROCEDURE UNTUK MENGECEK REFERENCED DATA DI TABLE REGIONAL
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Check_REFERENCED_REGIONAL' AND TYPE = 'P')
DROP PROCEDURE Sp_Check_REFERENCED_REGIONAL
GO
CREATE PROCEDURE Sp_Check_REFERENCED_REGIONAL
@REGIONAL_ID VARCHAR(5)
AS
BEGIN
IF (SELECT COUNT(REGIONAL_ID) FROM TERRITORY WHERE REGIONAL_ID = @REGIONAL_ID) > 0
	RETURN(1) 
END
RETURN(0)
GO

-------------------------------------------------------------------------------------
IF EXISTS(SELECT NAME FROM [DBO].SYSOBJECTS WHERE NAME = 'Sp_Select_Distributor' AND TYPE = 'P')
DROP PROCEDURE Sp_Select_Distributor
GO
CREATE PROCEDURE Sp_Select_Distributor
AS
SELECT * FROM Nufarm.dbo.DIST_DISTRIBUTOR
GO
-------------------------------------------------------------------------------------
--PROCEDURE UNTUK MENGECEK REFERENCI TABLE ANAK DISTRIBUTOR
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Select_ReferencedChild_DIST_DISTRIBUTOR' AND TYPE = 'P')
DROP PROCEDURE Sp_Select_ReferencedChild_DIST_DISTRIBUTOR
GO
CREATE PROCEDURE Sp_Select_ReferencedChild_DIST_DISTRIBUTOR
@DISTRIBUTOR_ID VARCHAR(10)
AS
BEGIN

 IF EXISTS(SELECT DISTRIBUTOR_ID FROM DISTRIBUTOR_AGREEMENT WHERE DISTRIBUTOR_ID = @DISTRIBUTOR_ID)
 	RETURN(2) 
 END
RETURN(0)
GO

-------------------------------------------------------------------------------------
--PROCEDURE UNTUK MENDELETE DATA DISTRIBUTOR
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Delete_Distributor'  AND TYPE = 'P')
DROP PROCEDURE Sp_Delete_Distributor
GO
CREATE PROCEDURE Sp_Delete_Distributor
@DISTRIBUTOR_ID VARCHAR(10)
AS
DELETE FROM DIST_DISTRIBUTOR WHERE DISTRIBUTOR_ID = @DISTRIBUTOR_ID
GO

--------------------------------------------------------------------------------------
--PROCEDURE UNTUK MENAMPILKAN DATA DI GRID_PURCAHSE ORDER
IF EXISTS(SELECT NAME FROM [dbo].SYSOBJECTS WHERE NAME = 'Sp_Select_PurchaseOrder' AND TYPE = 'P')
DROP PROCEDURE Sp_Select_PurchaseOrder
GO
CREATE PROCEDURE Sp_Select_PurchaseOrder
AS
SELECT DIST_DISTRIBUTOR.DISTRIBUTOR_NAME,ORDR_PURCHASE_ORDER.PO_REF_NO,ORDR_PURCHASE_ORDER.PO_REF_DATE,
ORDR_PURCHASE_ORDER.PROJ_REF_NO FROM DIST_DISTRIBUTOR INNER JOIN ORDR_PURCHASE_ORDER ON DIST_DISTRIBUTOR.DISTRIBUTOR_ID = 
ORDR_PURCHASE_ORDER.DISTRIBUTOR_ID 
GO

-----------------------------------------------------------------------------------
IF EXISTS(SELECT NAME FROM [DBO].SYSOBJECTS WHERE NAME = 'Sp_Select_ProgramRegistering' AND TYPE = 'P')
DROP PROCEDURE Sp_Select_ProgramRegistering
GO
CREATE PROCEDURE Sp_Select_ProgramRegistering
AS
SELECT * FROM Nufarm.[dbo].MRKT_MARKETING_PROGRAM
GO	
----------------------------------------------------------------------------------
IF EXISTS(SELECT NAME FROM [dbo].SYSOBJECTS WHERE NAME = 'Sp_Select_Agreement' AND TYPE = 'p')
DROP PROCEDURE Sp_Select_Agreement
GO 
CREATE PROCEDURE Sp_Select_Agreement
AS
SELECT * FROM Nufarm.dbo.AGREE_AGREEMENT
GO

------------------------------------------------------------------------------------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Select_OARegistering' AND TYPE = 'P')
DROP PROCEDURE Sp_Select_OARegistering
GO
CREATE PROCEDURE Sp_Select_OARegistering
AS
SELECT * FROM Nufarm.dbo.ORDR_ORDER_ACCEPTANCE
GO
------------------------------------------------------------------------------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Select_Project' AND TYPE = 'P')
DROP PROCEDURE Sp_Select_Project
GO
CREATE PROCEDURE Sp_Select_Project
AS SELECT * FROM Nufarm.dbo.PROJ_PROJECT
GO
---------------------------------------------------------------------------------------
IF EXISTS(SELECT NAME FROM [DBO].SYSOBJECTS WHERE NAME = 'Sp_Insert_Distributor' AND TYPE = 'P')
DROP PROCEDURE Sp_Insert_Distributor
GO
CREATE PROCEDURE Sp_Insert_Distributor
@DISTRIBUTOR_ID VARCHAR(10),
@DISTRIBUTOR_NAME VARCHAR(50),
@RESPONSIBLE_PERSON VARCHAR(50),
@TERRITORY_ID VARCHAR(10),
@PARENT_DISTRIBUTOR_ID VARCHAR(10),
@NPWP VARCHAR(30),
@MAX_DISC_PER_PO DECIMAL(10,3),
@ADDRESS VARCHAR(150),
@CONTACT VARCHAR(30),
@PHONE VARCHAR(30),
@FAX VARCHAR(20),
@HP VARCHAR(20),
@BIRTH_DATE DATETIME,
@CREATE_BY VARCHAR(30),
@JOIN_DATE SMALLDATETIME,
@HP1 VARCHAR(20) =  NULL
AS
SET NOCOUNT ON;
INSERT INTO Nufarm.dbo.DIST_DISTRIBUTOR(DISTRIBUTOR_ID,DISTRIBUTOR_NAME,RESPONSIBLE_PERSON,TERRITORY_ID,
PARENT_DISTRIBUTOR_ID,NPWP,MAX_DISC_PER_PO,ADDRESS,CONTACT,PHONE,FAX,HP,HP1,BIRTH_DATE,JOIN_DATE,CREATE_BY,CREATE_DATE)
VALUES(@DISTRIBUTOR_ID,@DISTRIBUTOR_NAME,@RESPONSIBLE_PERSON,@TERRITORY_ID,@PARENT_DISTRIBUTOR_ID,@NPWP,
@MAX_DISC_PER_PO,@ADDRESS,@CONTACT,@PHONE,@FAX,@HP,@HP1,@BIRTH_DATE,@JOIN_DATE,@CREATE_BY,getdate())
GO

--------------------------------------------------------------------------------------
IF EXISTS(SELECT NAME FROM dbo.SYSOBJECTS WHERE NAME = 'Sp_Update_Distributor' AND TYPE = 'P')
DROP PROCEDURE Sp_Update_Distributor
GO
CREATE PROCEDURE Sp_Update_Distributor
@DISTRIBUTOR_ID VARCHAR(10),
@DISTRIBUTOR_NAME VARCHAR(50),
@RESPONSIBLE_PERSON VARCHAR(50),
@TERRITORY_ID VARCHAR(10),
@PARENT_DISTRIBUTOR_ID VARCHAR(10),
@NPWP VARCHAR(30),
@MAX_DISC_PER_PO DECIMAL(10,3),
@ADDRESS VARCHAR(150),
@CONTACT VARCHAR(30),
@PHONE VARCHAR(30),
@FAX VARCHAR(20),
@HP VARCHAR(20),
@BIRTH_DATE DATETIME,
@MODIFY_BY VARCHAR(30),
@JOIN_DATE SMALLDATETIME,
@HP1 VARCHAR(20) =  NULL
AS
SET NOCOUNT ON;
UPDATE Nufarm.dbo.DIST_DISTRIBUTOR
SET DISTRIBUTOR_NAME = @DISTRIBUTOR_NAME,RESPONSIBLE_PERSON = @RESPONSIBLE_PERSON,
TERRITORY_ID = @TERRITORY_ID,PARENT_DISTRIBUTOR_ID = @PARENT_DISTRIBUTOR_ID,
NPWP = @NPWP,MAX_DISC_PER_PO = @MAX_DISC_PER_PO,ADDRESS =@ADDRESS,CONTACT =@CONTACT,
PHONE = @PHONE,FAX = @FAX,HP = @HP,HP1 = @HP1,JOIN_DATE = @JOIN_DATE,MODIFY_BY = @MODIFY_BY,BIRTH_DATE = @BIRTH_DATE,MODIFY_DATE = GETDATE()
WHERE DISTRIBUTOR_ID = @DISTRIBUTOR_ID
GO
------------------------------------------------------------------------------
-- INSERT AGREEMENT
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Insert_Agree_Agreement' AND TYPE = 'p')
DROP PROCEDURE Sp_Insert_Agree_Agreement
GO
CREATE PROCEDURE Sp_Insert_Agree_Agreement
@AGREEMENT_NO VARCHAR(25),
@AGREEMENT_DESC VARCHAR(50),
--@DISTRIBUTOR_ID VARCHAR(10),
@START_DATE DATETIME,
@END_DATE DATETIME,
@QS_TREATMENT_FLAG CHAR(1),
--@TARGET_YEAR BIGINT,
@CREATE_BY VARCHAR(30)
AS
SET NOCOUNT ON;
INSERT INTO AGREE_AGREEMENT(AGREEMENT_NO,AGREEMENT_DESC,START_DATE,END_DATE,
QS_TREATMENT_FLAG--,TARGET_YEAR
,CREATE_BY,CREATE_DATE)
VALUES(@AGREEMENT_NO,@AGREEMENT_DESC,@START_DATE,@END_DATE,@QS_TREATMENT_FLAG,--@TARGET_YEAR,
@CREATE_BY,GETDATE())
GO

---------------------------------------PROCEDURE UNTUK MENGINSERT DISTRIBUTOR_AGREEMENT----------------------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Insert_Distributor_Agreement' AND TYPE ='P')
DROP PROCEDURE Usp_Insert_Distributor_Agreement
GO
CREATE PROCEDURE Usp_Insert_Distributor_Agreement
@DISTRIBUTOR_ID VARCHAR(10),
@AGREEMENT_NO VARCHAR(25),
@CREATE_BY VARCHAR(50),
@CREATE_DATE SMALLDATETIME
AS
SET NOCOUNT ON;
INSERT INTO DISTRIBUTOR_AGREEMENT(DISTRIBUTOR_ID,AGREEMENT_NO,CREATE_BY,CREATE_DATE)
VALUES(@DISTRIBUTOR_ID,@AGREEMENT_NO,@CREATE_BY,@CREATE_DATE)
GO

--------------------------------------------------------------------------------
-- INSERT AGREEMENT PROGRESSIVE DISCOUNT
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Insert_Agree_progressive_Discount' AND TYPE = 'P')
DROP PROCEDURE Sp_Insert_Agree_progressive_Discount
GO
CREATE PROCEDURE Sp_Insert_Agree_progressive_Discount
@AGREEMENT_NO VARCHAR(25),
@UP_TO_PCT DECIMAL,
@PRGSV_DISC_PCT DECIMAL,
@QSY_DISC_FLAG CHAR(1),
@CREATE_BY VARCHAR(30)
AS
INSERT INTO AGREE_PROGRESSIVE_DISCOUNT(AGREEMENT_NO,UP_TO_PCT,PRGSV_DISC_PCT,
QSY_DISC_FLAG,CREATE_BY)
VALUES(@AGREEMENT_NO,@UP_TO_PCT,@PRGSV_DISC_PCT,@QSY_DISC_FLAG,@CREATE_BY)
GO
--------------------------------------------------------------------------------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Select_Agree_Progressive_Discount' AND TYPE = 'P')
DROP PROCEDURE Sp_Select_Agree_Progressive_Discount
GO
CREATE PROCEDURE Sp_Select_Agree_Progressive_Discount
AS
SELECT * FROM AGREE_PROGRESSIVE_DISCOUNT
GO
-----------------------------------------------------------------------------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Select_Agreement_Group' AND TYPE = 'P')
DROP PROCEDURE Usp_Select_Agreement_Group
GO
CREATE PROCEDURE Usp_Select_Agreement_Group
@AGREEMENT_NO VARCHAR(25)
AS
SELECT VIEW_DISTRIBUTOR.TERRITORY_AREA,VIEW_DISTRIBUTOR.REGIONAL_AREA,
DISTRIBUTOR_AGREEMENT.DISTRIBUTOR_ID,VIEW_DISTRIBUTOR.DISTRIBUTOR_NAME 
FROM VIEW_DISTRIBUTOR INNER JOIN DISTRIBUTOR_AGREEMENT
ON DISTRIBUTOR_AGREEMENT.DISTRIBUTOR_ID = VIEW_DISTRIBUTOR.DISTRIBUTOR_ID
WHERE DISTRIBUTOR_AGREEMENT.AGREEMENT_NO = @AGREEMENT_NO
GO
-----------------------------------------------------------------------------------------------
----PROCEDURE UNTUK MEMVIEW DATA AGREEMENT DI FILTER BERDASARKAN WAKTU---------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Create_View_Agreement' AND TYPE = 'P')
DROP PROCEDURE Usp_Create_View_Agreement
GO
CREATE PROCEDURE Usp_Create_View_Agreement
@START_DATE DATETIME,
@END_DATE DATETIME
AS
BEGIN
IF (@START_DATE IS NOT NULL AND @END_DATE IS NOT NULL)
   BEGIN
  	 SELECT DISTRIBUTOR_ID,DISTRIBUTOR_NAME,AGREEMENT_NO,START_DATE,END_DATE,BRAND_NAME,BRANDPACK_ID,BRANDPACK_NAME
  	 FROM VIEW_DISTRIBUTOR_AGREEMENT WHERE START_DATE >= @START_DATE AND END_DATE <= @END_DATE
   END
ELSE IF (@START_DATE IS NOT NULL)
   BEGIN
   	 SELECT DISTRIBUTOR_ID,DISTRIBUTOR_NAME,AGREEMENT_NO,START_DATE,END_DATE,BRAND_NAME,BRANDPACK_ID,BRANDPACK_NAME
  	 FROM VIEW_DISTRIBUTOR_AGREEMENT WHERE START_DATE >= @START_DATE
   END
ELSE IF (@END_DATE IS NOT NULL)
   BEGIN
	 SELECT DISTRIBUTOR_ID,DISTRIBUTOR_NAME,AGREEMENT_NO,START_DATE,END_DATE,BRAND_NAME,BRANDPACK_ID,BRANDPACK_NAME
  	 FROM VIEW_DISTRIBUTOR_AGREEMENT WHERE END_DATE <= @END_DATE
   END
END
GO
--exec Usp_Create_View_Agreement
--@START_DATE = '7/8/2008',
--@END_DATE = NULL
-----------------------------------------------------------------------------------------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Select_QS_Flag' AND TYPE = 'P')
DROP PROCEDURE Sp_Select_QS_Flag
GO
CREATE PROCEDURE Sp_Select_QS_Flag
@QS_FLAG CHAR(1),
@AGREEMENT_NO VARCHAR(25)
AS
SET NOCOUNT ON;
SELECT UNIQUE_ID,AGREEMENT_NO,UP_TO_PCT, PRGSV_DISC_PCT , QSY_DISC_FLAG 
FROM AGREE_PROGRESSIVE_DISCOUNT
WHERE (QSY_DISC_FLAG = @QS_FLAG) AND (AGREEMENT_NO = @AGREEMENT_NO)
ORDER BY UP_TO_PCT ASC;
GO
------------------------------------------------------------------------------------------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Select_Y_Flag' AND TYPE = 'P')
DROP PROCEDURE Sp_Select_Y_Flag
GO
CREATE PROCEDURE Sp_Select_Y_Flag
@AGREEMENT_NO VARCHAR(25)
AS
SET NOCOUNT ON;
SELECT UNIQUE_ID,AGREEMENT_NO, UP_TO_PCT,PRGSV_DISC_PCT, QSY_DISC_FLAG 
FROM  AGREE_PROGRESSIVE_DISCOUNT
WHERE (QSY_DISC_FLAG = 'Y') AND (AGREEMENT_NO = @AGREEMENT_NO)
ORDER BY UP_TO_PCT ASC;
GO
---------------------------------------------------------------------------------------
--PROCEDUR UNTUK MENYELEK DATA DI TABLE AGREE_PROG_DISCOUNT UNTUK DI BINDINGKAN DI 
--DATAGRID PERIODIK FORM AgreementRelation BUAT SAVING DATASET
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS  WHERE NAME = 'Usp_Select_QS_Flag' AND TYPE = 'P')
DROP PROCEDURE Usp_Select_QS_Flag
GO
CREATE PROCEDURE Usp_Select_QS_Flag
@QS_FLAG VARCHAR(2),
@AGREE_BRAND_ID VARCHAR(32)
AS
SET NOCOUNT ON;
SELECT UNIQUE_ID,AGREE_BRAND_ID,UP_TO_PCT, PRGSV_DISC_PCT , QSY_DISC_FLAG 
FROM AGREE_PROG_DISC
WHERE (QSY_DISC_FLAG LIKE @QS_FLAG + '%') AND (AGREE_BRAND_ID = @AGREE_BRAND_ID)
ORDER BY UP_TO_PCT ASC;
GO
-----------------------------------------------------------------------------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Select_Y_Flag' AND TYPE = 'P')
DROP PROCEDURE Usp_Select_Y_Flag
GO
CREATE PROCEDURE Usp_Select_Y_Flag
@AGREE_BRAND_ID VARCHAR(32)
AS
SET NOCOUNT ON;
SELECT UNIQUE_ID,AGREE_BRAND_ID, UP_TO_PCT,PRGSV_DISC_PCT, QSY_DISC_FLAG 
FROM  AGREE_PROG_DISC
WHERE (QSY_DISC_FLAG = 'Y') AND (AGREE_BRAND_ID = @AGREE_BRAND_ID)
ORDER BY UP_TO_PCT ASC;
GO
-----------------------------------------------------------------------------------------
-- UPDATE AGREEMENT
----------------------------------------------------------------------------------------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Update_Agreement' and TYPE = 'P')
DROP PROCEDURE Sp_Update_Agreement
GO
CREATE PROCEDURE Sp_Update_Agreement
@AGREEMENT_NO VARCHAR(25),
@AGREEMENT_DESC VARCHAR(50),
@START_DATE DATETIME,
@END_DATE DATETIME,
@QS_TREATMENT_FLAG CHAR(1),
@MODIFY_BY VARCHAR(30)
AS
SET NOCOUNT ON;
UPDATE AGREE_AGREEMENT 
SET AGREEMENT_DESC = @AGREEMENT_DESC,--DISTRIBUTOR_ID = @DISTRIBUTOR_ID,
START_DATE = @START_DATE,END_DATE = @END_DATE,QS_TREATMENT_FLAG = @QS_TREATMENT_FLAG,
MODIFY_BY = @MODIFY_BY,MODIFY_DATE = GETDATE() WHERE AGREEMENT_NO = @AGREEMENT_NO
--------------------------------------------------------------------------------------
------------------------------------------------------------------------
--SELECT BRAND_NAME FROM BRAND WHICH AGREEMENT_NO IS DIFINED IN BRAND_INCLUDE
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Select_FilterBrandName' AND TYPE = 'P')
DROP PROCEDURE Usp_Select_FilterBrandName
GO
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Select_FilterBrandName' AND TYPE = 'P')
DROP PROCEDURE Sp_Select_FilterBrandName
GO
CREATE PROCEDURE Usp_Select_FilterBrandName
@AGREEMENT_NO VARCHAR(25)
AS 
SET NOCOUNT ON;
SELECT BRAND_NAME,BRAND_ID FROM BRND_BRAND BR WHERE NOT EXISTS(SELECT BRAND_ID FROM
AGREE_BRAND_INCLUDE WHERE AGREEMENT_NO = @AGREEMENT_NO AND BRAND_ID = BR.BRAND_ID) 
AND BR.IsActive = 1 AND BR.IsObsolete = 0
AND BR.BRAND_NAME NOT LIKE '%OTHERS%' AND BR.BRAND_NAME NOT LIKE '%BULK%'
GO
-------------------------------------------------------------------------
----------------------------------------------------------------------------------------------	
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Select_BrandpakNameInclude_BrandIDDefined' AND TYPE ='P')
DROP PROCEDURE Sp_Select_BrandpakNameInclude_BrandIDDefined
GO
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Select_BrandpakNameInclude_BrandIDDefined' AND TYPE ='P')
DROP PROCEDURE Usp_Select_BrandpakNameInclude_BrandIDDefined
GO
CREATE PROCEDURE Usp_Select_BrandpakNameInclude_BrandIDDefined
@AGREEMENT_NO VARCHAR(25),
@BRAND_ID VARCHAR(7)
AS
SET NOCOUNT ON;
SELECT ABI.BRANDPACK_ID,BB.BRANDPACK_NAME FROM BRND_BRANDPACK BB 
INNER JOIN AGREE_BRANDPACK_INCLUDE ABI ON BB.BRANDPACK_ID = ABI.BRANDPACK_ID
WHERE ABI.AGREE_BRAND_ID = @AGREEMENT_NO + '' + @BRAND_ID
GO
--EXEC Sp_Select_BrandpakNameInclude_BrandIDDefined
--@AGREEMENT_NO = '231/NI/III/2002',
--@BRAND_ID = '07009'
------------------------------------------------------------------------------
--filter untuk brandpack bila brandid di tentukan dengan agrement no,branpack berdasarkan
--branpack_id di agree_brand_pack include berdasarkan agreement no
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Select_BPNAMENOTIN_AGREE_BRANDPACK_INCLUDE' AND TYPE = 'P')
DROP PROCEDURE Sp_Select_BPNAMENOTIN_AGREE_BRANDPACK_INCLUDE
GO
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Select_BPNAMENOTIN_AGREE_BRANDPACK_INCLUDE' AND TYPE = 'P')
DROP PROCEDURE Usp_Select_BPNAMENOTIN_AGREE_BRANDPACK_INCLUDE
GO
CREATE PROCEDURE Usp_Select_BPNAMENOTIN_AGREE_BRANDPACK_INCLUDE
@AGREEMENT_NO VARCHAR(25),
@BRAND_ID VARCHAR(7)
AS
SET NOCOUNT ON;
SELECT BRANDPACK_ID,BRANDPACK_NAME  FROM BRND_BRANDPACK BB WHERE
BRAND_ID = @BRAND_ID 
AND IsActive = 1 AND (IsObsolete = 0 OR IsObsolete IS NULL)
AND NOT EXISTS(SELECT BRANDPACK_ID FROM AGREE_BRANDPACK_INCLUDE WHERE BRANDPACK_ID = BB.BRANDPACK_ID AND AGREEMENT_NO = @AGREEMENT_NO)
GO
--exec Usp_Select_BPNAMENOTIN_AGREE_BRANDPACK_INCLUDE @AGREEMENT_NO = 'AG_123_TEST', @BRAND_ID = '00604'
--DELETE FROM AGREE_BRANDPACK_INCLUDE WHERE AGREE_BRANDPACK_ID = 'AG_123_TEST00604040LD'


---------------------------------------------------------------------------------
--PROCEDURE UNTUK MENGECEK REFERENSI BRANDPACK_INCLUDE DI TABLE ANAK MRKT_BRANDPACK_DISTRIBUTOR
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Select_AGREE_BRANDPACKID_MRKT_BRANDPACKID_DISTRIBUTOR' AND TYPE = 'P')
DROP PROCEDURE Sp_Select_AGREE_BRANDPACKID_MRKT_BRANDPACKID_DISTRIBUTOR
GO
CREATE PROCEDURE
Sp_Select_AGREE_BRANDPACKID_MRKT_BRANDPACKID_DISTRIBUTOR
@AGREEMENT_NO VARCHAR(25),
@BRANDPACK_ID VARCHAR(14)
AS
SET NOCOUNT ON;
SELECT ISNULL((SELECT 1 WHERE EXISTS(SELECT MBD.AGREE_BRANDPACK_ID  FROM MRKT_BRANDPACK_DISTRIBUTOR MBD
INNER JOIN AGREE_BRANDPACK_INCLUDE ABI ON MBD.AGREE_BRANDPACK_ID = ABI.AGREE_BRANDPACK_ID
WHERE ABI.AGREEMENT_NO = @AGREEMENT_NO AND ABI.BRANDPACK_ID = @BRANDPACK_ID)),0);
GO
--EXEC Sp_Select_AGREE_BRANDPACKID_MRKT_BRANDPACKID_DISTRIBUTOR @BRANDPACK_ID = '77264100GD',@AGREEMENT_NO = '0242/NI/II/2008.19'
--SELECT MBD.AGREE_BRANDPACK_ID  FROM MRKT_BRANDPACK_DISTRIBUTOR MBD
--INNER JOIN AGREE_BRANDPACK_INCLUDE ABI ON MBD.AGREE_BRANDPACK_ID = ABI.AGREE_BRANDPACK_ID
--WHERE ABI.AGREEMENT_NO = '0242/NI/II/2008.19' AND ABI.BRANDPACK_ID ='77264100GD';
--SELECT * FROM MRKT_BRANDPACK_DISTRIBUTOR WHERE AGREE_BRANDPACK_ID  = '0242/NI/II/2008.1977264100GD';
--SELECT * FROM MRKT_BRANDPACK WHERE PROG_BRANDPACK_ID = '1296/NI/VII/1977264100GD';
--89/ATU/VII/2019A-0004012789/ATU/VII/2019A77264100GD

--SELECT * FROM MRKT_DISC_HISTORY WHERE PROG_BRANDPACK_DIST_ID = '1296/NI/VII/1977264100GDZAI002IDR';
--SELECT * FROM ORDR_OA_BRANDPACK_DISC WHERE MRKT_DISC_HIST_ID = '1296/NI/VII/1977264100GDZAI002IDR'
------------------------------------------------------------------------------------
--PROCEDURE UNTUK MENGECEK REFERENSI AGREE_BRANDPACK_INCLUDE DI TABLE  AGREE_DISC_HISTORY
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Select_AGREE_BRANDPACKID_AGREE_DISC_HISTORY' AND TYPE = 'P')
DROP PROCEDURE 
Sp_Select_AGREE_BRANDPACKID_AGREE_DISC_HISTORY
GO
CREATE PROCEDURE Sp_Select_AGREE_BRANDPACKID_AGREE_DISC_HISTORY
@AGREEMENT_NO VARCHAR(25),
@BRANDPACK_ID VARCHAR(14)
AS
SET NOCOUNT ON;
DECLARE @V_AGREE_BRANDPACK_ID VARCHAR(50);
SET @V_AGREE_BRANDPACK_ID = @AGREEMENT_NO + '' + @BRANDPACK_ID;
BEGIN
  SELECT ISNULL((SELECT 1 
  WHERE EXISTS(
                SELECT AGREE_BRANDPACK_ID FROM AGREE_DISC_HISTORY
                WHERE AGREE_BRANDPACK_ID = @V_AGREE_BRANDPACK_ID
               ) 
     OR EXISTS(SELECT AGREE_BRANDPACK_ID FROM BRND_BRANDPACK_SAVING 
               WHERE AGREE_BRANDPACK_ID = @V_AGREE_BRANDPACK_ID
               )),0);
END
GO
---------------------------------------------------------------------------------
-- PROCEDURE UNTUK MENYELEK BRANDID(BRANDNAME) YANG BELUM DI COMBINED BERDASARKAN AGREEMENT
--UNUTUK MENGISI ITEM DI COMBO FIRST DAN SECOND BRAND 
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_SelectBrand_NOTINCOMBAGREE_BRAND_INCLUDE' AND TYPE = 'P')
DROP PROCEDURE Sp_SelectBrand_NOTINCOMBAGREE_BRAND_INCLUDE
GO
CREATE PROCEDURE Sp_SelectBrand_NOTINCOMBAGREE_BRAND_INCLUDE
@AGREEMENT_NO VARCHAR(25)
AS
SELECT BRAND_NAME,BRAND_ID FROM BRAND WHERE BRAND_ID IN (SELECT BRAND_ID FROM AGREE_BRAND_INCLUDE WHERE AGREEMENT_NO = @AGREEMENT_NO 
AND COMB_AGREE_BRAND_ID IS NULL)
GO
----------------------------------------------------------------------------------
--PROCEDURE UNTUK MEMILIH CONBINED_BRAND
--UNTUK MEMVIEW DATA DI GRID EX EXECUTE DULU PROCEDURE INI
--SETELAH DI EXECUTE DIATAS BIKIN ROW YANG BERDASARKAN BRAND_NAME(DARI BRAND_ID),JUMLAHKAN Q1,Q2..//S1.S2 SEBAGAI TOTAL DI COLUMN KEDUA
--BIKIN SATU COLUMN ALIAS DI DATATABLE DENGAN NAMA BRAND_NAME DAN ISINYA BRAND_NAME
------------------------------------------------------------------------------------
--PROCEDURE UNTUK MEMBUAT COLUMN COMBINED BERDASARKAN BRAND_ID(COMB_AGREE_BRAND_ID = AGREE_BRAND_ID)
-- LALU PILIH BRAND_IDNYA DENGAN MENYAMAKAN COMB_AGREE_BRAND_ID DENGAN AGREE_BRAND_ID YANG DI EXECUTE DIATAS
--SESUDAH DI PILIH BRAND_ID TINGGAL DICARI BRAND_NAME DARI BRAND_ID TERSEBUT
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Select_CABID_ABID' AND TYPE = 'P')
DROP PROCEDURE Sp_Select_CABID_ABID
GO
CREATE PROCEDURE Sp_Select_CABID_ABID
@AGREEMENT_NO VARCHAR(25)
AS
SELECT AGREE_BRAND_ID,COMB_AGREE_BRAND_ID FROM AGREE_BRAND_INCLUDE
WHERE AGREEMENT_NO = @AGREEMENT_NO AND COMB_AGREE_BRAND_ID IS NOT NULL
GO
-----------------------------------------------
--PROCEDURE UNTUK ME LOOPING BRAND_NAME,BRAND_ID,DENGAN VALUE DARI KEY HASHTABEL UNTUK MENGISI
-- TREEVIEW NODE PARENT NODE DENGAN NODE FIRSTBRAND + SECONDBRAND
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Select_BrandID_WITHKEYFROMHASHTABLE' AND TYPE = 'P')
DROP PROCEDURE Sp_Select_BrandID_WITHKEYFROMHASHTABLE
GO
CREATE PROCEDURE Sp_Select_BrandID_WITHKEYFROMHASHTABLE
@AGREEMENT_NO VARCHAR(25),
@AGREE_BRAND_ID VARCHAR(32)
AS
SELECT BRAND_ID,BRAND_NAME FROM BRND_BRAND WHERE  BRAND_ID = (SELECT BRAND_ID FROM AGREE_BRAND_INCLUDE
WHERE AGREE_BRAND_ID= @AGREE_BRAND_ID AND AGREEMENT_NO = @AGREEMENT_NO)
GO
----------------------------------------------------------------------------
--PROCEDURE UNTUK MENYELEKSI BRANDPACK_NAME DARI AGREE_BRANDPACK_INCLUDE
-- DENGAN AGREE_BRAND_ID DI TENTUKAN DAN AGREEMENT_NO JUGA BRANDPACK_DIANTARA
-- BRANDPACK_ID YANG ADA DI BRANDPACK_INCLUDE
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Select_BPNAME_INCLUDE_INABINCLUDE' AND TYPE = 'P')
DROP PROCEDURE Sp_Select_BPNAME_INCLUDE_INABINCLUDE
GO
CREATE PROCEDURE Sp_Select_BPNAME_INCLUDE_INABINCLUDE
@AGREEMENT_NO VARCHAR(25),
@AGREE_BRAND_ID VARCHAR(32),
@BRAND_ID VARCHAR(7)
AS
SELECT BRANDPACK_NAME,BRANDPACK_ID FROM BRND_BRANDPACK WHERE BRAND_ID = @BRAND_ID
AND BRANDPACK_ID IN(SELECT BRANDPACK_ID FROM AGREE_BRANDPACK_INCLUDE WHERE AGREEMENT_NO = @AGREEMENT_NO
AND AGREE_BRAND_ID = @AGREE_BRAND_ID)
GO
--------------------------------------------------------------------------------
--PROCEDURE UNTUK MENYELEK VIEW TARGET_QUANTITY JIKA ADA DAN Q1,Q2,Q3,Q4
-- BERDASARKAN PARAMETER AGREEMENT_NO DAN AGREE_BRAND_ID
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_SelectQQTY_FROM_ABI' AND TYPE = 'P')
DROP PROCEDURE Sp_SelectQQTY_FROM_ABI
GO
--CREATE PROCEDURE Sp_SelectQQTY_FROM_ABI
--@AGREEMENT_NO VARCHAR(25),
--@COMB_AGREE_BRAND_ID VARCHAR(32)
--AS
--SELECT BRAND_NAME,TARGET_Q1,TARGET_Q2,TARGET_Q3,TARGET_Q4 FROM VIEW_AGREE_BRAND_INCLUDE WHERE AGREEMENT_NO =@AGREEMENT_NO
--AND [ID] = @COMB_AGREE_BRAND_ID
--GO
---------------------------------------------------------------------------------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_SelectSQTY_FROM_ABI' AND TYPE = 'P')
-- PROCEDURE UNTUK MENYELEKSI VIEW TARGET_QUANTITY S1 S2,BERDASARKAN PARAMETER AGREEMENT_NO DAN AGREE_BRAND_ID
DROP PROCEDURE Sp_SelectSQTY_FROM_ABI
GO
--CREATE PROCEDURE Sp_SelectSQTY_FROM_ABI
--@AGREEMENT_NO VARCHAR(25),
--@COMB_AGREE_BRAND_ID VARCHAR(32)
--AS
--SELECT BRAND_NAME,TARGET_S1,TARGET_S2 FROM VIEW_AGREE_BRAND_INCLUDE WHERE AGREEMENT_NO = @AGREEMENT_NO AND
--[ID] = @COMB_AGREE_BRAND_ID
--GO
----------------------------------------------------------------------------------
--PROCEDURE UNTUK  MENGISI ITEM DI COMBOBOX FIRSTSECONDBRAND
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Select_Brand_IN_ABI' AND TYPE = 'P')
DROP PROCEDURE Sp_Select_Brand_IN_ABI
GO
CREATE PROCEDURE Sp_Select_Brand_IN_ABI 
@AGREEMENT_NO VARCHAR(25)
AS
SELECT DISTINCT BRAND_ID,BRAND_NAME FROM VIEW_AGREE_BRAND_INCLUDE WHERE AGREEMENT_NO = @AGREEMENT_NO
AND COMBINED_BRAND IS NULL
GO
-----------------------------------------------------------------------------------
--PROCEDURE UNTUK MENYELEKSI AGREE_BRAND_ID DENGAN PARAMETER AGREEMENT_NO DAN BRAND_ID yang ada di
-- combobox first second
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Select_AGREE_BRAND_IDComboFirst' AND TYPE = 'P')
DROP PROCEDURE Sp_Select_AGREE_BRAND_IDComboFirst
GO
CREATE PROCEDURE Sp_Select_AGREE_BRAND_IDComboFirst
@AGREEMENT_NO VARCHAR(25),
@BRAND_ID VARCHAR(7)
AS
SELECT AGREE_BRAND_ID FROM AGREE_BRAND_INCLUDE WHERE BRAND_ID = @BRAND_ID AND AGREEMENT_NO = @AGREEMENT_NO
GO
--------------------------------------------------------------------------------------
--PROCEDURE UNTUK MENGUPDATE COMBINED_BRAND
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Update_Combined_Brand' AND TYPE = 'P')
DROP PROCEDURE Sp_Update_Combined_Brand
GO
CREATE PROCEDURE Sp_Update_Combined_Brand
@AGREEMENT_NO varchar(25),
@AGREE_BRAND_ID VARCHAR(32),
@COMB_AGREE_BRAND_ID VARCHAR(32)--COMB_AGREE_BRAND_ID ADALAH HASIL DARI AGREE_BRAND_ID YANG DI SELECT DARI PROCEDURE DIATAS
AS
BEGIN
UPDATE AGREE_BRAND_INCLUDE SET COMB_AGREE_BRAND_ID = @COMB_AGREE_BRAND_ID WHERE AGREE_BRAND_ID = @AGREE_BRAND_ID
AND AGREEMENT_NO = @AGREEMENT_NO
END
BEGIN
UPDATE AGREE_BRAND_INCLUDE SET COMB_AGREE_BRAND_ID = @AGREE_BRAND_ID WHERE AGREE_BRAND_ID = @COMB_AGREE_BRAND_ID AND AGREEMENT_NO = @AGREEMENT_NO
END
GO
----------------------------------------------------------------------------------------------
--PROCEDURE UNTUK MENGUPDATE COMBINED_BRAND SUPAYA JADI CLEAR,KARENA BILA MEMAKI PROCEDURE DIATAS AKAN FAIL KARENA
-- DUA PARAMETER ID DI ATAS DI SET DBNULL
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Update_ClearCombined_brand' AND TYPE = 'P')
DROP PROCEDURE Sp_Update_ClearCombined_brand
GO
CREATE PROCEDURE Sp_Update_ClearCombined_brand
@AGREEMENT_NO varchar(25),
@AGREE_BRAND_ID VARCHAR(32),
@IsRoundUp SmallInt
AS
SET NOCOUNT ON;
 IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ACCRUED_HEADER' AND TABLE_TYPE = 'base table')  
 BEGIN  
  IF EXISTS(SELECT AC.ACHIEVEMENT_ID FROM ACCRUED_HEADER AC WHERE((AC.AGREEMENT_NO + '' + AC.BRAND_ID) = @AGREE_BRAND_ID) AND  
             EXISTS(SELECT ACHIEVEMENT_ID FROM ACCRUED_DETAIL WHERE ACHIEVEMENT_ID = AC.ACHIEVEMENT_ID AND CAN_RELEASE = 1))  
   BEGIN  
    IF(@IsRoundUp = 0)  
       BEGIN  
        RAISERROR('BrandPack already generated',16,1); 
        RETURN; 
       END  
    IF EXISTS(SELECT AGREE_BRANDPACK_ID FROM BRND_BRANDPACK_SAVING WHERE AGREE_BRANDPACK_ID
	  IN(SELECT AGREE_BRANDPACK_ID FROM AGREE_BRANDPACK_INCLUDE WHERE AGREE_BRAND_ID = @AGREE_BRAND_ID)
	  AND LEFT_QTY <= DISC_QTY)
       BEGIN
	RAISERROR('BrandPack already generated',16,1); 
	RETURN; 
       END
   END  
 END
UPDATE AGREE_BRAND_INCLUDE SET COMB_AGREE_BRAND_ID = NULL WHERE AGREE_BRAND_ID = @AGREE_BRAND_ID;
GO
------------------------------------------------------------------------------------
--PROCEDURE UNTUK MENGINSERT DATA AGREE_BRAND_INCLUDE
--IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Insert_AGREE_BRAND_ICNLUDE' AND TYPE = 'P')
--DROP PROCEDURE Sp_Insert_AGREE_BRAND_ICNLUDE
--GO
--CREATE PROCEDURE Sp_Insert_AGREE_BRAND_ICNLUDE
--@AGREE_BRAND_ID VARCHAR(32),
--@AGREEMENT_NO VARCHAR(25),
--@BRAND_ID VARCHAR(7),
--@GIVEN_DISC_PCT DECIMAL(10,3),
--@TARGET_Q1 DECIMAL(16,3),
--@TARGET_Q2 DECIMAL(16,3),
--@TARGET_Q3 DECIMAL(16,3),
--@TARGET_Q4 DECIMAL(16,3),
--@TARGET_S1 DECIMAL(16,3),
--@TARGET_S2 DECIMAL(16,3),
--@COMB_AGREE_BRAND_ID VARCHAR(32),
--@CREATE_BY VARCHAR(30)
--AS
--SET NOCOUNT ON;
--INSERT INTO AGREE_BRAND_INCLUDE(AGREE_BRAND_ID,AGREEMENT_NO,BRAND_ID,GIVEN_DISC_PCT,TARGET_Q1,TARGET_Q2,TARGET_Q3,
--TARGET_Q4,TARGET_S1,TARGET_S2,COMB_AGREE_BRAND_ID,CREATE_BY,CREATE_DATE)
--VALUES(@AGREE_BRAND_ID,@AGREEMENT_NO,@BRAND_ID,@GIVEN_DISC_PCT,@TARGET_Q1,@TARGET_Q2,@TARGET_Q3,@TARGET_Q4,
--@TARGET_S1,@TARGET_S2,@COMB_AGREE_BRAND_ID,@CREATE_BY,GETDATE())
--GO
-----------------------------------------------------------------------------------------------------
--PROCEDURE UNTUK MENGUPDATE DATA AGREE_BRAND_INCLUDE
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Update_AGREE_BRAND_ICNLUDE' AND TYPE = 'P')
DROP PROCEDURE Sp_Update_AGREE_BRAND_ICNLUDE
GO
CREATE PROCEDURE Sp_Update_AGREE_BRAND_ICNLUDE
@AGREE_BRAND_ID VARCHAR(32),
@AGREEMENT_NO VARCHAR(25),
@BRAND_ID VARCHAR(7),
@GIVEN_DISC_PCT DECIMAL(16,3),
@TARGET_Q1 DECIMAL(16,3),
@TARGET_Q2 DECIMAL(16,3),
@TARGET_Q3 DECIMAL(16,3),
@TARGET_Q4 DECIMAL(16,3),
@TARGET_S1 DECIMAL(16,3),
@TARGET_S2 DECIMAL(16,3),
@COMB_AGREE_BRAND_ID VARCHAR(32),
@MODIFY_BY VARCHAR(30)
AS
SET NOCOUNT ON;
UPDATE AGREE_BRAND_INCLUDE SET AGREEMENT_NO = @AGREEMENT_NO,BRAND_ID = @BRAND_ID
,GIVEN_DISC_PCT = @GIVEN_DISC_PCT,TARGET_Q1 = @TARGET_Q1,TARGET_Q2 = @TARGET_Q2,
TARGET_Q3 = @TARGET_Q3,TARGET_Q4 = @TARGET_Q4,TARGET_S1 = @TARGET_S1,TARGET_S2 = @TARGET_S2,COMB_AGREE_BRAND_ID 
= @COMB_AGREE_BRAND_ID,MODIFY_BY = @MODIFY_BY,MODIFY_DATE = GETDATE() WHERE AGREE_BRAND_ID = @AGREE_BRAND_ID
GO
---------------------------------------------------------------------------------
--PROCEDURE MUNTUK MENDELETE DATA AGREE_BRAND_INCLUDE
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Delete_AGREE_BRAND_INCLUDE' AND TYPE = 'P')
DROP PROCEDURE Sp_Delete_AGREE_BRAND_INCLUDE
GO
CREATE PROCEDURE Sp_Delete_AGREE_BRAND_INCLUDE
@AGREE_BRAND_ID VARCHAR(32)
AS
DELETE FROM AGREE_BRAND_INCLUDE WHERE AGREE_BRAND_ID = @AGREE_BRAND_ID
GO
------------------------------------------------------------------------- 
-- PROCEDURE UNTUK MENDELETE AGREE_BRANDPACK_INCLUDE
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Delete_AGREE_BRANDPACK_INCLUDE' AND TYPE = 'P')
DROP PROCEDURE Sp_Delete_AGREE_BRANDPACK_INCLUDE
GO
CREATE PROCEDURE Sp_Delete_AGREE_BRANDPACK_INCLUDE
@AGREE_BRANDPACK_ID  VARCHAR(39)
AS
DELETE FROM AGREE_BRANDPACK_INCLUDE WHERE AGREE_BRANDPACK_ID = @AGREE_BRANDPACK_ID
GO
-----------------------------------------------------------------------------------
--PROCEDURE UNTUK MENGINSERT DATA KE AGREE_BRANDPACK_INCLUDE
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Insert_AGREE_BRANDPACK_INCLUDE' AND TYPE = 'P')
DROP PROCEDURE Sp_Insert_AGREE_BRANDPACK_INCLUDE
GO
CREATE PROCEDURE Sp_Insert_AGREE_BRANDPACK_INCLUDE
@AGREE_BRANDPACK_ID VARCHAR(39),
@AGREEMENT_NO VARCHAR(25),
@AGREE_BRAND_ID VARCHAR(32),
@BRANDPACK_ID VARCHAR(14),
@CREATE_BY VARCHAR(30)
AS
SET NOCOUNT ON;
IF NOT EXISTS(SELECT AGREE_BRANDPACK_ID FROM AGREE_BRANDPACK_INCLUDE WHERE AGREE_BRANDPACK_ID = @AGREE_BRANDPACK_ID)
BEGIN
INSERT INTO AGREE_BRANDPACK_INCLUDE(AGREE_BRANDPACK_ID,AGREEMENT_NO,AGREE_BRAND_ID,BRANDPACK_ID,CREATE_BY,CREATE_DATE)
VALUES(@AGREE_BRANDPACK_ID,@AGREEMENT_NO,@AGREE_BRAND_ID,@BRANDPACK_ID,@CREATE_BY,GETDATE());
END
GO
----------------------------------------------------------------------------------
--PROCEDURE UNTUK MENGECEK AGREEMENT TIDAK BOLEH DI RUBAH KARENA AGREE_BRANDPACK_ID
--SUDAH DI GENERATE DI TABEL AGREE_DISC_HISTRORY DENGAN MEREFER AGREEMENT_NO
-- DAN AGREE_BRAND_ID NYA
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Select_Reference_AGREE_BRANDPACK_ID_IN_AGREE_DISC_HISTORY' AND TYPE = 'P')
DROP PROCEDURE Usp_Select_Reference_AGREE_BRANDPACK_ID_IN_AGREE_DISC_HISTORY
GO
CREATE PROCEDURE Usp_Select_Reference_AGREE_BRANDPACK_ID_IN_AGREE_DISC_HISTORY
@AGREEMENT_NO VARCHAR(25)
AS
SET NOCOUNT ON;
SELECT isnull((SELECT 1 WHERE EXISTS(SELECT AGREE_BRANDPACK_ID FROM AGREE_DISC_HISTORY WHERE AGREE_BRANDPACK_ID IN
(SELECT AGREE_BRANDPACK_ID FROM AGREE_BRANDPACK_INCLUDE WHERE AGREEMENT_NO = @AGREEMENT_NO))),0)
GO

---------------------------------------------------------------------------------------]
--PROCEDURE UNTUK  MENGECEK REFERENSI DATA ANAK YANG ADA DI TABEL AGREEMENT
--PADA SAAT DATA MAU DI HAPUS
--REFERENSI DATA PERTAMA DI AGREE_BRAND_INCLUDE
--REFERENSI DATA KEDUA ADA DI TABEL AGREE_BRANDPACK_INCLUDE
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Select_ReferencedData_ABI' AND TYPE = 'P')
DROP PROCEDURE Usp_Select_ReferencedData_ABI
GO
CREATE PROCEDURE Usp_Select_ReferencedData_ABI
@AGREEMENT_NO VARCHAR(25)
AS
SET NOCOUNT ON
SELECT ISNULL((SELECT 1 WHERE EXISTS(SELECT AGREEMENT_NO FROM AGREE_BRAND_INCLUDE WHERE AGREEMENT_NO = @AGREEMENT_NO)),0)
GO
---------------------------------------------------------------------------------------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Select_ReferencedData_ABPI'AND TYPE = 'P')
DROP PROCEDURE Sp_Select_ReferencedData_ABPI
GO
----------------------------------------------------------------------------------------
--PROCEDURE UNTUK MENDELETE DATA AGREEMENT_
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Delete_Agreement' AND TYPE = 'P')
DROP PROCEDURE Sp_Delete_Agreement
GO
CREATE PROCEDURE Sp_Delete_Agreement
@AGREEMENT_NO VARCHAR(25)
AS
DELETE FROM AGREE_AGREEMENT WHERE AGREEMENT_NO = @AGREEMENT_NO
GO
---------------------------------------------------------------------------------------
--PROCEDURE UNTUK MENGECEK KEBERADAAN DATA AGREEMENT_NO DI TABEL AGREEMENT
--DATA AGREEMENT HARUS UNIK
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Check_AGREEMENT_NO' AND TYPE = 'P')
DROP PROCEDURE Sp_Check_AGREEMENT_NO
GO
CREATE PROCEDURE Sp_Check_AGREEMENT_NO
@AGREEMENT_NO VARCHAR(25)
AS
SET NOCOUNT ON;
SELECT ISNULL((SELECT 1 WHERE EXISTS(SELECT AGREEMENT_NO FROM AGREE_AGREEMENT
               WHERE AGREEMENT_NO = RTRIM(@AGREEMENT_NO))),0);
GO
--------------------------------------------------------------------------
--PROCEDURE UNTUK MENDELETE DATA AGREE_PROGRESSIVE DISCOUNT
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Delete_AGREE_PROGRESSIVE_DISCOUNT')
DROP PROCEDURE Sp_Delete_AGREE_PROGRESSIVE_DISCOUNT
GO
CREATE PROCEDURE Sp_Delete_AGREE_PROGRESSIVE_DISCOUNT
@AGREEMENT_NO VARCHAR(25)
AS
DELETE FROM AGREE_PROGRESSIVE_DISCOUNT WHERE AGREEMENT_NO = @AGREEMENT_NO
GO
--VIEW BUAT AGREE_BRAND_INCLUDE
--SELECT VIEW_AGREE_BRAND_INCLUDE.AGREEMENT_NO,VIEW_AGREE_BRAND_INCLUDE.AGREEMENT_DESC,
--VIEW_AGREE_BRAND_INCLUDE.BRAND_ID,VIEW_AGREE_BRAND_INCLUDE.BRAND_NAME,VIEW_AGREE_BRAND_INCLUDE.START_DATE,
--VIEW_AGREE_BRAND_INCLUDE.END_DATE,VIEW_AGREE_BRAND_INCLUDE.[GIVEN%],VIEW_AGREE_BRAND_INCLUDE.TARGET_Q1,
--VIEW_AGREE_BRAND_INCLUDE.TARGET_Q2,VIEW_AGREE_BRAND_INCLUDE.TARGET_Q3,VIEW_AGREE_BRAND_INCLUDE.TARGET_Q4,
--VIEW_AGREE_BRAND_INCLUDE.TARGET_S1,VIEW_AGREE_BRAND_INCLUDE.TARGET_S2,AGREE_AGREEMENT.TARGET_YEAR
--FROM VIEW_AGREE_BRAND_INCLUDE,AGREE_AGREEMENT
--WHERE VIEW_AGREE_BRAND_INCLUDE.DISTRIBUTOR_ID = 'IBR001IDR' AND VIEW_AGREE_BRAND_INCLUDE.AGREEMENT_NO
--= AGREE_AGREEMENT.AGREEMENT_NO AND VIEW_AGREE_BRAND_INCLUDE.DISTRIBUTOR_ID = AGREE_AGREEMENT.DISTRIBUTOR_ID
--VIEW BUAT DISTRIBUTOR
--SELECT VIEW_DISTRIBUTOR.REGIONAL_AREA,VIEW_DISTRIBUTOR.TERRITORY_AREA,VIEW_DISTRIBUTOR.MANAGER,
--VIEW_DISTRIBUTOR.DISTRIBUTOR_ID,VIEW_DISTRIBUTOR.DISTRIBUTOR_NAME 
--FROM VIEW_DISTRIBUTOR
--WHERE VIEW_DISTRIBUTOR.DISTRIBUTOR_ID IN (SELECT DISTINCT DISTRIBUTOR_ID FROM AGREE_AGREEMENT)
--VIEW BUAT PROJECT DISTRIBUTOR
--SELECT PROJ_REF_NO,PROJECT_NAME,PROJ_REF_DATE,BRANDPACK_NAME,SHIP_TO_DISTRIBUTOR,MAX_ORDER,DISCOUNT,
--START_DATE,END_DATE FROM PROJECT WHERE DISTRIBUTOR_ID = 'ANE002IDR'
--------------------------------------------------------------------------------
--VIEW BUAT BRANDPACK_SAVING

IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_GetView_BrandPack_Saving' AND TYPE = 'P')
DROP PROCEDURE Usp_GetView_BrandPack_Saving 
GO
CREATE PROCEDURE Usp_GetView_BrandPack_Saving
@AGREEMENT_NO VARCHAR(25),
@DISTRIBUTOR_ID VARCHAR(10),
@QSY_FLAG VARCHAR(2)
AS
IF (@QSY_FLAG IS NULL)
    BEGIN
	SELECT BRND_BRANDPACK_SAVING.BRND_B_S_ID,BRND_BRANDPACK.BRANDPACK_NAME,BRND_BRANDPACK_SAVING.QSY_FLAG,BRND_BRANDPACK_SAVING.TOTAL_PO_QTY,
	BRND_BRANDPACK_SAVING.TOTAL_PO_AMOUNT,BRND_BRANDPACK_SAVING.AGREE_DISC_PCT,BRND_BRANDPACK_SAVING.DISC_QTY,
	BRND_BRANDPACK_SAVING.PRICE_PERQTY,
	BRND_BRANDPACK_SAVING.DISC_AMOUNT,BRND_BRANDPACK_SAVING.RELEASE_QTY,BRND_BRANDPACK_SAVING.RELEASE_AMOUNT,
	BRND_BRANDPACK_SAVING.LEFT_QTY,BRND_BRANDPACK_SAVING.LEFT_AMOUNT
	FROM BRND_BRANDPACK,AGREE_BRANDPACK_INCLUDE,AGREE_AGREEMENT,BRND_BRANDPACK_SAVING
	WHERE BRND_BRANDPACK_SAVING.AGREE_BRANDPACK_ID = AGREE_BRANDPACK_INCLUDE.AGREE_BRANDPACK_ID
	AND AGREE_BRANDPACK_INCLUDE.BRANDPACK_ID = BRND_BRANDPACK.BRANDPACK_ID
	AND AGREE_BRANDPACK_INCLUDE.AGREEMENT_NO = AGREE_AGREEMENT.AGREEMENT_NO 
	AND AGREE_AGREEMENT.AGREEMENT_NO = @AGREEMENT_NO AND BRND_BRANDPACK_SAVING.DISTRIBUTOR_ID = @DISTRIBUTOR_ID
    END
ELSE
     BEGIN
	SELECT BRND_BRANDPACK_SAVING.BRND_B_S_ID,BRND_BRANDPACK.BRANDPACK_NAME,BRND_BRANDPACK_SAVING.QSY_FLAG,BRND_BRANDPACK_SAVING.TOTAL_PO_QTY,
	BRND_BRANDPACK_SAVING.TOTAL_PO_AMOUNT,BRND_BRANDPACK_SAVING.AGREE_DISC_PCT,BRND_BRANDPACK_SAVING.DISC_QTY,
	BRND_BRANDPACK_SAVING.PRICE_PERQTY,
	BRND_BRANDPACK_SAVING.DISC_AMOUNT,BRND_BRANDPACK_SAVING.RELEASE_QTY,BRND_BRANDPACK_SAVING.RELEASE_AMOUNT,
	BRND_BRANDPACK_SAVING.LEFT_QTY,BRND_BRANDPACK_SAVING.LEFT_AMOUNT
	FROM BRND_BRANDPACK,AGREE_BRANDPACK_INCLUDE,AGREE_AGREEMENT,BRND_BRANDPACK_SAVING
	WHERE BRND_BRANDPACK_SAVING.AGREE_BRANDPACK_ID = AGREE_BRANDPACK_INCLUDE.AGREE_BRANDPACK_ID
	AND AGREE_BRANDPACK_INCLUDE.BRANDPACK_ID = BRND_BRANDPACK.BRANDPACK_ID
	AND AGREE_BRANDPACK_INCLUDE.AGREEMENT_NO = AGREE_AGREEMENT.AGREEMENT_NO 
	AND AGREE_AGREEMENT.AGREEMENT_NO = @AGREEMENT_NO AND BRND_BRANDPACK_SAVING.QSY_FLAG = @QSY_FLAG
	AND BRND_BRANDPACK_SAVING.DISTRIBUTOR_ID = @DISTRIBUTOR_ID
     END
GO
--EXEC Usp_GetView_BrandPack_Saving
---@AGREEMENT_NO = 'WSAD',
--@QSY_FLAG = 'Q1'
-----------------------VIEW BUAT BRANDPACK_SAVING UNTUK MENGECEK LEFT /RELEASE AMOUNTNYA
---------------------------------------------------------------------------------------------
--PROCEDURE UNTUK MENGGENERATE DATA AGREEMENT_BRANDPACK
--------------------------------------------------------------------------------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_INSERT_BRND_BRANDPACK_SAVING' AND TYPE = 'P')
DROP PROCEDURE Usp_INSERT_BRND_BRANDPACK_SAVING
GO
CREATE PROCEDURE Usp_INSERT_BRND_BRANDPACK_SAVING
@BRND_B_S_ID VARCHAR(60),
@DISTRIBUTOR_ID VARCHAR(10),
@AGREE_BRANDPACK_ID VARCHAR(39),
@QSY_FLAG VarCHAR(2),
@TOTAL_PO_QTY DECIMAL(16,3),
@TOTAL_PO_AMOUNT DECIMAL(16,3),
@AGREE_DISC_PCT DECIMAL(16,3),
@DISC_QTY DECIMAL(16,3),
@PRICE_PERQTY DECIMAL(16,3),
@DISC_AMOUNT DECIMAL(16,3),
@RELEASE_QTY DECIMAL(16,3),
@RELEASE_AMOUNT DECIMAL(16,3),
@LEFT_QTY DECIMAL(16,3),
@LEFT_AMOUNT DECIMAL(16,3),
@CREATE_BY VARCHAR(50)
AS
SET NOCOUNT ON;
BEGIN
    INSERT INTO BRND_BRANDPACK_SAVING(BRND_B_S_ID,DISTRIBUTOR_ID,AGREE_BRANDPACK_ID,QSY_FLAG,TOTAL_PO_QTY,
    TOTAL_PO_AMOUNT,AGREE_DISC_PCT,DISC_QTY,PRICE_PERQTY,DISC_AMOUNT,RELEASE_QTY,RELEASE_AMOUNT,LEFT_QTY,
    LEFT_AMOUNT,CREATE_BY,CREATE_DATE)
    VALUES(@BRND_B_S_ID,@DISTRIBUTOR_ID,@AGREE_BRANDPACK_ID,RTRIM(@QSY_FLAG),@TOTAL_PO_QTY,@TOTAL_PO_AMOUNT,
    @AGREE_DISC_PCT,@DISC_QTY,@PRICE_PERQTY,@DISC_AMOUNT,@RELEASE_QTY,@RELEASE_AMOUNT,@LEFT_QTY,@LEFT_AMOUNT,
    @CREATE_BY,GETDATE())  	
END
GO
---------------------------------------------------------------------------------

---REVISI
--PROCEDURE UNTUK MENGUPDATE DATA BRANDPACK_SAVING
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME  = 'Usp_Update_BRND_BRANDPACK_SAVING' AND TYPE = 'P')
DROP PROCEDURE Usp_Update_BRND_BRANDPACK_SAVING
GO
--CREATE PROCEDURE Usp_Update_BRND_BRANDPACK_SAVING
--@BRND_B_S_ID VARCHAR(60),
--@OA_BRANDPACK_DISC_QTY VARCHAR(10),
--@MODIFY_BY VARCHAR(30),
--@ISRELEASE BIT
--AS
--BEGIN
--DECLARE @V_PRICE_PERQTY FLOAT,@V_LEFT_QTY FLOAT,@V_RELEASE_QTY FLOAT,@V_AMOUNT_LEFT_QTY FLOAT,@V_AMOUNT_RELEASE_QTY FLOAT
--SET @V_PRICE_PERQTY = CAST((SELECT PRICE_PERQTY FROM BRND_BRANDPACK_SAVING WHERE BRND_B_S_ID = @BRND_B_S_ID) AS FLOAT)
  --  IF (@ISRELEASE = 1)
	--BEGIN
	  --   SET @V_LEFT_QTY = CAST((SELECT LEFT_QTY FROM BRND_BRANDPACK_SAVING WHERE BRND_B_S_ID = @BRND_B_S_ID)AS FLOAT) - CAST((@OA_BRANDPACK_DISC_QTY) AS float)
	    -- SET @V_AMOUNT_LEFT_QTY = @V_PRICE_PERQTY * @V_LEFT_QTY
	    -- SET @V_RELEASE_QTY = CAST((SELECT RELEASE_QTY FROM BRND_BRANDPACK_SAVING WHERE BRND_B_S_ID = @BRND_B_S_ID)AS FLOAT) + CAST((@OA_BRANDPACK_DISC_QTY) AS float)
	     --SET @V_AMOUNT_RELEASE_QTY = @V_PRICE_PERQTY * @V_RELEASE_QTY
	--END 
    --ELSE
	--BEGIN
	  --   SET @V_LEFT_QTY = CAST((SELECT LEFT_QTY FROM BRND_BRANDPACK_SAVING WHERE BRND_B_S_ID = @BRND_B_S_ID)AS FLOAT) + CAST((@OA_BRANDPACK_DISC_QTY) AS float)
	    -- SET @V_AMOUNT_LEFT_QTY = @V_PRICE_PERQTY * @V_LEFT_QTY
	    -- SET @V_RELEASE_QTY = CAST((SELECT RELEASE_QTY FROM BRND_BRANDPACK_SAVING WHERE BRND_B_S_ID = @BRND_B_S_ID)AS FLOAT) - CAST((@OA_BRANDPACK_DISC_QTY) AS float)
	     --SET @V_AMOUNT_RELEASE_QTY = @V_PRICE_PERQTY * @V_RELEASE_QTY
	--END

--UPDATE BRND_BRANDPACK_SAVING SET LEFT_QTY = @V_LEFT_QTY,LEFT_AMOUNT = @V_AMOUNT_LEFT_QTY,RELEASE_QTY = @V_RELEASE_QTY,
--RELEASE_AMOUNT = @V_AMOUNT_RELEASE_QTY,MODIFY_BY = @MODIFY_BY,MODIFY_DATE = GETDATE() WHERE BRND_B_S_ID = @BRND_B_S_ID 
--END
--GO
---------------------------PROCEDURE UNTUK MENAMPILKAN DATA BRAND DISTRIBUTOR DI FORM DISTRIBUTOR STORY----
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Create_View_Agreement_Program_Distributor_History' AND TYPE = 'P')
DROP PROCEDURE Usp_Create_View_Agreement_Program_Distributor_History
GO
CREATE PROCEDURE Usp_Create_View_Agreement_Program_Distributor_History
@DISTRIBUTOR_ID VARCHAR(10)
AS
SET NOCOUNT ON;
SELECT AGREEMENT_NO,AGREEMENT_DESC,BRAND_ID,BRAND_NAME,START_DATE,END_DATE,[GIVEN%],TARGET_Q1,
TARGET_Q2,TARGET_Q3,TARGET_Q4,TARGET_S1,TARGET_S2
FROM VIEW_AGREE_BRAND_INCLUDE WHERE DISTRIBUTOR_ID = @DISTRIBUTOR_ID
--AND START_DATE >= @START_DATE AND END_DATE <= @END_DATE ; 
GO

--SELECT VIEW_AGREE_BRAND_INCLUDE.AGREEMENT_NO,VIEW_AGREE_BRAND_INCLUDE.AGREEMENT_DESC,VIEW_AGREE_BRAND_INCLUDE.BRAND_ID,
--VIEW_AGREE_BRAND_INCLUDE.BRAND_NAME,VIEW_AGREE_BRAND_INCLUDE.START_DATE,VIEW_AGREE_BRAND_INCLUDE.END_DATE,VIEW_AGREE_BRAND_INCLUDE.[GIVEN%],
--VIEW_AGREE_BRAND_INCLUDE.TARGET_Q1,VIEW_AGREE_BRAND_INCLUDE.TARGET_Q2,VIEW_AGREE_BRAND_INCLUDE.TARGET_Q3,
--VIEW_AGREE_BRAND_INCLUDE.TARGET_Q4,VIEW_AGREE_BRAND_INCLUDE.TARGET_S1, VIEW_AGREE_BRAND_INCLUDE.TARGET_S2
-- FROM VIEW_AGREE_BRAND_INCLUDE, AGREE_AGREEMENT,DISTRIBUTOR_AGREEMENT
--WHERE VIEW_AGREE_BRAND_INCLUDE.DISTRIBUTOR_ID = @DISTRIBUTOR_ID AND VIEW_AGREE_BRAND_INCLUDE.AGREEMENT_NO
-- = AGREE_AGREEMENT.AGREEMENT_NO AND VIEW_AGREE_BRAND_INCLUDE.DISTRIBUTOR_ID = DISTRIBUTOR_AGREEMENT.DISTRIBUTOR_ID 
--AND AGREE_AGREEMENT.AGREEMENT_NO = DISTRIBUTOR_AGREEMENT.AGREEMENT_NO
--GO

-----------------------------------------------------------------------------------------------

IF EXISTS(SELECT NAME FROM SYS.OBJECTS WHERE NAME = 'Usp_Get_Schem_Distributor_History_Other' AND TYPE = 'P')
DROP PROCEDURE Usp_Get_Schem_Distributor_History_Other
GO
CREATE PROCEDURE Usp_Get_Schem_Distributor_History_Other
@DISTRIBUTOR_ID VARCHAR(10)
AS
SET NOCOUNT ON;
IF EXISTS(SELECT GRP_ID,GRP_NAME FROM DIST_GROUP)
	BEGIN
		SELECT BDL.BRAND_ID,BR.BRAND_NAME,BD.APPLY_DATE,APPLY_TO = 'ALL DISTRIBUTOR',BD.PROGRAM_DESC,BD.DISC_PROG_DESC
		FROM BRND_DISC_HEADER BD INNER JOIN BRND_DISC_LIST_BRAND BDL ON BDL.FKApp = BD.IDApp 
		INNER JOIN BRND_BRAND BR ON BR.BRAND_ID = BDL.BRAND_ID 
		WHERE BD.APPLY_TO = 'AL' 
		UNION

		 SELECT BDL.BRAND_ID,BR.BRAND_NAME,BD.APPLY_DATE,APPLY_TO = 'CERTAIN DISTRIBUTOR',BD.PROGRAM_DESC,BD.DISC_PROG_DESC
		FROM BRND_DISC_HEADER BD INNER JOIN BRND_DISC_LIST_BRAND BDL ON BDL.FKApp = BD.IDApp 
		INNER JOIN BRND_BRAND BR ON BR.BRAND_ID = BDL.BRAND_ID INNER JOIN DIST_DISC_BRAND_LIST DDBL
		ON DDBL.FKApp = BD.IDApp
		WHERE BD.APPLY_TO = 'CD' AND DDBL.DISTRIBUTOR_ID = @DISTRIBUTOR_ID  
		UNION

		 SELECT BDL.BRAND_ID,BR.BRAND_NAME,BD.APPLY_DATE,APPLY_TO = 'GROUP DISTRIBUTOR',BD.PROGRAM_DESC,BD.DISC_PROG_DESC
		FROM BRND_DISC_HEADER BD INNER JOIN BRND_DISC_LIST_BRAND BDL ON BDL.FKApp = BD.IDApp 
		INNER JOIN BRND_BRAND BR ON BR.BRAND_ID = BDL.BRAND_ID INNER JOIN DIST_GROUP_BRND_LIST DGBL ON DGBL.FKDisc = BD.IDApp
		INNER JOIN DIST_GROUP_LIST DGL ON DGL.GRP_ID = DGBL.FKGroup
		WHERE BD.APPLY_TO = 'GD' AND DGL.DISTRIBUTOR_ID = DISTRIBUTOR_ID  
	END
ELSE 
	BEGIN
		SELECT BDL.BRAND_ID,BR.BRAND_NAME,BD.APPLY_DATE,APPLY_TO = 'ALL DISTRIBUTOR',BD.PROGRAM_DESC,BD.DISC_PROG_DESC
		FROM BRND_DISC_HEADER BD INNER JOIN BRND_DISC_LIST_BRAND BDL ON BDL.FKApp = BD.IDApp 
		INNER JOIN BRND_BRAND BR ON BR.BRAND_ID = BDL.BRAND_ID 
		WHERE BD.APPLY_TO = 'AL' 
		UNION

		SELECT BDL.BRAND_ID,BR.BRAND_NAME,BD.APPLY_DATE,APPLY_TO = 'CERTAIN DISTRIBUTOR',BD.PROGRAM_DESC,BD.DISC_PROG_DESC
		FROM BRND_DISC_HEADER BD INNER JOIN BRND_DISC_LIST_BRAND BDL ON BDL.FKApp = BD.IDApp 
		INNER JOIN BRND_BRAND BR ON BR.BRAND_ID = BDL.BRAND_ID INNER JOIN DIST_DISC_BRAND_LIST DDBL
		ON DDBL.FKApp = BD.IDApp
		WHERE BD.APPLY_TO = 'CD' AND DDBL.DISTRIBUTOR_ID = @DISTRIBUTOR_ID  
	END

--EXEC Usp_Get_Schem_Distributor_History_Other @DISTRIBUTOR_ID = 'MEG001IDR'

---PROCEDURE UNTUK MENGECEK APAKAH ITEM BRANDPACK SUDAH DI INCLUDE UNTUK OLEH SUATU DISTRIBUTOR DALAM AGREEMENT YANG DI HANDLE 
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Check_Existing_BI_By_Distributor' AND TYPE = 'P')
DROP PROCEDURE Usp_Check_Existing_BI_By_Distributor
GO
CREATE PROCEDURE Usp_Check_Existing_BI_By_Distributor
@BRAND_ID VARCHAR(7),
@DISTRIBUTOR_ID VARCHAR(10)
AS
DECLARE @V_GETDATE SMALLDATETIME;
SET @V_GETDATE = (SELECT CAST((
SELECT CAST(MONTH(GETDATE())AS VARCHAR(2)) + '/' + CAST(DAY(GETDATE()) AS VARCHAR(2)) + '/' + CAST(YEAR(GETDATE())AS VARCHAR(4))
)AS SMALLDATETIME));

SELECT ISNULL((SELECT 1 
       WHERE EXISTS(SELECT AGREE_BRAND_ID FROM AGREE_BRAND_INCLUDE ABI INNER JOIN AGREE_AGREEMENT AA
                    ON ABI.AGREEMENT_NO = AA.AGREEMENT_NO 
                    INNER JOIN DISTRIBUTOR_AGREEMENT DA ON AA.AGREEMENT_NO = DA.AGREEMENT_NO
                    WHERE DA.DISTRIBUTOR_ID = @DISTRIBUTOR_ID AND DATEDIFF(DAY,@V_GETDATE,AA.END_DATE) > 31
                    AND ABI.BRAND_ID = @BRAND_ID
                    )),0) OPTION(KEEP PLAN); 
GO
exec Usp_Check_Existing_BI_By_Distributor @BRAND_ID = '00601', @DISTRIBUTOR_ID = 'PAN121000'

----------------------------------------------------------------------------                      
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'TEST_OUTPUT_PROC' AND TYPE = 'P')
DROP PROCEDURE TEST_OUTPUT_PROC
GO
CREATE PROCEDURE TEST_OUTPUT_PROC
@INPUT VARCHAR(14),
@MyOutPut VARCHAR(100) OUTPUT--,
--@OutputInt int OUTPUT
AS
SET @MyOutput = (SELECT BRANDPACK_NAME FROM BRND_BRANDPACK WHERE BRANDPACK_ID = 
@INPUT);
return(1)
go

