
DECLARE @V_PLANTATION_ID VARCHAR(50),@V_DISTRIBUTOR_ID VARCHAR(50),@V_TERRITORY_ID VARCHAR(15),@V_PO_BRANDPACK_ID VARCHAR(100);
DECLARE CURSOR_PO CURSOR FOR
SELECT PO.DISTRIBUTOR_ID,OPB.PO_BRANDPACK_ID,OPB.PLANTATION_ID FROM ORDR_PURCHASE_ORDER PO 
INNER JOIN ORDR_PO_BRANDPACK OPB ON PO.PO_REF_NO = OPB.PO_REF_NO WHERE OPB.PLANTATION_ID IS NOT NULL ;
OPEN CURSOR_PO ;
FETCH NEXT FROM CURSOR_PO INTO @V_DISTRIBUTOR_ID,@V_PO_BRANDPACK_ID,@V_PLANTATION_ID
WHILE (@@FETCH_STATUS = 0)
BEGIN
	SET @V_TERRITORY_ID = (SELECT ISNULL(TERRITORY_ID,'') FROM PLANTATION WHERE PLANTATION_ID = @V_PLANTATION_ID);
	IF(@V_TERRITORY_ID = '')
	BEGIN
		SET @V_TERRITORY_ID = (SELECT TERRITORY_ID FROM DIST_DISTRIBUTOR WHERE DISTRIBUTOR_ID = @V_DISTRIBUTOR_ID) ;
	END	
	UPDATE ORDR_PO_BRANDPACK SET TERRITORY_ID = @V_TERRITORY_ID WHERE PO_BRANDPACK_ID = @V_PO_BRANDPACK_ID ;
     FETCH NEXT FROM CURSOR_PO INTO @V_DISTRIBUTOR_ID,@V_PO_BRANDPACK_ID,@V_PLANTATION_ID
END
CLOSE CURSOR_PO;
DEALLOCATE CURSOR_PO ;
