
--DELETE  FROM  BRND_AVGPRICE;



SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
BEGIN TRANSACTION
GO
DECLARE @V_BrandID VARCHAR(14),@V_BRAND_NAME VARCHAR(100),@V_PRICE_FM FLOAT,@V_PRICE_PL FLOAT;

DECLARE CURSOR_BRAND CURSOR FOR
SELECT PRODUCTS,Price_FM,Price_PL FROM TempPrice;
OPEN CURSOR_BRAND ;
FETCH NEXT FROM CURSOR_BRAND INTO @V_BRAND_NAME,@V_PRICE_FM,@V_PRICE_PL ;
WHILE (@@FETCH_STATUS = 0)
BEGIN
	SET @V_BrandID = (SELECT TOP 1 BRAND_ID FROM BRND_BRAND WHERE BRAND_NAME  = @V_BRAND_NAME + '%' ORDER BY CREATE_DATE DESC);
	IF @V_BrandID IS NULL
		BEGIN
			SET @V_BrandID = (SELECT TOP 1 BRAND_ID FROM BRND_BRAND WHERE BRAND_NAME LIKE '%' + @V_BRAND_NAME + '%' AND IsActive = 1
			 AND IsObsolete = 0 ORDER BY CREATE_DATE DESC);
		END 
	IF (@V_BrandID IS NOT NULL)
	BEGIN
		INSERT INTO BRND_AVGPRICE(BRAND_ID,AVGPRICE,START_PERIODE,CreatedDate,CreatedBy,AVGPRICE_PL)
		VALUES(@V_BrandID,CONVERT(DECIMAL(18,4),ISNULL(@V_PRICE_FM,0)),'08/01/2015',GETDATE(),'System',CONVERT(DECIMAL(18,4),ISNULL(@V_PRICE_PL,0)));
		IF @@ERROR > 0
		BEGIN ROLLBACK TRANSACTION ; RETURN; END 			
	END
	FETCH NEXT FROM CURSOR_BRAND INTO @V_BRAND_NAME,@V_PRICE_FM,@V_PRICE_PL ;
END
CLOSE CURSOR_BRAND;
DEALLOCATE CURSOR_BRAND;
GO

IF @@ERROR > 0
ROLLBACK TRANSACTION;
GO

COMMIT TRANSACTION;
GO
