--SET TRANSACTION ISOLATION LEVEL READ COMMITED; 
--BEGIN TRANSACTION;
--GO

TRUNCATE TABLE GON_SMS;
GO

DELETE FROM GON_DETAIL WHERE SPPB_BRANDPACK_ID = ANY(SELECT SPPB_BRANDPACK_ID FROM SPPB_BRANDPACK 
WHERE OA_BRANDPACK_ID = ANY(
SELECT OA_BRANDPACK_ID FROM ORDR_OA_BRANDPACK_DISC WHERE ACHIEVEMENT_BRANDPACK_ID = ANY(SELECT ACHIEVEMENT_BRANDPACK_ID
FROM ACCRUED_DETAIL WHERE ACHIEVEMENT_ID = ANY(SELECT ACHIEVEMENT_ID FROM ACCRUED_HEADER WHERE AGREEMENT_NO = '118/NI/I/2004.14'))));
GO

--DELETE FROM GON_HEADER
DELETE FROM GON_HEADER WHERE GON_HEADER_ID NOT IN(SELECT GON_HEADER_ID FROM GON_DETAIL);
GO
--DELETE GON_RECEIVED_BACK
DELETE FROM GON_RECEIVED_BACK WHERE (SPPB_NO + '|' + GON_NO)  NOT IN(SELECT GON_HEADER_ID FROM GON_DETAIL);
GO

--INSERT INTO TEMP_DATA
IF EXISTS(SELECT [NAME] FROM tempdb.sys.sysobjects WHERE [name] = '##T_TEMP_OA' AND type = 'U')
BEGIN DROP TABLE tempdb..##T_TEMP_OA; END 
GO
SELECT OA_BRANDPACK_ID INTO TEMPDB..##T_TEMP_OA FROM ORDR_OA_BRANDPACK_DISC WHERE ACHIEVEMENT_BRANDPACK_ID = ANY(SELECT ACHIEVEMENT_BRANDPACK_ID
FROM ACCRUED_DETAIL WHERE ACHIEVEMENT_ID = ANY(SELECT ACHIEVEMENT_ID FROM ACCRUED_HEADER WHERE AGREEMENT_NO = '118/NI/I/2004.14'));
GO

--DELETE SPPB_BRANDPACK
DELETE FROM SPPB_BRANDPACK WHERE OA_BRANDPACK_ID = ANY(
SELECT OA_BRANDPACK_ID FROM ORDR_OA_BRANDPACK_DISC WHERE ACHIEVEMENT_BRANDPACK_ID = ANY(SELECT ACHIEVEMENT_BRANDPACK_ID
FROM ACCRUED_DETAIL WHERE ACHIEVEMENT_ID = ANY(SELECT ACHIEVEMENT_ID FROM ACCRUED_HEADER WHERE AGREEMENT_NO = '118/NI/I/2004.14')));
GO
DELETE FROM SPPB_HEADER WHERE SPPB_NO NOT IN(SELECT SPPB_NO FROM SPPB_BRANDPACK) 
AND SPPB_NO NOT IN(SELECT SPPB_NO FROM ORDR_OTP_HEADER);
GO

--INSERT INTO TEMP
IF EXISTS(SELECT [NAME] FROM tempdb.sys.sysobjects WHERE [name] = '##T_TEMP_OA_DISC' AND type = 'U')
BEGIN DROP TABLE tempdb..##T_TEMP_OA_DISC; END 
GO
SELECT OA_BRANDPACK_DISC_ID INTO TEMPDB..##T_TEMP_OA_DISC FROM ORDR_OA_BRANDPACK_DISC WHERE ACHIEVEMENT_BRANDPACK_ID = ANY(SELECT ACHIEVEMENT_BRANDPACK_ID
FROM ACCRUED_DETAIL WHERE ACHIEVEMENT_ID = ANY(SELECT ACHIEVEMENT_ID FROM ACCRUED_HEADER WHERE AGREEMENT_NO = '118/NI/I/2004.14'));
GO

--DELETE ORDR_OA_BRANDPACK_DISC
DELETE FROM ORDR_OA_BRANDPACK_DISC WHERE ACHIEVEMENT_BRANDPACK_ID = ANY(
SELECT ACHIEVEMENT_BRANDPACK_ID FROM ACCRUED_DETAIL WHERE ACHIEVEMENT_ID = ANY(SELECT ACHIEVEMENT_ID FROM ACCRUED_HEADER WHERE AGREEMENT_NO = '118/NI/I/2004.14'));
GO

--DELETE ORDR_OA_REMAINDING
DELETE FROM ORDR_OA_REMAINDING WHERE ACHIEVEMENT_BRANDPACK_ID = ANY(
SELECT ACHIEVEMENT_BRANDPACK_ID FROM ACCRUED_DETAIL WHERE ACHIEVEMENT_ID = ANY(SELECT ACHIEVEMENT_ID FROM ACCRUED_HEADER WHERE AGREEMENT_NO = '118/NI/I/2004.14'));
GO

--EXECUTE Procedure
DECLARE @V_OA_BRANDPACK_ID VARCHAR(200)
DECLARE CUR_OA CURSOR FOR
SELECT OA_BRANDPACK_ID FROM tempdb..##T_TEMP_OA ;

OPEN CUR_OA;
FETCH NEXT FROM CUR_OA INTO @V_OA_BRANDPACK_ID ;
WHILE (@@FETCH_STATUS = 0)
	BEGIN
		exec Usp_Check_Sum_Mathching_Disc_Qty
		 @OA_BRANDPACK_ID = @V_OA_BRANDPACK_ID,
		 @Discount_Type = 'Agreement_Discount';
		 FETCH NEXT FROM CUR_OA INTO @V_OA_BRANDPACK_ID ;
	END
CLOSE CUR_OA;
DEALLOCATE CUR_OA;
GO

DECLARE @V_OA_BRANDPACK_DISC_ID VARCHAR(300),@V_FKCodeAdjust INT,@V_LEFT_QTY DECIMAL(18,3),@V_DISC_QTY DECIMAL(18,3),@SUM_RELEASE_QTY DECIMAL(18,3);
DECLARE CUR_OA_DISC CURSOR FOR
SELECT CONVERT(VARCHAR(300),OA_BRANDPACK_DISC_ID)AS OA_BRANDPACK_DISC_ID FROM tempdb..##T_TEMP_OA_DISC ;

OPEN CUR_OA_DISC;
FETCH NEXT FROM CUR_OA_DISC INTO @V_OA_BRANDPACK_DISC_ID ;
WHILE (@@FETCH_STATUS = 0)
	BEGIN
		SET @V_FKCOdeAdjust = (SELECT TOP 1 FKApp FROM ADJUSTMENT_TRANS WHERE OA_BRANDPACK_DISC_ID = @V_OA_BRANDPACK_DISC_ID);
        IF (@V_FKCodeAdjust IS NOT NULL)
		BEGIN
			UPDATE ADJUSTMENT_TRANS SET ADJ_DISC_QTY = 0,ModifiedBy  = 'SYSTEM', ModifiedDate = GETDATE() WHERE OA_BRANDPACK_DISC_ID = @V_OA_BRANDPACK_DISC_ID ;
			 SET @V_DISC_QTY = (SELECT ISNULL(QTY,0) FROM ADJUSTMENT_DPD WHERE IDApp = @V_FKCOdeAdjust );
             SET @SUM_RELEASE_QTY = (SELECT ISNULL(SUM(ADJ_DISC_QTY),0) FROM ADJUSTMENT_TRANS WHERE FKApp = @V_FKCOdeAdjust) + (SELECT ISNULL(SUM(LEFT_QTY),0) FROM ORDR_OA_REMAINDING WHERE FkCodeAdjust = @V_FKCOdeAdjust); 
             UPDATE ADJUSTMENT_DPD SET RELEASE_QTY = @SUM_RELEASE_QTY,LEFT_QTY = (@V_DISC_QTY - @SUM_RELEASE_QTY), ModifiedBy  = 'SYSTEM', ModifiedDate = GETDATE() WHERE IDApp = @V_FKCOdeAdjust ;
		END
		 FETCH NEXT FROM CUR_OA_DISC INTO @V_OA_BRANDPACK_DISC_ID ;
	END
CLOSE CUR_OA_DISC;
DEALLOCATE CUR_OA_DISC;
GO


DELETE FROM ACCRUED_DETAIL WHERE ACHIEVEMENT_ID = ANY(SELECT ACHIEVEMENT_ID FROM ACCRUED_HEADER WHERE AGREEMENT_NO = '118/NI/I/2004.14');
DELETE FROM ACCRUED_HEADER WHERE AGREEMENT_NO = '118/NI/I/2004.14';
GO

DROP TABLE tempdb..##T_TEMP_OA_DISC;
DROP TABLE tempdb..##T_TEMP_OA;
GO
--COMMIT TRANSACTION;
--GO


DELETE FROM ACCRUED_DETAIL WHERE ACHIEVEMENT_ID = ANY(SELECT ACHIEVEMENT_ID FROM ACCRUED_HEADER WHERE AGREEMENT_NO = '118/NI/I/2004.14' AND FLAG IN('S2','Y'));
DELETE FROM ACCRUED_HEADER WHERE AGREEMENT_NO = '118/NI/I/2004.14' AND FLAG IN('S2','Y');
GO