Use Nufarm;
GO
DELETE FROM ACCRUED_DETAIL WHERE ACHIEVEMENT_ID = ANY(
SELECT ACHIEVEMENT_ID FROM ACCRUED_HEADER WHERE GP_ID IS NOT NULL);

DELETE FROM ACCRUED_HEADER WHERE GP_ID IS NOT NULL;

SELECT * FROM ACCRUED_HEADER WHERE GP_ID IS NOT NULL AND FLAG = 'Q1'
SELECT * FROM ACCRUED_DETAIL WHERE ACHIEVEMENT_ID = ANY(
SELECT ACHIEVEMENT_ID FROM ACCRUED_HEADER WHERE GP_ID IS NOT NULL AND FLAG = 'Q1');