 SELECT QRY.REGIONAL_ID,REG.REGIONAL_AREA,QRY.TERRITORY_ID,TER.TERRITORY_AREA,QRY.DISTRIBUTOR_ID,DR.DISTRIBUTOR_NAME, '[' + CONVERT(VARCHAR(100),QRY.BRAND_ID) + ']' AS BRAND_ID,BR.BRAND_NAME,QRY.BRANDPACK_ID,BB.BRANDPACK_NAME,
 QRY.TOTAL_PO,QRY.TOTAL_PO_AMOUNT,QRY.TOTAL_INV,QRY.TOTAL_INV_AMOUNT,
 QRY.TOTAL_SHIPMENT,QRY.TOTAL_SHIPMENT_AMOUNT 
 FROM(
 SELECT REGIONAL_ID,TERRITORY_ID,DISTRIBUTOR_ID,BRAND_ID,BRANDPACK_ID,SUM(PO_ORIGINAL_QTY)AS TOTAL_PO,SUM(PO_AMOUNT)AS TOTAL_PO_AMOUNT,
 SUM(INVQTY)AS TOTAL_INV,SUM(INV_AMOUNT)AS TOTAL_INV_AMOUNT,SUM(TOTAL_SHIPMENT)AS TOTAL_SHIPMENT,SUM(TOTAL_SHIPMENT_AMOUNT)AS TOTAL_SHIPMENT_AMOUNT
 FROM(
 SELECT PO.REGIONAL_ID,PO.REGIONAL_AREA,PO.TERRITORY_ID,PO.TERRITORY_AREA,PO.TERRITORY_MANAGER,PO.DISTRIBUTOR_ID,PO.DISTRIBUTOR_NAME,PO.PO_REF_NO,PO.PO_DATE,PO.OA_ID AS OA_REF_NO,  
PO.PROJ_REF_NO,PO.PROJECT_NAME,PO.PLANTATION_NAME,PO.PO_BRANDPACK_ID,PO.BRAND_ID,PO.BRAND_NAME,PO.BRANDPACK_ID,PO.BRANDPACK_NAME,PO.PO_ORIGINAL_QTY,PO.PRICE,PO.PO_AMOUNT,(INV.QTY/ISNULL(OOBD.SPPB_QTY,0)) * PO.PO_ORIGINAL_QTY AS INVQTY,  
INV.UNITPRICE AS INV_PRICE,((INV.QTY/ISNULL(OOBD.SPPB_QTY,0)) * PO.PO_ORIGINAL_QTY) * INV.UNITPRICE AS INV_AMOUNT,PO.CREATED_PO_BY,  
INV.INVNUMBER AS INVOICE_NUMBER,INV.INVDATE,FLAG = CASE WHEN((MONTH(INV.INVDATE) >= 8) AND (MONTH(INV.INVDATE) <= 12))THEN 'S1'   
WHEN (MONTH(INV.INVDATE) = 1) THEN 'S1'   
WHEN((MONTH(INV.INVDATE) >= 2) AND (MONTH(INV.INVDATE) <= 7)) THEN 'S2' ELSE '' END,   
YEAR_PERIODE = CASE WHEN ((MONTH(INV.INVDATE) >= 8) AND (MONTH(INV.INVDATE) <= 12))  THEN (CAST(YEAR(INV.INVDATE) AS VARCHAR(4)) + '-' + CAST((YEAR(INV.INVDATE) + 1) AS VARCHAR(4)))    
                WHEN (MONTH(INV.INVDATE) = 1) THEN (CAST((YEAR(INV.INVDATE) - 1) AS VARCHAR(4)) + '-' + CAST(YEAR(INV.INVDATE) AS VARCHAR(4)))    
                ELSE (CAST((YEAR(INV.INVDATE) - 1) AS VARCHAR(4)) + '-' + CAST(YEAR(INV.INVDATE) AS VARCHAR(4))) END,   
INV.QTY AS TOTAL_SHIPMENT,INV.INV_AMOUNT AS TOTAL_SHIPMENT_AMOUNT,INV.AUDTUSER AS CREATED_INVOICE_BY,DATENAME(MONTH,INV.INVDATE)AS [MONTH]   
FROM  TEMPDB..##T_Invoce_PO_NKusnandar  PO INNER JOIN TEMPDB..##T_INVOICE_2_NKusnandar   INV ON INV.BRANDPACK_ID = PO.BRANDPACK_ID AND ((INV.PONUMBER = PO.PO_REF_NO) OR (INV.REFERENCE = PO.RUN_NUMBER))   
INNER JOIN SPPB_BRANDPACK OOBD ON OOBD.OA_BRANDPACK_ID = PO.OA_BRANDPACK_ID   
WHERE INV.INVDATE >= '2014/08/01' AND INV.INVDATE <= '2015/07/31') QRY1
GROUP BY REGIONAL_ID,TERRITORY_ID,DISTRIBUTOR_ID,BRAND_ID,BRANDPACK_ID 
)QRY 
INNER JOIN DIST_REGIONAL REG ON REG.REGIONAL_ID = QRY.REGIONAL_ID
INNER JOIN TERRITORY TER ON TER.TERRITORY_ID = QRY.TERRITORY_ID
INNER JOIN DIST_DISTRIBUTOR DR ON DR.DISTRIBUTOR_ID = QRY.DISTRIBUTOR_ID
INNER JOIN BRND_BRAND BR ON BR.BRAND_ID = QRY.BRAND_ID
INNER JOIN BRND_BRANDPACK BB ON BB.BRANDPACK_ID = QRY.BRANDPACK_ID
