
--SELECT ACRD.ACHIEVEMENT_BRANDPACK_ID , RELEASE = 
--(SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC WHERE ACHIEVEMENT_BRANDPACK_ID = ACRD.ACHIEVEMENT_BRANDPACK_ID ) +  (SELECT ISNULL(SUM(QTY),0) FROM ORDR_OA_REMAINDING WHERE ACHIEVEMENT_BRANDPACK_ID = ACRD.ACHIEVEMENT_BRANDPACK_ID ) 
--FROM ACCRUED_DETAIL ACRD INNER JOIN ACCRUED_HEADER ACRH ON ACRH.ACHIEVEMENT_ID = ACRD.ACHIEVEMENT_ID 
--INNER JOIN Nufarm.dbo.AGREE_AGREEMENT AA ON ACRH.AGREEMENT_NO = AA.AGREEMENT_NO
--WHERE AA.START_DATE >= '08/01/2014' AND AA.END_DATE <= '07/31/2015' AND ACRH.FLAG IN('Q1','Q2','Q3','Q4') AND ACRH.BRAND_ID IN('006020','00681','00604','0060200','00684','006820','00601');
--GO
 --SELECT ACRH.DISTRIBUTOR_ID,ACRD.BRANDPACK_ID,
	--	         ISNULL(SUM(CASE ACRH.FLAG WHEN 'Q1' THEN ACRD.DISC_QTY END),0)AS QUARTER_1,
	--	         ISNULL(SUM(CASE ACRH.FLAG WHEN 'Q2' THEN ACRD.DISC_QTY END),0)AS QUARTER_2,
	--                 ISNULL(SUM(CASE ACRH.FLAG WHEN 'Q3' THEN ACRD.DISC_QTY  END),0)AS QUARTER_3,
	--	         ISNULL(SUM(CASE ACRH.FLAG WHEN 'Q4' THEN ACRD.DISC_QTY  END),0) AS QUARTER_4,
	--	         ISNULL(SUM(CASE ACRH.FLAG WHEN 'S1' THEN ACRD.DISC_QTY  END),0)AS SEMESTER_1,
	--	         ISNULL(SUM(CASE ACRH.FLAG WHEN 'S2' THEN ACRD.DISC_QTY  END),0)AS SEMESTER_2,
	--	         ISNULL(SUM(CASE ACRH.FLAG WHEN 'Y'  THEN ACRD.DISC_QTY  END),0)AS YEARLY,
	--	         ISNULL(SUM(CASE ACRH.FLAG WHEN 'Q1' THEN ACRD.RELEASE_QTY END),0)AS RELEASE_Q1,
	--	         ISNULL(SUM(CASE ACRH.FLAG WHEN 'Q2' THEN ACRD.RELEASE_QTY END),0)AS RELEASE_Q2,
	--	         ISNULL(SUM(CASE ACRH.FLAG WHEN 'Q3' THEN ACRD.RELEASE_QTY END),0)AS RELEASE_Q3,
	--	         ISNULL(SUM(CASE ACRH.FLAG WHEN 'Q4' THEN ACRD.RELEASE_QTY END),0)AS RELEASE_Q4,
	--	         ISNULL(SUM(CASE ACRH.FLAG WHEN 'S1' THEN ACRD.RELEASE_QTY END),0)AS RELEASE_S1,
	--	         ISNULL(SUM(CASE ACRH.FLAG WHEN 'S2' THEN ACRD.RELEASE_QTY END),0)AS RELEASE_S2,
	--	         ISNULL(SUM(CASE ACRH.FLAG WHEN 'Y'  THEN ACRD.RELEASE_QTY END),0)AS RELEASE_Y,
	--	         ISNULL(SUM(CASE ACRH.FLAG WHEN 'Q1' THEN ACRD.LEFT_QTY END),0)AS LEFT_Q1,
	--	         ISNULL(SUM(CASE ACRH.FLAG WHEN 'Q2' THEN ACRD.LEFT_QTY END),0) AS LEFT_Q2,
	--	         ISNULL(SUM(CASE ACRH.FLAG WHEN 'Q3' THEN ACRD.LEFT_QTY END),0)AS LEFT_Q3,
	--	         ISNULL(SUM(CASE ACRH.FLAG WHEN 'Q4' THEN ACRD.LEFT_QTY END),0) AS LEFT_Q4,
	--	         ISNULL(SUM(CASE ACRH.FLAG WHEN 'S1' THEN ACRD.LEFT_QTY END),0)AS LEFT_S1,
	--	         ISNULL(SUM(CASE ACRH.FLAG WHEN 'S2' THEN ACRD.LEFT_QTY END),0)AS LEFT_S2,
	--	         ISNULL(SUM(CASE ACRH.FLAG WHEN 'Y'  THEN ACRD.LEFT_QTY END),0)AS LEFT_Y

	--	         FROM Nufarm.dbo.ACCRUED_HEADER ACRH INNER JOIN Nufarm.dbo.ACCRUED_DETAIL ACRD
	--                 ON ACRH.ACHIEVEMENT_ID = ACRD.ACHIEVEMENT_ID
	--		 INNER JOIN Nufarm.dbo.AGREE_AGREEMENT AA ON ACRH.AGREEMENT_NO = AA.AGREEMENT_NO
 --                        WHERE AA.START_DATE >= '08/01/2014' AND AA.END_DATE <= '07/31/2015'
	--		 GROUP BY ACRH.DISTRIBUTOR_ID,ACRD.BRANDPACK_ID

--DEFRAG INDEX
Use Nufarm ;
GO
ALTER INDEX ALL ON Nufarm.dbo.ACCRUED_HEADER 
REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON,
              STATISTICS_NORECOMPUTE = ON);
GO
			 ALTER INDEX ALL ON Nufarm.dbo.ACCRUED_DETAIL
REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON,
              STATISTICS_NORECOMPUTE = ON);
GO

ALTER INDEX ALL ON Nufarm.dbo.AGREE_AGREEMENT
REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON,
              STATISTICS_NORECOMPUTE = ON);
GO
			 ALTER INDEX ALL ON Nufarm.dbo.AGREE_BRAND_INCLUDE
REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON,
              STATISTICS_NORECOMPUTE = ON);
GO

			 ALTER INDEX ALL ON Nufarm.dbo.DISTRIBUTOR_AGREEMENT
REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON,
              STATISTICS_NORECOMPUTE = ON);
GO


ALTER INDEX ALL ON Nufarm.dbo.AGREE_BRANDPACK_INCLUDE
REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON,
              STATISTICS_NORECOMPUTE = ON);
GO
			 ALTER INDEX ALL ON Nufarm.dbo.AGREE_PROGRESSIVE_DISCOUNT
REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON,
              STATISTICS_NORECOMPUTE = ON);
GO

ALTER INDEX ALL ON Nufarm.dbo.AGREE_PROG_DISC
REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON,
              STATISTICS_NORECOMPUTE = ON);
GO
			 ALTER INDEX ALL ON Nufarm.dbo.DIST_PLANT_PRICE
REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON,
              STATISTICS_NORECOMPUTE = ON);
GO

			 ALTER INDEX ALL ON Nufarm.dbo.PLANTATION
REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON,
              STATISTICS_NORECOMPUTE = ON);
GO
	
			 ALTER INDEX ALL ON Nufarm.dbo.PLANTATION_GROUP
REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON,
              STATISTICS_NORECOMPUTE = ON);
GO

ALTER INDEX ALL ON Nufarm.dbo.ORDR_OA_BRANDPACK
REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON,
              STATISTICS_NORECOMPUTE = ON);
GO
			 ALTER INDEX ALL ON Nufarm.dbo.ORDR_OA_BRANDPACK_DISC
REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON,
              STATISTICS_NORECOMPUTE = ON);
GO

ALTER INDEX ALL ON Nufarm.dbo.ORDR_ORDER_ACCEPTANCE
REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON,
              STATISTICS_NORECOMPUTE = ON);
GO
			 ALTER INDEX ALL ON Nufarm.dbo.ORDR_PO_BRANDPACK
REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON,
              STATISTICS_NORECOMPUTE = ON);
GO

ALTER INDEX ALL ON Nufarm.dbo.ORDR_PURCHASE_ORDER
REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON,
              STATISTICS_NORECOMPUTE = ON);
GO
			 ALTER INDEX ALL ON Nufarm.dbo.SPPB_BRANDPACK
REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON,
              STATISTICS_NORECOMPUTE = ON);
GO

			 ALTER INDEX ALL ON Nufarm.dbo.SPPB_HEADER
REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON,
              STATISTICS_NORECOMPUTE = ON);
GO


			 ALTER INDEX ALL ON Nufarm.dbo.	GON_DETAIL
REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON,
              STATISTICS_NORECOMPUTE = ON);
GO

			 ALTER INDEX ALL ON Nufarm.dbo.GON_AREA
REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON,
              STATISTICS_NORECOMPUTE = ON);
GO
			 ALTER INDEX ALL ON Nufarm.dbo.GON_TRANSPORTER
REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON,
              STATISTICS_NORECOMPUTE = ON);
GO

			 ALTER INDEX ALL ON Nufarm.dbo.GON_HEADER
REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON,
              STATISTICS_NORECOMPUTE = ON);

GO

			 ALTER INDEX ALL ON Nufarm.dbo.ORDR_OA_REMAINDING
REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON,
              STATISTICS_NORECOMPUTE = ON);
GO
			 ALTER INDEX ALL ON Nufarm.dbo.ADJUSTMENT_TRANS
REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON,
              STATISTICS_NORECOMPUTE = ON);
GO
			 ALTER INDEX ALL ON Nufarm.dbo.ADJUSTMENT_DPD
REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON,
              STATISTICS_NORECOMPUTE = ON);
GO
			 ALTER INDEX ALL ON Nufarm.dbo.GON_RECEIVED_BACK
REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON,
              STATISTICS_NORECOMPUTE = ON);
GO

			 ALTER INDEX ALL ON Nufarm.dbo.PRODUCT_CLASS
REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON,
              STATISTICS_NORECOMPUTE = ON);
GO

			 ALTER INDEX ALL ON Nufarm.dbo.BRND_BRAND
REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON,
              STATISTICS_NORECOMPUTE = ON);
GO
			 ALTER INDEX ALL ON Nufarm.dbo.BRND_BRANDPACK
REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON,
              STATISTICS_NORECOMPUTE = ON);
GO

			 ALTER INDEX ALL ON Nufarm.dbo.BRND_PRICE_HISTORY
REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON,
              STATISTICS_NORECOMPUTE = ON);
GO

			 ALTER INDEX ALL ON Nufarm.dbo.OA_SHIP_TO
REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON,
              STATISTICS_NORECOMPUTE = ON);
GO

			 ALTER INDEX ALL ON Nufarm.dbo.SHIP_TO
REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON,
              STATISTICS_NORECOMPUTE = ON);
GO

			 ALTER INDEX ALL ON Nufarm.dbo.TERRITORY
REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON,
              STATISTICS_NORECOMPUTE = ON);
GO
			 ALTER INDEX ALL ON Nufarm.dbo.TERRITORY_MANAGER
REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON,
              STATISTICS_NORECOMPUTE = ON);
GO

			 ALTER INDEX ALL ON Nufarm.dbo.DIST_DISTRIBUTOR
REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON,
              STATISTICS_NORECOMPUTE = ON);
GO

			 ALTER INDEX ALL ON Nufarm.dbo.ACHIEVEMENT_HEADER
REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON,
              STATISTICS_NORECOMPUTE = ON);
GO

			 ALTER INDEX ALL ON Nufarm.dbo.ACHIEVEMENT_DETAIL
REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON,
              STATISTICS_NORECOMPUTE = ON);
GO

--SET TRANSACTION ISOLATION LEVEL  READ COMMITTED; 
--SET DEADLOCK_PRIORITY NORMAL ; 
--SET ANSI_WARNINGS OFF;
--SET ARITHABORT OFF;
--BEGIN TRANSACTION;
--DECLARE @V_ACHIEVEMENT_BRANDPACK_ID VARCHAR(100),@V_DISC_QTY DECIMAL(19,3),@V_DISC_BY_VOLUME DECIMAL(19,3),@V_RELEASE_QTY DECIMAL(19,3),@V_TRUE_RELEASE_QTY DECIMAL(19,3),@V_H_DISC_QTY DECIMAL(19,3),@V_ACHIEVEMENT_ID VARCHAR(200);
--SELECT ACRD.ACHIEVEMENT_BRANDPACK_ID,ACRD.ACHIEVEMENT_ID,ACRH.BONUS_DISTRIBUTOR, ACRD.DISC_QTY,ACRD.DISC_BY_VOLUME,ACRD.RELEASE_QTY,TRUE_RELEASE_QTY = (SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC WHERE ACHIEVEMENT_BRANDPACK_ID = ACRD.ACHIEVEMENT_BRANDPACK_ID ) +  (SELECT ISNULL(SUM(QTY),0) FROM ORDR_OA_REMAINDING WHERE ACHIEVEMENT_BRANDPACK_ID = ACRD.ACHIEVEMENT_BRANDPACK_ID ) 
--INTO TEMPDB.SYS.##T_Maintenance FROM Nufarm.dbo.ACCRUED_HEADER ACRH INNER JOIN Nufarm.dbo.ACCRUED_DETAIL ACRD
--ON ACRH.ACHIEVEMENT_ID = ACRD.ACHIEVEMENT_ID INNER JOIN Nufarm.dbo.AGREE_AGREEMENT AA ON ACRH.AGREEMENT_NO = AA.AGREEMENT_NO
--WHERE AA.START_DATE >= '08/01/2014' AND AA.END_DATE <= '07/31/2015' AND ACRH.FLAG IN('Q1','Q2','Q3','Q4') AND ACRH.BRAND_ID IN('006020','00681','00604','0060200','00684','006820','00601');

--DECLARE CursorAch CURSOR FOR
--SELECT ACHIEVEMENT_BRANDPACK_ID,ACHIEVEMENT_ID,BONUS_DISTRIBUTOR,DISC_QTY,DISC_BY_VOLUME,RELEASE_QTY,TRUE_RELEASE_QTY FROM tempdb.SYS.##T_Maintenance ;
--OPEN CursorAch ;
--FETCH NEXT FROM CursorAch INTO @V_ACHIEVEMENT_BRANDPACK_ID,@V_ACHIEVEMENT_ID,@V_H_DISC_QTY,@V_DISC_QTY,@V_DISC_BY_VOLUME,@V_RELEASE_QTY,@V_TRUE_RELEASE_QTY ;
--WHILE (@@FETCH_STATUS = 0)
--BEGIN
--IF(@V_TRUE_RELEASE_QTY > 0)
--	BEGIN
--		UPDATE ACCRUED_DETAIL SET DISC_QTY = @V_H_DISC_QTY,DISC_BY_VOLUME = @V_H_DISC_QTY, RELEASE_QTY = @V_TRUE_RELEASE_QTY
--		WHERE ACHIEVEMENT_BRANDPACK_ID = @V_ACHIEVEMENT_BRANDPACK_ID;	
--		UPDATE ACCRUED_DETAIL SET LEFT_QTY = DISC_QTY - RELEASE_QTY 
--		WHERE ACHIEVEMENT_BRANDPACK_ID = @V_ACHIEVEMENT_BRANDPACK_ID;		
--	END
--FETCH NEXT FROM CursorAch INTO @V_ACHIEVEMENT_BRANDPACK_ID,@V_ACHIEVEMENT_ID,@V_H_DISC_QTY,@V_DISC_QTY,@V_DISC_BY_VOLUME,@V_RELEASE_QTY,@V_TRUE_RELEASE_QTY ;
--END
--CLOSE CursorAch;
--DEALLOCATE CursorAch;
--COMMIT TRANSACTION;
--DROP TABLE tempdb.SYS.##T_Maintenance ;
--GO



--SET TRANSACTION ISOLATION LEVEL  READ COMMITTED; 
--SET DEADLOCK_PRIORITY NORMAL ; 
--SET ANSI_WARNINGS OFF;
--SET ARITHABORT OFF;
--BEGIN TRANSACTION;
--DECLARE @V_ACHIEVEMENT_BRANDPACK_ID VARCHAR(100),@V_DISC_QTY DECIMAL(19,3),@V_DISC_BY_VOLUME DECIMAL(19,3),@V_RELEASE_QTY DECIMAL(19,3),@V_TRUE_RELEASE_QTY DECIMAL(19,3);
--SELECT ACRD.ACHIEVEMENT_BRANDPACK_ID,ACRD.DISC_QTY,ACRD.DISC_BY_VOLUME,ACRD.RELEASE_QTY,TRUE_RELEASE_QTY = (SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC WHERE ACHIEVEMENT_BRANDPACK_ID = ACRD.ACHIEVEMENT_BRANDPACK_ID ) +  (SELECT ISNULL(SUM(QTY),0) FROM ORDR_OA_REMAINDING WHERE ACHIEVEMENT_BRANDPACK_ID = ACRD.ACHIEVEMENT_BRANDPACK_ID ) 
--INTO TEMPDB.SYS.##T_Maintenance FROM Nufarm.dbo.ACCRUED_HEADER ACRH INNER JOIN Nufarm.dbo.ACCRUED_DETAIL ACRD
--ON ACRH.ACHIEVEMENT_ID = ACRD.ACHIEVEMENT_ID INNER JOIN Nufarm.dbo.AGREE_AGREEMENT AA ON ACRH.AGREEMENT_NO = AA.AGREEMENT_NO
--WHERE AA.START_DATE >= '08/01/2015' AND AA.END_DATE <= '07/31/2016' AND ACRD.DISC_QTY > 0;

--DECLARE CursorAch CURSOR FOR
--SELECT ACHIEVEMENT_BRANDPACK_ID,DISC_QTY,DISC_BY_VOLUME,RELEASE_QTY,TRUE_RELEASE_QTY FROM tempdb.SYS.##T_Maintenance ;
--OPEN CursorAch ;
--FETCH NEXT FROM CursorAch INTO @V_ACHIEVEMENT_BRANDPACK_ID,@V_DISC_QTY,@V_DISC_BY_VOLUME,@V_RELEASE_QTY,@V_TRUE_RELEASE_QTY ;
--WHILE (@@FETCH_STATUS = 0)
--BEGIN
--IF(@V_TRUE_RELEASE_QTY > 0)
--	BEGIN
--		UPDATE ACCRUED_DETAIL SET DISC_BY_VOLUME = @V_DISC_QTY, RELEASE_QTY = @V_TRUE_RELEASE_QTY,LEFT_QTY = (@V_DISC_QTY - @V_TRUE_RELEASE_QTY)
--		WHERE ACHIEVEMENT_BRANDPACK_ID = @V_ACHIEVEMENT_BRANDPACK_ID;		
--	END
--FETCH NEXT FROM CursorAch INTO @V_ACHIEVEMENT_BRANDPACK_ID,@V_DISC_QTY,@V_DISC_BY_VOLUME,@V_RELEASE_QTY,@V_TRUE_RELEASE_QTY ;
--END
--CLOSE CursorAch;
--DEALLOCATE CursorAch;
--COMMIT TRANSACTION;
--DROP TABLE tempdb.SYS.##T_Maintenance ;
--GO

--		SELECT ACRD.ACHIEVEMENT_BRANDPACK_ID,ACRD.DISC_QTY,ACRD.DISC_BY_VOLUME,ACRD.RELEASE_QTY,TRUE_RELEASE_QTY = ( (SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC WHERE ACHIEVEMENT_BRANDPACK_ID = ACRD.ACHIEVEMENT_BRANDPACK_ID ) + (SELECT ISNULL(SUM(QTY),0) FROM ORDR_OA_REMAINDING WHERE ACHIEVEMENT_BRANDPACK_ID =ACRD.ACHIEVEMENT_BRANDPACK_ID))
--INTO TEMPDB.SYS.##T_Maintenance FROM Nufarm.dbo.ACCRUED_HEADER ACRH INNER JOIN Nufarm.dbo.ACCRUED_DETAIL ACRD
--ON ACRH.ACHIEVEMENT_ID = ACRD.ACHIEVEMENT_ID INNER JOIN Nufarm.dbo.AGREE_AGREEMENT AA ON ACRH.AGREEMENT_NO = AA.AGREEMENT_NO
--WHERE AA.START_DATE >= '08/01/2014' AND AA.END_DATE <= '07/31/2015' AND ACRD.DISC_QTY > 0
--			  SELECT * FROM tempdb.SYS.##T_Maintenance WHERE TRUE_RELEASE_QTY  <> RELEASE_QTY 
			  
					--  SELECT ACRD.ACHIEVEMENT_BRANDPACK_ID,ACRD.DISC_QTY,ACRD.RELEASE_QTY,TRUE_RELEASE_QTY = ( (SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC WHERE ACHIEVEMENT_BRANDPACK_ID = ACRD.ACHIEVEMENT_BRANDPACK_ID ) + (SELECT ISNULL(SUM(QTY),0) FROM ORDR_OA_REMAINDING WHERE ACHIEVEMENT_BRANDPACK_ID =ACRD.ACHIEVEMENT_BRANDPACK_ID))
			  --FROM Nufarm.dbo.ACCRUED_HEADER ACRH INNER JOIN Nufarm.dbo.ACCRUED_DETAIL ACRD
	    --      ON ACRH.ACHIEVEMENT_ID = ACRD.ACHIEVEMENT_ID
			  --INNER JOIN Nufarm.dbo.AGREE_AGREEMENT AA ON ACRH.AGREEMENT_NO = AA.AGREEMENT_NO
     --         WHERE AA.START_DATE >= '08/01/2014' AND AA.END_DATE <= '07/31/2015' AND ACRD.DISC_BY_VOLUME > 0
--SET TRANSACTION ISOLATION LEVEL  READ COMMITTED; 
--SET DEADLOCK_PRIORITY NORMAL ; 
--SET ANSI_WARNINGS OFF;
--SET ARITHABORT OFF;
--BEGIN TRANSACTION;
--DECLARE @V_ACHIEVEMENT_BRANDPACK_ID VARCHAR(100),@V_DISC_QTY DECIMAL(19,3),@V_DISC_BY_VOLUME DECIMAL(19,3),@V_RELEASE_QTY DECIMAL(19,3),@V_TRUE_RELEASE_QTY DECIMAL(19,3);
--SELECT ACRD.ACHIEVEMENT_BRANDPACK_ID,ACRD.DISC_QTY,ACRD.DISC_BY_VOLUME,ACRD.RELEASE_QTY,TRUE_RELEASE_QTY = (SELECT ISNULL(SUM(QTY),0) FROM ORDR_OA_REMAINDING WHERE ACHIEVEMENT_BRANDPACK_ID = ACRD.ACHIEVEMENT_BRANDPACK_ID ) 
--INTO TEMPDB.SYS.##T_Maintenance FROM Nufarm.dbo.ACCRUED_HEADER ACRH INNER JOIN Nufarm.dbo.ACCRUED_DETAIL ACRD
--ON ACRH.ACHIEVEMENT_ID = ACRD.ACHIEVEMENT_ID INNER JOIN Nufarm.dbo.AGREE_AGREEMENT AA ON ACRH.AGREEMENT_NO = AA.AGREEMENT_NO
--WHERE AA.START_DATE >= '08/01/2014' AND AA.END_DATE <= '07/31/2015' AND ACRD.DISC_QTY > 0;

--DECLARE CursorAch CURSOR FOR
--SELECT ACHIEVEMENT_BRANDPACK_ID,DISC_QTY,DISC_BY_VOLUME,RELEASE_QTY,TRUE_RELEASE_QTY FROM tempdb.SYS.##T_Maintenance ;
--OPEN CursorAch ;
--FETCH NEXT FROM CursorAch INTO @V_ACHIEVEMENT_BRANDPACK_ID,@V_DISC_QTY,@V_DISC_BY_VOLUME,@V_RELEASE_QTY,@V_TRUE_RELEASE_QTY ;
--WHILE (@@FETCH_STATUS = 0)
--BEGIN
--IF(@V_TRUE_RELEASE_QTY > 0)
--	BEGIN
--		UPDATE ACCRUED_DETAIL SET RELEASE_QTY = RELEASE_QTY + @V_TRUE_RELEASE_QTY
--		WHERE ACHIEVEMENT_BRANDPACK_ID = @V_ACHIEVEMENT_BRANDPACK_ID;	
--		UPDATE ACCRUED_DETAIL SET LEFT_QTY = DISC_QTY - RELEASE_QTY 
--		WHERE ACHIEVEMENT_BRANDPACK_ID = @V_ACHIEVEMENT_BRANDPACK_ID;		
--	END
--FETCH NEXT FROM CursorAch INTO @V_ACHIEVEMENT_BRANDPACK_ID,@V_DISC_QTY,@V_DISC_BY_VOLUME,@V_RELEASE_QTY,@V_TRUE_RELEASE_QTY ;
--END
--CLOSE CursorAch;
--DEALLOCATE CursorAch;
--COMMIT TRANSACTION;
--DROP TABLE tempdb.SYS.##T_Maintenance ;
--GO


--SET TRANSACTION ISOLATION LEVEL  READ COMMITTED; 
--SET DEADLOCK_PRIORITY NORMAL ; 
--SET ANSI_WARNINGS OFF;
--SET ARITHABORT OFF;
--BEGIN TRANSACTION;
--DECLARE @V_ACHIEVEMENT_BRANDPACK_ID VARCHAR(100),@V_DISC_QTY DECIMAL(19,3),@V_DISC_BY_VOLUME DECIMAL(19,3),@V_RELEASE_QTY DECIMAL(19,3),@V_TRUE_RELEASE_QTY DECIMAL(19,3);
--SELECT ACRD.ACHIEVEMENT_BRANDPACK_ID,ACRD.DISC_QTY,ACRD.DISC_BY_VOLUME,ACRD.RELEASE_QTY,TRUE_RELEASE_QTY = (SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC WHERE ACHIEVEMENT_BRANDPACK_ID = ACRD.ACHIEVEMENT_BRANDPACK_ID ) 
--INTO TEMPDB.SYS.##T_Maintenance FROM Nufarm.dbo.ACCRUED_HEADER ACRH INNER JOIN Nufarm.dbo.ACCRUED_DETAIL ACRD
--ON ACRH.ACHIEVEMENT_ID = ACRD.ACHIEVEMENT_ID INNER JOIN Nufarm.dbo.AGREE_AGREEMENT AA ON ACRH.AGREEMENT_NO = AA.AGREEMENT_NO
--WHERE AA.START_DATE >= '08/01/2014' AND AA.END_DATE <= '07/31/2015' AND ACRD.DISC_QTY > 0;

--DECLARE CursorAch CURSOR FOR
--SELECT ACHIEVEMENT_BRANDPACK_ID,DISC_QTY,DISC_BY_VOLUME,RELEASE_QTY,TRUE_RELEASE_QTY FROM tempdb.SYS.##T_Maintenance ;
--OPEN CursorAch ;
--FETCH NEXT FROM CursorAch INTO @V_ACHIEVEMENT_BRANDPACK_ID,@V_DISC_QTY,@V_DISC_BY_VOLUME,@V_RELEASE_QTY,@V_TRUE_RELEASE_QTY ;
--WHILE (@@FETCH_STATUS = 0)
--BEGIN
--IF(@V_TRUE_RELEASE_QTY > 0)
--	BEGIN
--		UPDATE ACCRUED_DETAIL SET DISC_BY_VOLUME = @V_DISC_QTY, RELEASE_QTY = @V_TRUE_RELEASE_QTY,LEFT_QTY = (@V_DISC_QTY - @V_TRUE_RELEASE_QTY)
--		WHERE ACHIEVEMENT_BRANDPACK_ID = @V_ACHIEVEMENT_BRANDPACK_ID;		
--	END
--FETCH NEXT FROM CursorAch INTO @V_ACHIEVEMENT_BRANDPACK_ID,@V_DISC_QTY,@V_DISC_BY_VOLUME,@V_RELEASE_QTY,@V_TRUE_RELEASE_QTY ;
--END
--CLOSE CursorAch;
--DEALLOCATE CursorAch;
--COMMIT TRANSACTION;
--DROP TABLE tempdb.SYS.##T_Maintenance ;
--GO

--		SELECT ACRD.ACHIEVEMENT_BRANDPACK_ID,ACRD.DISC_QTY,ACRD.DISC_BY_VOLUME,ACRD.RELEASE_QTY,TRUE_RELEASE_QTY = ( (SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC WHERE ACHIEVEMENT_BRANDPACK_ID = ACRD.ACHIEVEMENT_BRANDPACK_ID ) + (SELECT ISNULL(SUM(QTY),0) FROM ORDR_OA_REMAINDING WHERE ACHIEVEMENT_BRANDPACK_ID =ACRD.ACHIEVEMENT_BRANDPACK_ID))
--INTO TEMPDB.SYS.##T_Maintenance FROM Nufarm.dbo.ACCRUED_HEADER ACRH INNER JOIN Nufarm.dbo.ACCRUED_DETAIL ACRD
--ON ACRH.ACHIEVEMENT_ID = ACRD.ACHIEVEMENT_ID INNER JOIN Nufarm.dbo.AGREE_AGREEMENT AA ON ACRH.AGREEMENT_NO = AA.AGREEMENT_NO
--WHERE AA.START_DATE >= '08/01/2014' AND AA.END_DATE <= '07/31/2015' AND ACRD.DISC_QTY > 0
--			  SELECT * FROM tempdb.SYS.##T_Maintenance WHERE TRUE_RELEASE_QTY  <> RELEASE_QTY 
			  
					--  SELECT ACRD.ACHIEVEMENT_BRANDPACK_ID,ACRD.DISC_QTY,ACRD.RELEASE_QTY,TRUE_RELEASE_QTY = ( (SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC WHERE ACHIEVEMENT_BRANDPACK_ID = ACRD.ACHIEVEMENT_BRANDPACK_ID ) + (SELECT ISNULL(SUM(QTY),0) FROM ORDR_OA_REMAINDING WHERE ACHIEVEMENT_BRANDPACK_ID =ACRD.ACHIEVEMENT_BRANDPACK_ID))
			  --FROM Nufarm.dbo.ACCRUED_HEADER ACRH INNER JOIN Nufarm.dbo.ACCRUED_DETAIL ACRD
	    --      ON ACRH.ACHIEVEMENT_ID = ACRD.ACHIEVEMENT_ID
			  --INNER JOIN Nufarm.dbo.AGREE_AGREEMENT AA ON ACRH.AGREEMENT_NO = AA.AGREEMENT_NO
     --         WHERE AA.START_DATE >= '08/01/2014' AND AA.END_DATE <= '07/31/2015' AND ACRD.DISC_BY_VOLUME > 0
--SET TRANSACTION ISOLATION LEVEL  READ COMMITTED; 
--SET DEADLOCK_PRIORITY NORMAL ; 
--SET ANSI_WARNINGS OFF;
--SET ARITHABORT OFF;
--BEGIN TRANSACTION;
--DECLARE @V_ACHIEVEMENT_BRANDPACK_ID VARCHAR(100),@V_DISC_QTY DECIMAL(19,3),@V_DISC_BY_VOLUME DECIMAL(19,3),@V_RELEASE_QTY DECIMAL(19,3),@V_TRUE_RELEASE_QTY DECIMAL(19,3);
--SELECT ACRD.ACHIEVEMENT_BRANDPACK_ID,ACRD.DISC_QTY,ACRD.DISC_BY_VOLUME,ACRD.RELEASE_QTY,TRUE_RELEASE_QTY = (SELECT ISNULL(SUM(QTY),0) FROM ORDR_OA_REMAINDING WHERE ACHIEVEMENT_BRANDPACK_ID = ACRD.ACHIEVEMENT_BRANDPACK_ID ) 
--INTO TEMPDB.SYS.##T_Maintenance FROM Nufarm.dbo.ACCRUED_HEADER ACRH INNER JOIN Nufarm.dbo.ACCRUED_DETAIL ACRD
--ON ACRH.ACHIEVEMENT_ID = ACRD.ACHIEVEMENT_ID INNER JOIN Nufarm.dbo.AGREE_AGREEMENT AA ON ACRH.AGREEMENT_NO = AA.AGREEMENT_NO
--WHERE AA.START_DATE >= '08/01/2014' AND AA.END_DATE <= '07/31/2015' AND ACRD.DISC_QTY > 0;

--DECLARE CursorAch CURSOR FOR
--SELECT ACHIEVEMENT_BRANDPACK_ID,DISC_QTY,DISC_BY_VOLUME,RELEASE_QTY,TRUE_RELEASE_QTY FROM tempdb.SYS.##T_Maintenance ;
--OPEN CursorAch ;
--FETCH NEXT FROM CursorAch INTO @V_ACHIEVEMENT_BRANDPACK_ID,@V_DISC_QTY,@V_DISC_BY_VOLUME,@V_RELEASE_QTY,@V_TRUE_RELEASE_QTY ;
--WHILE (@@FETCH_STATUS = 0)
--BEGIN
--IF(@V_TRUE_RELEASE_QTY > 0)
--	BEGIN
--		UPDATE ACCRUED_DETAIL SET RELEASE_QTY = RELEASE_QTY + @V_TRUE_RELEASE_QTY
--		WHERE ACHIEVEMENT_BRANDPACK_ID = @V_ACHIEVEMENT_BRANDPACK_ID;	
--		UPDATE ACCRUED_DETAIL SET LEFT_QTY = DISC_QTY - RELEASE_QTY 
--		WHERE ACHIEVEMENT_BRANDPACK_ID = @V_ACHIEVEMENT_BRANDPACK_ID;		
--	END
--FETCH NEXT FROM CursorAch INTO @V_ACHIEVEMENT_BRANDPACK_ID,@V_DISC_QTY,@V_DISC_BY_VOLUME,@V_RELEASE_QTY,@V_TRUE_RELEASE_QTY ;
--END
--CLOSE CursorAch;
--DEALLOCATE CursorAch;
--COMMIT TRANSACTION;
--DROP TABLE tempdb.SYS.##T_Maintenance ;
--GO



--SELECT OBJECT_NAME(OBJECT_ID), index_id,index_type_desc,index_level,
--avg_fragmentation_in_percent,avg_page_space_used_in_percent,page_count
--FROM sys.dm_db_index_physical_stats
--(DB_ID(N'Nufarm'), NULL, NULL, NULL , 'SAMPLED')
--ORDER BY avg_fragmentation_in_percent DESC
--GO

--CREATE PROCEDURE sp_showcontig_all AS
--DECLARE @tablename varchar(128)
--DECLARE @id int
--DECLARE @indid smallint
--DECLARE @indname varchar(126)
--DECLARE @tablename_header varchar(255)
--DECLARE tnames_cursor CURSOR 

--FOR

--SELECT obj.name, obj.id, idx.indid, idx.name
--    FROM sysobjects AS obj JOIN sysindexes AS idx
--    ON obj.id = idx.id
--    WHERE type = 'U' AND uid = 1 AND indid < 255

--OPEN tnames_cursor

--FETCH NEXT FROM tnames_cursor INTO @tablename, @id, @indid, @indname

--WHILE (@@fetch_status <> -1)
--BEGIN
--BEGIN

--      IF @indid=0
--         SELECT @tablename_header = 'Checking fragmentation on Table '+ RTRIM(UPPER(@tablename))

--      IF @indid=1
--         SELECT @tablename_header = 'Checking fragmentation on Clustered Index '+ RTRIM(UPPER(@tablename))

--      IF @indid >1
--         SELECT @tablename_header = 'Checking fragmentation on Non-clustered Index '+ RTRIM(UPPER(@indname))+' on Table '+RTRIM(UPPER(@tablename))

--      PRINT ' '
--      PRINT @tablename_header

--      SELECT @id = OBJECT_ID(@tablename)
--      DBCC SHOWCONTIG (@id, @indid)

--   END
--   FETCH NEXT FROM tnames_cursor INTO @tablename, @id, @indid, @indname
--END

--PRINT ' '
--PRINT ' '

--SELECT @tablename_header = '************ NO MORE TABLES ************'
--PRINT @tablename_header

--PRINT ' '
--PRINT 'Fragmentation has been checked for all tables and indexes.'

--DEALLOCATE tnames_cursor


--EXEC sp_showcontig_all;

--go
--SELECT * FROM ACCRUED_DETAIL WHERE ACHIEVEMENT_BRANDPACK_ID = 'SIS001IDR|0223/NI/III/2010.1400011|S1|00011200MD'
--SELECT * FROM ACCRUED_HEADER WHERE ACHIEVEMENT_ID = 'SIS001IDR|0223/NI/III/2010.1400011|S1'

--SELECT * FROM ACCRUED_DETAIL WHERE ACHIEVEMENT_ID = ANY(SELECT ACHIEVEMENT_ID FROM ACCRUED_HEADER WHERE AGREEMENT_NO = ANY(SELECT AGREEMENT_NO FROM AGREE_AGREEMENT 
--WHERE START_DATE = '08/01/2014' AND END_DATE = '07/31/2015') AND FLAG = 'S1');

--SELECT PO.PO_REF_NO, DR.DISTRIBUTOR_NAME FROM ORDR_PURCHASE_ORDER PO INNER JOIN DIST_DISTRIBUTOR DR
--ON PO.DISTRIBUTOR_ID = DR.DISTRIBUTOR_ID WHERE PO.PO_REF_NO = ANY(
--SELECT PO_REF_NO FROM ORDR_PO_BRANDPACK WHERE PO_BRANDPACK_ID = ANY(
--SELECT PO_BRANDPACK_ID FROM ORDR_OA_BRANDPACK  WHERE OA_BRANDPACK_ID = ANY(
--SELECT OA_BRANDPACK_ID FROM(
--SELECT * FROM ORDR_OA_BRANDPACK_DISC WHERE ACHIEVEMENT_BRANDPACK_ID = ANY(SELECT ACHIEVEMENT_BRANDPACK_ID FROM ACCRUED_DETAIL WHERE ACHIEVEMENT_ID = ANY
--(SELECT ACHIEVEMENT_ID FROM ACCRUED_HEADER WHERE AGREEMENT_NO = ANY(SELECT AGREEMENT_NO FROM AGREE_AGREEMENT 
--WHERE START_DATE = '08/01/2014' AND END_DATE = '07/31/2015') AND FLAG = 'S1')))C
--)));


--SELECT * FROM ACCRUED_DETAIL WHERE ACHIEVEMENT_ID = ANY(SELECT ACHIEVEMENT_ID FROM ACCRUED_HEADER WHERE AGREEMENT_NO = ANY(SELECT AGREEMENT_NO FROM AGREE_AGREEMENT 
--WHERE START_DATE = '08/01/2014' AND END_DATE = '07/31/2015') AND FLAG = 'Q2');


--SELECT * FROM ORDR_OA_BRANDPACK_DISC WHERE ACHIEVEMENT_BRANDPACK_ID = ANY(SELECT ACHIEVEMENT_BRANDPACK_ID FROM ACCRUED_DETAIL WHERE ACHIEVEMENT_ID = ANY
--(SELECT ACHIEVEMENT_ID FROM ACCRUED_HEADER WHERE AGREEMENT_NO = ANY(SELECT AGREEMENT_NO FROM AGREE_AGREEMENT 
--WHERE START_DATE >= '08/01/2014' AND END_DATE <= '07/31/2015') AND FLAG = 'Q2'));


--SELECT * FROM ORDR_OA_BRANDPACK_DISC WHERE ACHIEVEMENT_BRANDPACK_ID = ANY(SELECT ACHIEVEMENT_BRANDPACK_ID FROM ACCRUED_DETAIL WHERE ACHIEVEMENT_ID = ANY
--(SELECT ACHIEVEMENT_ID FROM ACCRUED_HEADER WHERE AGREEMENT_NO = ANY(SELECT AGREEMENT_NO FROM AGREE_AGREEMENT 
--WHERE START_DATE >= '08/01/2014' AND END_DATE <= '07/31/2015') AND FLAG = 'Q3'));


--SELECT * FROM ORDR_OA_BRANDPACK_DISC WHERE ACHIEVEMENT_BRANDPACK_ID = ANY(SELECT ACHIEVEMENT_BRANDPACK_ID FROM ACCRUED_DETAIL WHERE ACHIEVEMENT_ID = ANY
--(SELECT ACHIEVEMENT_ID FROM ACCRUED_HEADER WHERE AGREEMENT_NO = ANY(SELECT AGREEMENT_NO FROM AGREE_AGREEMENT 
--WHERE START_DATE >= '08/01/2014' AND END_DATE <= '07/31/2015') AND FLAG = 'Q4'));




--SELECT * FROM ORDR_OA_BRANDPACK_DISC WHERE ACHIEVEMENT_BRANDPACK_ID = ANY(SELECT ACHIEVEMENT_BRANDPACK_ID FROM ACCRUED_DETAIL WHERE ACHIEVEMENT_ID = ANY
--(SELECT ACHIEVEMENT_ID FROM ACCRUED_HEADER WHERE AGREEMENT_NO = ANY(SELECT AGREEMENT_NO FROM AGREE_AGREEMENT 
--WHERE START_DATE >= '08/01/2014' AND END_DATE <= '07/31/2015') AND FLAG = 'S1'));


--SELECT * FROM ACCRUED_DETAIL WHERE ACHIEVEMENT_ID = ANY(SELECT ACHIEVEMENT_ID FROM ACCRUED_HEADER WHERE AGREEMENT_NO = ANY(SELECT AGREEMENT_NO FROM AGREE_AGREEMENT 
--WHERE START_DATE >= '08/01/2014' AND END_DATE <= '07/31/2015') AND FLAG = 'S1');


--SELECT * FROM ORDR_OA_BRANDPACK_DISC WHERE ACHIEVEMENT_BRANDPACK_ID = ANY(SELECT ACHIEVEMENT_BRANDPACK_ID FROM ACCRUED_DETAIL WHERE ACHIEVEMENT_ID = ANY
--(SELECT ACHIEVEMENT_ID FROM ACCRUED_HEADER WHERE AGREEMENT_NO = ANY(SELECT AGREEMENT_NO FROM AGREE_AGREEMENT 
--WHERE START_DATE >= '08/01/2014' AND END_DATE <= '07/31/2015') AND FLAG = 'S2'));

--SELECT * FROM ACCRUED_DETAIL WHERE ACHIEVEMENT_BRANDPACK_ID = 'END001000|1082/NI/X/08-4L.1400604|Q1|00604040LD'


--SET TRANSACTION ISOLATION LEVEL  READ COMMITTED; 
--SET DEADLOCK_PRIORITY NORMAL ; 
--SET ANSI_WARNINGS OFF;
--SET ARITHABORT OFF;
--BEGIN TRANSACTION;
--DECLARE @V_TOTAL_ACTUAL DECIMAL(19,3),@V_DISPRO DECIMAL(18,4),@V_ACHIEVEMENT_BRANDPACK_ID VARCHAR(200),@V_TRUE_RELEASE_QTY DECIMAL(19,3),@V_DISC_QTY DECIMAL(19,3);
--DECLARE CursorAch CURSOR FOR
--SELECT ACRD.ACHIEVEMENT_BRANDPACK_ID,ACRD.TOTAL_ACTUAL,ACRH.DISPRO, TRUE_RELEASE_QTY = (SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC WHERE ACHIEVEMENT_BRANDPACK_ID = ACRD.ACHIEVEMENT_BRANDPACK_ID ) +  (SELECT ISNULL(SUM(QTY),0) FROM ORDR_OA_REMAINDING WHERE ACHIEVEMENT_BRANDPACK_ID = ACRD.ACHIEVEMENT_BRANDPACK_ID ) 
--FROM ACCRUED_DETAIL ACRD INNER JOIN ACCRUED_HEADER ACRH ON ACRD.ACHIEVEMENT_ID = ACRH.ACHIEVEMENT_ID 
--WHERE ACRH.BONUS_DISTRIBUTOR > 0 AND (ACRD.DESCRIPTIONS = '' OR ACRD.DESCRIPTIONS IS NULL)

--OPEN CursorAch
--FETCH NEXT FROM CursorAch INTO @V_ACHIEVEMENT_BRANDPACK_ID,@V_TOTAL_ACTUAL,@V_DISPRO,@V_TRUE_RELEASE_QTY;
--WHILE (@@FETCH_STATUS = 0)
--BEGIN
--SET @V_DISC_QTY = (@V_TOTAL_ACTUAL * @V_DISPRO);
--UPDATE ACCRUED_DETAIL SET DISC_QTY = @V_DISC_QTY, DISC_BY_VOLUME = @V_DISC_QTY,RELEASE_QTY =  @V_TRUE_RELEASE_QTY,
--LEFT_QTY = (@V_DISC_QTY - @V_TRUE_RELEASE_QTY)   WHERE ACHIEVEMENT_BRANDPACK_ID = @V_ACHIEVEMENT_BRANDPACK_ID;
--FETCH NEXT FROM CursorAch INTO @V_ACHIEVEMENT_BRANDPACK_ID,@V_TOTAL_ACTUAL,@V_DISPRO,@V_TRUE_RELEASE_QTY;
--END
--CLOSE CursorAch;
--DEALLOCATE CursorAch;
--CLOSE CursorAch;
--DEALLOCATE CursorAch;
--COMMIT TRANSACTION;
--GO

----------YANG ADA DESCRIPSI NYA
--SET TRANSACTION ISOLATION LEVEL  READ COMMITTED; 
--SET DEADLOCK_PRIORITY NORMAL ; 
--SET ANSI_WARNINGS OFF;
--SET ARITHABORT OFF;
--BEGIN TRANSACTION;
--DECLARE @V_TOTAL_ACTUAL DECIMAL(19,3),@V_DISPRO DECIMAL(18,4),@V_ACHIEVEMENT_BRANDPACK_ID VARCHAR(200),@V_TRUE_RELEASE_QTY DECIMAL(19,3),@V_DISC_QTY DECIMAL(19,3),
--@V_PBQ3 DECIMAL(18,3),@V_PBQ4 DECIMAL(18,3),@V_PBS2 DECIMAL(18,3),@V_CPQ1 DECIMAL(18,3),@V_CPQ2 DECIMAL(18,3),@V_CPQ3 DECIMAL(18,3),@V_CPS1 DECIMAL(18,3),@V_PBY DECIMAL(18,3);

--DECLARE CursorAch CURSOR FOR
--SELECT ACRD.ACHIEVEMENT_BRANDPACK_ID,GP.PBQ3,GP.PBQ4,GP.PBS2,GP.CPQ1,GP.CPQ2,GP.CPQ3,GP.CPS1,GP.PBY, ACRD.TOTAL_ACTUAL,ACRH.DISPRO, TRUE_RELEASE_QTY = (SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC WHERE ACHIEVEMENT_BRANDPACK_ID = ACRD.ACHIEVEMENT_BRANDPACK_ID ) +  (SELECT ISNULL(SUM(QTY),0) FROM ORDR_OA_REMAINDING WHERE ACHIEVEMENT_BRANDPACK_ID = ACRD.ACHIEVEMENT_BRANDPACK_ID ) 
--FROM ACCRUED_DETAIL ACRD INNER JOIN ACCRUED_HEADER ACRH ON ACRD.ACHIEVEMENT_ID = ACRH.ACHIEVEMENT_ID 
--INNER JOIN GIVEN_PROGRESSIVE GP ON (ACRH.AGREEMENT_NO + ACRH.BRAND_ID) = GP.AGREE_BRAND_ID  
--WHERE ACRH.BONUS_DISTRIBUTOR > 0 AND (ACRD.DESCRIPTIONS != '' and ACRD.DESCRIPTIONS IS NOT NULL)

--OPEN CursorAch
--FETCH NEXT FROM CursorAch INTO @V_ACHIEVEMENT_BRANDPACK_ID,@V_PB_Q3,@V_PBQ4,@V_TOTAL_ACTUAL,@V_DISPRO,@V_TRUE_RELEASE_QTY;
--WHILE (@@FETCH_STATUS = 0)
--BEGIN
--SET @V_DISC_QTY = (@V_TOTAL_ACTUAL * @V_DISPRO);
--UPDATE ACCRUED_DETAIL SET DISC_QTY = @V_DISC_QTY, DISC_BY_VOLUME = @V_DISC_QTY,RELEASE_QTY =  @V_TRUE_RELEASE_QTY,
--LEFT_QTY = (@V_DISC_QTY - @V_TRUE_RELEASE_QTY)   WHERE ACHIEVEMENT_BRANDPACK_ID = @V_ACHIEVEMENT_BRANDPACK_ID;
--FETCH NEXT FROM CursorAch INTO @V_ACHIEVEMENT_BRANDPACK_ID,@V_TOTAL_ACTUAL,@V_DISPRO,@V_TRUE_RELEASE_QTY;
--END
--CLOSE CursorAch;
--DEALLOCATE CursorAch;
--CLOSE CursorAch;
--DEALLOCATE CursorAch;
--COMMIT TRANSACTION;
--GO




--SELECT ACRD.* FROM ACCRUED_DETAIL ACRD INNER JOIN ACCRUED_HEADER ACRH ON ACRD.ACHIEVEMENT_ID = ACRH.ACHIEVEMENT_ID 
--WHERE ACRH.BONUS_DISTRIBUTOR > 0 AND ACRD.CAN_RELEASE = 1 AND (ACRD.DESCRIPTIONS != '' AND ACRD.DESCRIPTIONS IS NOT NULL)
--AND ACRD.DISC_QTY <= 0
--go
--2,00 % of S2, S2 = 465,000 Qty ,2,10 % of Y, Y = 465,000 Qty

--2,00 % of S2, S2 = 5.010,000 Qty ,2,63 % of Y, Y = 5.010,000 Qty

--2,00 % of S2, S2 = 5.000,000 Qty ,2,63 % of Y, Y = 5.000,000 Qty

--2,00 % of S2, S2 = 5.000,000 Qty ,2,63 % of Y, Y = 5.000,000 Qty

--0,00 % of S2, S2 = 7.999,992 Qty ,1,20 % of Y, Y = 7.999,992 Qty

--0,00 % of S2, S2 = 1.999,998 Qty ,1,20 % of Y, Y = 1.999,998 Qty

--0,00 % of S2, S2 = 9.999,990 Qty ,1,20 % of Y, Y = 9.999,990 Qty

--0,75 % of S2, S2 = 110,000 Qty ,3,00 % of Y, Y = 110,000 Qty

--0,00 % of S2, S2 = 50,000 Qty ,2,25 % of Y, Y = 50,000 Qty

--SELECT * FROM ACCRUED_DETAIL ORDER BY CREATE_DATE DESC;

--select * from tempdb.dbo.sysobjects

----select * from ##T_MASTER_PO_Nkusnandar
--SET DEADLOCK_PRIORITY NORMAL; SET NOCOUNT ON;
--                            SELECT AA.AGREEMENT_NO,AA.START_DATE,AA.END_DATE FROM AGREE_AGREEMENT AA INNER JOIN DISTRIBUTOR_AGREEMENT DA 
--                             ON AA.AGREEMENT_NO = DA.AGREEMENT_NO WHERE DA.DISTRIBUTOR_ID = 'AGR011IDR'
--                             AND YEAR(AA.END_DATE) >= YEAR(GETDATE()) - 1

--SELECT * FROM GIVEN_PROGRESSIVE WHERE AGREE_BRAND_ID = '00780652/NI/VI/2005.14'
--go

--UPDATE ACCRUED_DETAIL SET CAN_RELEASE = 1, LEFT_QTY = 0,RELEASE_QTY = DISC_QTY WHERE ACHIEVEMENT_BRANDPACK_ID 
--IN('AGR011IDR|652/NI/VI/2005.1400780|S1|00780001LD','AGR011IDR|652/NI/VI/2005.1400780|S1|00780005LD')

--SELECT * FROM ORDR_OA_BRANDPACK_DISC WHERE ACHIEVEMENT_BRANDPACK_ID IN('AGR011IDR|652/NI/VI/2005.1300010|S2|00010400MD')

----UPDATE ACCRUED_HEADER SET AGREE_ACH_BY = 'VOL' WHERE ACHIEVEMENT_ID IN('AGR011IDR|652/NI/VI/2005.1400780|S1','AGR011IDR|652/NI/VI/2005.1400540|S1')

--SELECT * FROM ##T_SELECT_INVOICE_Nkusnandar WHERE BRANDPACK_NAME = 'GIBGRO 20% TABLET @ 5 GR- D'

--UPDATE ACCRUED_DETAIL SET CAN_RELEASE = 1,DISC_QTY = 300, LEFT_QTY = 300, RELEASE_QTY = 0,DISC_BY_VOLUME = 300 WHERE ACHIEVEMENT_BRANDPACK_ID = 'KAR009IDR|820/NI/VIII/2005.1430896|S2|30896005GD'


--PT. KARISMA INDOAGRO UNIVERSAL

--SELECT * FROM ORDR_OA_BRANDPACK_DISC WHERE OA_RM_ID IS NOT NULL


--SELECT * FROM ORDR_OA_BRANDPACK_DISC WHERE DISC_QTY = 0

--UPDATE ACCRUED_HEADER SET AGREE_ACH_BY = 'VOL' WHERE AGREEMENT_NO = '820/NI/VIII/2005.14' AND FLAG = 'S1'

--UPDATE ACCRUED_DETAIL SET CAN_RELEASE = 1 WHERE ACHIEVEMENT_BRANDPACK_ID = 'KAR009IDR|820/NI/VIII/2005.1430896|S1|30896005GD'

--UPDATE ACCRUED_DETAIL SET CAN_RELEASE = 1,TOTAL_ACTUAL = 15000,DISC_BY_VOLUME = 300,LEFT_QTY = 300,TOTAL_PO_ORIGINAL = 15000
--WHERE ACHIEVEMENT_BRANDPACK_ID = 'KAR009IDR|820/NI/VIII/2005.1430896|S2|30896005GD';

--UPDATE ACCRUED_DETAIL SET TOTAL_ACTUAL = 20000,DISC_BY_VOLUME = 176,LEFT_QTY = 176,TOTAL_PO_ORIGINAL = 20000
--WHERE ACHIEVEMENT_BRANDPACK_ID = 'KAR009IDR|820/NI/VIII/2005.1430896|Y|30896005GD';

--UPDATE ACCRUED_DETAIL SET CAN_RELEASE = 1 WHERE ACHIEVEMENT_ID = ANY(SELECT ACHIEVEMENT_ID FROM ACCRUED_HEADER
--WHERE AGREEMENT_NO = '820/NI/VIII/2005.14' AND FLAG = 'Y')
--AND LEFT_QTY > 0;

--UPDATE ACCRUED_HEADER SET AGREE_ACH_BY = 'VOL' WHERE AGREEMENT_NO = '231/NI/III/2002.14' AND FLAG = 'S1'

--UPDATE ACCRUED_DETAIL SET CAN_RELEASE = 1 WHERE ACHIEVEMENT_ID = ANY(SELECT ACHIEVEMENT_ID FROM ACCRUED_HEADER
--WHERE AGREEMENT_NO = '231/NI/III/2002.14' AND FLAG = 'S1')

--UPDATE ACCRUED_DETAIL SET CAN_RELEASE = 0  WHERE ACHIEVEMENT_ID = ANY(SELECT ACHIEVEMENT_ID FROM ACCRUED_HEADER
--WHERE AGREEMENT_NO = '231/NI/III/2002.14' AND FLAG = 'S1') AND DISC_QTY <= 0

--UPDATE ACCRUED_HEADER SET AGREE_ACH_BY = 'VOL',BONUS_QTY = DISC_BY_VOLUME  WHERE AGREEMENT_NO = '348/NI/III/2002.14' AND FLAG = 'S1'

--UPDATE ACCRUED_DETAIL SET CAN_RELEASE = 1,TOTAL_ACTUAL = 15000,DISC_BY_VOLUME = 300,LEFT_QTY = 300,TOTAL_PO_ORIGINAL = 15000

--UPDATE ACCRUED_HEADER SET BONUS_QTY = DISC_BY_VOLUME,BONUS_DISTRIBUTOR = DISC_DIST_BY_VOLUME,AGREE_ACH_BY = 'VOL',LAST_UPDATE = GETDATE(),
--MODIFY_DATE = CONVERT(VARCHAR(100),GETDATE(),101)
--WHERE ACHIEVEMENT_ID = ANY(SELECT ACHIEVEMENT_ID FROM [tempdb].[sys].##T_LIST_ACH_HEADER_ & Me.ComputerName & )

--UPDATE ACCRUED_DETAIL SET CAN_RELEASE = 1, DISC_QTY = DISC_BY_VOLUME,RELEASE_QTY =13.5,LEFT_QTY = DISC_QTY - 13.5, LAST_UPDATE = GETDATE(),MODIFY_DATE = CONVERT(VARCHAR(100),GETDATE(),101)
--WHERE ACHIEVEMENT_BRANDPACK_ID = 'LIL001IDR|348/NI/III/2002.1477001|S1|77001500MD'

--GET PO
--SELECT * FROM NI87.DBO.OEORDH WHERE PONUMBER = '067/II/VN/2015' --'IN15083639.'
--SELECT * FROM NI87.DBO.OEINVH WHERE PONUMBER = '067/II/VN/2015'
----GET REFERENCE
--SELECT * FROM NI87.DBO.OEORDHO WHERE

--SELECT * FROM NI87.DBO.OEINVH WHERE INVNUMBER = '1412/XI/TS/2014'

--SELECT * FROM NI87.DBO.OEINVD WHERE INVUNIQ = '976495'

--SELECT * FROM NI87.DBO.OEINVH WHERE PONUMBER = '007/8M/RUB/18'

--SELECT * FROM NI87.DBO.OEORDHO WHERE VALUE = '00021613'

--SELECT * FROM NI87.DBO.OEORDH WHERE ORDUNIQ = 1440448

--SELECT * FROM NI87.DBO.ICITEM WHERE [DESC] LIKE '%MICROTHIOL%' AND INACTIVE = 0

--SELECT * FROM tempdb.##T_SELECT_INVOICE_NKusnandar where PONUMBER = '1412/XI/TS/2014'

--SELECT * FROM tempdb.##T_SELECT_INVOICE_NKusnandar  where BRANDPACK_NAME LIKE '%LINDOMIN%'
--AND INVDATE <= 20141131

--UPDATE AGREE_PROG_DISC SET PRGSV_DISC_PCT = 35 WHERE AGREE_BRAND_ID = '348/NI/III/2002.1477230'
 
--UPDATE AGREE_PROG_DISC SET UP_TO_PCT = 35, PRGSV_DISC_PCT = 1.5 WHERE AGREE_BRAND_ID = '348/NI/III/2002.1477240' AND QSY_DISC_FLAG = 'Y'

--UPDATE AGREE_PROG_DISC SET PRGSV_DISC_PCT = 1.25 WHERE AGREE_BRAND_ID = '348/NI/III/2002.1477240' AND QSY_DISC_FLAG = 'S1'
--UPDATE AGREE_PROG_DISC SET PRGSV_DISC_PCT = 0 WHERE AGREE_BRAND_ID = '348/NI/III/2002.1477240'  AND QSY_DISC_FLAG = 'S2'

--PT 8 MASAGRO GIBGRO RELEASE 2.248

--UPDATE ACCRUED_DETAIL SET CAN_RELEASE = 1, RELEASE_QTY = 2.248,LEFT_QTY = DISC_QTY - 2.248, LAST_UPDATE = GETDATE(),MODIFY_DATE = CONVERT(VARCHAR(100),GETDATE(),101)
--WHERE ACHIEVEMENT_BRANDPACK_ID = 'MAS003IDR|0853/NI/V/2011.1430898|S1|30898001GD'


--UPDATE ACCRUED_HEADER SET AGREE_ACH_BY = 'VOL' WHERE ACHIEVEMENT_ID = 'MAS003IDR|0853/NI/V/2011.1430898|S1'

--PT 8 MASAGRO lindomin RELEASE 426.240

--UPDATE ACCRUED_HEADER SET AGREE_ACH_BY = 'VOL' WHERE ACHIEVEMENT_ID = 'MAS003IDR|0853/NI/V/2011.1400010|S1'
--UPDATE ACCRUED_DETAIL SET CAN_RELEASE = 1,RELEASE_QTY = DISC_QTY,LEFT_QTY = 0 WHERE ACHIEVEMENT_ID = 'MAS003IDR|0853/NI/V/2011.1400010|S1'
--AND DISC_QTY > 0 AND RELEASE_QTY = 0 AND LEFT_QTY = 0

--SELECT * FROM NI87.DBO.OEINVH WHERE RTRIM(INVNUMBER) = 'IN151225001.'

--SELECT BB.BRANDPACK_NAME,SCP.*  FROM SALES_CPDAUTO_PRODUCT SCP INNER JOIN BRND_BRANDPACK BB ON BB.BRANDPACK_ID = SCP.BRANDPACK_ID WHERE FKCode = 1

--SELECT  1 WHERE EXISTS( SELECT SCP.BRANDPACK_ID FROM SALES_CPDAUTO_PRODUCT SCP INNER JOIN SALES_CPDAUTO_HEADER SCH ON SCH.IDApp = SCP.FKCode 
--                                 WHERE SCH.START_PERIODE <= GETDATE() AND SCH.END_PERIODE >= GETDATE() AND SCP.BRANDPACK_ID = '00790100MD')

--SELECT SCP.BRANDPACK_ID FROM SALES_CPDAUTO_PRODUCT SCP INNER JOIN SALES_CPDAUTO_HEADER SCH ON SCH.IDApp = SCP.FKCode 
--WHERE SCH.START_PERIODE <= '11/26/2015' AND SCH.END_PERIODE >= '11/26/2015' AND SCP.BRANDPACK_ID = '00790005LD'

--SELECT SCP.BRANDPACK_ID FROM SALES_CPDAUTO_PRODUCT SCP INNER JOIN SALES_CPDAUTO_HEADER SCH ON SCH.IDApp = SCP.FKCode 
--WHERE SCH.START_PERIODE <= '11/26/2015' AND SCH.END_PERIODE >= '11/26/2015' AND SCP.BRANDPACK_ID = '00790001LD'


--SELECT DR.DISTRIBUTOR_ID,DR.DISTRIBUTOR_NAME FROM DIST_DISTRIBUTOR DR WHERE EXISTS(SELECT DISTRIBUTOR_ID FROM
--ACCRUED_HEADER WHERE DISTRIBUTOR_ID = DR.DISTRIBUTOR_ID AND AGREEMENT_NO = ANY(
--SELECT AGREEMENT_NO FROM AGREE_AGREEMENT WHERE START_DATE <= GETDATE() AND END_DATE >= GETDATE()));

--DELETE FROM TERRITORY_MANAGER WHERE TM_ID = 147

--SELECT [Identity] = @@IDENTITY

--TRUNCATE TABLE ADJUSTMENT_DPD

--UPDATE ACCRUED_HEADER SET BONUS_QTY = DISC_BY_VOLUME,BONUS_DISTRIBUTOR = DISC_DIST_BY_VOLUME,AGREE_ACH_BY = 'VOL',LAST_UPDATE = GETDATE()
--WHERE AGREEMENT_NO = '1100/NI/X/2008-14' AND FLAG = 'Q1' 

--UPDATE ACCRUED_DETAIL  SET CAN_RELEASE = 1 WHERE ACHIEVEMENT_ID = ANY(
--SELECT ACHIEVEMENT_ID FROM ACCRUED_HEADER WHERE AGREEMENT_NO = '1100/NI/X/2008-14' AND FLAG = 'Q1'); 

--exec Usp_Get_Total_Qty_Brand_By_Invoice
--@START_DATE = '05/01/2015',
--@END_DATE = '07/31/2015',
--@AGREEMENT_NO = '1100/NI/X/2008-14',
--@COMPUTERNAME = 'NKusnandar'

--SELECT INVH.INVDATE,INVH.INVNUMBER,INVH.PONUMBER,RTRIM(ORD1.VALUE)AS REFERENCE,INVD.ITEM,INVD.[DESC] AS BRANDPACK_NAME,INVD.QTYSHIPPED,ISNULL(CRD.QTYRETURN,0)AS QTYRETURN,INVD.UNITPRICE,INVD.AUDTUSER
--       FROM NI87.dbo.OEINVH INVH INNER JOIN NI87.dbo.OEINVD INVD ON INVH.INVUNIQ = INVD.INVUNIQ
--       INNER JOIN NI87.DBO.OEORDH ORD ON ORD.ORDNUMBER = INVH.ORDNUMBER
--       INNER JOIN NI87.DBO.OEORDHO ORD1 ON ORD.ORDUNIQ = ORD1.ORDUNIQ
--       LEFT OUTER JOIN
--                  (
--		   SELECT CRDH1.INVNUMBER,CRDH1.ITEM,ISNULL(SUM(CRDH1.QTYRETURN),0)AS QTYRETURN
--		   FROM 
--			(								
--                   	  SELECT CRDH.CRDUNIQ,CRDH.INVNUMBER,CRDH.CRDDATE,CRD.ITEM,ISNULL(CRD.QTYRETURN,0)AS QTYRETURN
--                          FROM NI87.DBO.OECRDH CRDH INNER JOIN 
--                          (
--                            SELECT CRDUNIQ,ITEM,ISNULL(SUM(QTYRETURN),0)AS QTYRETURN
--                            FROM NI87.DBO.OECRDD WHERE LINETYPE = 1 AND (RTRIM(ACCTSET) = 'FG' OR RTRIM(ACCTSET) = 'FGST')
--						    GROUP BY CRDUNIQ,ITEM
--                           )CRD ON CRDH.CRDUNIQ = CRD.CRDUNIQ      
--                         )CRDH1
--                   WHERE CRDH1.CRDDATE >= 20150201
--                   GROUP BY CRDH1.INVNUMBER,CRDH1.ITEM    
--                  )CRD
--        ON CRD.INVNUMBER = INVH.INVNUMBER 
--        AND CRD.ITEM = INVD.ITEM
--        WHERE RTRIM(ORD1.OPTFIELD) = 'DTSREF'
--		AND LEN(RTRIM(ORD1.VALUE)) >= 4 AND INVH.INVDATE >= 20150101
--         AND INVH.INVDATE <= 20150731
--		AND (RTRIM(INVD.ACCTSET) = 'FG' OR RTRIM(INVD.ACCTSET) = 'FGST') AND INVD.LINETYPE = 1
--        AND LEN(RIGHT(RTRIM(INVD.ITEM),11)) >= 11
--		AND RTRIM(INVH.CUSTOMER) = 'VEN001IDR'

--UPDATE ACCRUED_HEADER SET DISC_BY_VOLUME = BONUS_QTY,DISC_DIST_BY_VOLUME = BONUS_QTY, 
-- BONUS_DISTRIBUTOR = DISC_DIST_BY_VOLUME,AGREE_ACH_BY = 'VOL',LAST_UPDATE = GETDATE()
-- WHERE AGREEMENT_NO = '1115/NI/X/2008.14' AND FLAG = 'Q3';

-- UPDATE ACCRUED_DETAIL SET DISC_BY_VOLUME = DISC_QTY WHERE ACHIEVEMENT_ID = 
-- ANY(SELECT ACHIEVEMENT_ID FROM ACCRUED_HEADER WHERE AGREEMENT_NO = '1115/NI/X/2008.14' AND FLAG = 'Q3');

--UPDATE ACCRUED_DETAIL SET DISC_QTY = 10,DISC_BY_VOLUME = 10,LEFT_QTY = 10 WHERE ACHIEVEMENT_BRANDPACK_ID = 'VEN001IDR|582/NI/VII/2002.1477009|S2|77009001KD';
--GO
--UPDATE ACCRUED_DETAIL SET DISC_QTY = 12.5,DISC_BY_VOLUME = 12.5,LEFT_QTY = 12.5 WHERE ACHIEVEMENT_BRANDPACK_ID = 'VEN001IDR|582/NI/VII/2002.1400790|S2|00790005LD';
--GO

--UPDATE ACCRUED_HEADER SET AGREE_ACH_BY = 'VOL' WHERE AGREEMENT_NO = '582/NI/VII/2002.14' AND FLAG = 'S2'

--UPDATE ACCRUED_DETAIL SET DISC_BY_VOLUME = 28.125,LEFT_QTY = 28.125 WHERE ACHIEVEMENT_BRANDPACK_ID = 'VEN001IDR|582/NI/VII/2002.1400790|S2|007900000D';
--GO

--UPDATE ACCRUED_DETAIL SET DISC_QTY = 3.3,DISC_BY_VOLUME = 3.3,LEFT_QTY = 3.3 WHERE ACHIEVEMENT_BRANDPACK_ID = 'VEN001IDR|582/NI/VII/2002.1400790|Y|00790005LD';
--GO
--VEN001IDR|582/NI/VII/2002.1400790|Y--\\

--UPDATE ACCRUED_DETAIL SET TOTAL_ACTUAL = 9000  WHERE ACHIEVEMENT_BRANDPACK_ID = 'VEN001IDR|582/NI/VII/2002.1400540|S2|00540001LD'
--UPDATE ACCRUED_HEADER SET TOTAL_ACTUAL = 4750,ACTUAL_DISTRIBUTOR = 4750,BONUS_DISTRIBUTOR = 15.675,BONUS_QTY = 15.675,DISC_BY_VOLUME = 15.675,DISC_DIST_BY_VOLUME = 15.675
--WHERE ACHIEVEMENT_ID = 'VEN001IDR|582/NI/VII/2002.1400790|Y'

--UPDATE ACCRUED_DETAIL SET TOTAL_ACTUAL = 1000,DISC_BY_VOLUME = 3.300,DISC_QTY = 3.300,LEFT_QTY = 3.300  WHERE ACHIEVEMENT_BRANDPACK_ID = 'VEN001IDR|582/NI/VII/2002.1400790|Y|00790005LD'
--UPDATE ACCRUED_HEADER SET AGREE_ACH_BY = 'VOL',DISC_DIST_BY_VOLUME = 731.1,BONUS_DISTRIBUTOR = 731.1,BONUS_QTY = 731.1
-- WHERE AGREEMENT_NO = '118/NI/I/2004.14' AND FLAG = 'S1'

 --UPDATE ACCRUED_HEADER SET AGREE_ACH_BY = 'VOL' WHERE (AGREE_ACH_BY = '' OR AGREE_ACH_BY IS NULL) 
 --AND AGREEMENT_NO = '118/NI/I/2004.14' AND FLAG = 'S1' AND CREATE_BY = 'Admin'

 --UPDATE ACCRUED_DETAIL SET CAN_RELEASE = 1 WHERE ACHIEVEMENT_BRANDPACK_ID = ANY(
 --SELECT ACHIEVEMENT_BRANDPACK_ID FROM ACCRUED_DETAIL WHERE DISC_QTY > 0)
 --AND ACHIEVEMENT_ID = ANY(SELECT ACHIEVEMENT_ID FROM ACCRUED_HEADER WHERE AGREEMENT_NO = '118/NI/I/2004.14' AND FLAG = 'S1' AND DISC_BY_VOLUME > 0);
 --SELECT OPB.* FROM ORDR_PO_BRANDPACK OPB INNER JOIN ORDR_PURCHASE_ORDER PO ON PO.PO_REF_NO = OPB.PO_REF_NO WHERE OPB.BRANDPACK_ID = '007900000D'
 --AND PO.PO_REF_DATE >= '08/01/2014'
 

 -----S1
 --  UPDATE ORDR_OA_BRANDPACK_DISC SET ACHIEVEMENT_BRANDPACK_ID = 'FLA001IDR|070/NI/XI/2001.1400790|S1|00790001LD'
 --   WHERE ACHIEVEMENT_BRANDPACK_ID = 'FLA001IDR|070/NI/XI/2001.1400790|S1|007900000D';

	--UPDATE ORDR_OA_REMAINDING SET ACHIEVEMENT_BRANDPACK_ID = 'FLA001IDR|070/NI/XI/2001.1400790|S1|00790001LD'
 --   WHERE ACHIEVEMENT_BRANDPACK_ID = 'FLA001IDR|070/NI/XI/2001.1400790|S1|007900000D';

 --UPDATE ACCRUED_DETAIL SET ACHIEVEMENT_BRANDPACK_ID = 'FLA001IDR|070/NI/XI/2001.1400790|S1|00790001LD',BRANDPACK_ID = '00790001LD'
 --WHERE ACHIEVEMENT_BRANDPACK_ID = 'FLA001IDR|070/NI/XI/2001.1400790|S1|007900000D';

 
 ----S2
 --   UPDATE ORDR_OA_BRANDPACK_DISC SET ACHIEVEMENT_BRANDPACK_ID = 'FLA001IDR|070/NI/XI/2001.1400790|S2|00790001LD'
 --   WHERE ACHIEVEMENT_BRANDPACK_ID = 'FLA001IDR|070/NI/XI/2001.1400790|S2|007900000D';

	--UPDATE ORDR_OA_REMAINDING SET ACHIEVEMENT_BRANDPACK_ID = 'FLA001IDR|070/NI/XI/2001.1400790|S2|00790001LD'
 --   WHERE ACHIEVEMENT_BRANDPACK_ID = 'FLA001IDR|070/NI/XI/2001.1400790|S2|007900000D';

 --UPDATE ACCRUED_DETAIL SET ACHIEVEMENT_BRANDPACK_ID = 'FLA001IDR|070/NI/XI/2001.1400790|S2|00790001LD',BRANDPACK_ID = '00790001LD'
 --WHERE ACHIEVEMENT_BRANDPACK_ID = 'FLA001IDR|070/NI/XI/2001.1400790|S2|007900000D';


 ----Y
 --   UPDATE ORDR_OA_BRANDPACK_DISC SET ACHIEVEMENT_BRANDPACK_ID = 'FLA001IDR|070/NI/XI/2001.1400790|Y|00790001LD'
 --   WHERE ACHIEVEMENT_BRANDPACK_ID = 'FLA001IDR|070/NI/XI/2001.1400790|Y|007900000D';

	--UPDATE ORDR_OA_REMAINDING SET ACHIEVEMENT_BRANDPACK_ID = 'FLA001IDR|070/NI/XI/2001.1400790|Y|00790001LD'
 --   WHERE ACHIEVEMENT_BRANDPACK_ID = 'FLA001IDR|070/NI/XI/2001.1400790|Y|007900000D';

 --UPDATE ACCRUED_DETAIL SET ACHIEVEMENT_BRANDPACK_ID = 'FLA001IDR|070/NI/XI/2001.1400790|Y|00790001LD',BRANDPACK_ID = '00790001LD'
 --WHERE ACHIEVEMENT_BRANDPACK_ID = 'FLA001IDR|070/NI/XI/2001.1400790|Y|007900000D';
 ----GO

 ----VENUS MICROTHIOL HEADER -SALAH
 --UPDATE ACCRUED_HEADER SET DISC_BY_VOLUME = 10,DISC_DIST_BY_VOLUME = 10,BONUS_DISTRIBUTOR = 10,BONUS_QTY = 10 WHERE ACHIEVEMENT_ID = 'VEN001IDR|582/NI/VII/2002.1477009|S2'
 ---- VENUS NUFARIS
 -- UPDATE ACCRUED_HEADER SET DISC_BY_VOLUME = 40.625,DISC_DIST_BY_VOLUME = 40.625,BONUS_DISTRIBUTOR = 40.625,BONUS_QTY = 40.625 WHERE ACHIEVEMENT_ID = 'VEN001IDR|582/NI/VII/2002.1400790|S2'

 --UPDATE ACCRUED_HEADER SET TOTAL_ACTUAL = 750,ACTUAL_DISTRIBUTOR = 750,DISC_DIST_BY_VOLUME = 6.6,DISC_BY_VOLUME = 6.6,BONUS_DISTRIBUTOR = 6.6,BONUS_QTY = 6.6
 --WHERE ACHIEVEMENT_ID = 'VEN001IDR|582/NI/VII/2002.1477009|Y'

 --UPDATE ACCRUED_DETAIL SET DISC_BY_VOLUME = 6.6,DISC_QTY = 6.6,LEFT_QTY = 6.6,TOTAL_ACTUAL = 750 WHERE ACHIEVEMENT_BRANDPACK_ID = 'VEN001IDR|582/NI/VII/2002.1477009|Y|77009001KD';
 --GO

 --UPDATE ACCRUED_DETAIL SET CAN_RELEASE = 1,RELEASE_QTY = DISC_QTY,DISC_BY_VOLUME = DISC_QTY WHERE ACHIEVEMENT_BRANDPACK_ID = 'END001IDR|118/NI/I/2004.1477240|S1|77240001KD';

 --UPDATE ACCRUED_DETAIL SET CAN_RELEASE = 1 WHERE ACHIEVEMENT_BRANDPACK_ID = 'END001IDR|118/NI/I/2004.1477230|S1|77230001KD';

 --UPDATE ACCRUED_DETAIL SET DISC_QTY = 90.324,DISC_BY_VOLUME = 90.324,LEFT_QTY = 90.324, CAN_RELEASE = 1 WHERE ACHIEVEMENT_BRANDPACK_ID = 'END001IDR|118/NI/I/2004.1400010|Y|00010200MD'

 --UPDATE ACCRUED_HEADER SET DISC_DIST_BY_VOLUME = 731.1,DISC_BY_VOLUME = 731.1,BONUS_DISTRIBUTOR = 731.1,BONUS_QTY = 731.1
 --WHERE ACHIEVEMENT_ID = 'END001IDR|118/NI/I/2004.1430896|S1'

 --UPDATE ACCRUED_DETAIL SET CAN_RELEASE = 1,RELEASE_QTY = DISC_QTY,DISC_BY_VOLUME = DISC_QTY WHERE ACHIEVEMENT_BRANDPACK_ID = 'END001IDR|118/NI/I/2004.1477240|S1|77240001KD'

 --UPDATE ACCRUED_HEADER SET AGREE_ACH_BY = 'VOL',DISC_DIST_BY_VOLUME = 22.848,DISC_BY_VOLUME = 22.848,BONUS_DISTRIBUTOR = 22.848,BONUS_QTY = 22.848 
 --WHERE ACHIEVEMENT_ID = 'END001IDR|118/NI/I/2004.1477290|S1'

 -- UPDATE ACCRUED_HEADER SET AGREE_ACH_BY = 'VOL',DISC_DIST_BY_VOLUME = 14.742,DISC_BY_VOLUME = 14.742,BONUS_DISTRIBUTOR = 14.742,BONUS_QTY = 14.742 
 --WHERE ACHIEVEMENT_ID = 'END001IDR|118/NI/I/2004.1411024|S1'

 --UPDATE ACCRUED_DETAIL SET CAN_RELEASE = 1,DISC_BY_VOLUME = DISC_QTY,RELEASE_QTY = DISC_QTY WHERE ACHIEVEMENT_BRANDPACK_ID ='END001IDR|118/NI/I/2004.1477240|S1|77240001KD'; 

 --UPDATE ACCRUED_DETAIL SET CAN_RELEASE = 1,DISC_BY_VOLUME = DISC_QTY,LEFT_QTY  = DISC_QTY WHERE ACHIEVEMENT_BRANDPACK_ID = 'END001IDR|118/NI/I/2004.1477230|S1|77230001KD'

 --UPDATE ACCRUED_HEADER SET DISC_BY_VOLUME = 267.878,DISC_DIST_BY_VOLUME = 267.878,BONUS_DISTRIBUTOR = 267.878,BONUS_QTY = 267.878,
 --AGREE_ACH_BY = 'VOL' WHERE ACHIEVEMENT_ID = 'END001IDR|118/NI/I/2004.1477018|S2';

 
 -- UPDATE ACCRUED_HEADER SET DISC_BY_VOLUME = 225,DISC_DIST_BY_VOLUME = 225,BONUS_DISTRIBUTOR = 225,BONUS_QTY = 225,
 --AGREE_ACH_BY = 'VOL' WHERE ACHIEVEMENT_ID IN('END001IDR|118/NI/I/2004.1477230|S2','END001IDR|118/NI/I/2004.1477240|S2');

 --UPDATE ACCRUED_DETAIL SET BRANDPACK_ID = '00790001LD',ACHIEVEMENT_BRANDPACK_ID = ACHIEVEMENT_ID + '|00790001LD'
 --WHERE ACHIEVEMENT_BRANDPACK_ID = 'CIN003IDR|1261/NI/XI/2008.1400790|Y|007900000D'

 -- UPDATE ACCRUED_DETAIL SET BRANDPACK_ID = '00790001LD',ACHIEVEMENT_BRANDPACK_ID = ACHIEVEMENT_ID + '|00790001LD'
 --WHERE ACHIEVEMENT_BRANDPACK_ID = 'CIN003IDR|1261/NI/XI/2008.1400790|S1|007900000D'

  --UPDATE ACCRUED_DETAIL SET DISC_QTY = 1159.920,DISC_BY_VOLUME = 1159.920,LEFT_QTY  = 1159.920
  -- WHERE ACHIEVEMENT_BRANDPACK_ID = 'BUM006000F|1093/NI/X/08-1L.1400601|Q2|00601001LD'

  --   UPDATE ACCRUED_DETAIL SET DISC_QTY = 1159.920,DISC_BY_VOLUME = 1159.920,LEFT_QTY  = 1159.920
  -- WHERE ACHIEVEMENT_BRANDPACK_ID = 'BUM006000|1093/NI/X/08-1L.1400601|Q2|00601001LD'

   --   UPDATE ACCRUED_DETAIL SET DISC_QTY = 44.750,DISC_BY_VOLUME = 44.750,LEFT_QTY  = 44.750
   --WHERE ACHIEVEMENT_BRANDPACK_ID = 'BUM006000D|1093/NI/X/08-200ML.140060200|Q2|0060200200MD'

   --BUM006000|1093/NI/X/08-1L.1400601|Q2

   --     UPDATE ACCRUED_DETAIL SET DISC_QTY = 1159.920,DISC_BY_VOLUME = 1159.920,LEFT_QTY  = 0
   --WHERE ACHIEVEMENT_BRANDPACK_ID = 'BUM006000|1093/NI/X/08-1L.1400601|Q2|00601001LD'

   
   --   UPDATE ACCRUED_DETAIL SET DISC_QTY = 0,DISC_BY_VOLUME = 0,LEFT_QTY  = 0,TOTAL_ACTUAL = 0,CAN_RELEASE = 0
   --WHERE ACHIEVEMENT_BRANDPACK_ID = 'MAS003IDR|0853/NI/V/2011.1400010|S1|00010020LD'

   --      UPDATE ACCRUED_DETAIL SET DISC_QTY = 0,DISC_BY_VOLUME = 0,LEFT_QTY  = 0,TOTAL_ACTUAL = 0,CAN_RELEASE = 0
   --WHERE ACHIEVEMENT_BRANDPACK_ID = 'MAS003IDR|0853/NI/V/2011.1400010|Y|00010020LD'

   --SELECT * FROM ACCRUED_DETAIL WHERE ACHIEVEMENT_BRANDPACK_ID = 'MAS003IDR|0853/NI/V/2011.1400010|S1|00010020LD'
   
   --SELECT * FROM ACCRUED_DETAIL WHERE ACHIEVEMENT_BRANDPACK_ID = 'MAS003IDR|0853/NI/V/2011.1400010|Y|00010020LD'


   ------------================================PR kalau ada pak indra=======================
 --SELECT SUBSTRING(REPLACE(RIGHT(RTRIM(INV.ITEM),14),'-',''),2,9)AS BRANDPACK_ID,INV.BRANDPACK_NAME,
 --     INV.QTYSHIPPED - INV.QTYRETURN AS QTY,RTRIM(INV.INVNUMBER)AS INVNUMBER, RTRIM(INV.PONUMBER) AS PONUMBER,RTRIM(INV.REFERENCE)AS REFERENCE,INV.INVDATE,INV.UNITPRICE, 
	-- (INV.QTYSHIPPED - INV.QTYRETURN)* INV.UNITPRICE AS INV_AMOUNT,INV.AUDTUSER
 --    FROM
 --     (
 --      SELECT INVH.INVDATE,INVH.INVNUMBER,INVH.PONUMBER,RTRIM(ORD1.VALUE)AS REFERENCE,INVD.ITEM,INVD.[DESC] AS BRANDPACK_NAME,INVD.QTYSHIPPED,ISNULL(CRD.QTYRETURN,0)AS QTYRETURN,INVD.UNITPRICE,INVD.AUDTUSER
 --      FROM NI87.dbo.OEINVH INVH INNER JOIN  NI87.dbo.OEINVD INVD ON INVH.INVUNIQ = INVD.INVUNIQ
	--   ( SELECT ITEM,INVUNIQ,ISNULL(SUM(QTYSHIPPED),0) - ISNULL(SUM(QTYBACKORD),0) AS QTYSHIPPED FROM NI87.dbo.OEINVD  WHERE (RTRIM(ACCTSET) = 'FG' OR RTRIM(ACCTSET) = 'FGST') AND LINETYPE = 1 AND LEN(RIGHT(RTRIM(ITEM),11)) >= 11 GROUP BY ITEM,INVUNIQ)INVD1
	  
 --      INNER JOIN NI87.DBO.OEORDH ORD ON ORD.ORDNUMBER = INVH.ORDNUMBER
 --      INNER JOIN NI87.DBO.OEORDHO ORD1 ON ORD.ORDUNIQ = ORD1.ORDUNIQ
 --      LEFT OUTER JOIN
 --                 (
	--	   SELECT CRDH1.INVNUMBER,CRDH1.ITEM,ISNULL(SUM(CRDH1.QTYRETURN),0)AS QTYRETURN
	--	   FROM 
	--		(								
 --                  	  SELECT CRDH.CRDUNIQ,CRDH.INVNUMBER,CRDH.CRDDATE,CRD.ITEM,ISNULL(CRD.QTYRETURN,0)AS QTYRETURN
 --                         FROM NI87.DBO.OECRDH CRDH INNER JOIN 
 --                         (
 --                           SELECT CRDUNIQ,ITEM,ISNULL(SUM(QTYRETURN),0)AS QTYRETURN
 --                           FROM NI87.DBO.OECRDD WHERE LINETYPE = 1 AND (RTRIM(ACCTSET) = 'FG' OR RTRIM(ACCTSET) = 'FGST')
	--					    GROUP BY CRDUNIQ,ITEM
 --                          )CRD ON CRDH.CRDUNIQ = CRD.CRDUNIQ      
 --                        )CRDH1
 --                  WHERE CRDH1.CRDDATE >=   CAST(20150701 AS VARCHAR(20)) 
 --                   GROUP BY CRDH1.INVNUMBER,CRDH1.ITEM    
 --                 )CRD
 --       ON CRD.INVNUMBER = INVH.INVNUMBER 
 --       AND CRD.ITEM = INVD.ITEM
 --       WHERE RTRIM(ORD1.OPTFIELD) = 'DTSREF'
 --       AND LEN(RTRIM(ORD1.VALUE)) >= 4
 --       AND INVH.INVDATE >=  + CAST(20150701 AS VARCHAR(20))   
 --       AND INVH.INVDATE <=  + CAST(20150731 AS VARCHAR(20)) 
	--	AND (RTRIM(INVD.ACCTSET) = 'FG' OR RTRIM(INVD.ACCTSET) = 'FGST') AND INVD.LINETYPE = 1
 --       AND LEN(RIGHT(RTRIM(INVD.ITEM),11)) >= 11
 --      )INV;

 
SELECT * FROM NI87.DBO.OEINVH WHERE RTRIM(INVNUMBER) = 'IN19062635'
 -----------===============QUERY Credit Return---==============================================================
 ----POKDI/0415/0013.A
 SELECT CRDH1.INVNUMBER,CRDH1.ITEM,ISNULL(SUM(CRDH1.QTYRETURN),0)AS QTYRETURN
		   FROM 
			(								
                   	  SELECT CRDH.CRDUNIQ,CRDH.INVNUMBER,CRDH.CRDDATE,CRD.ITEM,ISNULL(CRD.QTYRETURN,0)AS QTYRETURN
                          FROM NI87.DBO.OECRDH CRDH INNER JOIN 
                          (
                            SELECT CRDUNIQ,ITEM,ISNULL(SUM(QTYRETURN),0)AS QTYRETURN
                            FROM NI87.DBO.OECRDD WHERE LINETYPE = 1 AND (RTRIM(ACCTSET) = 'FG' OR RTRIM(ACCTSET) = 'FGST' OR RTRIM(ACCTSET) = 'FGTOLL')
						    GROUP BY CRDUNIQ,ITEM
                           )CRD ON CRDH.CRDUNIQ = CRD.CRDUNIQ      
                         )CRDH1
                   WHERE RTRIM(CRDH1.INVNUMBER) IN('IN19073019') 
                    GROUP BY CRDH1.INVNUMBER,CRDH1.ITEM    
                  --)CRD
				  GO
--===============================================================================================


--------========================QUERY INVOICE by INVNumber==============================================================

				   SELECT INVH.INVUNIQ, INVH.INVDATE,INVH.INVNUMBER,INVH.PONUMBER,
				   RTRIM(ORD1.VALUE)AS REFERENCE,
				   INVD.ITEM,INVD.[DESC] AS BRANDPACK_NAME,INVD.QTYSHIPPED,
				   ISNULL(CRD.QTYRETURN,0)AS QTYRETURN,
				   INVD.UNITPRICE,INVD.AUDTUSER
       FROM NI87.dbo.OEINVH INVH INNER JOIN NI87.dbo.OEINVD INVD ON INVH.INVUNIQ = INVD.INVUNIQ
       INNER JOIN NI87.DBO.OEORDH ORD ON ORD.ORDNUMBER = INVH.ORDNUMBER
       INNER JOIN NI87.DBO.OEORDHO ORD1 ON ORD.ORDUNIQ = ORD1.ORDUNIQ
       LEFT OUTER JOIN
                  (
		   SELECT CRDH1.INVNUMBER,CRDH1.ITEM,ISNULL(SUM(CRDH1.QTYRETURN),0)AS QTYRETURN
		   FROM 
			(								
                   	  SELECT CRDH.CRDUNIQ,CRDH.INVNUMBER,CRDH.CRDDATE,CRD.ITEM,ISNULL(CRD.QTYRETURN,0)AS QTYRETURN
                          FROM NI87.DBO.OECRDH CRDH INNER JOIN 
                          (
                            SELECT CRDUNIQ,ITEM,ISNULL(SUM(QTYRETURN),0)AS QTYRETURN
                            FROM NI87.DBO.OECRDD WHERE LINETYPE = 1 AND (RTRIM(ACCTSET) = 'FG' OR RTRIM(ACCTSET) = 'FGST')
						    GROUP BY CRDUNIQ,ITEM
                           )CRD ON CRDH.CRDUNIQ = CRD.CRDUNIQ      
                         )CRDH1
                   WHERE RTRIM(CRDH1.INVNUMBER) IN('IN19072955') 
                    GROUP BY CRDH1.INVNUMBER,CRDH1.ITEM    
                  )CRD
        ON CRD.INVNUMBER = INVH.INVNUMBER 
        AND CRD.ITEM = INVD.ITEM
        WHERE RTRIM(ORD1.OPTFIELD) = 'DTSREF'
        AND LEN(RTRIM(ORD1.VALUE)) >= 4
        AND (RTRIM(INVD.ACCTSET) = 'FG' OR RTRIM(INVD.ACCTSET) = 'FGST') AND INVD.LINETYPE = 1
        AND LEN(RIGHT(RTRIM(INVD.ITEM),11)) >= 11
		AND RTRIM(INVH.INVNUMBER) IN('IN19072955') 

		GO
		--=========================================================================================================
		
		---====================qUERY ke INVOICE Header dengan PO Number---------------------------
		SELECT * FROM NI87.DBO.OEINVH WHERE RTRIM(PONUMBER) = '01/SUT-PB/I/2021' 

		SELECT invuniq,INVNUMBER,INVDATE FROM NI87.DBO.OEINVH WHERE RTRIM(PONUMBER) = '02/PSM/I/19' 

		---====================qUERY ke INVOICE DETAIL dengan no invoice IN('IN15125113.','IN15125113') 
		SELECT * FROM  NI87.dbo.OEINVD WHERE INVUNIQ  IN(1084851)	
		
		SELECT * FROM  NI87.dbo.OEINVD WHERE INVUNIQ  IN(1079734)	

			SELECT * FROM ORDR_PO_BRANDPACK WHERE PO_REF_NO = '17/01/085'
		GO
		---=============================================================================================
		
		--exec Usp_Create_Temp_Invoice_Table @COMPUTERNAME = 'NKusnandar', 
		--@DEC_START_DATE = 20161201, @DEC_END_DATE = 20170131
		--SELECT * FROM tempdb..##t_select_invoice_nKusnandar WHERE ponumber = 'SAP/2016/11/017A'
		--DROP TABLE tempdb..##t_select_invoice_nKusnandar
  --SELECT CRDH.CRDUNIQ,CRDH.INVNUMBER,CRDH.CRDDATE,CRD.ITEM,ISNULL(CRD.QTYRETURN,0)AS QTYRETURN
  --                        FROM NI87.DBO.OECRDH CRDH INNER JOIN 
  --                        (
  --                          SELECT CRDUNIQ,ITEM,ISNULL(SUM(QTYRETURN),0)AS QTYRETURN
  --                          FROM NI87.DBO.OECRDD WHERE LINETYPE = 1 AND (RTRIM(ACCTSET) = 'FG' OR RTRIM(ACCTSET) = 'FGST')
							
		--				    GROUP BY CRDUNIQ,ITEM
  --                         )CRD ON CRDH.CRDUNIQ = CRD.CRDUNIQ      
  --                       )CRDH1
  --                 WHERE CRDH.INVNUMBER IN('IN15125113.','IN15125113') 
		--		   order by INVNUMBER DESC;
  --                  GROUP BY CRDH1.INVNUMBER,CRDH1.ITEM    

		--		   select * from NI87.DBO.OECRDH WHERE INVUNIQ IN(664558,660292)
		--		   select * from NI87.DBO.OECRDH WHERE INVNUMBER IN('IN15125113.','IN15125113') 

		--00038639
		--19/01/103
		--19/04/006
SELECT * FROM NI87.DBO.OEORDH WHERE PONUMBER IN('010/NU/DS-SMD/I/2019A');   
SELECT * FROM NI87.DBO.OEORDD WHERE ORDUNIQ IN (1999617);       
SELECT * FROM NI87.DBO.OEORDD WHERE ORDUNIQ IN (2029947);
SELECT * FROM ni87.DBO.OEORDH WHERE ORDUNIQ = '2002304'

--SELECT * FROM NI87.DBO.OEORDHO WHERE ORDUNIQ = 2002304
--SELECT * FROM NI87.DBO.OEORDHO WHERE ORDUNIQ = 2227323
--UPDATE NI87.DBO.OEORDHO SET VALUE = '00044437' WHERE ORDUNIQ = 2227323 AND OPTFIELD = 'DTSREF' ;

--SELECT CRDH1.INVNUMBER,CRDH1.ITEM,ISNULL(SUM(CRDH1.QTYRETURN),0)AS QTYRETURN
--		   FROM 
--			(								
                   	  SELECT CRDH.CRDNUMBER,CRDH.CRDUNIQ,CRDH.INVNUMBER,CRDH.CRDDATE,CRD.ITEM,ISNULL(CRD.QTYRETURN,0)AS QTYRETURN,CRDH.AUDTDATE,CRDH.AUDTUSER
                          FROM NI87.DBO.OECRDH CRDH INNER JOIN 
                          (
                            SELECT CRDUNIQ,ITEM,ISNULL(SUM(QTYRETURN),0)AS QTYRETURN
                            FROM NI87.DBO.OECRDD WHERE LINETYPE = 1 AND (RTRIM(ACCTSET) = 'FG' OR RTRIM(ACCTSET) = 'FGST')
						    GROUP BY CRDUNIQ,ITEM
                           )CRD ON CRDH.CRDUNIQ = CRD.CRDUNIQ   
						  WHERE RTRIM(CRDH.INVNUMBER) IN('IIN16082936')   
--                         )CRDH1
--                   WHERE CRDH1.INVNUMBER IN('IN151225001.') 
--                    GROUP BY CRDH1.INVNUMBER,CRDH1.ITEM    
--                  --)CRD
--				  GO
				   

--				    SELECT OOBD.OA_BRANDPACK_ID,ISNULL(SUM(OOBD.DISC_QTY),0) - ISNULL(SUM(AT.ADJ_DISC_QTY) ,0) AS TOTAL_DISC_QTY FROM ORDR_OA_BRANDPACK_DISC OOBD  
--                                         LEFT OUTER JOIN ADJUSTMENT_TRANS AT ON AT.OA_BRANDPACK_DISC_ID = OOBD.OA_BRANDPACK_DISC_ID  
--                                         WHERE OOBD.OA_BRANDPACK_ID = ANY(  
--                                                                           SELECT OA_BRANDPACK_ID FROM ORDR_OA_BRANDPACK  
--                                                                           WHERE PO_BRANDPACK_ID = ANY(SELECT PO_BRANDPACK_ID FROM ORDR_PO_BRANDPACK WHERE PO_REF_NO = '016/II/PO/CIP/2016')  
--                                                                          )  
--                                          GROUP BY OOBD.OA_BRANDPACK_ID 

--										  SELECT * FROM ORDR_OA_BRANDPACK_DISC WHERE OA_BRANDPACK_ID = ANY(  
--                                                                           SELECT OA_BRANDPACK_ID FROM ORDR_OA_BRANDPACK  
--                                                                           WHERE PO_BRANDPACK_ID = ANY(SELECT PO_BRANDPACK_ID FROM ORDR_PO_BRANDPACK WHERE PO_REF_NO = '016/II/PO/CIP/2016')  
--                                                                          )  

--SELECT * FROM ADJUSTMENT_TRANS WHERE OA_BRANDPACK_DISC_ID = ANY(
--										  SELECT OA_BRANDPACK_DISC_ID FROM ORDR_OA_BRANDPACK_DISC WHERE OA_BRANDPACK_ID = ANY(  
--                                                                           SELECT OA_BRANDPACK_ID FROM ORDR_OA_BRANDPACK  
--                                                                           WHERE PO_BRANDPACK_ID = ANY(SELECT PO_BRANDPACK_ID FROM ORDR_PO_BRANDPACK WHERE PO_REF_NO = '016/II/PO/CIP/2016')  
--                                                                          )
--																		  )
																		  
																		  
--SELECT * FROM SPPB_BRANDPACK WHERE OA_BRANDPACK_ID =    ANY(  SELECT OA_BRANDPACK_ID FROM ORDR_OA_BRANDPACK  
--                                                              WHERE PO_BRANDPACK_ID = ANY(SELECT PO_BRANDPACK_ID FROM ORDR_PO_BRANDPACK WHERE PO_REF_NO = '016/II/PO/CIP/2016')  
--                                                             )  

--SELECT * FROM ADJUSTMENT_TRANS ORDER BY CreatedDate asc;

--exec createtemptable invoice

SELECT * FROM NI109.dbo.ICCATG WHERE [desc] LIKE '%glove%'

SELECT * FROM NI109.dbo.ICITEM WHERE [desc] LIKE '%glove%'

--SELECT PACK_ID,BRANDPACK_NAME FROM( 
--SELECT DISTINCT RTRIM(SEGMENT4) + '' + RTRIM(SEGMENT3) AS PACK_ID,RTRIM([DESC]) AS BRANDPACK_NAME FROM NI109.dbo.ICITEM
--WHERE INACTIVE = 0 AND (RTRIM(ITEMBRKID) = 'FG' OR RTRIM(ITEMBRKID) = 'FGST') AND [DESC] LIKE '%@%')IC
--WHERE BRANDPACK_NAME LIKE '%CO-PACK%'

--SELECT * FROM BRND_BRANDPACK WHERE PACK_ID IN('25CPD','50CPD')

--SELECT PACK_ID,BRANDPACK_NAME FROM( 
--SELECT DISTINCT RTRIM(SEGMENT4) + '' + RTRIM(SEGMENT3) AS PACK_ID,RTRIM([DESC]) AS BRANDPACK_NAME FROM NI109.dbo.ICITEM
--WHERE INACTIVE = 0 AND (RTRIM(ITEMBRKID) = 'FG' OR RTRIM(ITEMBRKID) = 'FGST') AND [DESC] LIKE '%@%')IC
--WHERE NOT EXISTS(SELECT PACK_ID FROM Nufarm.dbo.BRND_PACK WHERE PACK_ID = IC.PACK_ID)

--CORNBELT @ 50 ML - D
--CORNBELT
--CO-PACK CORNBELT @ 50 ML - D
--0008450CPD
--UPDATE BRND_BRANDPACK SET BRANDPACK_NAME = 'CO-PACK CORNBELT @ 50 ML - D'
--WHERE BRANDPACK_ID = '0008450CPD'
--UPDATE BRND_BRANDPACK SET BRANDPACK_NAME = 'CO-PACK SERENDY 28 WP @ 25 GR - D'
--WHERE BRANDPACK_ID = '0090325CPD';

--SET NOCOUNT ON; 
--SELECT * FROM ##T_BRANDPACK BP WHERE NOT EXISTS( 
-- SELECT BRANDPACK_ID_DTS FROM COMPARE_ITEM WHERE BRANDPACK_ID_DTS = BP.BRANDPACK_ID_DTS 
-- AND BRANDPACK_ID_ACCPAC = BP.BRANDPACK_ID_ACCPAC) AND BP.BRANDPACK_ID_DTS IS NOT NULL 
-- AND BP.BRANDPACK_ID_ACCPAC IS NOT NULL AND (BP.BRANDPACK_NAME LIKE '%-D' OR BP.BRANDPACK_NAME LIKE '%- D') ;

-- SELECT * FROM BRND_BRAND WHERE BRAND_NAME like '%AT%';
-- SELECT * FROM ##T_BRANDPACK  WHERE BRANDPACK_NAME like '%MESO%';
-- SELECT * FROM ##T_BRANDPACK  WHERE BRANDPACK_NAME like '%ATRADEX 550%';

--SELECT * FROM nUFARM.dbo.ORDR_PO_BRANDPACK  WHERE PO_REF_NO = '007/8M/RUB/18'

--UPDATE AGREE_AGREEMENT SET END_DATE = '09/30/2020' WHERE RTRIM(LTRIM(AGREEMENT_NO)) IN(
--'0013/NI/I/2010.20','0013/NI/I/2010.20A','1549/NI/IX/2018.20','1261/NI/XI/2008.20','1017/NI/VIII/2010.20',
--'2620/NI/XII/2015.20','1713/NI/X/2018.20','0836/NI/IV/15.20','0223/NI/III/2010.20','167/NI/III/2003.20',
--'0244/NI/II/2008.20','3533/NI/XII/2014.20','2053/NI/X/2012.20','362/NI/III/2002.20','407/NI/VI/2003.20',
--'1578/NI/IX/2018.20','1212/NI/VIII/2017.20','0906/NI/IX/2009.20','2403/NI/XI/2019.20','0424/NI/II/2019.20',
--'2316/NI/VIII/14.20','2351/NI/XI/2019.20','0527/NI/IV/2016.20','0072/NI/I/2016.20','543/NI/VI/2004.20',
--'940/NI/X/2004.20','0359/NI/II/2016.20','0802/NI/VII/2008.20','0853/NI/V/2011.20','1035/NI/VIII/10.20',
--'01099/NI/VII/2009.20','0448/NI/III/20.20','0133/NI/I/2017.20','2039/NI/VI/2014.20','0813/NI/VII/2008.20',
--'1842/NI/X/2018.20','065/NI/X/2001.20','984/NI/VIII/2007.20','984/NI/VIII/2007.20A','118/NI/I/2004.20',
--'2477/NI/X/2013.20','2890/NI/X/2014.20','799/NI/VIII/2003.20','0235/NI/II/2011.20','01037/NI/IX/2009.20',
--'821/NI/VIII/2005.20','657/NI/V/2004.20','0243/NI/II/2008.20','820/NI/VIII/2005.20','0515/NI/III/2019.20',
--'0630/NI/V/2018.20','LOK002IDR.20','1311/NI/VII/2016.20','1275/NI/VII/19.20B','1275/NI/VII/19.20D',
--'1275/NI/VII/19.20','1275/NI/VII/19.20A','1275/NI/VII/19.20C','1275/NI/VII/19.20E','0274/NI/II/2019.20',
--'409/NI/I/2003-20-BJM','409/NI/I/2003-20-JABAR','409/NI/I/2003-20-KALTENG','409/NI/I/2003-20-KALTIM',
--'409/NI/I/2003-20-MEDAN','409/NI/I/2003-20-MKS','409/NI/I/2003-20-NUSRA','409/NI/I/2003-20-PALU',
--'409/NI/I/2003-20-PTK','409/NI/i/2003-20-RIAU','409/NI/I/2003-20-SULTRA','0609/NI/III/2007.20',
--'1055/NI/XI/2006.20','1838/NI/X/2018.20','0361/NI/III/2007.20','0549/NI/III/2012.20','231/NI/III/2002.20',
--'800/NI/VI/2003.20','555/NI/V/2004.20','796/NI/VIII/2003.20','1153/NI/XI/2008.20','305A/NI/V/2001.20',
--'0219/NI/I/2006.20','1048/NI/XII/2008.20','1059/NI/VII/2018.20A','1059/NI/VII/2018.20','1059/NI/VII/2018.20B',
--'00528/NI/IV/2009.20','986/NI/VIII/2007.20','0011/NI/I/2006.20B','0011/NI/I/2006.20','0054/NI/I/2018.20',
--'TUJ001IDR.20','582/NI/VII/2002.20','348/NI/III/2002.20','0831/NI/V/2017.20','2809/NI/XI/2013.20','652/NI/VI/2005.20',
--'0242/NI/II/2008.20','432/NI/VII/2003.20');

--SELECT * FROM AGREE_AGREEMENT WHERE YEAR(START_DATE) = 2020

--SELECT DISTINCT(START_DATE),END_DATE FROM AGREE_AGREEMENT WHERE YEAR(START_DATE) = 2020

--SELECT * FROM AGREE_AGREEMENT WHERE START_DATE = '2020-08-08 00:00:00.000'
--OR END_DATE = '2021-08-07 00:00:00.000'

--UPDATE AGREE_AGREEMENT SET START_DATE = '08/01/2020',END_DATE = '09/30/2020' WHERE AGREEMENT_NO = '0422/NI/II/2013.20'

--SELECT * FROM BRND_PRICE_HISTORY WHERE PRICE_TAG = '00074020LD|4/26/2021'
--UPDATE BRND_PRICE_HISTORY SET PRICE = 61100
--WHERE PRICE_TAG = '00074020LD|4/26/2021'


--SELECT * FROM dprd.dbo.uv_kios WHERE IDKios Like '%036A/186/TIGA%' 051136
--SELECT * FROM UserPriviledge WHERE UserName LIKE '%NURSYAMSIH%'
--SELECT * FROM dprd.dbo.uv_kios WHERE IDKios Like '%009/45/SARANA TANI DRY%' 

--SELECT * FROM DPRD.dbo.RLP_Target_Detail_1 WHErE Kioscode LIKE '%038/4790/VENUS%'
--UPDATE dprd.dbo.RLP_Target_detail_1
--SET KiosCode = '054/5223/PT. TRIMITRA AGUNG CEMERLANG' WHERE KiosCode = '055/5076/PT. TRIMITRA AGUNG CEMERLANG'

--DELETE dprd.dbo.RLP_Target_Detail_1 where IDApp in(2137,2138,2139)
--Use Dprd;
--GO
--DELETE FROM dprd.dbo.AppGeneral WHERE CodeApp = '038/019|RLP2020_2021|13';
--DELETE FROM dprd.dbo.RLP_Target_Detail_1 WHERE FKCode = '038/019|RLP2020_2021|13';
--GO

use Nufarm;
GO

--SELECT * FROM BRND_DISC_HEADER WHERE PROGRAM_ID = '071021A-RUPNAS'

--SELECT * FROM BRND_DISC_HEADER WHERE PROGRAM_ID = '071021-RUPNAS'

--UPDATE BRND_DISC_HEADER SET END_DATE = '10/25/2021' WHERE PROGRAM_ID IN('071021A-RUPNAS','071021-RUPNAS');

--SELECT * FROM ACHIEVEMENT_HEADER WHERE AGREEMENT_NO = '1083/NI/X/08.20' AND FLAG = 'F3'

--SELECT * FROM ORDR_PO_BRANDPACK WHERE BRANDPACK_ID = '00055020LD' 
--AND PO_REF_NO in('004/8M/NI/21','008/8M/NI/21','009/8M/NI/21A','010/8M/NI/21A')

--SELECT * FROM ORDR_PO_BRANDPACK WHERE BRANDPACK_ID = '00540020LD' 
--AND PO_REF_NO in('014/SAP/PO/II/2021','014/SAP/PO/II/2021A','026/SAP/PO/III/2021','026/SAP/PO/III/2021A','026/SAP/PO/III/2021B')
--UPDATE ORDR_PO_BRANDPACK SET ExCludeDPD = 1  WHERE BRANDPACK_ID = '00055020LD' 
--AND PO_REF_NO in('004/8M/NI/21','008/8M/NI/21','009/8M/NI/21A','010/8M/NI/21A')

--SELECT * FROM ##T_Master_PO_IDNJWLF662 
--WHERE BRANDPACK_ID = '00055020LD' 

--UPDATE ORDR_PO_BRANDPACK SET PLANTATION_ID = NULL,TERRITORY_ID = NULL,DESCRIPTIONS = 'PRICE FROM FREE MARKET' WHERE PO_BRANDPACK_ID = 'POSMD/0721/0050006020020LD'

--UPDATE AppContacts SET TMCode = '051136' WHERE FKCode = '036A/186/Tiga Tani Putra' OR CodeApp = '036A/186/Tiga Tani Putra'
--UPDATE AppContacts SET TMCode = '051136' WHERE FKCode = '036A/295/TOKO MAKMUR JAYA' OR CodeApp = '036A/295/TOKO MAKMUR JAYA'
--SELECT * FROM AGREE_BRAND_INCLUDE WHERE AGREEMENT_NO = '1100/NI/X/2008-20'

--SELECT * FROM AGREE_AGREEMENT WHERE AGREEMENT_NO = '1100/NI/X/2008-20'

--USE dprd;
--go

--SELECT * FROM BRND_BRAND WHERE BRAND_NAME LIKE 'marvel%'
--SELECT * FROM DIST_PLANT_PRICE WHERE PRICE_TAG = '00070004LD|6/4/2023|13/4/2023|044A-01283|MAS003IDR'
--UPDATE DIST_PLANT_PRICE SET END_DATE = '01/30/2023'
--WHERE PRICE_TAG = '00070004LD|8/1/2023|31/1/2023|042-00532|PAN102IDR'

SELECT * FROM ACHIEVEMENT_HEADER WHERE AGREEMENT_NO = '1159/NI/VIII/10.22'
SET DEADLOCK_PRIORITY NORMAL; SET NOCOUNT ON; SET ANSI_WARNINGS OFF ;
SELECT ACRH.ACH_HEADER_ID,ACRH.DISTRIBUTOR_ID,DR.DISTRIBUTOR_NAME,ACRH.AGREEMENT_NO,AA.START_DATE,AA.END_DATE,ACRH.FLAG,ACRH.BRAND_ID,BB.BRAND_NAME,
ISNULL(AP.AVGPRICE,0) AS AVG_PRICE_FM,ISNULL(AP.AVGPRICE_PL,0) AS AVG_PRICE_PL,ACRH.TARGET_FM,ACRH.TARGET_PL,ISNULL(AP.AVGPRICE,0) * ACRH.TOTAL_TARGET AS TARGET_VALUE,ACRH.TOTAL_PO_VALUE,ACRH.TOTAL_TARGET,
 ACRH.TOTAL_PO,ACRH.TOTAL_ACTUAL,ACRH.BALANCE,ACRH.ACH_BY_CAT/100 AS ACH_BY_CAT,ACRH.ACH_DISPRO/100 AS ACHIEVEMENT_DISPRO,ACRH.DISPRO/100 AS DISPRO,  
 ACRH.DISC_QTY, ACRH.TOTAL_CPQ1,ACRH.TOTAL_CPQ2, 
 ACRH.TOTAL_CPQ3, 
 ACRH.TOTAL_CPF1,ACRH.TOTAL_CPF2,TOTAL_PBF3,ACRH.[DESCRIPTIONS],ACRH.ACTUAL_DIST,ACRH.PO_DIST,ACRH.PO_VALUE_DIST,ACRH.DISC_DIST,ACRH.CPQ1_DIST,ACRH.CPQ2_DIST,ACRH.CPQ3_DIST,ACRH.CPF1_DIST,ACRH.CPF2_DIST,ACRH.PBF3_DIST 
 FROM ACHIEVEMENT_HEADER ACRH INNER JOIN AGREE_AGREEMENT AA ON ACRH.AGREEMENT_NO = AA.AGREEMENT_NO INNER JOIN DIST_DISTRIBUTOR DR ON ACRH.DISTRIBUTOR_ID 
 = DR.DISTRIBUTOR_ID INNER JOIN BRND_BRAND BB ON BB.BRAND_ID = ACRH.BRAND_ID 
  LEFT OUTER JOIN BRND_AVGPRICE AP ON AP.IDApp = ACRH.AvgPriceID 
 WHERE ACRH.DISTRIBUTOR_ID = 'SIS001000' AND ACRH.AGREEMENT_NO 
 = ANY(SELECT DA.AGREEMENT_NO FROM DISTRIBUTOR_AGREEMENT DA INNER JOIN AGREE_AGREEMENT AA 
       ON DA.AGREEMENT_NO = AA.AGREEMENT_NO WHERE DA.DISTRIBUTOR_ID = 'SIS001000' 
       AND YEAR(AA.END_DATE) >= YEAR(GETDATE()) - 2 ) AND ACRH.FLAG = 'F3' OPTION(KEEP PLAN);