----------------------------------------------------------------------------------
--PROCEDURE UNTUK MENGINSERT DATA PROGRAM REGISTERING
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Insert_MRKT_MARKETING_PROGRAM' AND TYPE = 'P')
DROP PROCEDURE Sp_Insert_MRKT_MARKETING_PROGRAM
GO
CREATE PROCEDURE Sp_Insert_MRKT_MARKETING_PROGRAM
@PROGRAM_ID VARCHAR(15),
@PROGRAM_NAME VARCHAR(30),
@START_DATE DATETIME,
@END_DATE DATETIME,
@CREATE_BY VARCHAR(30)
AS
INSERT INTO MRKT_MARKETING_PROGRAM(PROGRAM_ID,PROGRAM_NAME,START_DATE,END_DATE,CREATE_BY,CREATE_DATE)
VALUES(@PROGRAM_ID,@PROGRAM_NAME,@START_DATE,@END_DATE,@CREATE_BY,GETDATE())
GO
--------------------------------------------------------------------------------
--PROCEDURE UNTUK MENGUPDATE PROGRAM
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Update_MRKT_MARKETING_PROGRAM' AND TYPE = 'P')
DROP PROCEDURE Sp_Update_MRKT_MARKETING_PROGRAM
GO
CREATE PROCEDURE Sp_Update_MRKT_MAvRKETING_PROGRAM
@PROGRAM_ID VARCHAR(15),
@PROGRAM_NAME VARCHAR(30),
@START_DATE DATETIME,
@END_DATE DATETIME,
@MODIFY_BY VARCHAR(30)
AS
UPDATE MRKT_MARKETING_PROGRAM SET PROGRAM_NAME = @PROGRAM_NAME,START_DATE = @START_DATE,
END_DATE = @END_DATE,MODIFY_BY = @MODIFY_BY,MODIFY_DATE = GETDATE() WHERE PROGRAM_ID = @PROGRAM_ID
GO
-----------------------------------------------------------------------------------------
--PROCEDURE UNTUK MENGECEK KEBERADAAN PROGRAM
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME ='Sp_Check_Existing_MRKT_MARKETING_PROGRAM' AND TYPE = 'P')
DROP PROCEDURE Sp_Check_Existing_MRKT_MARKETING_PROGRAM
GO
CREATE PROCEDURE Sp_Check_Existing_MRKT_MARKETING_PROGRAM
@PROGRAM_ID VARCHAR(15)
AS
BEGIN
IF (SELECT COUNT(PROGRAM_ID) FROM MRKT_MARKETING_PROGRAM WHERE PROGRAM_ID = @PROGRAM_ID) > 0
	RETURN(1)
END
RETURN(0)
GO
-----------------------------------------------------------------------------------------
--PROCEDURE UNTUK MENGECEK REFERENSI TABLE ANAK PROGRAM
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Check_REFERENCED_MRKT_MARKETING_PROGRAM' AND TYPE = 'P')
DROP PROCEDURE Sp_Check_REFERENCED_MRKT_MARKETING_PROGRAM
GO
CREATE PROCEDURE Sp_Check_REFERENCED_MRKT_MARKETING_PROGRAM
@PROGRAM_ID VARCHAR(15)
AS
IF EXISTS(SELECT PROG_BRANDPACK_DIST_ID FROM MRKT_DISC_HISTORY WHERE PROG_BRANDPACK_DIST_ID
= ANY(SELECT PROG_BRANDPACK_DIST_ID FROM MRKT_BRANDPACK_DISTRIBUTOR WHERE PROG_BRANDPACK_ID
= ANY(SELECT PROG_BRANDPACK_ID FROM MRKT_BRANDPACK WHERE PROGRAM_ID = @PROGRAM_ID)))
RETURN(1);
ELSE
RETURN(0)
GO
--------------------------------------------------------------------------------
--PROCEDURE UNTUK MENDELETE DATA MRKT_MARKETING_PROGRAM
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Delete_MRKT_MARKETING_PROGRAM' AND TYPE = 'P')
DROP PROCEDURE Sp_Delete_MRKT_MARKETING_PROGRAM
GO
CREATE PROCEDURE Sp_Delete_MRKT_MARKETING_PROGRAM
@PROGRAM_ID VARCHAR(15)
AS
DELETE FROM MRKT_MARKETING_PROGRAM WHERE PROGRAM_ID = @PROGRAM_ID
GO

--------------------------------------------------------------------------------
--procedure untuk mengecek data existing MRKT_BRANDPACK
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Check_Existing_MRKT_BRANDPACK' AND TYPE = 'P')
DROP PROCEDURE Sp_Check_Existing_MRKT_BRANDPACK
GO
CREATE PROCEDURE Sp_Check_Existing_MRKT_BRANDPACK
@PROG_BRANDPACK_ID varchar(30)
AS
BEGIN
   IF (SELECT COUNT(PROG_BRANDPACK_ID) FROM MRKT_BRANDPACK WHERE PROG_BRANDPACK_ID = @PROG_BRANDPACK_ID)> 0
	RETURN(1)
END
RETURN(0)
GO
----------------------------------------------------------------------------------------
--PROCEDURE UNTUK MENGECEK REFERENSI TABLE MRKT_BRANDPACK
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Check_REFERENCED_MRKT_BRANDPACK' AND TYPE = 'P')
DROP PROCEDURE Sp_Check_REFERENCED_MRKT_BRANDPACK
GO
CREATE PROCEDURE Sp_Check_REFERENCED_MRKT_BRANDPACK
@PROG_BRANDPACK_ID VARCHAR(30)
AS
BEGIN
   IF (SELECT COUNT(PROG_BRANDPACK_ID) FROM MRKT_BRANDPACK_DISTRIBUTOR WHERE PROG_BRANDPACK_ID = @PROG_BRANDPACK_ID) > 0
	RETURN(1)
END
RETURN(0)
GO

---------------------------------------------------------------------------------------
--PROCEDURE UNTUK MENDELETE DATA MRKT_BRANDPACK
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Delete_MRKT_BRANDPACK' AND TYPE = 'P')
DROP PROCEDURE Sp_Delete_MRKT_BRANDPACK
GO
CREATE PROCEDURE Sp_Delete_MRKT_BRANDPACK
@PROG_BRANDPACK_ID VARCHAR(30)
AS
DELETE FROM MRKT_BRANDPACK WHERE PROG_BRANDPACK_ID = @PROG_BRANDPACK_ID
GO

----------------------------------------------------------------------------
--PROCEDURE UNTUK MENGINSERT DATA MRKT_BRANDPACK
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Insert_MRKT_BRANDPACK' AND TYPE = 'P')
DROP PROCEDURE Sp_Insert_MRKT_BRANDPACK
GO
CREATE PROCEDURE Sp_Insert_MRKT_BRANDPACK
@PROG_BRANDPACK_ID VARCHAR(30),
@PROGRAM_ID VARCHAR(15),
@BRANDPACK_ID VARCHAR(14),
@START_DATE DATETIME,
@END_DATE DATETIME,
@CREATE_BY VARCHAR(30)
AS
INSERT INTO MRKT_BRANDPACK(PROG_BRANDPACK_ID,PROGRAM_ID,BRANDPACK_ID,START_DATE,END_DATE,CREATE_BY,CREATE_DATE)
VALUES(@PROG_BRANDPACK_ID,@PROGRAM_ID,@BRANDPACK_ID,@START_DATE,@END_DATE,@CREATE_BY,GETDATE())
GO
---------------------------------------------------------------------------------------
--PROCEDURE UNTUK MENGUPDATE MRKT_BRANDPACK
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Update_MRKT_BRANDPACK' AND TYPE = 'P')
DROP PROCEDURE Sp_Update_MRKT_BRANDPACK
GO
CREATE PROCEDURE Sp_Update_MRKT_BRANDPACK
@PROG_BRANDPACK_ID VARCHAR(30),
@PROGRAM_ID VARCHAR(15),
@BRANDPACK_ID VARCHAR(14),
@START_DATE DATETIME,
@END_DATE DATETIME,
@MODIFY_BY VARCHAR(30)
AS
UPDATE MRKT_BRANDPACK SET PROGRAM_ID = @PROGRAM_ID,BRANDPACK_ID = @BRANDPACK_ID,START_DATE = @START_DATE,END_DATE = @END_DATE,
MODIFY_BY = @MODIFY_BY, MODIFY_DATE = GETDATE() WHERE PROG_BRANDPACK_ID = @PROG_BRANDPACK_ID
GO
 
-----------------------------------------------------------------------------------------------------------
--PROCEDURE UNTUK Mengecek keberadaan data PROG_BRANDPACK_DIST_ID di table MRKT_BRANDPACK_DISTRIBUTOR
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Check_Existing_PROG_BRANDPACK_DIST_ID' AND TYPE = 'P')
DROP PROCEDURE Sp_Check_Existing_PROG_BRANDPACK_DIST_ID
GO
CREATE PROCEDURE Sp_Check_Existing_PROG_BRANDPACK_DIST_ID
@PROG_BRANDPACK_DIST_ID VARCHAR(40)
AS
BEGIN
  IF (SELECT COUNT(PROG_BRANDPACK_DIST_ID) FROM MRKT_BRANDPACK_DISTRIBUTOR 
  WHERE PROG_BRANDPACK_DIST_ID = @PROG_BRANDPACK_DIST_ID)> 0 
	RETURN(1)
END
RETURN(0)
GO
---------------------------------------------------------------------------------------------------------------
--PROCEDURE UNTUK MENGECEK REFERENSI TABLE MRKT_BRANDPACK_DISTRIBUTOR
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Check_REFERENCED_MRKT_BRANDPACK_DISTRIBUTOR' AND TYPE = 'P')
DROP PROCEDURE Sp_Check_REFERENCED_MRKT_BRANDPACK_DISTRIBUTOR
GO
CREATE PROCEDURE Sp_Check_REFERENCED_MRKT_BRANDPACK_DISTRIBUTOR
@PROG_BRANDPACK_DIST_ID VARCHAR(40)
AS
BEGIN
  IF EXISTS(SELECT PROG_BRANDPACK_DIST_ID FROM MRKT_DISC_HISTORY
        WHERE PROG_BRANDPACK_DIST_ID = @PROG_BRANDPACK_DIST_ID) 
	RETURN(2)  
  ELSE IF EXISTS(SELECT PROG_BRANDPACK_DIST_ID FROM  MRKT_MARKETING_SAVING
	WHERE PROG_BRANDPACK_DIST_ID = @PROG_BRANDPACK_DIST_ID) 
	RETURN(3)
END 
 RETURN(0)
GO
------------------------------------------------------------------------------------------------
--PROCEDURE UNTUK MENGECEK REFERENSI DATA TABLE MRKT_BRANDPACK_DISTRIBUTOR TETAPI TIDAK MENGECEK DI STEPPING DISCOUNT
--PROCEDURE INI DI PAKAI DI DATAGRID GRIDEX 2 DI FORM PROGRAM PADA SAAT USER MENDELETE ROW DI MANA STEPPING DISCOUNT BERNILAI TRUE
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Check_REFERENCED_MRKT_BRANDPACK_DISTRIBUTOR_1' AND TYPE = 'P')
DROP PROCEDURE Sp_Check_REFERENCED_MRKT_BRANDPACK_DISTRIBUTOR_1
GO
CREATE PROCEDURE Sp_Check_REFERENCED_MRKT_BRANDPACK_DISTRIBUTOR_1
@PROG_BRANDPACK_DIST_ID VARCHAR(40)
AS
BEGIN
   IF (SELECT COUNT(PROG_BRANDPACK_DIST_ID) FROM MRKT_DISC_HISTORY WHERE PROG_BRANDPACK_DIST_ID
      = @PROG_BRANDPACK_DIST_ID)> 0
	  RETURN(1) 
   ELSE IF(SELECT COUNT(PROG_BRANDPACK_DIST_ID) FROM MRKT_MARKETING_SAVING WHERE PROG_BRANDPACK_DIST_ID = @PROG_BRANDPACK_DIST_ID) > 0
	RETURN(2)
END
RETURN(0)
GO
-------------------------------------------------------------------------------------------------
--PROCEDURE UNTUK MENDELETE DATA MRKT_BRANDPACK_DISTRIBUTOR
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Delete_MRKT_BRANDPACK_DISTRIBUTOR' AND TYPE = 'P')
DROP PROCEDURE Sp_Delete_MRKT_BRANDPACK_DISTRIBUTOR
GO
CREATE PROCEDURE Sp_Delete_MRKT_BRANDPACK_DISTRIBUTOR
@PROG_BRANDPACK_DIST_ID VARCHAR(40)
AS
DELETE FROM MRKT_BRANDPACK_DISTRIBUTOR WHERE PROG_BRANDPACK_DIST_ID = @PROG_BRANDPACK_DIST_ID
GO
----------------------------------------------------------------------------------------------
--PROCEDURE UNTUK MENGINSERT DATA MRKT_BRANDPACK_DISTRIBUTOR
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Insert_MRKT_BRANDPACK_DISTRIBUTOR' AND TYPE = 'P')
DROP PROCEDURE Sp_Insert_MRKT_BRANDPACK_DISTRIBUTOR
GO
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Insert_MRKT_BRANDPACK_DISTRIBUTOR' AND TYPE = 'P')
DROP PROCEDURE Usp_Insert_MRKT_BRANDPACK_DISTRIBUTOR
GO
CREATE PROCEDURE Usp_Insert_MRKT_BRANDPACK_DISTRIBUTOR
@PROG_BRANDPACK_DIST_ID VARCHAR(40),
@PROG_BRANDPACK_ID VARCHAR(30),
@AGREE_BRANDPACK_ID VARCHAR(39),
@DISTRIBUTOR_ID VARCHAR(10),
@START_DATE DATETIME,
@END_DATE DATETIME,
@GIVEN_DISC_PCT DECIMAL(10,2),
@TARGET_QTY DECIMAL(18,3),
@TARGET_DISC_PCT DECIMAL(10,2),
@STEPPING_FLAG BIT,
@ISRPK BIT,
@ISPKPP BIT,
@GIVEN_PKPP DECIMAL(10,2),
@TARGET_PKPP DECIMAL(18,3),
@ISCP BIT,
@GIVEN_CP DECIMAL(10,2),
@TARGET_CP DECIMAL(18,3),
@ISSCPD BIT,
@ISCPMRT BIT,
@GIVEN_CPMRT DECIMAL(18,3),
@TARGET_CPMRT DECIMAL(18,3),
@IS_T_TM_DIST BIT,
@SHIP_TO_ID VARCHAR(25),
@ISCPR BIT,
@GIVEN_CPR DECIMAL(10,3),
@TARGET_CPR DECIMAL(18,3),
@ISDK BIT,
@GIVEN_DK DECIMAL(10,2),
@TARGET_DK DECIMAL(18,3),
@ISHK BIT,
@TARGET_HK DECIMAL(18,3),
@PRICE_HK DECIMAL(10,2),
@BONUS_VALUE DECIMAL(18,2),
@DESCRIPTIONS VARCHAR(200),
@CREATE_BY VARCHAR(30)
AS
SET NOCOUNT ON;
IF NOT EXISTS(SELECT PROG_BRANDPACK_DIST_ID FROM MRKT_BRANDPACK_DISTRIBUTOR WHERE PROG_BRANDPACK_DIST_ID = @PROG_BRANDPACK_DIST_ID)
BEGIN
INSERT INTO MRKT_BRANDPACK_DISTRIBUTOR(PROG_BRANDPACK_DIST_ID,PROG_BRANDPACK_ID,AGREE_BRANDPACK_ID,
DISTRIBUTOR_ID,START_DATE,END_DATE,ISRPK,GIVEN_DISC_PCT,TARGET_QTY,TARGET_DISC_PCT,STEPPING_FLAG,
ISPKPP,GIVEN_PKPP,TARGET_PKPP,BONUS_VALUE,ISCP,GIVEN_CP,TARGET_CP,ISSCPD,ISCPMRT,GIVEN_CPMRT,TARGET_CPMRT,IS_T_TM_DIST,SHIP_TO_ID,ISCPR,GIVEN_CPR,TARGET_CPR,ISDK,GIVEN_DK,TARGET_DK,ISHK,TARGET_HK,PRICE_HK,DESCRIPTIONS,CREATE_BY,CREATE_DATE)
VALUES(@PROG_BRANDPACK_DIST_ID,@PROG_BRANDPACK_ID,@AGREE_BRANDPACK_ID,
@DISTRIBUTOR_ID,@START_DATE,@END_DATE,@ISRPK,@GIVEN_DISC_PCT,@TARGET_QTY,@TARGET_DISC_PCT,@STEPPING_FLAG,
@ISPKPP,@GIVEN_PKPP,@TARGET_PKPP,@BONUS_VALUE,@ISCP,@GIVEN_CP,@TARGET_CP,@ISSCPD,@ISCPMRT,@GIVEN_CPMRT,@TARGET_CPMRT,@IS_T_TM_DIST,@SHIP_TO_ID,@ISCPR,@GIVEN_CPR,@TARGET_CPR,@ISDK,@GIVEN_DK,@TARGET_DK,@ISHK,@TARGET_HK,@PRICE_HK,@DESCRIPTIONS,@CREATE_BY,GETDATE())
END
GO
--------------------------------------------------------------------------------------

--PROCEDURE UNTUK MENGUPDATE MRKT_BRANDPACK_DISTR
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Update_MRKT_BRANDPACK_DISTRIBUTOR' AND TYPE = 'P')
DROP PROCEDURE Sp_Update_MRKT_BRANDPACK_DISTRIBUTOR
GO
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Update_MRKT_BRANDPACK_DISTRIBUTOR' AND TYPE = 'P')
DROP PROCEDURE Usp_Update_MRKT_BRANDPACK_DISTRIBUTOR
GO
CREATE PROCEDURE Usp_Update_MRKT_BRANDPACK_DISTRIBUTOR
@PROG_BRANDPACK_DIST_ID VARCHAR(40),
@PROG_BRANDPACK_ID VARCHAR(30),
@AGREE_BRANDPACK_ID VARCHAR(39),
@DISTRIBUTOR_ID VARCHAR(10),
@START_DATE DATETIME,
@END_DATE DATETIME,
@GIVEN_DISC_PCT DECIMAL(10,2),
@TARGET_QTY DECIMAL(18,3),
@TARGET_DISC_PCT DECIMAL(10,2),
@STEPPING_FLAG BIT,
@ISRPK BIT,
@ISPKPP BIT,
@GIVEN_PKPP DECIMAL(10,2),
@TARGET_PKPP DECIMAL(18,3),
@ISCP BIT,
@GIVEN_CP DECIMAL(10,2),
@TARGET_CP DECIMAL(18,3),
@ISSCPD BIT,
@ISCPMRT BIT,
@GIVEN_CPMRT DECIMAL(18,3),
@TARGET_CPMRT DECIMAL(18,3),

@IS_T_TM_DIST BIT,
@SHIP_TO_ID VARCHAR(25),
@ISCPR BIT,
@GIVEN_CPR DECIMAL(10,3),
@TARGET_CPR DECIMAL(18,3),
@ISDK BIT,
@GIVEN_DK DECIMAL(10,2),
@TARGET_DK DECIMAL(18,3),
@ISHK BIT,
@TARGET_HK DECIMAL(18,3),
@PRICE_HK DECIMAL(10,2),
@BONUS_VALUE DECIMAL(18,2),
@DESCRIPTIONS VARCHAR(200),
@MODIFY_BY VARCHAR(30)
AS
SET NOCOUNT ON;
IF EXISTS(SELECT PROG_BRANDPACK_DIST_ID FROM MRKT_BRANDPACK_DISTRIBUTOR WHERE PROG_BRANDPACK_DIST_ID = @PROG_BRANDPACK_DIST_ID)
BEGIN
UPDATE MRKT_BRANDPACK_DISTRIBUTOR SET PROG_BRANDPACK_ID = @PROG_BRANDPACK_ID,AGREE_BRANDPACK_ID = @AGREE_BRANDPACK_ID,
DISTRIBUTOR_ID = @DISTRIBUTOR_ID,START_DATE = @START_DATE,END_DATE = @END_DATE,ISRPK = @ISRPK,
GIVEN_DISC_PCT = @GIVEN_DISC_PCT,TARGET_QTY = @TARGET_QTY,TARGET_DISC_PCT = @TARGET_DISC_PCT,STEPPING_FLAG = @STEPPING_FLAG,
ISPKPP = @ISPKPP,GIVEN_PKPP = @GIVEN_PKPP,TARGET_PKPP = @TARGET_PKPP,BONUS_VALUE = @BONUS_VALUE,ISCP = @ISCP,GIVEN_CP = @GIVEN_CP,
TARGET_CP = @TARGET_CP,ISSCPD = @ISSCPD,
ISCPMRT = @ISCPMRT,GIVEN_CPMRT = @GIVEN_CPMRT ,TARGET_CPMRT = @TARGET_CPMRT,
SHIP_TO_ID = @SHIP_TO_ID,IS_T_TM_DIST = @IS_T_TM_DIST,ISCPR = @ISCPR,GIVEN_CPR = @GIVEN_CPR,TARGET_CPR = @TARGET_CPR,ISDK = @ISDK,GIVEN_DK = @GIVEN_DK,TARGET_DK = @TARGET_DK,ISHK = @ISHK,
TARGET_HK = @TARGET_HK,PRICE_HK = @PRICE_HK,DESCRIPTIONS = @DESCRIPTIONS,MODIFY_BY = @MODIFY_BY,MODIFY_DATE = GETDATE() WHERE PROG_BRANDPACK_DIST_ID = @PROG_BRANDPACK_DIST_ID
END
GO
-----------------------------------------------------------------------------------------
--PROCEDURE UNTUK MEMBUAT VIEW DI GRIDEXF FORM DISTIBUTOR_INCLUDE
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_CREATE_VIEW_MRKT_BRANDPACK' AND TYPE = 'P')
DROP PROCEDURE Sp_CREATE_VIEW_MRKT_BRANDPACK
GO
CREATE PROCEDURE Sp_CREATE_VIEW_MRKT_BRANDPACK
@PROG_BRANDPACK_DIST_ID VARCHAR(40)
AS
SELECT MBD.PROG_BRANDPACK_DIST_ID,MBD.PROG_BRANDPACK_ID,
MBD.AGREE_BRANDPACK_ID,MBD.DISTRIBUTOR_ID,DR.DISTRIBUTOR_NAME,
MBD.START_DATE,MBD.END_DATE,MBD.ISRPK,MBD.GIVEN_DISC_PCT,
MBD.TARGET_QTY,MBD.TARGET_DISC_PCT,MBD.STEPPING_FLAG,MP.PROGRAM_NAME,
MB.PROGRAM_ID,MB.BRANDPACK_ID,BB.BRANDPACK_NAME,MBD.ISPKPP,MBD.GIVEN_PKPP,
MBD.TARGET_PKPP,MBD.BONUS_VALUE,MBD.ISDK,MBD.GIVEN_DK,MBD.TARGET_DK,
MBD.ISCP,MBD.GIVEN_CP,MBD.TARGET_CP,MBD.ISSCPD,MBD.IS_T_TM_DIST,MBD.SHIP_TO_ID,
MBD.ISCPR,MBD.GIVEN_CPR,MBD.TARGET_CPR,
MBD.ISHK,MBD.TARGET_HK,MBD.DESCRIPTIONS,
MBD.PRICE_HK FROM MRKT_BRANDPACK_DISTRIBUTOR MBD INNER JOIN MRKT_BRANDPACK MB
ON MBD.PROG_BRANDPACK_ID = MB.PROG_BRANDPACK_ID INNER JOIN MRKT_MARKETING_PROGRAM MP
ON MB.PROGRAM_ID = MP.PROGRAM_ID INNER JOIN DIST_DISTRIBUTOR DR ON DR.DISTRIBUTOR_ID = MBD.DISTRIBUTOR_ID
INNER JOIN BRND_BRANDPACK BB ON BB.BRANDPACK_ID = MB.BRANDPACK_ID
WHERE  MBD.PROG_BRANDPACK_DIST_ID = @PROG_BRANDPACK_DIST_ID
GO

------------------------------------------------------------------------------------------

--PROCEDURE UNTUK MENYELEK AGREE_BRANDPACK_ID UNTUK DI INSERT DI TABLE MRKT_BRANDPACK_DISTRIBUTOR
--IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Get_AGREE_BANDPACK_ID_FOR_MRKT_BRANDPACK' AND TYPE = 'P')
--DROP PROCEDURE Sp_Get_AGREE_BANDPACK_ID_FOR_MRKT_BRANDPACK
--GO
--CREATE PROCEDURE Sp_Get_AGREE_BANDPACK_ID_FOR_MRKT_BRANDPACK
--@BRANDPACK_ID VARCHAR(14),
--@DISTRIBUTOR_ID VARCHAR(10),
--@GETDATE SMALLDATETIME
--AS
--SELECT AGREE_BRANDPACK_INCLUDE.AGREE_BRANDPACK_ID FROM AGREE_BRANDPACK_INCLUDE,AGREE_AGREEMENT,DISTRIBUTOR_AGREEMENT
--WHERE AGREE_BRANDPACK_INCLUDE.BRANDPACK_ID = @BRANDPACK_ID AND AGREE_BRANDPACK_INCLUDE.AGREEMENT_NO = AGREE_AGREEMENT.AGREEEMENT_NO
--AND AGREEE_AGREEMENT.AGREEMENT_NO = DISTRIBUTOR_AGREEMENT.AGREEMENT_NO AND DISTRIBUTOR_AGREEMENT.DISTRIBUTOR_ID = @DISTRIBUTOR_ID
--AND AGREE_AGREEMENT.END_DATE  >= @GETDATE ;
--GO
----------------------------------------------------------------------------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_GetAgreeBrandPack_ID_FOR_MRKT_BRANDPACK' AND TYPE = 'P')
DROP PROCEDURE Usp_GetAgreeBrandPack_ID_FOR_MRKT_BRANDPACK
GO
CREATE PROCEDURE Usp_GetAgreeBrandPack_ID_FOR_MRKT_BRANDPACK
@BRANDPACK_ID VARCHAR(14),@DISTRIBUTOR_ID VARCHAR(10),@START_DATE SMALLDATETIME,@END_DATE SMALLDATETIME
AS
SELECT TOP 1 AGREE_BRANDPACK_ID FROM
(
  SELECT ABI.AGREE_BRANDPACK_ID,AA.END_DATE FROM DISTRIBUTOR_AGREEMENT DA INNER JOIN
  AGREE_AGREEMENT AA ON DA.AGREEMENT_NO = AA.AGREEMENT_NO
  INNER JOIN AGREE_BRANDPACK_INCLUDE ABI ON ABI.AGREEMENT_NO = AA.AGREEMENT_NO
  WHERE DA.DISTRIBUTOR_ID = @DISTRIBUTOR_ID AND ABI.BRANDPACK_ID = @BRANDPACK_ID 
  AND AA.END_DATE >= @END_DATE AND AA.START_DATE <= @START_DATE
)ABI
ORDER BY END_DATE DESC;    
GO




--EXEC Usp_GetAgreeBrandPack_ID_FOR_MRKT_BRANDPACK
--@BRANDPACK_ID = '0060200200MD',
--@DISTRIBUTOR_ID = 'AGR019000'
--------------------------------------------------------------------------------------------------
--PROCEDURE UNTUK MENDELETE DATA STEPPING DISCOUNT BASED PROG_BRANDPACK_DIST_ID
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Delete_STEPPING_DISCOUNT' AND TYPE = 'P')
DROP PROCEDURE Sp_Delete_STEPPING_DISCOUNT 
GO
CREATE PROCEDURE Sp_Delete_STEPPING_DISCOUNT
@PROG_BRANDPACK_DIST_ID VARCHAR(40)
AS
DELETE FROM MRKT_STEPPING_DISCOUNT WHERE PROG_BRANDPACK_DIST_ID = @PROG_BRANDPACK_DIST_ID
GO

---------------------------------------------------------------------------------------------
--PROCEUDURE UNTUK MEMVIEW DATA DI MULTICOLUMN COMBO DI FORM STEPPING DISCOUNT UNTUK MODE SAVE
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_GetView_PROG_BRANDPACK_DIST_ID' AND TYPE = 'P')
DROP PROCEDURE  Sp_GetView_PROG_BRANDPACK_DIST_ID
GO
CREATE PROCEDURE Sp_GetView_PROG_BRANDPACK_DIST_ID
AS
SELECT MRKT_BRANDPACK_DISTRIBUTOR.PROG_BRANDPACK_DIST_ID,DIST_DISTRIBUTOR.DISTRIBUTOR_NAME,MRKT_MARKETING_PROGRAM.PROGRAM_NAME,
MRKT_BRANDPACK.BRANDPACK_ID,BRND_BRANDPACK.BRANDPACK_NAME
FROM MRKT_BRANDPACK_DISTRIBUTOR,DIST_DISTRIBUTOR,MRKT_BRANDPACK,MRKT_MARKETING_PROGRAM,BRND_BRANDPACK
WHERE MRKT_BRANDPACK_DISTRIBUTOR.DISTRIBUTOR_ID = DIST_DISTRIBUTOR.DISTRIBUTOR_ID AND
MRKT_BRANDPACK_DISTRIBUTOR.PROG_BRANDPACK_ID = MRKT_BRANDPACK.PROG_BRANDPACK_ID AND
MRKT_BRANDPACK.PROGRAM_ID = MRKT_MARKETING_PROGRAM.PROGRAM_ID AND
MRKT_BRANDPACK.BRANDPACK_ID = BRND_BRANDPACK.BRANDPACK_ID 
AND MRKT_BRANDPACK_DISTRIBUTOR.STEPPING_FLAG = 1 AND MRKT_BRANDPACK_DISTRIBUTOR.PROG_BRANDPACK_DIST_ID 
NOT IN(SELECT PROG_BRANDPACK_DIST_ID FROM MRKT_STEPPING_DISCOUNT)
GO
-----------------------------------------------------------------------------------------
--PROCEDURE UNTUK MEMVIEW DATA DI MULTICOLUMN COMBO DI FORM STEPPING DISCOUNT PADA SAAT MODE UPDATE

IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_GetView_PROG_BRANDPACK_DIST_ID_1' AND TYPE = 'P')
DROP PROCEDURE  Sp_GetView_PROG_BRANDPACK_DIST_ID_1
GO
CREATE PROCEDURE Sp_GetView_PROG_BRANDPACK_DIST_ID_1
AS
SELECT MRKT_BRANDPACK_DISTRIBUTOR.PROG_BRANDPACK_DIST_ID,DIST_DISTRIBUTOR.DISTRIBUTOR_NAME,MRKT_MARKETING_PROGRAM.PROGRAM_NAME,
MRKT_BRANDPACK.BRANDPACK_ID,BRND_BRANDPACK.BRANDPACK_NAME
FROM MRKT_BRANDPACK_DISTRIBUTOR,DIST_DISTRIBUTOR,MRKT_BRANDPACK,MRKT_MARKETING_PROGRAM,BRND_BRANDPACK
WHERE MRKT_BRANDPACK_DISTRIBUTOR.DISTRIBUTOR_ID = DIST_DISTRIBUTOR.DISTRIBUTOR_ID AND
MRKT_BRANDPACK_DISTRIBUTOR.PROG_BRANDPACK_ID = MRKT_BRANDPACK.PROG_BRANDPACK_ID AND
MRKT_BRANDPACK.PROGRAM_ID = MRKT_MARKETING_PROGRAM.PROGRAM_ID AND
MRKT_BRANDPACK.BRANDPACK_ID = BRND_BRANDPACK.BRANDPACK_ID
AND MRKT_BRANDPACK_DISTRIBUTOR.STEPPING_FLAG = 1 AND MRKT_BRANDPACK_DISTRIBUTOR.PROG_BRANDPACK_DIST_ID 
IN(SELECT PROG_BRANDPACK_DIST_ID FROM MRKT_STEPPING_DISCOUNT) 
GO
-------------------------------------------------------------------
--PROCEDURE UNTUK MENEGECEK BRANDPACK YANG SAMA YANG DI IKUTI DISTRIBUTOR YANG SAMA
-- PADA PERIOD YANG SAMA
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Chek_DISTRIBUTOR_BRANDPACK_WITH_SAME_PERIOD' AND TYPE = 'P')
DROP PROCEDURE Sp_Chek_DISTRIBUTOR_BRANDPACK_WITH_SAME_PERIOD
GO
CREATE PROCEDURE Sp_Chek_DISTRIBUTOR_BRANDPACK_WITH_SAME_PERIOD
@DISTRIBUTOR_ID VARCHAR(10),
@BRANDPACK_ID VARCHAR(25),
@START_DATE DATETIME
AS
BEGIN
IF (SELECT COUNT(MRKT_BRANDPACK_DISTRIBUTOR.DISTRIBUTOR_ID) FROM MRKT_BRANDPACK_DISTRIBUTOR,MRKT_BRANDPACK WHERE 
	MRKT_BRANDPACK_DISTRIBUTOR.PROG_BRANDPACK_ID = MRKT_BRANDPACK.PROG_BRANDPACK_ID AND 
	MRKT_BRANDPACK_DISTRIBUTOR.DISTRIBUTOR_ID = @DISTRIBUTOR_ID AND
	MRKT_BRANDPACK.BRANDPACK_ID = @BRANDPACK_ID AND MRKT_BRANDPACK_DISTRIBUTOR.END_DATE >= @START_DATE
	)> 0
	RETURN(1)
END
RETURN(0)
GO

----------------------
--EXEC Sp_Chek_DISTRIBUTOR_BRANDPACK_WITH_SAME_PERIOD
--@DISTRIBUTOR_ID = 'IBR001IDR',
--@BRANDPACK_ID = '00049200LD',
--@START_DATE = '07/30/2008'
--------------------------------------------------------------------------------------
--PROCEDURE UNTUK MENYELEK BERAPA BRANDPACK.YANG DIIKUTI DISTRIBUTOR UNTUK PROGRAM TERTENTU
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Select_BrandPack_Marketing_Distributor' AND TYPE = 'P')
DROP PROCEDURE Usp_Select_BrandPack_Marketing_Distributor
GO
CREATE PROCEDURE Usp_Select_BrandPack_Marketing_Distributor
@DISTRIBUTOR_ID VARCHAR(10),
@PROGRAM_ID VARCHAR(15)
AS
SELECT MRKT_MARKETING_PROGRAM.PROGRAM_ID,MRKT_BRANDPACK.BRANDPACK_ID,MRKT_BRANDPACK_DISTRIBUTOR.PROG_BRANDPACK_DIST_ID,
MRKT_BRANDPACK_DISTRIBUTOR.START_DATE,MRKT_BRANDPACK_DISTRIBUTOR.END_DATE,MRKT_BRANDPACK_DISTRIBUTOR.TARGET_QTY,
MRKT_BRANDPACK_DISTRIBUTOR.TARGET_DISC_PCT,MRKT_BRANDPACK_DISTRIBUTOR.STEPPING_FLAG
FROM MRKT_MARKETING_PROGRAM,MRKT_BRANDPACK,MRKT_BRANDPACK_DISTRIBUTOR
WHERE MRKT_BRANDPACK_DISTRIBUTOR.PROG_BRANDPACK_ID = MRKT_BRANDPACK.PROG_BRANDPACK_ID
AND MRKT_BRANDPACK.PROGRAM_ID = MRKT_MARKETING_PROGRAM.PROGRAM_ID AND MRKT_BRANDPACK_DISTRIBUTOR.DISTRIBUTOR_ID
= @DISTRIBUTOR_ID AND MRKT_MARKETING_PROGRAM.PROGRAM_ID = @PROGRAM_ID
GO
--------------------------------------------------------------------------------------
--exec Usp_Select_BrandPack_Marketing_Distributor @DISTRIBUTOR_ID = 'AGR001USD',
--@pROGRAM_ID = 'PR_02'
--------------------------------------------------------------------------------
--PROCEDURE UNTUK MEMVIEW DISCOUNT
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_GetView_Discount_Marketing' AND TYPE = 'P')
DROP PROCEDURE Usp_GetView_Discount_Marketing
GO
CREATE PROCEDURE Usp_GetView_Discount_Marketing
@DISTRIBUTOR_ID VARCHAR(10),
@PROGRAM_ID VARCHAR(15)
AS
SELECT MRKT_MARKETING_PROGRAM.PROGRAM_NAME,BRND_BRANDPACK.BRANDPACK_NAME,DIST_DISTRIBUTOR.DISTRIBUTOR_NAME,
MRKT_BRANDPACK_DISTRIBUTOR.START_DATE,MRKT_BRANDPACK_DISTRIBUTOR.END_DATE,MRKT_BRANDPACK_DISTRIBUTOR.TARGET_QTY,
MRKT_BRANDPACK_DISTRIBUTOR.STEPPING_FLAG,MRKT_MARKETING_SAVING.TOTAL_REACHED_QTY,MRKT_MARKETING_SAVING.TOTAL_REACHED_AMOUNT,
MRKT_MARKETING_SAVING.MRKT_DISC_PCT,MRKT_MARKETING_SAVING.MRKT_DISC_QTY,MRKT_MARKETING_SAVING.PRICE_PERQTY,MRKT_MARKETING_SAVING.DISC_AMOUNT,
MRKT_MARKETING_SAVING.MRKT_RELEASE_QTY,MRKT_MARKETING_SAVING.MRKT_RELEASE_AMOUNT,
MRKT_MARKETING_SAVING.MRKT_LEFT_QTY,MRKT_MARKETING_SAVING.MRKT_LEFT_AMOUNT
FROM MRKT_MARKETING_PROGRAM,BRND_BRANDPACK,DIST_DISTRIBUTOR,MRKT_BRANDPACK,MRKT_BRANDPACK_DISTRIBUTOR,MRKT_MARKETING_SAVING
WHERE MRKT_MARKETING_SAVING.PROG_BRANDPACK_DIST_ID = MRKT_BRANDPACK_DISTRIBUTOR.PROG_BRANDPACK_DIST_ID
AND MRKT_BRANDPACK_DISTRIBUTOR.PROG_BRANDPACK_ID = MRKT_BRANDPACK.PROG_BRANDPACK_ID
AND MRKT_BRANDPACK_DISTRIBUTOR.DISTRIBUTOR_ID = @DISTRIBUTOR_ID AND MRKT_BRANDPACK_DISTRIBUTOR.DISTRIBUTOR_ID = DIST_DISTRIBUTOR.DISTRIBUTOR_ID
AND MRKT_BRANDPACK.BRANDPACK_ID = BRND_BRANDPACK.BRANDPACK_ID
AND MRKT_BRANDPACK.PROGRAM_ID = MRKT_MARKETING_PROGRAM.PROGRAM_ID AND MRKT_MARKETING_PROGRAM.PROGRAM_ID = @PROGRAM_ID
GO

--EXEC Usp_GetView_Discount_Marketing
--@DISTRIBUTOR_ID = 'IBR001IDR',
--@PROGRAM_ID = 'PR_1'

------------------------------------------------------------------------------------
--PROCEDURE UNTUK MEMVIEW DISTRIBUTOR YANG IKUTAN PROGRAM DI MULTICOLUMN COMBO DISCOUNT MARKETING

IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_GetView_Distributor_Marketing' AND TYPE = 'P')
DROP PROCEDURE Usp_GetView_Distributor_Marketing
GO
CREATE PROCEDURE Usp_GetView_Distributor_Marketing
AS
SELECT DISTINCT(MRKT_BRANDPACK_DISTRIBUTOR.DISTRIBUTOR_ID),DIST_DISTRIBUTOR.DISTRIBUTOR_NAME,
MRKT_MARKETING_PROGRAM.PROGRAM_ID,MRKT_MARKETING_PROGRAM.PROGRAM_NAME
FROM MRKT_BRANDPACK_DISTRIBUTOR,DIST_DISTRIBUTOR,MRKT_BRANDPACK,MRKT_MARKETING_PROGRAM
WHERE MRKT_BRANDPACK_DISTRIBUTOR.DISTRIBUTOR_ID = DIST_DISTRIBUTOR.DISTRIBUTOR_ID
AND MRKT_BRANDPACK_DISTRIBUTOR.PROG_BRANDPACK_ID = MRKT_BRANDPACK.PROG_BRANDPACK_ID 
AND MRKT_BRANDPACK.PROGRAM_ID = MRKT_MARKETING_PROGRAM.PROGRAM_ID
AND MRKT_BRANDPACK_DISTRIBUTOR.TARGET_QTY > 1 
AND MRKT_BRANDPACK_DISTRIBUTOR.END_DATE < GETDATE()
AND YEAR(MRKT_BRANDPACK_DISTRIBUTOR.END_DATE) >= (YEAR(GETDATE()) -1)

GO
------------------------------------------------------------------------------------
-----------------PROCEDURE UNTUK MENGINSERT DATA KE MRKT_MARKETING_SAVING
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Insert_MRKT_MARKETING_SAVING' AND TYPE = 'P')
DROP PROCEDURE Usp_Insert_MRKT_MARKETING_SAVING
GO
CREATE PROCEDURE Usp_Insert_MRKT_MARKETING_SAVING
@MRKT_M_S_ID VARCHAR(60),
@PROG_BRANDPACK_DIST_ID VARCHAR(40),
@ST_FLAG varCHAR(2),
@TOTAL_REACHED_QTY VARCHAR(14),
@TOTAL_REACHED_AMOUNT VARCHAR(20),
@MRKT_DISC_PCT VARCHAR(6),
@MRKT_DISC_QTY VARCHAR(10),
@PRICE_PERQTY VARCHAR(10),
@DISC_AMOUNT VARCHAR(10),
@MRKT_RELEASE_QTY VARCHAR(10),
@MRKT_RELEASE_AMOUNT VARCHAR(10),
@MRKT_LEFT_QTY VARCHAR(10),
@MRKT_LEFT_AMOUNT VARCHAR(10),
@CREATE_BY VARCHAR(30)
AS
INSERT INTO MRKT_MARKETING_SAVING(MRKT_M_S_ID,PROG_BRANDPACK_DIST_ID,ST_FLAG,TOTAL_REACHED_QTY,
TOTAL_REACHED_AMOUNT,MRKT_DISC_PCT,MRKT_DISC_QTY,PRICE_PERQTY,DISC_AMOUNT,MRKT_RELEASE_QTY,
MRKT_RELEASE_AMOUNT,MRKT_LEFT_QTY,MRKT_LEFT_AMOUNT,CREATE_BY,CREATE_DATE)
VALUES(@MRKT_M_S_ID,@PROG_BRANDPACK_DIST_ID,@ST_FLAG,@TOTAL_REACHED_QTY,@TOTAL_REACHED_AMOUNT,
@MRKT_DISC_PCT,@MRKT_DISC_QTY,@PRICE_PERQTY,@DISC_AMOUNT,@MRKT_RELEASE_QTY,@MRKT_RELEASE_AMOUNT,
@MRKT_LEFT_QTY,@MRKT_LEFT_AMOUNT,@CREATE_BY,GETDATE())
GO
----------------------------------------------------------------------------------------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Create_View_Sales_Program_Distributor_History' AND TYPE = 'P')
DROP PROCEDURE Usp_Create_View_Sales_Program_Distributor_History
GO
CREATE PROCEDURE Usp_Create_View_Sales_Program_Distributor_History
@DISTRIBUTOR_ID VARCHAR(30)
--,
--@END_DATE SMALLDATETIME,
--@START_DATE SMALLDATETIME
AS
SET NOCOUNT ON;
SELECT MP.PROGRAM_ID,MP.PROGRAM_NAME,MB.BRANDPACK_ID,BB.BRANDPACK_NAME,MBD.START_DATE,
MBD.END_DATE,MBD.GIVEN_DISC_PCT AS [GIVEN %],MBD.TARGET_QTY,MBD.TARGET_DISC_PCT AS [TARGET %],
MBD.ISHK,MBD.ISRPK AS DPRDS,MBD.PRICE_HK,MBD.TARGET_HK,MBD.ISDK AS DK,MBD.GIVEN_DK,MBD.TARGET_DK,
MBD.ISCP AS [CP(D)],MBD.GIVEN_CP AS [GIVEN_CP(D)],MBD.TARGET_CP AS [TARGET_CP(D)],
MBD.ISSCPD AS [CP(DK)],MBD.IS_T_TM_DIST AS TARGET_TM_DIST,MBD.ISCPMRT AS [CP(MRT)],
MBD.GIVEN_CPMRT AS [GIVEN_CP(MRT)],MBD.TARGET_CPMRT AS [TARGET_CP(MRT)],
MBD.ISCPR AS [CP(RD)],MBD.GIVEN_CPR AS [GIVEN_CP(RD)],MBD.TARGET_CPR AS [TARGET_CP(RD)],
MBD.ISPKPP AS PKPP,MBD.GIVEN_PKPP,MBD.TARGET_PKPP,MBD.BONUS_VALUE AS GIVEN_VALUE_PKPP,MBD.DESCRIPTIONS
FROM MRKT_MARKETING_PROGRAM MP INNER JOIN MRKT_BRANDPACK MB ON
MP.PROGRAM_ID = MB.PROGRAM_ID INNER JOIN MRKT_BRANDPACK_DISTRIBUTOR MBD
ON MB.PROG_BRANDPACK_ID = MBD.PROG_BRANDPACK_ID 
INNER JOIN BRND_BRANDPACK BB ON BB.BRANDPACK_ID = MB.BRANDPACK_ID
WHERE --MBD.START_DATE >= @START_DATE AND MBD.END_DATE <= @END_DATE AND 
MBD.DISTRIBUTOR_ID = @DISTRIBUTOR_ID
GO
 
--SELECT MARKETING_BRANDPACK_DISTRIBUTOR.PROGRAM_ID,MRKT_MARKETING_PROGRAM.PROGRAM_NAME,
--MARKETING_BRANDPACK_DISTRIBUTOR.BRANDPACK_NAME,MARKETING_BRANDPACK_DISTRIBUTOR.START_DATE,
--MARKETING_BRANDPACK_DISTRIBUTOR.END_DATE,MARKETING_BRANDPACK_DISTRIBUTOR.[GIVEN %],
--MARKETING_BRANDPACK_DISTRIBUTOR.TARGET_QTY,MARKETING_BRANDPACK_DISTRIBUTOR.[TARGET %],
--MARKETING_BRANDPACK_DISTRIBUTOR.STEPPING AS STEPPING_DISCOUNT,MARKETING_BRANDPACK_DISTRIBUTOR.ISHK,
--MARKETING_BRANDPACK_DISTRIBUTOR.PRICE_HK,MARKETING_BRANDPACK_DISTRIBUTOR.TARGET_HK,
--MARKETING_BRANDPACK_DISTRIBUTOR.ISDK,MARKETING_BRANDPACK_DISTRIBUTOR.GIVEN_DK,
--MARKETING_BRANDPACK_DISTRIBUTOR.TARGET_DK,MARKETING_BRANDPACK_DISTRIBUTOR.ISCP AS ISCP_D,
--MARKETING_BRANDPACK_DISTRIBUTOR.GIVEN_CP AS GIVEN_CP_D,MARKETING_BRANDPACK_DISTRIBUTOR.TARGET_CP AS TARGET_CP_D,
--MARKETING_BRANDPACK_DISTRIBUTOR.ISCPR AS ISCP_R,MARKETING_BRANDPACK_DISTRIBUTOR.GIVEN_CPR AS GIVEN_CP_R,
--MARKETING_BRANDPACK_DISTRIBUTOR.TARGET_CPR AS TARGET_CP_R,
--MARKETING_BRANDPACK_DISTRIBUTOR.ISPKPP,MARKETING_BRANDPACK_DISTRIBUTOR.GIVEN_PKPP,
--MARKETING_BRANDPACK_DISTRIBUTOR.TARGET_PKPP
--FROM MRKT_MARKETING_PROGRAM, MARKETING_BRANDPACK_DISTRIBUTOR 
--WHERE MRKT_MARKETING_PROGRAM.PROGRAM_ID = MARKETING_BRANDPACK_DISTRIBUTOR.PROGRAM_ID
--AND MARKETING_BRANDPACK_DISTRIBUTOR.DISTRIBUTOR_ID = @DISTRIBUTOR_ID
--GO

-------------------------------------------------------------------------------------- 
----PROCEDURE UNTUK MEMVIEW HK_PROGRAM
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Create_View_HK_Program' AND TYPE = 'P')
DROP PROCEDURE Usp_Create_View_HK_Program
GO
--CREATE PROCEDURE Usp_Create_View_HK_Program
--@DISTRIBUTOR_ID VARCHAR(10)
--AS
--SELECT MP.PROGRAM_ID,MP.PROGRAM_NAME,BB.BRANDPACK_NAME,DTP.PRICE,
--DTP.TARGET_QTY,DTP.START_DATE,DTP.END_DATE
--FROM MRKT_MARKETING_PROGRAM MP INNER JOIN DIST_TYPICAL_PRICE DTP ON MP.PROGRAM_ID = DTP.PROGRAM_ID
--INNER JOIN BRND_BRANDPACK BB ON DTP.BRANDPACK_ID = BB.BRANDPACK_ID 
--WHERE DTP.DISTRIBUTOR_ID = @DISTRIBUTOR_ID
--GO
--------------------------------------------------------------------------------------------

--PROCEDURE UNTUK MEMVIEW OTHER PROGRAM
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Create_View_Other_Program' AND TYPE = 'P')
DROP PROCEDURE Usp_Create_View_Other_Program
GO
--CREATE PROCEDURE Usp_Create_View_Other_Program
--@DISTRIBUTOR_ID VARCHAR(10)
--AS
--SELECT MP.PROGRAM_ID,MP.PROGRAM_NAME,BB.BRANDPACK_NAME,MBD.START_DATE,MBD.END_DATE,
--MBD.GIVEN_DISC_PCT AS GIVEN_DISC,MBD.TARGET_QTY,MBD.CFD_FLAG AS TYPE
--FROM MRKT_MARKETING_PROGRAM MP INNER JOIN MRKT_BRANDPACK_1 MB
--ON MP.PROGRAM_ID = MB.PROGRAM_ID INNER JOIN BRND_BRANDPACK_BB ON MB.BRANDPACK_ID = BB.BRANDPACK_ID
--INNER JOIN MARKETING_BRANDPACK_DISTRIBUTOR_I MBD ON MB.PROG_BRANDPACK_ID = MBD.PROG_BRANDPACK_ID
--WHERE MBD.DISTRIBUTOR_ID = @DISTRIBUTOR_ID
--GO




