IF EXISTS(SELECT NAME FROM [DBO].SYSOBJECTS WHERE NAME = 'Usp_Check_Availability_Disc_Other' AND TYPE = 'P')
DROP PROCEDURE Usp_Check_Availability_Disc_Other
GO
CREATE PROCEDURE Usp_Check_Availability_Disc_Other
@DISTRIBUTOR_ID VARCHAR(10),
@BRANDPACK_ID VARCHAR(14),
@O_DEVIDED_QTY DECIMAL(18,3) OUTPUT,
@O_DEVIDE_FACTOR DECIMAL(18,3) OUTPUT,
@PO_DATE SMALLDATETIME,
@O_UNIT VARCHAR(15) OUTPUT,
@O_DD BIT OUTPUT,
@O_DR BIT OUTPUT,
@O_CBD BIT OUTPUT,
@O_DK BIT OUTPUT,
@O_DP BIT OUTPUT,
@IDApp INT
AS 
--SET NOCOUNT ON
DECLARE @V_BRAND_ID VARCHAR(7),@V_ApplyTo VARCHAR(5),@V_ApplyDate SMALLDATETIME,@V_START_DATE_PKD SMALLDATETIME,@V_IsDiscByBrandPack BIT,@V_IsDiscByBrandPackForAll BIT,
@V_IsByBrand bit,@V_END_DATE_PKD SMALLDATETIME;
SELECT @O_DEVIDED_QTY = (SELECT DEVIDED_QUANTITY FROM BRND_BRANDPACK WHERE BRANDPACK_ID = @BRANDPACK_ID );
SELECT @O_DEVIDE_FACTOR = (SELECT TOP 1 DEVIDE_FACTOR FROM BRND_PACK WHERE PACK_ID = (SELECT TOP 1 PACK_ID FROM BRND_BRANDPACK 
						   WHERE BRANDPACK_ID = @BRANDPACK_ID));
SELECT @O_UNIT = (SELECT UNIT FROM BRND_BRANDPACK WHERE BRANDPACK_ID = @BRANDPACK_ID );
SELECT TOP 1 @V_ApplyTo = APPLY_TO,@V_ApplyDate = APPLY_DATE FROM BRND_DISC_HEADER WHERE IDApp = @IDApp 
IF @IDApp > 0
	BEGIN 
		 SET @V_BRAND_ID = (SELECT BRAND_ID FROM BRND_BRANDPACK WHERE BRANDPACK_ID = @BRANDPACK_ID);
		 --check apakah discount by brandpack/by brand
		 IF (SELECT COUNT(*) FROM BRND_DISC_LIST_BRANDPACK WHERE FKApp = @IDApp) > 0
			--DISCOUNT BY BRANDPACK BERARTI
			BEGIN 
			--CHECK APAKAH BrandPack nya sama 
				SET @V_IsDiscByBrandPack = CONVERT(BIT,ISNULL((SELECT 1 WHERE EXISTS(SELECT IDApp FROM BRND_DISC_PROG WHERE FKApp = @IDApp AND BRANDPACK_ID = @BRANDPACK_ID)),0));
				SET @V_IsDiscByBrandPackForAll = CONVERT(BIT,ISNULL((SELECT 1 WHERE EXISTS(SELECT IDApp FROM BRND_DISC_LIST_BRANDPACK WHERE FKApp = @IDApp AND BRANDPACK_ID =@BRANDPACK_ID)),0));
				IF @V_IsDiscByBrandPackForAll = 0 
					RETURN 0;	 
				
			END
		 ELSE IF EXISTS(SELECT BDLB.BRAND_ID FROM BRND_DISC_LIST_BRAND BDLB INNER JOIN BRND_DISC_PROG BDP ON BDLB.BRAND_ID = BDP.BRAND_ID
						WHERE BDlB.BRAND_ID = @V_BRAND_ID AND BDP.FKApp = @IDApp)
				SET @V_IsByBrand = 1;
		 ELSE IF NOT EXISTS(SELECT BRAND_ID FROM BRND_DISC_LIST_BRAND WHERE BRAND_ID = @V_BRAND_ID AND FKApp = @IDApp)
			RETURN 0;				
		IF @V_IsDiscByBrandPack > 0
			BEGIN
				SELECT @O_DD = CONVERT(BIT,ISNULL((SELECT 1 WHERE EXISTS(SELECT TypeApp FROM BRND_DISC_PROG WHERE FKApp = @IDApp AND TypeApp = 'DD' AND BRANDPACK_ID = @BRANDPACK_ID)),0));
				SELECT @O_DR =  CONVERT(BIT,ISNULL((SELECT 1 WHERE EXISTS(SELECT TypeApp FROM BRND_DISC_PROG WHERE FKApp = @IDApp AND TypeApp = 'DR' AND BRANDPACK_ID = @BRANDPACK_ID)),0));
				SELECT @O_CBD = CONVERT(BIT,ISNULL((SELECT 1 WHERE EXISTS(SELECT TypeApp FROM BRND_DISC_PROG WHERE FKApp = @IDApp AND TypeApp = 'CBD' AND BRANDPACK_ID = @BRANDPACK_ID)),0));
				SELECT @O_DK = CONVERT(BIT,ISNULL((SELECT 1 WHERE EXISTS(SELECT TypeApp FROM BRND_DISC_PROG WHERE FKApp = @IDApp AND TypeApp = 'Dk' AND BRANDPACK_ID = @BRANDPACK_ID)),0));
				SELECT @O_DP = CONVERT(BIT,ISNULL((SELECT 1 WHERE EXISTS(SELECT TypeApp FROM BRND_DISC_PROG WHERE FKApp = @IDApp AND TypeApp = 'DP' AND BRANDPACK_ID = @BRANDPACK_ID)),0));	
			END
		ELSE IF @V_IsDiscByBrandPackForAll > 0
			BEGIN
				SELECT @O_DD = CONVERT(BIT,ISNULL((SELECT 1 WHERE EXISTS(SELECT TypeApp FROM BRND_DISC_PROG WHERE FKApp = @IDApp AND TypeApp = 'DD')),0));
				SELECT @O_DR =  CONVERT(BIT,ISNULL((SELECT 1 WHERE EXISTS(SELECT TypeApp FROM BRND_DISC_PROG WHERE FKApp = @IDApp AND TypeApp = 'DR')),0));
				SELECT @O_CBD = CONVERT(BIT,ISNULL((SELECT 1 WHERE EXISTS(SELECT TypeApp FROM BRND_DISC_PROG WHERE FKApp = @IDApp AND TypeApp = 'CBD')),0));
				SELECT @O_DK = CONVERT(BIT,ISNULL((SELECT 1 WHERE EXISTS(SELECT TypeApp FROM BRND_DISC_PROG WHERE FKApp = @IDApp AND TypeApp = 'DK')),0));	
				SELECT @O_DP = CONVERT(BIT,ISNULL((SELECT 1 WHERE EXISTS(SELECT TypeApp FROM BRND_DISC_PROG WHERE FKApp = @IDApp AND TypeApp = 'DP')),0));	
			END
		ELSE IF @V_IsByBrand > 0
			BEGIN
				SELECT @O_DD = CONVERT(BIT,ISNULL((SELECT 1 WHERE EXISTS(SELECT TypeApp FROM BRND_DISC_PROG WHERE FKApp = @IDApp AND TypeApp = 'DD' AND BRAND_ID = @V_BRAND_ID)),0));
				SELECT @O_DR =  CONVERT(BIT,ISNULL((SELECT 1 WHERE EXISTS(SELECT TypeApp FROM BRND_DISC_PROG WHERE FKApp = @IDApp AND TypeApp = 'DR' AND BRAND_ID = @V_BRAND_ID)),0));
				SELECT @O_CBD = CONVERT(BIT,ISNULL((SELECT 1 WHERE EXISTS(SELECT TypeApp FROM BRND_DISC_PROG WHERE FKApp = @IDApp AND TypeApp = 'CBD' AND BRAND_ID = @V_BRAND_ID)),0));
				SELECT @O_DK = CONVERT(BIT,ISNULL((SELECT 1 WHERE EXISTS(SELECT TypeApp FROM BRND_DISC_PROG WHERE FKApp = @IDApp AND TypeApp = 'DK' AND BRAND_ID = @V_BRAND_ID)),0));
				SELECT @O_DP = CONVERT(BIT,ISNULL((SELECT 1 WHERE EXISTS(SELECT TypeApp FROM BRND_DISC_PROG WHERE FKApp = @IDApp AND TypeApp = 'DP' AND BRAND_ID = @V_BRAND_ID)),0));
			END
		ELSE
			BEGIN
				SELECT @O_DD = CONVERT(BIT,ISNULL((SELECT 1 WHERE EXISTS(SELECT TypeApp FROM BRND_DISC_PROG WHERE FKApp = @IDApp AND TypeApp = 'DD')),0));
				SELECT @O_DR =  CONVERT(BIT,ISNULL((SELECT 1 WHERE EXISTS(SELECT TypeApp FROM BRND_DISC_PROG WHERE FKApp = @IDApp AND TypeApp = 'DR')),0));
				SELECT @O_CBD = CONVERT(BIT,ISNULL((SELECT 1 WHERE EXISTS(SELECT TypeApp FROM BRND_DISC_PROG WHERE FKApp = @IDApp AND TypeApp = 'CBD')),0));
				SELECT @O_DK = CONVERT(BIT,ISNULL((SELECT 1 WHERE EXISTS(SELECT TypeApp FROM BRND_DISC_PROG WHERE FKApp = @IDApp AND TypeApp = 'DK')),0));
				SELECT @O_DP = CONVERT(BIT,ISNULL((SELECT 1 WHERE EXISTS(SELECT TypeApp FROM BRND_DISC_PROG WHERE FKApp = @IDApp AND TypeApp = 'DP')),0));	
			END	
		IF @V_ApplyTo = 'AL'
			RETURN 1
		 IF @V_ApplyTo = 'CD'
			BEGIN
                SELECT TOP 1 @V_START_DATE_PKD = AA.START_DATE,@V_END_DATE_PKD = AA.END_DATE FROM AGREE_AGREEMENT AA  
                INNER JOIN DISTRIBUTOR_AGREEMENT DA ON DA.AGREEMENT_NO = AA.AGREEMENT_NO INNER JOIN AGREE_BRANDPACK_INCLUDE ABP ON ABP.AGREEMENT_NO = AA.AGREEMENT_NO  
                WHERE AA.END_DATE >= @PO_DATE AND AA.START_DATE <= @PO_DATE AND DA.DISTRIBUTOR_ID = @DISTRIBUTOR_ID AND ABP.BRANDPACK_ID = @BRANDPACK_ID ; 
                IF (@V_ApplyDate >=@V_START_DATE_PKD) AND (@V_ApplyDate <=@V_END_DATE_PKD)  
                BEGIN 				
				  RETURN(SELECT 1 WHERE EXISTS(SELECT DISTRIBUTOR_ID FROM DIST_DISC_BRAND_LIST WHERE DISTRIBUTOR_ID = @DISTRIBUTOR_ID AND FKApp = @IDApp));  
                END 
			END
		 ELSE IF @V_ApplyTo = 'GD'
			BEGIN
				SELECT TOP 1 @V_START_DATE_PKD = AA.START_DATE,@V_END_DATE_PKD = AA.END_DATE FROM AGREE_AGREEMENT AA 
                INNER JOIN DISTRIBUTOR_AGREEMENT DA ON DA.AGREEMENT_NO = AA.AGREEMENT_NO INNER JOIN AGREE_BRANDPACK_INCLUDE ABP ON ABP.AGREEMENT_NO = AA.AGREEMENT_NO 
                WHERE AA.END_DATE >= @PO_DATE AND AA.START_DATE <= @PO_DATE AND DA.DISTRIBUTOR_ID = @DISTRIBUTOR_ID AND ABP.BRANDPACK_ID = @BRANDPACK_ID ;
                IF (@V_ApplyDate >=@V_START_DATE_PKD) AND (@V_ApplyDate <=@V_END_DATE_PKD)   
				BEGIN 
					RETURN (SELECT 1 WHERE EXISTS(SELECT DGL.DISTRIBUTOR_ID FROM DIST_GROUP_LIST DGL INNER JOIN DIST_GROUP_BRND_LIST GBL ON GBL.FKGroup = DGL.GRP_ID 
                    WHERE GBL.FKDisc = @IDApp AND DGL.DISTRIBUTOR_ID = @DISTRIBUTOR_ID));
				END
			END
	END
ELSE
	RETURN 0
GO


IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Create_View_Distributor_Report_1' AND TYPE = 'P')
DROP PROCEDURE Usp_Create_View_Distributor_Report_1
GO
CREATE PROCEDURE Usp_Create_View_Distributor_Report_1
@StartDate DateTime,
@EndDate DateTime
AS 
SET NOCOUNT ON;
IF (@StartDate IS NOT NULL AND @EndDate IS NOT NULL)
BEGIN
	 SELECT DG.REGIONAL_AREA,TER.TERRITORY_AREA,OPO.DISTRIBUTOR_ID,DR.DISTRIBUTOR_NAME,OPO.PO_REF_NO,OPO.PO_REF_DATE,
	OOA.OA_ID AS OA_REF_NO,OOA.OA_DATE,BR.BRAND_ID,BR.BRAND_NAME,BB.BRANDPACK_ID,BB.BRANDPACK_NAME,OPB.PO_ORIGINAL_QTY AS PO_QTY,OOB.QTY_EVEN,
	OPB.PO_PRICE_PERQTY AS PRICE,OOB.UNIT,OOB.REMARK,OPB.DESCRIPTIONS2 AS CSE_REMARK,ISNULL(OA_DISC.REMAIND_QTY,0)AS REMAIND_QTY,OA_DISC.GIVEN_AGREEMENT,OA_DISC.[QUARTER],
	OA_DISC.[SEMESTER],OA_DISC.YEARLY,OA_DISC.RPK,OA_DISC.DK,OA_DISC.CP_D,OA_DISC.CP_D_S,OA_DISC.CP_RMT,OA_DISC.PKPP,OA_DISC.CP_R,
	OA_DISC.CP_D_AUTO,OA_DISC.OTHER,OA_DISC.OTHER_DD,OA_DISC.OTHER_DR,OA_DISC.OTHER_DK,OA_DISC.OTHER_CBD,
	ISNULL(T_DISC.TOTAL_DISC,0)AS TOTAL_DISC,
	--ISNULL(T_DISC.TOTAL_DISC,0) * OOB.OA_PRICE_PERQTY AS TOTAL_DISC_AMOUNT,
	OOB.QTY_EVEN + ISNULL(T_DISC.TOTAL_DISC,0) + ISNULL(OA_LEFT.TOTAL_DISC,0) AS TOTAL_DELIVERY,
	--(OOB.QTY_EVEN + ISNULL(T_DISC.TOTAL_DISC,0) + ISNULL(OA_LEFT.TOTAL_DISC,0)) * OOB.OA_PRICE_PERQTY AS TOTAL_AMOUNT_DELIVERY,
	OOB.QTY_EVEN + ISNULL(OA_LEFT.TOTAL_DISC,0) AS TOTAL_SALES
	--(OOB.QTY_EVEN + ISNULL(OA_LEFT.TOTAL_DISC,0)) * OOB.OA_PRICE_PERQTY AS TOTAL_AMOUNT_SALES         
	FROM ORDR_PURCHASE_ORDER OPO INNER JOIN DIST_DISTRIBUTOR DR ON OPO.DISTRIBUTOR_ID = DR.DISTRIBUTOR_ID
	 INNER JOIN ORDR_PO_BRANDPACK OPB ON OPB.PO_REF_NO = OPO.PO_REF_NO LEFT OUTER JOIN ORDR_ORDER_ACCEPTANCE OOA
	ON OOA.PO_REF_NO = OPB.PO_REF_NO --INNER JOIN BRND_BRAND BR ON BR.BRAND_ID = BB.BRAND_ID
	LEFT OUTER JOIN ORDR_OA_BRANDPACK OOB ON OOB.PO_BRANDPACK_ID = OPB.PO_BRANDPACK_ID AND OOB.OA_ID = OOA.OA_ID
	INNER JOIN BRND_BRANDPACK BB ON OPB.BRANDPACK_ID = BB.BRANDPACK_ID --INNER JOIN ORDR_OA_BRANDPACK_DISC OOBD ON OOBD.OA_BRANDPACK_ID = OOB.OA_BRANDPACK_ID
	LEFT OUTER JOIN
	               (
	                 SELECT OA_BRANDPACK_ID,
	                 SUM(CASE GQSY_SGT_P_FLAG WHEN 'RMOA' THEN DISC_QTY ELSE 0 END)AS REMAIND_QTY,
	                 SUM(CASE GQSY_SGT_P_FLAG WHEN 'G' THEN DISC_QTY ELSE 0 END)AS GIVEN_AGREEMENT, 
	            	 SUM(CASE GQSY_SGT_P_FLAG WHEN 'Q1' THEN DISC_QTY WHEN 'Q2' THEN DISC_QTY WHEN 'Q3' THEN DISC_QTY
	                                     	  WHEN 'Q4' THEN DISC_QTY ELSE 0 END)AS [QUARTER],
	            	 SUM(CASE GQSY_SGT_P_FLAG WHEN 'S1' THEN DISC_QTY WHEN 'S2' THEN DISC_QTY ELSE 0 END)AS [SEMESTER], 
	           		 SUM(CASE GQSY_SGT_P_FLAG WHEN 'Y' THEN DISC_QTY ELSE 0 END)AS YEARLY, 
	           		 SUM(CASE GQSY_SGT_P_FLAG WHEN 'MG' THEN DISC_QTY ELSE 0 END)AS RPK,
					 SUM(CASE GQSY_SGT_P_FLAG WHEN 'DK' THEN DISC_QTY WHEN 'DN' THEN DISC_QTY ELSE 0 END)AS DK,
	           		 SUM(CASE GQSY_SGT_P_FLAG WHEN 'CP' THEN DISC_QTY WHEN 'TD' THEN DISC_QTY ELSE 0 END)AS CP_D,
					 SUM(CASE GQSY_SGT_P_FLAG WHEN 'CS' THEN DISC_QTY WHEN 'TS' THEN DISC_QTY WHEN 'SC' THEN DISC_QTY ELSE 0 END)AS CP_D_S,
					 SUM(CASE GQSY_SGT_P_FLAG WHEN 'CD' THEN DISC_QTY WHEN 'CT' THEN DISC_QTY ELSE 0 END)AS CP_RMT,
					 SUM(CASE GQSY_SGT_P_FLAG WHEN 'KP' THEN DISC_QTY ELSE 0 END)AS PKPP,
					 SUM(CASE GQSY_SGT_P_FLAG WHEN 'CR' THEN DISC_QTY ELSE 0 END) AS CP_R,
					 SUM(CASE GQSY_SGT_P_FLAG WHEN 'CA' THEN DISC_QTY ELSE 0 END) AS CP_D_AUTO,
					 SUM(CASE GQSY_SGT_P_FLAG WHEN 'O'  THEN DISC_QTY ELSE 0 END) AS OTHER,
					 SUM(CASE GQSY_SGT_P_FLAG WHEN 'ODD' THEN DISC_QTY ELSE 0 END) AS OTHER_DD,
					 SUM(CASE GQSY_SGT_P_FLAG WHEN 'ODR' THEN DISC_QTY ELSE 0 END) AS OTHER_DR,
					 SUM(CASE GQSY_SGT_P_FLAG WHEN 'OCBD' THEN DISC_QTY ELSE 0 END) AS OTHER_CBD,
					 SUM(CASE GQSY_SGT_P_FLAG WHEN 'ODK' THEN DISC_QTY ELSE 0 END) AS OTHER_DK
					 FROM ORDR_OA_BRANDPACK_DISC GROUP BY OA_BRANDPACK_ID
	           	)OA_DISC ON OA_DISC.OA_BRANDPACK_ID = OOB.OA_BRANDPACK_ID
	LEFT OUTER JOIN(
	                 SELECT OA_BRANDPACK_ID,ISNULL(SUM(DISC_QTY),0)AS TOTAL_DISC FROM ORDR_OA_BRANDPACK_DISC 
	                 WHERE GQSY_SGT_P_FLAG != 'RMOA'
	                 GROUP BY OA_BRANDPACK_ID
	                )T_DISC ON OOB.OA_BRANDPACK_ID = T_DISC.OA_BRANDPACK_ID
	LEFT OUTER JOIN( 
	                 SELECT OA_BRANDPACK_ID,ISNULL(SUM(DISC_QTY),0)AS TOTAL_DISC FROM ORDR_OA_BRANDPACK_DISC 
	                 WHERE GQSY_SGT_P_FLAG = 'RMOA'
	                 GROUP BY OA_BRANDPACK_ID
	                )OA_LEFT ON OA_LEFT.OA_BRANDPACK_ID = OOB.OA_BRANDPACK_ID 
	INNER JOIN TERRITORY TER ON TER.TERRITORY_ID = DR.TERRITORY_ID
	INNER JOIN DIST_REGIONAL DG ON DG.REGIONAL_ID = TER.REGIONAL_ID 
	INNER JOIN BRND_BRAND BR ON BR.BRAND_ID = BB.BRAND_ID
	WHERE OPO.PO_REF_DATE >= @StartDate AND OPO.PO_REF_DATE <= @EndDate
END
ELSE IF (@StartDate IS NOT NULL)
BEGIN
	 SELECT DG.REGIONAL_AREA,TER.TERRITORY_AREA,OPO.DISTRIBUTOR_ID,DR.DISTRIBUTOR_NAME,OPO.PO_REF_NO,OPO.PO_REF_DATE,
	OOA.OA_ID AS OA_REF_NO,OOA.OA_DATE,BR.BRAND_ID,BR.BRAND_NAME,BB.BRANDPACK_ID,BB.BRANDPACK_NAME,OPB.PO_ORIGINAL_QTY AS PO_QTY,OOB.QTY_EVEN,
	OPB.PO_PRICE_PERQTY AS PRICE,OOB.UNIT,OOB.REMARK,OPB.DESCRIPTIONS2 AS CSE_REMARK,ISNULL(OA_DISC.REMAIND_QTY,0)AS REMAIND_QTY,OA_DISC.GIVEN_AGREEMENT,OA_DISC.[QUARTER],
	OA_DISC.[SEMESTER],OA_DISC.YEARLY,OA_DISC.RPK,OA_DISC.DK,OA_DISC.CP_D,OA_DISC.CP_D_S,OA_DISC.CP_RMT,OA_DISC.PKPP,OA_DISC.CP_R,
	OA_DISC.CP_D_AUTO,OA_DISC.OTHER,OA_DISC.OTHER_DD,OA_DISC.OTHER_DR,OA_DISC.OTHER_DK,OA_DISC.OTHER_CBD,
	ISNULL(T_DISC.TOTAL_DISC,0)AS TOTAL_DISC,
	--ISNULL(T_DISC.TOTAL_DISC,0) * OOB.OA_PRICE_PERQTY AS TOTAL_DISC_AMOUNT,
	OOB.QTY_EVEN + ISNULL(T_DISC.TOTAL_DISC,0) + ISNULL(OA_LEFT.TOTAL_DISC,0) AS TOTAL_DELIVERY,
	--(OOB.QTY_EVEN + ISNULL(T_DISC.TOTAL_DISC,0) + ISNULL(OA_LEFT.TOTAL_DISC,0)) * OOB.OA_PRICE_PERQTY AS TOTAL_AMOUNT_DELIVERY,
	OOB.QTY_EVEN + ISNULL(OA_LEFT.TOTAL_DISC,0) AS TOTAL_SALES
	--(OOB.QTY_EVEN + ISNULL(OA_LEFT.TOTAL_DISC,0)) * OOB.OA_PRICE_PERQTY AS TOTAL_AMOUNT_SALES              
	FROM ORDR_PURCHASE_ORDER OPO INNER JOIN DIST_DISTRIBUTOR DR ON OPO.DISTRIBUTOR_ID = DR.DISTRIBUTOR_ID
	 INNER JOIN ORDR_PO_BRANDPACK OPB ON OPB.PO_REF_NO = OPO.PO_REF_NO LEFT OUTER JOIN ORDR_ORDER_ACCEPTANCE OOA
	ON OOA.PO_REF_NO = OPB.PO_REF_NO --INNER JOIN BRND_BRAND BR ON BR.BRAND_ID = BB.BRAND_ID
	LEFT OUTER JOIN ORDR_OA_BRANDPACK OOB ON OOB.PO_BRANDPACK_ID = OPB.PO_BRANDPACK_ID AND OOB.OA_ID = OOA.OA_ID
	INNER JOIN BRND_BRANDPACK BB ON OPB.BRANDPACK_ID = BB.BRANDPACK_ID --INNER JOIN ORDR_OA_BRANDPACK_DISC OOBD ON OOBD.OA_BRANDPACK_ID = OOB.OA_BRANDPACK_ID
	LEFT OUTER JOIN
	               (
	                 SELECT OA_BRANDPACK_ID,
	                 SUM(CASE GQSY_SGT_P_FLAG WHEN 'RMOA' THEN DISC_QTY ELSE 0 END)AS REMAIND_QTY,
	                 SUM(CASE GQSY_SGT_P_FLAG WHEN 'G' THEN DISC_QTY ELSE 0 END)AS GIVEN_AGREEMENT, 
	            	 SUM(CASE GQSY_SGT_P_FLAG WHEN 'Q1' THEN DISC_QTY WHEN 'Q2' THEN DISC_QTY WHEN 'Q3' THEN DISC_QTY
	                                     	  WHEN 'Q4' THEN DISC_QTY ELSE 0 END)AS [QUARTER],
	            	 SUM(CASE GQSY_SGT_P_FLAG WHEN 'S1' THEN DISC_QTY WHEN 'S2' THEN DISC_QTY ELSE 0 END)AS [SEMESTER], 
	           		 SUM(CASE GQSY_SGT_P_FLAG WHEN 'Y' THEN DISC_QTY ELSE 0 END)AS YEARLY, 
	           		 SUM(CASE GQSY_SGT_P_FLAG WHEN 'MG' THEN DISC_QTY ELSE 0 END)AS RPK,
					 SUM(CASE GQSY_SGT_P_FLAG WHEN 'DK' THEN DISC_QTY WHEN 'DN' THEN DISC_QTY ELSE 0 END)AS DK,
					 SUM(CASE GQSY_SGT_P_FLAG WHEN 'CP' THEN DISC_QTY WHEN 'TD' THEN DISC_QTY ELSE 0 END)AS CP_D,
					 SUM(CASE GQSY_SGT_P_FLAG WHEN 'CS' THEN DISC_QTY WHEN 'TS' THEN DISC_QTY WHEN 'SC' THEN DISC_QTY ELSE 0 END)AS CP_D_S,
	            	 SUM(CASE GQSY_SGT_P_FLAG WHEN 'CD' THEN DISC_QTY WHEN 'CT' THEN DISC_QTY ELSE 0 END)AS CP_RMT,
					 SUM(CASE GQSY_SGT_P_FLAG WHEN 'KP' THEN DISC_QTY ELSE 0 END)AS PKPP,
	            	 SUM(CASE GQSY_SGT_P_FLAG WHEN 'CR' THEN DISC_QTY ELSE 0 END) AS CP_R,
					 SUM(CASE GQSY_SGT_P_FLAG WHEN 'CA' THEN DISC_QTY ELSE 0 END) AS CP_D_AUTO,
	            	 SUM(CASE GQSY_SGT_P_FLAG WHEN 'O'  THEN DISC_QTY ELSE 0 END)AS OTHER,
					 SUM(CASE GQSY_SGT_P_FLAG WHEN 'ODD' THEN DISC_QTY ELSE 0 END) AS OTHER_DD,
					 SUM(CASE GQSY_SGT_P_FLAG WHEN 'ODR' THEN DISC_QTY ELSE 0 END) AS OTHER_DR,
					 SUM(CASE GQSY_SGT_P_FLAG WHEN 'OCBD' THEN DISC_QTY ELSE 0 END) AS OTHER_CBD,
					 SUM(CASE GQSY_SGT_P_FLAG WHEN 'ODK' THEN DISC_QTY ELSE 0 END) AS OTHER_DK
	            	 FROM ORDR_OA_BRANDPACK_DISC GROUP BY OA_BRANDPACK_ID
	           	)OA_DISC ON OA_DISC.OA_BRANDPACK_ID = OOB.OA_BRANDPACK_ID
	LEFT OUTER JOIN(
	                 SELECT OA_BRANDPACK_ID,ISNULL(SUM(DISC_QTY),0)AS TOTAL_DISC FROM ORDR_OA_BRANDPACK_DISC 
	                 WHERE GQSY_SGT_P_FLAG != 'RMOA'
	                 GROUP BY OA_BRANDPACK_ID
	                )T_DISC ON OOB.OA_BRANDPACK_ID = T_DISC.OA_BRANDPACK_ID
	LEFT OUTER JOIN( 
	                 SELECT OA_BRANDPACK_ID,ISNULL(SUM(DISC_QTY),0)AS TOTAL_DISC FROM ORDR_OA_BRANDPACK_DISC 
	                 WHERE GQSY_SGT_P_FLAG = 'RMOA'
	                 GROUP BY OA_BRANDPACK_ID
	                )OA_LEFT ON OA_LEFT.OA_BRANDPACK_ID = OOB.OA_BRANDPACK_ID 
	INNER JOIN TERRITORY TER ON TER.TERRITORY_ID = DR.TERRITORY_ID
	INNER JOIN DIST_REGIONAL DG ON DG.REGIONAL_ID = TER.REGIONAL_ID 
	INNER JOIN BRND_BRAND BR ON BR.BRAND_ID = BB.BRAND_ID
	WHERE OPO.PO_REF_DATE >= @StartDate
END
ELSE IF (@EndDate IS NOT NULL)
BEGIN
   SELECT DG.REGIONAL_AREA,TER.TERRITORY_AREA,OPO.DISTRIBUTOR_ID,DR.DISTRIBUTOR_NAME,OPO.PO_REF_NO,OPO.PO_REF_DATE,
	OOA.OA_ID AS OA_REF_NO,OOA.OA_DATE,BR.BRAND_ID,BR.BRAND_NAME,BB.BRANDPACK_ID,BB.BRANDPACK_NAME,OPB.PO_ORIGINAL_QTY AS PO_QTY,OOB.QTY_EVEN,
	OPB.PO_PRICE_PERQTY AS PRICE,OOB.UNIT,OOB.REMARK,OPB.DESCRIPTIONS2 AS CSE_REMARK,ISNULL(OA_DISC.REMAIND_QTY,0)AS REMAIND_QTY,OA_DISC.GIVEN_AGREEMENT,OA_DISC.[QUARTER],
	OA_DISC.[SEMESTER],OA_DISC.YEARLY,OA_DISC.RPK,OA_DISC.DK,OA_DISC.CP_D,OA_DISC.CP_D_S,OA_DISC.CP_RMT,OA_DISC.PKPP,OA_DISC.CP_R,
	OA_DISC.CP_D_AUTO,OA_DISC.OTHER,OA_DISC.OTHER_DD,OA_DISC.OTHER_DR,OA_DISC.OTHER_DK,OA_DISC.OTHER_CBD,
	ISNULL(T_DISC.TOTAL_DISC,0)AS TOTAL_DISC,
	--ISNULL(T_DISC.TOTAL_DISC,0) * OOB.OA_PRICE_PERQTY AS TOTAL_DISC_AMOUNT,
	OOB.QTY_EVEN + ISNULL(T_DISC.TOTAL_DISC,0) + ISNULL(OA_LEFT.TOTAL_DISC,0) AS TOTAL_DELIVERY,
	--(OOB.QTY_EVEN + ISNULL(T_DISC.TOTAL_DISC,0) + ISNULL(OA_LEFT.TOTAL_DISC,0)) * OOB.OA_PRICE_PERQTY AS TOTAL_AMOUNT_DELIVERY,
	OOB.QTY_EVEN + ISNULL(OA_LEFT.TOTAL_DISC,0) AS TOTAL_SALES
	--(OOB.QTY_EVEN + ISNULL(OA_LEFT.TOTAL_DISC,0)) * OOB.OA_PRICE_PERQTY AS TOTAL_AMOUNT_SALES       
	FROM ORDR_PURCHASE_ORDER OPO INNER JOIN DIST_DISTRIBUTOR DR ON OPO.DISTRIBUTOR_ID = DR.DISTRIBUTOR_ID
	 INNER JOIN ORDR_PO_BRANDPACK OPB ON OPB.PO_REF_NO = OPO.PO_REF_NO LEFT OUTER JOIN ORDR_ORDER_ACCEPTANCE OOA
	ON OOA.PO_REF_NO = OPB.PO_REF_NO --INNER JOIN BRND_BRAND BR ON BR.BRAND_ID = BB.BRAND_ID
	LEFT OUTER JOIN ORDR_OA_BRANDPACK OOB ON OOB.PO_BRANDPACK_ID = OPB.PO_BRANDPACK_ID AND OOB.OA_ID = OOA.OA_ID
	INNER JOIN BRND_BRANDPACK BB ON OPB.BRANDPACK_ID = BB.BRANDPACK_ID --INNER JOIN ORDR_OA_BRANDPACK_DISC OOBD ON OOBD.OA_BRANDPACK_ID = OOB.OA_BRANDPACK_ID
	LEFT OUTER JOIN
	               (
	                 SELECT OA_BRANDPACK_ID,
	                 SUM(CASE GQSY_SGT_P_FLAG WHEN 'RMOA' THEN DISC_QTY ELSE 0 END)AS REMAIND_QTY,
	                 SUM(CASE GQSY_SGT_P_FLAG WHEN 'G' THEN DISC_QTY ELSE 0 END)AS GIVEN_AGREEMENT, 
	            	 SUM(CASE GQSY_SGT_P_FLAG WHEN 'Q1' THEN DISC_QTY WHEN 'Q2' THEN DISC_QTY WHEN 'Q3' THEN DISC_QTY
	                                     	  WHEN 'Q4' THEN DISC_QTY ELSE 0 END)AS [QUARTER],
	            	 SUM(CASE GQSY_SGT_P_FLAG WHEN 'S1' THEN DISC_QTY WHEN 'S2' THEN DISC_QTY ELSE 0 END)AS [SEMESTER], 
	           		 SUM(CASE GQSY_SGT_P_FLAG WHEN 'Y' THEN DISC_QTY ELSE 0 END)AS YEARLY, 
	           		 SUM(CASE GQSY_SGT_P_FLAG WHEN 'MG' THEN DISC_QTY ELSE 0 END)AS RPK,
	            	 SUM(CASE GQSY_SGT_P_FLAG WHEN 'DK' THEN DISC_QTY WHEN 'DN' THEN DISC_QTY ELSE 0 END)AS DK,
					 SUM(CASE GQSY_SGT_P_FLAG WHEN 'CP' THEN DISC_QTY WHEN 'TD' THEN DISC_QTY ELSE 0 END)AS CP_D,
					 SUM(CASE GQSY_SGT_P_FLAG WHEN 'CS' THEN DISC_QTY WHEN 'TS' THEN DISC_QTY WHEN 'SC' THEN DISC_QTY ELSE 0 END)AS CP_D_S,
					 SUM(CASE GQSY_SGT_P_FLAG WHEN 'CD' THEN DISC_QTY WHEN 'CT' THEN DISC_QTY ELSE 0 END)AS CP_RMT,
	            	 SUM(CASE GQSY_SGT_P_FLAG WHEN 'KP' THEN DISC_QTY ELSE 0 END)AS PKPP,
	            	 SUM(CASE GQSY_SGT_P_FLAG WHEN 'CR' THEN DISC_QTY ELSE 0 END) AS CP_R,
					 SUM(CASE GQSY_SGT_P_FLAG WHEN 'CA' THEN DISC_QTY ELSE 0 END) AS CP_D_AUTO,
	            	 SUM(CASE GQSY_SGT_P_FLAG WHEN 'O'  THEN DISC_QTY ELSE 0 END) AS OTHER,
					 SUM(CASE GQSY_SGT_P_FLAG WHEN 'ODD' THEN DISC_QTY ELSE 0 END) AS OTHER_DD,
					 SUM(CASE GQSY_SGT_P_FLAG WHEN 'ODR' THEN DISC_QTY ELSE 0 END) AS OTHER_DR,
					 SUM(CASE GQSY_SGT_P_FLAG WHEN 'OCBD' THEN DISC_QTY ELSE 0 END) AS OTHER_CBD,
					 SUM(CASE GQSY_SGT_P_FLAG WHEN 'ODK' THEN DISC_QTY ELSE 0 END) AS OTHER_DK
	            	 FROM ORDR_OA_BRANDPACK_DISC GROUP BY OA_BRANDPACK_ID
	           	)OA_DISC ON OA_DISC.OA_BRANDPACK_ID = OOB.OA_BRANDPACK_ID
	LEFT OUTER JOIN(
	                 SELECT OA_BRANDPACK_ID,ISNULL(SUM(DISC_QTY),0)AS TOTAL_DISC FROM ORDR_OA_BRANDPACK_DISC 
	                 WHERE GQSY_SGT_P_FLAG != 'RMOA'
	                 GROUP BY OA_BRANDPACK_ID
	                )T_DISC ON OOB.OA_BRANDPACK_ID = T_DISC.OA_BRANDPACK_ID
	LEFT OUTER JOIN( 
	                 SELECT OA_BRANDPACK_ID,ISNULL(SUM(DISC_QTY),0)AS TOTAL_DISC FROM ORDR_OA_BRANDPACK_DISC 
	                 WHERE GQSY_SGT_P_FLAG = 'RMOA'
	                 GROUP BY OA_BRANDPACK_ID
	                )OA_LEFT ON OA_LEFT.OA_BRANDPACK_ID = OOB.OA_BRANDPACK_ID 
	INNER JOIN TERRITORY TER ON TER.TERRITORY_ID = DR.TERRITORY_ID
	INNER JOIN DIST_REGIONAL DG ON DG.REGIONAL_ID = TER.REGIONAL_ID 
	INNER JOIN BRND_BRAND BR ON BR.BRAND_ID = BB.BRAND_ID
	WHERE OPO.PO_REF_DATE <= @EndDate
END
GO