--PROCEDURE UNTUK MEMVIEW REMAINDING QTY BERDASARKAN FLAG

IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_CreateView_Remainding_Detail'
 AND TYPE = 'P')
DROP PROCEDURE Usp_CreateView_Remainding_Detail
GO
CREATE PROCEDURE Usp_CreateView_Remainding_Detail
@OA_BRANDPACK_ID VARCHAR(75),
@FLAG VARCHAR(5)
AS
SET NOCOUNT ON;
SELECT OPB.PO_REF_NO,OOB.OA_ID AS OA_REF_NO,OOR.QTY,OOR.RELEASE_QTY,OOR.LEFT_QTY
FROM ORDR_PO_BRANDPACK OPB INNER JOIN ORDR_OA_BRANDPACK OOB ON OOB.PO_BRANDPACK_ID = OPB.PO_BRANDPACK_ID
INNER JOIN ORDR_OA_REMAINDING OOR ON OOR.OA_BRANDPACK_ID = OOB.OA_BRANDPACK_ID
WHERE OOB.OA_BRANDPACK_ID = @OA_BRANDPACK_ID AND OOR.FLAG = @FLAG

GO
------------------------------------------------------------------------------
--PROCEDURE UNTUK MEMVIEW TOTAL LEFT QUATITY DARI DISTIBUTOR YANG BISA DIAMBIL
/*
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_CreateView_Total_Left_Remainding'
AND TYPE = 'P')
DROP PROCEDURE Usp_CreateView_Total_Left_Remainding
GO
CREATE PROCEDURE Usp_CreateView_Total_Left_Remainding
@RM_HEADER_ID VARCHAR(25)
AS
SELECT OA_REMAINDING_HEADER.RM_HEADER_ID,OA_REMAINDING_HEADER.BRANDPACK_ID,
BRND_BRANDPACK.BRANDPACK_NAME,OA_REMAINDING_HEADER.QTY,OA_REMAINDING_HEADER.RELEASE_QTY,
OA_REMAINDING_HEADER.LEFT_QTY,OA_REMAINDING_HEADER.MODIFY_DATE AS DATE_UPDATED
FROM
OA_REMAINDING_HEADER INNER JOIN BRND_BRANDPACK ON OA_REMAINDING_HEADER.BRANDPACK_ID
= BRND_BRANDPACK.BRANDPACK_ID
WHERE OA_REMAINDING_HEADER.RM_HEADER_ID = @RM_HEADER_ID
GO
*/
--------------------------------------------------------------------------------
--PROCEDURE UNTUK MEMVIEW DATA OA_REMAINDING TABLE ORDR_OA_REMAINDING
IF EXISTS(SELECT NAME FROM SYS.SYSOBJECTS WHERE NAME = 'Usp_Select_OA_Remainding_Detail' AND TYPE = 'P')
DROP PROCEDURE Usp_Select_OA_Remainding_Detail
GO
CREATE PROCEDURE Usp_Select_OA_Remainding_Detail
@DISTRIBUTOR_ID VARCHAR(10),
@BRANDPACK_ID VARCHAR(14),
@OA_ID VARCHAR(32)
AS-----------------------------------------------------------------------------------------------
execute sp_executesql
N'SET NOCOUNT ON;SET IMPLICIT_TRANSACTIONS OFF
DECLARE @V_BRANDPACK_NAME VARCHAR(14),@V_OA_DATE DATETIME;
SET @V_BRANDPACK_NAME = (SELECT BRANDPACK_NAME FROM BRND_BRANDPACK WHERE BRANDPACK_ID = @V_BRANDPACK_ID); 
SET @V_OA_DATE = (SELECT OA_DATE FROM ORDR_ORDER_ACCEPTANCE WHERE OA_ID = @V_OA_ID);
BEGIN
	SELECT OORM.OA_RM_ID,OOB.OA_ID AS OA_REF_NO,BRANDPACK_NAME = @V_BRANDPACK_NAME,
        OOB.OA_BRANDPACK_ID,OORM.QTY,OORM.LEFT_QTY,OORM.RELEASE_QTY,OORM.AGREE_DISC_HIST_ID,
	OORM.BRND_B_S_ID,OORM.ACHIEVEMENT_BRANDPACK_ID,OORM.MRKT_DISC_HIST_ID,OORM.MRKT_M_S_ID,OORM.PROJ_DISC_HIST_ID,
        OORM.FLAG,CONVERT(BIT,(CASE WHEN (OORM.FKCodeAdjust IS NOT NULL) THEN 1 ELSE 0 END))AS IsAdjustment, OORM.CREATE_DATE
	FROM ORDR_OA_REMAINDING OORM  INNER JOIN ORDR_OA_BRANDPACK OOB ON OORM.OA_BRANDPACK_ID = OOB.OA_BRANDPACK_ID
        WHERE OOB.OA_BRANDPACK_ID = ANY(SELECT OA_BRANDPACK_ID FROM ORDR_OA_BRANDPACK WHERE PO_BRANDPACK_ID 
	= ANY(SELECT PO_BRANDPACK_ID FROM ORDR_PO_BRANDPACK WHERE BRANDPACK_ID = @V_BRANDPACK_ID AND PO_REF_NO = ANY(SELECT
	PO_REF_NO FROM ORDR_PURCHASE_ORDER WHERE DISTRIBUTOR_ID = @V_DISTRIBUTOR_ID)))
	AND OOB.OA_ID = ANY(SELECT OA_ID FROM ORDR_ORDER_ACCEPTANCE WHERE OA_DATE <= @V_OA_DATE
        AND YEAR(OA_DATE) >= YEAR(GETDATE()) -1) AND OORM.LEFT_QTY > 0 
		
END',N'@V_DISTRIBUTOR_ID VARCHAR(10),@V_BRANDPACK_ID VARCHAR(14),@V_OA_ID VARCHAR(32)',
@V_DISTRIBUTOR_ID = @DISTRIBUTOR_ID,@V_BRANDPACK_ID = @BRANDPACK_ID,@V_OA_ID = @OA_ID;
GO

--exec Usp_Select_OA_Remainding_Detail @DISTRIBUTOR_ID = 'PAN115000', @BRANDPACK_ID = '00601001LD', @OA_ID = 'pan-5928'
--EXEC Usp_Select_OA_Remainding_Detail
--@DISTRIBUTOR_ID = 'SAN008IDR',
--@BRANDPACK_ID = '00010400MD'

-------------------------------------------------------------------------------
--PROCEDURE UNTUK MENGINSERT KE OA_REMAINDING
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Insert_OA_Remainding' AND TYPE = 'P')
DROP PROCEDURE Usp_Insert_OA_Remainding
GO
CREATE PROCEDURE Usp_Insert_OA_Remainding

@OA_BRANDPACK_ID VARCHAR(75),
@AGREE_DISC_HIST_ID VARCHAR(115),
@BRND_B_S_ID VARCHAR(60),
@ACHIEVEMENT_BRANDPACK_ID VARCHAR(70),
@MRKT_DISC_HIST_ID VARCHAR(115),
@MRKT_M_S_ID VARCHAR(60),
@PROJ_DISC_HIST_ID VARCHAR(66),
@FLAG VARCHAR(5),
@QTY DECIMAL(18,3),
@RELEASE_QTY DECIMAL(18,3),
@LEFT_QTY DECIMAL(18,3),
@CREATE_BY VARCHAR(50)
AS
SET NOCOUNT ON;
INSERT INTO ORDR_OA_REMAINDING(OA_BRANDPACK_ID,AGREE_DISC_HIST_ID,BRND_B_S_ID,ACHIEVEMENT_BRANDPACK_ID,MRKT_DISC_HIST_ID,
MRKT_M_S_ID,PROJ_DISC_HIST_ID,FLAG,QTY,RELEASE_QTY,LEFT_QTY,CREATE_BY,CREATE_DATE)
VALUES(@OA_BRANDPACK_ID,@AGREE_DISC_HIST_ID,@BRND_B_S_ID,@ACHIEVEMENT_BRANDPACK_ID,@MRKT_DISC_HIST_ID,@MRKT_M_S_ID,
@PROJ_DISC_HIST_ID,@FLAG,@QTY,@RELEASE_QTY,@LEFT_QTY,@CREATE_BY,GETDATE())
GO
------------------------------------------------------------------------------
--PROCEDURE UNTUK MENGUPDATE ORDR_OA_REMAINDING
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_UPDATE_ORDR_OA_REMAINDING' AND TYPE = 'P')
DROP PROCEDURE Usp_UPDATE_ORDR_OA_REMAINDING
GO
CREATE PROCEDURE Usp_UPDATE_ORDR_OA_REMAINDING
@OA_RM_ID VARCHAR(150),
@QTY VARCHAR(13), 
@MODIFY_BY VARCHAR(50),
@ISRELEASE BIT
AS
IF (@ISRELEASE = 1)
  BEGIN
	UPDATE ORDR_OA_REMAINDING SET RELEASE_QTY = (CAST((SELECT RELEASE_QTY FROM ORDR_OA_REMAINDING
	WHERE OA_RM_ID = @OA_RM_ID)AS FLOAT) + CAST((@QTY)AS FLOAT)),LEFT_QTY = (CAST((SELECT LEFT_QTY FROM ORDR_OA_REMAINDING
	WHERE OA_RM_ID = @OA_RM_ID)AS FLOAT) - CAST((@QTY) AS FLOAT)),MODIFY_BY = @MODIFY_BY,MODIFY_DATE = GETDATE()
	WHERE OA_RM_ID = @OA_RM_ID
  END
ELSE
  BEGIN
	UPDATE ORDR_OA_REMAINDING SET RELEASE_QTY = (CAST((SELECT RELEASE_QTY FROM ORDR_OA_REMAINDING
	WHERE OA_RM_ID = @OA_RM_ID)AS FLOAT) - CAST((@QTY)AS FLOAT)),LEFT_QTY = (CAST((SELECT LEFT_QTY FROM ORDR_OA_REMAINDING
	WHERE OA_RM_ID = @OA_RM_ID)AS FLOAT) + CAST((@QTY) AS FLOAT)),MODIFY_BY = @MODIFY_BY,MODIFY_DATE = GETDATE()
	WHERE OA_RM_ID = @OA_RM_ID
  END
GO
---------------------------------------------------------------------------------------------
--PROCEDURE UNTUK MENGECEK KEBERADAAN OA_RM_ID DI TABLE OA_BRANDPACK_DISC
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Check_OA_RM_ID_IN_OA_BRANDPACK_DISC' AND TYPE = 'P')
DROP PROCEDURE Usp_Check_OA_RM_ID_IN_OA_BRANDPACK_DISC
GO
CREATE PROCEDURE Usp_Check_OA_RM_ID_IN_OA_BRANDPACK_DISC
@OA_BRANDPACK_ID VARCHAR(70),
@OA_RM_ID VARCHAR(150)
AS
SELECT OA_RM_ID FROM ORDR_OA_BRANDPACK_DISC WHERE OA_RM_ID = @OA_RM_ID
AND OA_BRANDPACK_ID = @OA_BRANDPACK_ID 
 GO


------------------------------------------------------------------------- 
--PROCEDURE UNTUK MEMVIEW REMAINDING_LEFT AGREEMENT QTY DI TABLE DISCOUNT YANG DI PILIH

IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Select_REMAINDING_AGREEMENT_DISCOUNT' AND TYPE = 'P')
DROP PROCEDURE Usp_Select_REMAINDING_AGREEMENT_DISCOUNT
GO
CREATE PROCEDURE Usp_Select_REMAINDING_AGREEMENT_DISCOUNT
@BRANDPACK_ID VARCHAR(14),
@DISTRIBUTOR_ID VARCHAR(10),
@FLAG VARCHAR(5),
@OA_ID VARCHAR(32)
AS
IF (@FLAG = 'G')
   BEGIN
	SELECT ADH.AGREE_DISC_HIST_ID,OPB.PO_BRANDPACK_ID,BB.BRANDPACK_NAME,BB.BRANDPACK_ID,
	OPB.PO_REF_NO,OPO.PO_REF_DATE,ADH.AGREE_BRANDPACK_ID,ADH.OA_BRANDPACK_ID,ADH.AGREE_OA_QTY,ADH.AGREE_OA_DISC_PCT,
	ADH.AGREE_DISC_QTY,ADH.AGREE_RELEASE_QTY,ADH.AGREE_LEFT_QTY,ADH.GQSY_FLAG FROM AGREE_DISC_HISTORY ADH INNER JOIN
	ORDR_OA_BRANDPACK OOA ON ADH.OA_BRANDPACK_ID = OOA.OA_BRANDPACK_ID INNER JOIN ORDR_PO_BRANDPACK OPB ON OOA.PO_BRANDPACK_ID
	= OPB.PO_BRANDPACK_ID INNER JOIN ORDR_PURCHASE_ORDER OPO ON OPB.PO_REF_NO = OPO.PO_REF_NO INNER JOIN ORDR_ORDER_ACCEPTANCE
	OOC ON OOA.OA_ID = OOC.OA_ID AND OPO.PO_REF_NO = OOC.PO_REF_NO INNER JOIN AGREE_BRANDPACK_INCLUDE ABI ON ABI.AGREE_BRANDPACK_ID
	= ADH.AGREE_BRANDPACK_ID INNER JOIN BRND_BRANDPACK BB ON ABI.BRANDPACK_ID = BB.BRANDPACK_ID AND OPB.BRANDPACK_ID = BB.BRANDPACK_ID
	WHERE OPB.BRANDPACK_ID = @BRANDPACK_ID AND OPO.DISTRIBUTOR_ID = @DISTRIBUTOR_ID AND ADH.GQSY_FLAG = 'G'
	AND OOC.OA_DATE <= CAST((SELECT OA_DATE FROM ORDR_ORDER_ACCEPTANCE WHERE OA_ID = @OA_ID)AS DATETIME)
	AND ADH.AGREE_LEFT_QTY > 0 AND YEAR(OOC.OA_DATE) >= (SELECT YEAR(OA_DATE) FROM ORDR_ORDER_ACCEPTANCE WHERE OA_ID = @OA_ID) -1
		
   END
ELSE
   BEGIN
	SELECT AGREE_AGREEMENT.AGREEMENT_NO,BRND_BRANDPACK_SAVING.BRND_B_S_ID,BRND_BRANDPACK_SAVING.AGREE_BRANDPACK_ID,
	BRND_BRANDPACK_SAVING.TOTAL_PO_QTY,BRND_BRANDPACK_SAVING.TOTAL_PO_AMOUNT,BRND_BRANDPACK_SAVING.AGREE_DISC_PCT,
	BRND_BRANDPACK_SAVING.DISC_QTY,BRND_BRANDPACK_SAVING.DISC_AMOUNT,BRND_BRANDPACK_SAVING.RELEASE_QTY,
	BRND_BRANDPACK_SAVING.RELEASE_AMOUNT,BRND_BRANDPACK_SAVING.LEFT_QTY,BRND_BRANDPACK_SAVING.LEFT_AMOUNT,BRND_BRANDPACK_SAVING.QSY_FLAG
	FROM AGREE_AGREEMENT,AGREE_BRANDPACK_INCLUDE,BRND_BRANDPACK_SAVING,DISTRIBUTOR_AGREEMENT
	WHERE DISTRIBUTOR_AGREEMENT.AGREEMENT_NO = AGREE_AGREEMENT.AGREEMENT_NO AND DISTRIBUTOR_AGREEMENT.DISTRIBUTOR_ID = @DISTRIBUTOR_ID AND AGREE_BRANDPACK_INCLUDE.AGREEMENT_NO = 
	AGREE_AGREEMENT.AGREEMENT_NO AND BRND_BRANDPACK_SAVING.AGREE_BRANDPACK_ID = 
	AGREE_BRANDPACK_INCLUDE.AGREE_BRANDPACK_ID AND AGREE_BRANDPACK_INCLUDE.BRANDPACK_ID = @BRANDPACK_ID
	AND BRND_BRANDPACK_SAVING.DISTRIBUTOR_ID = @DISTRIBUTOR_ID
	AND BRND_BRANDPACK_SAVING.QSY_FLAG LIKE @FLAG + '%' AND BRND_BRANDPACK_SAVING.LEFT_QTY > 0
	AND BRND_BRANDPACK_SAVING.RELEASE_QTY > 0 AND YEAR(AGREE_AGREEMENT.END_DATE) >= YEAR(GETDATE()) -1 
	
   END
GO
--Usp_Select_REMAINDING_AGREEMENT_DISCOUNT
--@BRANDPACK_ID = '00010400MD',
--@DISTRIBUTOR_ID = 'AGR011000',
--@FLAG = 'Q1'
--------------------------------------------------------------------------------------

--PROCEDURE UNTUK MENGENABLEDKAN RADIO BUTTON BUAT AGREEMENT  DI REMAINDING LEFT,ADA / TIDAK ADANYA REMAINDING LEFT BERDASARKAN OA_BRANDPACK_ID
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Check_Remainding_Qty_Agreement_Discount' AND TYPE = 'P')
DROP PROCEDURE Usp_Check_Remainding_Qty_Agreement_Discount
GO
CREATE PROCEDURE Usp_Check_Remainding_Qty_Agreement_Discount
@DISTRIBUTOR_ID VARCHAR(10),
@BRANDPACK_ID VARCHAR(14),
@FLAG VARCHAR(5),
@OA_ID VARCHAR(32)
AS
IF (@FLAG = 'G')
    BEGIN
	SELECT COUNT(ADH.AGREE_LEFT_QTY) FROM AGREE_DISC_HISTORY ADH INNER JOIN ORDR_OA_BRANDPACK OOB 
	ON ADH.OA_BRANDPACK_ID = OOB.OA_BRANDPACK_ID INNER JOIN ORDR_PO_BRANDPACK OPB ON OOB.PO_BRANDPACK_ID
	= OPB.PO_BRANDPACK_ID INNER JOIN ORDR_PURCHASE_ORDER OPO ON OPB.PO_REF_NO = OPO.PO_REF_NO
	INNER JOIN ORDR_ORDER_ACCEPTANCE OOA ON OOA.PO_REF_NO = OPO.PO_REF_NO AND OOB.OA_ID = OOA.OA_ID
	WHERE OPB.BRANDPACK_ID = @BRANDPACK_ID AND OPO.DISTRIBUTOR_ID = @DISTRIBUTOR_ID
	AND ADH.AGREE_LEFT_QTY > 0
	AND OOA.OA_DATE <= CAST((SELECT OA_DATE FROM ORDR_ORDER_ACCEPTANCE WHERE OA_ID = @OA_ID) AS DATETIME)
	AND YEAR(OOA.OA_DATE) >= YEAR(GETDATE())-1
	AND ADH.AGREE_RELEASE_QTY > 0 AND ADH.GQSY_FLAG = 'G'
    END
ELSE
    BEGIN
	SELECT COUNT(BBS.LEFT_QTY) FROM BRND_BRANDPACK_SAVING BBS INNER JOIN AGREE_BRANDPACK_INCLUDE ABI
	ON ABI.AGREE_BRANDPACK_ID = BBS.AGREE_BRANDPACK_ID INNER JOIN AGREE_AGREEMENT AA
	ON ABI.AGREEMENT_NO =AA.AGREEMENT_NO INNER JOIN DISTRIBUTOR_AGREEMENT DA 
	ON AA.AGREEMENT_NO = DA.AGREEMENT_NO WHERE DA.DISTRIBUTOR_ID = @DISTRIBUTOR_ID
	AND ABI.BRANDPACK_ID = @BRANDPACK_ID AND BBS.QSY_FLAG LIKE @FLAG + '%'
	AND BBS.LEFT_QTY > 0 AND BBS.RELEASE_QTY > 0 AND BBS.DISTRIBUTOR_ID = @DISTRIBUTOR_ID
	AND YEAR(AA.END_DATE) >= (YEAR(GETDATE()) -1)
    END
 GO
-------------------------------------------------------------------------------------
--PROCEDURE UNTUK MENNGENABLEDKAN(MENGECEK) ADA / TIDAKNYA REMAINDING QTY DARI SALES
--BERDASARKAN OA_BRANDPACK_ID

IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Check_Remainding_Qty_Sales_Discount' AND TYPE  ='P')
DROP PROCEDURE Usp_Check_Remainding_Qty_Sales_Discount
GO
CREATE PROCEDURE Usp_Check_Remainding_Qty_Sales_Discount
@BRANDPACK_ID VARCHAR(14),
@DISTRIBUTOR_ID VARCHAR(10),
@FLAG VARCHAR(5),
@OA_ID VARCHAR(32)
AS
IF (@FLAG = 'MG') OR (@FLAG = 'KP') OR (@FLAG = 'DK') OR (@FLAG = 'CP') OR (@FLAG = 'CR')
   BEGIN
	SELECT COUNT(MDH.MRKT_LEFT_QTY) FROM MRKT_DISC_HISTORY MDH INNER JOIN ORDR_OA_BRANDPACK OOB
	ON OOB.OA_BRANDPACK_ID = MDH.OA_BRANDPACK_ID INNER JOIN ORDR_PO_BRANDPACK OPB ON OPB.PO_BRANDPACK_ID
	= OOB.PO_BRANDPACK_ID INNER JOIN ORDR_PURCHASE_ORDER OPO ON OPB.PO_REF_NO = OPO.PO_REF_NO
	INNER JOIN MRKT_BRANDPACK_DISTRIBUTOR MBD ON OPO.DISTRIBUTOR_ID = MBD.DISTRIBUTOR_ID
	AND MBD.PROG_BRANDPACK_DIST_ID = MDH.PROG_BRANDPACK_DIST_ID
	INNER JOIN ORDR_ORDER_ACCEPTANCE OOA ON OOA.PO_REF_NO = OPO.PO_REF_NO AND OOB.OA_ID = OOA.OA_ID
	WHERE OPO.DISTRIBUTOR_ID = @DISTRIBUTOR_ID AND OPB.BRANDPACK_ID = @BRANDPACK_ID
	AND MDH.SGT_FLAG = @FLAG AND YEAR(OOA.OA_DATE) >= (YEAR(GETDATE()) -1)
	AND OOA.OA_DATE <= CAST((SELECT OA_DATE FROM ORDR_ORDER_ACCEPTANCE WHERE OA_ID = @OA_ID)AS DATETIME)
	AND MDH.MRKT_LEFT_QTY > 0 AND MDH.MRKT_RELEASE_QTY > 0
	--AND 
	--((MDH.MRKT_LEFT_QTY > 0 AND MDH.MRKT_RELEASE_QTY > 0) OR (MDH.MRKT_LEFT_QTY <
	--(SELECT DEVIDED_QUANTITY FROM BRND_BRANDPACK WHERE BRANDPACK_ID = @BRANDPACK_ID)))
   END
ELSE IF (@FLAG = 'MS')
   BEGIN
	SELECT COUNT(MMS.MRKT_LEFT_QTY) FROM MRKT_MARKETING_SAVING MMS INNER JOIN MRKT_BRANDPACK_DISTRIBUTOR MBD
	ON MMS.PROG_BRANDPACK_DIST_ID = MBD.PROG_BRANDPACK_DIST_ID INNER JOIN MRKT_BRANDPACK MB ON MBD.PROG_BRANDPACK_ID
	= MB.PROG_BRANDPACK_ID 
	WHERE MBD.DISTRIBUTOR_ID = @DISTRIBUTOR_ID AND MB.BRANDPACK_ID = @BRANDPACK_ID
	AND YEAR(MBD.END_DATE) >= (YEAR(GETDATE()) -1) AND MMS.MRKT_LEFT_QTY > 0
	AND MMS.MRKT_RELEASE_QTY > 0  AND MMS.ST_FLAG = 'MS'
   END
ELSE IF(@FLAG = 'MT')
	SELECT COUNT(MMS.MRKT_LEFT_QTY) FROM MRKT_MARKETING_SAVING MMS INNER JOIN MRKT_BRANDPACK_DISTRIBUTOR MBD
	ON MMS.PROG_BRANDPACK_DIST_ID = MBD.PROG_BRANDPACK_DIST_ID INNER JOIN MRKT_BRANDPACK MB ON MBD.PROG_BRANDPACK_ID
	= MB.PROG_BRANDPACK_ID 
	WHERE MBD.DISTRIBUTOR_ID = @DISTRIBUTOR_ID AND MB.BRANDPACK_ID = @BRANDPACK_ID
	AND YEAR(MBD.END_DATE) >= (YEAR(GETDATE()) -1) AND MMS.MRKT_LEFT_QTY > 0
	AND MMS.MRKT_RELEASE_QTY > 0  AND MMS.ST_FLAG = 'MT'
GO

-------------------------------------------------------------------------------------------
--PROCEDURE UNTUK MEMVIEW REMAINDING SALES PROGRAM
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Select_REMAINDING_SALES_PROGRAM' AND TYPE = 'P')
DROP PROCEDURE Usp_Select_REMAINDING_SALES_PROGRAM
GO
CREATE PROCEDURE Usp_Select_REMAINDING_SALES_PROGRAM
@BRANDPACK_ID VARCHAR(14),
@DISTRIBUTOR_ID VARCHAR(14),
@FLAG VARCHAR(5),
@OA_ID VARCHAR(32)
AS
IF (@FLAG = 'MG') OR (@FLAG = 'KP') OR (@FLAG = 'DK') OR (@FLAG = 'CP') OR (@FLAG = 'CR')
   BEGIN

	SELECT MDH.MRKT_DISC_HIST_ID,OPB.BRANDPACK_ID,BB.BRANDPACK_NAME,OPB.PO_REF_NO,OPO.PO_REF_DATE,
	MDH.OA_BRANDPACK_ID,MDH.PROG_BRANDPACK_DIST_ID,MDH.MRKT_OA_QTY,MBD.GIVEN_DISC_PCT AS MRKT_DISC_PCT,
	MDH.MRKT_DISC_QTY,MDH.MRKT_RELEASE_QTY,MDH.MRKT_LEFT_QTY,MDH.SGT_FLAG
	FROM MRKT_DISC_HISTORY MDH INNER JOIN MRKT_BRANDPACK_DISTRIBUTOR MBD ON MDH.PROG_BRANDPACK_DIST_ID
	= MBD.PROG_BRANDPACK_DIST_ID INNER JOIN ORDR_PURCHASE_ORDER OPO ON MBD.DISTRIBUTOR_ID = OPO.DISTRIBUTOR_ID
	INNER JOIN ORDR_PO_BRANDPACK OPB ON OPO.PO_REF_NO = OPB.PO_REF_NO INNER JOIN ORDR_OA_BRANDPACK OOA ON OPB.PO_BRANDPACK_ID
	= OOA.PO_BRANDPACK_ID AND OOA.OA_BRANDPACK_ID = MDH.OA_BRANDPACK_ID
	INNER JOIN BRND_BRANDPACK BB ON BB.BRANDPACK_ID = OPB.BRANDPACK_ID
	INNER JOIN ORDR_ORDER_ACCEPTANCE OOC ON OOA.OA_ID = OOC.OA_ID
	AND OOC.PO_REF_NO = OPO.PO_REF_NO
	WHERE OPB.BRANDPACK_ID = @BRANDPACK_ID AND OPO.DISTRIBUTOR_ID = @DISTRIBUTOR_ID
	AND MDH.SGT_FLAG = @FLAG AND OOC.OA_DATE <= CAST((SELECT OA_DATE FROM ORDR_ORDER_ACCEPTANCE
	WHERE OA_ID = @OA_ID)AS DATETIME) 
	AND MDH.MRKT_LEFT_QTY > 0 AND MDH.MRKT_RELEASE_QTY > 0
	--AND 
	--((MDH.MRKT_LEFT_QTY > 0 AND MDH.MRKT_RELEASE_QTY > 0) OR (MDH.MRKT_LEFT_QTY <
	--(SELECT DEVIDED_QUANTITY FROM BRND_BRANDPACK WHERE BRANDPACK_ID = @BRANDPACK_ID)))
	AND YEAR(OOC.OA_DATE) >= YEAR(GETDATE()) -1
	AND OOC.OA_DATE <= CAST((SELECT OA_DATE FROM ORDR_ORDER_ACCEPTANCE WHERE OA_ID = @OA_ID)AS DATETIME)
   END
ELSE
   BEGIN
	SELECT MRKT_MARKETING_PROGRAM.PROGRAM_ID,MRKT_MARKETING_PROGRAM.PROGRAM_NAME,BRND_BRANDPACK.BRANDPACK_NAME,MRKT_MARKETING_SAVING.MRKT_M_S_ID,
	MRKT_MARKETING_SAVING.TOTAL_REACHED_QTY,MRKT_MARKETING_SAVING.TOTAL_REACHED_AMOUNT,MRKT_MARKETING_SAVING.MRKT_DISC_PCT,MRKT_MARKETING_SAVING.MRKT_DISC_QTY,
	MRKT_MARKETING_SAVING.DISC_AMOUNT,MRKT_MARKETING_SAVING.MRKT_RELEASE_QTY,MRKT_MARKETING_SAVING.MRKT_RELEASE_AMOUNT,MRKT_MARKETING_SAVING.MRKT_LEFT_QTY,
	MRKT_MARKETING_SAVING.MRKT_LEFT_AMOUNT,MRKT_MARKETING_SAVING.ST_FLAG
	FROM MRKT_MARKETING_PROGRAM,MRKT_BRANDPACK,BRND_BRANDPACK,MRKT_BRANDPACK_DISTRIBUTOR,MRKT_MARKETING_SAVING
	WHERE MRKT_BRANDPACK.BRANDPACK_ID = @BRANDPACK_ID AND MRKT_BRANDPACK.PROGRAM_ID = MRKT_MARKETING_PROGRAM.PROGRAM_ID
	AND MRKT_BRANDPACK.BRANDPACK_ID = BRND_BRANDPACK.BRANDPACK_ID AND MRKT_BRANDPACK.PROG_BRANDPACK_ID = 
	MRKT_BRANDPACK_DISTRIBUTOR.PROG_BRANDPACK_ID AND MRKT_BRANDPACK_DISTRIBUTOR.DISTRIBUTOR_ID = @DISTRIBUTOR_ID
	AND MRKT_BRANDPACK_DISTRIBUTOR.PROG_BRANDPACK_DIST_ID = MRKT_MARKETING_SAVING.PROG_BRANDPACK_DIST_ID AND 
	MRKT_MARKETING_SAVING.MRKT_LEFT_QTY > 0 AND MRKT_MARKETING_SAVING.ST_FLAG LIKE @FLAG + '%'
	AND MRKT_MARKETING_SAVING.MRKT_RELEASE_QTY > 0 AND YEAR(MRKT_BRANDPACK_DISTRIBUTOR.END_DATE) >= YEAR(GETDATE()) -1
   END
GO
-------------------------------------------------------------------------------------
------PROCEDURE UNTUK MENGECEK REMAINIDNG PROJECT DISCOUNT
/*
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Check_Remainding_Qty_Project_Discount' AND TYPE = 'P')
DROP PROCEDURE Usp_Check_Remainding_Qty_Project_Discount
GO
CREATE PROCEDURE Usp_Check_Remainding_Qty_Project_Discount
@BRANDPACK_ID VARCHAR(14),
@DISTRIBUTOR_ID VARCHAR(10)
AS
SELECT COUNT(PDH.PROJ_LEFT_QTY) FROM PROJ_DISC_HISTORY PDH INNER JOIN PROJ_BRANDPACK PB
	ON PDH.PROJ_BRANDPACK_ID = PB.PROJ_BRANDPACK_ID INNER JOIN PROJ_PROJECT PP ON PB.PROJ_REF_NO = PP.PROJ_REF_NO
	WHERE PDH.PROJ_RELEASE_QTY > 0 AND PDH.PROJ_LEFT_QTY > 0 AND PP.DISTRIBUTOR_ID =@DISTRIBUTOR_ID
	AND PB.BRANDPACK_ID = @BRANDPACK_ID
GO
----------------------------------------------------------------------------------------------
 ---PROCEDURE UNTUK MENGECEK SUDAH / BELUM NYA AGREEMENT DI GENERATED

IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Check_Generated_Agreement' AND TYPE = 'P')
DROP PROCEDURE Usp_Check_Generated_Agreement
GO
CREATE PROCEDURE Usp_Check_Generated_Agreement
@DISTRIBUTOR_ID VARCHAR(10),
@BRANDPACK_ID VARCHAR(14),
@O_COUNTQTYQ1 INT OUTPUT,
@O_COUNTQTYQ2 INT OUTPUT,
@O_COUNTQTYQ3 INT OUTPUT,
@O_COUNTQTYQ4 INT OUTPUT,
@O_COUNTQTYS1 INT OUTPUT,
@O_COUNTQTYS2 INT OUTPUT,
@O_COUNTQTYY INT OUTPUT
AS
BEGIN

SET @O_COUNTQTYQ1 = (SELECT COUNT(BBS.LEFT_QTY) FROM BRND_BRANDPACK_SAVING BBS INNER JOIN AGREE_BRANDPACK_INCLUDE ABI
	ON BBS.AGREE_BRANDPACK_ID = ABI.AGREE_BRANDPACK_ID INNER JOIN AGREE_AGREEMENT AA ON AA.AGREEMENT_NO
	= ABI.AGREEMENT_NO WHERE BBS.QSY_FLAG = 'Q1' AND BBS.DISTRIBUTOR_ID = @DISTRIBUTOR_ID
	  AND YEAR(AA.END_DATE) >= (YEAR(AA.END_DATE) - 1) AND BBS.LEFT_QTY > 0 AND ABI.BRANDPACK_ID = @BRANDPACK_ID)
SET @O_COUNTQTYQ2 = (SELECT COUNT(BBS.LEFT_QTY) FROM BRND_BRANDPACK_SAVING BBS INNER JOIN AGREE_BRANDPACK_INCLUDE ABI
	ON BBS.AGREE_BRANDPACK_ID = ABI.AGREE_BRANDPACK_ID INNER JOIN AGREE_AGREEMENT AA ON AA.AGREEMENT_NO
	= ABI.AGREEMENT_NO WHERE BBS.QSY_FLAG = 'Q2' AND BBS.DISTRIBUTOR_ID = @DISTRIBUTOR_ID
	  AND YEAR(AA.END_DATE) >= (YEAR(AA.END_DATE) - 1) AND BBS.LEFT_QTY > 0 AND ABI.BRANDPACK_ID = @BRANDPACK_ID)
SET @O_COUNTQTYQ3 = (SELECT COUNT(BBS.LEFT_QTY) FROM BRND_BRANDPACK_SAVING BBS INNER JOIN AGREE_BRANDPACK_INCLUDE ABI
	ON BBS.AGREE_BRANDPACK_ID = ABI.AGREE_BRANDPACK_ID INNER JOIN AGREE_AGREEMENT AA ON AA.AGREEMENT_NO
	= ABI.AGREEMENT_NO WHERE BBS.QSY_FLAG = 'Q3' AND BBS.DISTRIBUTOR_ID = @DISTRIBUTOR_ID
	  AND YEAR(AA.END_DATE) >= (YEAR(AA.END_DATE) - 1) AND BBS.LEFT_QTY > 0 AND ABI.BRANDPACK_ID = @BRANDPACK_ID)
SET @O_COUNTQTYQ4 = (SELECT COUNT(BBS.LEFT_QTY) FROM BRND_BRANDPACK_SAVING BBS INNER JOIN AGREE_BRANDPACK_INCLUDE ABI
	ON BBS.AGREE_BRANDPACK_ID = ABI.AGREE_BRANDPACK_ID INNER JOIN AGREE_AGREEMENT AA ON AA.AGREEMENT_NO
	= ABI.AGREEMENT_NO WHERE BBS.QSY_FLAG = 'Q4' AND BBS.DISTRIBUTOR_ID = @DISTRIBUTOR_ID
	  AND YEAR(AA.END_DATE) >= (YEAR(AA.END_DATE) - 1) AND BBS.LEFT_QTY > 0 AND ABI.BRANDPACK_ID = @BRANDPACK_ID)
SET @O_COUNTQTYS1 = (SELECT COUNT(BBS.LEFT_QTY) FROM BRND_BRANDPACK_SAVING BBS INNER JOIN AGREE_BRANDPACK_INCLUDE ABI
	ON BBS.AGREE_BRANDPACK_ID = ABI.AGREE_BRANDPACK_ID INNER JOIN AGREE_AGREEMENT AA ON AA.AGREEMENT_NO
	= ABI.AGREEMENT_NO WHERE BBS.QSY_FLAG = 'S1' AND BBS.DISTRIBUTOR_ID = @DISTRIBUTOR_ID
	  AND YEAR(AA.END_DATE) >= (YEAR(AA.END_DATE) - 1) AND BBS.LEFT_QTY > 0 AND ABI.BRANDPACK_ID = @BRANDPACK_ID)
SET @O_COUNTQTYS2 = (SELECT COUNT(BBS.LEFT_QTY) FROM BRND_BRANDPACK_SAVING BBS INNER JOIN AGREE_BRANDPACK_INCLUDE ABI
	ON BBS.AGREE_BRANDPACK_ID = ABI.AGREE_BRANDPACK_ID INNER JOIN AGREE_AGREEMENT AA ON AA.AGREEMENT_NO
	= ABI.AGREEMENT_NO WHERE BBS.QSY_FLAG = 'S2' AND BBS.DISTRIBUTOR_ID = @DISTRIBUTOR_ID
	  AND YEAR(AA.END_DATE) >= (YEAR(AA.END_DATE) - 1) AND BBS.LEFT_QTY > 0 AND ABI.BRANDPACK_ID = @BRANDPACK_ID )
SET @O_COUNTQTYY = (SELECT COUNT(BBS.LEFT_QTY) FROM BRND_BRANDPACK_SAVING BBS INNER JOIN AGREE_BRANDPACK_INCLUDE ABI
	ON BBS.AGREE_BRANDPACK_ID = ABI.AGREE_BRANDPACK_ID INNER JOIN AGREE_AGREEMENT AA ON AA.AGREEMENT_NO
	= ABI.AGREEMENT_NO WHERE BBS.QSY_FLAG = 'Y' AND BBS.DISTRIBUTOR_ID = @DISTRIBUTOR_ID
	  AND YEAR(AA.END_DATE) >= (YEAR(AA.END_DATE) - 1) AND BBS.LEFT_QTY > 0 AND ABI.BRANDPACK_ID = @BRANDPACK_ID)
END
GO

exec Usp_Check_Generated_Agreement @DISTRIBUTOR_ID = 'BIN012000',@BRANDPACK_ID = '"0060200200MD',
@O_COUNTQTYQ1 =0,
@O_COUNTQTYQ2 =0,
@O_COUNTQTYQ3 =0,
@O_COUNTQTYQ4 =0,
@O_COUNTQTYS1 =0,
@O_COUNTQTYS2 =0,
@O_COUNTQTYY =0
SELECT * FROM BRND_BRANDPACK_SAVING BBS INNER JOIN AGREE_BRANDPACK_INCLUDE ABI
	ON BBS.AGREE_BRANDPACK_ID = ABI.AGREE_BRANDPACK_ID INNER JOIN AGREE_AGREEMENT AA ON AA.AGREEMENT_NO
	= ABI.AGREEMENT_NO WHERE BBS.QSY_FLAG = 'Q1' AND BBS.DISTRIBUTOR_ID = 'BIN012000'
	AND YEAR(AA.END_DATE) >= (YEAR(AA.END_DATE) - 1) AND BBS.LEFT_QTY > 0 AND ABI.BRANDPACK_ID = '0060200200MD'
*/ 
---------------------------------------------------------------------------------------------
--PROCEDURE UNTUK MEMVIEW SISA PROJECT DISCOUNT

IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Select_REMAINDING_PROJECT_DISCOUNT' AND TYPE = 'P')
DROP PROCEDURE Usp_Select_REMAINDING_PROJECT_DISCOUNT
GO
CREATE PROCEDURE Usp_Select_REMAINDING_PROJECT_DISCOUNT
@BRANDPACK_ID VARCHAR(14),
@DISTRIBUTOR_ID VARCHAR(14)
AS
SELECT PROJ_DISC_HISTORY.PROJ_DISC_HIST_ID,PROJ_BRANDPACK.BRANDPACK_ID,BRND_BRANDPACK.BRANDPACK_NAME,PROJ_BRANDPACK.PROJ_REF_NO,
PROJ_DISC_HISTORY.PROJ_BRANDPACK_ID,PROJ_DISC_HISTORY.TOTAL_PO_QTY,PROJ_DISC_HISTORY.PROJ_DISC_PCT,PROJ_DISC_HISTORY.PROJ_DISC_QTY,PROJ_DISC_HISTORY.PROJ_RELEASE_QTY,
PROJ_DISC_HISTORY.PROJ_LEFT_QTY
FROM PROJ_DISC_HISTORY,BRND_BRANDPACK,PROJ_PROJECT,PROJ_BRANDPACK
WHERE PROJ_PROJECT.DISTRIBUTOR_ID = @DISTRIBUTOR_ID AND PROJ_BRANDPACK.PROJ_REF_NO = PROJ_PROJECT.PROJ_REF_NO
AND PROJ_DISC_HISTORY.PROJ_BRANDPACK_ID = PROJ_BRANDPACK.PROJ_BRANDPACK_ID AND PROJ_BRANDPACK.BRANDPACK_ID = @BRANDPACK_ID AND PROJ_BRANDPACK.BRANDPACK_ID = BRND_BRANDPACK.BRANDPACK_ID AND 
PROJ_DISC_HISTORY.PROJ_LEFT_QTY > 0 AND PROJ_RELEASE_QTY > 0
GO
-----------------------------------------------------------------------------------
/*
--PROCEDURE UNTUK MEMVIEW SELURUH LEFT _QTY BERDASARKAN OTHER DISCOUNT
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Select_REMAINDING_OTHER_DISCOUNT' AND TYPE = 'P')
DROP PROCEDURE Usp_Select_REMAINDING_OTHER_DISCOUNT
GO
CREATE PROCEDURE Usp_Select_REMAINDING_OTHER_DISCOUNT
@DISTRIBUTOR_ID VARCHAR(10),
@BRANDPACK_ID VARCHAR(14)
AS
DECLARE @DEVIDE_FACTOR FLOAT,@V_BRANDPACK_NAME VARCHAR(100),@V_UNIT VARCHAR(15)
SET @DEVIDE_FACTOR = (SELECT DEVIDE_FACTOR FROM BRND_PACK WHERE PACK_ID = (SELECT PACK_ID FROM BRND_BRANDPACK WHERE BRANDPACK_ID = @BRANDPACK_ID))
SET @V_BRANDPACK_NAME = (SELECT BRANDPACK_NAME FROM BRND_BRANDPACK WHERE BRANDPACK_ID = @BRANDPACK_ID) 
SET @V_UNIT = (SELECT UNIT FROM BRND_BRANDPACK WHERE BRANDPACK_ID = @BRANDPACK_ID) 
BEGIN
	SELECT ORDR_OA_REMAINDING.OA_RM_ID,ORDR_OA_BRANDPACK.OA_ID AS OA_REF_NO,BRANDPACK_NAME = @V_BRANDPACK_NAME,
        ORDR_OA_BRANDPACK.OA_BRANDPACK_ID,ORDR_OA_REMAINDING.QTY,CAST((CAST((ORDR_OA_REMAINDING.QTY) AS FLOAT) * @DEVIDE_FACTOR) AS VARCHAR(20)) + ' ' + @V_UNIT AS RESULT_QTY,
	ORDR_OA_REMAINDING.LEFT_QTY,CAST((CAST((ORDR_OA_REMAINDING.LEFT_QTY) AS FLOAT) * @DEVIDE_FACTOR) AS VARCHAR(20)) + ' ' + @V_UNIT AS RESULT_LEFT,RELEASE_QTY,
	CAST((CAST((ORDR_OA_REMAINDING.RELEASE_QTY) AS FLOAT) * @DEVIDE_FACTOR) AS VARCHAR(20)) + ' ' + @V_UNIT AS RESULT_RELEASE,
	UNIT = @V_UNIT,ORDR_OA_REMAINDING.AGREE_DISC_HIST_ID, 
	ORDR_OA_REMAINDING.BRND_B_S_ID,ORDR_OA_REMAINDING.MRKT_DISC_HIST_ID,ORDR_OA_REMAINDING.MRKT_M_S_ID,
	ORDR_OA_REMAINDING.PROJ_DISC_HIST_ID,ORDR_OA_REMAINDING.FLAG
	FROM ORDR_OA_BRANDPACK,ORDR_OA_REMAINDING WHERE ORDR_OA_BRANDPACK.OA_BRANDPACK_ID IN(SELECT OA_BRANDPACK_ID FROM ORDR_OA_BRANDPACK
	WHERE PO_BRANDPACK_ID IN(SELECT PO_BRANDPACK_ID FROM ORDR_PO_BRANDPACK WHERE PO_REF_NO IN(SELECT
	PO_REF_NO FROM ORDR_PURCHASE_ORDER WHERE DISTRIBUTOR_ID =@DISTRIBUTOR_ID AND 
	YEAR(PO_REF_DATE) >= (YEAR(GETDATE())-1))))
	AND ORDR_OA_REMAINDING.LEFT_QTY > 0 AND ORDR_OA_REMAINDING.FLAG = 'O' 
	AND ORDR_OA_BRANDPACK.OA_BRANDPACK_ID = ORDR_OA_REMAINDING.OA_BRANDPACK_ID
END
GO

--EXEC Usp_Select_REMAINDING_OTHER_DISCOUNT
--@DISTRIBUTOR_ID = 'AGR011000',
--@BRANDPACK_ID = '006020020LD'
------------------------------------------------------------------------------------

--PRPCEDURE UNTUK MEMVIEW SELURUH LEFT_QTY BERDASARKAN OA_LEFT_QTY
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Select_REMAINDING_OA_LEFT_QTY' AND TYPE = 'P')
DROP PROCEDURE Usp_Select_REMAINDING_OA_LEFT_QTY
GO
CREATE PROCEDURE Usp_Select_REMAINDING_OA_LEFT_QTY
@DISTRIBUTOR_ID VARCHAR(10),
@BRANDPACK_ID VARCHAR(14)
AS
DECLARE @DEVIDE_FACTOR FLOAT,@V_BRANDPACK_NAME VARCHAR(100),@V_UNIT VARCHAR(15)
SET @DEVIDE_FACTOR = (SELECT DEVIDE_FACTOR FROM BRND_PACK WHERE PACK_ID = (SELECT PACK_ID FROM BRND_BRANDPACK WHERE BRANDPACK_ID = @BRANDPACK_ID))
SET @V_BRANDPACK_NAME = (SELECT BRANDPACK_NAME FROM BRND_BRANDPACK WHERE BRANDPACK_ID = @BRANDPACK_ID) 
SET @V_UNIT = (SELECT UNIT FROM BRND_BRANDPACK WHERE BRANDPACK_ID = @BRANDPACK_ID) 
BEGIN
	SELECT ORDR_OA_REMAINDING.OA_RM_ID,ORDR_OA_BRANDPACK.OA_ID AS OA_REF_NO,BRANDPACK_NAME = @V_BRANDPACK_NAME,
        ORDR_OA_BRANDPACK.OA_BRANDPACK_ID,ORDR_OA_REMAINDING.QTY,CAST((CAST((ORDR_OA_REMAINDING.QTY) AS FLOAT) * @DEVIDE_FACTOR) AS VARCHAR(20)) + ' ' + @V_UNIT AS RESULT_QTY,
	ORDR_OA_REMAINDING.LEFT_QTY,CAST((CAST((ORDR_OA_REMAINDING.LEFT_QTY) AS FLOAT) * @DEVIDE_FACTOR) AS VARCHAR(20)) + ' ' + @V_UNIT AS RESULT_LEFT,RELEASE_QTY,
	CAST((CAST((ORDR_OA_REMAINDING.RELEASE_QTY) AS FLOAT) * @DEVIDE_FACTOR) AS VARCHAR(20)) + ' ' + @V_UNIT AS RESULT_RELEASE, 
	UNIT = @V_UNIT,ORDR_OA_REMAINDING.AGREE_DISC_HIST_ID,
	ORDR_OA_REMAINDING.BRND_B_S_ID,ORDR_OA_REMAINDING.MRKT_DISC_HIST_ID,ORDR_OA_REMAINDING.MRKT_M_S_ID,
	ORDR_OA_REMAINDING.PROJ_DISC_HIST_ID,ORDR_OA_REMAINDING.FLAG
	FROM ORDR_OA_BRANDPACK,ORDR_OA_REMAINDING WHERE ORDR_OA_BRANDPACK.OA_BRANDPACK_ID IN(SELECT OA_BRANDPACK_ID FROM ORDR_OA_BRANDPACK
	WHERE PO_BRANDPACK_ID IN(SELECT PO_BRANDPACK_ID FROM ORDR_PO_BRANDPACK WHERE PO_REF_NO IN(SELECT
	PO_REF_NO FROM ORDR_PURCHASE_ORDER WHERE DISTRIBUTOR_ID =@DISTRIBUTOR_ID AND 
	YEAR(PO_REF_DATE) >= (YEAR(GETDATE())-1))))
	AND ORDR_OA_REMAINDING.LEFT_QTY > 0 AND ORDR_OA_REMAINDING.FLAG = 'RMOA' 
	AND ORDR_OA_BRANDPACK.OA_BRANDPACK_ID = ORDR_OA_REMAINDING.OA_BRANDPACK_ID
END
GO

--EXEC Usp_Select_REMAINDING_OA_LEFT_QTY
--@DISTRIBUTOR_ID = 'SAN008IDR',
--@BRANDPACK_ID = '00010400MD'

--PO_SAN-1628PO_SAN00010400MD

--SELECT * FROM BRND_BRANDPACK WHERE BRANDPACK_ID = '00010400MD'
*/
------------------------------------------------------------------------------------
IF EXISTS(SELECT NAME FROM sys.SYSOBJECTS WHERE NAME = 'Usp_Get_Sum_QTY_OA_BRANDPACK' AND TYPE = 'P')
DROP PROCEDURE Usp_Get_Sum_QTY_OA_BRANDPACK
GO
CREATE PROCEDURE Usp_Get_Sum_QTY_OA_BRANDPACK
@OA_BRANDPACK_ID VARCHAR(75)
AS
SET NOCOUNT ON;
DECLARE @V_TOTAL_DISC DECIMAL(16,3),@V_TOTAL_ADJ DECIMAL(16,3);
SET @V_TOTAL_DISC = (SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC WHERE OA_BRANDPACK_ID = @OA_BRANDPACK_ID);
SET @V_TOTAL_ADJ = (SELECT ISNULL(SUM(AT.ADJ_DISC_QTY),0) FROM ADJUSTMENT_TRANS AT INNER JOIN ORDR_OA_BRANDPACK_DISC OOBD ON OOBD.OA_BRANDPACK_DISC_ID = AT.OA_BRANDPACK_DISC_ID
					WHERE OOBD.OA_BRANDPACK_ID = @OA_BRANDPACK_ID AND OOBD.GQSY_SGT_P_FLAG IN('Q1','Q2','Q3','Q4','S1','S2','Y')); 
 SELECT RESULT = (@V_TOTAL_DISC - @V_TOTAL_ADJ);
 GO
------------------------------------------------------------------------------------
/*
--PROCEDURE UNTUK MENGECEK ADA / TIDAKNYA PROGRAM BAGI DISTRBUTOR
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Check_Distributor_Sales_Program' AND TYPE = 'P')
DROP PROCEDURE Usp_Check_Distributor_Sales_Program
GO
CREATE PROCEDURE Usp_Check_Distributor_Sales_Program
@DISTRIBUTOR_ID VARCHAR(10),
@BRANDPACK_ID VARCHAR(14),
@PO_DATE VARCHAR(15),
@FLAG VARCHAR(2)
AS
IF (@FLAG = 'KP')
   BEGIN
	SELECT MRKT_BRANDPACK_DISTRIBUTOR.GIVEN_PKPP FROM MRKT_BRANDPACK_DISTRIBUTOR INNER JOIN MRKT_BRANDPACK
	ON MRKT_BRANDPACK_DISTRIBUTOR.PROG_BRANDPACK_ID = MRKT_BRANDPACK.PROG_BRANDPACK_ID
	WHERE MRKT_BRANDPACK_DISTRIBUTOR.DISTRIBUTOR_ID = @DISTRIBUTOR_ID AND MRKT_BRANDPACK.BRANDPACK_ID = @BRANDPACK_ID
	AND MRKT_BRANDPACK_DISTRIBUTOR.END_DATE >= @PO_DATE AND 
	MRKT_BRANDPACK_DISTRIBUTOR.START_DATE <= @PO_DATE AND MRKT_BRANDPACK_DISTRIBUTOR.ISPKPP = 1
   END 
ELSE IF (@FLAG = 'MG')
   BEGIN
	SELECT MRKT_BRANDPACK_DISTRIBUTOR.ISRPK,GIVEN_DISC_PCT FROM MRKT_BRANDPACK_DISTRIBUTOR INNER JOIN MRKT_BRANDPACK
        ON MRKT_BRANDPACK_DISTRIBUTOR.PROG_BRANDPACK_ID = MRKT_BRANDPACK.PROG_BRANDPACK_ID
        WHERE MRKT_BRANDPACK_DISTRIBUTOR.DISTRIBUTOR_ID = @DISTRIBUTOR_ID AND MRKT_BRANDPACK.BRANDPACK_ID = @BRANDPACK_ID 
        AND MRKT_BRANDPACK_DISTRIBUTOR.END_DATE >= @PO_DATE AND MRKT_BRANDPACK_DISTRIBUTOR.START_DATE <= @PO_DATE
	AND ISPKPP = 0 AND ISDK = 0 AND ISCPR = 0 AND ISCP = 0 AND ISHK = 0
   END
ELSE IF (@FLAG = 'DK')
   BEGIN
	SELECT MRKT_BRANDPACK_DISTRIBUTOR.GIVEN_PKPP FROM MRKT_BRANDPACK_DISTRIBUTOR INNER JOIN MRKT_BRANDPACK
	ON MRKT_BRANDPACK_DISTRIBUTOR.PROG_BRANDPACK_ID = MRKT_BRANDPACK.PROG_BRANDPACK_ID
	WHERE MRKT_BRANDPACK_DISTRIBUTOR.DISTRIBUTOR_ID = @DISTRIBUTOR_ID AND MRKT_BRANDPACK.BRANDPACK_ID = @BRANDPACK_ID
	AND MRKT_BRANDPACK_DISTRIBUTOR.END_DATE >= @PO_DATE AND 
	MRKT_BRANDPACK_DISTRIBUTOR.START_DATE <= @PO_DATE AND MRKT_BRANDPACK_DISTRIBUTOR.ISDK = 1
   END
ELSE IF(@FLAG = 'CP')
    BEGIN
	SELECT MRKT_BRANDPACK_DISTRIBUTOR.GIVEN_PKPP FROM MRKT_BRANDPACK_DISTRIBUTOR INNER JOIN MRKT_BRANDPACK
	ON MRKT_BRANDPACK_DISTRIBUTOR.PROG_BRANDPACK_ID = MRKT_BRANDPACK.PROG_BRANDPACK_ID
	WHERE MRKT_BRANDPACK_DISTRIBUTOR.DISTRIBUTOR_ID = @DISTRIBUTOR_ID AND MRKT_BRANDPACK.BRANDPACK_ID = @BRANDPACK_ID
	AND MRKT_BRANDPACK_DISTRIBUTOR.END_DATE >= @PO_DATE AND 
	MRKT_BRANDPACK_DISTRIBUTOR.START_DATE <= @PO_DATE AND MRKT_BRANDPACK_DISTRIBUTOR.ISCP = 1
    END
ELSE IF (@FLAG = 'CR')
    BEGIN
	SELECT MRKT_BRANDPACK_DISTRIBUTOR.GIVEN_CPR FROM MRKT_BRANDPACK_DISTRIBUTOR INNER JOIN MRKT_BRANDPACK
	ON MRKT_BRANDPACK_DISTRIBUTOR.PROG_BRANDPACK_ID = MRKT_BRANDPACK.PROG_BRANDPACK_ID
	WHERE MRKT_BRANDPACK_DISTRIBUTOR.DISTRIBUTOR_ID = @DISTRIBUTOR_ID AND MRKT_BRANDPACK.BRANDPACK_ID = @BRANDPACK_ID
	AND MRKT_BRANDPACK_DISTRIBUTOR.END_DATE >= @PO_DATE AND 
	MRKT_BRANDPACK_DISTRIBUTOR.START_DATE <= @PO_DATE AND MRKT_BRANDPACK_DISTRIBUTOR.ISCPR = 1
    END
GO
--SELECT * FROM MRKT_BRANDPACK_DISTRIBUTOR WHERE ISDK = 1
*/
--------------------------------------------------------------------------------------------

----------------PROCEDURE UNTUK MENGAMBIL DIVIDED_QTY DARI BRANDPACK--------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Get_Divided_Qty' AND TYPE = 'P' AND TYPE = 'P')
DROP PROCEDURE Usp_Get_Divided_Qty
GO
CREATE PROCEDURE Usp_Get_Divided_Qty
@BRANDPACK_ID VARCHAR(14)
AS
SELECT DEVIDED_QUANTITY FROM BRND_BRANDPACK WHERE BRANDPACK_ID = @BRANDPACK_ID
GO
----------------------------------------------------------------------------------
---PROCEDURE UNTUK MENGAMBIL DIVIDE_FACTOR DARI BRANDPACK
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Get_Divide_Factor' AND TYPE = 'P')
DROP PROCEDURE Usp_Get_Divide_Factor
GO
CREATE PROCEDURE Usp_Get_Divide_Factor
@BRANDPACK_ID VARCHAR(14)
AS
SELECT DEVIDE_FACTOR FROM BRND_PACK WHERE PACK_ID = (SELECT PACK_ID FROM BRND_BRANDPACK
WHERE BRANDPACK_ID  = @BRANDPACK_ID)
GO
--------------------------------------------------------------------------------------
----PROCEDURE UNTUK MENGAMBIL UNIT DARI BRANDPACK------------------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Get_Unit_Brandpack' AND TYPE = 'P')
DROP PROCEDURE Usp_Get_Unit_Brandpack
GO
CREATE PROCEDURE Usp_Get_Unit_Brandpack
@BRANDPACK_ID VARCHAR(14)
AS
SELECT UNIT FROM BRND_BRANDPACK WHERE BRANDPACK_ID = @BRANDPACK_ID
GO
-------------------------------------------------------------------------------
 
--SELECT * FROM ORDR_OA_BRANDPACK_DISC WHERE OA_BRANDPACK_ID = 'PO UD_AGRO-1626PO UD_AGRO0060200200MD'

--EXEC Usp_Get_Sum_QTY_OA_BRANDPACK @OA_BRANDPACK_ID = 'PO UD_AGRO-1626PO UD_AGRO0060200200MD'

--SELECT * FROM ORDR_OA_BRANDPACK WHERE OA_ID LIKE 'PO UD%'
--------------------------------------------------------------------------------
--400MSO
--SELECT * FROM BRND_PACK WHERE PACK_ID= '400MSO' LIKE 'STANDING POUNCH%'

select cast((select devided_quantity from brnd_brandpack where brandpack_id = '0060200200MD')as decimal(18,3))
BEGIN
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRANSACTION
   DECLARE @V_PACK_ID VARCHAR(10),@V_QUANTITY DECIMAL(18,3),@V_DEVIDE_FACTOR DECIMAL(18,3),@V_UNIT VARCHAR(15),@V_DEVIDED_QUANTITY FLOAT
   DECLARE Cursor_BrandPack CURSOR FOR
   SELECT PACK_ID,QUANTITY,DEVIDE_FACTOR,UNIT FROM BRND_PACK WHERE QUANTITY IS NOT NULL
   AND DEVIDE_FACTOR IS NOT NULL
   OPEN Cursor_BrandPack
   	FETCH NEXT FROM Cursor_BrandPack INTO @V_PACK_ID,@V_QUANTITY,@V_DEVIDE_FACTOR,
	@V_UNIT
	WHILE (@@FETCH_STATUS >= 0)
		BEGIN
			SET @V_DEVIDED_QUANTITY = CAST((@V_QUANTITY / @V_DEVIDE_FACTOR) AS FLOAT)
			PRINT '@V_QUANTITY = ' + CAST((@V_QUANTITY) AS VARCHAR(10))
			PRINT '@V_DEVIDE_FACTOR = ' + CAST((@V_DEVIDE_FACTOR) AS VARCHAR(10))
			PRINT '@V_DEVIDED_QUANTITY = ' + CAST((@V_DEVIDED_QUANTITY)AS VARCHAR(40))
			UPDATE BRND_BRANDPACK SET DEVIDED_QUANTITY = @V_DEVIDED_QUANTITY
			,UNIT = @V_UNIT WHERE PACK_ID = @V_PACK_ID
			IF (@@ERROR > 0)
				BEGIN
					ROLLBACK TRANSACTION
					CLOSE Cursor_BrandPack
					DEALLOCATE Cursor_BrandPack
					RETURN
				END
 			FETCH NEXT FROM Cursor_BrandPack INTO @V_PACK_ID,@V_QUANTITY,@V_DEVIDE_FACTOR,
			@V_UNIT
  		END
	COMMIT TRANSACTION	
	CLOSE Cursor_BrandPack
	DEALLOCATE Cursor_BrandPack
END
--DELETE FROM MRKT_BRANDPACK WHERE BRANDPACK_ID NOT IN(SELECT BRANDPACK_ID FROM BRND_BRANDPACK)
--DELETE FROM BRND_BRANDPACK WHERE PACK_ID NOT IN (SELECT PACK_ID FROM BRND_PACK)
--DELETE FROM AGREE_BRANDPACK_INCLUDE WHERE BRANDPACK_ID NOT IN(SELECT BRANDPACK_ID FROM BRND_BRANDPACK)
/*

select * FROM ORDR_ORDER_ACCEPTANCE WHERE OA_ID NOT IN(SELECT OA_ID FROM 
ORDR_OA_BRANDPACK)

SELECT * FROM ORDR_ORDER_ACCEPTANCE WHERE CREATE_DATE >= (GETDATE() -2)

2001

select devided_quantity from brnd_brandpack where brandpack_id = '00053500MD'



SELECT * FROM ORDR_OA_BRANDPACK WHERE OA_BRANDPACK_ID NOT IN(
SELECT OA_BRANDPACK_ID FROM ORDR_OA_BRANDPACK_DISC WHERE OA_BRANDPACK_ID LIKE '4346/PES-PANL/V/2009%')
AND OA_BRANDPACK_ID LIKE '4346/PES-PANL/V/2009%'

SELECT * FROM BRND_BRANDPACK WHERE PACK_ID = '0000D'

SELECT * FROM SPPB_HEADER WHERE PO_REF_NO = '09-00341/PKNN/OP'

SELECT * FROM SPPB_BRANDPACK WHERE SPPB_NO = '09.10-000075'

SELECT * FROM VIEW_SPPB_ALL WHERE PO_REF_NO = '09-00341/PKNN/OP'

EXEC Usp_Create_View_SPPB_Detail
@UNTIL_PO_DATE = '08/15/2009',
@FROM_PO_DATE = NULL,
@CATEGORY_DATE = 'ByPO'
*/
--IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Get_All_Remainding_By_Brand_ID' AND TYPE = 'P')
--DROP PROCEDURE Usp_Get_All_Remainding_By_Brand_ID
--GO
--CREATE PROCEDURE Usp_Get_All_Remainding_By_Brand_ID
--@BRANDPACK_ID VARCHAR(14),
--@DISTRIBUTOR_ID VARCHAR(10)
--AS
--DECLARE @V_BRAND_ID VARCHAR(7),@V_DEVIDED_QTY DECIMAL(10,3)
--SET @V_DEVIDED_QTY = (SELECT DEVIDED_QUANTITY FROM BRND_BRANDPACK
--WHERE BRANDPACK_ID = @BRANDPACK_ID)
--SET @V_BRAND_ID = (SELECT BRAND_ID FROM BRND_BRANDPACK WHERE BRANDPACK_ID = @BRANDPACK_ID)
--SELECT OPO.PO_REF_NO,OPO.PO_REF_DATE AS PO_DATE,OPB.BRANDPACK_ID,BB.BRANDPACK_NAME,OOR.OA_RM_ID,OOR.LEFT_QTY,
--OOR.OA_BRANDPACK_ID,OOR.AGREE_DISC_HIST_ID,OOR.BRND_B_S_ID,OOR.MRKT_DISC_HIST_ID,
--OOR.MRKT_M_S_ID,OOR.PROJ_DISC_HIST_ID,OOR.FLAG,OOR.ISRELOTHEROA,REMARK_RELEASED
--FROM BRND_BRANDPACK BB INNER JOIN ORDR_PO_BRANDPACK OPB ON BB.BRANDPACK_ID = OPB.BRANDPACK_ID
--INNER JOIN ORDR_PURCHASE_ORDER OPO ON OPO.PO_REF_NO = OPB.PO_REF_NO
--INNER JOIN ORDR_ORDER_ACCEPTANCE OOA ON OPO.PO_REF_NO = OOA.PO_REF_NO
--INNER JOIN ORDR_OA_BRANDPACK OOB ON OOA.OA_ID = OOB.OA_ID
--INNER JOIN ORDR_OA_REMAINDING OOR ON OOB.OA_BRANDPACK_ID = OOR.OA_BRANDPACK_ID
--WHERE OPO.DISTRIBUTOR_ID = @DISTRIBUTOR_ID
--AND YEAR(OPO.PO_REF_DATE) >= YEAR(GETDATE()) -1
--AND OPB.BRANDPACK_ID LIKE @V_BRAND_ID + '%'
--AND OOR.LEFT_QTY >= @V_DEVIDED_QTY
--AND OOR.LEFT_QTY > OOR.RELOTHEROA_QTY
--GO
-----------------------------------------------------------------------
--IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Update_ORDR_OA_REMAINDING_By_Other_OA' AND TYPE = 'P')
--DROP PROCEDURE Usp_Update_ORDR_OA_REMAINDING_By_Other_OA
--GO
--CREATE PROCEDURE Usp_Update_ORDR_OA_REMAINDING_By_Other_OA
--@OA_RM_ID VARCHAR(100),
--@REMARK_RELEASED VARCHAR(100),
--@MODIFY_BY VARCHAR(30),
--@RELOTHEROA_QTY VARCHAR(13)
--AS
--UPDATE ORDR_OA_REMAINDING SET ISRELOTHEROA = 1,
--REMARK_RELEASED = @REMARK_RELEASED,RELOTHEROA_QTY = @RELOTHEROA_QTY,MODIFY_BY = @MODIFY_BY,
--MODIFY_DATE = GETDATE()
--WHERE OA_RM_ID = @OA_RM_ID
--GO
   
--SELECT * FROM ORDR_OA_REMAINDING WHERE ACHIEVEMENT_BRANDPACK_ID IS NOT NULL