IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Save_Brnd_Price_Distributor'
	AND TYPE = 'P')
DROP PROCEDURE Usp_Save_Brnd_Price_Distributor
GO
CREATE PROCEDURE Usp_Save_Brnd_Price_Distributor
@PRICE_TAG VARCHAR(50),@PRICE DECIMAL(18,2),@DISTRIBUTOR_ID VARCHAR(10),@BRANDPACK_ID VARCHAR(14),
@CREATE_BY VARCHAR(50),@CREATE_DATE SMALLDATETIME,@PLANTATION_ID VARCHAR(50),@START_DATE SMALLDATETIME,
@MODIFY_BY VARCHAR(50),@MODIFY_DATE SMALLDATETIME

AS
SET NOCOUNT ON; 
--DECLARE @V_PRICE DECIMAL(10,3); 
--IF EXISTS(SELECT PRICE_TAG FROM DIST_PLANT_PRICE WHERE PRICE_TAG = @PRICE_TAG) 
 -- BEGIN  
    --CHECK PO
  	   --DELETE FROM DIST_PLANT_PRICE WHERE PRICE_TAG = @PRICE_TAG
 -- END
--ELSE  
  -- BEGIN 
   INSERT INTO DIST_PLANT_PRICE(PRICE_TAG,BRANDPACK_ID,DISTRIBUTOR_ID,PLANTATION_ID,
    PRICE,START_DATE,CREATE_BY,CREATE_DATE)
    VALUES(@PRICE_TAG,@BRANDPACK_ID,@DISTRIBUTOR_ID,@PLANTATION_ID,@PRICE,@START_DATE,@CREATE_BY,@CREATE_DATE);
   -- END
GO
------------------------------------------------------------------------------------
--SELECT * FROM DIST_PLANT_PRICE WHERE PRICE_TAG = '006020020LD|16/07/2010|KIM002000|KI|2'