---PROCEDURE UNTUK SEMUA YANG BERHUBUNGAN DENGAN PROJECT BRANDPACK
--KARENA PROCEDURE UNTUK PROJECT SUDAH DI BIKIN SEBELUMNYA JADI DI SINI 
-- TINGGAN BIKIN PROCEDURE SELECT BRANDPACK DETAIL
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Select_PROJ_BRANDPACK' AND TYPE = 'P')
DROP PROCEDURE Sp_Select_PROJ_BRANDPACK
GO
CREATE PROCEDURE Sp_Select_PROJ_BRANDPACK
AS
SELECT * FROM PROJ_BRANDPACK
GO
--------------------------------------------------------------------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_SelectBPInclude_WITHPARAM_DISTRIBUTOR_ID_AGREEMENT_STILL_APLY' AND TYPE = 'P')
DROP PROCEDURE Sp_SelectBPInclude_WITHPARAM_DISTRIBUTOR_ID_AGREEMENT_STILL_APLY
GO
CREATE PROCEDURE Sp_SelectBPInclude_WITHPARAM_DISTRIBUTOR_ID_AGREEMENT_STILL_APLY
@DISTRIBUTOR_ID VARCHAR(10)
AS
SELECT BRANDPACK_ID,BRANDPACK_NAME FROM VIEW_AGREE_BRANDPACK_INCLUDE WHERE DISTRIBUTOR_ID = @DISTRIBUTOR_ID
AND END_DATE >= GETDATE()
GO
-----------------------------------------------------------------------------------
--PROCEDURE UNTUK MENGECEK REFERENSI TABLE PROJ_PROJECT SELAIN DI PROJ_BRANDPACK
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Select_REFERENCE_PROJ_PROJECT'and TYPE = 'P')
DROP PROCEDURE Sp_Select_REFERENCE_PROJ_PROJECT
GO
CREATE PROCEDURE Sp_Select_REFERENCE_PROJ_PROJECT
@PROJ_REF_NO VARCHAR(15)
AS
BEGIN
IF(SELECT COUNT(PROJ_REF_NO) FROM ORDR_PURCHASE_ORDER WHERE PROJ_REF_NO = @PROJ_REF_NO)> 0
	RETURN(1)
END
RETURN(0)
GO
--------------------------------------------------------------------------
--PROCEDURE UNTUK MENGECEK REFERENSI TABLE PROJ_BRANDPACK
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME  = 'Sp_Select_REFERENCED_PROJ_BRANDPACK' AND TYPE = 'P')
DROP PROCEDURE Sp_Select_REFERENCED_PROJ_BRANDPACK
GO
CREATE PROCEDURE Sp_Select_REFERENCED_PROJ_BRANDPACK
@PROJ_BRANDPACK_ID VARCHAR(25)
AS
BEGIN
  if (SELECT COUNT(PROJ_BRANDPACK_ID) FROM PROJ_DISC_HISTORY WHERE PROJ_BRANDPACK_ID = @PROJ_BRANDPACK_ID) > 0
	RETURN(1)
END
RETURN(0)
GO
------------------------------------------------------------------------------------
--PROCEDURE FOR INSERT DATA PROJECT
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Insert_Project' AND TYPE = 'P')
DROP PROCEDURE Sp_Insert_Project
GO
CREATE PROCEDURE Sp_Insert_Project
@PROJ_REF_NO VARCHAR(15),
@PROJECT_NAME VARCHAR(50),
@PROJECT_REF_DATE DATETIME,
@ADDRESS VARCHAR(100),
@CONTACT VARCHAR(15),
@PHONE VARCHAR(15),
@FAX VARCHAR(15),
@HP VARCHAR(15),
@DISTRIBUTOR_ID VARCHAR(10),
@CREATE_BY VARCHAR(30)
AS
INSERT INTO PROJ_PROJECT(PROJ_REF_NO,PROJECT_NAME,PROJ_REF_DATE,ADDRESS,CONTACT,
PHONE,FAX,HP,DISTRIBUTOR_ID,CREATE_BY,CREATE_DATE)
VALUES(@PROJ_REF_NO,@PROJECT_NAME,@PROJECT_REF_DATE,@ADDRESS,@CONTACT,@PHONE,@FAX,@HP,@DISTRIBUTOR_ID,
@CREATE_BY,GETDATE())
GO
-----------------------------------------------------------------------------------
--PROCEDURE UNTUK UPDATE DATA PROJECT
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Update_Project' AND TYPE  = 'P')
DROP PROCEDURE Sp_Update_Project
GO
CREATE PROCEDURE Sp_Update_Project
@PROJ_REF_NO VARCHAR(15),
@PROJECT_NAME VARCHAR(50),
@PROJECT_REF_DATE DATETIME,
@ADDRESS VARCHAR(100),
@CONTACT VARCHAR(15),
@PHONE VARCHAR(15),
@FAX VARCHAR(15),
@HP VARCHAR(15),
@DISTRIBUTOR_ID VARCHAR(10),
@MODIFY_BY VARCHAR(30)
AS
UPDATE PROJ_PROJECT SET PROJECT_NAME = @PROJECT_NAME,PROJ_REF_DATE = @PROJECT_REF_DATE,
ADDRESS = @ADDRESS,CONTACT = @CONTACT,PHONE = @PHONE,FAX = @FAX,HP = @HP,DISTRIBUTOR_ID = @DISTRIBUTOR_ID,
MODIFY_BY = @MODIFY_BY,MODIFY_DATE = GETDATE() WHERE PROJ_REF_NO = @PROJ_REF_NO
GO
-------------------------------------------------------------------------------------
--PROCEDURE UNTUK MENGECEK DATA PROJ_REF_NO
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Check_PROJ_REF_NO' AND TYPE = 'P')
DROP PROCEDURE Sp_Check_PROJ_REF_NO
GO
CREATE PROCEDURE Sp_Check_PROJ_REF_NO
@PROJ_REF_NO VARCHAR(15)
AS
BEGIN
   IF (SELECT COUNT(PROJ_REF_NO) FROM PROJ_PROJECT WHERE PROJ_REF_NO = @PROJ_REF_NO) > 0
	RETURN(1)
END
RETURN(0)
GO
--------------------------------------------------------------------------------------
--PROCEDURE UNTUK MENDELETE DATA PROJ_PROJECT
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Delete_PROJ_PROJECT' AND TYPE = 'P')
DROP PROCEDURE Sp_Delete_PROJ_PROJECT
GO
CREATE PROCEDURE Sp_Delete_PROJ_PROJECT
@PROJ_REF_NO VARCHAR(15)
AS
DELETE FROM PROJ_PROJECT WHERE PROJ_REF_NO = @PROJ_REF_NO
GO
------------------------------------------------------------------------------------
----PROCEDURE UNTUK MEMVIEW DISCOUNT PROJECT
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_GetView_Project_Discount' AND TYPE = 'P')
DROP PROCEDURE Usp_GetView_Project_Discount
GO
CREATE PROCEDURE Usp_GetView_Project_Discount
@PROJ_REF_NO VARCHAR(15),
@DISTRIBUTOR_ID VARCHAR(10)
AS
SELECT PROJ_PROJECT.PROJ_REF_NO,BRND_BRANDPACK.BRANDPACK_NAME,PROJ_DISC_HISTORY.TOTAL_PO_QTY,PROJ_DISC_HISTORY.PROJ_DISC_PCT,
PROJ_DISC_HISTORY.PROJ_DISC_QTY,PROJ_DISC_HISTORY.PROJ_RELEASE_QTY,PROJ_DISC_HISTORY.PROJ_LEFT_QTY
FROM PROJ_PROJECT,PROJ_BRANDPACK,BRND_BRANDPACK,PROJ_DISC_HISTORY
WHERE PROJ_DISC_HISTORY.PROJ_BRANDPACK_ID = PROJ_BRANDPACK.PROJ_BRANDPACK_ID
AND PROJ_BRANDPACK.BRANDPACK_ID = BRND_BRANDPACK.BRANDPACK_ID AND PROJ_BRANDPACK.PROJ_REF_NO 
= PROJ_PROJECT.PROJ_REF_NO AND PROJ_PROJECT.PROJ_REF_NO = @PROJ_REF_NO AND PROJ_PROJECT.DISTRIBUTOR_ID = @DISTRIBUTOR_ID
GO
--EXEC Usp_GetView_Project_Discount
--@PROJ_REF_NO = 'PROJ/02',
--@DISTRIBUTOR_ID = 'ANE002IDR'

-----------------------------------------------------------------------------------
-----------PROCEDURE UNTUK MENEYELEKSI DATA BRANDPACK DI PO BERDASARKAN PROJ_REF_NO
/*
WIPER 865 AS @ 50 ML - D
WIPER 865 AS @ LABEL - 50 ML
WIPER 865 AS @ 200 L - D
WIPER 865 AS @ 400 ML -D
AGROXONE 400 AS @ BULK - D
AGROXONE 400 AS @ 250 ML- D
AVENTIS @ 100 ML - D
WIPER 865 AS @ 50 ML - D
AGROXONE 400 AS @ BULK - D
AGROXONE 400 AS @ 250 ML- D
AGROXONE 400 AS @ LABEL - 250 ML
AGROXONE 400 AS @ 500 ML - D
AVENTIS @ 100 ML - D
AGROMIN 865 AS-P @ 400 ML -D
ABAMECTIN 19.5 EC @ 15 ML - D
ABAMECTIN 19.5 EC @ 100 ML - D
ABAMECTIN 19.5 EC @ 150 ML - D
AGROMIN 865 AS-P @ 400 ML -D
ABAMECTIN 19.5 EC @ 15 ML - D
ABAMECTIN 19.5 EC @ 100 ML - D
ABAMECTIN 19.5 EC @ 150 ML - D
*/
--DELETE FROM PROJ_DISC_HISTORY