--PROCEDURE UNTUK MENYELEK DISTRIBUTOR UNTUK DI TAMPILKAN DI MULTICOLUMN COMBO
-- DI pURCHASE_ORDER , DISTRIBUTOR YANG DI TAMPILKAN ADALAH DISTRIBUTOR YANG MEMILIKI AGREEMENT
-- YANG MASIH BERLAKU DAN YANG MEMILIKI PROJECT 
--JADI UNUTK MENGISI MULTICOLUMN COMBO MESTI MENYELEKSI DISTRIBUTOR DI VIEW_AGREE_BRANDPACK_INCLUDE
-- DAN DI PROJECT DISTRIBUTOR
--DI VIEW BERDASARKAN PO_REF_NO DAN PADA SAAT INPUT
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Select_Distributor_For_MCB_PO' AND TYPE = 'P')
DROP PROCEDURE Sp_Select_Distributor_For_MCB_PO
GO
CREATE PROCEDURE Sp_Select_Distributor_For_MCB_PO
AS
BEGIN
SELECT DISTINCT VIEW_DISTRIBUTOR.DISTRIBUTOR_ID,VIEW_DISTRIBUTOR.DISTRIBUTOR_NAME,VIEW_DISTRIBUTOR.REGIONAL_AREA,
VIEW_DISTRIBUTOR.TERRITORY_AREA,VIEW_DISTRIBUTOR.CONTACT,VIEW_DISTRIBUTOR.PHONE FROM VIEW_DISTRIBUTOR
INNER JOIN VIEW_AGREE_BRANDPACK_INCLUDE ON VIEW_DISTRIBUTOR.DISTRIBUTOR_ID = VIEW_AGREE_BRANDPACK_INCLUDE.DISTRIBUTOR_ID
WHERE VIEW_AGREE_BRANDPACK_INCLUDE.END_DATE >= GETDATE()
END
GO

-------------------------------------------------------------------------------
--PROCEDURE UNTUK MENAMPILKAN DISTRIBUTOR UNTUK MENYELEK DISTRIBUTOR DI PO
--PO TERSEBUT BERDASARKAN AGREEMENT YANG MASIH BERLAKU
--PROCEDURE INI DI PAKAI UNTUK MENGECEK ITEM DISTRIBUTOR DI MULTICOLUMN COMNBO DISTRIBUTOR_PO
--PADA SAAT MAU DI ADD SATI SATU PADA MULTICOLUMN COMBO TERSEBUT APAKAH DISTRIBUTOR_YANG MEMILIKI AGREEMENT_ 
-- YANG MASIH BERLAKU / PROJECTNYA SUDAH ADA DI PO / BELUM
------------------------------------------------------------
--PROCEDURE INI ADA DI VIEW VIEW_DIST_PO_AGREE_STILL_APPLY
------------------------------------------------------------
--PROCEDURE UNTUK MENYELEKSI BRANDPACK BERDASARKAN PROJ_REF_NO
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Select_BRANDPACK_NAME_WITHPARAM_PROJ_REF_NO' AND TYPE = 'P')
DROP PROCEDURE Sp_Select_BRANDPACK_NAME_WITHPARAM_PROJ_REF_NO
GO
CREATE PROCEDURE Sp_Select_BRANDPACK_NAME_WITHPARAM_PROJ_REF_NO
@PROJ_REF_NO VARCHAR(15)
AS
SELECT BRANDPACK_ID,BRANDPACK_NAME,MAX_ORDER FROM PROJECT_BRANDPACK_DETAIL
WHERE PROJ_REF_NO = @PROJ_REF_NO AND END_DATE >= GETDATE()
GO
-----------------------------------------------------------------------------
--PROCEDURE UNTUK MENGINSERT DATA PO
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Insert_PO' AND TYPE = 'P')
DROP PROCEDURE Sp_Insert_PO
GO
CREATE PROCEDURE Sp_Insert_PO
@PO_REF_NO VARCHAR(25),
@PO_REF_DATE DATETIME,
@DISTRIBUTOR_ID VARCHAR(10),
@PROJ_REF_NO VARCHAR(15),
@CREATE_BY VARCHAR(30)
AS
INSERT INTO ORDR_PURCHASE_ORDER(PO_REF_NO,PO_REF_DATE,DISTRIBUTOR_ID,PROJ_REF_NO,CREATE_BY,CREATE_DATE)
VALUES(@PO_REF_NO,@PO_REF_DATE,@DISTRIBUTOR_ID,@PROJ_REF_NO,@CREATE_BY,GETDATE())
GO
---------------------------------------------------------------------------------
--PROCEDURE UNTUK MENGECEK REFERENSI DATA TABLE_PO PADA SAAT MAU DI DELETE
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Check_REFERENCED_PO' AND TYPE = 'P')
DROP PROCEDURE Sp_Check_REFERENCED_PO
GO
CREATE PROCEDURE Sp_Check_REFERENCED_PO
@PO_REF_NO VARCHAR(25)
AS
BEGIN
  IF (SELECT COUNT(PO_REF_NO) FROM ORDR_PO_BRANDPACK WHERE PO_REF_NO = @PO_REF_NO) > 0
	RETURN(1)
  ELSE IF (SELECT COUNT(PO_REF_NO) FROM ORDR_ORDER_ACCEPTANCE WHERE PO_REF_NO = @PO_REF_NO) > 0
	RETURN(2)
END
RETURN(0)
GO
--PROCEDURE UNTUK MENGECEK REFERENSI TABLE_PO_BRANDPACK_ID
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Select_REFERENCED_PO_BRANDPACK' AND TYPE = 'P')
DROP PROCEDURE Sp_Select_REFERENCED_PO_BRANDPACK
GO
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Select_REFERENCED_PO_BRANDPACK' AND TYPE = 'P')
DROP PROCEDURE Usp_Select_REFERENCED_PO_BRANDPACK
GO
CREATE PROCEDURE Usp_Select_REFERENCED_PO_BRANDPACK
@PO_BRANDPACK_ID VARCHAR(39)
AS
BEGIN
DECLARE @V_OA_BRANDPACK_ID  VARCHAR(70),@V_OA_ORIGINAL_QTY DECIMAL(18,3),@V_OA_QTY DECIMAL(18,3)
IF EXISTS(SELECT OA_BRANDPACK_ID FROM ORDR_OA_BRANDPACK WHERE PO_BRANDPACK_ID = @PO_BRANDPACK_ID)
  BEGIN  
        SET @V_OA_BRANDPACK_ID = (SELECT TOP 1 OA_BRANDPACK_ID FROM ORDR_OA_BRANDPACK WHERE PO_BRANDPACK_ID = @PO_BRANDPACK_ID)		
	SET @V_OA_QTY = (SELECT CAST((SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC WHERE OA_BRANDPACK_ID = @V_OA_BRANDPACK_ID AND GQSY_SGT_P_FLAG = 'RMOA') AS DECIMAL(18,3))
	+ CAST((SELECT QTY_EVEN FROM ORDR_OA_BRANDPACK WHERE OA_BRANDPACK_ID = @V_OA_BRANDPACK_ID)AS DECIMAL(18,3)))
	IF NOT EXISTS(SELECT TOP 1 SPPB_BRANDPACK_ID FROM SPPB_BRANDPACK WHERE OA_BRANDPACK_ID 
           = ANY(SELECT  OA_BRANDPACK_ID FROM ORDR_OA_BRANDPACK WHERE PO_BRANDPACK_ID = @PO_BRANDPACK_ID))
		BEGIN
			PRINT ' RETURN 0'
			RETURN(0)
		END
	IF EXISTS(SELECT SPPB_BRANDPACK_ID FROM SPPB_BRANDPACK WHERE OA_BRANDPACK_ID
          = ANY(SELECT  OA_BRANDPACK_ID FROM ORDR_OA_BRANDPACK WHERE PO_BRANDPACK_ID = @PO_BRANDPACK_ID))
		BEGIN
			PRINT 'RETURN 1'
			RETURN(1)
		END
	   
	ELSE IF EXISTS(SELECT SPPB_BRANDPACK_ID FROM SPPB_BRANDPACK WHERE OA_BRANDPACK_ID 
         = ANY(SELECT  OA_BRANDPACK_ID FROM ORDR_OA_BRANDPACK WHERE PO_BRANDPACK_ID = @PO_BRANDPACK_ID)
	 AND ISREVISION = 1 AND SPPB_QTY <> @V_OA_QTY)
	   BEGIN
		PRINT 'RETURN 0'
		RETURN(0)
	   END
	ELSE
	   BEGIN
	        PRINT ' RETURN 2'
	        RETURN(2)
	   END
   END
END
RETURN(0)
GO

--EXEC Sp_Select_REFERENCED_PO_BRANDPACK @PO_BRANDPACK_ID = 'PO_ABADI00010200MD'
--PROCEDURE UNTUK MENGECEK KEBERADAAN PO_REF_NO DI TABEL ORDR_PURCHASE_ORDER
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Check_PO_REF_NO' AND TYPE = 'P')
DROP PROCEDURE Sp_Check_PO_REF_NO
GO
CREATE PROCEDURE Sp_Check_PO_REF_NO
@PO_REF_NO VARCHAR(35)
AS
BEGIN
  IF (SELECT COUNT(PO_REF_NO) FROM ORDR_PURCHASE_ORDER WHERE PO_REF_NO = @PO_REF_NO) > 0
	RETURN(1)
END
RETURN(0)
GO
--DECLARE @RETURN_STATUS INT
--EXEC @RETURN_STATUS = Sp_Check_PO_REF_NO 'PO_HARRY_01'
-----------------------------------------------------------------------------
--PROCEDURE UNTUK MENGUPDATE DATA PO
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Update_PO' AND TYPE = 'P')
DROP PROCEDURE Sp_Update_PO
GO
CREATE PROCEDURE Sp_Update_PO
@PO_REF_NO VARCHAR(25),
@PO_REF_DATE DATETIME,
@DISTRIBUTOR_ID VARCHAR(10),
@PROJ_REF_NO VARCHAR(15),
@MODIFY_BY VARCHAR(30)
AS
UPDATE ORDR_PURCHASE_ORDER SET PO_REF_DATE = @PO_REF_DATE,
DISTRIBUTOR_ID = @DISTRIBUTOR_ID,MODIFY_BY = @MODIFY_BY,PROJ_REF_NO = @PROJ_REF_NO,
MODIFY_DATE = GETDATE() WHERE PO_REF_NO = @PO_REF_NO
GO
---------------------------------------------------------------------------------------------
--PROCEDURE UNTUK MENGECEK KEBERADAAN PO_BRANDPACK
if EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_CheckPO_BRANDPACK_ID' AND TYPE = 'P')
DROP PROCEDURE Sp_CheckPO_BRANDPACK_ID
GO
CREATE PROCEDURE Sp_CheckPO_BRANDPACK_ID
@PO_BRANDPACK_ID VARCHAR(39)
AS
BEGIN
IF (SELECT COUNT(PO_BRANDPACK_ID) FROM ORDR_PO_BRANDPACK WHERE PO_BRANDPACK_ID
= @PO_BRANDPACK_ID) > 0
	RETURN(1)
END
RETURN(0)
--------------------------------------------------------------------------
--PROCEDURE UNTUK MENYLEKSI PRICE UNTUK DI PAKAI DI PURCHASE ORDER
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Select_Price_ByDIST_ID' AND TYPE = 'P')
DROP PROCEDURE Sp_Select_Price_ByDIST_ID
GO
CREATE PROCEDURE Sp_Select_Price_ByDIST_ID
@DISTRIBUTOR_ID VARCHAR(10),
@PRICE_START_DATE DATETIME
AS
BEGIN
SELECT VIEW_AGREE_BRANDPACK_INCLUDE.BRANDPACK_ID,BRND_PRICE_HISTORY.PRICE,BRND_PRICE_HISTORY.START_DATE
FROM VIEW_AGREE_BRANDPACK_INCLUDE INNER JOIN BRND_PRICE_HISTORY ON VIEW_AGREE_BRANDPACK_INCLUDE.BRANDPACK_ID = BRND_PRICE_HISTORY.BRANDPACK_ID
WHERE VIEW_AGREE_BRANDPACK_INCLUDE.DISTRIBUTOR_ID = @DISTRIBUTOR_ID AND BRND_PRICE_HISTORY.START_DATE <= @PRICE_START_DATE
ORDER BY BRND_PRICE_HISTORY.START_DATE
END
GO
--------------------------------------------------------------------------
--PROCEDURE UNTUK MENYELEKSI PROCE UNTUK DI PAKAI DI PUCRCHASE_ORDER BERDASARKAN PROJ_REF_NO'
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Select_Price_ByPROJ_REF_NO' AND TYPE = 'P')
DROP PROCEDURE Sp_Select_Price_ByPROJ_REF_NO
GO
CREATE PROCEDURE Sp_Select_Price_ByPROJ_REF_NO
@PROJ_REF_NO VARCHAR(15),
@PRICE_START_DATE DATETIME
AS
SELECT PROJECT_BRANDPACK_DETAIL.BRANDPACK_ID,BRND_PRICE_HISTORY.PRICE,BRND_PRICE_HISTORY.START_DATE
FROM PROJECT_BRANDPACK_DETAIL INNER JOIN BRND_PRICE_HISTORY
ON PROJECT_BRANDPACK_DETAIL.BRANDPACK_ID = BRND_PRICE_HISTORY.BRANDPACK_ID
WHERE PROJECT_BRANDPACK_DETAIL.PROJ_REF_NO = @PROJ_REF_NO AND BRND_PRICE_HISTORY.START_DATE <= @PRICE_START_DATE
ORDER BY BRND_PRICE_HISTORY.START_DATE
GO

---------------------------------------------------------------------------------
--PROCEDUR UNTUK MENDELETE PURHCASE_ORDER
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Delete_PO' AND TYPE = 'P')
DROP PROCEDURE Sp_Delete_PO
GO
CREATE PROCEDURE Sp_Delete_PO
@PO_REF_NO VARCHAR(25)
AS
DELETE FROM ORDR_PURCHASE_ORDER WHERE PO_REF_NO = @PO_REF_NO
GO

-----------------------------------------------------------------------------
--PROCEDURE UNTUK MENDELETE PO_BRANDPACK
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Delete_ORDR_PO_BRANDPACK' AND TYPE = 'P')
DROP PROCEDURE Sp_Delete_ORDR_PO_BRANDPACK
GO
CREATE PROCEDURE Sp_Delete_ORDR_PO_BRANDPACK
@PO_BRANDPACK_ID varchar(39)
AS
DELETE FROM ORDR_PO_BRANDPACK WHERE PO_BRANDPACK_ID = @PO_BRANDPACK_ID
GO
----------------------------------------------------------------------------------
--PROCEDURE UNTUK MEMBINDING DATA DROPDOWNS DI DATAGRID PURCHASE ORDER
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_SelectBPInclude_WITHPARAM_DISTRIBUTOR_ID_AGREEMENT_STILL_APLY' AND TYPE = 'P')
DROP PROCEDURE Sp_SelectBPInclude_WITHPARAM_DISTRIBUTOR_ID_AGREEMENT_STILL_APLY
GO
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_SelectBPInclude_WITHPARAM_DISTRIBUTOR_ID_AGREEMENT_STILL_APLY' AND TYPE = 'P')
DROP PROCEDURE Usp_SelectBPInclude_WITHPARAM_DISTRIBUTOR_ID_AGREEMENT_STILL_APLY
GO
CREATE PROCEDURE Usp_SelectBPInclude_WITHPARAM_DISTRIBUTOR_ID_AGREEMENT_STILL_APLY
@DISTRIBUTOR_ID VARCHAR(10),
@PO_DATE DATETIME
AS
SELECT  BRANDPACK_ID,BRANDPACK_NAME FROM BRND_BRANDPACK BP 
WHERE EXISTS(SELECT BRANDPACK_ID FROM VIEW_AGREE_BRANDPACK_INCLUDE WHERE DISTRIBUTOR_ID = @DISTRIBUTOR_ID
 AND START_DATE <= @PO_DATE AND END_DATE >= @PO_DATE AND BRANDPACK_ID = BP.BRANDPACK_ID)
GO

-----------------------------------------------------------------------------------
--PROCEDURE UNTUK MEMVIEW PURCHASE_ORDER AGREEMENT_STILL APPLY
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_GetView_PURCHASE_ORDER_AGREE_STILL_APPLY' AND TYPE = 'P')
DROP PROCEDURE Sp_GetView_PURCHASE_ORDER_AGREE_STILL_APPLY
GO
CREATE PROCEDURE Sp_GetView_PURCHASE_ORDER_AGREE_STILL_APPLY
AS
SELECT VIEW_PURCHASE_ORDER.* FROM VIEW_PURCHASE_ORDER,AGREE_AGREEMENT
WHERE VIEW_PURCHASE_ORDER.DISTRIBUTOR_ID = AGREE_AGREEMENT.DISTRIBUTOR_ID
AND AGREE_AGREEMENT.END_DATE >= GETDATE()
GO
----------------------PROCEDURE UNTUK MENAMPILKAN PENCAPAIAN TARGET DI FORM PO----------------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Create_View_Target_Reaching' AND TYPE = 'P')
DROP PROCEDURE Usp_Create_View_Target_Reaching
GO
CREATE PROCEDURE Usp_Create_View_Target_Reaching
@DISTRIBUTOR_ID VARCHAR(10),
@AGREEMENT_NO VARCHAR(25),
@FLAG VARCHAR(2)
AS
SET NOCOUNT ON
DECLARE @V_START_DATE DATETIME,@V_SUMDAYS INT,@V_LONG_DATE INT
SET @V_START_DATE = (SELECT START_DATE FROM AGREE_AGREEMENT WHERE AGREEMENT_NO = @AGREEMENT_NO)
SET @V_SUMDAYS = CAST((SELECT DATEDIFF(DAY,START_DATE,END_DATE) FROM AGREE_AGREEMENT WHERE AGREEMENT_NO = @AGREEMENT_NO)AS INT)
IF (@FLAG = 'Q1') 
  BEGIN
	SET @V_LONG_DATE = (@V_SUMDAYS/4)
	DECLARE @V_START_DATE_Q1 DATETIME,@V_END_DATE_Q1 DATETIME
	SET @V_START_DATE_Q1 = @V_START_DATE
	SET @V_END_DATE_Q1 = (SELECT DATEADD(DAY,90,@V_START_DATE))
 	IF (SELECT COUNT (DISTRIBUTOR_ID) FROM DISTRIBUTOR_AGREEMENT WHERE AGREEMENT_NO = @AGREEMENT_NO) <= 1
	    BEGIN
		SELECT ABI.BRAND_ID,BR_1.BRAND_NAME,ABI.TARGET_Q1,TARGET_GROUP = 'NO',ISNULL(BR.ACTUAL,0)AS ACTUAL,ISNULL(BR.ACTUAL,0) - ABI.TARGET_Q1 AS LEFT_QTY FROM AGREE_BRAND_INCLUDE ABI INNER JOIN BRND_BRAND BR_1
		ON ABI.BRAND_ID = BR_1.BRAND_ID 
        	LEFT OUTER JOIN(
	                        SELECT ABI_1.AGREE_BRAND_ID,ISNULL(SUM(OPO.ACTUAL),0)AS ACTUAL FROM AGREE_BRANDPACK_INCLUDE ABI_1
	                        INNER JOIN(
			                   SELECT ABI_2.AGREE_BRANDPACK_ID,ISNULL(SUM(OPB.PO_ORIGINAL_QTY),0) AS ACTUAL FROM ORDR_PO_BRANDPACK OPB INNER JOIN AGREE_BRANDPACK_INCLUDE ABI_2
	                                   ON ABI_2.BRANDPACK_ID = OPB.BRANDPACK_ID 
	                                   INNER JOIN ORDR_PURCHASE_ORDER OPO ON OPB.PO_REF_NO = OPO.PO_REF_NO
                                           WHERE OPO.PO_REF_DATE <= @V_END_DATE_Q1 AND OPO.PO_REF_DATE >= @V_START_DATE_Q1
	                                   AND ABI_2.AGREEMENT_NO = @AGREEMENT_NO AND OPO.DISTRIBUTOR_ID = @DISTRIBUTOR_ID GROUP BY ABI_2.AGREE_BRANDPACK_ID 
                                           )OPO 
			                    ON OPO.AGREE_BRANDPACK_ID = ABI_1.AGREE_BRANDPACK_ID  GROUP BY ABI_1.AGREE_BRAND_ID
            		       )BR	
                                ON BR.AGREE_BRAND_ID = ABI.AGREE_BRAND_ID 
		WHERE ABI.AGREEMENT_NO = @AGREEMENT_NO 
	    END
	 ELSE
	    BEGIN
		SELECT ABI.BRAND_ID,BR_1.BRAND_NAME,ABI.TARGET_Q1,TARGET_GROUP = 'YESS',ISNULL(BR.ACTUAL,0)AS ACTUAL_DISTRIBUTOR,ISNULL(BR.ACTUAL_GROUP,0) AS ACTUAL_GROUP,
                ISNULL(BR.ACTUAL_GROUP,0) - ABI.TARGET_Q1 AS LEFT_QTY FROM AGREE_BRAND_INCLUDE ABI INNER JOIN BRND_BRAND BR_1
		ON ABI.BRAND_ID = BR_1.BRAND_ID 
        	LEFT OUTER JOIN(
	                        SELECT ABI_1.AGREE_BRAND_ID,ISNULL(SUM(OPO.ACTUAL),0)AS ACTUAL,ISNULL(SUM(OPO_1.ACTUAL_GROUP),0) AS ACTUAL_GROUP FROM AGREE_BRANDPACK_INCLUDE ABI_1
	                        INNER JOIN(
			                   SELECT ABI_2.AGREE_BRANDPACK_ID,ISNULL(SUM(OPB.PO_ORIGINAL_QTY),0) AS ACTUAL FROM ORDR_PO_BRANDPACK OPB INNER JOIN AGREE_BRANDPACK_INCLUDE ABI_2
	                                   ON ABI_2.BRANDPACK_ID = OPB.BRANDPACK_ID 
	                                   INNER JOIN ORDR_PURCHASE_ORDER OPO ON OPB.PO_REF_NO = OPO.PO_REF_NO
                                           WHERE OPO.PO_REF_DATE <= @V_END_DATE_Q1 AND OPO.PO_REF_DATE >= @V_START_DATE_Q1 AND OPO.DISTRIBUTOR_ID = @DISTRIBUTOR_ID
				           AND ABI_2.AGREEMENT_NO = @AGREEMENT_NO
	                                    GROUP BY ABI_2.AGREE_BRANDPACK_ID
                                           )OPO 
                                            ON OPO.AGREE_BRANDPACK_ID = ABI_1.AGREE_BRANDPACK_ID  
			         INNER JOIN(
			                   SELECT ABI_2.AGREE_BRANDPACK_ID,ISNULL(SUM(OPB.PO_ORIGINAL_QTY),0) AS ACTUAL_GROUP FROM ORDR_PO_BRANDPACK OPB INNER JOIN AGREE_BRANDPACK_INCLUDE ABI_2
	                                   ON ABI_2.BRANDPACK_ID = OPB.BRANDPACK_ID 
	                                   INNER JOIN ORDR_PURCHASE_ORDER OPO ON OPB.PO_REF_NO = OPO.PO_REF_NO
                                           WHERE OPO.PO_REF_DATE <= @V_END_DATE_Q1 AND OPO.PO_REF_DATE >= @V_START_DATE_Q1 AND 
					   OPO.DISTRIBUTOR_ID IN(SELECT DISTRIBUTOR_ID FROM DISTRIBUTOR_AGREEMENT WHERE AGREEMENT_NO = @AGREEMENT_NO)
				           AND ABI_2.AGREEMENT_NO = @AGREEMENT_NO
	                                    GROUP BY ABI_2.AGREE_BRANDPACK_ID
                                           )OPO_1 
                                          ON OPO_1.AGREE_BRANDPACK_ID = ABI_1.AGREE_BRANDPACK_ID  
                                  GROUP BY ABI_1.AGREE_BRAND_ID  					    
                        	 )BR	
                                ON BR.AGREE_BRAND_ID = ABI.AGREE_BRAND_ID 
		WHERE ABI.AGREEMENT_NO = @AGREEMENT_NO 
            END		
	PRINT ' @V_START_DATE_Q1 = ' + CAST((@V_START_DATE_Q1)AS VARCHAR(30))
	PRINT ' @V_END_DATE_Q1 = ' + CAST((@V_END_DATE_Q1)AS VARCHAR(30))
   END
ELSE IF(@FLAG = 'Q2')
   BEGIN
	SET @V_LONG_DATE = @V_SUMDAYS/4
	DECLARE @V_START_DATE_Q2 DATETIME,@V_END_DATE_Q2 DATETIME
	SET @V_START_DATE_Q2 = (SELECT DATEADD(DAY,@V_LONG_DATE,@V_START_DATE))
	SET @V_END_DATE_Q2 = (SELECT DATEADD(DAY,90,@V_START_DATE_Q2))
	IF (SELECT COUNT (DISTRIBUTOR_ID) FROM DISTRIBUTOR_AGREEMENT WHERE AGREEMENT_NO = @AGREEMENT_NO) <= 1
	    BEGIN
		SELECT ABI.BRAND_ID,BR_1.BRAND_NAME,ABI.TARGET_Q2,TARGET_GROUP = 'NO',ISNULL(BR.ACTUAL,0)AS ACTUAL,ISNULL(BR.ACTUAL,0) - ABI.TARGET_Q1 AS LEFT_QTY FROM AGREE_BRAND_INCLUDE ABI INNER JOIN BRND_BRAND BR_1
		ON ABI.BRAND_ID = BR_1.BRAND_ID 
        	LEFT OUTER JOIN(
	                        SELECT ABI_1.AGREE_BRAND_ID,ISNULL(SUM(OPO.ACTUAL),0)AS ACTUAL FROM AGREE_BRANDPACK_INCLUDE ABI_1
	                        INNER JOIN(
			                   SELECT ABI_2.AGREE_BRANDPACK_ID,ISNULL(SUM(OPB.PO_ORIGINAL_QTY),0) AS ACTUAL FROM ORDR_PO_BRANDPACK OPB INNER JOIN AGREE_BRANDPACK_INCLUDE ABI_2
	                                   ON ABI_2.BRANDPACK_ID = OPB.BRANDPACK_ID 
	                                   INNER JOIN ORDR_PURCHASE_ORDER OPO ON OPB.PO_REF_NO = OPO.PO_REF_NO
                                           WHERE OPO.PO_REF_DATE <= @V_END_DATE_Q2 AND OPO.PO_REF_DATE >= @V_START_DATE_Q2
	                                   AND ABI_2.AGREEMENT_NO = @AGREEMENT_NO AND OPO.DISTRIBUTOR_ID = @DISTRIBUTOR_ID GROUP BY ABI_2.AGREE_BRANDPACK_ID 
                                           )OPO 
			                    ON OPO.AGREE_BRANDPACK_ID = ABI_1.AGREE_BRANDPACK_ID  GROUP BY ABI_1.AGREE_BRAND_ID
            		       )BR	
                                ON BR.AGREE_BRAND_ID = ABI.AGREE_BRAND_ID 
		WHERE ABI.AGREEMENT_NO = @AGREEMENT_NO 
	    END
	 ELSE
	    BEGIN
		SELECT ABI.BRAND_ID,BR_1.BRAND_NAME,ABI.TARGET_Q2,TARGET_GROUP = 'YESS',ISNULL(BR.ACTUAL,0)AS ACTUAL_DISTRIBUTOR,ISNULL(BR.ACTUAL_GROUP,0) AS ACTUAL_GROUP,
                ISNULL(BR.ACTUAL_GROUP,0) - ABI.TARGET_Q1 AS LEFT_QTY FROM AGREE_BRAND_INCLUDE ABI INNER JOIN BRND_BRAND BR_1
		ON ABI.BRAND_ID = BR_1.BRAND_ID 
        	LEFT OUTER JOIN(
	                        SELECT ABI_1.AGREE_BRAND_ID,ISNULL(SUM(OPO.ACTUAL),0)AS ACTUAL,ISNULL(SUM(OPO_1.ACTUAL_GROUP),0) AS ACTUAL_GROUP FROM AGREE_BRANDPACK_INCLUDE ABI_1
	                        INNER JOIN(
			                   SELECT ABI_2.AGREE_BRANDPACK_ID,ISNULL(SUM(OPB.PO_ORIGINAL_QTY),0) AS ACTUAL FROM ORDR_PO_BRANDPACK OPB INNER JOIN AGREE_BRANDPACK_INCLUDE ABI_2
	                                   ON ABI_2.BRANDPACK_ID = OPB.BRANDPACK_ID 
	                                   INNER JOIN ORDR_PURCHASE_ORDER OPO ON OPB.PO_REF_NO = OPO.PO_REF_NO
                                           WHERE OPO.PO_REF_DATE <= @V_END_DATE_Q2 AND OPO.PO_REF_DATE >= @V_START_DATE_Q2 AND OPO.DISTRIBUTOR_ID = @DISTRIBUTOR_ID
				           AND ABI_2.AGREEMENT_NO = @AGREEMENT_NO
	                                    GROUP BY ABI_2.AGREE_BRANDPACK_ID
                                           )OPO 
                                            ON OPO.AGREE_BRANDPACK_ID = ABI_1.AGREE_BRANDPACK_ID  
			         INNER JOIN(
			                   SELECT ABI_2.AGREE_BRANDPACK_ID,ISNULL(SUM(OPB.PO_ORIGINAL_QTY),0) AS ACTUAL_GROUP FROM ORDR_PO_BRANDPACK OPB INNER JOIN AGREE_BRANDPACK_INCLUDE ABI_2
	                                   ON ABI_2.BRANDPACK_ID = OPB.BRANDPACK_ID 
	                                   INNER JOIN ORDR_PURCHASE_ORDER OPO ON OPB.PO_REF_NO = OPO.PO_REF_NO
                                           WHERE OPO.PO_REF_DATE <= @V_END_DATE_Q2 AND OPO.PO_REF_DATE >= @V_START_DATE_Q2 AND 
					   OPO.DISTRIBUTOR_ID IN(SELECT DISTRIBUTOR_ID FROM DISTRIBUTOR_AGREEMENT WHERE AGREEMENT_NO = @AGREEMENT_NO)
				           AND ABI_2.AGREEMENT_NO = @AGREEMENT_NO
	                                    GROUP BY ABI_2.AGREE_BRANDPACK_ID
                                           )OPO_1 
                                          ON OPO_1.AGREE_BRANDPACK_ID = ABI_1.AGREE_BRANDPACK_ID  
                                  GROUP BY ABI_1.AGREE_BRAND_ID  					    
                        	 )BR	
                                ON BR.AGREE_BRAND_ID = ABI.AGREE_BRAND_ID 
		WHERE ABI.AGREEMENT_NO = @AGREEMENT_NO 
            END
	PRINT ' @V_START_DATE_Q2 = ' + CAST((@V_START_DATE_Q2)AS VARCHAR(30))
	PRINT ' @V_END_DATE_Q2 = ' + CAST((@V_END_DATE_Q2)AS VARCHAR(30))
   END
ELSE IF(@FLAG = 'Q3')
   BEGIN
	SET @V_LONG_DATE = @V_SUMDAYS/4
	DECLARE @V_START_DATEQ2 DATETIME,@V_START_DATE_Q3 DATETIME,@V_END_DATE_Q3 DATETIME
	SET @V_START_DATEQ2 = (SELECT DATEADD(DAY,@V_LONG_DATE,@V_START_DATE)) 
	SET @V_START_DATE_Q3 = (SELECT DATEADD(DAY,91, @V_START_DATEQ2)) 
	SET @V_END_DATE_Q3 = (SELECT DATEADD(DAY,90,@V_START_DATE_Q3))
	IF (SELECT COUNT (DISTRIBUTOR_ID) FROM DISTRIBUTOR_AGREEMENT WHERE AGREEMENT_NO = @AGREEMENT_NO) <= 1
	    BEGIN
		SELECT ABI.BRAND_ID,BR_1.BRAND_NAME,ABI.TARGET_Q3,TARGET_GROUP = 'NO',ISNULL(BR.ACTUAL,0)AS ACTUAL,ISNULL(BR.ACTUAL,0) - ABI.TARGET_Q1 AS LEFT_QTY FROM AGREE_BRAND_INCLUDE ABI INNER JOIN BRND_BRAND BR_1
		ON ABI.BRAND_ID = BR_1.BRAND_ID 
        	LEFT OUTER JOIN(
	                        SELECT ABI_1.AGREE_BRAND_ID,ISNULL(SUM(OPO.ACTUAL),0)AS ACTUAL FROM AGREE_BRANDPACK_INCLUDE ABI_1
	                        INNER JOIN(
			                   SELECT ABI_2.AGREE_BRANDPACK_ID,ISNULL(SUM(OPB.PO_ORIGINAL_QTY),0) AS ACTUAL FROM ORDR_PO_BRANDPACK OPB INNER JOIN AGREE_BRANDPACK_INCLUDE ABI_2
	                                   ON ABI_2.BRANDPACK_ID = OPB.BRANDPACK_ID 
	                                   INNER JOIN ORDR_PURCHASE_ORDER OPO ON OPB.PO_REF_NO = OPO.PO_REF_NO
                                           WHERE OPO.PO_REF_DATE <= @V_END_DATE_Q3 AND OPO.PO_REF_DATE >= @V_START_DATE_Q3
	                                   AND ABI_2.AGREEMENT_NO = @AGREEMENT_NO AND OPO.DISTRIBUTOR_ID = @DISTRIBUTOR_ID GROUP BY ABI_2.AGREE_BRANDPACK_ID 
                                           )OPO 
			                    ON OPO.AGREE_BRANDPACK_ID = ABI_1.AGREE_BRANDPACK_ID  GROUP BY ABI_1.AGREE_BRAND_ID
            		       )BR	
                                ON BR.AGREE_BRAND_ID = ABI.AGREE_BRAND_ID 
		WHERE ABI.AGREEMENT_NO = @AGREEMENT_NO 
	    END
	 ELSE
	    BEGIN
		SELECT ABI.BRAND_ID,BR_1.BRAND_NAME,ABI.TARGET_Q3,TARGET_GROUP = 'YESS',ISNULL(BR.ACTUAL,0)AS ACTUAL_DISTRIBUTOR,ISNULL(BR.ACTUAL_GROUP,0) AS ACTUAL_GROUP,
                ISNULL(BR.ACTUAL_GROUP,0) - ABI.TARGET_Q1 AS LEFT_QTY FROM AGREE_BRAND_INCLUDE ABI INNER JOIN BRND_BRAND BR_1
		ON ABI.BRAND_ID = BR_1.BRAND_ID 
        	LEFT OUTER JOIN(
	                        SELECT ABI_1.AGREE_BRAND_ID,ISNULL(SUM(OPO.ACTUAL),0)AS ACTUAL,ISNULL(SUM(OPO_1.ACTUAL_GROUP),0) AS ACTUAL_GROUP FROM AGREE_BRANDPACK_INCLUDE ABI_1
	                        INNER JOIN(
			                   SELECT ABI_2.AGREE_BRANDPACK_ID,ISNULL(SUM(OPB.PO_ORIGINAL_QTY),0) AS ACTUAL FROM ORDR_PO_BRANDPACK OPB INNER JOIN AGREE_BRANDPACK_INCLUDE ABI_2
	                                   ON ABI_2.BRANDPACK_ID = OPB.BRANDPACK_ID 
	                                   INNER JOIN ORDR_PURCHASE_ORDER OPO ON OPB.PO_REF_NO = OPO.PO_REF_NO
                                           WHERE OPO.PO_REF_DATE <= @V_END_DATE_Q3 AND OPO.PO_REF_DATE >= @V_START_DATE_Q3 AND OPO.DISTRIBUTOR_ID = @DISTRIBUTOR_ID
				           AND ABI_2.AGREEMENT_NO = @AGREEMENT_NO
	                                    GROUP BY ABI_2.AGREE_BRANDPACK_ID
                                           )OPO 
                                            ON OPO.AGREE_BRANDPACK_ID = ABI_1.AGREE_BRANDPACK_ID  
			         INNER JOIN(
			                   SELECT ABI_2.AGREE_BRANDPACK_ID,ISNULL(SUM(OPB.PO_ORIGINAL_QTY),0) AS ACTUAL_GROUP FROM ORDR_PO_BRANDPACK OPB INNER JOIN AGREE_BRANDPACK_INCLUDE ABI_2
	                                   ON ABI_2.BRANDPACK_ID = OPB.BRANDPACK_ID 
	                                   INNER JOIN ORDR_PURCHASE_ORDER OPO ON OPB.PO_REF_NO = OPO.PO_REF_NO
                                           WHERE OPO.PO_REF_DATE <= @V_END_DATE_Q3 AND OPO.PO_REF_DATE >= @V_START_DATE_Q3 AND 
					   OPO.DISTRIBUTOR_ID IN(SELECT DISTRIBUTOR_ID FROM DISTRIBUTOR_AGREEMENT WHERE AGREEMENT_NO = @AGREEMENT_NO)
				           AND ABI_2.AGREEMENT_NO = @AGREEMENT_NO
	                                    GROUP BY ABI_2.AGREE_BRANDPACK_ID
                                           )OPO_1 
                                          ON OPO_1.AGREE_BRANDPACK_ID = ABI_1.AGREE_BRANDPACK_ID  
                                  GROUP BY ABI_1.AGREE_BRAND_ID  					    
                        	 )BR	
                                ON BR.AGREE_BRAND_ID = ABI.AGREE_BRAND_ID 
		WHERE ABI.AGREEMENT_NO = @AGREEMENT_NO 
            END
	PRINT ' @V_START_DATE_Q3 = ' + CAST((@V_START_DATE_Q3)AS VARCHAR(30))
	PRINT ' @V_END_DATE_Q3 = ' + CAST((@V_END_DATE_Q3)AS VARCHAR(30))
   END
ELSE IF (@FLAG = 'Q4')
   BEGIN
	SET @V_LONG_DATE = @V_SUMDAYS/4
	DECLARE @V_START_Q2 DATETIME,@V_START_DATE_Q4 DATETIME,@V_END_DATE_Q4 DATETIME,@V_START_DATEQ3 DATETIME
	SET @V_START_Q2 = (SELECT DATEADD(DAY,@V_LONG_DATE,@V_START_DATE)) 
	SET @V_START_DATEQ3 = (SELECT DATEADD(DAY,91, @V_START_Q2)) 
	SET @V_START_DATE_Q4 = (SELECT DATEADD(DAY,91,@V_START_DATEQ3)) 
	SET @V_END_DATE_Q4 = (SELECT END_DATE FROM AGREE_AGREEMENT WHERE AGREEMENT_NO = @AGREEMENT_NO )
	IF (SELECT COUNT (DISTRIBUTOR_ID) FROM DISTRIBUTOR_AGREEMENT WHERE AGREEMENT_NO = @AGREEMENT_NO) <= 1
	    BEGIN
		SELECT ABI.BRAND_ID,BR_1.BRAND_NAME,ABI.TARGET_Q4,TARGET_GROUP = 'NO',ISNULL(BR.ACTUAL,0)AS ACTUAL,ISNULL(BR.ACTUAL,0) - ABI.TARGET_Q1 AS LEFT_QTY FROM AGREE_BRAND_INCLUDE ABI INNER JOIN BRND_BRAND BR_1
		ON ABI.BRAND_ID = BR_1.BRAND_ID 
        	LEFT OUTER JOIN(
	                        SELECT ABI_1.AGREE_BRAND_ID,ISNULL(SUM(OPO.ACTUAL),0)AS ACTUAL FROM AGREE_BRANDPACK_INCLUDE ABI_1
	                        INNER JOIN(
			                   SELECT ABI_2.AGREE_BRANDPACK_ID,ISNULL(SUM(OPB.PO_ORIGINAL_QTY),0) AS ACTUAL FROM ORDR_PO_BRANDPACK OPB INNER JOIN AGREE_BRANDPACK_INCLUDE ABI_2
	                                   ON ABI_2.BRANDPACK_ID = OPB.BRANDPACK_ID 
	                                   INNER JOIN ORDR_PURCHASE_ORDER OPO ON OPB.PO_REF_NO = OPO.PO_REF_NO
                                           WHERE OPO.PO_REF_DATE <= @V_END_DATE_Q4 AND OPO.PO_REF_DATE >= @V_START_DATE_Q4
	                                   AND ABI_2.AGREEMENT_NO = @AGREEMENT_NO AND OPO.DISTRIBUTOR_ID = @DISTRIBUTOR_ID GROUP BY ABI_2.AGREE_BRANDPACK_ID 
                                           )OPO 
			                    ON OPO.AGREE_BRANDPACK_ID = ABI_1.AGREE_BRANDPACK_ID  GROUP BY ABI_1.AGREE_BRAND_ID
            		       )BR	
                                ON BR.AGREE_BRAND_ID = ABI.AGREE_BRAND_ID 
		WHERE ABI.AGREEMENT_NO = @AGREEMENT_NO 
	    END
	 ELSE
	    BEGIN
		SELECT ABI.BRAND_ID,BR_1.BRAND_NAME,ABI.TARGET_Q4,TARGET_GROUP = 'YESS',ISNULL(BR.ACTUAL,0)AS ACTUAL_DISTRIBUTOR,ISNULL(BR.ACTUAL_GROUP,0) AS ACTUAL_GROUP,
                ISNULL(BR.ACTUAL_GROUP,0) - ABI.TARGET_Q1 AS LEFT_QTY FROM AGREE_BRAND_INCLUDE ABI INNER JOIN BRND_BRAND BR_1
		ON ABI.BRAND_ID = BR_1.BRAND_ID 
        	LEFT OUTER JOIN(
	                        SELECT ABI_1.AGREE_BRAND_ID,ISNULL(SUM(OPO.ACTUAL),0)AS ACTUAL,ISNULL(SUM(OPO_1.ACTUAL_GROUP),0) AS ACTUAL_GROUP FROM AGREE_BRANDPACK_INCLUDE ABI_1
	                        INNER JOIN(
			                   SELECT ABI_2.AGREE_BRANDPACK_ID,ISNULL(SUM(OPB.PO_ORIGINAL_QTY),0) AS ACTUAL FROM ORDR_PO_BRANDPACK OPB INNER JOIN AGREE_BRANDPACK_INCLUDE ABI_2
	                                   ON ABI_2.BRANDPACK_ID = OPB.BRANDPACK_ID 
	                                   INNER JOIN ORDR_PURCHASE_ORDER OPO ON OPB.PO_REF_NO = OPO.PO_REF_NO
                                           WHERE OPO.PO_REF_DATE <= @V_END_DATE_Q4 AND OPO.PO_REF_DATE >= @V_START_DATE_Q4 AND OPO.DISTRIBUTOR_ID = @DISTRIBUTOR_ID
				           AND ABI_2.AGREEMENT_NO = @AGREEMENT_NO
	                                    GROUP BY ABI_2.AGREE_BRANDPACK_ID
                                           )OPO 
                                            ON OPO.AGREE_BRANDPACK_ID = ABI_1.AGREE_BRANDPACK_ID  
			         INNER JOIN(
			                   SELECT ABI_2.AGREE_BRANDPACK_ID,ISNULL(SUM(OPB.PO_ORIGINAL_QTY),0) AS ACTUAL_GROUP FROM ORDR_PO_BRANDPACK OPB INNER JOIN AGREE_BRANDPACK_INCLUDE ABI_2
	                                   ON ABI_2.BRANDPACK_ID = OPB.BRANDPACK_ID 
	                                   INNER JOIN ORDR_PURCHASE_ORDER OPO ON OPB.PO_REF_NO = OPO.PO_REF_NO
                                           WHERE OPO.PO_REF_DATE <= @V_END_DATE_Q4 AND OPO.PO_REF_DATE >= @V_START_DATE_Q4 AND 
					   OPO.DISTRIBUTOR_ID IN(SELECT DISTRIBUTOR_ID FROM DISTRIBUTOR_AGREEMENT WHERE AGREEMENT_NO = @AGREEMENT_NO)
				           AND ABI_2.AGREEMENT_NO = @AGREEMENT_NO
	                                    GROUP BY ABI_2.AGREE_BRANDPACK_ID
                                           )OPO_1 
                                          ON OPO_1.AGREE_BRANDPACK_ID = ABI_1.AGREE_BRANDPACK_ID  
                                  GROUP BY ABI_1.AGREE_BRAND_ID  					    
                        	 )BR	
                                ON BR.AGREE_BRAND_ID = ABI.AGREE_BRAND_ID 
		WHERE ABI.AGREEMENT_NO = @AGREEMENT_NO 
            END

	PRINT ' @V_START_DATE_Q4 = ' + CAST((@V_START_DATE_Q4)AS VARCHAR(30))
	PRINT ' @V_END_DATE_Q4 = ' + CAST((@V_END_DATE_Q4)AS VARCHAR(30))
   END
ELSE IF(@FLAG = 'S1')
     BEGIN
	SET @V_LONG_DATE = @V_SUMDAYS/2
	DECLARE @V_START_DATE_S1 DATETIME,@V_END_DATE_S1 DATETIME
	SET @V_START_DATE_S1 = @V_START_DATE
	SET @V_END_DATE_S1 = (SELECT DATEADD(DAY,@V_LONG_DATE - 1,@V_START_DATE_S1))
	PRINT ' @V_START_DATE_S1 = ' + CAST((@V_START_DATE_S1)AS VARCHAR(30))
	PRINT ' @V_END_DATE_S1 = ' + CAST((@V_END_DATE_S1)AS VARCHAR(30))
	IF (SELECT COUNT (DISTRIBUTOR_ID) FROM DISTRIBUTOR_AGREEMENT WHERE AGREEMENT_NO = @AGREEMENT_NO) <= 1
	    BEGIN
		SELECT ABI.BRAND_ID,BR_1.BRAND_NAME,ABI.TARGET_S1,TARGET_GROUP = 'NO',ISNULL(BR.ACTUAL,0)AS ACTUAL,ISNULL(BR.ACTUAL,0) - ABI.TARGET_Q1 AS LEFT_QTY FROM AGREE_BRAND_INCLUDE ABI INNER JOIN BRND_BRAND BR_1
		ON ABI.BRAND_ID = BR_1.BRAND_ID 
        	LEFT OUTER JOIN(
	                        SELECT ABI_1.AGREE_BRAND_ID,ISNULL(SUM(OPO.ACTUAL),0)AS ACTUAL FROM AGREE_BRANDPACK_INCLUDE ABI_1
	                        INNER JOIN(
			                   SELECT ABI_2.AGREE_BRANDPACK_ID,ISNULL(SUM(OPB.PO_ORIGINAL_QTY),0) AS ACTUAL FROM ORDR_PO_BRANDPACK OPB INNER JOIN AGREE_BRANDPACK_INCLUDE ABI_2
	                                   ON ABI_2.BRANDPACK_ID = OPB.BRANDPACK_ID 
	                                   INNER JOIN ORDR_PURCHASE_ORDER OPO ON OPB.PO_REF_NO = OPO.PO_REF_NO
                                           WHERE OPO.PO_REF_DATE <= @V_END_DATE_S1 AND OPO.PO_REF_DATE >= @V_START_DATE_S1
	                                   AND ABI_2.AGREEMENT_NO = @AGREEMENT_NO AND OPO.DISTRIBUTOR_ID = @DISTRIBUTOR_ID GROUP BY ABI_2.AGREE_BRANDPACK_ID 
                                           )OPO 
			                    ON OPO.AGREE_BRANDPACK_ID = ABI_1.AGREE_BRANDPACK_ID  GROUP BY ABI_1.AGREE_BRAND_ID
            		       )BR	
                                ON BR.AGREE_BRAND_ID = ABI.AGREE_BRAND_ID 
		WHERE ABI.AGREEMENT_NO = @AGREEMENT_NO 
	    END
	 ELSE
	    BEGIN
		SELECT ABI.BRAND_ID,BR_1.BRAND_NAME,ABI.TARGET_S1,TARGET_GROUP = 'YESS',ISNULL(BR.ACTUAL,0)AS ACTUAL_DISTRIBUTOR,ISNULL(BR.ACTUAL_GROUP,0) AS ACTUAL_GROUP,
                ISNULL(BR.ACTUAL_GROUP,0) - ABI.TARGET_Q1 AS LEFT_QTY FROM AGREE_BRAND_INCLUDE ABI INNER JOIN BRND_BRAND BR_1
		ON ABI.BRAND_ID = BR_1.BRAND_ID 
        	LEFT OUTER JOIN(
	                        SELECT ABI_1.AGREE_BRAND_ID,ISNULL(SUM(OPO.ACTUAL),0)AS ACTUAL,ISNULL(SUM(OPO_1.ACTUAL_GROUP),0) AS ACTUAL_GROUP FROM AGREE_BRANDPACK_INCLUDE ABI_1
	                        INNER JOIN(
			                   SELECT ABI_2.AGREE_BRANDPACK_ID,ISNULL(SUM(OPB.PO_ORIGINAL_QTY),0) AS ACTUAL FROM ORDR_PO_BRANDPACK OPB INNER JOIN AGREE_BRANDPACK_INCLUDE ABI_2
	                                   ON ABI_2.BRANDPACK_ID = OPB.BRANDPACK_ID 
	                                   INNER JOIN ORDR_PURCHASE_ORDER OPO ON OPB.PO_REF_NO = OPO.PO_REF_NO
                                           WHERE OPO.PO_REF_DATE <= @V_END_DATE_S1 AND OPO.PO_REF_DATE >= @V_START_DATE_S1 AND OPO.DISTRIBUTOR_ID = @DISTRIBUTOR_ID
				           AND ABI_2.AGREEMENT_NO = @AGREEMENT_NO
	                                    GROUP BY ABI_2.AGREE_BRANDPACK_ID
                                           )OPO 
                                            ON OPO.AGREE_BRANDPACK_ID = ABI_1.AGREE_BRANDPACK_ID  
			         INNER JOIN(
			                   SELECT ABI_2.AGREE_BRANDPACK_ID,ISNULL(SUM(OPB.PO_ORIGINAL_QTY),0) AS ACTUAL_GROUP FROM ORDR_PO_BRANDPACK OPB INNER JOIN AGREE_BRANDPACK_INCLUDE ABI_2
	                                   ON ABI_2.BRANDPACK_ID = OPB.BRANDPACK_ID 
	                                   INNER JOIN ORDR_PURCHASE_ORDER OPO ON OPB.PO_REF_NO = OPO.PO_REF_NO
                                           WHERE OPO.PO_REF_DATE <= @V_END_DATE_S1 AND OPO.PO_REF_DATE >= @V_START_DATE_S1 AND 
					   OPO.DISTRIBUTOR_ID IN(SELECT DISTRIBUTOR_ID FROM DISTRIBUTOR_AGREEMENT WHERE AGREEMENT_NO = @AGREEMENT_NO)
				           AND ABI_2.AGREEMENT_NO = @AGREEMENT_NO
	                                    GROUP BY ABI_2.AGREE_BRANDPACK_ID
                                           )OPO_1 
                                          ON OPO_1.AGREE_BRANDPACK_ID = ABI_1.AGREE_BRANDPACK_ID  
                                  GROUP BY ABI_1.AGREE_BRAND_ID  					    
                        	 )BR	
                                ON BR.AGREE_BRAND_ID = ABI.AGREE_BRAND_ID 
		WHERE ABI.AGREEMENT_NO = @AGREEMENT_NO 
            END
	
     END
ELSE IF (@FLAG = 'S2')
     BEGIN
	SET @V_LONG_DATE = @V_SUMDAYS/2
	DECLARE @V_START_DATE_S2 DATETIME,@V_END_DATE_S2 DATETIME
	SET @V_START_DATE_S2 = (SELECT DATEADD(DAY,@V_LONG_DATE,@V_START_DATE)) 
	SET @V_END_DATE_S2 = (SELECT END_DATE FROM AGREE_AGREEMENT WHERE AGREEMENT_NO = @AGREEMENT_NO)
	PRINT ' @V_START_DATE_S2 = ' + CAST((@V_START_DATE_S2)AS VARCHAR(30))
	PRINT ' @V_END_DATE_S2 = ' + CAST((@V_END_DATE_S2)AS VARCHAR(30))
	IF (SELECT COUNT (DISTRIBUTOR_ID) FROM DISTRIBUTOR_AGREEMENT WHERE AGREEMENT_NO = @AGREEMENT_NO) <= 1
	    BEGIN
		SELECT ABI.BRAND_ID,BR_1.BRAND_NAME,ABI.TARGET_S2,TARGET_GROUP = 'NO',ISNULL(BR.ACTUAL,0)AS ACTUAL,ISNULL(BR.ACTUAL,0) - ABI.TARGET_Q1 AS LEFT_QTY FROM AGREE_BRAND_INCLUDE ABI INNER JOIN BRND_BRAND BR_1
		ON ABI.BRAND_ID = BR_1.BRAND_ID 
        	LEFT OUTER JOIN(
	                        SELECT ABI_1.AGREE_BRAND_ID,ISNULL(SUM(OPO.ACTUAL),0)AS ACTUAL FROM AGREE_BRANDPACK_INCLUDE ABI_1
	                        INNER JOIN(
			                   SELECT ABI_2.AGREE_BRANDPACK_ID,ISNULL(SUM(OPB.PO_ORIGINAL_QTY),0) AS ACTUAL FROM ORDR_PO_BRANDPACK OPB INNER JOIN AGREE_BRANDPACK_INCLUDE ABI_2
	                                   ON ABI_2.BRANDPACK_ID = OPB.BRANDPACK_ID 
	                                   INNER JOIN ORDR_PURCHASE_ORDER OPO ON OPB.PO_REF_NO = OPO.PO_REF_NO
                                           WHERE OPO.PO_REF_DATE <= @V_END_DATE_S2 AND OPO.PO_REF_DATE >= @V_START_DATE_S2
	                                   AND ABI_2.AGREEMENT_NO = @AGREEMENT_NO AND OPO.DISTRIBUTOR_ID = @DISTRIBUTOR_ID GROUP BY ABI_2.AGREE_BRANDPACK_ID 
                                           )OPO 
			                    ON OPO.AGREE_BRANDPACK_ID = ABI_1.AGREE_BRANDPACK_ID  GROUP BY ABI_1.AGREE_BRAND_ID
            		       )BR	
                                ON BR.AGREE_BRAND_ID = ABI.AGREE_BRAND_ID 
		WHERE ABI.AGREEMENT_NO = @AGREEMENT_NO 
	    END
	 ELSE
	    BEGIN
		SELECT ABI.BRAND_ID,BR_1.BRAND_NAME,ABI.TARGET_S2,TARGET_GROUP = 'YESS',ISNULL(BR.ACTUAL,0)AS ACTUAL_DISTRIBUTOR,ISNULL(BR.ACTUAL_GROUP,0) AS ACTUAL_GROUP,
                ISNULL(BR.ACTUAL_GROUP,0) - ABI.TARGET_Q1 AS LEFT_QTY FROM AGREE_BRAND_INCLUDE ABI INNER JOIN BRND_BRAND BR_1
		ON ABI.BRAND_ID = BR_1.BRAND_ID 
        	LEFT OUTER JOIN(
	                        SELECT ABI_1.AGREE_BRAND_ID,ISNULL(SUM(OPO.ACTUAL),0)AS ACTUAL,ISNULL(SUM(OPO_1.ACTUAL_GROUP),0) AS ACTUAL_GROUP FROM AGREE_BRANDPACK_INCLUDE ABI_1
	                        INNER JOIN(
			                   SELECT ABI_2.AGREE_BRANDPACK_ID,ISNULL(SUM(OPB.PO_ORIGINAL_QTY),0) AS ACTUAL FROM ORDR_PO_BRANDPACK OPB INNER JOIN AGREE_BRANDPACK_INCLUDE ABI_2
	                                   ON ABI_2.BRANDPACK_ID = OPB.BRANDPACK_ID 
	                                   INNER JOIN ORDR_PURCHASE_ORDER OPO ON OPB.PO_REF_NO = OPO.PO_REF_NO
                                           WHERE OPO.PO_REF_DATE <= @V_END_DATE_S2 AND OPO.PO_REF_DATE >= @V_START_DATE_S2 AND OPO.DISTRIBUTOR_ID = @DISTRIBUTOR_ID
				           AND ABI_2.AGREEMENT_NO = @AGREEMENT_NO
	                                    GROUP BY ABI_2.AGREE_BRANDPACK_ID
                                           )OPO 
                                            ON OPO.AGREE_BRANDPACK_ID = ABI_1.AGREE_BRANDPACK_ID  
			         INNER JOIN(
			                   SELECT ABI_2.AGREE_BRANDPACK_ID,ISNULL(SUM(OPB.PO_ORIGINAL_QTY),0) AS ACTUAL_GROUP FROM ORDR_PO_BRANDPACK OPB INNER JOIN AGREE_BRANDPACK_INCLUDE ABI_2
	                                   ON ABI_2.BRANDPACK_ID = OPB.BRANDPACK_ID 
	                                   INNER JOIN ORDR_PURCHASE_ORDER OPO ON OPB.PO_REF_NO = OPO.PO_REF_NO
                                           WHERE OPO.PO_REF_DATE <= @V_END_DATE_S2 AND OPO.PO_REF_DATE >= @V_START_DATE_S2 AND 
					   OPO.DISTRIBUTOR_ID IN(SELECT DISTRIBUTOR_ID FROM DISTRIBUTOR_AGREEMENT WHERE AGREEMENT_NO = @AGREEMENT_NO)
				           AND ABI_2.AGREEMENT_NO = @AGREEMENT_NO
	                                    GROUP BY ABI_2.AGREE_BRANDPACK_ID
                                           )OPO_1 
                                          ON OPO_1.AGREE_BRANDPACK_ID = ABI_1.AGREE_BRANDPACK_ID  
                                  GROUP BY ABI_1.AGREE_BRAND_ID  					    
                        	 )BR	
                                ON BR.AGREE_BRAND_ID = ABI.AGREE_BRAND_ID 
		WHERE ABI.AGREEMENT_NO = @AGREEMENT_NO 
            END
     END
ELSE IF(@FLAG = 'Y')
     BEGIN
	DECLARE @V_END_DATE DATETIME
	SET @V_END_DATE = (SELECT END_DATE FROM AGREE_AGREEMENT WHERE AGREEMENT_NO = @AGREEMENT_NO)
 	   IF (SELECT COUNT (DISTRIBUTOR_ID) FROM DISTRIBUTOR_AGREEMENT WHERE AGREEMENT_NO = @AGREEMENT_NO) <= 1
	    BEGIN
		SELECT ABI.BRAND_ID,BR_1.BRAND_NAME,ABI.TARGET_Q1 + ABI.TARGET_Q2 + ABI.TARGET_Q3 + ABI.TARGET_Q4
                + ABI.TARGET_S1 + ABI.TARGET_S2 AS TARGET_YEAR,TARGET_GROUP = 'NO',ISNULL(BR.ACTUAL,0)AS ACTUAL,ISNULL(BR.ACTUAL,0) - ABI.TARGET_Q1 AS LEFT_QTY FROM AGREE_BRAND_INCLUDE ABI INNER JOIN BRND_BRAND BR_1
		ON ABI.BRAND_ID = BR_1.BRAND_ID 
        	LEFT OUTER JOIN(
	                        SELECT ABI_1.AGREE_BRAND_ID,ISNULL(SUM(OPO.ACTUAL),0)AS ACTUAL FROM AGREE_BRANDPACK_INCLUDE ABI_1
	                        INNER JOIN(
			                   SELECT ABI_2.AGREE_BRANDPACK_ID,ISNULL(SUM(OPB.PO_ORIGINAL_QTY),0) AS ACTUAL FROM ORDR_PO_BRANDPACK OPB INNER JOIN AGREE_BRANDPACK_INCLUDE ABI_2
	                                   ON ABI_2.BRANDPACK_ID = OPB.BRANDPACK_ID 
	                                   INNER JOIN ORDR_PURCHASE_ORDER OPO ON OPB.PO_REF_NO = OPO.PO_REF_NO
                                           WHERE OPO.PO_REF_DATE <= @V_END_DATE AND OPO.PO_REF_DATE >= @V_START_DATE
	                                   AND ABI_2.AGREEMENT_NO = @AGREEMENT_NO AND OPO.DISTRIBUTOR_ID = @DISTRIBUTOR_ID GROUP BY ABI_2.AGREE_BRANDPACK_ID 
                                           )OPO 
			                    ON OPO.AGREE_BRANDPACK_ID = ABI_1.AGREE_BRANDPACK_ID  GROUP BY ABI_1.AGREE_BRAND_ID
            		       )BR	
                                ON BR.AGREE_BRAND_ID = ABI.AGREE_BRAND_ID 
		WHERE ABI.AGREEMENT_NO = @AGREEMENT_NO 
	    END
	 ELSE
	    BEGIN
		SELECT ABI.BRAND_ID,BR_1.BRAND_NAME,ABI.TARGET_Q1 + ABI.TARGET_Q2 + ABI.TARGET_Q3 + ABI.TARGET_Q4
                + ABI.TARGET_S1 + ABI.TARGET_S2 AS TARGET_YEAR,TARGET_GROUP = 'YESS',ISNULL(BR.ACTUAL,0)AS ACTUAL_DISTRIBUTOR,ISNULL(BR.ACTUAL_GROUP,0) AS ACTUAL_GROUP,
                ISNULL(BR.ACTUAL_GROUP,0) - (ABI.TARGET_Q1 + ABI.TARGET_Q2 + ABI.TARGET_Q3 + ABI.TARGET_Q4
                + ABI.TARGET_S1 + ABI.TARGET_S2) AS LEFT_QTY FROM AGREE_BRAND_INCLUDE ABI INNER JOIN BRND_BRAND BR_1
		ON ABI.BRAND_ID = BR_1.BRAND_ID 
        	LEFT OUTER JOIN(
	                        SELECT ABI_1.AGREE_BRAND_ID,ISNULL(SUM(OPO.ACTUAL),0)AS ACTUAL,ISNULL(SUM(OPO_1.ACTUAL_GROUP),0) AS ACTUAL_GROUP FROM AGREE_BRANDPACK_INCLUDE ABI_1
	                        INNER JOIN(
			                   SELECT ABI_2.AGREE_BRANDPACK_ID,ISNULL(SUM(OPB.PO_ORIGINAL_QTY),0) AS ACTUAL FROM ORDR_PO_BRANDPACK OPB INNER JOIN AGREE_BRANDPACK_INCLUDE ABI_2
	                                   ON ABI_2.BRANDPACK_ID = OPB.BRANDPACK_ID 
	                                   INNER JOIN ORDR_PURCHASE_ORDER OPO ON OPB.PO_REF_NO = OPO.PO_REF_NO
                                           WHERE OPO.PO_REF_DATE <= @V_END_DATE AND OPO.PO_REF_DATE >= @V_START_DATE AND OPO.DISTRIBUTOR_ID = @DISTRIBUTOR_ID
				           AND ABI_2.AGREEMENT_NO = @AGREEMENT_NO
	                                    GROUP BY ABI_2.AGREE_BRANDPACK_ID
                                           )OPO 
                                            ON OPO.AGREE_BRANDPACK_ID = ABI_1.AGREE_BRANDPACK_ID  
			         INNER JOIN(
			                   SELECT ABI_2.AGREE_BRANDPACK_ID,ISNULL(SUM(OPB.PO_ORIGINAL_QTY),0) AS ACTUAL_GROUP FROM ORDR_PO_BRANDPACK OPB INNER JOIN AGREE_BRANDPACK_INCLUDE ABI_2
	                                   ON ABI_2.BRANDPACK_ID = OPB.BRANDPACK_ID 
	                                   INNER JOIN ORDR_PURCHASE_ORDER OPO ON OPB.PO_REF_NO = OPO.PO_REF_NO
                                           WHERE OPO.PO_REF_DATE <= @V_END_DATE AND OPO.PO_REF_DATE >= @V_START_DATE AND 
					   OPO.DISTRIBUTOR_ID IN(SELECT DISTRIBUTOR_ID FROM DISTRIBUTOR_AGREEMENT WHERE AGREEMENT_NO = @AGREEMENT_NO)
				           AND ABI_2.AGREEMENT_NO = @AGREEMENT_NO
	                                    GROUP BY ABI_2.AGREE_BRANDPACK_ID
                                           )OPO_1 
                                          ON OPO_1.AGREE_BRANDPACK_ID = ABI_1.AGREE_BRANDPACK_ID  
                                  GROUP BY ABI_1.AGREE_BRAND_ID  					    
                        	 )BR	
                                ON BR.AGREE_BRAND_ID = ABI.AGREE_BRAND_ID 
		WHERE ABI.AGREEMENT_NO = @AGREEMENT_NO 
            END

	PRINT '@V_START_DATE = ' + CAST((@V_START_DATE)AS VARCHAR(30))
	PRINT '@V_END_DATE = ' + CAST((@V_END_DATE)AS VARCHAR(30))
     END

GO
--exec Usp_Create_View_Target_Reaching
--@DISTRIBUTOR_ID = 'LOK002000',
--@AGREEMENT_NO = '1114/NI/X/2008-200ML',
--@FLAG = 'Q1'
-------------------------------------------------------------------------------------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_GetView_Actice_PO' AND TYPE = 'P')
DROP PROCEDURE Usp_GetView_Actice_PO
GO
CREATE PROCEDURE Usp_GetView_Actice_PO
@DISTRIBUTOR_ID VARCHAR(10)
AS
SET NOCOUNT ON;
DECLARE @ParamValue INT;
--MSC0002 = Setting berapa bulan PO dapat di cancel terhitung dari tanggal PO
SELECT @ParamValue = CAST((SELECT ParamValue FROM RefBussinesRules WHERE CodeApp = 'MSC0002')AS INT);
SELECT OPO.DISTRIBUTOR_ID,DTR.DISTRIBUTOR_NAME,OPO.PO_REF_NO,OPO.PO_REF_DATE,
OPB.PO_BRANDPACK_ID,PO_ORIGINAL_QTY,BRN.BRANDPACK_NAME,	[REASON] = '' FROM DIST_DISTRIBUTOR DTR
INNER JOIN ORDR_PURCHASE_ORDER OPO ON OPO.DISTRIBUTOR_ID = DTR.DISTRIBUTOR_ID
INNER JOIN ORDR_PO_BRANDPACK OPB ON OPO.PO_REF_NO = OPB.PO_REF_NO
INNER JOIN BRND_BRANDPACK BRN ON OPB.BRANDPACK_ID = BRN.BRANDPACK_ID
WHERE OPO.DISTRIBUTOR_ID = @DISTRIBUTOR_ID AND DATEDIFF(MONTH,OPO.PO_REF_DATE,GETDATE()) <= @ParamValue
AND OPB.PO_ORIGINAL_QTY > 0;
GO

--exec sp_executesql N'SET NOCOUNT ON ;
--SELECT OPO.DISTRIBUTOR_ID,DR.DISTRIBUTOR_NAME,OPO.PO_REF_NO,OPO.PO_REF_DATE,OPB.PO_BRANDPACK_ID,BB.BRANDPACK_NAME,
-- OPB.PO_ORIGINAL_QTY AS QUANTITY,OPB.PO_PRICE_PERQTY AS [PRICE/QTY],
-- OPB.PO_ORIGINAL_QTY * OPB.PO_PRICE_PERQTY AS TOTAL,
-- OPB.BRANDPACK_ID,OPB.GIVEN_PKPP_VALUE,OPB.DESCRIPTIONS,
-- OPB.CREATE_DATE, OPB.MODIFY_DATE 
-- FROM ORDR_PURCHASE_ORDER OPO INNER JOIN DIST_DISTRIBUTOR DR ON OPO.DISTRIBUTOR_ID = DR.DISTRIBUTOR_ID 
-- LEFT OUTER JOIN ORDR_PO_BRANDPACK OPB ON OPB.PO_REF_NO = OPO.PO_REF_NO LEFT OUTER JOIN BRND_BRANDPACK BB 
-- ON OPB.BRANDPACK_ID = BB.BRANDPACK_ID WHERE OPO.PO_REF_DATE >= @StartDate AND OPO.PO_REF_DATE <= @EndDate ;', N'@StartDate 
--datetime,@EndDate datetime', @StartDate = 'May  3 2011', @EndDate = 'Jun 30 2011'