IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME  ='Usp_Get_Detail_Qty_Dispro_By_Invoice' 
           AND TYPE = 'P')
DROP PROCEDURE Usp_Get_Detail_Qty_Dispro_By_Invoice
GO
CREATE PROCEDURE Usp_Get_Detail_Qty_Dispro_By_Invoice
@DISTRIBUTOR_ID VARCHAR(10),
@START_DATE SMALLDATETIME,
@END_DATE SMALLDATETIME
AS
SET NOCOUNT ON;
DECLARE @Criteria NVARCHAR(100);
IF (@DISTRIBUTOR_ID IS NOT NULL)
   BEGIN
     SET @Criteria = ' WHERE OPO.DISTRIBUTOR_ID = @V_DISTRIBUTOR_ID';
   END
ELSE
   BEGIN
     SET @Criteria = '';
   END
SELECT DR.DISTRIBUTOR_ID,DR.DISTRIBUTOR_NAME,BR.BRAND_NAME,BB.BRANDPACK_NAME,(OPO.QTY_EVEN + ISNULL(OPO.LEFT_OA_QTY,0)) AS OA_QTY,OPO.RPK,
OPO.DP,OPO.CP_D,OPO.CP_R,OPO.PKPP,OPO.DK,OPO.OTHERS,OPO.QTY AS TOTAL_DELIVERY,
ACCRUE.QUARTER_1 ,ACCRUE.QUARTER_2 ,ACCRUE.QUARTER_3,ACCRUE.QUARTER_4,ACCRUE.SEMESTER_1,
ACCRUE.SEMESTER_2 ,ACCRUE.YEARLY,ACCRUE.RELEASE_Q1 - OPO.REM_Q1 AS RELEASE_Q1,
ACCRUE.RELEASE_Q2 - OPO.REM_Q2 AS RELEASE_Q2,ACCRUE.RELEASE_Q3 - OPO.REM_Q3 AS RELEASE_Q3,
ACCRUE.RELEASE_Q4 - OPO.REM_Q4 AS RELEASE_Q4,ACCRUE.RELEASE_S1 - OPO.REM_S1 AS RELEASE_S1,
ACCRUE.RELEASE_S2 - OPO.REM_S2 AS RELEASE_S2,ACCRUE.RELEASE_Y - OPO.REM_Y AS RELEASE_Y, 
ISNULL((ACCRUE.RELEASE_Q1 + ACCRUE.RELEASE_Q2 + ACCRUE.RELEASE_Q3 + ACCRUE.RELEASE_Q4 + ACCRUE.RELEASE_S1 + ACCRUE.RELEASE_S2 + ACCRUE.RELEASE_Y),0)
- ISNULL((OPO.REM_Q1 + OPO.REM_Q2 + OPO.REM_Q3 + OPO.REM_Q4 + OPO.REM_S1 + OPO.REM_S2 + OPO.REM_Y),0)
AS TOTAL_RELEASE,

ACCRUE.LEFT_Q1,ACCRUE.LEFT_Q2,ACCRUE.LEFT_Q3,ACCRUE.LEFT_Q4,ACCRUE.LEFT_S1, ACCRUE.LEFT_S2,ACCRUE.LEFT_Y,
ISNULL((ACCRUE.LEFT_Q1 + ACCRUE.LEFT_Q2 + ACCRUE.LEFT_Q3 + ACCRUE.LEFT_Q4 + ACCRUE.LEFT_S1 +  ACCRUE.LEFT_S2 + ACCRUE.LEFT_Y),0)
AS TOTAL_LEFT
FROM Nufarm.dbo.DIST_DISTRIBUTOR DR INNER JOIN
(
  SELECT OPO.DISTRIBUTOR_ID,OPB.BRANDPACK_ID,ISNULL(SUM(OOB.QTY_EVEN),0) AS QTY_EVEN,
  ISNULL(SUM(OBD.RPK),0)AS RPK,ISNULL(SUM(OBD.OTHERS),0)AS OTHERS,ISNULL(SUM(OBD.LEFT_OA_QTY),0) AS LEFT_OA_QTY,
  ISNULL(SUM(OBD.DP),0)AS DP,ISNULL(SUM(OBD.CP_D),0)AS CP_D,ISNULL(SUM(OBD.CP_R),0)AS CP_R,
  ISNULL(SUM(OBD.PKPP),0) AS PKPP,ISNULL(SUM(OBD.DK),0) AS DK,
  ISNULL(SUM(REM.REM_Q1),0)AS REM_Q1,ISNULL(SUM(REM.REM_Q2),0)AS REM_Q2,ISNULL(SUM(REM.REM_Q3),0)AS REM_Q3,
  ISNULL(SUM(REM.REM_Q4),0)AS REM_Q4,ISNULL(SUM(REM.REM_S1),0)AS REM_S1,
  ISNULL(SUM(REM.REM_S2),0)AS REM_S2,ISNULL(SUM(REM.REM_Y),0)AS REM_Y,
  ISNULL(SUM(OBD.TOTAL_DISC),0) AS TOTAL_DISC,ISNULL(SUM(INVOICE.QTY),0)AS QTY
  FROM Nufarm.dbo.ORDR_PURCHASE_ORDER OPO 
  INNER JOIN Nufarm.dbo.ORDR_PO_BRANDPACK OPB ON OPO.PO_REF_NO = OPB.PO_REF_NO
  INNER JOIN Nufarm.dbo.ORDR_OA_BRANDPACK OOB ON OOB.PO_BRANDPACK_ID = OPB.PO_BRANDPACK_ID 
  INNER JOIN 
          (
     	    SELECT REPLACE(RIGHT(RTRIM(INV.ITEM),11),'-','')AS BRANDPACK_ID,
     	    INV.QTYSHIPPED - INV.QTYRETURN AS QTY, INV.PONUMBER
     	    FROM
         	(
          	  SELECT INVH.INVDATE,INVH.PONUMBER,INVD.ITEM,INVD.QTYSHIPPED,ISNULL(CRD.QTYRETURN,0)AS QTYRETURN
           	  FROM NI87.dbo.OEINVH INVH INNER JOIN NI87.dbo.OEINVD INVD ON INVH.INVUNIQ = INVD.INVUNIQ
           	  LEFT OUTER JOIN
                         (
			   SELECT CRDH1.INVNUMBER,CRDH1.ITEM,ISNULL(SUM(CRDH1.QTYRETURN),0)AS QTYRETURN
			   FROM 
				(								
                           	  SELECT CRDH.CRDUNIQ,CRDH.INVNUMBER,CRD.ITEM,ISNULL(CRD.QTYRETURN,0)AS QTYRETURN
                                  FROM NI87.DBO.OECRDH CRDH INNER JOIN 
                                  (
                                    SELECT CRDUNIQ,ITEM,ISNULL(SUM(QTYRETURN),0)AS QTYRETURN
                                    FROM NI87.DBO.OECRDD WHERE LINETYPE = 1 AND ACCTSET = 'FG'
                                    GROUP BY CRDUNIQ,ITEM
                                   )CRD ON CRDH.CRDUNIQ = CRD.CRDUNIQ      
                                 )CRDH1
                           GROUP BY CRDH1.INVNUMBER,CRDH1.ITEM    
                          )CRD
                  ON CRD.INVNUMBER = INVH.INVNUMBER 
           	  AND CRD.ITEM = INVD.ITEM
           	  WHERE INVH.INVDATE >= @START_DATE 
	          AND INVH.INVDATE >= @END_DATE
		  AND INVD.ACCTSET = 'FG' AND INVD.LINETYPE = 1
	   	  AND LEN(RIGHT(RTRIM(INVD.ITEM),11)) >= 11
                 )INV
    	   )INVOICE
  ON INVOICE.PONUMBER = OPO.PO_REF_NO AND INVOICE.BRANDPACK_ID = OPB.BRANDPACK_ID    
  LEFT OUTER JOIN (
		    SELECT OA_BRANDPACK_ID,
		    ISNULL(SUM(CASE GQSY_SGT_P_FLAG WHEN 'MG' THEN DISC_QTY ELSE 0 END),0) AS RPK,
		    ISNULL(SUM(CASE GQSY_SGT_P_FLAG WHEN 'O' THEN DISC_QTY ELSE 0 END),0)AS OTHERS,
		    ISNULL(SUM(CASE GQSY_SGT_P_FLAG WHEN 'RMOA' THEN DISC_QTY ELSE 0 END),0) AS LEFT_OA_QTY,
		    ISNULL(SUM(CASE GQSY_SGT_P_FLAG WHEN 'G' THEN DISC_QTY ELSE 0 END),0) AS DP,
		    ISNULL(SUM(CASE GQSY_SGT_P_FLAG WHEN 'CPD' THEN DISC_QTY ELSE 0 END),0) AS CP_D,
		    ISNULL(SUM(CASE GQSY_SGT_P_FLAG WHEN 'CPR' THEN DISC_QTY ELSE 0 END),0) AS CP_R,
		    ISNULL(SUM(CASE GQSY_SGT_P_FLAG WHEN 'KP' THEN DISC_QTY ELSE 0 END),0)AS PKPP,
		    ISNULL(SUM(CASE GQSY_SGT_P_FLAG WHEN 'DK' THEN DISC_QTY ELSE 0 END),0) AS DK,
		    ISNULL(SUM(DISC_QTY),0) AS TOTAL_DISC
		    FROM Nufarm.dbo.ORDR_OA_BRANDPACK_DISC
		    GROUP BY OA_BRANDPACK_ID
                 )OBD
  ON OOB.OA_BRANDPACK_ID = OBD.OA_BRANDPACK_ID
  LEFT OUTER JOIN (
                   SELECT OA_BRANDPACK_ID,
                   ISNULL(SUM(CASE FLAG WHEN 'Q1' THEN LEFT_QTY ELSE 0 END),0) AS REM_Q1,
		   ISNULL(SUM(CASE FLAG WHEN 'Q2' THEN LEFT_QTY ELSE 0 END),0) AS REM_Q2,
		   ISNULL(SUM(CASE FLAG WHEN 'Q3' THEN LEFT_QTY ELSE 0 END),0) AS REM_Q3,
		   ISNULL(SUM(CASE FLAG WHEN 'Q4' THEN LEFT_QTY ELSE 0 END),0) AS REM_Q4,
		   ISNULL(SUM(CASE FLAG WHEN 'S1' THEN LEFT_QTY ELSE 0 END),0) AS REM_S1,
		   ISNULL(SUM(CASE FLAG WHEN 'S2' THEN LEFT_QTY ELSE 0 END),0) AS REM_S2,
		   ISNULL(SUM(CASE FLAG WHEN 'Y' THEN LEFT_QTY ELSE 0 END),0)AS REM_Y
                   FROM Nufarm.dbo.ORDR_OA_REMAINDING GROUP BY OA_BRANDPACK_ID
		  )REM
  ON OOB.OA_BRANDPACK_ID = REM.OA_BRANDPACK_ID

  WHERE OPO.PO_REF_DATE >= @START_DATE AND OPO.PO_REF_DATE <= @END_DATE
  AND INVOICE.QTY >= OPB.PO_ORIGINAL_QTY 
  GROUP BY OPO.DISTRIBUTOR_ID,OPB.BRANDPACK_ID
)OPO
ON OPO.DISTRIBUTOR_ID = DR.DISTRIBUTOR_ID
INNER JOIN Nufarm.dbo.BRND_BRANDPACK BB ON BB.BRANDPACK_ID = OPO.BRANDPACK_ID
INNER JOIN BRND_BRAND BR ON BR.BRAND_ID = BB.BRAND_ID
LEFT OUTER JOIN(
                 SELECT ACRH.DISTRIBUTOR_ID,ACRD.BRANDPACK_ID,

	         (CASE ACRH.FLAG WHEN 'Q1' THEN ACRD.DISC_QTY ELSE 0 END)AS QUARTER_1,
	         (CASE ACRH.FLAG WHEN 'Q2' THEN ACRD.DISC_QTY ELSE 0 END)AS QUARTER_2,
                 (CASE ACRH.FLAG WHEN 'Q3' THEN ACRD.DISC_QTY ELSE 0 END)AS QUARTER_3,
	         (CASE ACRH.FLAG WHEN 'Q4' THEN ACRD.DISC_QTY ELSE 0 END) AS QUARTER_4,
	         (CASE ACRH.FLAG WHEN 'S1' THEN ACRD.DISC_QTY ELSE 0 END)AS SEMESTER_1,
	         (CASE ACRH.FLAG WHEN 'S2' THEN ACRD.DISC_QTY ELSE 0 END)AS SEMESTER_2,
	         (CASE ACRH.FLAG WHEN 'Y'  THEN ACRD.DISC_QTY ELSE 0 END)AS YEARLY,
	         (CASE ACRH.FLAG WHEN 'Q1' THEN ACRD.RELEASE_QTY ELSE 0 END)AS RELEASE_Q1,
	         (CASE ACRH.FLAG WHEN 'Q2' THEN ACRD.RELEASE_QTY ELSE 0 END)AS RELEASE_Q2,
	         (CASE ACRH.FLAG WHEN 'Q3' THEN ACRD.RELEASE_QTY ELSE 0 END)AS RELEASE_Q3,
	         (CASE ACRH.FLAG WHEN 'Q4' THEN ACRD.RELEASE_QTY ELSE 0 END)AS RELEASE_Q4,
	         (CASE ACRH.FLAG WHEN 'S1' THEN ACRD.RELEASE_QTY ELSE 0 END)AS RELEASE_S1,
	         (CASE ACRH.FLAG WHEN 'S2' THEN ACRD.RELEASE_QTY ELSE 0 END)AS RELEASE_S2,
	         (CASE ACRH.FLAG WHEN 'Y'  THEN ACRD.RELEASE_QTY ELSE 0 END)AS RELEASE_Y,
	         (CASE ACRH.FLAG WHEN 'Q1' THEN ACRD.LEFT_QTY ELSE 0 END)AS LEFT_Q1,
	         (CASE ACRH.FLAG WHEN 'Q2' THEN ACRD.LEFT_QTY ELSE 0 END) AS LEFT_Q2,
	         (CASE ACRH.FLAG WHEN 'Q3' THEN ACRD.LEFT_QTY ELSE 0 END)AS LEFT_Q3,
	         (CASE ACRH.FLAG WHEN 'Q4' THEN ACRD.LEFT_QTY ELSE 0 END) AS LEFT_Q4,
	         (CASE ACRH.FLAG WHEN 'S1' THEN ACRD.LEFT_QTY ELSE 0 END)AS LEFT_S1,
	         (CASE ACRH.FLAG WHEN 'S2' THEN ACRD.LEFT_QTY ELSE 0 END)AS LEFT_S2,
	         (CASE ACRH.FLAG WHEN 'Y'  THEN ACRD.LEFT_QTY ELSE 0 END)AS LEFT_Y
	   
	         FROM Nufarm.dbo.ACCRUED_HEADER ACRH INNER JOIN Nufarm.dbo.ACCRUED_DETAIL ACRD
                 ON ACRH.ACHIEVEMENT_ID = ACRD.ACHIEVEMENT_ID
	       )ACCRUE
ON OPO.BRANDPACK_ID = ACCRUE.BRANDPACK_ID
AND OPO.DISTRIBUTOR_ID = ACCRUE.DISTRIBUTOR_ID
WHERE OPO.DISTRIBUTOR_ID = @DISTRIBUTOR_ID


