IF EXISTS(SELECT NAME FROM SYS.OBJECTS WHERE NAME = 'Usp_Get_Report_DD_DR' AND TYPE = 'P')
DROP PROCEDURE Usp_Get_Report_DD_DR
GO
CREATE PROCEDURE Usp_Get_Report_DD_DR
@START_DATE SMALLDATETIME,
@END_DATE SMALLDATETIME,
@PAR_COLUMNS VARCHAR(50),
@DISTRIBUTOR_ID VARCHAR(50)
AS
SET NOCOUNT ON;
DECLARE @QRY_MAIN NVARCHAR(MAX),@QRY_WHERE NVARCHAR(300),@QRY_FULL NVARCHAR(MAX)
SET @QRY_MAIN = N'SELECT REG.REGIONAL_AREA,TR.TERRITORY_AREA,PROGRAM_ID = CASE WHEN (BDH.PROGRAM_ID IS NOT NULL) THEN BDH.PROGRAM_ID
ELSE CONVERT(VARCHAR(100),BDH.IDApp) END,
BDH.PROGRAM_DESC,BDH.APPlY_DATE,BDH.END_DATE,
CASE BDH.APPLY_TO WHEN ''AL'' THEN (''ALL DISTRIBUTORS'') ELSE ''CERTAIN DISTRIBUTORS'' END
AS APPLY_TO,
CASE BDH.APPLY_TO WHEN ''AL'' THEN (''REF ALL'') ELSE DR.DISTRIBUTOR_NAME END
AS DISTRIBUTORS,
BR.BRAND_NAME,ISNULL(LB.BRANDPACK_NAME,'''') AS BRANDPACK_NAME,
APPLY_TARGET_TO =  CASE WHEN (PROG1.BRANDPACK_ID IS NOT NULL) THEN ''CURRENT PACK SIZE'' 
						WHEN (PROG2.BRAND_ID IS NOT NULL) THEN ''ALL PACK SIZE OF CURRENT BRAND''
						ELSE ''ALL PRODUCT(S)'' 
						END,
TARGET_PO = CASE WHEN (PROG1.BRANDPACK_ID IS NOT NULL) THEN PROG1.MoreThanQty 
						WHEN (PROG2.BRAND_ID IS NOT NULL) THEN PROG2.MoreThanQty
						ELSE PROG.MoreThanQty 
						END,
DISC = CASE WHEN (PROG1.BRANDPACK_ID IS NOT NULL) THEN PROG1.Disc/100 
						WHEN (PROG2.BRAND_ID IS NOT NULL) THEN PROG2.Disc/100
						ELSE PROG.Disc/100 
						END,
DISC_TYPE = CASE WHEN (PROG1.BRANDPACK_ID IS NOT NULL) THEN PROG1.TypeApp 
						WHEN (PROG2.BRAND_ID IS NOT NULL) THEN PROG2.TypeApp
						ELSE PROG.TypeApp 
						END

FROM DIST_REGIONAL REG INNER JOIN TERRITORY TR ON TR.REGIONAL_ID = REG.REGIONAL_ID
INNER JOIN DIST_DISTRIBUTOR DR ON DR.TERRITORY_ID = TR.TERRITORY_ID
INNER JOIN DIST_DISC_BRAND_LIST DDBL ON DR.DISTRIBUTOR_ID = DDBL.DISTRIBUTOR_ID 
INNER JOIN BRND_DISC_HEADER BDH ON BDH.IDApp = DDBL.FKApp
INNER JOIN BRND_DISC_LIST_BRAND BDLB ON BDLB.FKApp = BDH.IDApp
INNER JOIN BRND_BRAND BR ON BR.BRAND_ID = BDLB.BRAND_ID
LEFT OUTER JOIN(SELECT BR1.BRAND_ID, BDLP.BRANDPACK_ID,BP.BRANDPACK_NAME,BDLP.FKApp FROM BRND_BRANDPACK BP INNER JOIN BRND_DISC_LIST_BRANDPACK BDLP ON BDLP.BRANDPACK_ID = BP.BRANDPACK_ID
 INNER JOIN BRND_BRAND BR1 ON BR1.BRAND_ID = BP.BRAND_ID)LB
ON LB.FKApp = BDH.IDApp AND LB.BRAND_ID = BDLB.BRAND_ID
LEFT OUTER JOIN(SELECT FKApp,MoreThanQty,Disc,TypeApp,BRANDPACK_ID FROM BRND_DISC_PROG WHERE BRANDPACK_ID IS NOT NULL)PROG1
ON PROG1.BRANDPACK_ID = LB.BRANDPACK_ID AND PROG1.FKApp = BDH.IDApp
LEFT OUTER JOIN (SELECT FkApp,MoreThanQty,Disc,TypeApp,BRAND_ID FROM BRND_DISC_PROG WHERE BRAND_ID IS NOT NULL)PROG2
 ON PROG2.FKApp=BDH.IDApp AND PROG2.BRAND_ID = BDLB.BRAND_ID
LEFT OUTER JOIN (SELECT FkApp,MoreThanQty,Disc,TypeApp FROM BRND_DISC_PROG WHERE (BRAND_ID IS NULL AND BRANDPACK_ID IS NULL))PROG
 ON PROG.FKApp = BDH.IDApp';
 IF @PAR_COLUMNS = 'APPLY_DATE AND END_DATE' 
	BEGIN
		SET @QRY_WHERE = ' WHERE BDH.APPLY_DATE >= @V_START_DATE AND BDH.END_DATE <= @V_END_DATE' 
	END
ELSE IF @PAR_COLUMNS = 'APPLY_DATE'
	BEGIN 
		SET @QRY_WHERE = ' WHERE BDH.APPLY_DATE >= @V_START_DATE AND BDH.APPLY_DATE <= @V_END_DATE' 
	END
ELSE 
	BEGIN 
		SET @QRY_WHERE = ' WHERE BDH.END_DATE >= @V_START_DATE AND BDH.END_DATE <= @V_END_DATE'
	END
SET @QRY_FULL = @QRY_MAIN + @QRY_WHERE ;
IF @DISTRIBUTOR_ID IS NOT NULL
	SET @QRY_FULL = @QRY_FULL + ' AND DR.DISTRIBUTOR_ID = @V_DISTRIBUTOR_ID '
--EXECUTE sp_executesql @QRY_FULL,N'@V_START_DATE SMALLDATETIME,@V_END_DATE SMALLDATETIME,@V_DISTRIBUTOR_ID VARCHAR(50)',@V_START_DATE = @START_DATE,@V_END_DATE = @END_DATE,@V_DISTRIBUTOR_ID = @DISTRIBUTOR_ID
GO


IF EXISTS(SELECT NAME FROM SYS.OBJECTS WHERE NAME = 'Usp_Get_Report_DD_DR_All' AND TYPE = 'P')
DROP PROCEDURE Usp_Get_Report_DD_DR_All
GO
CREATE PROCEDURE Usp_Get_Report_DD_DR_All
@START_DATE SMALLDATETIME,
@END_DATE SMALLDATETIME,
@PAR_COLUMNS VARCHAR(50),
@DISTRIBUTOR_ID VARCHAR(50) = NULL
AS
SET NOCOUNT ON;
DECLARE @QRY_MAIN NVARCHAR(MAX),@QRY_WHERE NVARCHAR(300),@QRY_FULL NVARCHAR(MAX)
SET @QRY_MAIN = N'SELECT REGIONAL_AREA = ''ALL_REGIONALS'',TERRITORY_AREA = ''ALL_TERRITORIES'',PROGRAM_ID = CASE WHEN (BDH.PROGRAM_ID IS NOT NULL) THEN BDH.PROGRAM_ID
ELSE CONVERT(VARCHAR(100),BDH.IDApp) END,
BDH.PROGRAM_DESC,BDH.APPlY_DATE,BDH.END_DATE,
APPLY_TO = ''ALL_DISTRIBUTORS'',DISTRIBUTORS = '''',
BR.BRAND_NAME,ISNULL(LB.BRANDPACK_NAME,'''') AS BRANDPACK_NAME,
APPLY_TARGET_TO =  CASE WHEN (PROG1.BRANDPACK_ID IS NOT NULL) THEN ''CURRENT PACK SIZE'' 
						WHEN (PROG2.BRAND_ID IS NOT NULL) THEN ''ALL PACK SIZE OF CURRENT BRAND''
						ELSE ''ALL PRODUCT(S)'' 
						END,
TARGET_PO = CASE WHEN (PROG1.BRANDPACK_ID IS NOT NULL) THEN PROG1.MoreThanQty 
						WHEN (PROG2.BRAND_ID IS NOT NULL) THEN PROG2.MoreThanQty
						ELSE PROG.MoreThanQty 
						END,
DISC = CASE WHEN (PROG1.BRANDPACK_ID IS NOT NULL) THEN PROG1.Disc/100 
						WHEN (PROG2.BRAND_ID IS NOT NULL) THEN PROG2.Disc/100
						ELSE PROG.Disc/100 
						END,
DISC_TYPE = CASE WHEN (PROG1.BRANDPACK_ID IS NOT NULL) THEN PROG1.TypeApp 
						WHEN (PROG2.BRAND_ID IS NOT NULL) THEN PROG2.TypeApp
						ELSE PROG.TypeApp 
						END

FROM BRND_DISC_HEADER BDH INNER JOIN BRND_DISC_LIST_BRAND BDLB ON BDLB.FKApp = BDH.IDApp
INNER JOIN BRND_BRAND BR ON BR.BRAND_ID = BDLB.BRAND_ID
LEFT OUTER JOIN(SELECT BR1.BRAND_ID, BDLP.BRANDPACK_ID,BP.BRANDPACK_NAME,BDLP.FKApp FROM BRND_BRANDPACK BP INNER JOIN BRND_DISC_LIST_BRANDPACK BDLP ON BDLP.BRANDPACK_ID = BP.BRANDPACK_ID
 INNER JOIN BRND_BRAND BR1 ON BR1.BRAND_ID = BP.BRAND_ID)LB
ON LB.FKApp = BDH.IDApp AND LB.BRAND_ID = BDLB.BRAND_ID
LEFT OUTER JOIN(SELECT FKApp,MoreThanQty,Disc,TypeApp,BRANDPACK_ID FROM BRND_DISC_PROG WHERE BRANDPACK_ID IS NOT NULL)PROG1
ON PROG1.BRANDPACK_ID = LB.BRANDPACK_ID AND PROG1.FKApp = BDH.IDApp
LEFT OUTER JOIN (SELECT FkApp,MoreThanQty,Disc,TypeApp,BRAND_ID FROM BRND_DISC_PROG WHERE BRAND_ID IS NOT NULL)PROG2
 ON PROG2.FKApp=BDH.IDApp AND PROG2.BRAND_ID = BDLB.BRAND_ID
LEFT OUTER JOIN (SELECT FkApp,MoreThanQty,Disc,TypeApp FROM BRND_DISC_PROG WHERE (BRAND_ID IS NULL AND BRANDPACK_ID IS NULL))PROG
 ON PROG.FKApp = BDH.IDApp';
 IF @PAR_COLUMNS = 'APPLY_DATE AND END_DATE' 
	BEGIN
		SET @QRY_WHERE = ' WHERE BDH.APPLY_DATE >= @V_START_DATE AND BDH.END_DATE <= @V_END_DATE AND BDH.APPLY_TO = ''AL''' 
	END
ELSE IF @PAR_COLUMNS = 'APPLY_DATE'
	BEGIN 
		SET @QRY_WHERE = ' WHERE BDH.APPLY_DATE >= @V_START_DATE AND BDH.APPLY_DATE <= @V_END_DATE  AND BDH.APPLY_TO = ''AL''' 
	END
ELSE 
	BEGIN 
		SET @QRY_WHERE = ' WHERE BDH.END_DATE >= @V_START_DATE AND BDH.END_DATE <= @V_END_DATE AND BDH.APPLY_TO = ''AL'''
	END
SET @QRY_FULL = @QRY_MAIN + @QRY_WHERE ;
EXECUTE sp_executesql @QRY_FULL,N'@V_START_DATE SMALLDATETIME,@V_END_DATE SMALLDATETIME',@V_START_DATE = @START_DATE,@V_END_DATE = @END_DATE
GO

--EXEC Usp_Get_Report_DD_DR_All @PAR_COLUMNS = 'APPLY_DATE', @START_DATE = '05/01/2019',@END_DATE = '08/01/2019'

IF EXISTS(SELECT NAME FROM SYS.OBJECTS WHERE NAME = 'Usp_Get_Report_DD_DR_History' AND TYPE = 'P')
DROP PROCEDURE Usp_Get_Report_DD_DR_History
GO
CREATE PROCEDURE Usp_Get_Report_DD_DR_History
@DISTRIBUTOR_ID VARCHAR(50)
AS
SET NOCOUNT ON;
SELECT REG.REGIONAL_AREA,TR.TERRITORY_AREA,PROGRAM_ID = CASE WHEN (BDH.PROGRAM_ID IS NOT NULL) THEN BDH.PROGRAM_ID
ELSE CONVERT(VARCHAR(100),BDH.IDApp) END,
BDH.PROGRAM_DESC,BDH.APPlY_DATE,BDH.END_DATE,
APPLY_TO = 'CERTAIN DISTRIBUTORS',DISTRIBUTORS = DR.DISTRIBUTOR_NAME ,
BR.BRAND_NAME,ISNULL(LB.BRANDPACK_NAME,'') AS BRANDPACK_NAME,
APPLY_TARGET_TO =  CASE WHEN (PROG1.BRANDPACK_ID IS NOT NULL) THEN 'CURRENT PACK SIZE' 
						WHEN (PROG2.BRAND_ID IS NOT NULL) THEN 'ALL PACK SIZE OF CURRENT BRAND'
						ELSE 'ALL PRODUCT(S)' 
						END,
TARGET_PO = CASE WHEN (PROG1.BRANDPACK_ID IS NOT NULL) THEN PROG1.MoreThanQty 
						WHEN (PROG2.BRAND_ID IS NOT NULL) THEN PROG2.MoreThanQty
						ELSE PROG.MoreThanQty 
						END,
DISC = CASE WHEN (PROG1.BRANDPACK_ID IS NOT NULL) THEN PROG1.Disc/100 
						WHEN (PROG2.BRAND_ID IS NOT NULL) THEN PROG2.Disc/100
						ELSE PROG.Disc/100 
						END,
DISC_TYPE = CASE WHEN (PROG1.BRANDPACK_ID IS NOT NULL) THEN PROG1.TypeApp 
						WHEN (PROG2.BRAND_ID IS NOT NULL) THEN PROG2.TypeApp
						ELSE PROG.TypeApp 
						END
FROM DIST_REGIONAL REG INNER JOIN TERRITORY TR ON TR.REGIONAL_ID = REG.REGIONAL_ID
INNER JOIN DIST_DISTRIBUTOR DR ON DR.TERRITORY_ID = TR.TERRITORY_ID
INNER JOIN DIST_DISC_BRAND_LIST DDBL ON DR.DISTRIBUTOR_ID = DDBL.DISTRIBUTOR_ID 
INNER JOIN BRND_DISC_HEADER BDH ON BDH.IDApp = DDBL.FKApp
INNER JOIN BRND_DISC_LIST_BRAND BDLB ON BDLB.FKApp = BDH.IDApp
INNER JOIN BRND_BRAND BR ON BR.BRAND_ID = BDLB.BRAND_ID
LEFT OUTER JOIN(SELECT BR1.BRAND_ID, BDLP.BRANDPACK_ID,BP.BRANDPACK_NAME,BDLP.FKApp FROM BRND_BRANDPACK BP INNER JOIN BRND_DISC_LIST_BRANDPACK BDLP ON BDLP.BRANDPACK_ID = BP.BRANDPACK_ID
 INNER JOIN BRND_BRAND BR1 ON BR1.BRAND_ID = BP.BRAND_ID)LB
ON LB.FKApp = BDH.IDApp AND LB.BRAND_ID = BDLB.BRAND_ID
LEFT OUTER JOIN(SELECT FKApp,MoreThanQty,Disc,TypeApp,BRANDPACK_ID FROM BRND_DISC_PROG WHERE BRANDPACK_ID IS NOT NULL)PROG1
ON PROG1.BRANDPACK_ID = LB.BRANDPACK_ID AND PROG1.FKApp = BDH.IDApp
LEFT OUTER JOIN (SELECT FkApp,MoreThanQty,Disc,TypeApp,BRAND_ID FROM BRND_DISC_PROG WHERE BRAND_ID IS NOT NULL)PROG2
 ON PROG2.FKApp=BDH.IDApp AND PROG2.BRAND_ID = BDLB.BRAND_ID
LEFT OUTER JOIN (SELECT FkApp,MoreThanQty,Disc,TypeApp FROM BRND_DISC_PROG WHERE (BRAND_ID IS NULL AND BRANDPACK_ID IS NULL))PROG
 ON PROG.FKApp = BDH.IDApp 
 WHERE DDBL.DISTRIBUTOR_ID = @DISTRIBUTOR_ID AND BDH.APPLY_TO = 'CD'
 UNION
 SELECT REGIONAL_AREA = 'ALL_REGIONALS',TERRITORY_AREA = 'ALL_TERRITORIES',PROGRAM_ID = CASE WHEN (BDH.PROGRAM_ID IS NOT NULL) THEN BDH.PROGRAM_ID
ELSE CONVERT(VARCHAR(100),BDH.IDApp) END,
BDH.PROGRAM_DESC,BDH.APPlY_DATE,BDH.END_DATE,
APPLY_TO = 'ALL_DISTRIBUTORS',DISTRIBUTORS = '',
BR.BRAND_NAME,ISNULL(LB.BRANDPACK_NAME,'') AS BRANDPACK_NAME,
APPLY_TARGET_TO =  CASE WHEN (PROG1.BRANDPACK_ID IS NOT NULL) THEN 'CURRENT PACK SIZE' 
						WHEN (PROG2.BRAND_ID IS NOT NULL) THEN 'ALL PACK SIZE OF CURRENT BRAND'
						ELSE 'ALL PRODUCT(S)' 
						END,
TARGET_PO = CASE WHEN (PROG1.BRANDPACK_ID IS NOT NULL) THEN PROG1.MoreThanQty 
						WHEN (PROG2.BRAND_ID IS NOT NULL) THEN PROG2.MoreThanQty
						ELSE PROG.MoreThanQty 
						END,
DISC = CASE WHEN (PROG1.BRANDPACK_ID IS NOT NULL) THEN PROG1.Disc/100 
						WHEN (PROG2.BRAND_ID IS NOT NULL) THEN PROG2.Disc/100
						ELSE PROG.Disc/100 
						END,
DISC_TYPE = CASE WHEN (PROG1.BRANDPACK_ID IS NOT NULL) THEN PROG1.TypeApp 
						WHEN (PROG2.BRAND_ID IS NOT NULL) THEN PROG2.TypeApp
						ELSE PROG.TypeApp 
						END

FROM BRND_DISC_HEADER BDH INNER JOIN BRND_DISC_LIST_BRAND BDLB ON BDLB.FKApp = BDH.IDApp
INNER JOIN BRND_BRAND BR ON BR.BRAND_ID = BDLB.BRAND_ID
LEFT OUTER JOIN(SELECT BR1.BRAND_ID, BDLP.BRANDPACK_ID,BP.BRANDPACK_NAME,BDLP.FKApp FROM BRND_BRANDPACK BP INNER JOIN BRND_DISC_LIST_BRANDPACK BDLP ON BDLP.BRANDPACK_ID = BP.BRANDPACK_ID
 INNER JOIN BRND_BRAND BR1 ON BR1.BRAND_ID = BP.BRAND_ID)LB
ON LB.FKApp = BDH.IDApp AND LB.BRAND_ID = BDLB.BRAND_ID
LEFT OUTER JOIN(SELECT FKApp,MoreThanQty,Disc,TypeApp,BRANDPACK_ID FROM BRND_DISC_PROG WHERE BRANDPACK_ID IS NOT NULL)PROG1
ON PROG1.BRANDPACK_ID = LB.BRANDPACK_ID AND PROG1.FKApp = BDH.IDApp
LEFT OUTER JOIN (SELECT FkApp,MoreThanQty,Disc,TypeApp,BRAND_ID FROM BRND_DISC_PROG WHERE BRAND_ID IS NOT NULL)PROG2
 ON PROG2.FKApp=BDH.IDApp AND PROG2.BRAND_ID = BDLB.BRAND_ID
LEFT OUTER JOIN (SELECT FkApp,MoreThanQty,Disc,TypeApp FROM BRND_DISC_PROG WHERE (BRAND_ID IS NULL AND BRANDPACK_ID IS NULL))PROG
 ON PROG.FKApp = BDH.IDApp
 WHERE BDH.APPLY_TO = 'AL'
 GO
 --exec Usp_Get_Report_DD_DR_History @DISTRIBUTOR_ID = 'WIR001IDR'
--SELECT * FROM BRND_DISC_PROG WHERE FKApp = 121

--SELECT * FROM ORDR_OA_BRANDPACK_DISC WHERE RefOther = 121

--SELECT * FROM ORDR_OA_BRANDPACK_DISC WHERE GQSY_SGT_P_FLAG = 'ODR' AND OA_BRANDPACK_ID LIKE '%0001/NUF/PJA/VIII/19%'

--SELECT * FROM BRND_DISC_HEADER WHERE IDApp = 128

--SELECT * FROM BRND_DISC_HEADER WHERE PROGRAM_ID = '0204C/NI/IV/19'

--SELECT * FROM ORDR_OA_BRANDPACK_DISC WHERE RefOther NOT IN(SELECT IDApp FROM BRND_DISC_HEADER)
--AND RefOther > 0

--UPDATE ORDR_OA_BRANDPACK_DISC SET GQSY_SGT_P_FLAG = 'ODD', RefOther = 121 WHERE OA_BRANDPACK_DISC_ID = 102368

--1907-060-000400651907-06011030025GD

--009/SMA-NFM/VIII/2019-00040250009/SMA-NFM/VIII/201900075250MD

--UPDATE ORDR_OA_BRANDPACK_DISC SET RefOther = 151 WHERE OA_BRANDPACK_DISC_ID IN(102379,102380,102383,102381,102384,102382)
 --SELECT * FROM DIST_DISTRIBUTOR WHERE DISTRIBUTOR_NAME LIKE '%WIRA AGRI%'

 --SELECT * FROM ORDR_OA_BRANDPACK_DISC WHERE OA_BRANDPACK_DISC_ID =  102368