---------PROCEDURE UNTUK MEMBIKIN REPORT PER OA UNTUK DI PRINT DI OA_BRANDPACK-------

IF EXISTS(SELECT NAME FROM SYS.OBJECTS WHERE NAME = 'Usp_Create_View_Report_Per_OA_Ref_No' AND TYPE = 'P')
DROP PROCEDURE Usp_Create_View_Report_Per_OA_Ref_No
GO
CREATE PROCEDURE Usp_Create_View_Report_Per_OA_Ref_No
@OA_REF_NO VARCHAR(32)
AS
SET NOCOUNT ON;
EXECUTE sp_executesql  N'SELECT OPO.DISTRIBUTOR_ID,DR.DISTRIBUTOR_NAME,OPO.PO_REF_NO,OPO.PO_REF_DATE,
OOA.OA_ID AS OA_REF_NO,OOA.OA_DATE,BB.BRANDPACK_NAME,OOB.OA_ORIGINAL_QTY ,OOB.QTY_EVEN,
OOB.OA_PRICE_PERQTY AS PRICE,OOB.UNIT,OOB.REMARK,OA_DISC.REMAIND_QTY,OA_DISC.GIVEN_AGREEMENT,OA_DISC.[QUARTER],
OA_DISC.[SEMESTER],OA_DISC.YEARLY,OA_DISC.RPK,OA_DISC.CP_MRT,OA_DISC.DK,OA_DISC.CP_D,OA_DISC.CP_DK,OA_DISC.PKPP,OA_DISC.CP_R,
OA_DISC.OTHER,(OA_DISC.GIVEN_AGREEMENT * OOB.OA_PRICE_PERQTY) AS GIVEN_AMOUNT,
(OA_DISC.[QUARTER]* OOB.OA_PRICE_PERQTY) AS QUARTER_AMOUNT,
(OA_DISC.[SEMESTER] * OOB.OA_PRICE_PERQTY) AS SEMESTER_AMOUNT,
(OA_DISC.[YEARLY] * OOB.OA_PRICE_PERQTY) AS YEARLY_AMOUNT,
(OA_DISC.RPK * OOB.OA_PRICE_PERQTY) AS RPK_AMOUNT,
(OA_DISC.DK * OOB.OA_PRICE_PERQTY) AS DK_AMOUNT,
(OA_DISC.CP_D * OOB.OA_PRICE_PERQTY) AS CP_D_AMOUNT,
(OA_DISC.CP_DK * OOB.OA_PRICE_PERQTY) AS CP_DK_AMOUNT,
(OA_DISC.PKPP * OOB.OA_PRICE_PERQTY) AS PKPP_AMOUNT,
(OA_DISC.CP_R * OOB.OA_PRICE_PERQTY) AS CP_R_AMOUNT,
(OA_DISC.OTHER * OOB.OA_PRICE_PERQTY) AS OTHER_AMOUNT,
(OA_DISC.CP_MRT * OOB.OA_PRICE_PERQTY) AS CP_MRT_AMOUNT, 
(OOB.QTY_EVEN + ISNULL(OA_LEFT.TOTAL_DISC,0)) * OOB.OA_PRICE_PERQTY AS OA_AMOUNT,
((T_DISC.TOTAL_DISC - ISNULL(ADJUST.ADJUST_QTY,0)) * OOB.OA_PRICE_PERQTY) AS TOTAL_DISC_AMOUNT,
ISNULL(ADJUST.ADJUST_QTY,0) AS ADJUST_QTY, ISNULL(ADJUST.ADJUST_QTY,0) * OOB.OA_PRICE_PERQTY AS ADJUST_AMOUNT
FROM ORDR_PURCHASE_ORDER OPO INNER JOIN DIST_DISTRIBUTOR DR ON OPO.DISTRIBUTOR_ID = DR.DISTRIBUTOR_ID
 INNER JOIN ORDR_PO_BRANDPACK OPB ON OPB.PO_REF_NO = OPO.PO_REF_NO INNER JOIN ORDR_ORDER_ACCEPTANCE OOA
ON OOA.PO_REF_NO = OPB.PO_REF_NO
INNER JOIN ORDR_OA_BRANDPACK OOB ON OOB.PO_BRANDPACK_ID = OPB.PO_BRANDPACK_ID AND OOB.OA_ID = OOA.OA_ID
INNER JOIN BRND_BRANDPACK BB ON OPB.BRANDPACK_ID = BB.BRANDPACK_ID --INNER JOIN ORDR_OA_BRANDPACK_DISC OOBD ON OOBD.OA_BRANDPACK_ID = OOB.OA_BRANDPACK_ID
LEFT OUTER JOIN
               (
                 SELECT OA_BRANDPACK_ID,
                 SUM(CASE GQSY_SGT_P_FLAG WHEN ''RMOA'' THEN DISC_QTY ELSE 0 END)AS REMAIND_QTY,
                 SUM(CASE GQSY_SGT_P_FLAG WHEN ''G''  THEN DISC_QTY ELSE 0 END)AS GIVEN_AGREEMENT, 
            	 SUM(CASE GQSY_SGT_P_FLAG WHEN ''Q1'' THEN DISC_QTY WHEN ''Q2'' THEN DISC_QTY WHEN ''Q3'' THEN DISC_QTY
                                     	  WHEN ''Q4'' THEN DISC_QTY ELSE 0 END)AS [QUARTER],
				 SUM(CASE GQSY_SGT_P_FLAG WHEN ''S1'' THEN DISC_QTY WHEN ''S2'' THEN DISC_QTY ELSE 0 END)AS [SEMESTER], 
           		 SUM(CASE GQSY_SGT_P_FLAG WHEN ''Y''  THEN DISC_QTY ELSE 0 END)AS YEARLY, 
           		 SUM(CASE GQSY_SGT_P_FLAG WHEN ''MG'' THEN DISC_QTY ELSE 0 END)AS RPK,
				 SUM(CASE GQSY_SGT_P_FLAG WHEN ''DK'' THEN DISC_QTY WHEN ''DN'' THEN DISC_QTY ELSE 0 END)AS DK,
           		 SUM(CASE GQSY_SGT_P_FLAG WHEN ''CP'' THEN DISC_QTY  WHEN ''TD'' THEN DISC_QTY WHEN ''CA'' THEN DISC_QTY ELSE 0 END)AS CP_D,
				 SUM(CASE GQSY_SGT_P_FLAG WHEN ''CS'' THEN DISC_QTY  WHEN ''TS'' THEN DISC_QTY ELSE 0 END)AS CP_DK,
				 SUM(CASE GQSY_SGT_P_FLAG WHEN ''CT'' THEN DISC_QTY WHEN ''CD'' THEN DISC_QTY ELSE 0 END)AS CP_MRT,
				 SUM(CASE GQSY_SGT_P_FLAG WHEN ''KP'' THEN DISC_QTY ELSE 0 END)AS PKPP,
				 SUM(CASE GQSY_SGT_P_FLAG WHEN ''CR'' THEN DISC_QTY ELSE 0 END) AS CP_R,
				 SUM(CASE GQSY_SGT_P_FLAG WHEN ''O''  THEN DISC_QTY WHEN ''ODD''  THEN DISC_QTY WHEN ''ODR''  THEN DISC_QTY WHEN ''OCBD'' THEN DISC_QTY ELSE 0 END)AS OTHER
				 FROM ORDR_OA_BRANDPACK_DISC GROUP BY OA_BRANDPACK_ID
           	)OA_DISC ON OA_DISC.OA_BRANDPACK_ID = OOB.OA_BRANDPACK_ID
LEFT OUTER JOIN(
                 SELECT OA_BRANDPACK_ID,ISNULL(SUM(DISC_QTY),0)AS TOTAL_DISC FROM ORDR_OA_BRANDPACK_DISC 
                 WHERE GQSY_SGT_P_FLAG != ''RMOA''
                 GROUP BY OA_BRANDPACK_ID
                )T_DISC ON OOB.OA_BRANDPACK_ID = T_DISC.OA_BRANDPACK_ID
LEFT OUTER JOIN( 
                 SELECT OA_BRANDPACK_ID,ISNULL(SUM(DISC_QTY),0)AS TOTAL_DISC FROM ORDR_OA_BRANDPACK_DISC 
                 WHERE GQSY_SGT_P_FLAG = ''RMOA''
                 GROUP BY OA_BRANDPACK_ID
                )OA_LEFT ON OA_LEFT.OA_BRANDPACK_ID = OOB.OA_BRANDPACK_ID 
LEFT OUTER JOIN (
				SELECT OOBD.OA_BRANDPACK_ID,ISNULL(SUM(AT.ADJ_DISC_QTY),0) AS ADJUST_QTY FROM ORDR_OA_BRANDPACK_DISC OOBD INNER JOIN ADJUSTMENT_TRANS AT 
				ON AT.OA_BRANDPACK_DISC_ID = OOBD.OA_BRANDPACK_DISC_ID WHERE OOBD.OA_BRANDPACK_ID = ANY(SELECT OA_BRANDPACK_ID FROM ORDR_OA_BRANDPACK WHERE OA_ID = @V_OA_REF_NO)
				GROUP BY OOBD.OA_BRANDPACK_ID
				)ADJUST
ON ADJUST.OA_BRANDPACK_ID = OOB.OA_BRANDPACK_ID				
WHERE OOA.OA_ID = @V_OA_REF_NO OPTION(KEEP PLAN)',N'@V_OA_REF_NO VARCHAR(32)',@V_OA_REF_NO = @OA_REF_NO
GO

--EXEC Usp_Create_View_Report_Per_OA_Ref_No @OA_REF_NO = 'SAP/5021/09-2595'

--------REPORT OC 2019-----------------(tidak ada discount)------------------------

IF EXISTS(SELECT NAME FROM SYS.OBJECTS WHERE NAME = 'Usp_Get_DOC' AND TYPE = 'P')
DROP PROCEDURE Usp_Get_DOC
GO
CREATE PROCEDURE Usp_Get_DOC
@OA_REF_NO VARCHAR(32)

AS

SET ARITHABORT OFF;   -- Default 
        SET ANSI_WARNINGS OFF
SELECT PO.DISTRIBUTOR_ID,DR.DISTRIBUTOR_NAME,PO.PO_REF_NO,PO.PO_REF_DATE,
OA.OA_ID AS OA_REF_NO,OA.OA_DATE,BP.BRANDPACK_NAME,OB.OA_ORIGINAL_QTY,OB.QTY_EVEN,
OB.OA_PRICE_PERQTY AS PRICE,OB.UNIT,OB.REMARK,(OB.QTY_EVEN + ISNULL(OA_LEFT.TOTAL_DISC,0)) * OB.OA_PRICE_PERQTY AS OA_AMOUNT,
ISNULL(T_DISC.TOTAL_DISC,0) AS TOTAL_DISC ,ISNULL((T_DISC.TOTAL_DISC  * OB.OA_PRICE_PERQTY),0) AS TOTAL_DISC_AMOUNT,
(OB.QTY_EVEN + ISNULL(OA_LEFT.TOTAL_DISC,0) + ISNULL(T_DISC.TOTAL_DISC,0)) AS TOTAL_DELIVERY,
(OB.QTY_EVEN + ISNULL(OA_LEFT.TOTAL_DISC,0) + ISNULL(T_DISC.TOTAL_DISC,0)) * OB.OA_PRICE_PERQTY AS TOTAL_DELIVERY_AMOUNT,
ISNULL(((OB.QTY_EVEN + ISNULL(OA_LEFT.TOTAL_DISC,0)) * OB.OA_PRICE_PERQTY)/(OB.QTY_EVEN + ISNULL(OA_LEFT.TOTAL_DISC,0) + ISNULL(T_DISC.TOTAL_DISC,0)),0) AS NET_PRICE
FROM ORDR_PURCHASE_ORDER PO INNER JOIN DIST_DISTRIBUTOR DR ON PO.DISTRIBUTOR_ID = DR.DISTRIBUTOR_ID
INNER JOIN ORDR_PO_BRANDPACK PB ON PB.PO_REF_NO = PO.PO_REF_NO INNER JOIN ORDR_ORDER_ACCEPTANCE OA
ON OA.PO_REF_NO = PB.PO_REF_NO AND OA.PO_REF_NO = PO.PO_REF_NO
INNER JOIN ORDR_OA_BRANDPACK OB ON OB.OA_ID = OA.OA_ID AND OB.PO_BRANDPACK_ID = PB.PO_BRANDPACK_ID
INNER JOIN BRND_BRANDPACK BP ON PB.BRANDPACK_ID = BP.BRANDPACK_ID 
LEFT OUTER JOIN(
                 SELECT OA_BRANDPACK_ID,ISNULL(SUM(DISC_QTY),0)AS TOTAL_DISC FROM ORDR_OA_BRANDPACK_DISC 
                 WHERE GQSY_SGT_P_FLAG != 'RMOA'
                 GROUP BY OA_BRANDPACK_ID
                )T_DISC ON OB.OA_BRANDPACK_ID = T_DISC.OA_BRANDPACK_ID
LEFT OUTER JOIN( 
                 SELECT OA_BRANDPACK_ID,ISNULL(SUM(DISC_QTY),0)AS TOTAL_DISC FROM ORDR_OA_BRANDPACK_DISC 
                 WHERE GQSY_SGT_P_FLAG = 'RMOA'
                 GROUP BY OA_BRANDPACK_ID
                )OA_LEFT ON OA_LEFT.OA_BRANDPACK_ID = OB.OA_BRANDPACK_ID 
WHERE OA.OA_ID = @OA_REF_NO

GO

EXEC Usp_Get_DOC @OA_REF_NO = '465/JA/PLG/XI/2020A-00047586' 

--SELECT 1836.000 * 40392.156862 AS TEST
---------------PROCEDURE UNTUK MENGECURE REPOT OA--------------------------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Create_View_OA_Report' AND TYPE = 'P')
DROP PROCEDURE Usp_Create_View_OA_Report
GO
CREATE PROCEDURE Usp_Create_View_OA_Report
@FROM_OADATE DATETIME,
@UNTIL_OADATE DATETIME,
@FROM_PODATE DATETIME,
@UNTIL_PODATE DATETIME
AS
IF ((@FROM_OADATE IS NOT NULL) AND (@UNTIL_OADATE IS NOT NULL))
   BEGIN
	SELECT DIST_DISTRIBUTOR.DISTRIBUTOR_ID,DIST_DISTRIBUTOR.DISTRIBUTOR_NAME,ORDR_PURCHASE_ORDER.PO_REF_NO,
	ORDR_PURCHASE_ORDER.PO_REF_DATE,BRND_BRAND.BRAND_NAME,BRND_BRANDPACK.BRANDPACK_NAME,ORDR_OA_BRANDPACK.OA_PRICE_PERQTY AS PRICE,
	(SELECT ISNULL(SUM(ORDR_OA_REMAINDING.QTY),0) FROM ORDR_OA_REMAINDING WHERE OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID)  AS REMAINDING,
	CAST((SELECT ISNULL(SUM(ORDR_OA_REMAINDING.QTY),0) FROM ORDR_OA_REMAINDING WHERE OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID)AS DECIMAL(18,3)) * ORDR_OA_BRANDPACK.OA_PRICE_PERQTY AS REMAINDING_AMOUNT,
	ORDR_PO_BRANDPACK.PO_ORIGINAL_QTY,
	ORDR_PO_BRANDPACK.PO_ORIGINAL_QTY * ORDR_PO_BRANDPACK.PO_PRICE_PERQTY AS PO_AMOUNT_QTY,ORDR_ORDER_ACCEPTANCE.OA_ID AS OA_REF_NO,
	ORDR_ORDER_ACCEPTANCE.OA_DATE,ORDR_OA_BRANDPACK.QTY_EVEN + (SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC WHERE GQSY_SGT_P_FLAG = 'RMOA'
	 AND OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID) AS OA_QTY,(ORDR_OA_BRANDPACK.QTY_EVEN + (SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC WHERE GQSY_SGT_P_FLAG = 'RMOA'
	 AND OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID)) * ORDR_OA_BRANDPACK.OA_PRICE_PERQTY AS OA_AMOUNT_QTY,
	ORDR_OA_BRANDPACK.AGREE_DISC_QTY + ORDR_OA_BRANDPACK.PROG_DISC_QTY + ORDR_OA_BRANDPACK.PROJ_DISC_QTY + ORDR_OA_BRANDPACK.OTHER_DISC_QTY AS DISC_QTY,
	(ORDR_OA_BRANDPACK.AGREE_DISC_QTY + ORDR_OA_BRANDPACK.PROG_DISC_QTY + ORDR_OA_BRANDPACK.PROJ_DISC_QTY + ORDR_OA_BRANDPACK.OTHER_DISC_QTY) * ORDR_OA_BRANDPACK.OA_PRICE_PERQTY AS DISC_AMOUNT_QTY,
	ORDR_OA_BRANDPACK.QTY_EVEN + (SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC WHERE GQSY_SGT_P_FLAG = 'RMOA'
	 AND OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID) + ORDR_OA_BRANDPACK.AGREE_DISC_QTY + 
	ORDR_OA_BRANDPACK.PROG_DISC_QTY + ORDR_OA_BRANDPACK.PROJ_DISC_QTY + ORDR_OA_BRANDPACK.OTHER_DISC_QTY AS TOTAL,
	cast((ORDR_OA_BRANDPACK.QTY_EVEN + (SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC WHERE GQSY_SGT_P_FLAG = 'RMOA'
	 AND OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID) + ORDR_OA_BRANDPACK.AGREE_DISC_QTY + 
	ORDR_OA_BRANDPACK.PROG_DISC_QTY + ORDR_OA_BRANDPACK.PROJ_DISC_QTY + ORDR_OA_BRANDPACK.OTHER_DISC_QTY)as DECIMAL(14,3)) * ORDR_OA_BRANDPACK.OA_PRICE_PERQTY AS TOTAL_AMOUNT_DELIVERY,
	(cast((ORDR_OA_BRANDPACK.QTY_EVEN + (SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC WHERE GQSY_SGT_P_FLAG = 'RMOA'
	 AND OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID) + ORDR_OA_BRANDPACK.AGREE_DISC_QTY +
	ORDR_OA_BRANDPACK.PROG_DISC_QTY + ORDR_OA_BRANDPACK.PROJ_DISC_QTY + ORDR_OA_BRANDPACK.OTHER_DISC_QTY)as DECIMAL(14,3)) * ORDR_OA_BRANDPACK.OA_PRICE_PERQTY) - 
	((ORDR_OA_BRANDPACK.AGREE_DISC_QTY + ORDR_OA_BRANDPACK.PROG_DISC_QTY + ORDR_OA_BRANDPACK.PROJ_DISC_QTY + ORDR_OA_BRANDPACK.OTHER_DISC_QTY) * ORDR_OA_BRANDPACK.OA_PRICE_PERQTY) AS TOTAL_AMOUNT_SALES
	--,ORDR_OA_BRANDPACK.REMARK
	FROM DIST_DISTRIBUTOR,ORDR_PURCHASE_ORDER,ORDR_PO_BRANDPACK,ORDR_ORDER_ACCEPTANCE,BRND_BRANDPACK,BRND_BRAND,ORDR_OA_BRANDPACK
	WHERE ORDR_PURCHASE_ORDER.DISTRIBUTOR_ID = DIST_DISTRIBUTOR.DISTRIBUTOR_ID
	AND ORDR_OA_BRANDPACK.OA_ID = ORDR_ORDER_ACCEPTANCE.OA_ID AND ORDR_OA_BRANDPACK.PO_BRANDPACK_ID
	= ORDR_PO_BRANDPACK.PO_BRANDPACK_ID AND ORDR_ORDER_ACCEPTANCE.PO_REF_NO = ORDR_PO_BRANDPACK.PO_REF_NO
	AND ORDR_PO_BRANDPACK.PO_REF_NO = ORDR_PURCHASE_ORDER.PO_REF_NO
	AND ORDR_PO_BRANDPACK.BRANDPACK_ID = BRND_BRANDPACK.BRANDPACK_ID
	AND BRND_BRANDPACK.BRAND_ID = BRND_BRAND.BRAND_ID
	AND ORDR_ORDER_ACCEPTANCE.OA_DATE >= @FROM_OADATE AND ORDR_ORDER_ACCEPTANCE.OA_DATE <= @UNTIL_OADATE
   END  
ELSE IF (@FROM_OADATE IS NOT NULL)
   BEGIN
	SELECT DIST_DISTRIBUTOR.DISTRIBUTOR_ID,DIST_DISTRIBUTOR.DISTRIBUTOR_NAME,ORDR_PURCHASE_ORDER.PO_REF_NO,
	ORDR_PURCHASE_ORDER.PO_REF_DATE,BRND_BRAND.BRAND_NAME,BRND_BRANDPACK.BRANDPACK_NAME,
	ORDR_OA_BRANDPACK.OA_PRICE_PERQTY AS PRICE,
	(SELECT ISNULL(SUM(ORDR_OA_REMAINDING.QTY),0) FROM ORDR_OA_REMAINDING WHERE OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID)  AS REMAINDING,
	CAST((SELECT ISNULL(SUM(ORDR_OA_REMAINDING.QTY),0) FROM ORDR_OA_REMAINDING WHERE OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID)AS DECIMAL(18,3)) * ORDR_OA_BRANDPACK.OA_PRICE_PERQTY AS REMAINDING_AMOUNT,
	ORDR_PO_BRANDPACK.PO_ORIGINAL_QTY,
		ORDR_PO_BRANDPACK.PO_ORIGINAL_QTY * ORDR_PO_BRANDPACK.PO_PRICE_PERQTY AS PO_AMOUNT_QTY,ORDR_ORDER_ACCEPTANCE.OA_ID AS OA_REF_NO,
	ORDR_ORDER_ACCEPTANCE.OA_DATE,ORDR_OA_BRANDPACK.QTY_EVEN + (SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC WHERE GQSY_SGT_P_FLAG = 'RMOA'
	 AND OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID) AS OA_QTY,(ORDR_OA_BRANDPACK.QTY_EVEN + (SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC WHERE GQSY_SGT_P_FLAG = 'RMOA'
	 AND OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID)) * ORDR_OA_BRANDPACK.OA_PRICE_PERQTY AS OA_AMOUNT_QTY,
	ORDR_OA_BRANDPACK.AGREE_DISC_QTY + ORDR_OA_BRANDPACK.PROG_DISC_QTY + ORDR_OA_BRANDPACK.PROJ_DISC_QTY + ORDR_OA_BRANDPACK.OTHER_DISC_QTY AS DISC_QTY,
	(ORDR_OA_BRANDPACK.AGREE_DISC_QTY + ORDR_OA_BRANDPACK.PROG_DISC_QTY + ORDR_OA_BRANDPACK.PROJ_DISC_QTY + ORDR_OA_BRANDPACK.OTHER_DISC_QTY) * ORDR_OA_BRANDPACK.OA_PRICE_PERQTY AS DISC_AMOUNT_QTY,
	ORDR_OA_BRANDPACK.QTY_EVEN + (SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC WHERE GQSY_SGT_P_FLAG = 'RMOA'
	 AND OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID) + ORDR_OA_BRANDPACK.AGREE_DISC_QTY + 
	ORDR_OA_BRANDPACK.PROG_DISC_QTY + ORDR_OA_BRANDPACK.PROJ_DISC_QTY + ORDR_OA_BRANDPACK.OTHER_DISC_QTY AS TOTAL,
	cast((ORDR_OA_BRANDPACK.QTY_EVEN + (SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC WHERE GQSY_SGT_P_FLAG = 'RMOA'
	 AND OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID) + ORDR_OA_BRANDPACK.AGREE_DISC_QTY + 
	ORDR_OA_BRANDPACK.PROG_DISC_QTY + ORDR_OA_BRANDPACK.PROJ_DISC_QTY + ORDR_OA_BRANDPACK.OTHER_DISC_QTY)as DECIMAL(14,3)) * ORDR_OA_BRANDPACK.OA_PRICE_PERQTY AS TOTAL_AMOUNT_DELIVERY,
	(cast((ORDR_OA_BRANDPACK.QTY_EVEN + (SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC WHERE GQSY_SGT_P_FLAG = 'RMOA'
	 AND OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID) + ORDR_OA_BRANDPACK.AGREE_DISC_QTY +
	ORDR_OA_BRANDPACK.PROG_DISC_QTY + ORDR_OA_BRANDPACK.PROJ_DISC_QTY + ORDR_OA_BRANDPACK.OTHER_DISC_QTY)as DECIMAL(14,3)) * ORDR_OA_BRANDPACK.OA_PRICE_PERQTY) - 
	((ORDR_OA_BRANDPACK.AGREE_DISC_QTY + ORDR_OA_BRANDPACK.PROG_DISC_QTY + ORDR_OA_BRANDPACK.PROJ_DISC_QTY + ORDR_OA_BRANDPACK.OTHER_DISC_QTY) * ORDR_OA_BRANDPACK.OA_PRICE_PERQTY) AS TOTAL_AMOUNT_SALES
	--,ORDR_OA_BRANDPACK.REMARK
	FROM DIST_DISTRIBUTOR,ORDR_PURCHASE_ORDER,ORDR_PO_BRANDPACK,ORDR_OA_BRANDPACK,ORDR_ORDER_ACCEPTANCE,BRND_BRAND,BRND_BRANDPACK
	WHERE ORDR_PURCHASE_ORDER.DISTRIBUTOR_ID = DIST_DISTRIBUTOR.DISTRIBUTOR_ID
	AND ORDR_OA_BRANDPACK.OA_ID = ORDR_ORDER_ACCEPTANCE.OA_ID AND ORDR_OA_BRANDPACK.PO_BRANDPACK_ID
	= ORDR_PO_BRANDPACK.PO_BRANDPACK_ID AND ORDR_ORDER_ACCEPTANCE.PO_REF_NO = ORDR_PO_BRANDPACK.PO_REF_NO
	AND ORDR_PO_BRANDPACK.PO_REF_NO = ORDR_PURCHASE_ORDER.PO_REF_NO
	AND ORDR_PO_BRANDPACK.BRANDPACK_ID = BRND_BRANDPACK.BRANDPACK_ID
	AND BRND_BRANDPACK.BRAND_ID = BRND_BRAND.BRAND_ID
	AND ORDR_ORDER_ACCEPTANCE.OA_DATE >= @FROM_OADATE
   END
ELSE IF (@UNTIL_OADATE IS NOT NULL)
     BEGIN
	SELECT DIST_DISTRIBUTOR.DISTRIBUTOR_ID,DIST_DISTRIBUTOR.DISTRIBUTOR_NAME,ORDR_PURCHASE_ORDER.PO_REF_NO,
	ORDR_PURCHASE_ORDER.PO_REF_DATE,BRND_BRAND.BRAND_NAME,BRND_BRANDPACK.BRANDPACK_NAME,
	ORDR_OA_BRANDPACK.OA_PRICE_PERQTY AS PRICE,
	(SELECT ISNULL(SUM(ORDR_OA_REMAINDING.QTY),0) FROM ORDR_OA_REMAINDING WHERE OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID)  AS REMAINDING,
	CAST((SELECT ISNULL(SUM(ORDR_OA_REMAINDING.QTY),0) FROM ORDR_OA_REMAINDING WHERE OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID)AS DECIMAL(18,3)) * ORDR_OA_BRANDPACK.OA_PRICE_PERQTY AS REMAINDING_AMOUNT,
	ORDR_PO_BRANDPACK.PO_ORIGINAL_QTY,
		ORDR_PO_BRANDPACK.PO_ORIGINAL_QTY * ORDR_PO_BRANDPACK.PO_PRICE_PERQTY AS PO_AMOUNT_QTY,ORDR_ORDER_ACCEPTANCE.OA_ID AS OA_REF_NO,
	ORDR_ORDER_ACCEPTANCE.OA_DATE,ORDR_OA_BRANDPACK.QTY_EVEN + (SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC WHERE GQSY_SGT_P_FLAG = 'RMOA'
	 AND OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID) AS OA_QTY,(ORDR_OA_BRANDPACK.QTY_EVEN + (SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC WHERE GQSY_SGT_P_FLAG = 'RMOA'
	 AND OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID)) * ORDR_OA_BRANDPACK.OA_PRICE_PERQTY AS OA_AMOUNT_QTY,
	ORDR_OA_BRANDPACK.AGREE_DISC_QTY + ORDR_OA_BRANDPACK.PROG_DISC_QTY + ORDR_OA_BRANDPACK.PROJ_DISC_QTY + ORDR_OA_BRANDPACK.OTHER_DISC_QTY AS DISC_QTY,
	(ORDR_OA_BRANDPACK.AGREE_DISC_QTY + ORDR_OA_BRANDPACK.PROG_DISC_QTY + ORDR_OA_BRANDPACK.PROJ_DISC_QTY + ORDR_OA_BRANDPACK.OTHER_DISC_QTY) * ORDR_OA_BRANDPACK.OA_PRICE_PERQTY AS DISC_AMOUNT_QTY,
	ORDR_OA_BRANDPACK.QTY_EVEN + (SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC WHERE GQSY_SGT_P_FLAG = 'RMOA'
	 AND OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID)+ ORDR_OA_BRANDPACK.AGREE_DISC_QTY + 
	ORDR_OA_BRANDPACK.PROG_DISC_QTY + ORDR_OA_BRANDPACK.PROJ_DISC_QTY + ORDR_OA_BRANDPACK.OTHER_DISC_QTY AS TOTAL,
	cast((ORDR_OA_BRANDPACK.QTY_EVEN + (SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC WHERE GQSY_SGT_P_FLAG = 'RMOA'
	 AND OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID) + ORDR_OA_BRANDPACK.AGREE_DISC_QTY + 
	ORDR_OA_BRANDPACK.PROG_DISC_QTY + ORDR_OA_BRANDPACK.PROJ_DISC_QTY + ORDR_OA_BRANDPACK.OTHER_DISC_QTY)as DECIMAL(14,3)) * ORDR_OA_BRANDPACK.OA_PRICE_PERQTY AS TOTAL_AMOUNT_DELIVERY,
	(cast((ORDR_OA_BRANDPACK.QTY_EVEN + (SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC WHERE GQSY_SGT_P_FLAG = 'RMOA'
	 AND OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID) + ORDR_OA_BRANDPACK.AGREE_DISC_QTY +
	ORDR_OA_BRANDPACK.PROG_DISC_QTY + ORDR_OA_BRANDPACK.PROJ_DISC_QTY + ORDR_OA_BRANDPACK.OTHER_DISC_QTY)as DECIMAL(14,3)) * ORDR_OA_BRANDPACK.OA_PRICE_PERQTY) - 
	((ORDR_OA_BRANDPACK.AGREE_DISC_QTY + ORDR_OA_BRANDPACK.PROG_DISC_QTY + ORDR_OA_BRANDPACK.PROJ_DISC_QTY + ORDR_OA_BRANDPACK.OTHER_DISC_QTY) * ORDR_OA_BRANDPACK.OA_PRICE_PERQTY) AS TOTAL_AMOUNT_SALES
	--,ORDR_OA_BRANDPACK.REMARK
	FROM DIST_DISTRIBUTOR,ORDR_PURCHASE_ORDER,ORDR_PO_BRANDPACK,ORDR_OA_BRANDPACK,ORDR_ORDER_ACCEPTANCE,BRND_BRAND,BRND_BRANDPACK
	WHERE ORDR_PURCHASE_ORDER.DISTRIBUTOR_ID = DIST_DISTRIBUTOR.DISTRIBUTOR_ID
	AND ORDR_OA_BRANDPACK.OA_ID = ORDR_ORDER_ACCEPTANCE.OA_ID AND ORDR_OA_BRANDPACK.PO_BRANDPACK_ID
	= ORDR_PO_BRANDPACK.PO_BRANDPACK_ID AND ORDR_ORDER_ACCEPTANCE.PO_REF_NO = ORDR_PO_BRANDPACK.PO_REF_NO
	AND ORDR_PO_BRANDPACK.PO_REF_NO = ORDR_PURCHASE_ORDER.PO_REF_NO
	AND ORDR_PO_BRANDPACK.BRANDPACK_ID = BRND_BRANDPACK.BRANDPACK_ID
	AND BRND_BRANDPACK.BRAND_ID = BRND_BRAND.BRAND_ID
	AND ORDR_ORDER_ACCEPTANCE.OA_DATE <= @UNTIL_OADATE
     END
ELSE IF ((@FROM_PODATE IS NOT NULL) AND (@UNTIL_PODATE IS NOT NULL))
     BEGIN	
	SELECT DIST_DISTRIBUTOR.DISTRIBUTOR_ID,DIST_DISTRIBUTOR.DISTRIBUTOR_NAME,ORDR_PURCHASE_ORDER.PO_REF_NO,
	ORDR_PURCHASE_ORDER.PO_REF_DATE,BRND_BRAND.BRAND_NAME,BRND_BRANDPACK.BRANDPACK_NAME,
	ORDR_OA_BRANDPACK.OA_PRICE_PERQTY AS PRICE,
	(SELECT ISNULL(SUM(ORDR_OA_REMAINDING.QTY),0) FROM ORDR_OA_REMAINDING WHERE OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID)  AS REMAINDING,
	CAST((SELECT ISNULL(SUM(ORDR_OA_REMAINDING.QTY),0) FROM ORDR_OA_REMAINDING WHERE OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID)AS DECIMAL(18,3)) * ORDR_OA_BRANDPACK.OA_PRICE_PERQTY AS REMAINDING_AMOUNT,
	ORDR_PO_BRANDPACK.PO_ORIGINAL_QTY,
	ORDR_PO_BRANDPACK.PO_ORIGINAL_QTY * ORDR_PO_BRANDPACK.PO_PRICE_PERQTY AS PO_AMOUNT_QTY,ORDR_ORDER_ACCEPTANCE.OA_ID AS OA_REF_NO,
	ORDR_ORDER_ACCEPTANCE.OA_DATE,ORDR_OA_BRANDPACK.QTY_EVEN + (SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC WHERE GQSY_SGT_P_FLAG = 'RMOA'
	 AND OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID) AS OA_QTY,(ORDR_OA_BRANDPACK.QTY_EVEN + (SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC WHERE GQSY_SGT_P_FLAG = 'RMOA'
	 AND OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID)) * ORDR_OA_BRANDPACK.OA_PRICE_PERQTY AS OA_AMOUNT_QTY,
	ORDR_OA_BRANDPACK.AGREE_DISC_QTY + ORDR_OA_BRANDPACK.PROG_DISC_QTY + ORDR_OA_BRANDPACK.PROJ_DISC_QTY + ORDR_OA_BRANDPACK.OTHER_DISC_QTY AS DISC_QTY,
	(ORDR_OA_BRANDPACK.AGREE_DISC_QTY + ORDR_OA_BRANDPACK.PROG_DISC_QTY + ORDR_OA_BRANDPACK.PROJ_DISC_QTY + ORDR_OA_BRANDPACK.OTHER_DISC_QTY) * ORDR_OA_BRANDPACK.OA_PRICE_PERQTY AS DISC_AMOUNT_QTY,
	ORDR_OA_BRANDPACK.QTY_EVEN + (SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC WHERE GQSY_SGT_P_FLAG = 'RMOA'
	 AND OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID) + ORDR_OA_BRANDPACK.AGREE_DISC_QTY + 
	ORDR_OA_BRANDPACK.PROG_DISC_QTY + ORDR_OA_BRANDPACK.PROJ_DISC_QTY + ORDR_OA_BRANDPACK.OTHER_DISC_QTY AS TOTAL,
	cast((ORDR_OA_BRANDPACK.QTY_EVEN + (SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC WHERE GQSY_SGT_P_FLAG = 'RMOA'
	 AND OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID) + ORDR_OA_BRANDPACK.AGREE_DISC_QTY + 
	ORDR_OA_BRANDPACK.PROG_DISC_QTY + ORDR_OA_BRANDPACK.PROJ_DISC_QTY + ORDR_OA_BRANDPACK.OTHER_DISC_QTY)as DECIMAL(14,3)) * ORDR_OA_BRANDPACK.OA_PRICE_PERQTY AS TOTAL_AMOUNT_DELIVERY,
	(cast((ORDR_OA_BRANDPACK.QTY_EVEN + (SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC WHERE GQSY_SGT_P_FLAG = 'RMOA'
	 AND OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID) + ORDR_OA_BRANDPACK.AGREE_DISC_QTY +
	ORDR_OA_BRANDPACK.PROG_DISC_QTY + ORDR_OA_BRANDPACK.PROJ_DISC_QTY + ORDR_OA_BRANDPACK.OTHER_DISC_QTY)as DECIMAL(14,3)) * ORDR_OA_BRANDPACK.OA_PRICE_PERQTY) - 
	((ORDR_OA_BRANDPACK.AGREE_DISC_QTY + ORDR_OA_BRANDPACK.PROG_DISC_QTY + ORDR_OA_BRANDPACK.PROJ_DISC_QTY + ORDR_OA_BRANDPACK.OTHER_DISC_QTY) * ORDR_OA_BRANDPACK.OA_PRICE_PERQTY) AS TOTAL_AMOUNT_SALES
	--,ORDR_OA_BRANDPACK.REMARK
	FROM DIST_DISTRIBUTOR,ORDR_PURCHASE_ORDER,ORDR_PO_BRANDPACK,ORDR_ORDER_ACCEPTANCE,BRND_BRAND,BRND_BRANDPACK,ORDR_OA_BRANDPACK
	WHERE ORDR_PURCHASE_ORDER.DISTRIBUTOR_ID = DIST_DISTRIBUTOR.DISTRIBUTOR_ID
	AND ORDR_OA_BRANDPACK.OA_ID = ORDR_ORDER_ACCEPTANCE.OA_ID AND ORDR_OA_BRANDPACK.PO_BRANDPACK_ID
	= ORDR_PO_BRANDPACK.PO_BRANDPACK_ID AND ORDR_ORDER_ACCEPTANCE.PO_REF_NO = ORDR_PO_BRANDPACK.PO_REF_NO
	AND ORDR_PO_BRANDPACK.PO_REF_NO = ORDR_PURCHASE_ORDER.PO_REF_NO
	AND ORDR_PO_BRANDPACK.BRANDPACK_ID = BRND_BRANDPACK.BRANDPACK_ID
	AND BRND_BRANDPACK.BRAND_ID = BRND_BRAND.BRAND_ID
	AND ORDR_PURCHASE_ORDER.PO_REF_DATE >= @FROM_PODATE AND ORDR_PURCHASE_ORDER.PO_REF_DATE <= @UNTIL_PODATE
     END
ELSE IF (@FROM_PODATE IS NOT NULL)
    BEGIN
	SELECT DIST_DISTRIBUTOR.DISTRIBUTOR_ID,DIST_DISTRIBUTOR.DISTRIBUTOR_NAME,ORDR_PURCHASE_ORDER.PO_REF_NO,
	ORDR_PURCHASE_ORDER.PO_REF_DATE,BRND_BRAND.BRAND_NAME,BRND_BRANDPACK.BRANDPACK_NAME,
	ORDR_OA_BRANDPACK.OA_PRICE_PERQTY AS PRICE,
	(SELECT ISNULL(SUM(ORDR_OA_REMAINDING.QTY),0) FROM ORDR_OA_REMAINDING WHERE OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID)  AS REMAINDING,
	CAST((SELECT ISNULL(SUM(ORDR_OA_REMAINDING.QTY),0) FROM ORDR_OA_REMAINDING WHERE OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID)AS DECIMAL(18,3)) * ORDR_OA_BRANDPACK.OA_PRICE_PERQTY AS REMAINDING_AMOUNT,
	ORDR_PO_BRANDPACK.PO_ORIGINAL_QTY,
		ORDR_PO_BRANDPACK.PO_ORIGINAL_QTY * ORDR_PO_BRANDPACK.PO_PRICE_PERQTY AS PO_AMOUNT_QTY,ORDR_ORDER_ACCEPTANCE.OA_ID AS OA_REF_NO,
	ORDR_ORDER_ACCEPTANCE.OA_DATE,ORDR_OA_BRANDPACK.QTY_EVEN + (SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC WHERE GQSY_SGT_P_FLAG = 'RMOA'
	 AND OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID) AS OA_QTY,(ORDR_OA_BRANDPACK.QTY_EVEN + (SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC WHERE GQSY_SGT_P_FLAG = 'RMOA'
	 AND OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID)) * ORDR_OA_BRANDPACK.OA_PRICE_PERQTY AS OA_AMOUNT_QTY,
	ORDR_OA_BRANDPACK.AGREE_DISC_QTY + ORDR_OA_BRANDPACK.PROG_DISC_QTY + ORDR_OA_BRANDPACK.PROJ_DISC_QTY + ORDR_OA_BRANDPACK.OTHER_DISC_QTY AS DISC_QTY,
	(ORDR_OA_BRANDPACK.AGREE_DISC_QTY + ORDR_OA_BRANDPACK.PROG_DISC_QTY + ORDR_OA_BRANDPACK.PROJ_DISC_QTY + ORDR_OA_BRANDPACK.OTHER_DISC_QTY) * ORDR_OA_BRANDPACK.OA_PRICE_PERQTY AS DISC_AMOUNT_QTY,
	ORDR_OA_BRANDPACK.QTY_EVEN + (SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC WHERE GQSY_SGT_P_FLAG = 'RMOA'
	 AND OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID) + ORDR_OA_BRANDPACK.AGREE_DISC_QTY + 
	ORDR_OA_BRANDPACK.PROG_DISC_QTY + ORDR_OA_BRANDPACK.PROJ_DISC_QTY + ORDR_OA_BRANDPACK.OTHER_DISC_QTY AS TOTAL,
	cast((ORDR_OA_BRANDPACK.QTY_EVEN + (SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC WHERE GQSY_SGT_P_FLAG = 'RMOA'
	 AND OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID) + ORDR_OA_BRANDPACK.AGREE_DISC_QTY + 
	ORDR_OA_BRANDPACK.PROG_DISC_QTY + ORDR_OA_BRANDPACK.PROJ_DISC_QTY + ORDR_OA_BRANDPACK.OTHER_DISC_QTY)as DECIMAL(14,3)) * ORDR_OA_BRANDPACK.OA_PRICE_PERQTY AS TOTAL_AMOUNT_DELIVERY,
	(cast((ORDR_OA_BRANDPACK.QTY_EVEN + (SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC WHERE GQSY_SGT_P_FLAG = 'RMOA'
	 AND OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID) + ORDR_OA_BRANDPACK.AGREE_DISC_QTY +
	ORDR_OA_BRANDPACK.PROG_DISC_QTY + ORDR_OA_BRANDPACK.PROJ_DISC_QTY + ORDR_OA_BRANDPACK.OTHER_DISC_QTY)as DECIMAL(14,3)) * ORDR_OA_BRANDPACK.OA_PRICE_PERQTY) - 
	((ORDR_OA_BRANDPACK.AGREE_DISC_QTY + ORDR_OA_BRANDPACK.PROG_DISC_QTY + ORDR_OA_BRANDPACK.PROJ_DISC_QTY + ORDR_OA_BRANDPACK.OTHER_DISC_QTY) * ORDR_OA_BRANDPACK.OA_PRICE_PERQTY) AS TOTAL_AMOUNT_SALES
	--,ORDR_OA_BRANDPACK.REMARK
	FROM DIST_DISTRIBUTOR,ORDR_PURCHASE_ORDER,ORDR_PO_BRANDPACK,ORDR_ORDER_ACCEPTANCE,BRND_BRAND,BRND_BRANDPACK,ORDR_OA_BRANDPACK
	WHERE ORDR_PURCHASE_ORDER.DISTRIBUTOR_ID = DIST_DISTRIBUTOR.DISTRIBUTOR_ID
	AND ORDR_OA_BRANDPACK.OA_ID = ORDR_ORDER_ACCEPTANCE.OA_ID AND ORDR_OA_BRANDPACK.PO_BRANDPACK_ID
	= ORDR_PO_BRANDPACK.PO_BRANDPACK_ID AND ORDR_ORDER_ACCEPTANCE.PO_REF_NO = ORDR_PO_BRANDPACK.PO_REF_NO
	AND ORDR_PO_BRANDPACK.PO_REF_NO = ORDR_PURCHASE_ORDER.PO_REF_NO
	AND ORDR_PO_BRANDPACK.BRANDPACK_ID = BRND_BRANDPACK.BRANDPACK_ID
	AND BRND_BRANDPACK.BRAND_ID = BRND_BRAND.BRAND_ID
	AND ORDR_PURCHASE_ORDER.PO_REF_DATE >= @FROM_PODATE 
	
    END
ELSE IF (@UNTIL_PODATE IS NOT NULL)
     BEGIN
	SELECT DIST_DISTRIBUTOR.DISTRIBUTOR_ID,DIST_DISTRIBUTOR.DISTRIBUTOR_NAME,ORDR_PURCHASE_ORDER.PO_REF_NO,
	ORDR_PURCHASE_ORDER.PO_REF_DATE,BRND_BRAND.BRAND_NAME,BRND_BRANDPACK.BRANDPACK_NAME,
	ORDR_OA_BRANDPACK.OA_PRICE_PERQTY AS PRICE,
	(SELECT ISNULL(SUM(ORDR_OA_REMAINDING.QTY),0) FROM ORDR_OA_REMAINDING WHERE OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID)  AS REMAINDING,
	CAST((SELECT ISNULL(SUM(ORDR_OA_REMAINDING.QTY),0) FROM ORDR_OA_REMAINDING WHERE OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID)AS DECIMAL(18,3)) * ORDR_OA_BRANDPACK.OA_PRICE_PERQTY AS REMAINDING_AMOUNT,
	ORDR_PO_BRANDPACK.PO_ORIGINAL_QTY,
		ORDR_PO_BRANDPACK.PO_ORIGINAL_QTY * ORDR_PO_BRANDPACK.PO_PRICE_PERQTY AS PO_AMOUNT_QTY,ORDR_ORDER_ACCEPTANCE.OA_ID AS OA_REF_NO,
	ORDR_ORDER_ACCEPTANCE.OA_DATE,ORDR_OA_BRANDPACK.QTY_EVEN + (SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC WHERE GQSY_SGT_P_FLAG = 'RMOA'
	 AND OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID) AS OA_QTY,(ORDR_OA_BRANDPACK.QTY_EVEN + (SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC WHERE GQSY_SGT_P_FLAG = 'RMOA'
	 AND OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID)) * ORDR_OA_BRANDPACK.OA_PRICE_PERQTY AS OA_AMOUNT_QTY,
	ORDR_OA_BRANDPACK.AGREE_DISC_QTY + ORDR_OA_BRANDPACK.PROG_DISC_QTY + ORDR_OA_BRANDPACK.PROJ_DISC_QTY + ORDR_OA_BRANDPACK.OTHER_DISC_QTY AS DISC_QTY,
	(ORDR_OA_BRANDPACK.AGREE_DISC_QTY + ORDR_OA_BRANDPACK.PROG_DISC_QTY + ORDR_OA_BRANDPACK.PROJ_DISC_QTY + ORDR_OA_BRANDPACK.OTHER_DISC_QTY) * ORDR_OA_BRANDPACK.OA_PRICE_PERQTY AS DISC_AMOUNT_QTY,
	ORDR_OA_BRANDPACK.QTY_EVEN + (SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC WHERE GQSY_SGT_P_FLAG = 'RMOA'
	 AND OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID) + ORDR_OA_BRANDPACK.AGREE_DISC_QTY + 
	ORDR_OA_BRANDPACK.PROG_DISC_QTY + ORDR_OA_BRANDPACK.PROJ_DISC_QTY + ORDR_OA_BRANDPACK.OTHER_DISC_QTY AS TOTAL,
	cast((ORDR_OA_BRANDPACK.QTY_EVEN + (SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC WHERE GQSY_SGT_P_FLAG = 'RMOA'
	 AND OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID) + ORDR_OA_BRANDPACK.AGREE_DISC_QTY + 
	ORDR_OA_BRANDPACK.PROG_DISC_QTY + ORDR_OA_BRANDPACK.PROJ_DISC_QTY + ORDR_OA_BRANDPACK.OTHER_DISC_QTY)as DECIMAL(14,3)) * ORDR_OA_BRANDPACK.OA_PRICE_PERQTY AS TOTAL_AMOUNT_DELIVERY,
	(cast((ORDR_OA_BRANDPACK.QTY_EVEN + (SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC WHERE GQSY_SGT_P_FLAG = 'RMOA'
	 AND OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID) + ORDR_OA_BRANDPACK.AGREE_DISC_QTY +
	ORDR_OA_BRANDPACK.PROG_DISC_QTY + ORDR_OA_BRANDPACK.PROJ_DISC_QTY + ORDR_OA_BRANDPACK.OTHER_DISC_QTY)as DECIMAL(14,3)) * ORDR_OA_BRANDPACK.OA_PRICE_PERQTY) - 
	((ORDR_OA_BRANDPACK.AGREE_DISC_QTY + ORDR_OA_BRANDPACK.PROG_DISC_QTY + ORDR_OA_BRANDPACK.PROJ_DISC_QTY + ORDR_OA_BRANDPACK.OTHER_DISC_QTY) * ORDR_OA_BRANDPACK.OA_PRICE_PERQTY) AS TOTAL_AMOUNT_SALES
	--,ORDR_OA_BRANDPACK.REMARK
	FROM DIST_DISTRIBUTOR,ORDR_PURCHASE_ORDER,ORDR_PO_BRANDPACK,ORDR_ORDER_ACCEPTANCE,BRND_BRAND,BRND_BRANDPACK,ORDR_OA_BRANDPACK
	WHERE ORDR_PURCHASE_ORDER.DISTRIBUTOR_ID = DIST_DISTRIBUTOR.DISTRIBUTOR_ID
	AND ORDR_OA_BRANDPACK.OA_ID = ORDR_ORDER_ACCEPTANCE.OA_ID AND ORDR_OA_BRANDPACK.PO_BRANDPACK_ID
	= ORDR_PO_BRANDPACK.PO_BRANDPACK_ID AND ORDR_ORDER_ACCEPTANCE.PO_REF_NO = ORDR_PO_BRANDPACK.PO_REF_NO
	AND ORDR_PO_BRANDPACK.PO_REF_NO = ORDR_PURCHASE_ORDER.PO_REF_NO
	AND ORDR_PO_BRANDPACK.BRANDPACK_ID = BRND_BRANDPACK.BRANDPACK_ID
	AND BRND_BRANDPACK.BRAND_ID = BRND_BRAND.BRAND_ID
	AND ORDR_PURCHASE_ORDER.PO_REF_DATE <= @UNTIL_PODATE 
	
     END
GO
--exec Usp_Create_View_OA_Report
--@FROM_OADATE = null,
--@UNTIL_OADATE = '05/23/2009',
--@FROM_PODATE = NULL,
--@UNTIL_PODATE = NULL 
-----------------------------------------------------------------------------------
--PROCEDURE UNTUK MEMVIEW REPORT OA DI CRYSTAL REPORT------------------------------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Create_View_OA_Report_1' AND TYPE = 'P')
DROP PROCEDURE Usp_Create_View_OA_Report_1
GO
CREATE PROCEDURE Usp_Create_View_OA_Report_1
AS
BEGIN

SELECT OPO.DISTRIBUTOR_ID,DR.DISTRIBUTOR_NAME,OPO.PO_REF_NO,OPO.PO_REF_DATE,OPB.PO_BRANDPACK_ID,BB.BRANDPACK_NAME,
OPB.PO_ORIGINAL_QTY,OOA.OA_ID AS OA_REF_NO,OOA.OA_DATE,
(CAST((OOB.QTY_EVEN)AS DECIMAL(18,3)) + CAST((SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC WHERE GQSY_SGT_P_FLAG = 'RMOA' AND OA_BRANDPACK_ID = OOB.OA_BRANDPACK_ID)AS DECIMAL(18,3))) AS OA_QTY,
(CAST((OOB.QTY_EVEN)AS DECIMAL(18,3)) + CAST((SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC WHERE GQSY_SGT_P_FLAG = 'RMOA' AND OA_BRANDPACK_ID = OOB.OA_BRANDPACK_ID)AS DECIMAL(18,3))) + 
OOB.AGREE_DISC_QTY + OOB.PROG_DISC_QTY + OOB.PROJ_DISC_QTY + OOB.OTHER_DISC_QTY AS TOTAL,
(CAST((OOB.QTY_EVEN)AS DECIMAL(18,3)) + CAST((SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC WHERE GQSY_SGT_P_FLAG = 'RMOA' AND OA_BRANDPACK_ID = OOB.OA_BRANDPACK_ID)AS DECIMAL(18,3))) * OOB.OA_PRICE_PERQTY AS TOTAL_AMOUNT_SALES
FROM ORDR_PURCHASE_ORDER OPO INNER JOIN DIST_DISTRIBUTOR DR ON OPO.DISTRIBUTOR_ID = DR.DISTRIBUTOR_ID
INNER JOIN ORDR_PO_BRANDPACK OPB ON OPO.PO_REF_NO = OPB.PO_REF_NO INNER JOIN ORDR_ORDER_ACCEPTANCE OOA
ON OOA.PO_REF_NO = OPO.PO_REF_NO INNER JOIN ORDR_OA_BRANDPACK OOB ON OOB.OA_ID = OOA.OA_ID
AND OPB.PO_BRANDPACK_ID = OOB.PO_BRANDPACK_ID INNER JOIN BRND_BRANDPACK BB ON OPB.BRANDPACK_ID = BB.BRANDPACK_ID
WHERE YEAR(OPO.PO_REF_DATE) >= YEAR(GETDATE()) -1
END
GO
--------------------------------------------------------------------------------------
---PROCEDURE UNTUK MEMVIEW REPORT DISTRIBUTOR REPORT-----------

IF EXISTS(SELECT NAME FROM SYS.SYSOBJECTS WHERE NAME = 'Usp_Create_View_Distributor_Report' AND TYPE = 'P')
DROP PROCEDURE Usp_Create_View_Distributor_Report
GO
CREATE PROCEDURE Usp_Create_View_Distributor_Report
AS
BEGIN
	SELECT DIST_DISTRIBUTOR.DISTRIBUTOR_ID,DIST_DISTRIBUTOR.DISTRIBUTOR_NAME,BRND_BRANDPACK.BRANDPACK_NAME,ORDR_PURCHASE_ORDER.PO_REF_DATE,ORDR_PURCHASE_ORDER.PO_REF_NO,
	ORDR_PO_BRANDPACK.PO_BRANDPACK_ID,ORDR_PO_BRANDPACK.PO_ORIGINAL_QTY, ORDR_ORDER_ACCEPTANCE.OA_ID AS OA_REF_NO,ORDR_ORDER_ACCEPTANCE.OA_DATE,ORDR_OA_BRANDPACK.OA_BRANDPACK_ID,
	(CAST((ORDR_OA_BRANDPACK.QTY_EVEN)AS DECIMAL(18,3)) + CAST((SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC WHERE GQSY_SGT_P_FLAG = 'RMOA' AND OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID)AS DECIMAL(18,3))) AS OA_QTY,
	(SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC WHERE OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID AND GQSY_SGT_P_FLAG = 'G') AS GIVEN,
	(SELECT ISNULL(SUM(DISC_QTY),0)  FROM ORDR_OA_BRANDPACK_DISC WHERE OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID AND GQSY_SGT_P_FLAG LIKE 'Q%') AS [QUARTER],
	(SELECT ISNULL(SUM(DISC_QTY),0)  FROM ORDR_OA_BRANDPACK_DISC WHERE OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID AND GQSY_SGT_P_FLAG LIKE 'S%') AS SEMESTER,
	(SELECT ISNULL(SUM(DISC_QTY),0)  FROM ORDR_OA_BRANDPACK_DISC WHERE OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID AND GQSY_SGT_P_FLAG = 'Y') AS [YEAR],
	(SELECT ISNULL(SUM(DISC_QTY),0)  FROM ORDR_OA_BRANDPACK_DISC WHERE OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID AND GQSY_SGT_P_FLAG = 'MG') + 
	(SELECT ISNULL(SUM(DISC_QTY),0)  FROM ORDR_OA_BRANDPACK_DISC WHERE OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID AND GQSY_SGT_P_FLAG = 'DK') +
	(SELECT ISNULL(SUM(DISC_QTY),0)  FROM ORDR_OA_BRANDPACK_DISC WHERE OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID AND GQSY_SGT_P_FLAG = 'CP') + 
	(SELECT ISNULL(SUM(DISC_QTY),0)  FROM ORDR_OA_BRANDPACK_DISC WHERE OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID AND GQSY_SGT_P_FLAG = 'SC') + 
	(SELECT ISNULL(SUM(DISC_QTY),0)  FROM ORDR_OA_BRANDPACK_DISC WHERE OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID AND GQSY_SGT_P_FLAG = 'CR') +
	(SELECT ISNULL(SUM(DISC_QTY),0)  FROM ORDR_OA_BRANDPACK_DISC WHERE OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID AND GQSY_SGT_P_FLAG = 'KP') 
	 AS GIVEN_MARKETING,
	(SELECT ISNULL(SUM(DISC_QTY),0)  FROM ORDR_OA_BRANDPACK_DISC WHERE OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID AND GQSY_SGT_P_FLAG = 'MS') AS STEPPING,
	(SELECT ISNULL(SUM(DISC_QTY),0)  FROM ORDR_OA_BRANDPACK_DISC WHERE OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID AND GQSY_SGT_P_FLAG = 'MT') AS TARGET,
	(SELECT ISNULL(SUM(DISC_QTY),0)  FROM ORDR_OA_BRANDPACK_DISC WHERE OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID AND GQSY_SGT_P_FLAG = 'P')AS PROJECT_DISCOUNT,
	(SELECT ISNULL(SUM(DISC_QTY),0)  FROM ORDR_OA_BRANDPACK_DISC WHERE OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID AND GQSY_SGT_P_FLAG = 'O')AS OTHER,
	(SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC WHERE OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID) + 
	(CAST((ORDR_OA_BRANDPACK.QTY_EVEN)AS DECIMAL(18,3)) + CAST((SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC WHERE GQSY_SGT_P_FLAG = 'RMOA' AND OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID)AS DECIMAL(18,3))) AS TOTAL_DELIVERY,
	(((SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC WHERE OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID) + 
	(CAST((ORDR_OA_BRANDPACK.QTY_EVEN)AS DECIMAL(18,3)) + CAST((SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC WHERE GQSY_SGT_P_FLAG = 'RMOA' AND OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID)AS DECIMAL(18,3))))  * ORDR_OA_BRANDPACK.OA_PRICE_PERQTY) -  
	((ORDR_OA_BRANDPACK.AGREE_DISC_QTY + ORDR_OA_BRANDPACK.PROG_DISC_QTY + ORDR_OA_BRANDPACK.PROJ_DISC_QTY + ORDR_OA_BRANDPACK.OTHER_DISC_QTY) * ORDR_OA_BRANDPACK.OA_PRICE_PERQTY) AS TOTAL_AMOUNT_SALES  
	FROM BRND_BRANDPACK,ORDR_PURCHASE_ORDER,ORDR_ORDER_ACCEPTANCE,ORDR_PO_BRANDPACK,DIST_DISTRIBUTOR,
	ORDR_OA_BRANDPACK WHERE ORDR_OA_BRANDPACK.OA_ID = ORDR_ORDER_ACCEPTANCE.OA_ID AND ORDR_OA_BRANDPACK.PO_BRANDPACK_ID
	  	= ORDR_PO_BRANDPACK.PO_BRANDPACK_ID AND ORDR_ORDER_ACCEPTANCE.PO_REF_NO = ORDR_PO_BRANDPACK.PO_REF_NO
		AND ORDR_PO_BRANDPACK.PO_REF_NO = ORDR_PURCHASE_ORDER.PO_REF_NO /*AND ORDR_ORDER_ACCEPTANCE.OA_DATE >= 
		@FROM_OADATE AND ORDR_ORDER_ACCEPTANCE.OA_DATE <= @UNTIL_OADATE*/ AND ORDR_PURCHASE_ORDER.DISTRIBUTOR_ID = DIST_DISTRIBUTOR.DISTRIBUTOR_ID
		AND ORDR_PO_BRANDPACK.BRANDPACK_ID = BRND_BRANDPACK.BRANDPACK_ID
	AND YEAR(ORDR_PURCHASE_ORDER.PO_REF_DATE) >= YEAR(GETDATE()) -1
    END
GO
---------------------------------------------------------------------------------------
----------------------PROCEDURE UNTUK MENGECUTE REPORT DISTRIBUTOR HEADER OA---------------------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Create_View_Distributor_Report_1' AND TYPE = 'P')
DROP PROCEDURE Usp_Create_View_Distributor_Report_1
GO
CREATE PROCEDURE Usp_Create_View_Distributor_Report_1
@StartDate DateTime,
@EndDate DateTime
AS 
SET NOCOUNT ON;
IF (@StartDate IS NOT NULL AND @EndDate IS NOT NULL)
BEGIN
	 SELECT DG.REGIONAL_AREA,TER.TERRITORY_AREA,OPO.DISTRIBUTOR_ID,DR.DISTRIBUTOR_NAME,OPO.PO_REF_NO,OPO.PO_REF_DATE,
	OOA.OA_ID AS OA_REF_NO,OOA.OA_DATE,BR.BRAND_ID,BR.BRAND_NAME,BB.BRANDPACK_ID,BB.BRANDPACK_NAME,OPB.PO_ORIGINAL_QTY AS PO_QTY,OOB.QTY_EVEN,
	OPB.PO_PRICE_PERQTY AS PRICE,OOB.UNIT,OOB.REMARK,OPB.DESCRIPTIONS2 AS CSE_REMARK,ISNULL(OA_DISC.REMAIND_QTY,0)AS REMAIND_QTY,OA_DISC.GIVEN_AGREEMENT,OA_DISC.[QUARTER],
	OA_DISC.[SEMESTER],OA_DISC.YEARLY,OA_DISC.RPK,OA_DISC.DK,OA_DISC.CP_D,OA_DISC.CP_D_S,OA_DISC.CP_RMT,OA_DISC.PKPP,OA_DISC.CP_R,
	OA_DISC.CP_D_AUTO,OA_DISC.OTHER,OA_DISC.OTHER_DD,OA_DISC.OTHER_DR,OA_DISC.OTHER_CBD,
	ISNULL(T_DISC.TOTAL_DISC,0)AS TOTAL_DISC,
	--ISNULL(T_DISC.TOTAL_DISC,0) * OOB.OA_PRICE_PERQTY AS TOTAL_DISC_AMOUNT,
	OOB.QTY_EVEN + ISNULL(T_DISC.TOTAL_DISC,0) + ISNULL(OA_LEFT.TOTAL_DISC,0) AS TOTAL_DELIVERY,
	--(OOB.QTY_EVEN + ISNULL(T_DISC.TOTAL_DISC,0) + ISNULL(OA_LEFT.TOTAL_DISC,0)) * OOB.OA_PRICE_PERQTY AS TOTAL_AMOUNT_DELIVERY,
	OOB.QTY_EVEN + ISNULL(OA_LEFT.TOTAL_DISC,0) AS TOTAL_SALES
	--(OOB.QTY_EVEN + ISNULL(OA_LEFT.TOTAL_DISC,0)) * OOB.OA_PRICE_PERQTY AS TOTAL_AMOUNT_SALES         
	FROM ORDR_PURCHASE_ORDER OPO INNER JOIN DIST_DISTRIBUTOR DR ON OPO.DISTRIBUTOR_ID = DR.DISTRIBUTOR_ID
	 INNER JOIN ORDR_PO_BRANDPACK OPB ON OPB.PO_REF_NO = OPO.PO_REF_NO LEFT OUTER JOIN ORDR_ORDER_ACCEPTANCE OOA
	ON OOA.PO_REF_NO = OPB.PO_REF_NO --INNER JOIN BRND_BRAND BR ON BR.BRAND_ID = BB.BRAND_ID
	LEFT OUTER JOIN ORDR_OA_BRANDPACK OOB ON OOB.PO_BRANDPACK_ID = OPB.PO_BRANDPACK_ID AND OOB.OA_ID = OOA.OA_ID
	INNER JOIN BRND_BRANDPACK BB ON OPB.BRANDPACK_ID = BB.BRANDPACK_ID --INNER JOIN ORDR_OA_BRANDPACK_DISC OOBD ON OOBD.OA_BRANDPACK_ID = OOB.OA_BRANDPACK_ID
	LEFT OUTER JOIN
	               (
	                 SELECT OA_BRANDPACK_ID,
	                 SUM(CASE GQSY_SGT_P_FLAG WHEN 'RMOA' THEN DISC_QTY ELSE 0 END)AS REMAIND_QTY,
	                 SUM(CASE GQSY_SGT_P_FLAG WHEN 'G' THEN DISC_QTY ELSE 0 END)AS GIVEN_AGREEMENT, 
	            	 SUM(CASE GQSY_SGT_P_FLAG WHEN 'Q1' THEN DISC_QTY WHEN 'Q2' THEN DISC_QTY WHEN 'Q3' THEN DISC_QTY
	                                     	  WHEN 'Q4' THEN DISC_QTY ELSE 0 END)AS [QUARTER],
	            	 SUM(CASE GQSY_SGT_P_FLAG WHEN 'S1' THEN DISC_QTY WHEN 'S2' THEN DISC_QTY ELSE 0 END)AS [SEMESTER], 
	           		 SUM(CASE GQSY_SGT_P_FLAG WHEN 'Y' THEN DISC_QTY ELSE 0 END)AS YEARLY, 
	           		 SUM(CASE GQSY_SGT_P_FLAG WHEN 'MG' THEN DISC_QTY ELSE 0 END)AS RPK,
					 SUM(CASE GQSY_SGT_P_FLAG WHEN 'DK' THEN DISC_QTY WHEN 'DN' THEN DISC_QTY ELSE 0 END)AS DK,
	           		 SUM(CASE GQSY_SGT_P_FLAG WHEN 'CP' THEN DISC_QTY WHEN 'TD' THEN DISC_QTY ELSE 0 END)AS CP_D,
					 SUM(CASE GQSY_SGT_P_FLAG WHEN 'CS' THEN DISC_QTY WHEN 'TS' THEN DISC_QTY WHEN 'SC' THEN DISC_QTY ELSE 0 END)AS CP_D_S,
					 SUM(CASE GQSY_SGT_P_FLAG WHEN 'CD' THEN DISC_QTY WHEN 'CT' THEN DISC_QTY ELSE 0 END)AS CP_RMT,
					 SUM(CASE GQSY_SGT_P_FLAG WHEN 'KP' THEN DISC_QTY ELSE 0 END)AS PKPP,
					 SUM(CASE GQSY_SGT_P_FLAG WHEN 'CR' THEN DISC_QTY ELSE 0 END) AS CP_R,
					 SUM(CASE GQSY_SGT_P_FLAG WHEN 'CA' THEN DISC_QTY ELSE 0 END) AS CP_D_AUTO,
					 SUM(CASE GQSY_SGT_P_FLAG WHEN 'O'  THEN DISC_QTY ELSE 0 END) AS OTHER,
					 SUM(CASE GQSY_SGT_P_FLAG WHEN 'ODD' THEN DISC_QTY ELSE 0 END) AS OTHER_DD,
					 SUM(CASE GQSY_SGT_P_FLAG WHEN 'ODR' THEN DISC_QTY ELSE 0 END) AS OTHER_DR,
					 SUM(CASE GQSY_SGT_P_FLAG WHEN 'OCBD' THEN DISC_QTY ELSE 0 END) AS OTHER_CBD,
					 SUM(CASE GQSY_SGT_P_FLAG WHEN 'ODK' THEN DISC_QTY ELSE 0 END) AS OTHER_DK
					 FROM ORDR_OA_BRANDPACK_DISC GROUP BY OA_BRANDPACK_ID
	           	)OA_DISC ON OA_DISC.OA_BRANDPACK_ID = OOB.OA_BRANDPACK_ID
	LEFT OUTER JOIN(
	                 SELECT OA_BRANDPACK_ID,ISNULL(SUM(DISC_QTY),0)AS TOTAL_DISC FROM ORDR_OA_BRANDPACK_DISC 
	                 WHERE GQSY_SGT_P_FLAG != 'RMOA'
	                 GROUP BY OA_BRANDPACK_ID
	                )T_DISC ON OOB.OA_BRANDPACK_ID = T_DISC.OA_BRANDPACK_ID
	LEFT OUTER JOIN( 
	                 SELECT OA_BRANDPACK_ID,ISNULL(SUM(DISC_QTY),0)AS TOTAL_DISC FROM ORDR_OA_BRANDPACK_DISC 
	                 WHERE GQSY_SGT_P_FLAG = 'RMOA'
	                 GROUP BY OA_BRANDPACK_ID
	                )OA_LEFT ON OA_LEFT.OA_BRANDPACK_ID = OOB.OA_BRANDPACK_ID 
	INNER JOIN TERRITORY TER ON TER.TERRITORY_ID = DR.TERRITORY_ID
	INNER JOIN DIST_REGIONAL DG ON DG.REGIONAL_ID = TER.REGIONAL_ID 
	INNER JOIN BRND_BRAND BR ON BR.BRAND_ID = BB.BRAND_ID
	WHERE OPO.PO_REF_DATE >= @StartDate AND OPO.PO_REF_DATE <= @EndDate
END
ELSE IF (@StartDate IS NOT NULL)
BEGIN
	 SELECT DG.REGIONAL_AREA,TER.TERRITORY_AREA,OPO.DISTRIBUTOR_ID,DR.DISTRIBUTOR_NAME,OPO.PO_REF_NO,OPO.PO_REF_DATE,
	OOA.OA_ID AS OA_REF_NO,OOA.OA_DATE,BR.BRAND_ID,BR.BRAND_NAME,BB.BRANDPACK_ID,BB.BRANDPACK_NAME,OPB.PO_ORIGINAL_QTY AS PO_QTY,OOB.QTY_EVEN,
	OPB.PO_PRICE_PERQTY AS PRICE,OOB.UNIT,OOB.REMARK,OPB.DESCRIPTIONS2 AS CSE_REMARK,ISNULL(OA_DISC.REMAIND_QTY,0)AS REMAIND_QTY,OA_DISC.GIVEN_AGREEMENT,OA_DISC.[QUARTER],
	OA_DISC.[SEMESTER],OA_DISC.YEARLY,OA_DISC.RPK,OA_DISC.DK,OA_DISC.CP_D,OA_DISC.CP_D_S,OA_DISC.CP_RMT,OA_DISC.PKPP,OA_DISC.CP_R,
	OA_DISC.CP_D_AUTO,OA_DISC.OTHER,OA_DISC.OTHER_DD,OA_DISC.OTHER_DR,OA_DISC.OTHER_CBD,
	ISNULL(T_DISC.TOTAL_DISC,0)AS TOTAL_DISC,
	--ISNULL(T_DISC.TOTAL_DISC,0) * OOB.OA_PRICE_PERQTY AS TOTAL_DISC_AMOUNT,
	OOB.QTY_EVEN + ISNULL(T_DISC.TOTAL_DISC,0) + ISNULL(OA_LEFT.TOTAL_DISC,0) AS TOTAL_DELIVERY,
	--(OOB.QTY_EVEN + ISNULL(T_DISC.TOTAL_DISC,0) + ISNULL(OA_LEFT.TOTAL_DISC,0)) * OOB.OA_PRICE_PERQTY AS TOTAL_AMOUNT_DELIVERY,
	OOB.QTY_EVEN + ISNULL(OA_LEFT.TOTAL_DISC,0) AS TOTAL_SALES
	--(OOB.QTY_EVEN + ISNULL(OA_LEFT.TOTAL_DISC,0)) * OOB.OA_PRICE_PERQTY AS TOTAL_AMOUNT_SALES              
	FROM ORDR_PURCHASE_ORDER OPO INNER JOIN DIST_DISTRIBUTOR DR ON OPO.DISTRIBUTOR_ID = DR.DISTRIBUTOR_ID
	 INNER JOIN ORDR_PO_BRANDPACK OPB ON OPB.PO_REF_NO = OPO.PO_REF_NO LEFT OUTER JOIN ORDR_ORDER_ACCEPTANCE OOA
	ON OOA.PO_REF_NO = OPB.PO_REF_NO --INNER JOIN BRND_BRAND BR ON BR.BRAND_ID = BB.BRAND_ID
	LEFT OUTER JOIN ORDR_OA_BRANDPACK OOB ON OOB.PO_BRANDPACK_ID = OPB.PO_BRANDPACK_ID AND OOB.OA_ID = OOA.OA_ID
	INNER JOIN BRND_BRANDPACK BB ON OPB.BRANDPACK_ID = BB.BRANDPACK_ID --INNER JOIN ORDR_OA_BRANDPACK_DISC OOBD ON OOBD.OA_BRANDPACK_ID = OOB.OA_BRANDPACK_ID
	LEFT OUTER JOIN
	               (
	                 SELECT OA_BRANDPACK_ID,
	                 SUM(CASE GQSY_SGT_P_FLAG WHEN 'RMOA' THEN DISC_QTY ELSE 0 END)AS REMAIND_QTY,
	                 SUM(CASE GQSY_SGT_P_FLAG WHEN 'G' THEN DISC_QTY ELSE 0 END)AS GIVEN_AGREEMENT, 
	            	 SUM(CASE GQSY_SGT_P_FLAG WHEN 'Q1' THEN DISC_QTY WHEN 'Q2' THEN DISC_QTY WHEN 'Q3' THEN DISC_QTY
	                                     	  WHEN 'Q4' THEN DISC_QTY ELSE 0 END)AS [QUARTER],
	            	 SUM(CASE GQSY_SGT_P_FLAG WHEN 'S1' THEN DISC_QTY WHEN 'S2' THEN DISC_QTY ELSE 0 END)AS [SEMESTER], 
	           		 SUM(CASE GQSY_SGT_P_FLAG WHEN 'Y' THEN DISC_QTY ELSE 0 END)AS YEARLY, 
	           		 SUM(CASE GQSY_SGT_P_FLAG WHEN 'MG' THEN DISC_QTY ELSE 0 END)AS RPK,
					 SUM(CASE GQSY_SGT_P_FLAG WHEN 'DK' THEN DISC_QTY WHEN 'DN' THEN DISC_QTY ELSE 0 END)AS DK,
					 SUM(CASE GQSY_SGT_P_FLAG WHEN 'CP' THEN DISC_QTY WHEN 'TD' THEN DISC_QTY ELSE 0 END)AS CP_D,
					 SUM(CASE GQSY_SGT_P_FLAG WHEN 'CS' THEN DISC_QTY WHEN 'TS' THEN DISC_QTY WHEN 'SC' THEN DISC_QTY ELSE 0 END)AS CP_D_S,
	            	 SUM(CASE GQSY_SGT_P_FLAG WHEN 'CD' THEN DISC_QTY WHEN 'CT' THEN DISC_QTY ELSE 0 END)AS CP_RMT,
					 SUM(CASE GQSY_SGT_P_FLAG WHEN 'KP' THEN DISC_QTY ELSE 0 END)AS PKPP,
	            	 SUM(CASE GQSY_SGT_P_FLAG WHEN 'CR' THEN DISC_QTY ELSE 0 END) AS CP_R,
					 SUM(CASE GQSY_SGT_P_FLAG WHEN 'CA' THEN DISC_QTY ELSE 0 END) AS CP_D_AUTO,
	            	 SUM(CASE GQSY_SGT_P_FLAG WHEN 'O'  THEN DISC_QTY ELSE 0 END)AS OTHER,
					 SUM(CASE GQSY_SGT_P_FLAG WHEN 'ODD' THEN DISC_QTY ELSE 0 END) AS OTHER_DD,
					 SUM(CASE GQSY_SGT_P_FLAG WHEN 'ODR' THEN DISC_QTY ELSE 0 END) AS OTHER_DR,
					 SUM(CASE GQSY_SGT_P_FLAG WHEN 'OCBD' THEN DISC_QTY ELSE 0 END) AS OTHER_CBD,
					 SUM(CASE GQSY_SGT_P_FLAG WHEN 'ODK' THEN DISC_QTY ELSE 0 END) AS OTHER_DK
	            	 FROM ORDR_OA_BRANDPACK_DISC GROUP BY OA_BRANDPACK_ID
	           	)OA_DISC ON OA_DISC.OA_BRANDPACK_ID = OOB.OA_BRANDPACK_ID
	LEFT OUTER JOIN(
	                 SELECT OA_BRANDPACK_ID,ISNULL(SUM(DISC_QTY),0)AS TOTAL_DISC FROM ORDR_OA_BRANDPACK_DISC 
	                 WHERE GQSY_SGT_P_FLAG != 'RMOA'
	                 GROUP BY OA_BRANDPACK_ID
	                )T_DISC ON OOB.OA_BRANDPACK_ID = T_DISC.OA_BRANDPACK_ID
	LEFT OUTER JOIN( 
	                 SELECT OA_BRANDPACK_ID,ISNULL(SUM(DISC_QTY),0)AS TOTAL_DISC FROM ORDR_OA_BRANDPACK_DISC 
	                 WHERE GQSY_SGT_P_FLAG = 'RMOA'
	                 GROUP BY OA_BRANDPACK_ID
	                )OA_LEFT ON OA_LEFT.OA_BRANDPACK_ID = OOB.OA_BRANDPACK_ID 
	INNER JOIN TERRITORY TER ON TER.TERRITORY_ID = DR.TERRITORY_ID
	INNER JOIN DIST_REGIONAL DG ON DG.REGIONAL_ID = TER.REGIONAL_ID 
	INNER JOIN BRND_BRAND BR ON BR.BRAND_ID = BB.BRAND_ID
	WHERE OPO.PO_REF_DATE >= @StartDate
END
ELSE IF (@EndDate IS NOT NULL)
BEGIN
   SELECT DG.REGIONAL_AREA,TER.TERRITORY_AREA,OPO.DISTRIBUTOR_ID,DR.DISTRIBUTOR_NAME,OPO.PO_REF_NO,OPO.PO_REF_DATE,
	OOA.OA_ID AS OA_REF_NO,OOA.OA_DATE,BR.BRAND_ID,BR.BRAND_NAME,BB.BRANDPACK_ID,BB.BRANDPACK_NAME,OPB.PO_ORIGINAL_QTY AS PO_QTY,OOB.QTY_EVEN,
	OPB.PO_PRICE_PERQTY AS PRICE,OOB.UNIT,OOB.REMARK,OPB.DESCRIPTIONS2 AS CSE_REMARK,ISNULL(OA_DISC.REMAIND_QTY,0)AS REMAIND_QTY,OA_DISC.GIVEN_AGREEMENT,OA_DISC.[QUARTER],
	OA_DISC.[SEMESTER],OA_DISC.YEARLY,OA_DISC.RPK,OA_DISC.DK,OA_DISC.CP_D,OA_DISC.CP_D_S,OA_DISC.CP_RMT,OA_DISC.PKPP,OA_DISC.CP_R,
	OA_DISC.CP_D_AUTO,OA_DISC.OTHER,OA_DISC.OTHER_DD,OA_DISC.OTHER_DR,OA_DISC.OTHER_CBD,
	ISNULL(T_DISC.TOTAL_DISC,0)AS TOTAL_DISC,
	--ISNULL(T_DISC.TOTAL_DISC,0) * OOB.OA_PRICE_PERQTY AS TOTAL_DISC_AMOUNT,
	OOB.QTY_EVEN + ISNULL(T_DISC.TOTAL_DISC,0) + ISNULL(OA_LEFT.TOTAL_DISC,0) AS TOTAL_DELIVERY,
	--(OOB.QTY_EVEN + ISNULL(T_DISC.TOTAL_DISC,0) + ISNULL(OA_LEFT.TOTAL_DISC,0)) * OOB.OA_PRICE_PERQTY AS TOTAL_AMOUNT_DELIVERY,
	OOB.QTY_EVEN + ISNULL(OA_LEFT.TOTAL_DISC,0) AS TOTAL_SALES
	--(OOB.QTY_EVEN + ISNULL(OA_LEFT.TOTAL_DISC,0)) * OOB.OA_PRICE_PERQTY AS TOTAL_AMOUNT_SALES       
	FROM ORDR_PURCHASE_ORDER OPO INNER JOIN DIST_DISTRIBUTOR DR ON OPO.DISTRIBUTOR_ID = DR.DISTRIBUTOR_ID
	 INNER JOIN ORDR_PO_BRANDPACK OPB ON OPB.PO_REF_NO = OPO.PO_REF_NO LEFT OUTER JOIN ORDR_ORDER_ACCEPTANCE OOA
	ON OOA.PO_REF_NO = OPB.PO_REF_NO --INNER JOIN BRND_BRAND BR ON BR.BRAND_ID = BB.BRAND_ID
	LEFT OUTER JOIN ORDR_OA_BRANDPACK OOB ON OOB.PO_BRANDPACK_ID = OPB.PO_BRANDPACK_ID AND OOB.OA_ID = OOA.OA_ID
	INNER JOIN BRND_BRANDPACK BB ON OPB.BRANDPACK_ID = BB.BRANDPACK_ID --INNER JOIN ORDR_OA_BRANDPACK_DISC OOBD ON OOBD.OA_BRANDPACK_ID = OOB.OA_BRANDPACK_ID
	LEFT OUTER JOIN
	               (
	                 SELECT OA_BRANDPACK_ID,
	                 SUM(CASE GQSY_SGT_P_FLAG WHEN 'RMOA' THEN DISC_QTY ELSE 0 END)AS REMAIND_QTY,
	                 SUM(CASE GQSY_SGT_P_FLAG WHEN 'G' THEN DISC_QTY ELSE 0 END)AS GIVEN_AGREEMENT, 
	            	 SUM(CASE GQSY_SGT_P_FLAG WHEN 'Q1' THEN DISC_QTY WHEN 'Q2' THEN DISC_QTY WHEN 'Q3' THEN DISC_QTY
	                                     	  WHEN 'Q4' THEN DISC_QTY ELSE 0 END)AS [QUARTER],
	            	 SUM(CASE GQSY_SGT_P_FLAG WHEN 'S1' THEN DISC_QTY WHEN 'S2' THEN DISC_QTY ELSE 0 END)AS [SEMESTER], 
	           		 SUM(CASE GQSY_SGT_P_FLAG WHEN 'Y' THEN DISC_QTY ELSE 0 END)AS YEARLY, 
	           		 SUM(CASE GQSY_SGT_P_FLAG WHEN 'MG' THEN DISC_QTY ELSE 0 END)AS RPK,
	            	 SUM(CASE GQSY_SGT_P_FLAG WHEN 'DK' THEN DISC_QTY WHEN 'DN' THEN DISC_QTY ELSE 0 END)AS DK,
					 SUM(CASE GQSY_SGT_P_FLAG WHEN 'CP' THEN DISC_QTY WHEN 'TD' THEN DISC_QTY ELSE 0 END)AS CP_D,
					 SUM(CASE GQSY_SGT_P_FLAG WHEN 'CS' THEN DISC_QTY WHEN 'TS' THEN DISC_QTY WHEN 'SC' THEN DISC_QTY ELSE 0 END)AS CP_D_S,
					 SUM(CASE GQSY_SGT_P_FLAG WHEN 'CD' THEN DISC_QTY WHEN 'CT' THEN DISC_QTY ELSE 0 END)AS CP_RMT,
	            	 SUM(CASE GQSY_SGT_P_FLAG WHEN 'KP' THEN DISC_QTY ELSE 0 END)AS PKPP,
	            	 SUM(CASE GQSY_SGT_P_FLAG WHEN 'CR' THEN DISC_QTY ELSE 0 END) AS CP_R,
					 SUM(CASE GQSY_SGT_P_FLAG WHEN 'CA' THEN DISC_QTY ELSE 0 END) AS CP_D_AUTO,
	            	 SUM(CASE GQSY_SGT_P_FLAG WHEN 'O'  THEN DISC_QTY ELSE 0 END) AS OTHER,
					 SUM(CASE GQSY_SGT_P_FLAG WHEN 'ODD' THEN DISC_QTY ELSE 0 END) AS OTHER_DD,
					 SUM(CASE GQSY_SGT_P_FLAG WHEN 'ODR' THEN DISC_QTY ELSE 0 END) AS OTHER_DR,
					 SUM(CASE GQSY_SGT_P_FLAG WHEN 'OCBD' THEN DISC_QTY ELSE 0 END) AS OTHER_CBD,
					 SUM(CASE GQSY_SGT_P_FLAG WHEN 'ODK' THEN DISC_QTY ELSE 0 END) AS OTHER_DK
	            	 FROM ORDR_OA_BRANDPACK_DISC GROUP BY OA_BRANDPACK_ID
	           	)OA_DISC ON OA_DISC.OA_BRANDPACK_ID = OOB.OA_BRANDPACK_ID
	LEFT OUTER JOIN(
	                 SELECT OA_BRANDPACK_ID,ISNULL(SUM(DISC_QTY),0)AS TOTAL_DISC FROM ORDR_OA_BRANDPACK_DISC 
	                 WHERE GQSY_SGT_P_FLAG != 'RMOA'
	                 GROUP BY OA_BRANDPACK_ID
	                )T_DISC ON OOB.OA_BRANDPACK_ID = T_DISC.OA_BRANDPACK_ID
	LEFT OUTER JOIN( 
	                 SELECT OA_BRANDPACK_ID,ISNULL(SUM(DISC_QTY),0)AS TOTAL_DISC FROM ORDR_OA_BRANDPACK_DISC 
	                 WHERE GQSY_SGT_P_FLAG = 'RMOA'
	                 GROUP BY OA_BRANDPACK_ID
	                )OA_LEFT ON OA_LEFT.OA_BRANDPACK_ID = OOB.OA_BRANDPACK_ID 
	INNER JOIN TERRITORY TER ON TER.TERRITORY_ID = DR.TERRITORY_ID
	INNER JOIN DIST_REGIONAL DG ON DG.REGIONAL_ID = TER.REGIONAL_ID 
	INNER JOIN BRND_BRAND BR ON BR.BRAND_ID = BB.BRAND_ID
	WHERE OPO.PO_REF_DATE <= @EndDate
END
GO
--exec Usp_Create_View_Distributor_Report_1
--@StartDate = '04/01/2019',@EndDate = '04/22/2019'

-----------------------------PROCEDURE UNTUK MEMBUAT REPORT TARGET---------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Create_View_Target_Reaching_Agreement' AND TYPE = 'P')
DROP PROCEDURE Usp_Create_View_Target_Reaching_Agreement--toptodaynews.com
GO
CREATE PROCEDURE Usp_Create_View_Target_Reaching_Agreement
@START_DATE SMALLDATETIME,@END_DATE SMALLDATETIME
AS
SET NOCOUNT ON;

SET NOCOUNT ON;
IF OBJECT_ID ('TEMPDB..##T_TargetAgreementReport') IS NOT NULL
BEGIN
	DROP TABLE  TEMPDB..##T_TargetAgreementReport;
END

SELECT TER.TERRITORY_AREA,DR.DISTRIBUTOR_ID,DR.DISTRIBUTOR_NAME,AA.AGREEMENT_NO,AA.END_DATE,ABI.BRAND_ID,BN.BRAND_NAME,
ISCombined = CASE 
                   WHEN ABI.COMB_AGREE_BRAND_ID IS NOT NULL THEN 'YES'
                   ELSE 'NO'
	     END,
ABI.TARGET_Q1,ABI.TARGET_Q2,ABI.TARGET_Q3,ABI.TARGET_Q4,ABI.TARGET_S1,ABI.TARGET_S2,
(ABI.TARGET_Q1 + ABI.TARGET_Q2 + ABI.TARGET_Q3 + ABI.TARGET_Q4 + ABI.TARGET_S1 + ABI.TARGET_S2)
AS TARGET_YEAR,
ABI.TARGET_Q1_FM,ABI.TARGET_Q1_FM * AVGP.AVGPRICE AS TARGET_Q1_FM_VALUE,ABI.TARGET_Q1_PL,ABI.TARGET_Q1_PL * AVGP.AVGPRICE_PL AS TARGET_Q1_PL_VALUE, 
ABI.TARGET_Q2_FM,ABI.TARGET_Q2_FM * AVGP.AVGPRICE AS TARGET_Q2_FM_VALUE,ABI.TARGET_Q2_PL,ABI.TARGET_Q2_PL * AVGP.AVGPRICE_PL AS TARGET_Q2_PL_VALUE,
ABI.TARGET_Q3_FM,ABI.TARGET_Q3_FM * AVGP.AVGPRICE AS TARGET_Q3_FM_VALUE,ABI.TARGET_Q3_PL,ABI.TARGET_Q3_PL * AVGP.AVGPRICE_PL AS TARGET_Q3_PL_VALUE,
ABI.TARGET_Q4_FM,ABI.TARGET_Q4_FM * AVGP.AVGPRICE AS TARGET_Q4_FM_VALUE,ABI.TARGET_Q4_PL,ABI.TARGET_Q4_PL * AVGP.AVGPRICE_PL AS TARGET_Q4_PL_VALUE,
ABI.TARGET_S1_FM,ABI.TARGET_S1_FM * AVGP.AVGPRICE AS TARGET_S1_FM_VALUE,ABI.TARGET_S1_PL,ABI.TARGET_S1_PL * AVGP.AVGPRICE_PL AS TARGET_S1_PL_VALUE,
ABI.TARGET_S2_FM,ABI.TARGET_S2_FM * AVGP.AVGPRICE AS TARGET_S2_FM_VALUE,ABI.TARGET_S2_PL,ABI.TARGET_S2_PL * AVGP.AVGPRICE_PL AS TARGET_S2_PL_VALUE,
TARGET_YEAR_FM_VALUE = CASE
WHEN (AA.QS_TREATMENT_FLAG = 'Q') 
THEN ((ABI.TARGET_Q1_FM + ABI.TARGET_Q2_FM + ABI.TARGET_Q3_FM + ABI.TARGET_Q4_FM) * AVGP.AVGPRICE)
WHEN AA.QS_TREATMENT_FLAG = 'S'
THEN ((ABI.TARGET_S1_FM + ABI.TARGET_S2_FM) * AVGP.AVGPRICE)
ELSE 0 END,
TARGET_YEAR_PL_VALUE = CASE
WHEN (AA.QS_TREATMENT_FLAG = 'Q') 
THEN ((ABI.TARGET_Q1_PL + ABI.TARGET_Q2_PL + ABI.TARGET_Q3_PL + ABI.TARGET_Q4_PL) * AVGP.AVGPRICE_PL)
WHEN AA.QS_TREATMENT_FLAG = 'S'
THEN ((ABI.TARGET_S1_PL + ABI.TARGET_S2_PL) * AVGP.AVGPRICE_PL)
ELSE 0 END,ABI.CREATE_DATE,ABI.CREATE_BY,ABI.MODIFY_BY,ABI.MODIFY_DATE 
INTO Tempdb..##T_TargetAgreementReport
FROM  DIST_DISTRIBUTOR DR INNER JOIN DISTRIBUTOR_AGREEMENT DA ON DR.DISTRIBUTOR_ID = DA.DISTRIBUTOR_ID
INNER JOIN AGREE_AGREEMENT AA ON DA.AGREEMENT_NO = AA.AGREEMENT_NO
INNER JOIN AGREE_BRAND_INCLUDE ABI ON AA.AGREEMENT_NO = ABI.AGREEMENT_NO
INNER JOIN BRND_BRAND BN ON BN.BRAND_ID = ABI.BRAND_ID
INNER JOIN TERRITORY TER ON TER.TERRITORY_ID = DR.TERRITORY_ID
LEFT OUTER JOIN(
SELECT BRAND_ID,AVGPRICE,AVGPRICE_PL, START_PERIODE FROM BRND_AVGPRICE WHERE START_PERIODE >= @START_DATE
 )AVGP
 ON AVGP.START_PERIODE = AA.START_DATE AND AVGP.BRAND_ID = ABI.BRAND_ID
 AND BN.BRAND_ID = AVGP.BRAND_ID
WHERE AA.START_DATE >= @START_DATE AND AA.END_DATE <= @END_DATE;
CREATE NONCLUSTERED INDEX IX_T_TargetAgreementReport ON Tempdb..##T_TargetAgreementReport(CREATE_DATE,MODIFY_DATE);

SELECT * FROM Tempdb..##T_TargetAgreementReport ;
GO
--------------------------------------------------------------------------------------

---------------Report untuk menampilkan data PKD 4 months Periode-------------

----------PROCEDURE UNTUK MENAMPILKAN REPORT TOTAL PO & DISPRO PERDISTRIBUTOR PER PERIODE TERTENTU
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Get_Detail_Qty_Dispro' AND TYPE = 'P')
DROP PROCEDURE Usp_Get_Detail_Qty_Dispro                             
GO
CREATE PROCEDURE Usp_Get_Detail_Qty_Dispro
@DISTRIBUTOR_ID VARCHAR(10),
@START_DATE DATETIME,
@END_DATE DATETIME
AS
SET NOCOUNT ON;
IF (@DISTRIBUTOR_ID IS NULL)
  BEGIN
      SELECT DR.DISTRIBUTOR_ID,DR.DISTRIBUTOR_NAME,BR.BRAND_NAME,BB.BRANDPACK_NAME,(OPO.QTY_EVEN + ISNULL(OPO.LEFT_OA_QTY,0)) AS OA_QTY,OPO.RPK,
      OPO.DP,OPO.CP_D,OPO.CP_R,OPO.PKPP,OPO.DK,OPO.OTHERS,(ISNULL(OPO.TOTAL_DISC,0) + OPO.QTY_EVEN) AS TOTAL_DELIVERY,
      BBS.QUARTER_1 ,BBS.QUARTER_2 ,BBS.QUARTER_3,BBS.QUARTER_4,BBS.SEMESTER_1,
      BBS.SEMESTER_2 ,BBS.YEARLY,BBS.RELEASE_Q1 - OPO.REM_Q1 AS RELEASE_Q1,
      BBS.RELEASE_Q2 - OPO.REM_Q2 AS RELEASE_Q2,BBS.RELEASE_Q3 - OPO.REM_Q3 AS RELEASE_Q3,
      BBS.RELEASE_Q4 - OPO.REM_Q4 AS RELEASE_Q4,BBS.RELEASE_S1 - OPO.REM_S1 AS RELEASE_S1,
      BBS.RELEASE_S2 - OPO.REM_S2 AS RELEASE_S2,BBS.RELEASE_Y - OPO.REM_Y AS RELEASE_Y, 
      ISNULL((BBS.RELEASE_Q1 + BBS.RELEASE_Q2 + BBS.RELEASE_Q3 + BBS.RELEASE_Q4 + BBS.RELEASE_S1 + BBS.RELEASE_S2 + BBS.RELEASE_Y),0)
      - ISNULL((OPO.REM_Q1 + OPO.REM_Q2 + OPO.REM_Q3 + OPO.REM_Q4 + OPO.REM_S1 + OPO.REM_S2 + OPO.REM_Y),0)
      AS TOTAL_RELEASE,

      BBS.LEFT_Q1,BBS.LEFT_Q2,BBS.LEFT_Q3,BBS.LEFT_Q4,BBS.LEFT_S1, BBS.LEFT_S2,BBS.LEFT_Y,
      ISNULL((BBS.LEFT_Q1 + BBS.LEFT_Q2 + BBS.LEFT_Q3 + BBS.LEFT_Q4 + BBS.LEFT_S1 +  BBS.LEFT_S2 + BBS.LEFT_Y),0)
      AS TOTAL_LEFT,OPO.REM_Q1, OPO.REM_Q2, OPO.REM_Q3, OPO.REM_Q4, OPO.REM_S1, OPO.REM_S2, OPO.REM_Y,
	  (OPO.REM_Q1 + OPO.REM_Q2 + OPO.REM_Q3 + OPO.REM_Q4 + OPO.REM_S1 + OPO.REM_S2 + OPO.REM_Y) AS TOTAL_REMAIND
      FROM DIST_DISTRIBUTOR DR INNER JOIN
          (
            SELECT OPO.DISTRIBUTOR_ID,OPB.BRANDPACK_ID,ISNULL(SUM(OOB.QTY_EVEN),0) AS QTY_EVEN,ISNULL(SUM(OBD.RPK),0)AS RPK,
            ISNULL(SUM(OBD.OTHERS),0)AS OTHERS,ISNULL(SUM(OBD.LEFT_OA_QTY),0) AS LEFT_OA_QTY,
	    ISNULL(SUM(OBD.DP),0)AS DP,ISNULL(SUM(OBD.CP_D),0) AS CP_D,ISNULL(SUM(OBD.CP_R),0)AS CP_R,
            ISNULL(SUM(OBD.PKPP),0) AS PKPP,ISNULL(SUM(OBD.DK),0) AS DK,
            ISNULL(SUM(REM.REM_Q1),0)AS REM_Q1,ISNULL(SUM(REM.REM_Q2),0)AS REM_Q2,ISNULL(SUM(REM.REM_Q3),0)AS REM_Q3,
            ISNULL(SUM(REM.REM_Q4),0)AS REM_Q4,ISNULL(SUM(REM.REM_S1),0)AS REM_S1,
            ISNULL(SUM(REM.REM_S2),0)AS REM_S2,ISNULL(SUM(REM.REM_Y),0)AS REM_Y,
            ISNULL(SUM(OBD.TOTAL_DISC),0) AS TOTAL_DISC 
            FROM ORDR_PURCHASE_ORDER OPO INNER JOIN ORDR_PO_BRANDPACK OPB ON OPO.PO_REF_NO = OPB.PO_REF_NO
            INNER JOIN ORDR_OA_BRANDPACK OOB ON OOB.PO_BRANDPACK_ID = OPB.PO_BRANDPACK_ID     
            LEFT OUTER JOIN
                           (
                    	      SELECT OA_BRANDPACK_ID,
			      ISNULL(SUM(CASE GQSY_SGT_P_FLAG WHEN 'MG' THEN DISC_QTY ELSE 0 END),0) AS RPK,
			      ISNULL(SUM(CASE GQSY_SGT_P_FLAG WHEN 'O' THEN DISC_QTY ELSE 0 END),0)AS OTHERS,
		              ISNULL(SUM(CASE GQSY_SGT_P_FLAG WHEN 'RMOA' THEN DISC_QTY ELSE 0 END),0) AS LEFT_OA_QTY,
			      ISNULL(SUM(CASE GQSY_SGT_P_FLAG WHEN 'G' THEN DISC_QTY ELSE 0 END),0) AS DP,
			      ISNULL(SUM(CASE GQSY_SGT_P_FLAG WHEN 'CP' THEN DISC_QTY ELSE 0 END),0) AS CP_D,
			      ISNULL(SUM(CASE GQSY_SGT_P_FLAG WHEN 'SC' THEN DISC_QTY ELSE 0 END),0) AS CP_D_S,
				  ISNULL(SUM(CASE GQSY_SGT_P_FLAG WHEN 'CD' THEN DISC_QTY WHEN 'CT' THEN DISC_QTY ELSE 0 END),0) AS CP_RMT,
			      ISNULL(SUM(CASE GQSY_SGT_P_FLAG WHEN 'CR' THEN DISC_QTY ELSE 0 END),0) AS CP_R,
        		      ISNULL(SUM(CASE GQSY_SGT_P_FLAG WHEN 'KP' THEN DISC_QTY ELSE 0 END),0)AS PKPP,
			      ISNULL(SUM(CASE GQSY_SGT_P_FLAG WHEN 'DK' THEN DISC_QTY WHEN 'DN' THEN DISC_QTY ELSE 0 END),0) AS DK,
			      ISNULL(SUM(DISC_QTY),0) AS TOTAL_DISC
			      FROM ORDR_OA_BRANDPACK_DISC
			      GROUP BY OA_BRANDPACK_ID
                    	    )OBD
             ON OOB.OA_BRANDPACK_ID = OBD.OA_BRANDPACK_ID
             LEFT OUTER JOIN (
                               SELECT OA_BRANDPACK_ID,
                               ISNULL(SUM(CASE FLAG WHEN 'Q1' THEN LEFT_QTY ELSE 0 END),0) AS REM_Q1,
			       ISNULL(SUM(CASE FLAG WHEN 'Q2' THEN LEFT_QTY ELSE 0 END),0) AS REM_Q2,
			       ISNULL(SUM(CASE FLAG WHEN 'Q3' THEN LEFT_QTY ELSE 0 END),0) AS REM_Q3,
			       ISNULL(SUM(CASE FLAG WHEN 'Q4' THEN LEFT_QTY ELSE 0 END),0) AS REM_Q4,
			       ISNULL(SUM(CASE FLAG WHEN 'S1' THEN LEFT_QTY ELSE 0 END),0) AS REM_S1,
			       ISNULL(SUM(CASE FLAG WHEN 'S2' THEN LEFT_QTY ELSE 0 END),0) AS REM_S2,
        		       ISNULL(SUM(CASE FLAG WHEN 'Y' THEN  LEFT_QTY ELSE 0 END),0)AS REM_Y
                               FROM ORDR_OA_REMAINDING GROUP BY OA_BRANDPACK_ID
			     )REM
             ON OOB.OA_BRANDPACK_ID = REM.OA_BRANDPACK_ID 
	     WHERE OPO.PO_REF_DATE >= @START_DATE AND OPO.PO_REF_DATE <= @END_DATE
	     GROUP BY OPO.DISTRIBUTOR_ID,OPB.BRANDPACK_ID
          )OPO
     ON OPO.DISTRIBUTOR_ID = DR.DISTRIBUTOR_ID
     INNER JOIN BRND_BRANDPACK BB ON BB.BRANDPACK_ID = OPO.BRANDPACK_ID
     INNER JOIN BRND_BRAND BR ON BR.BRAND_ID = BB.BRAND_ID

     LEFT OUTER JOIN(
                      SELECT BBS.DISTRIBUTOR_ID,ABI.BRANDPACK_ID,
      		      SUM(CASE BBS.QSY_FLAG WHEN 'Q1' THEN DISC_QTY ELSE 0 END)AS QUARTER_1,
    		      SUM(CASE BBS.QSY_FLAG WHEN 'Q2' THEN DISC_QTY ELSE 0 END)AS QUARTER_2,
    		      SUM(CASE BBS.QSY_FLAG WHEN 'Q3' THEN DISC_QTY ELSE 0 END)AS QUARTER_3,
    		      SUM(CASE BBS.QSY_FLAG WHEN 'Q4' THEN DISC_QTY ELSE 0 END) AS QUARTER_4,
    		      SUM(CASE BBS.QSY_FLAG WHEN 'S1' THEN DISC_QTY ELSE 0 END)AS SEMESTER_1,
    		      SUM(CASE BBS.QSY_FLAG WHEN 'S2' THEN DISC_QTY ELSE 0 END)AS SEMESTER_2,
    		      SUM(CASE BBS.QSY_FLAG WHEN 'Y' THEN DISC_QTY ELSE 0 END)AS YEARLY,
    		      SUM(CASE BBS.QSY_FLAG WHEN 'Q1' THEN RELEASE_QTY ELSE 0 END)AS RELEASE_Q1,
    		      SUM(CASE BBS.QSY_FLAG WHEN 'Q2' THEN RELEASE_QTY ELSE 0 END)AS RELEASE_Q2,
		      SUM(CASE BBS.QSY_FLAG WHEN 'Q3' THEN RELEASE_QTY ELSE 0 END)AS RELEASE_Q3,
		      SUM(CASE BBS.QSY_FLAG WHEN 'Q4' THEN RELEASE_QTY ELSE 0 END)AS RELEASE_Q4,
		      SUM(CASE BBS.QSY_FLAG WHEN 'S1' THEN RELEASE_QTY ELSE 0 END)AS RELEASE_S1,
		      SUM(CASE BBS.QSY_FLAG WHEN 'S2' THEN RELEASE_QTY ELSE 0 END)AS RELEASE_S2,
		      SUM(CASE BBS.QSY_FLAG WHEN 'Y' THEN RELEASE_QTY ELSE 0 END)AS RELEASE_Y,
		      SUM(CASE BBS.QSY_FLAG WHEN 'Q1' THEN LEFT_QTY ELSE 0 END)AS LEFT_Q1,
		      SUM(CASE BBS.QSY_FLAG WHEN 'Q2' THEN LEFT_QTY ELSE 0 END) AS LEFT_Q2,
		      SUM(CASE BBS.QSY_FLAG WHEN 'Q3'THEN LEFT_QTY ELSE 0 END)AS LEFT_Q3,
		      SUM(CASE BBS.QSY_FLAG WHEN 'Q4' THEN LEFT_QTY ELSE 0 END) AS LEFT_Q4,
		      SUM(CASE BBS.QSY_FLAG WHEN 'S1' THEN LEFT_QTY ELSE 0 END)AS LEFT_S1,
		      SUM(CASE BBS.QSY_FLAG WHEN 'S2' THEN LEFT_QTY ELSE 0 END)AS LEFT_S2,
		      SUM(CASE BBS.QSY_FLAG WHEN 'Y' THEN LEFT_QTY ELSE 0 END)AS LEFT_Y
		   
		      FROM AGREE_BRANDPACK_INCLUDE ABI LEFT OUTER JOIN BRND_BRANDPACK_SAVING BBS
		      ON ABI.AGREE_BRANDPACK_ID = BBS.AGREE_BRANDPACK_ID
		      WHERE ABI.AGREE_BRANDPACK_ID IN(SELECT AGREE_BRANDPACK_ID FROM AGREE_BRANDPACK_INCLUDE
		      WHERE AGREEMENT_NO IN(SELECT DISTINCT AA.AGREEMENT_NO FROM AGREE_AGREEMENT AA
		      INNER JOIN DISTRIBUTOR_AGREEMENT DA ON DA.AGREEMENT_NO = AA.AGREEMENT_NO
		      WHERE DA.DISTRIBUTOR_ID = BBS.DISTRIBUTOR_ID AND AA.START_DATE >= @START_DATE
		      AND AA.END_DATE <= @END_DATE))--YEAR(AA.END_DATE) >= YEAR(GETDATE()) - 1))
		      GROUP BY BBS.DISTRIBUTOR_ID,ABI.BRANDPACK_ID
                     )BBS
     ON OPO.BRANDPACK_ID = BBS.BRANDPACK_ID
     AND BBS.DISTRIBUTOR_ID = DR.DISTRIBUTOR_ID
  END
ELSE
  BEGIN
      SELECT DR.DISTRIBUTOR_ID,DR.DISTRIBUTOR_NAME,BR.BRAND_NAME,BB.BRANDPACK_NAME,(OPO.QTY_EVEN + ISNULL(OPO.LEFT_OA_QTY,0)) AS OA_QTY,OPO.RPK,
      OPO.DP,OPO.CP_D,OPO.CP_R,OPO.PKPP,OPO.DK,OPO.OTHERS,(ISNULL(OPO.TOTAL_DISC,0) + OPO.QTY_EVEN) AS TOTAL_DELIVERY,
      BBS.QUARTER_1 ,BBS.QUARTER_2 ,BBS.QUARTER_3,BBS.QUARTER_4,BBS.SEMESTER_1,
      BBS.SEMESTER_2 ,BBS.YEARLY,BBS.RELEASE_Q1 - OPO.REM_Q1 AS RELEASE_Q1,
      BBS.RELEASE_Q2 - OPO.REM_Q2 AS RELEASE_Q2,BBS.RELEASE_Q3 - OPO.REM_Q3 AS RELEASE_Q3,
      BBS.RELEASE_Q4 - OPO.REM_Q4 AS RELEASE_Q4,BBS.RELEASE_S1 - OPO.REM_S1 AS RELEASE_S1,
      BBS.RELEASE_S2 - OPO.REM_S2 AS RELEASE_S2,BBS.RELEASE_Y - OPO.REM_Y AS RELEASE_Y, 
      ISNULL((BBS.RELEASE_Q1 + BBS.RELEASE_Q2 + BBS.RELEASE_Q3 + BBS.RELEASE_Q4 + BBS.RELEASE_S1 + BBS.RELEASE_S2 + BBS.RELEASE_Y),0)
      - ISNULL((OPO.REM_Q1 + OPO.REM_Q2 + OPO.REM_Q3 + OPO.REM_Q4 + OPO.REM_S1 + OPO.REM_S2 + OPO.REM_Y),0)
      AS TOTAL_RELEASE,

      BBS.LEFT_Q1,BBS.LEFT_Q2,BBS.LEFT_Q3,BBS.LEFT_Q4,BBS.LEFT_S1, BBS.LEFT_S2,BBS.LEFT_Y,
      ISNULL((BBS.LEFT_Q1 + BBS.LEFT_Q2 + BBS.LEFT_Q3 + BBS.LEFT_Q4 + BBS.LEFT_S1 +  BBS.LEFT_S2 + BBS.LEFT_Y),0)
      AS TOTAL_LEFT,OPO.REM_Q1, OPO.REM_Q2, OPO.REM_Q3, OPO.REM_Q4, OPO.REM_S1, OPO.REM_S2, OPO.REM_Y,
	  (OPO.REM_Q1 + OPO.REM_Q2 + OPO.REM_Q3 + OPO.REM_Q4 + OPO.REM_S1 + OPO.REM_S2 + OPO.REM_Y) AS TOTAL_REMAIND
      FROM DIST_DISTRIBUTOR DR INNER JOIN
       (
          SELECT OPO.DISTRIBUTOR_ID,OPB.BRANDPACK_ID,ISNULL(SUM(OOB.QTY_EVEN),0) AS QTY_EVEN,
          ISNULL(SUM(OBD.RPK),0)AS RPK,ISNULL(SUM(OBD.OTHERS),0)AS OTHERS,ISNULL(SUM(OBD.LEFT_OA_QTY),0) AS LEFT_OA_QTY,
          ISNULL(SUM(OBD.DP),0)AS DP,ISNULL(SUM(OBD.CP_D),0)AS CP_D,ISNULL(SUM(OBD.CP_R),0)AS CP_R,
          ISNULL(SUM(OBD.PKPP),0) AS PKPP,ISNULL(SUM(OBD.DK),0) AS DK,
          ISNULL(SUM(REM.REM_Q1),0)AS REM_Q1,ISNULL(SUM(REM.REM_Q2),0)AS REM_Q2,ISNULL(SUM(REM.REM_Q3),0)AS REM_Q3,
          ISNULL(SUM(REM.REM_Q4),0)AS REM_Q4,ISNULL(SUM(REM.REM_S1),0)AS REM_S1,
          ISNULL(SUM(REM.REM_S2),0)AS REM_S2,ISNULL(SUM(REM.REM_Y),0)AS REM_Y,
          ISNULL(SUM(OBD.TOTAL_DISC),0) AS TOTAL_DISC FROM ORDR_PURCHASE_ORDER OPO INNER JOIN ORDR_PO_BRANDPACK
          OPB ON OPO.PO_REF_NO = OPB.PO_REF_NO
          INNER JOIN ORDR_OA_BRANDPACK OOB ON OOB.PO_BRANDPACK_ID = OPB.PO_BRANDPACK_ID     
          LEFT OUTER JOIN (
        		    SELECT OA_BRANDPACK_ID,
			    ISNULL(SUM(CASE GQSY_SGT_P_FLAG WHEN 'MG' THEN DISC_QTY ELSE 0 END),0) AS RPK,
			    ISNULL(SUM(CASE GQSY_SGT_P_FLAG WHEN 'O' THEN DISC_QTY ELSE 0 END),0)AS OTHERS,
			    ISNULL(SUM(CASE GQSY_SGT_P_FLAG WHEN 'RMOA' THEN DISC_QTY ELSE 0 END),0) AS LEFT_OA_QTY,
			    ISNULL(SUM(CASE GQSY_SGT_P_FLAG WHEN 'G' THEN DISC_QTY ELSE 0 END),0) AS DP,
			    ISNULL(SUM(CASE GQSY_SGT_P_FLAG WHEN 'CP' THEN DISC_QTY ELSE 0 END),0) AS CP_D,
			    ISNULL(SUM(CASE GQSY_SGT_P_FLAG WHEN 'SC' THEN DISC_QTY ELSE 0 END),0) AS CP_D_S,
				ISNULL(SUM(CASE GQSY_SGT_P_FLAG	WHEN 'CD' THEN DISC_QTY WHEN 'CT' THEN DISC_QTY ELSE 0 END),0) AS CP_RMT,
			    ISNULL(SUM(CASE GQSY_SGT_P_FLAG WHEN 'CR' THEN DISC_QTY ELSE 0 END),0) AS CP_R,
        		    ISNULL(SUM(CASE GQSY_SGT_P_FLAG WHEN 'KP' THEN DISC_QTY ELSE 0 END),0)AS PKPP,
			    ISNULL(SUM(CASE GQSY_SGT_P_FLAG WHEN 'DK' THEN DISC_QTY WHEN 'DN' THEN DISC_QTY ELSE 0 END),0) AS DK,
			    ISNULL(SUM(DISC_QTY),0) AS TOTAL_DISC
			    FROM ORDR_OA_BRANDPACK_DISC
			    GROUP BY OA_BRANDPACK_ID
                         )OBD
          ON OOB.OA_BRANDPACK_ID = OBD.OA_BRANDPACK_ID
          LEFT OUTER JOIN (
                           SELECT OA_BRANDPACK_ID,
                           ISNULL(SUM(CASE FLAG WHEN 'Q1' THEN LEFT_QTY ELSE 0 END),0) AS REM_Q1,
			   ISNULL(SUM(CASE FLAG WHEN 'Q2' THEN LEFT_QTY ELSE 0 END),0) AS REM_Q2,
			   ISNULL(SUM(CASE FLAG WHEN 'Q3' THEN LEFT_QTY ELSE 0 END),0) AS REM_Q3,
			   ISNULL(SUM(CASE FLAG WHEN 'Q4' THEN LEFT_QTY ELSE 0 END),0) AS REM_Q4,
			   ISNULL(SUM(CASE FLAG WHEN 'S1' THEN LEFT_QTY ELSE 0 END),0) AS REM_S1,
			   ISNULL(SUM(CASE FLAG WHEN 'S2' THEN LEFT_QTY ELSE 0 END),0) AS REM_S2,
        		   ISNULL(SUM(CASE FLAG WHEN 'Y' THEN LEFT_QTY ELSE 0 END),0)AS REM_Y
                           FROM ORDR_OA_REMAINDING GROUP BY OA_BRANDPACK_ID
			  )REM
          ON OOB.OA_BRANDPACK_ID = REM.OA_BRANDPACK_ID
          WHERE OPO.PO_REF_DATE >= @START_DATE AND OPO.PO_REF_DATE <= @END_DATE 
          GROUP BY OPO.DISTRIBUTOR_ID,OPB.BRANDPACK_ID
       )OPO
       ON OPO.DISTRIBUTOR_ID = DR.DISTRIBUTOR_ID
      INNER JOIN BRND_BRANDPACK BB ON BB.BRANDPACK_ID = OPO.BRANDPACK_ID
      INNER JOIN BRND_BRAND BR ON BR.BRAND_ID = BB.BRAND_ID
  
      LEFT OUTER JOIN(
                       SELECT BBS.DISTRIBUTOR_ID,ABI.BRANDPACK_ID,
      		       SUM(CASE BBS.QSY_FLAG WHEN 'Q1' THEN DISC_QTY ELSE 0 END)AS QUARTER_1,
      		       SUM(CASE BBS.QSY_FLAG WHEN 'Q2' THEN DISC_QTY ELSE 0 END)AS QUARTER_2,
	               SUM(CASE BBS.QSY_FLAG WHEN 'Q3' THEN DISC_QTY ELSE 0 END)AS QUARTER_3,
		       SUM(CASE BBS.QSY_FLAG WHEN 'Q4' THEN DISC_QTY ELSE 0 END) AS QUARTER_4,
		       SUM(CASE BBS.QSY_FLAG WHEN 'S1' THEN DISC_QTY ELSE 0 END)AS SEMESTER_1,
		       SUM(CASE BBS.QSY_FLAG WHEN 'S2' THEN DISC_QTY ELSE 0 END)AS SEMESTER_2,
		       SUM(CASE BBS.QSY_FLAG WHEN 'Y' THEN DISC_QTY ELSE 0 END)AS YEARLY,
		       SUM(CASE BBS.QSY_FLAG WHEN 'Q1' THEN RELEASE_QTY ELSE 0 END)AS RELEASE_Q1,
		       SUM(CASE BBS.QSY_FLAG WHEN 'Q2' THEN RELEASE_QTY ELSE 0 END)AS RELEASE_Q2,
		       SUM(CASE BBS.QSY_FLAG WHEN 'Q3' THEN RELEASE_QTY ELSE 0 END)AS RELEASE_Q3,
		       SUM(CASE BBS.QSY_FLAG WHEN 'Q4' THEN RELEASE_QTY ELSE 0 END)AS RELEASE_Q4,
		       SUM(CASE BBS.QSY_FLAG WHEN 'S1' THEN RELEASE_QTY ELSE 0 END)AS RELEASE_S1,
		       SUM(CASE BBS.QSY_FLAG WHEN 'S2' THEN RELEASE_QTY ELSE 0 END)AS RELEASE_S2,
		       SUM(CASE BBS.QSY_FLAG WHEN 'Y' THEN RELEASE_QTY ELSE 0 END)AS RELEASE_Y,
		       SUM(CASE BBS.QSY_FLAG WHEN 'Q1' THEN LEFT_QTY ELSE 0 END)AS LEFT_Q1,
		       SUM(CASE BBS.QSY_FLAG WHEN 'Q2' THEN LEFT_QTY ELSE 0 END) AS LEFT_Q2,
		       SUM(CASE BBS.QSY_FLAG WHEN 'Q3'THEN LEFT_QTY ELSE 0 END)AS LEFT_Q3,
		       SUM(CASE BBS.QSY_FLAG WHEN 'Q4' THEN LEFT_QTY ELSE 0 END) AS LEFT_Q4,
		       SUM(CASE BBS.QSY_FLAG WHEN 'S1' THEN LEFT_QTY ELSE 0 END)AS LEFT_S1,
		       SUM(CASE BBS.QSY_FLAG WHEN 'S2' THEN LEFT_QTY ELSE 0 END)AS LEFT_S2,
		       SUM(CASE BBS.QSY_FLAG WHEN 'Y' THEN LEFT_QTY ELSE 0 END)AS LEFT_Y
		   
		       FROM AGREE_BRANDPACK_INCLUDE ABI LEFT OUTER JOIN BRND_BRANDPACK_SAVING BBS
		       ON ABI.AGREE_BRANDPACK_ID = BBS.AGREE_BRANDPACK_ID
		       WHERE ABI.AGREE_BRANDPACK_ID IN(SELECT AGREE_BRANDPACK_ID FROM AGREE_BRANDPACK_INCLUDE
		       WHERE AGREEMENT_NO IN(SELECT AA.AGREEMENT_NO FROM AGREE_AGREEMENT AA
		       INNER JOIN DISTRIBUTOR_AGREEMENT DA ON DA.AGREEMENT_NO = AA.AGREEMENT_NO
		       WHERE DA.DISTRIBUTOR_ID = BBS.DISTRIBUTOR_ID AND AA.START_DATE >= @START_DATE
		          AND AA.END_DATE <= @END_DATE))
		       GROUP BY BBS.DISTRIBUTOR_ID,ABI.BRANDPACK_ID
		     )BBS
       ON OPO.BRANDPACK_ID = BBS.BRANDPACK_ID
       AND BBS.DISTRIBUTOR_ID = OPO.DISTRIBUTOR_ID
       WHERE OPO.DISTRIBUTOR_ID = @DISTRIBUTOR_ID
  END
GO
 
--EXEC Usp_Get_Detail_Qty_Dispro
--@DISTRIBUTOR_ID = 'MUL007000',
--@START_DATE = '06/01/2009',
--@END_DATE = '06/30/2009'--NULL 
-----------------------------------------------------------------------------------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Get_Total_PO_Dispro_Brand_By_Invoice' AND TYPE = 'P')
   DROP PROCEDURE Usp_Get_Total_PO_Dispro_Brand_By_Invoice
GO
CREATE PROCEDURE Usp_Get_Total_PO_Dispro_Brand_By_Invoice
@START_DATE SMALLDATETIME,@END_DATE SMALLDATETIME
AS
SET NOCOUNT ON;
--CHECK APAKAH SEKARANG SUDAH KE INVOICE / BELUM
DECLARE @V_DISC_FROM VARCHAR(50);
--RPT002 = Setting untuk menentukan Report Report Summary Dispro by Brand di hubungkan ke invoice = 1,PO = 0
IF (SELECT AllowRules FROM RefBussinesRules WHERE CodeApp = 'RPT002') = 1
 BEGIN
	SELECT ACRH.BRAND_ID,BR.BRAND_NAME,ACRH.TOTAL_Q1,ACRH.TOTAL_Q2,ACRH.TOTAL_Q3,ACRH.TOTAL_Q4,
	ACRH.TOTAL_S1,ACRH.TOTAL_S2,ACRH.TOTAL_YEAR FROM BRND_BRAND BR
	 INNER JOIN(SELECT ACRH.BRAND_ID,
	            ISNULL(SUM(CASE WHEN ACRH.FLAG = 'Q1' THEN ACRH.BONUS_DISTRIBUTOR END),0)AS TOTAL_Q1,
	            ISNULL(SUM(CASE WHEN ACRH.FLAG = 'Q2' THEN ACRH.BONUS_DISTRIBUTOR END),0)AS TOTAL_Q2,
		    ISNULL(SUM(CASE WHEN ACRH.FLAG = 'Q3' THEN ACRH.BONUS_DISTRIBUTOR END),0)AS TOTAL_Q3,
		    ISNULL(SUM(CASE WHEN ACRH.FLAG = 'Q4' THEN ACRH.BONUS_DISTRIBUTOR END),0)AS TOTAL_Q4,
		    ISNULL(SUM(CASE WHEN ACRH.FLAG = 'S1' THEN ACRH.BONUS_DISTRIBUTOR END),0)AS TOTAL_S1,
		    ISNULL(SUM(CASE WHEN ACRH.FLAG = 'S2' THEN ACRH.BONUS_DISTRIBUTOR END),0)AS TOTAL_S2,
		    ISNULL(SUM(CASE WHEN ACRH.FLAG = 'Y' THEN ACRH.BONUS_DISTRIBUTOR END),0)AS TOTAL_YEAR
	            FROM ACCRUED_HEADER ACRH 
                    INNER JOIN AGREE_AGREEMENT AA ON AA.AGREEMENT_NO = ACRH.AGREEMENT_NO
 		    WHERE AA.START_DATE >= @START_DATE AND AA.END_DATE <= @END_DATE
		    GROUP BY ACRH.BRAND_ID
	           )ACRH
	ON BR.BRAND_ID = ACRH.BRAND_ID;
 END
ELSE
 BEGIN
	SELECT DP.BRAND_ID,BR.BRAND_NAME,DP.TOTAL_Q1,DP.TOTAL_Q2,DP.TOTAL_Q3,DP.TOTAL_Q4,DP.TOTAL_S1,
	DP.TOTAL_S2,DP.TOTAL_YEAR
	FROM (
		SELECT ABI.BRAND_ID,ISNULL(SUM(CASE WHEN QSY_FLAG = 'Q1' THEN DISC_QTY END),0)AS TOTAL_Q1,
		ISNULL(SUM(CASE WHEN BBS.QSY_FLAG = 'Q2' THEN BBS.DISC_QTY END),0)AS TOTAL_Q2,
		ISNULL(SUM(CASE WHEN BBS.QSY_FLAG = 'Q3' THEN BBS.DISC_QTY END),0)AS TOTAL_Q3,
		ISNULL(SUM(CASE WHEN BBS.QSY_FLAG = 'Q4' THEN BBS.DISC_QTY END),0)AS TOTAL_Q4,
		ISNULL(SUM(CASE WHEN BBS.QSY_FLAG = 'S1' THEN BBS.DISC_QTY END),0) AS TOTAL_S1,
		ISNULL(SUM(CASE WHEN BBS.QSY_FLAG = 'S2' THEN BBS.DISC_QTY END),0) AS TOTAL_S2,
		ISNULL(SUM(CASE WHEN BBS.QSY_FLAG = 'Y' THEN BBS.DISC_QTY END),0) AS TOTAL_YEAR
		FROM AGREE_BRAND_INCLUDE ABI INNER JOIN AGREE_AGREEMENT AA ON AA.AGREEMENT_NO = ABI.AGREEMENT_NO
		INNER JOIN AGREE_BRANDPACK_INCLUDE ABP ON ABP.AGREE_BRAND_ID = ABI.AGREE_BRAND_ID
		INNER JOIN BRND_BRANDPACK_SAVING BBS ON BBS.AGREE_BRANDPACK_ID = ABP.AGREE_BRANDPACK_ID
		WHERE AA.END_DATE >= @START_DATE 
	        AND AA.END_DATE <= @END_DATE
		GROUP BY ABI.BRAND_ID
	    )DP
	INNER JOIN BRND_BRAND BR ON BR.BRAND_ID = DP.BRAND_ID
 END
GO

----------PROCEDURE UNTUK MENAMPILKAN REPORT TOTAL PER BRAND(DI GROUP BERDASARKAN BRANDPACK SAJA) TIDAK DENGAN DISTRIBUTOR NYA
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Get_Total_PO_Dispro_By_Brand' AND TYPE = 'P')
 DROP PROCEDURE Usp_Get_Total_PO_Dispro_By_Brand
GO
--CREATE PROCEDURE Usp_Get_Total_PO_Dispro_By_Brand
--@START_DATE DATETIME,
--@END_DATE DATETIME
--AS
--SET NOCOUNT ON;
  -- BEGIN
      	
    --  SELECT BR.BRAND_NAME,BB.BRANDPACK_NAME,(OPO.QTY_EVEN + ISNULL(OPO.LEFT_OA_QTY,0)) AS OA_QTY,OPO.RPK,
     -- OPO.DP,OPO.CP_D,OPO.CP_R,OPO.PKPP,OPO.DK,OPO.OTHERS,(ISNULL(OPO.TOTAL_DISC,0) + OPO.QTY_EVEN) AS TOTAL_DELIVERY,
     -- BBS.QUARTER_1 ,BBS.QUARTER_2 ,BBS.QUARTER_3,BBS.QUARTER_4,BBS.SEMESTER_1,
     -- BBS.SEMESTER_2 ,BBS.YEARLY,BBS.RELEASE_Q1,BBS.RELEASE_Q2,BBS.RELEASE_Q3,
     -- BBS.RELEASE_Q4,BBS.RELEASE_S1,BBS.RELEASE_S2,BBS.RELEASE_Y, 
      --BBS.LEFT_Q1,BBS.LEFT_Q2,BBS.LEFT_Q3,BBS.LEFT_Q4,BBS.LEFT_S1,
      --BBS.LEFT_S2,BBS.LEFT_Y,
       --ISNULL((BBS.RELEASE_Q1 + BBS.RELEASE_Q2 + BBS.RELEASE_Q3 + BBS.RELEASE_Q4 + BBS.RELEASE_S1 + BBS.RELEASE_S2 + BBS.RELEASE_Y),0)
	--AS TOTAL_RELEASE,
      --BBS.LEFT_Q1,BBS.LEFT_Q2,BBS.LEFT_Q3,BBS.LEFT_Q4,BBS.LEFT_S1,
      --BBS.LEFT_S2,BBS.LEFT_Y,
      --ISNULL((BBS.LEFT_Q1 + BBS.LEFT_Q2 + BBS.LEFT_Q3 + BBS.LEFT_Q4 + BBS.LEFT_S1 +  BBS.LEFT_S2 + BBS.LEFT_Y),0)
--	AS TOTAL_LEFT
  --    FROM        
    --   (SELECT OPB.BRANDPACK_ID,SUM(OOB.QTY_EVEN) AS QTY_EVEN,SUM(OBD.RPK)AS RPK,SUM(OBD.OTHERS)AS OTHERS,SUM(OBD.LEFT_OA_QTY) AS LEFT_OA_QTY,
--	SUM(OBD.DP)AS DP,SUM(OBD.CP_D) AS CP_D,SUM(OBD.CP_R)AS CP_R,SUM(OBD.PKPP) AS PKPP,SUM(OBD.DK) AS DK,
 --        SUM(OBD.TOTAL_DISC) AS TOTAL_DISC FROM ORDR_PURCHASE_ORDER OPO INNER JOIN ORDR_PO_BRANDPACK
 --        OPB ON OPO.PO_REF_NO = OPB.PO_REF_NO
  --       INNER JOIN ORDR_OA_BRANDPACK OOB ON OOB.PO_BRANDPACK_ID = OPB.PO_BRANDPACK_ID     
 --       LEFT OUTER JOIN
 --      (SELECT OA_BRANDPACK_ID,
--	ISNULL(SUM(CASE GQSY_SGT_P_FLAG WHEN 'MG' THEN DISC_QTY ELSE 0 END),0) AS RPK,
--	ISNULL(SUM(CASE GQSY_SGT_P_FLAG WHEN 'O' THEN DISC_QTY ELSE 0 END),0)AS OTHERS,
--	ISNULL(SUM(CASE GQSY_SGT_P_FLAG WHEN 'RMOA' THEN DISC_QTY ELSE 0 END),0) AS LEFT_OA_QTY,
--	ISNULL(SUM(CASE GQSY_SGT_P_FLAG WHEN 'G' THEN DISC_QTY ELSE 0 END),0) AS DP,
--	ISNULL(SUM(CASE GQSY_SGT_P_FLAG WHEN 'CPD' THEN DISC_QTY ELSE 0 END),0) AS CP_D,
--	ISNULL(SUM(CASE GQSY_SGT_P_FLAG WHEN 'CPR' THEN DISC_QTY ELSE 0 END),0) AS CP_R,
--       ISNULL(SUM(CASE GQSY_SGT_P_FLAG WHEN 'KP' THEN DISC_QTY ELSE 0 END),0)AS PKPP,
--	ISNULL(SUM(CASE GQSY_SGT_P_FLAG WHEN 'DK' THEN DISC_QTY ELSE 0 END),0) AS DK,
--	ISNULL(SUM(DISC_QTY),0) AS TOTAL_DISC
--	FROM ORDR_OA_BRANDPACK_DISC
--	GROUP BY OA_BRANDPACK_ID)OBD
 --        ON OOB.OA_BRANDPACK_ID = OBD.OA_BRANDPACK_ID 
--	 WHERE OPO.PO_REF_DATE >= @START_DATE AND OPO.PO_REF_DATE <= @END_DATE
	 --GROUP BY OPB.BRANDPACK_ID
         --)OPO
	
--        INNER JOIN BRND_BRANDPACK BB ON BB.BRANDPACK_ID = OPO.BRANDPACK_ID
 --       INNER JOIN (SELECT DISTINCT BRANDPACK_ID FROM AGREE_BRANDPACK_INCLUDE)ABI ON ABI.BRANDPACK_ID = OPO.BRANDPACK_ID
  --      INNER JOIN BRND_BRAND BR ON BR.BRAND_ID = BB.BRAND_ID

--    LEFT OUTER JOIN(SELECT ABI.BRANDPACK_ID,
--    SUM(CASE BBS.QSY_FLAG WHEN 'Q1' THEN DISC_QTY ELSE 0 END)AS QUARTER_1,
--    SUM(CASE BBS.QSY_FLAG WHEN 'Q2' THEN DISC_QTY ELSE 0 END)AS QUARTER_2,
--    SUM(CASE BBS.QSY_FLAG WHEN 'Q3' THEN DISC_QTY ELSE 0 END)AS QUARTER_3,
--    SUM(CASE BBS.QSY_FLAG WHEN 'Q4' THEN DISC_QTY ELSE 0 END) AS QUARTER_4,
--    SUM(CASE BBS.QSY_FLAG WHEN 'S1' THEN DISC_QTY ELSE 0 END)AS SEMESTER_1,
--    SUM(CASE BBS.QSY_FLAG WHEN 'S2' THEN DISC_QTY ELSE 0 END)AS SEMESTER_2,
--    SUM(CASE BBS.QSY_FLAG WHEN 'Y' THEN DISC_QTY ELSE 0 END)AS YEARLY,
--    SUM(CASE BBS.QSY_FLAG WHEN 'Q1' THEN RELEASE_QTY ELSE 0 END)AS RELEASE_Q1,
--    SUM(CASE BBS.QSY_FLAG WHEN 'Q2' THEN RELEASE_QTY ELSE 0 END)AS RELEASE_Q2,
--    SUM(CASE BBS.QSY_FLAG WHEN 'Q3' THEN RELEASE_QTY ELSE 0 END)AS RELEASE_Q3,
--    SUM(CASE BBS.QSY_FLAG WHEN 'Q4' THEN RELEASE_QTY ELSE 0 END)AS RELEASE_Q4,
--    SUM(CASE BBS.QSY_FLAG WHEN 'S1' THEN RELEASE_QTY ELSE 0 END)AS RELEASE_S1,
--    SUM(CASE BBS.QSY_FLAG WHEN 'S2' THEN RELEASE_QTY ELSE 0 END)AS RELEASE_S2,
--    SUM(CASE BBS.QSY_FLAG WHEN 'Y' THEN RELEASE_QTY ELSE 0 END)AS RELEASE_Y,
--    SUM(CASE BBS.QSY_FLAG WHEN 'Q1' THEN LEFT_QTY ELSE 0 END)AS LEFT_Q1,
--    SUM(CASE BBS.QSY_FLAG WHEN 'Q2' THEN LEFT_QTY ELSE 0 END) AS LEFT_Q2,
--    SUM(CASE BBS.QSY_FLAG WHEN 'Q3'THEN LEFT_QTY ELSE 0 END)AS LEFT_Q3,
--    SUM(CASE BBS.QSY_FLAG WHEN 'Q4' THEN LEFT_QTY ELSE 0 END) AS LEFT_Q4,
--    SUM(CASE BBS.QSY_FLAG WHEN 'S1' THEN LEFT_QTY ELSE 0 END)AS LEFT_S1,
--    SUM(CASE BBS.QSY_FLAG WHEN 'S2' THEN LEFT_QTY ELSE 0 END)AS LEFT_S2,
--    SUM(CASE BBS.QSY_FLAG WHEN 'Y' THEN LEFT_QTY ELSE 0 END)AS LEFT_Y
   
--    FROM AGREE_BRANDPACK_INCLUDE ABI LEFT OUTER JOIN BRND_BRANDPACK_SAVING BBS
--    ON ABI.AGREE_BRANDPACK_ID = BBS.AGREE_BRANDPACK_ID
--    WHERE ABI.AGREE_BRANDPACK_ID IN(SELECT AGREE_BRANDPACK_ID FROM AGREE_BRANDPACK_INCLUDE
--    WHERE AGREEMENT_NO IN(SELECT DISTINCT AGREEMENT_NO FROM AGREE_AGREEMENT 
--        WHERE START_DATE = @START_DATE AND END_DATE = @END_DATE))
--     GROUP BY ABI.BRANDPACK_ID)BBS
--    ON OPO.BRANDPACK_ID = BBS.BRANDPACK_ID
--  END
--GO

--EXEC Usp_Get_Total_PO_Dispro_By_Brand
--@DISTRIBUTOR_ID = NULL,
--@START_DATE = '09/03/2008',
--@END_DATE = '09/03/2009'--NULL 
--PO-2009/01/04/021

IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME  ='Usp_Get_Detail_Qty_Dispro_By_Invoice' 
           AND TYPE = 'P')
DROP PROCEDURE Usp_Get_Detail_Qty_Dispro_By_Invoice
GO
CREATE PROCEDURE Usp_Get_Detail_Qty_Dispro_By_Invoice
@DISTRIBUTOR_ID VARCHAR(10),
@START_DATE SMALLDATETIME,
@END_DATE SMALLDATETIME
AS
SET NOCOUNT ON;
-------------------------------------------------------------------------------- 
IF (@DISTRIBUTOR_ID IS NOT NULL)
BEGIN
	SELECT DR.DISTRIBUTOR_ID,DR.DISTRIBUTOR_NAME,BR.BRAND_NAME,BB.BRANDPACK_NAME,(OPO.QTY_EVEN + ISNULL(OPO.LEFT_OA_QTY,0)) AS OA_QTY,OPO.RPK,
	OPO.DP,OPO.CP_D,OPO.CP_R,OPO.PKPP,OPO.DK,OPO.OTHERS,(ISNULL(OPO.TOTAL_DISC,0) + OPO.QTY_EVEN)AS TOTAL_DELIVERY,
	ACCRUE.QUARTER_1 ,ACCRUE.QUARTER_2 ,ACCRUE.QUARTER_3,ACCRUE.QUARTER_4,ACCRUE.SEMESTER_1,
	ACCRUE.SEMESTER_2 ,ACCRUE.YEARLY,ACCRUE.RELEASE_Q1,
	ACCRUE.RELEASE_Q2,ACCRUE.RELEASE_Q3,
	ACCRUE.RELEASE_Q4 ,ACCRUE.RELEASE_S1 ,
	ACCRUE.RELEASE_S2,ACCRUE.RELEASE_Y , 

	TOTAL_RELEASE = ACCRUE.RELEASE_Q1 + ACCRUE.RELEASE_Q2 + ACCRUE.RELEASE_Q3 + ACCRUE.RELEASE_Q4 + ACCRUE.RELEASE_S1 + ACCRUE.RELEASE_S2 + ACCRUE.RELEASE_Y,	
	ACCRUE.LEFT_Q1,ACCRUE.LEFT_Q2,ACCRUE.LEFT_Q3,ACCRUE.LEFT_Q4,ACCRUE.LEFT_S1, ACCRUE.LEFT_S2,ACCRUE.LEFT_Y,
	ISNULL((ACCRUE.LEFT_Q1 + ACCRUE.LEFT_Q2 + ACCRUE.LEFT_Q3 + ACCRUE.LEFT_Q4 + ACCRUE.LEFT_S1 +  ACCRUE.LEFT_S2 + ACCRUE.LEFT_Y),0)
	 AS TOTAL_LEFT,OPO.REM_Q1, OPO.REM_Q2, OPO.REM_Q3, OPO.REM_Q4, OPO.REM_S1, OPO.REM_S2, OPO.REM_Y,
	  (OPO.REM_Q1 + OPO.REM_Q2 + OPO.REM_Q3 + OPO.REM_Q4 + OPO.REM_S1 + OPO.REM_S2 + OPO.REM_Y) AS TOTAL_REMAIND
	FROM Nufarm.dbo.DIST_DISTRIBUTOR DR INNER JOIN
	(
	  SELECT OPO.DISTRIBUTOR_ID,OPB.BRANDPACK_ID,ISNULL(SUM(OOB.QTY_EVEN),0) AS QTY_EVEN,
	  ISNULL(SUM(OBD.RPK),0)AS RPK,ISNULL(SUM(OBD.OTHERS),0)AS OTHERS,ISNULL(SUM(OBD.LEFT_OA_QTY),0) AS LEFT_OA_QTY,
	  ISNULL(SUM(OBD.DP),0)AS DP,ISNULL(SUM(OBD.CP_D),0)AS CP_D,ISNULL(SUM(OBD.CP_R),0)AS CP_R,
	  ISNULL(SUM(OBD.PKPP),0) AS PKPP,ISNULL(SUM(OBD.DK),0) AS DK,
	  ISNULL(SUM(REM.REM_Q1),0)AS REM_Q1,ISNULL(SUM(REM.REM_Q2),0)AS REM_Q2,ISNULL(SUM(REM.REM_Q3),0)AS REM_Q3,
	  ISNULL(SUM(REM.REM_Q4),0)AS REM_Q4,ISNULL(SUM(REM.REM_S1),0)AS REM_S1,
	  ISNULL(SUM(REM.REM_S2),0)AS REM_S2,ISNULL(SUM(REM.REM_Y),0)AS REM_Y,
	  ISNULL(SUM(OBD.TOTAL_DISC),0) AS TOTAL_DISC
	  FROM Nufarm.dbo.ORDR_PURCHASE_ORDER OPO 
	  INNER JOIN Nufarm.dbo.ORDR_PO_BRANDPACK OPB ON OPO.PO_REF_NO = OPB.PO_REF_NO
	  INNER JOIN Nufarm.dbo.ORDR_OA_BRANDPACK OOB ON OOB.PO_BRANDPACK_ID = OPB.PO_BRANDPACK_ID 
	  LEFT OUTER JOIN (
			    SELECT OA_BRANDPACK_ID,
			    ISNULL(SUM(CASE GQSY_SGT_P_FLAG WHEN 'MG' THEN DISC_QTY ELSE 0 END),0) AS RPK,
			    ISNULL(SUM(CASE GQSY_SGT_P_FLAG WHEN 'O' THEN DISC_QTY ELSE 0 END),0)AS OTHERS,
			    ISNULL(SUM(CASE GQSY_SGT_P_FLAG WHEN 'RMOA' THEN DISC_QTY ELSE 0 END),0) AS LEFT_OA_QTY,
			    ISNULL(SUM(CASE GQSY_SGT_P_FLAG WHEN 'G' THEN DISC_QTY ELSE 0 END),0) AS DP,
			    ISNULL(SUM(CASE GQSY_SGT_P_FLAG WHEN 'CP' THEN DISC_QTY ELSE 0 END),0) AS CP_D,
			    ISNULL(SUM(CASE GQSY_SGT_P_FLAG WHEN 'SC' THEN DISC_QTY ELSE 0 END),0) AS CP_D_S,
			    ISNULL(SUM(CASE GQSY_SGT_P_FLAG WHEN 'CR' THEN DISC_QTY ELSE 0 END),0) AS CP_R,
			    ISNULL(SUM(CASE GQSY_SGT_P_FLAG WHEN 'KP' THEN DISC_QTY ELSE 0 END),0)AS PKPP,
			    ISNULL(SUM(CASE GQSY_SGT_P_FLAG WHEN 'DK' THEN DISC_QTY ELSE 0 END),0) AS DK,
			    ISNULL(SUM(DISC_QTY),0) AS TOTAL_DISC
			    FROM Nufarm.dbo.ORDR_OA_BRANDPACK_DISC
			    GROUP BY OA_BRANDPACK_ID
	                  )OBD
	  ON OOB.OA_BRANDPACK_ID = OBD.OA_BRANDPACK_ID
	  LEFT OUTER JOIN (
	                    SELECT OA_BRANDPACK_ID,
	                    ISNULL(SUM(CASE FLAG WHEN 'Q1' THEN LEFT_QTY ELSE 0 END),0) AS REM_Q1,
			    ISNULL(SUM(CASE FLAG WHEN 'Q2' THEN LEFT_QTY ELSE 0 END),0) AS REM_Q2,
			    ISNULL(SUM(CASE FLAG WHEN 'Q3' THEN LEFT_QTY ELSE 0 END),0) AS REM_Q3,
			    ISNULL(SUM(CASE FLAG WHEN 'Q4' THEN LEFT_QTY ELSE 0 END),0) AS REM_Q4,
			    ISNULL(SUM(CASE FLAG WHEN 'S1' THEN LEFT_QTY ELSE 0 END),0) AS REM_S1,
			    ISNULL(SUM(CASE FLAG WHEN 'S2' THEN LEFT_QTY ELSE 0 END),0) AS REM_S2,
			    ISNULL(SUM(CASE FLAG WHEN 'Y' THEN LEFT_QTY ELSE 0 END),0)AS REM_Y
	                    FROM Nufarm.dbo.ORDR_OA_REMAINDING GROUP BY OA_BRANDPACK_ID
			  )REM
	  ON OOB.OA_BRANDPACK_ID = REM.OA_BRANDPACK_ID
	  WHERE OPO.PO_REF_DATE >= @START_DATE
	  AND OPB.PO_ORIGINAL_QTY > 0  
	  GROUP BY OPO.DISTRIBUTOR_ID,OPB.BRANDPACK_ID
	)OPO
	ON OPO.DISTRIBUTOR_ID = DR.DISTRIBUTOR_ID
	INNER JOIN Nufarm.dbo.BRND_BRANDPACK BB ON BB.BRANDPACK_ID = OPO.BRANDPACK_ID
	INNER JOIN BRND_BRAND BR ON BR.BRAND_ID = BB.BRAND_ID
	LEFT OUTER JOIN(
	                 SELECT ACRH.DISTRIBUTOR_ID,ACRD.BRANDPACK_ID,

		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'Q1' THEN ACRD.DISC_QTY END),0)AS QUARTER_1,
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'Q2' THEN ACRD.DISC_QTY END),0)AS QUARTER_2,
	                 ISNULL(SUM(CASE ACRH.FLAG WHEN 'Q3' THEN ACRD.DISC_QTY  END),0)AS QUARTER_3,
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'Q4' THEN ACRD.DISC_QTY  END),0) AS QUARTER_4,
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'S1' THEN ACRD.DISC_QTY  END),0)AS SEMESTER_1,
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'S2' THEN ACRD.DISC_QTY  END),0)AS SEMESTER_2,
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'Y'  THEN ACRD.DISC_QTY  END),0)AS YEARLY,
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'Q1' THEN ACRD.RELEASE_QTY END),0)AS RELEASE_Q1,
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'Q2' THEN ACRD.RELEASE_QTY END),0)AS RELEASE_Q2,
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'Q3' THEN ACRD.RELEASE_QTY END),0)AS RELEASE_Q3,
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'Q4' THEN ACRD.RELEASE_QTY END),0)AS RELEASE_Q4,
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'S1' THEN ACRD.RELEASE_QTY END),0)AS RELEASE_S1,
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'S2' THEN ACRD.RELEASE_QTY END),0)AS RELEASE_S2,
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'Y'  THEN ACRD.RELEASE_QTY END),0)AS RELEASE_Y,
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'Q1' THEN ACRD.LEFT_QTY END),0)AS LEFT_Q1,
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'Q2' THEN ACRD.LEFT_QTY END),0) AS LEFT_Q2,
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'Q3' THEN ACRD.LEFT_QTY END),0)AS LEFT_Q3,
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'Q4' THEN ACRD.LEFT_QTY END),0) AS LEFT_Q4,
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'S1' THEN ACRD.LEFT_QTY END),0)AS LEFT_S1,
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'S2' THEN ACRD.LEFT_QTY END),0)AS LEFT_S2,
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'Y'  THEN ACRD.LEFT_QTY END),0)AS LEFT_Y

		         FROM Nufarm.dbo.ACCRUED_HEADER ACRH INNER JOIN Nufarm.dbo.ACCRUED_DETAIL ACRD
	                 ON ACRH.ACHIEVEMENT_ID = ACRD.ACHIEVEMENT_ID
			 INNER JOIN Nufarm.dbo.AGREE_AGREEMENT AA ON ACRH.AGREEMENT_NO = AA.AGREEMENT_NO
                         WHERE AA.START_DATE >= @START_DATE AND AA.END_DATE <= @END_DATE
			 GROUP BY ACRH.DISTRIBUTOR_ID,ACRD.BRANDPACK_ID
		       )ACCRUE
	ON OPO.BRANDPACK_ID = ACCRUE.BRANDPACK_ID
	AND OPO.DISTRIBUTOR_ID = ACCRUE.DISTRIBUTOR_ID
	WHERE OPO.DISTRIBUTOR_ID = @DISTRIBUTOR_ID;
    END
ELSE
    BEGIN
	SELECT DR.DISTRIBUTOR_ID,DR.DISTRIBUTOR_NAME,BR.BRAND_NAME,BB.BRANDPACK_NAME,(OPO.QTY_EVEN + ISNULL(OPO.LEFT_OA_QTY,0)) AS OA_QTY,OPO.RPK,
	OPO.DP,OPO.CP_D,OPO.CP_R,OPO.PKPP,OPO.DK,OPO.OTHERS,(ISNULL(OPO.TOTAL_DISC,0) + OPO.QTY_EVEN) AS TOTAL_DELIVERY,
	ACCRUE.QUARTER_1 ,ACCRUE.QUARTER_2 ,ACCRUE.QUARTER_3,ACCRUE.QUARTER_4,ACCRUE.SEMESTER_1,
	ACCRUE.SEMESTER_2 ,ACCRUE.YEARLY,ACCRUE.RELEASE_Q1,
	ACCRUE.RELEASE_Q2,ACCRUE.RELEASE_Q3 ,
	ACCRUE.RELEASE_Q4 ,ACCRUE.RELEASE_S1,
	ACCRUE.RELEASE_S2 ,ACCRUE.RELEASE_Y ,

	TOTAL_RELEASE = ACCRUE.RELEASE_Q1 + ACCRUE.RELEASE_Q2 + ACCRUE.RELEASE_Q3 + ACCRUE.RELEASE_Q4 + ACCRUE.RELEASE_S1 + ACCRUE.RELEASE_S2 + ACCRUE.RELEASE_Y,		
	ACCRUE.LEFT_Q1,ACCRUE.LEFT_Q2,ACCRUE.LEFT_Q3,ACCRUE.LEFT_Q4,ACCRUE.LEFT_S1, ACCRUE.LEFT_S2,ACCRUE.LEFT_Y,
	ISNULL((ACCRUE.LEFT_Q1 + ACCRUE.LEFT_Q2 + ACCRUE.LEFT_Q3 + ACCRUE.LEFT_Q4 + ACCRUE.LEFT_S1 +  ACCRUE.LEFT_S2 + ACCRUE.LEFT_Y),0)
	 AS TOTAL_LEFT,OPO.REM_Q1, OPO.REM_Q2, OPO.REM_Q3, OPO.REM_Q4, OPO.REM_S1, OPO.REM_S2, OPO.REM_Y,
	  (OPO.REM_Q1 + OPO.REM_Q2 + OPO.REM_Q3 + OPO.REM_Q4 + OPO.REM_S1 + OPO.REM_S2 + OPO.REM_Y) AS TOTAL_REMAIND
	FROM Nufarm.dbo.DIST_DISTRIBUTOR DR INNER JOIN
	(
	  SELECT OPO.DISTRIBUTOR_ID,OPB.BRANDPACK_ID,ISNULL(SUM(OOB.QTY_EVEN),0) AS QTY_EVEN,
	  ISNULL(SUM(OBD.RPK),0)AS RPK,ISNULL(SUM(OBD.OTHERS),0)AS OTHERS,ISNULL(SUM(OBD.LEFT_OA_QTY),0) AS LEFT_OA_QTY,
	  ISNULL(SUM(OBD.DP),0)AS DP,ISNULL(SUM(OBD.CP_D),0)AS CP_D,ISNULL(SUM(OBD.CP_R),0)AS CP_R,
	  ISNULL(SUM(OBD.PKPP),0) AS PKPP,ISNULL(SUM(OBD.DK),0) AS DK,
	  ISNULL(SUM(REM.REM_Q1),0)AS REM_Q1,ISNULL(SUM(REM.REM_Q2),0)AS REM_Q2,ISNULL(SUM(REM.REM_Q3),0)AS REM_Q3,
	  ISNULL(SUM(REM.REM_Q4),0)AS REM_Q4,ISNULL(SUM(REM.REM_S1),0)AS REM_S1,
	  ISNULL(SUM(REM.REM_S2),0)AS REM_S2,ISNULL(SUM(REM.REM_Y),0)AS REM_Y,
	  ISNULL(SUM(OBD.TOTAL_DISC),0) AS TOTAL_DISC
	  FROM Nufarm.dbo.ORDR_PURCHASE_ORDER OPO 
	  INNER JOIN Nufarm.dbo.ORDR_PO_BRANDPACK OPB ON OPO.PO_REF_NO = OPB.PO_REF_NO
	  INNER JOIN Nufarm.dbo.ORDR_OA_BRANDPACK OOB ON OOB.PO_BRANDPACK_ID = OPB.PO_BRANDPACK_ID 
	  LEFT OUTER JOIN (
			    SELECT OA_BRANDPACK_ID,
			    ISNULL(SUM(CASE GQSY_SGT_P_FLAG WHEN 'MG' THEN DISC_QTY ELSE 0 END),0) AS RPK,
			    ISNULL(SUM(CASE GQSY_SGT_P_FLAG WHEN 'O' THEN DISC_QTY ELSE 0 END),0)AS OTHERS,
			    ISNULL(SUM(CASE GQSY_SGT_P_FLAG WHEN 'RMOA' THEN DISC_QTY ELSE 0 END),0) AS LEFT_OA_QTY,
			    ISNULL(SUM(CASE GQSY_SGT_P_FLAG WHEN 'G' THEN DISC_QTY ELSE 0 END),0) AS DP,
			    ISNULL(SUM(CASE GQSY_SGT_P_FLAG WHEN 'CP' THEN DISC_QTY ELSE 0 END),0) AS CP_D,
			    ISNULL(SUM(CASE GQSY_SGT_P_FLAG WHEN 'SC' THEN DISC_QTY ELSE 0 END),0) AS CP_D_S,
			    ISNULL(SUM(CASE GQSY_SGT_P_FLAG WHEN 'CR' THEN DISC_QTY ELSE 0 END),0) AS CP_R,
			    ISNULL(SUM(CASE GQSY_SGT_P_FLAG WHEN 'KP' THEN DISC_QTY ELSE 0 END),0)AS PKPP,
			    ISNULL(SUM(CASE GQSY_SGT_P_FLAG WHEN 'DK' THEN DISC_QTY ELSE 0 END),0) AS DK,
			    ISNULL(SUM(DISC_QTY),0) AS TOTAL_DISC
			    FROM Nufarm.dbo.ORDR_OA_BRANDPACK_DISC
			    GROUP BY OA_BRANDPACK_ID
	                  )OBD
	  ON OOB.OA_BRANDPACK_ID = OBD.OA_BRANDPACK_ID
	  LEFT OUTER JOIN (
	                    SELECT OA_BRANDPACK_ID,
	                    ISNULL(SUM(CASE FLAG WHEN 'Q1' THEN LEFT_QTY ELSE 0 END),0) AS REM_Q1,
			    ISNULL(SUM(CASE FLAG WHEN 'Q2' THEN LEFT_QTY ELSE 0 END),0) AS REM_Q2,
			    ISNULL(SUM(CASE FLAG WHEN 'Q3' THEN LEFT_QTY ELSE 0 END),0) AS REM_Q3,
			    ISNULL(SUM(CASE FLAG WHEN 'Q4' THEN LEFT_QTY ELSE 0 END),0) AS REM_Q4,
			    ISNULL(SUM(CASE FLAG WHEN 'S1' THEN LEFT_QTY ELSE 0 END),0) AS REM_S1,
			    ISNULL(SUM(CASE FLAG WHEN 'S2' THEN LEFT_QTY ELSE 0 END),0) AS REM_S2,
			    ISNULL(SUM(CASE FLAG WHEN 'Y' THEN LEFT_QTY ELSE 0 END),0)AS REM_Y
	                    FROM Nufarm.dbo.ORDR_OA_REMAINDING GROUP BY OA_BRANDPACK_ID
			  )REM
	  ON OOB.OA_BRANDPACK_ID = REM.OA_BRANDPACK_ID
	  WHERE OPO.PO_REF_DATE >= @START_DATE 
	  AND OPB.PO_ORIGINAL_QTY > 0 
	  GROUP BY OPO.DISTRIBUTOR_ID,OPB.BRANDPACK_ID
	)OPO
	ON OPO.DISTRIBUTOR_ID = DR.DISTRIBUTOR_ID
	INNER JOIN Nufarm.dbo.BRND_BRANDPACK BB ON BB.BRANDPACK_ID = OPO.BRANDPACK_ID
	INNER JOIN BRND_BRAND BR ON BR.BRAND_ID = BB.BRAND_ID
	LEFT OUTER JOIN(
	                 SELECT ACRH.DISTRIBUTOR_ID,ACRD.BRANDPACK_ID,
	
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'Q1' THEN ACRD.DISC_QTY END),0)AS QUARTER_1,
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'Q2' THEN ACRD.DISC_QTY END),0)AS QUARTER_2,
	                 ISNULL(SUM(CASE ACRH.FLAG WHEN 'Q3' THEN ACRD.DISC_QTY  END),0)AS QUARTER_3,
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'Q4' THEN ACRD.DISC_QTY  END),0) AS QUARTER_4,
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'S1' THEN ACRD.DISC_QTY  END),0)AS SEMESTER_1,
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'S2' THEN ACRD.DISC_QTY  END),0)AS SEMESTER_2,
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'Y'  THEN ACRD.DISC_QTY  END),0)AS YEARLY,
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'Q1' THEN ACRD.RELEASE_QTY END),0)AS RELEASE_Q1,
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'Q2' THEN ACRD.RELEASE_QTY END),0)AS RELEASE_Q2,
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'Q3' THEN ACRD.RELEASE_QTY END),0)AS RELEASE_Q3,
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'Q4' THEN ACRD.RELEASE_QTY END),0)AS RELEASE_Q4,
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'S1' THEN ACRD.RELEASE_QTY END),0)AS RELEASE_S1,
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'S2' THEN ACRD.RELEASE_QTY END),0)AS RELEASE_S2,
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'Y'  THEN ACRD.RELEASE_QTY END),0)AS RELEASE_Y,
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'Q1' THEN ACRD.LEFT_QTY END),0)AS LEFT_Q1,
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'Q2' THEN ACRD.LEFT_QTY END),0) AS LEFT_Q2,
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'Q3' THEN ACRD.LEFT_QTY END),0)AS LEFT_Q3,
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'Q4' THEN ACRD.LEFT_QTY END),0) AS LEFT_Q4,
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'S1' THEN ACRD.LEFT_QTY END),0)AS LEFT_S1,
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'S2' THEN ACRD.LEFT_QTY END),0)AS LEFT_S2,
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'Y'  THEN ACRD.LEFT_QTY END),0)AS LEFT_Y
		   
		         FROM Nufarm.dbo.ACCRUED_HEADER ACRH INNER JOIN Nufarm.dbo.ACCRUED_DETAIL ACRD
	                 ON ACRH.ACHIEVEMENT_ID = ACRD.ACHIEVEMENT_ID
			 INNER JOIN Nufarm.dbo.AGREE_AGREEMENT AA ON ACRH.AGREEMENT_NO = AA.AGREEMENT_NO
                         WHERE AA.START_DATE >= @START_DATE AND AA.END_DATE <= @END_DATE
			 GROUP BY ACRH.DISTRIBUTOR_ID,ACRD.BRANDPACK_ID
		       )ACCRUE
	ON OPO.BRANDPACK_ID = ACCRUE.BRANDPACK_ID
	AND OPO.DISTRIBUTOR_ID = ACCRUE.DISTRIBUTOR_ID;
   END
GO

---------------------------------------------------------------------------
-----REPORT PLANTATION

--SELECT DISTINCT(ACRH.BRAND_ID) FROM ACCRUED_HEADER ACRH 
--INNER JOIN BRND_BRAND BR ON BR.BRAND_ID = ACRH.BRAND_ID
--WHERE ACRH.FLAG IN('Q1','Q2','Q3','Q4') AND BR.BRAND_NAME LIKE '%ROUND%'
--'006020','00681','00604','0060200','00684','006820','00601'

SELECT ACRH.DISTRIBUTOR_ID,ACRD.BRANDPACK_ID,
	
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'Q1' THEN ACRD.DISC_QTY END),0)AS QUARTER_1,
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'Q2' THEN ACRD.DISC_QTY END),0)AS QUARTER_2,
	                 ISNULL(SUM(CASE ACRH.FLAG WHEN 'Q3' THEN ACRD.DISC_QTY  END),0)AS QUARTER_3,
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'Q4' THEN ACRD.DISC_QTY  END),0) AS QUARTER_4,
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'S1' THEN ACRD.DISC_QTY  END),0)AS SEMESTER_1,
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'S2' THEN ACRD.DISC_QTY  END),0)AS SEMESTER_2,
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'Y'  THEN ACRD.DISC_QTY  END),0)AS YEARLY,
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'Q1' THEN ACRD.RELEASE_QTY END),0)AS RELEASE_Q1,
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'Q2' THEN ACRD.RELEASE_QTY END),0)AS RELEASE_Q2,
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'Q3' THEN ACRD.RELEASE_QTY END),0)AS RELEASE_Q3,
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'Q4' THEN ACRD.RELEASE_QTY END),0)AS RELEASE_Q4,
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'S1' THEN ACRD.RELEASE_QTY END),0)AS RELEASE_S1,
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'S2' THEN ACRD.RELEASE_QTY END),0)AS RELEASE_S2,
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'Y'  THEN ACRD.RELEASE_QTY END),0)AS RELEASE_Y,
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'Q1' THEN ACRD.LEFT_QTY END),0)AS LEFT_Q1,
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'Q2' THEN ACRD.LEFT_QTY END),0) AS LEFT_Q2,
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'Q3' THEN ACRD.LEFT_QTY END),0)AS LEFT_Q3,
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'Q4' THEN ACRD.LEFT_QTY END),0) AS LEFT_Q4,
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'S1' THEN ACRD.LEFT_QTY END),0)AS LEFT_S1,
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'S2' THEN ACRD.LEFT_QTY END),0)AS LEFT_S2,
		         ISNULL(SUM(CASE ACRH.FLAG WHEN 'Y'  THEN ACRD.LEFT_QTY END),0)AS LEFT_Y
		   
		         FROM Nufarm.dbo.ACCRUED_HEADER ACRH INNER JOIN Nufarm.dbo.ACCRUED_DETAIL ACRD
	                 ON ACRH.ACHIEVEMENT_ID = ACRD.ACHIEVEMENT_ID
			 INNER JOIN Nufarm.dbo.AGREE_AGREEMENT AA ON ACRH.AGREEMENT_NO = AA.AGREEMENT_NO
                         WHERE AA.START_DATE >=  '08/01/2014' AND AA.END_DATE <= '07/31/2015'
			 GROUP BY ACRH.DISTRIBUTOR_ID,ACRD.BRANDPACK_ID