Use Nufarm;
GO

UPDATE ACCRUED_HEADER SET DISC_BY_VOLUME = BONUS_QTY,DISC_DIST_BY_VOLUME = BONUS_DISTRIBUTOR WHERE AGREEMENT_NO  = '1103/NI/X/2008. 14'
AND FLAG = 'Q3';
UPDATE ACCRUED_HEADER SET DISC_BY_VOLUME = BONUS_QTY,DISC_DIST_BY_VOLUME = BONUS_DISTRIBUTOR WHERE AGREEMENT_NO  = '1103/NI/X/2008. 14'
AND FLAG = 'Q4';
UPDATE ACCRUED_HEADER SET DISC_BY_VOLUME = BONUS_QTY,DISC_DIST_BY_VOLUME = BONUS_DISTRIBUTOR WHERE AGREEMENT_NO  = '1103/NI/X/2008. 14'
AND FLAG = 'Y';

UPDATE ACCRUED_DETAIL SET DISC_BY_VOLUME = DISC_QTY 
WHERE ACHIEVEMENT_ID = ANY(SELECT ACHIEVEMENT_ID FROM ACCRUED_HEADER WHERE AGREEMENT_NO = '1103/NI/X/2008. 14' AND FLAG ='Q3');

UPDATE ACCRUED_DETAIL SET DISC_BY_VOLUME = DISC_QTY 
WHERE ACHIEVEMENT_ID = ANY(SELECT ACHIEVEMENT_ID FROM ACCRUED_HEADER WHERE AGREEMENT_NO = '1103/NI/X/2008. 14' AND FLAG ='Q4');


UPDATE ACCRUED_DETAIL SET DISC_BY_VOLUME = DISC_QTY 
WHERE ACHIEVEMENT_ID = ANY(SELECT ACHIEVEMENT_ID FROM ACCRUED_HEADER WHERE AGREEMENT_NO = '1103/NI/X/2008. 14' AND FLAG ='Y');

SELECT * FROM ACCRUED_DETAIL WHERE ACHIEVEMENT_BRANDPACK_ID =

--UPDATE ACCRUED_DETAIL SET LEFT_QTY = DISC_BY_VOLUME  WHERE ACHIEVEMENT_BRANDPACK_ID = 'PAN102000|1103/NI/X/2008. 1400604|Q3|00604040LD'