exec sp_executesql @stmt = N'SET NOCOUNT ON;
SELECT DISTINCT RIGHT(RTRIM(ITEM.SEGMENT1),1) + '''' + RTRIM(ITEM.SEGMENT2) AS BRAND_ID
,RTRIM(SUBSTRING(ITEM.[DESC],1,CHARINDEX(''@'',ITEM.[DESC],0)- 1))AS BRAND_NAME FROM NI87.dbo.ICITEM ITEM 
 WHERE-- EXISTS(SELECT BRAND_ID FROM Nufarm.dbo.BRND_BRAND WHERE BRAND_ID = 
 --RIGHT(RTRIM(ITEM.SEGMENT1),1) + '''' + RTRIM(ITEM.SEGMENT2)) 
 --AND 
ITEM.INACTIVE = 0 AND RTRIM(ITEM.[DESC]) NOT LIKE ''%OTHER%'' AND ITEM.[DESC] LIKE ''%@%''
 AND RTRIM(ITEM.[DESC]) NOT LIKE ''ROUNDUP%'' OPTION(KEEP PLAN);'

SELECT * FROM BRND_BRAND WHERE BRAND_ID ='11032'

SELECT * FROM NI87.DBO.ICITEM WHERE [DESC] LIKE '%INOVATE%'

--VIKING RUBAH JADI 500 EC
SELECT * FROM NI87.DBO.ICITEM WHERE [DESC] LIKE '%VIKING%'

--LEGION DI DTS DI ACCPACK SIKLON
SELECT * FROM BRND_BRAND WHERE BRAND_ID like '%1030%'
                    
--BUAT BARU LEGION DI DTS
SELECT * FROM NI87.DBO.ICITEM WHERE [DESC] LIKE '%LEG%';

SELECT * FROM NI87.DBO.ICITEM WHERE [DESC] LIKE '%SIKLON%'


SELECT * FROM NI87.DBO.ICITEM WHERE [DESC] LIKE '%ZENITH%'
SELECT * FROM NI87.DBO.ICITEM WHERE [DESC] LIKE '%XENIUM%';

SELECT * FROM BRND_BRAND WHERE BRAND_ID LIKE '%7252%'                    

SELECT * FROM NI87.DBO.ICITEM WHERE [DESC] LIKE '%ROUNDUP%'


SELECT * FROM NI87.DBO.ICCATG WHERE CATEGORY = '11032'
SELECT * FROM NI87.DBO.ICCATG WHERE CATEGORY = '1030'
SELECT * FROM NI87.DBO.ICCATG WHERE CATEGORY = '7252'    

SELECT * FROM NI87.DBO.ICCATG WHERE CATEGORY = '0741'   
SELECT * FROM NI87.DBO.ICCATG WHERE CATEGORY = '0134'                   

SELECT REPLACE(BRAND_NAME,'-','') FROM BRND_BRAND         
SELECT * FROM ORDR_PO_BRANDPACK WHERE BRANDPACK_ID LIKE '%11032%'       
SELECT * FROM AGREE_BRANDPACK_INCLUDE WHERE BRANDPACK_ID LIKE '%11032%'   
SELECT * FROM BRND_BRAND WHERE BRAND_ID LIKE '%00102%'
SELECT * FROM NI87.DBO.ICITEM WHERE [DESC] LIKE '%NUPAX%'

--LEGION JADI SIKLON
--XENIUM JADI ZENITH
--BUPROMONO JADI BUDOKA
--NUPAX JADI VIKING

SELECT * FROM AGREE_AGREEMENT WHERE AGREEMENT_NO = '0853/NI/V/2011.13'
SELECT * FROM BRND_BRAND WHERE BRAND_NAME LIKE '%VIKING%'
SELECT * FROM BRND_BRANDPACK WHERE BRANDPACK_NAME LIKE '%VIKING%'

SELECT * FROM AGREE_BRANDPACK_INCLUDE WHERE BRANDPACK_ID LIKE '%11032'
SELECT * FROM AGREE_BRANDPACK_INCLUDE WHERE AGREE_BRAND_ID LIKE '%11032'
--UPDATE BRANDPACK
UPDATE BRND_BRANDPACK SET BRANDPACK_NAME = REPLACE(BRANDPACK_NAME,'VIKING 100 EC','VIKING 500 EC'), BRAND_ID = '00102',
BRANDPACK_ID = REPLACE(BRANDPACK_ID,'11032','00102') WHERE BRAND_ID = '11032';
GO

--UPDATE ACCRUED_DETAIL
UPDATE ACCRUED_DETAIL SET ACHIEVEMENT_ID = REPLACE(ACHIEVEMENT_ID,'11032','00102'),BRANDPACK_ID = REPLACE(BRANDPACK_ID,'11032','00102')
,ACHIEVEMENT_BRANDPACK_ID = REPLACE(ACHIEVEMENT_BRANDPACK_ID,'11032','00102')
WHERE ACHIEVEMENT_ID = ANY(SELECT ACHIEVEMENT_ID FROM ACCRUED_HEADER WHERE BRAND_ID = '11032');
GO

--UPDATE ACCRUED_HEADER
UPDATE ACCRUED_HEADER SET BRAND_ID = '00102',ACHIEVEMENT_ID = REPLACE(ACHIEVEMENT_ID,'11032','00102')
WHERE BRAND_ID = '11032';
GO
--UPDATE AGREE_PROG_DISC
UPDATE AGREE_PROG_DISC SET AGREE_BRAND_ID = REPLACE(AGREE_BRAND_ID,'11032','00102')
WHERE AGREE_BRAND_ID = ANY(SELECT AGREE_BRAND_ID FROM AGREE_BRAND_INCLUDE WHERE BRAND_ID = '11032');
GO
--UPDATE GIVEN_PROGRESIVE
UPDATE GIVEN_PROGRESSIVE SET AGREE_BRAND_ID = REPLACE(AGREE_BRAND_ID,'11032','00102')
WHERE AGREE_BRAND_ID = ANY(SELECT AGREE_BRAND_ID FROM AGREE_BRAND_INCLUDE WHERE BRAND_ID = '11032');
GO

--UPDATE AGREE_BRAND_ID
UPDATE AGREE_BRAND_INCLUDE SET BRAND_ID = REPLACE(BRAND_ID,'11032','00102'),
AGREE_BRAND_ID = REPLACE(AGREE_BRAND_ID,'11032','00102')
WHERE BRAND_ID = '11032';
GO

UPDATE AGREE_BRANDPACK_INCLUDE SET AGREE_BRANDPACK_ID = REPLACE(AGREE_BRANDPACK_ID,'11032','00102'),
AGREE_BRAND_ID = REPLACE(AGREE_BRAND_ID,'11032','00102'),BRANDPACK_ID = REPLACE(BRANDPACK_ID,'11032','00102')
WHERE AGREE_BRAND_ID LIKE '%11032';
GO 

SELECT * FROM AGREE_BRANDPACK_INCLUDE WHERE  AGREE_BRAND_ID = ANY(SELECT AGREE_BRAND_ID FROM AGREE_BRAND_INCLUDE WHERE BRAND_ID = '00102');
SELECT * FROM BRND_BRANDPACK WHERE BRANDPACK_ID LIKE '%00102%'   
SELECT * FROM AGREE_PROG_DISC WHERE AGREE_BRAND_ID LIKE '%11032%';


SELECT * FROM ACCRUED_HEADER WHERE BRAND_ID = '11032'

SELECT * FROM BRND_BRANDPACK WHERE BRANDPACK_NAME  LIKE 'LEGION 5.7 WG%';

--LEGION JADI SIKLON
UPDATE BRND_BRANDPACK SET BRANDPACK_NAME = REPLACE(BRANDPACK_NAME,'LEGION 5.7 WG','SIKLON 5.7 WG')
WHERE BRANDPACK_NAME LIKE 'LEGION 5.7 WG%';
GO
--XENIUM JADI ZENITH
UPDATE BRND_BRANDPACK SET BRANDPACK_NAME = REPLACE(BRANDPACK_NAME,'XENIUM 75 WP','ZENITH 75 WP')
WHERE BRANDPACK_NAME LIKE 'XENIUM 75 WP%';
GO


--'BUDOKA 25 WP'
--BUPROMONO JADI BUDOKA
--SELECT * FROM NI87.DBO.ICITEM WHERE [DESC] LIKE '%BUDOKA%';
--BUDOKA 25 WP @ 100 GR - D                                   
UPDATE BRND_BRANDPACK SET BRANDPACK_NAME = REPLACE(BRANDPACK_NAME,'BUPROMONO 25 WP','BUDOKA 25 WP')
WHERE BRANDPACK_NAME LIKE 'BUPROMONO 25 WP%';
GO
