--------------PROCEDURE UNTUK MENGINSERT DATA KE TABLE SPPB-----
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Insert_SPPB_Header' AND TYPE = 'P')
DROP PROCEDURE Usp_Insert_SPPB_Header
GO
CREATE PROCEDURE Usp_Insert_SPPB_Header
@SPPB_NO VARCHAR(15),
@SPPB_DATE DATETIME,
@PO_REF_NO VARCHAR(25),
@CREATE_BY VARCHAR(30)
AS
INSERT INTO SPPB_HEADER(SPPB_NO,SPPB_DATE,PO_REF_NO,CREATE_BY,CREATE_DATE)
VALUES(@SPPB_NO,@SPPB_DATE,@PO_REF_NO,@CREATE_BY,GETDATE())
GO
---------------------------------------------------------------------------------------------
---------------------------------PROCEDURE UNTUK MENDELETE SPPB_HEADER-------------------------
--IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Delete_SPPB_Header' AND TYPE = 'P')
--DROP PROCEDURE Usp_Delete_SPPB_Header
--GO
--CREATE PROEDURE Usp_Delete_SPPB_Header
--@SPPB_NO VARCHAR(15)
--AS
--DELETE FROM SPPB_HEADER WHERE SPPB_NO = @SPPB_NO
--GO
--------------------------------PROCEDURWE UNTUK MENGUPDATE ----SPPB_HEADER---------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Update_SPPB_Header' AND TYPE = 'P')
DROP PROCEDURE Usp_Update_SPPB_Header
GO
CREATE PROCEDURE Usp_Update_SPPB_Header
@SPPB_NO VARCHAR(15),
@SPPB_DATE DATETIME,
@PO_REF_NO VARCHAR(25),
@MODIFY_BY VARCHAR(30)
AS
UPDATE SPPB_HEADER SET SPPB_DATE = @SPPB_DATE,PO_REF_NO = @PO_REF_NO,MODIFY_BY = @MODIFY_BY
WHERE SPPB_NO =@SPPB_NO 
GO
/*
------------------------------------------------------------------------------------------
-------------PROCEDURE UNTUK MENGINSERT SPPB_DETAIL--------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME ='Usp_Insert_SPPB_Detail' AND TYPE = 'P')
DROP PROCEDURE Usp_Insert_SPPB_Detail
GO
CREATE PROCEDURE Usp_Insert_SPPB_Detail

@SPPB_BRANDPACK VARCHAR(85),
@SPPB_NO VARCHAR(15),
@OA_BRANDPACK_ID VARCHAR(70),
@SPPB_QTY VARCHAR(18),--TOTAL OA_QTY
@GON_1_NO VARCHAR(15),
@GON_1_DATE DATETIME,
@GON_1_QTY VARCHAR(18),
@GON_2_NO VARCHAR(15),
@GON_2_DATE DATETIME,
@GON_2_QTY VARCHAR(18),
@GON_3_NO VARCHAR(15),
@GON_3_DATE DATETIME,
@GON_3_QTY VARCHAR(18),
@GON_4_NO VARCHAR(15),
@GON_4_DATE DATETIME,
@GON_4_QTY VARCHAR(18),
@GON_5_NO VARCHAR(15),
@GON_5_DATE DATETIME,
@GON_5_QTY VARCHAR(18),
@GON_6_NO VARCHAR(15),
@GON_6_DATE DATETIME,
@GON_6_QTY VARCHAR(18),
@STATUS VARCHAR(10),
@BALANCE VARCHAR(18),
@REMARK VARCHAR(150),
@CREATE_BY VARCHAR(30)
AS
INSERT INTO SPPB_BRANDPACK(SPPB_BRANDPACK,SPPB_NO,OA_BRANDPACK_ID,SPPB_QTY,GON_1_NO,GON_1_DATE,GON_1_QTY,
GON_2_NO,GON_2_DATE,GON_2_QTY,GON_3_NO,GON_3_DATE,GON_3_QTY,GON_4_NO,GON_4_DATE,GON_4_QTY,GON_5_NO,GON_5_DATE,
GON_5_QTY,GON_6_NO,GON_6_DATE,GON_6_QTY,REMARK,CREATE_BY,CREATE_DATE)
VALUES(@SPPB_BRANDPACK,@SPPB_NO,@OA_BRANDPACK_ID,@SPPB_QTY,@GON_1_NO,@GON_1_DATE,@GON_1_QTY,@GON_2_NO,@GON_2_DATE,@GON_2_QTY,
@GON_3_NO,@GON_3_DATE,@GON_3_QTY,@GON_4_NO,@GON_4_DATE,@GON_4_QTY,@GON_5_NO,@GON_5_DATE,@GON_5_QTY,@GON_6_NO,
@GON_6_DATE,@GON_6_QTY,@REMARK,@CREATE_BY,GETDATE())
GO
------------PROCEDURE UNTUK MENGUPDATE ---DATE SPPB_BRANDPACK------------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Update_SPPB_GON' AND TYPE  ='P')
DROP PROCEDURE Usp_Update_SPPB_BrandPack
GO
CREATE PROCEDURE Usp_Update_SPPB_BrandPack
AS
@SPPB_BRANDPACK VARCHAR(85)
@GON_1_NO VARCHAR(15),
@GON_1_DATE DATETIME,
@GON_1_QTY VARCHAR(18),
@GON_2_NO VARCHAR(15),
@GON_2_DATE DATETIME,
@GON_2_QTY VARCHAR(18),
@GON_3_NO VARHCAR(15),
@GON_3_DATE DATETIME,
@GON_3_QTY VARCHAR(18),
@GON_4_NO  VARCHAR(15),
@GON_4_DATE DATETIME,
@GON_4_QTY VARCHAR(18),
@GON_5_NO VARCHAR(15),
@GON_5_DATE  DATETIME,
@GON_5_QTY VARCHAR(18),
@GON_6_NO VARCHAR(15),
@GON_6_DATE DATETIME,
@GON_6_QTY VARCHAR(18),
@MODIFY_BY  VARCHAR(30), 
AS
UPDATE SPPB_BRANPDACK SET GON_1_NO = @GON_1_NO,GON_1_DATE = @GON_1_DATE,@GON_1_QTY  = @GON_1_QTY,
GON_2_NO = @GON_2_NO ,GON_2_DATE = @GON_2_DATE,GON_2_QTY = @GON_2_QTY,GON_3_NO = @GON_3_NO,GON_3_DATE = @GON_3_DATE,
@GON_3_QTY = @GON_3_QTY,@GON_4_NO = @GON_4_NO,GON_4_DATE = @GON_4_DATE,GON_4_QTY = @GON_4_QTY,
GON_5_NO = @GON_5_NO,@GON_5_DATE = @GON_5_DATE,@GON_5_QTY = @GON_5_QTY,GON_6_NO = @GON_6_NO,
GON_6_DATE = @GON_6_DATE,@GON_6_QTY = @GON_6_QTY,MODIFY_BY = @MODFY_BY,MODIFY_DATE = GETDATE()
WHERE SPPB_BRANDPACK_ID = @SPPB_BRANDPACK_ID
GO

--------------------------------------------------------------------------------------------------
*/
----------------------PROCEDYURE UNTUK MEMACHINGKAN QTY SPPB DENGAN DENGAN PARTIAL GON
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Check_Sum_Mathing_Qty_GON' AND TYPE = 'P')
DROP PROCEDURE Usp_Check_Sum_Mathing_Qty_GON
GO
CREATE PROCEDURE Usp_Check_Sum_Mathing_Qty_GON
@SPPB_BRANDPACK VARCHAR(85),
@BALANCE VARCHAR(13), --LEFT_QTY
@STATUS VARCHAR(10),
@MODIFY_BY VARCHAR(30),
@REMARK VARCHAR(150)
AS
DECLARE @V_SUM_GONE_QTY DECIMAL(18,3),@V_SPPB_QTY DECIMAL(18,3)
SET @V_SPPB_QTY = CAST((SELECT SPPB_QTY FROM SPPB_BRANDPACK WHERE SPPB_BRANDPACK = @SPPB_BRANDPACK)AS DECIMAL(18,3))
SET @V_SUM_GON_QTY = CAST((SELECT ISNULL(GON_1_QTY,0) + ISNULL(GON_2_QTY,0) ISNULL(GON_QTY_3,0) + ISNULL(GON_QTY_4) + ISNULL(GON_QTY_5,0) 
			ISNULL(GON_QTY_6,0) FROM SPPB_BRANDPACK WHERE SPPB_BRANDPACK = @SPPB_BRANDPACK) AS DECIMAL(18,3))
IF @V_SUM_GON_QTY > @V_SPPB_QTY
   BEGIN
	RAISERROR('GON_QTY > FROM QTY_OA',16,1)
   END	

--IF (SELECT COUNT(OA_BRANPACK_ID) FROM OTP_DETAIL WHERE OA_BRANDPACK_ID = @OA_BRANDPACK_ID
--------------------------------------------------------------------------------------------
-----PROCEDURE UNTUK MENGINSERT DATA ORDR_OTP_HEADER-------------------------------------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Insert_ORDR_OTP_HEADER' AND TYPE = 'P')
DROP PROCEDURE Usp_Insert_ORDR_OTP_HEADER
GO
CREATE PROCEDURE Usp_Insert_ORDR_OTP_HEADER
@OTP_NO VARCHAR(15),
@OTP_DATE DATETIME,
@SPPB_NO VARCHAR(15),
@CREATE_BY VARCHAR(30)
AS
INSERT INTO ORDR_OTP_HEADER(OTP_NO,OTP_DATE,SPPB_NO,CREATE_BY,CREATE_DATE)
VALUES(@OTP_NO,@OTP_DATE,@SPPB_NO,@CREATE_BY,GETDATE())
GO
----------------------------PROCEDURE UNTUK MENGUPDATE DATA ORDR_OTP_HEADER-----
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Update_ORDR_OTP_HEADER' AND TYPE = 'P')
DROP PROCEDURE Usp_Update_ORDR_OTP_HEADER
GO
CREATE PROCEDURE Usp_Update_ORDR_OTP_HEADER
@OTP_NO VARCHAR(15),
@OTP_DATE DATETIME,
@SPPB_NO VARCHAR(15),
@MODIFY_BY VARCHAR(30)
AS
UPDATE ORDR_OTP_HEADER SET OTP_DATE = @OTP_DATE,SPPB_NO = @SPPB_NO,MODIFY_BY = @MODIFY_BY WHERE OTP_NO =@OTP_NO
GO
------------------------------------------------------------------------------------------------
--------PROCEDURE UNTUK MENGINSERT KE TABLE ORDR_OTP_HEADER----------------------------------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Delete_ORDR_OTP_BrandPack_By_OA_BrandPack' AND TYPE = 'P')
DROP PROCEDURE Usp_Delete_ORDR_OTP_BrandPack_By_OA_BrandPack
GO

CREATE PROCEDURE Usp_Delete_ORDR_OTP_BrandPack_By_OA_BrandPack
@OA_BRANDPACK_ID VARCHAR(75)
AS
DECLARE @V_OTP_NO VARCHAR(15)
IF EXISTS(SELECT OA_BRANDPACK_ID FROM OTP_DETAIL WHERE OA_BRANDPACK_ID = @OA_BRANDPACK_ID)
   BEGIN
	SET @V_OTP_NO = (SELECT OTP_NO FROM OTP_DETAIL WHERE OA_BRANDPACK_ID = @OA_BRANDPACK_ID)
	EXEC Usp_Delete_DO_TP_DETAIL @OA_BRANDPACK_ID = @OA_BRANDPACK_ID;
	DELETE FROM OTP_DETAIL WHERE OA_BRANDPACK_ID = @OA_BRANDPACK_ID;
	IF (@@ERROR <= 0)
	    BEGIN
		IF NOT EXISTS(SELECT OTP_NO FROM OTP_DETAIL WHERE OTP_NO = @V_OTP_NO) 
		   BEGIN
			DELETE FROM ORDR_OTP_HEADER WHERE OTP_NO = @V_OTP_NO
		   END 
	    END
   END

GO
--------------------------------------------------------------------------------------------
-------------------------PROCEDURE UNTUK MENDELETE MENGINSERT -------------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Insert_DO_Third_Party_Header' AND TYPE = 'P')
DROP PROCEDURE Usp_Insert_DO_Third_Party_Header
GO
CREATE PROCEDURE Usp_Insert_DO_Third_Party_Header
@DO_TP_NO VARCHAR(15),
@DO_TP_DATE DATETIME,
@OTP_NO VARCHAR(15),
@CREATE_BY VARCHAR(30)
AS
INSERT INTO DO_TP_HEADER(DO_TP_NO,DO_TP_DATE,OTP_NO,CREATE_BY,CREATE_DATE)
VALUES(@DO_TP_NO,@DO_TP_DATE,@OTP_NO,@CREATE_BY,GETDATE())
GO
------------------------------------------------------------------------------------------------
-----------PROCEUDURE UNTUK MENGUPDATE DO_TP_HEADER-------------------------------------------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Update_DO_Third_Party_Header' AND TYPE = 'P')
DROP PROCEDURE Usp_Update_DO_Third_Party_Header
GO
CREATE PROCEDURE Usp_Update_DO_Third_Party_Header
@DO_TP_NO VARCHAR(30),
@DO_TP_DATE DATETIME,
@OTP_NO VARCHAR(25),
@MODIFY_BY VARCHAR(30)
AS
UPDATE DO_TP_HEADER SET DO_TP_DATE = @DO_TP_DATE,OTP_NO = @OTP_NO,MODIFY_BY = @MODIFY_BY,MODIFY_DATE = GETDATE()
WHERE DO_TP_NO = @DO_TP_NO
GO
--------------------------------------------------------------------------------------------
----------------------------PROCEDURE UNTUK MENDELETE DO_TP_HEADER------------------------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Delete_DO_TP_DETAIL' AND TYPE = 'P')
DROP PROCEDURE Usp_Delete_DO_TP_DETAIL
GO
CREATE PROCEDURE Usp_Delete_DO_TP_DETAIL
@OA_BRANDPACK_ID VARCHAR(75)
AS
DECLARE @V_DO_TP_NO VARCHAR(15)
IF EXISTS(SELECT OA_BRANDPACK_ID FROM DO_TP_DETAIL WHERE OA_BRANDPACK_ID = @OA_BRANDPACK_ID)
   BEGIN
	SET @V_DO_TP_NO = (SELECT DO_TP_NO FROM DO_TP_DETAIL WHERE OA_BRANDPACK_ID = @OA_BRANDPACK_ID)
	DELETE FROM DO_TP_DETAIL WHERE OA_BRANDPACK_ID = @OA_BRANDPACK_ID 
	IF (@@ERROR <= 0)
	   BEGIN
		IF NOT EXISTS(SELECT DO_TP_NO FROM DO_TP_DETAIL WHERE DO_TP_NO = @V_DO_TP_NO) 
		  BEGIN
			DELETE FROM DO_TP_HEADER WHERE DO_TP_NO = @V_DO_TP_NO
		  END
	   END
   END
GO

---------------------PROCEDURE UNTUK MENDELETE --SPPB_BRANDPACK-----------------

IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Delete_SPPB_BrandPack' AND TYPE = 'P')
DROP PROCEDURE Usp_Delete_SPPB_BrandPack
GO
CREATE PROCEDURE Usp_Delete_SPPB_BrandPack
@OA_BRANDPACK_ID VARCHAR(75)
AS
DECLARE @V_SPPB_NO VARCHAR(15)
SET @V_SPPB_NO = (SELECT TOP 1 SPPB_NO FROM SPPB_BRANDPACK WHERE OA_BRANDPACK_ID = @OA_BRANDPACK_ID)
DELETE FROM SPPB_BRANDPACK WHERE OA_BRANDPACK_ID = @OA_BRANDPACK_ID
IF (@@ERROR <= 0)
   BEGIN
     EXEC Usp_Delete_ORDR_OTP_BrandPack_By_OA_BrandPack @OA_BRANDPACK_ID = @OA_BRANDPACK_ID
     IF NOT EXISTS(SELECT SPPB_NO FROM SPPB_BRANDPACK WHERE SPPB_NO = @V_SPPB_NO)
	   BEGIN
                DELETE FROM GON_SMS WHERE SPPB_NO = @V_SPPB_NO;
		DELETE FROM SPPB_HEADER WHERE SPPB_NO =@V_SPPB_NO;
	   END
 
   END
GO
--------------------------------------------------------------------------------------------
---------PROCEDURE UNTUK MEMVIEW SPPB DI GRID_SPPB FORM SPPB----------------------------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Create_View_SPPB_Detail' AND TYPE = 'P')
DROP PROCEDURE Usp_Create_View_SPPB_Detail
GO
CREATE PROCEDURE Usp_Create_View_SPPB_Detail
@DISTRIBUTOR_ID VARCHAR(10),
@FROM_PO_DATE DATETIME,
@UNTIL_PO_DATE DATETIME,
@CATEGORY_DATE VARCHAR(14)
AS
IF (@CATEGORY_DATE = 'ByPO')
   BEGIN
	IF ((@FROM_PO_DATE IS NOT NULL) AND (@UNTIL_PO_DATE IS NOT NULL))
	     BEGIN
		IF (@DISTRIBUTOR_ID IS NOT NULL)
		    BEGIN
				SELECT DISTRIBUTOR_ID,DISTRIBUTOR_NAME,SHIP_TO,MANAGER,PO_REF_NO,PO_REF_DATE,OA_REF_NO,BRAND_NAME,BRANDPACK_ID,
				BRANDPACK_NAME,PO_ORIGINAL_QTY,PRICE,OA_QTY,OA_BRANDPACK_ID,ISNULL(SPPB_NO,'Undefined')AS SPPB_NO,SPPB_DATE,SPPB_QTY,CREATE_DATE,RELEASE_DATE,LEAD_TIME,
				GON_1_NO,GON_1_DATE,GON_1_QTY,GON_1_GT_ID,GON_1_TRANSPORTER_NAME,
				GON_2_NO,GON_2_DATE,GON_2_QTY,GON_2_GT_ID,GON_2_TRANSPORTER_NAME,
				GON_3_NO,GON_3_DATE,GON_3_QTY,GON_3_GT_ID,GON_3_TRANSPORTER_NAME,
				GON_4_NO,GON_4_DATE,GON_4_QTY,GON_4_GT_ID,GON_4_TRANSPORTER_NAME,
				GON_5_NO,GON_5_DATE,GON_5_QTY,GON_5_GT_ID,GON_5_TRANSPORTER_NAME,
				GON_6_NO,GON_6_DATE,GON_6_QTY,GON_6_GT_ID,GON_6_TRANSPORTER_NAME,
				ISNULL(STATUS,'PENDING')AS STATUS,ISNULL(BALANCE,0)AS BALANCE,ISREVISION,REMARK
				FROM VIEW_SPPB_ALL VSA WHERE DISTRIBUTOR_ID = @DISTRIBUTOR_ID
				AND PO_REF_DATE >= @FROM_PO_DATE AND PO_REF_DATE <= @UNTIL_PO_DATE
		    END
		ELSE
		    BEGIN
				SELECT DISTRIBUTOR_ID,DISTRIBUTOR_NAME,SHIP_TO,MANAGER,PO_REF_NO,PO_REF_DATE,OA_REF_NO,BRAND_NAME,BRANDPACK_ID,
				BRANDPACK_NAME,PO_ORIGINAL_QTY,PRICE,OA_QTY,OA_BRANDPACK_ID,ISNULL(SPPB_NO,'Undefined')AS SPPB_NO,SPPB_DATE,SPPB_QTY,CREATE_DATE,RELEASE_DATE,LEAD_TIME,
				GON_1_NO,GON_1_DATE,GON_1_QTY,GON_1_GT_ID,GON_1_TRANSPORTER_NAME,
				GON_2_NO,GON_2_DATE,GON_2_QTY,GON_2_GT_ID,GON_2_TRANSPORTER_NAME,
				GON_3_NO,GON_3_DATE,GON_3_QTY,GON_3_GT_ID,GON_3_TRANSPORTER_NAME,
				GON_4_NO,GON_4_DATE,GON_4_QTY,GON_4_GT_ID,GON_4_TRANSPORTER_NAME,
				GON_5_NO,GON_5_DATE,GON_5_QTY,GON_5_GT_ID,GON_5_TRANSPORTER_NAME,
				GON_6_NO,GON_6_DATE,GON_6_QTY,GON_6_GT_ID,GON_6_TRANSPORTER_NAME,
				ISNULL(STATUS,'PENDING')AS STATUS,ISNULL(BALANCE,0)AS BALANCE,ISREVISION,REMARK
				FROM VIEW_SPPB_ALL VSA WHERE PO_REF_DATE >= @FROM_PO_DATE AND PO_REF_DATE <= @UNTIL_PO_DATE
		    END
	     END
	ELSE IF((@FROM_PO_DATE IS NOT NULL) AND (@UNTIL_PO_DATE IS NOT NULL))
		BEGIN
		   IF(@DISTRIBUTOR_ID IS NOT NULL)
		     BEGIN
				SELECT DISTRIBUTOR_ID,DISTRIBUTOR_NAME,SHIP_TO,MANAGER,PO_REF_NO,PO_REF_DATE,OA_REF_NO,BRAND_NAME,BRANDPACK_ID,BRANDPACK_NAME,PO_ORIGINAL_QTY,PRICE,OA_QTY,
				OA_BRANDPACK_ID,ISNULL(SPPB_NO,'Undefined')AS SPPB_NO,SPPB_DATE,SPPB_QTY,CREATE_DATE,RELEASE_DATE,LEAD_TIME,
				GON_1_NO,GON_1_DATE,GON_1_QTY,GON_1_GT_ID,GON_1_TRANSPORTER_NAME,
				GON_2_NO,GON_2_DATE,GON_2_QTY,GON_2_GT_ID,GON_2_TRANSPORTER_NAME,
				GON_3_NO,GON_3_DATE,GON_3_QTY,GON_3_GT_ID,GON_3_TRANSPORTER_NAME,
				GON_4_NO,GON_4_DATE,GON_4_QTY,GON_4_GT_ID,GON_4_TRANSPORTER_NAME,
				GON_5_NO,GON_5_DATE,GON_5_QTY,GON_5_GT_ID,GON_5_TRANSPORTER_NAME,
				GON_6_NO,GON_6_DATE,GON_6_QTY,GON_6_GT_ID,GON_6_TRANSPORTER_NAME,
				ISNULL(STATUS,'PENDING')AS STATUS,ISNULL(BALANCE,0)AS BALANCE,ISREVISION,REMARK
				FROM VIEW_SPPB_ALL VSA WHERE DISTRIBUTOR_ID = @DISTRIBUTOR_ID
				AND PO_REF_DATE >= @FROM_PO_DATE
		     END
		   ELSE
		     BEGIN
				SELECT DISTRIBUTOR_ID,DISTRIBUTOR_NAME,SHIP_TO,MANAGER,PO_REF_NO,PO_REF_DATE,OA_REF_NO,BRAND_NAME,BRANDPACK_ID,BRANDPACK_NAME,
				PO_ORIGINAL_QTY,PRICE,OA_QTY,OA_BRANDPACK_ID,ISNULL(SPPB_NO,'Undefined')AS SPPB_NO,SPPB_DATE,SPPB_QTY,CREATE_DATE,RELEASE_DATE,LEAD_TIME,
				GON_1_NO,GON_1_DATE,GON_1_QTY,GON_1_GT_ID,GON_1_TRANSPORTER_NAME,
				GON_2_NO,GON_2_DATE,GON_2_QTY,GON_2_GT_ID,GON_2_TRANSPORTER_NAME,
				GON_3_NO,GON_3_DATE,GON_3_QTY,GON_3_GT_ID,GON_3_TRANSPORTER_NAME,
				GON_4_NO,GON_4_DATE,GON_4_QTY,GON_4_GT_ID,GON_4_TRANSPORTER_NAME,
				GON_5_NO,GON_5_DATE,GON_5_QTY,GON_5_GT_ID,GON_5_TRANSPORTER_NAME,
				GON_6_NO,GON_6_DATE,GON_6_QTY,GON_6_GT_ID,GON_6_TRANSPORTER_NAME,
				ISNULL(STATUS,'PENDING')AS STATUS,ISNULL(BALANCE,0)AS BALANCE,ISREVISION,REMARK
				FROM VIEW_SPPB_ALL VSA WHERE PO_REF_DATE >= @FROM_PO_DATE
		     END
		END
	ELSE IF ((@FROM_PO_DATE IS NULL) AND (@UNTIL_PO_DATE IS NOT NULL))
		BEGIN
		   IF (@DISTRIBUTOR_ID IS NOT NULL)
		     BEGIN
				SELECT DISTRIBUTOR_ID,DISTRIBUTOR_NAME,SHIP_TO,MANAGER,PO_REF_NO,PO_REF_DATE,OA_REF_NO,BRAND_NAME,BRANDPACK_ID,BRANDPACK_NAME,
				PO_ORIGINAL_QTY,PRICE,OA_QTY,OA_BRANDPACK_ID,ISNULL(SPPB_NO,'Undefined')AS SPPB_NO,SPPB_DATE,SPPB_QTY,CREATE_DATE,RELEASE_DATE,LEAD_TIME,
				GON_1_NO,GON_1_DATE,GON_1_QTY,GON_1_GT_ID,GON_1_TRANSPORTER_NAME,
				GON_2_NO,GON_2_DATE,GON_2_QTY,GON_2_GT_ID,GON_2_TRANSPORTER_NAME,
				GON_3_NO,GON_3_DATE,GON_3_QTY,GON_3_GT_ID,GON_3_TRANSPORTER_NAME,
				GON_4_NO,GON_4_DATE,GON_4_QTY,GON_4_GT_ID,GON_4_TRANSPORTER_NAME,
				GON_5_NO,GON_5_DATE,GON_5_QTY,GON_5_GT_ID,GON_5_TRANSPORTER_NAME,
				GON_6_NO,GON_6_DATE,GON_6_QTY,GON_6_GT_ID,GON_6_TRANSPORTER_NAME,
				ISNULL(STATUS,'PENDING')AS STATUS,ISNULL(BALANCE,0)AS BALANCE,ISREVISION,REMARK
				FROM VIEW_SPPB_ALL VSA WHERE DISTRIBUTOR_ID = @DISTRIBUTOR_ID
				AND PO_REF_DATE <= @UNTIL_PO_DATE
		     END
		   ELSE
		     BEGIN
				SELECT DISTRIBUTOR_ID,DISTRIBUTOR_NAME,SHIP_TO,MANAGER,PO_REF_NO,PO_REF_DATE,OA_REF_NO,BRAND_NAME,BRANDPACK_ID,BRANDPACK_NAME,
				PO_ORIGINAL_QTY,PRICE,OA_QTY,OA_BRANDPACK_ID,ISNULL(SPPB_NO,'Undefined')AS SPPB_NO,SPPB_DATE,SPPB_QTY,CREATE_DATE,RELEASE_DATE,LEAD_TIME,
				GON_1_NO,GON_1_DATE,GON_1_QTY,GON_1_GT_ID,GON_1_TRANSPORTER_NAME,
				GON_2_NO,GON_2_DATE,GON_2_QTY,GON_2_GT_ID,GON_2_TRANSPORTER_NAME,
				GON_3_NO,GON_3_DATE,GON_3_QTY,GON_3_GT_ID,GON_3_TRANSPORTER_NAME,
				GON_4_NO,GON_4_DATE,GON_4_QTY,GON_4_GT_ID,GON_4_TRANSPORTER_NAME,
				GON_5_NO,GON_5_DATE,GON_5_QTY,GON_5_GT_ID,GON_5_TRANSPORTER_NAME,
				GON_6_NO,GON_6_DATE,GON_6_QTY,GON_6_GT_ID,GON_6_TRANSPORTER_NAME,
				ISNULL(STATUS,'PENDING')AS STATUS,ISNULL(BALANCE,0)AS BALANCE,ISREVISION,REMARK
				FROM VIEW_SPPB_ALL VSA WHERE PO_REF_DATE <= @UNTIL_PO_DATE
		     END
		END
	ELSE IF ((@FROM_PO_DATE IS NULL) AND (@UNTIL_PO_DATE IS NULL))
		BEGIN
		    IF(@DISTRIBUTOR_ID IS NOT NULL)
		      BEGIN
				 SELECT DISTRIBUTOR_ID,DISTRIBUTOR_NAME,SHIP_TO,MANAGER,PO_REF_NO,PO_REF_DATE,OA_REF_NO,BRAND_NAME,BRANDPACK_ID, BRANDPACK_NAME,
				 PO_ORIGINAL_QTY,PRICE,OA_QTY,OA_BRANDPACK_ID,ISNULL(SPPB_NO,'Undefined')AS SPPB_NO,SPPB_DATE,SPPB_QTY,CREATE_DATE,RELEASE_DATE,LEAD_TIME,GON_1_NO,
				 GON_1_NO,GON_1_DATE,GON_1_QTY,GON_1_GT_ID,GON_1_TRANSPORTER_NAME,
				 GON_2_NO,GON_2_DATE,GON_2_QTY,GON_2_GT_ID,GON_2_TRANSPORTER_NAME,
				 GON_3_NO,GON_3_DATE,GON_3_QTY,GON_3_GT_ID,GON_3_TRANSPORTER_NAME,
				 GON_4_NO,GON_4_DATE,GON_4_QTY,GON_4_GT_ID,GON_4_TRANSPORTER_NAME,
				 GON_5_NO,GON_5_DATE,GON_5_QTY,GON_5_GT_ID,GON_5_TRANSPORTER_NAME,
				 GON_6_NO,GON_6_DATE,GON_6_QTY,GON_6_GT_ID,GON_6_TRANSPORTER_NAME,
				 ISNULL(STATUS,'PENDING')AS STATUS,ISNULL(BALANCE,0)AS BALANCE,ISREVISION,REMARK
				 FROM VIEW_SPPB_ALL VSA WHERE DISTRIBUTOR_ID = @DISTRIBUTOR_ID
		      END
		     ELSE
		       BEGIN
				  SELECT DISTRIBUTOR_ID,DISTRIBUTOR_NAME,SHIP_TO,MANAGER,PO_REF_NO,PO_REF_DATE,OA_REF_NO,BRAND_NAME,BRANDPACK_ID, BRANDPACK_NAME,
				  PO_ORIGINAL_QTY,PRICE,OA_QTY,OA_BRANDPACK_ID,ISNULL(SPPB_NO,'Undefined')AS SPPB_NO,SPPB_DATE,SPPB_QTY,CREATE_DATE,RELEASE_DATE,LEAD_TIME,GON_1_NO,
				  GON_1_NO,GON_1_DATE,GON_1_QTY,GON_1_GT_ID,GON_1_TRANSPORTER_NAME,
				  GON_2_NO,GON_2_DATE,GON_2_QTY,GON_2_GT_ID,GON_2_TRANSPORTER_NAME,
				  GON_3_NO,GON_3_DATE,GON_3_QTY,GON_3_GT_ID,GON_3_TRANSPORTER_NAME,
				  GON_4_NO,GON_4_DATE,GON_4_QTY,GON_4_GT_ID,GON_4_TRANSPORTER_NAME,
				  GON_5_NO,GON_5_DATE,GON_5_QTY,GON_5_GT_ID,GON_5_TRANSPORTER_NAME,
				  GON_6_NO,GON_6_DATE,GON_6_QTY,GON_6_GT_ID,GON_6_TRANSPORTER_NAME,
				  ISNULL(STATUS,'PENDING')AS STATUS,ISNULL(BALANCE,0)AS BALANCE,ISREVISION,REMARK
				  FROM VIEW_SPPB_ALL VSA 
		       END	
		END
	
   END

ELSE
   BEGIN
	IF ((@FROM_PO_DATE IS NOT NULL) AND (@UNTIL_PO_DATE IS NOT NULL))
	     BEGIN
		IF (@DISTRIBUTOR_ID IS NOT NULL)
		    BEGIN
				SELECT DISTRIBUTOR_ID,DISTRIBUTOR_NAME,SHIP_TO,MANAGER,PO_REF_NO,PO_REF_DATE,OA_REF_NO,BRAND_NAME,BRANDPACK_ID,
				BRANDPACK_NAME,PO_ORIGINAL_QTY,PRICE,OA_QTY,OA_BRANDPACK_ID,ISNULL(SPPB_NO,'Undefined')AS SPPB_NO,SPPB_DATE,SPPB_QTY,CREATE_DATE,RELEASE_DATE,LEAD_TIME,
				GON_1_NO,GON_1_DATE,GON_1_QTY,GON_1_GT_ID,GON_1_TRANSPORTER_NAME,
				GON_2_NO,GON_2_DATE,GON_2_QTY,GON_2_GT_ID,GON_2_TRANSPORTER_NAME,
				GON_3_NO,GON_3_DATE,GON_3_QTY,GON_3_GT_ID,GON_3_TRANSPORTER_NAME,
				GON_4_NO,GON_4_DATE,GON_4_QTY,GON_4_GT_ID,GON_4_TRANSPORTER_NAME,
				GON_5_NO,GON_5_DATE,GON_5_QTY,GON_5_GT_ID,GON_5_TRANSPORTER_NAME,
				GON_6_NO,GON_6_DATE,GON_6_QTY,GON_6_GT_ID,GON_6_TRANSPORTER_NAME,
				ISNULL(STATUS,'PENDING')AS STATUS,ISNULL(BALANCE,0)AS BALANCE,ISREVISION,REMARK
				FROM VIEW_SPPB_ALL VSA WHERE DISTRIBUTOR_ID = @DISTRIBUTOR_ID
				AND SPPB_DATE >= @FROM_PO_DATE AND SPPB_DATE <= @UNTIL_PO_DATE
		    END
		ELSE
		    BEGIN
				SELECT DISTRIBUTOR_ID,DISTRIBUTOR_NAME,SHIP_TO,MANAGER,PO_REF_NO,PO_REF_DATE,OA_REF_NO,BRAND_NAME,BRANDPACK_ID,
				BRANDPACK_NAME,PO_ORIGINAL_QTY,PRICE,OA_QTY,OA_BRANDPACK_ID,ISNULL(SPPB_NO,'Undefined')AS SPPB_NO,SPPB_DATE,SPPB_QTY,CREATE_DATE,RELEASE_DATE,LEAD_TIME,
				GON_1_NO,GON_1_DATE,GON_1_QTY,GON_1_GT_ID,GON_1_TRANSPORTER_NAME,
				GON_2_NO,GON_2_DATE,GON_2_QTY,GON_2_GT_ID,GON_2_TRANSPORTER_NAME,
				GON_3_NO,GON_3_DATE,GON_3_QTY,GON_3_GT_ID,GON_3_TRANSPORTER_NAME,
				GON_4_NO,GON_4_DATE,GON_4_QTY,GON_4_GT_ID,GON_4_TRANSPORTER_NAME,
				GON_5_NO,GON_5_DATE,GON_5_QTY,GON_5_GT_ID,GON_5_TRANSPORTER_NAME,
				GON_6_NO,GON_6_DATE,GON_6_QTY,GON_6_GT_ID,GON_6_TRANSPORTER_NAME,
				ISNULL(STATUS,'PENDING')AS STATUS,ISNULL(BALANCE,0)AS BALANCE,ISREVISION,REMARK
				FROM VIEW_SPPB_ALL VSA WHERE SPPB_DATE >= @FROM_PO_DATE AND SPPB_DATE <= @UNTIL_PO_DATE
		    END
	     END
	ELSE IF((@FROM_PO_DATE IS NOT NULL) AND (@UNTIL_PO_DATE IS NOT NULL))
		BEGIN
		   IF(@DISTRIBUTOR_ID IS NOT NULL)
		     BEGIN
				SELECT DISTRIBUTOR_ID,DISTRIBUTOR_NAME,SHIP_TO,MANAGER,PO_REF_NO,PO_REF_DATE,OA_REF_NO,BRAND_NAME,BRANDPACK_ID,BRANDPACK_NAME,PO_ORIGINAL_QTY,PRICE,OA_QTY,
				OA_BRANDPACK_ID,ISNULL(SPPB_NO,'Undefined')AS SPPB_NO,SPPB_DATE,SPPB_QTY,CREATE_DATE,RELEASE_DATE,LEAD_TIME,
				GON_1_NO,GON_1_DATE,GON_1_QTY,GON_1_GT_ID,GON_1_TRANSPORTER_NAME,
				GON_2_NO,GON_2_DATE,GON_2_QTY,GON_2_GT_ID,GON_2_TRANSPORTER_NAME,
				GON_3_NO,GON_3_DATE,GON_3_QTY,GON_3_GT_ID,GON_3_TRANSPORTER_NAME,
				GON_4_NO,GON_4_DATE,GON_4_QTY,GON_4_GT_ID,GON_4_TRANSPORTER_NAME,
				GON_5_NO,GON_5_DATE,GON_5_QTY,GON_5_GT_ID,GON_5_TRANSPORTER_NAME,
				GON_6_NO,GON_6_DATE,GON_6_QTY,GON_6_GT_ID,GON_6_TRANSPORTER_NAME,
				ISNULL(STATUS,'PENDING')AS STATUS,ISNULL(BALANCE,0)AS BALANCE,ISREVISION,REMARK
				FROM VIEW_SPPB_ALL VSA WHERE DISTRIBUTOR_ID = @DISTRIBUTOR_ID
				AND SPPB_DATE >= @FROM_PO_DATE
		     END
		   ELSE
		     BEGIN
				SELECT DISTRIBUTOR_ID,DISTRIBUTOR_NAME,SHIP_TO,MANAGER,PO_REF_NO,PO_REF_DATE,OA_REF_NO,BRAND_NAME,BRANDPACK_ID,BRANDPACK_NAME,
				PO_ORIGINAL_QTY,PRICE,OA_QTY,OA_BRANDPACK_ID,ISNULL(SPPB_NO,'Undefined')AS SPPB_NO,SPPB_DATE,SPPB_QTY,CREATE_DATE,RELEASE_DATE,LEAD_TIME,
				GON_1_NO,GON_1_DATE,GON_1_QTY,GON_1_GT_ID,GON_1_TRANSPORTER_NAME,
				GON_2_NO,GON_2_DATE,GON_2_QTY,GON_2_GT_ID,GON_2_TRANSPORTER_NAME,
				GON_3_NO,GON_3_DATE,GON_3_QTY,GON_3_GT_ID,GON_3_TRANSPORTER_NAME,
				GON_4_NO,GON_4_DATE,GON_4_QTY,GON_4_GT_ID,GON_4_TRANSPORTER_NAME,
				GON_5_NO,GON_5_DATE,GON_5_QTY,GON_5_GT_ID,GON_5_TRANSPORTER_NAME,
				GON_6_NO,GON_6_DATE,GON_6_QTY,GON_6_GT_ID,GON_6_TRANSPORTER_NAME,
				ISNULL(STATUS,'PENDING')AS STATUS,ISNULL(BALANCE,0)AS BALANCE,ISREVISION,REMARK
				FROM VIEW_SPPB_ALL VSA WHERE SPPB_DATE >= @FROM_PO_DATE
		     END
		END
	ELSE IF ((@FROM_PO_DATE IS NULL) AND (@UNTIL_PO_DATE IS NOT NULL))
		BEGIN
		   IF (@DISTRIBUTOR_ID IS NOT NULL)
		     BEGIN
				SELECT DISTRIBUTOR_ID,DISTRIBUTOR_NAME,SHIP_TO,MANAGER,PO_REF_NO,PO_REF_DATE,OA_REF_NO,BRAND_NAME,BRANDPACK_ID,BRANDPACK_NAME,
				PO_ORIGINAL_QTY,PRICE,OA_QTY,OA_BRANDPACK_ID,ISNULL(SPPB_NO,'Undefined')AS SPPB_NO,SPPB_DATE,SPPB_QTY,CREATE_DATE,RELEASE_DATE,LEAD_TIME,
				GON_1_NO,GON_1_DATE,GON_1_QTY,GON_1_GT_ID,GON_1_TRANSPORTER_NAME,
				GON_2_NO,GON_2_DATE,GON_2_QTY,GON_2_GT_ID,GON_2_TRANSPORTER_NAME,
				GON_3_NO,GON_3_DATE,GON_3_QTY,GON_3_GT_ID,GON_3_TRANSPORTER_NAME,
				GON_4_NO,GON_4_DATE,GON_4_QTY,GON_4_GT_ID,GON_4_TRANSPORTER_NAME,
				GON_5_NO,GON_5_DATE,GON_5_QTY,GON_5_GT_ID,GON_5_TRANSPORTER_NAME,
				GON_6_NO,GON_6_DATE,GON_6_QTY,GON_6_GT_ID,GON_6_TRANSPORTER_NAME,
				ISNULL(STATUS,'PENDING')AS STATUS,ISNULL(BALANCE,0)AS BALANCE,ISREVISION,REMARK
				FROM VIEW_SPPB_ALL VSA WHERE DISTRIBUTOR_ID = @DISTRIBUTOR_ID
				AND SPPB_DATE <= @UNTIL_PO_DATE
		     END
		   ELSE
		     BEGIN
				SELECT DISTRIBUTOR_ID,DISTRIBUTOR_NAME,SHIP_TO,MANAGER,PO_REF_NO,PO_REF_DATE,OA_REF_NO,BRAND_NAME,BRANDPACK_ID,BRANDPACK_NAME,
				PO_ORIGINAL_QTY,PRICE,OA_QTY,OA_BRANDPACK_ID,ISNULL(SPPB_NO,'Undefined')AS SPPB_NO,SPPB_DATE,SPPB_QTY,CREATE_DATE,RELEASE_DATE,LEAD_TIME,
				GON_1_NO,GON_1_DATE,GON_1_QTY,GON_1_GT_ID,GON_1_TRANSPORTER_NAME,
				GON_2_NO,GON_2_DATE,GON_2_QTY,GON_2_GT_ID,GON_2_TRANSPORTER_NAME,
				GON_3_NO,GON_3_DATE,GON_3_QTY,GON_3_GT_ID,GON_3_TRANSPORTER_NAME,
				GON_4_NO,GON_4_DATE,GON_4_QTY,GON_4_GT_ID,GON_4_TRANSPORTER_NAME,
				GON_5_NO,GON_5_DATE,GON_5_QTY,GON_5_GT_ID,GON_5_TRANSPORTER_NAME,
				GON_6_NO,GON_6_DATE,GON_6_QTY,GON_6_GT_ID,GON_6_TRANSPORTER_NAME,
				ISNULL(STATUS,'PENDING')AS STATUS,ISNULL(BALANCE,0)AS BALANCE,ISREVISION,REMARK
				FROM VIEW_SPPB_ALL VSA WHERE SPPB_DATE <= @UNTIL_PO_DATE
		     END
		END
	ELSE IF ((@FROM_PO_DATE IS NULL) AND (@UNTIL_PO_DATE IS NULL))
		BEGIN
		    IF(@DISTRIBUTOR_ID IS NOT NULL)
		      BEGIN
				SELECT DISTRIBUTOR_ID,DISTRIBUTOR_NAME,SHIP_TO,MANAGER,PO_REF_NO,PO_REF_DATE,OA_REF_NO,BRAND_NAME,BRANDPACK_ID, BRANDPACK_NAME,
				PO_ORIGINAL_QTY,PRICE,OA_QTY,OA_BRANDPACK_ID,ISNULL(SPPB_NO,'Undefined')AS SPPB_NO,SPPB_DATE,SPPB_QTY,CREATE_DATE,RELEASE_DATE,LEAD_TIME,GON_1_NO,
				GON_1_NO,GON_1_DATE,GON_1_QTY,GON_1_GT_ID,GON_1_TRANSPORTER_NAME,
				GON_2_NO,GON_2_DATE,GON_2_QTY,GON_2_GT_ID,GON_2_TRANSPORTER_NAME,
				GON_3_NO,GON_3_DATE,GON_3_QTY,GON_3_GT_ID,GON_3_TRANSPORTER_NAME,
				GON_4_NO,GON_4_DATE,GON_4_QTY,GON_4_GT_ID,GON_4_TRANSPORTER_NAME,
				GON_5_NO,GON_5_DATE,GON_5_QTY,GON_5_GT_ID,GON_5_TRANSPORTER_NAME,
				GON_6_NO,GON_6_DATE,GON_6_QTY,GON_6_GT_ID,GON_6_TRANSPORTER_NAME,
				ISNULL(STATUS,'PENDING')AS STATUS,ISNULL(BALANCE,0)AS BALANCE,ISREVISION,REMARK
				FROM VIEW_SPPB_ALL VSA WHERE DISTRIBUTOR_ID = @DISTRIBUTOR_ID
		      END
		     ELSE
		       BEGIN
				 SELECT DISTRIBUTOR_ID,DISTRIBUTOR_NAME,SHIP_TO,MANAGER,PO_REF_NO,PO_REF_DATE,OA_REF_NO,BRAND_NAME,BRANDPACK_ID, BRANDPACK_NAME,
				 PO_ORIGINAL_QTY,PRICE,OA_QTY,OA_BRANDPACK_ID,ISNULL(SPPB_NO,'Undefined')AS SPPB_NO,SPPB_DATE,SPPB_QTY,CREATE_DATE,RELEASE_DATE,LEAD_TIME,
				 GON_1_NO,GON_1_DATE,GON_1_QTY,GON_1_GT_ID,GON_1_TRANSPORTER_NAME,
				 GON_2_NO,GON_2_DATE,GON_2_QTY,GON_2_GT_ID,GON_2_TRANSPORTER_NAME,
				 GON_3_NO,GON_3_DATE,GON_3_QTY,GON_3_GT_ID,GON_3_TRANSPORTER_NAME,
				 GON_4_NO,GON_4_DATE,GON_4_QTY,GON_4_GT_ID,GON_4_TRANSPORTER_NAME,
				 GON_5_NO,GON_5_DATE,GON_5_QTY,GON_5_GT_ID,GON_5_TRANSPORTER_NAME,
				 GON_6_NO,GON_6_DATE,GON_6_QTY,GON_6_GT_ID,GON_6_TRANSPORTER_NAME,
				 ISNULL(STATUS,'PENDING')AS STATUS,ISNULL(BALANCE,0)AS BALANCE,ISREVISION,REMARK
				 FROM VIEW_SPPB_ALL VSA 
		       END	
		END	
   END	
GO
--exec Usp_Create_View_SPPB_Detail
--@DISTRIBUTOR_ID = 'AGR016IDR',
--@FROM_PO_DATE = null,--DATETIME,
--@UNTIL_PO_DATE = '5/24/2009',--DATETIME
--@CATEGORY_DATE = 'ByPO'
-------------------------VIEW UNTUK SPPB_ENTRY----------------------------------------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Create_View_SPPB_Detail_Entry' AND TYPE = 'P')
DROP PROCEDURE Usp_Create_View_SPPB_Detail_Entry
GO
CREATE PROCEDURE Usp_Create_View_SPPB_Detail_Entry
@SPPB_NO VARCHAR(15)
AS
SET NOCOUNT ON;
SELECT OPB.BRANDPACK_ID,SB.OA_BRANDPACK_ID,SB.SPPB_BRANDPACK_ID,SB.SPPB_NO,SB.SPPB_QTY,
SB.GON_1_NO,SB.GON_1_DATE,SB.GON_1_QTY,SB.GON_1_GT_ID,SB.GON_1_TRANSPORTER_NAME,
SB.GON_2_NO,SB.GON_2_DATE,SB.GON_2_QTY,SB.GON_2_GT_ID,SB.GON_2_TRANSPORTER_NAME,
SB.GON_3_NO,SB.GON_3_DATE,SB.GON_3_QTY,SB.GON_3_GT_ID,SB.GON_3_TRANSPORTER_NAME,
SB.GON_4_NO,SB.GON_4_DATE,SB.GON_4_QTY,SB.GON_4_GT_ID,SB.GON_4_TRANSPORTER_NAME,
SB.GON_5_NO,SB.GON_5_DATE,SB.GON_5_QTY,SB.GON_5_GT_ID,SB.GON_5_TRANSPORTER_NAME,
SB.GON_6_NO,SB.GON_6_DATE,SB.GON_6_QTY,SB.GON_6_GT_ID,SB.GON_6_TRANSPORTER_NAME,
SB.STATUS,SB.BALANCE,SB.REMARK,SB.ISREVISION,SB.CREATE_BY,SB.CREATE_DATE,SB.RELEASE_DATE,SB.MODIFY_BY,SB.MODIFY_DATE 
FROM  ORDR_PO_BRANDPACK OPB  INNER JOIN ORDR_OA_BRANDPACK OOB
ON OOB.PO_BRANDPACK_ID = OPB.PO_BRANDPACK_ID 
INNER JOIN SPPB_BRANDPACK SB ON  SB.OA_BRANDPACK_ID = OOB.OA_BRANDPACK_ID
WHERE SB.SPPB_NO = @SPPB_NO
GO
--exec Usp_Create_View_SPPB_Detail_Entry @SPPB_NO = 'OA_SPPB_1'
-------------------------------------------------------------------------------------------
------------------------------------BRANDPACK UNTUK VALUELIST SPPB DETAIL----------------
--IF EXISTS(SELECT NAME FROM 
-------------------------------------------------------------------------------------
--------PROCEDURE UNTUK MEMVIEW THIRD PARTY----------------------------------------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Create_View_Third_Party' AND TYPE = 'P')
DROP PROCEDURE Usp_Create_View_Third_Party
GO
CREATE PROCEDURE Usp_Create_View_Third_Party
@DISTRIBUTOR_ID VARCHAR(10),
@FROM_SPPB_DATE DATETIME,
@UNTIL_SPPB_DATE DATETIME
AS
IF ((@FROM_SPPB_DATE IS NOT NULL) AND (@UNTIL_SPPB_DATE IS NOT NULL))
    BEGIN
		
	IF (@DISTRIBUTOR_ID IS NOT NULL)
	    BEGIN
		SELECT DISTRIBUTOR_ID,DISTRIBUTOR_NAME,SHIP_TO,MANAGER,PO_REF_NO,PO_REF_DATE,BRAND_NAME,BRANDPACK_ID,BRANDPACK_NAME,
		PO_ORIGINAL_QTY,OA_BRANDPACK_ID,ISNULL(SPPB_NO,'Undefined') AS SPPB_NO,SPPB_DATE,SPPB_QTY,ISNULL(STATUS,'PENDING') AS STATUS,
		BALANCE,OTP_NO,OTP_DATE,OTP_QTY,OTP_CREATE_DATE,DO_TP_NO,DO_TP_DATE,DO_TP_QTY,REMARK
		FROM VIEW_SPPB_ALL WHERE DISTRIBUTOR_ID = @DISTRIBUTOR_ID AND SPPB_DATE >= @FROM_SPPB_DATE
		AND SPPB_DATE <= @UNTIL_SPPB_DATE AND SPPB_DATE IS NOT NULL AND BRANDPACK_NAME LIKE 'ROUNDUP%'
	    END
	ELSE
	    BEGIN
		SELECT DISTRIBUTOR_ID,DISTRIBUTOR_NAME,SHIP_TO,MANAGER,PO_REF_NO,PO_REF_DATE,BRAND_NAME,BRANDPACK_ID,BRANDPACK_NAME,
		PO_ORIGINAL_QTY,OA_BRANDPACK_ID,ISNULL(SPPB_NO,'Undefined') AS SPPB_NO,SPPB_DATE,SPPB_QTY,ISNULL(STATUS,'PENDING') AS STATUS,
		BALANCE,OTP_NO,OTP_DATE,OTP_QTY,OTP_CREATE_DATE,DO_TP_NO,DO_TP_DATE,DO_TP_QTY,REMARK
		FROM VIEW_SPPB_ALL WHERE SPPB_DATE >= @FROM_SPPB_DATE 
		AND SPPB_DATE <= @UNTIL_SPPB_DATE AND SPPB_DATE IS NOT NULL AND BRANDPACK_NAME LIKE 'ROUNDUP%'
	    END	
		
    END
ELSE IF ((@FROM_SPPB_DATE IS NOT NULL) AND(@UNTIL_SPPB_DATE IS NULL))
    BEGIN
		
	IF (@DISTRIBUTOR_ID IS NOT NULL)
	    BEGIN
		SELECT DISTRIBUTOR_ID,DISTRIBUTOR_NAME,SHIP_TO,MANAGER,PO_REF_NO,PO_REF_DATE,BRAND_NAME,BRANDPACK_ID,BRANDPACK_NAME,
		PO_ORIGINAL_QTY,OA_BRANDPACK_ID,ISNULL(SPPB_NO,'Undefined') AS SPPB_NO,SPPB_DATE,SPPB_QTY,ISNULL(STATUS,'PENDING') AS STATUS,
		BALANCE,OTP_NO,OTP_DATE,OTP_QTY,OTP_CREATE_DATE,DO_TP_NO,DO_TP_DATE,DO_TP_QTY,REMARK
		FROM VIEW_SPPB_ALL WHERE DISTRIBUTOR_ID = @DISTRIBUTOR_ID AND SPPB_DATE >= @FROM_SPPB_DATE 
		AND SPPB_DATE IS NOT NULL AND BRANDPACK_NAME LIKE 'ROUNDUP%'
	    END
	ELSE
	    BEGIN
		SELECT DISTRIBUTOR_ID,DISTRIBUTOR_NAME,SHIP_TO,MANAGER,PO_REF_NO,PO_REF_DATE,BRAND_NAME,BRANDPACK_ID,BRANDPACK_NAME,
		PO_ORIGINAL_QTY,OA_BRANDPACK_ID,ISNULL(SPPB_NO,'Undefined') AS SPPB_NO,SPPB_DATE,SPPB_QTY,ISNULL(STATUS,'PENDING') AS STATUS,
		BALANCE,OTP_NO,OTP_DATE,OTP_QTY,OTP_CREATE_DATE,DO_TP_NO,DO_TP_DATE,DO_TP_QTY,REMARK
		FROM VIEW_SPPB_ALL WHERE SPPB_DATE >= @FROM_SPPB_DATE  AND SPPB_DATE IS NOT NULL AND BRANDPACK_NAME LIKE 'ROUNDUP%'
	    END	
     END	
ELSE IF ((@FROM_SPPB_DATE IS NULL) AND (@UNTIL_SPPB_DATE IS NOT NULL))
    BEGIN
	
	IF (@DISTRIBUTOR_ID IS NOT NULL)
	    BEGIN
		SELECT DISTRIBUTOR_ID,DISTRIBUTOR_NAME,SHIP_TO,MANAGER,PO_REF_NO,PO_REF_DATE,BRAND_NAME,BRANDPACK_ID,BRANDPACK_NAME,
		PO_ORIGINAL_QTY,OA_BRANDPACK_ID,ISNULL(SPPB_NO,'Undefined') AS SPPB_NO,SPPB_DATE,SPPB_QTY,ISNULL(STATUS,'PENDING') AS STATUS,
		BALANCE,OTP_NO,OTP_DATE,OTP_QTY,OTP_CREATE_DATE,DO_TP_NO,DO_TP_DATE,DO_TP_QTY,REMARK
		FROM VIEW_SPPB_ALL WHERE DISTRIBUTOR_ID = @DISTRIBUTOR_ID 
		AND SPPB_DATE <= @UNTIL_SPPB_DATE AND SPPB_DATE IS NOT NULL AND BRANDPACK_NAME LIKE 'ROUNDUP%'
	    END
	ELSE
	    BEGIN
	 	SELECT DISTRIBUTOR_ID,DISTRIBUTOR_NAME,SHIP_TO,MANAGER,PO_REF_NO,PO_REF_DATE,BRAND_NAME,BRANDPACK_ID,BRANDPACK_NAME,
		PO_ORIGINAL_QTY,OA_BRANDPACK_ID,ISNULL(SPPB_NO,'Undefined') AS SPPB_NO,SPPB_DATE,SPPB_QTY,ISNULL(STATUS,'PENDING') AS STATUS,
		BALANCE,OTP_NO,OTP_DATE,OTP_QTY,OTP_CREATE_DATE,DO_TP_NO,DO_TP_DATE,DO_TP_QTY,REMARK
		FROM VIEW_SPPB_ALL WHERE SPPB_DATE <= @UNTIL_SPPB_DATE AND SPPB_DATE IS NOT NULL AND BRANDPACK_NAME LIKE 'ROUNDUP%'
	    END
	
     END
ELSE IF ((@FROM_SPPB_DATE IS NULL) AND(@UNTIL_SPPB_DATE IS NULL))
     BEGIN

	IF (@DISTRIBUTOR_ID IS NOT NULL)
	    BEGIN
		SELECT DISTRIBUTOR_ID,DISTRIBUTOR_NAME,SHIP_TO,MANAGER,PO_REF_NO,PO_REF_DATE,BRAND_NAME,BRANDPACK_ID,BRANDPACK_NAME,
		PO_ORIGINAL_QTY,OA_BRANDPACK_ID,ISNULL(SPPB_NO,'Undefined') AS SPPB_NO,SPPB_DATE,SPPB_QTY,ISNULL(STATUS,'PENDING') AS STATUS,
		BALANCE,OTP_NO,OTP_DATE,OTP_QTY,OTP_CREATE_DATE,DO_TP_NO,DO_TP_DATE,DO_TP_QTY,REMARK
		FROM VIEW_SPPB_ALL WHERE DISTRIBUTOR_ID = @DISTRIBUTOR_ID  AND SPPB_DATE IS NOT NULL AND BRANDPACK_NAME LIKE 'ROUNDUP%'
	    END
	ELSE
	    BEGIN
		SELECT DISTRIBUTOR_ID,DISTRIBUTOR_NAME,SHIP_TO,MANAGER,PO_REF_NO,PO_REF_DATE,BRAND_NAME,BRANDPACK_ID,BRANDPACK_NAME,
		PO_ORIGINAL_QTY,OA_BRANDPACK_ID,ISNULL(SPPB_NO,'Undefined') AS SPPB_NO,SPPB_DATE,SPPB_QTY,ISNULL(STATUS,'PENDING') AS STATUS,
		BALANCE,OTP_NO,OTP_DATE,OTP_QTY,OTP_CREATE_DATE,DO_TP_NO,DO_TP_DATE,DO_TP_QTY,REMARK
		
		FROM VIEW_SPPB_ALL
		WHERE SPPB_DATE  IS NOT NULL AND BRANDPACK_NAME LIKE 'ROUNDUP%'
	    END
     END
  

GO

---------------------------VIEW UNTUK OA_REF_NO SPPB_ENTRY------------------DI MCBOA_REF_NO
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Create_View_OA_Ref_No_SPPB_Entry' AND TYPE = 'P')
DROP PROCEDURE Usp_Create_View_OA_Ref_No_SPPB_Entry
GO
CREATE PROCEDURE Usp_Create_View_OA_Ref_No_SPPB_Entry
@DISTRIBUTOR_ID VARCHAR(10),
@ISREGISTEREDSPPB  BIT
AS
SET NOCOUNT ON;
IF (@ISREGISTEREDSPPB = 0)
   BEGIN
    SELECT OOA.OA_ID AS OA_REF_NO,OOA.PO_REF_NO,OPO.PO_REF_DATE FROM ORDR_ORDER_ACCEPTANCE OOA INNER JOIN ORDR_PURCHASE_ORDER OPO
    ON OPO.PO_REF_NO = OOA.PO_REF_NO
    WHERE OPO.DISTRIBUTOR_ID = @DISTRIBUTOR_ID AND YEAR(OOA.OA_DATE) >= YEAR(GETDATE()) -1
    AND NOT EXISTS(SELECT OA_ID FROM ORDR_OA_BRANDPACK OOAB INNER JOIN SPPB_BRANDPACK SB 
              	    ON OOAB.OA_BRANDPACK_ID = SB.OA_BRANDPACK_ID 
                    WHERE OOAB.OA_ID = OOA.OA_ID
                    ); 
   END
ELSE
   BEGIN
       SELECT OOA.OA_ID AS OA_REF_NO,OOA.PO_REF_NO,OPO.PO_REF_DATE FROM ORDR_ORDER_ACCEPTANCE OOA INNER JOIN ORDR_PURCHASE_ORDER OPO
   	 ON OPO.PO_REF_NO = OOA.PO_REF_NO
   	 WHERE OPO.DISTRIBUTOR_ID = @DISTRIBUTOR_ID AND YEAR(OOA.OA_DATE) >= YEAR(GETDATE()) -1
      	 AND EXISTS(SELECT OA_ID FROM ORDR_OA_BRANDPACK OOAB INNER JOIN SPPB_BRANDPACK SB 
              	    ON OOAB.OA_BRANDPACK_ID = SB.OA_BRANDPACK_ID 
                    WHERE OOAB.OA_ID = OOA.OA_ID
                    ); 
   END
GO
----------------------------------------------------------------------------------
-------------------------PROCEDURE UNTUK SEARCHING OA_REF_NO DO FORM SPPB ENTRY----
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Search_OA_Ref_NO_SPPB_Entry' AND TYPE = 'P')
DROP PROCEDURE Usp_Search_OA_Ref_NO_SPPB_Entry
GO
CREATE PROCEDURE Usp_Search_OA_Ref_NO_SPPB_Entry
@SEARCH_OA_REF_NO VARCHAR(75),
@DISTRIBUTOR_ID VARCHAR(10)

AS
SELECT OOA.OA_ID AS OA_REF_NO,OOA.PO_REF_NO,OPO.PO_REF_DATE FROM ORDR_ORDER_ACCEPTANCE OOA INNER JOIN ORDR_PURCHASE_ORDER OPO
ON OPO.PO_REF_NO = OOA.PO_REF_NO
WHERE OPO.DISTRIBUTOR_ID = @DISTRIBUTOR_ID AND YEAR(OOA.OA_DATE) >= YEAR(GETDATE()) -1
AND EXISTS(SELECT OA_ID FROM ORDR_OA_BRANDPACK WHERE OA_ID = OOA.OA_ID)
AND OOA.OA_ID LIKE @SEARCH_OA_REF_NO + '%'
 AND NOT EXISTS(SELECT OA_BRANDPACK_ID FROM SPPB_BRANDPACK WHERE OA_BRANDPACK_ID IN
    (SELECT OA_BRANDPACK_ID FROM ORDR_OA_BRANDPACK WHERE OA_ID = OOA.OA_ID))
GO
 -----------------------------PROCEDURE UNTUK INFLATEDATAMCBREFNO---------------------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Getrow_By_OA_Ref_No' AND TYPE = 'P')
DROP PROCEDURE Usp_Getrow_By_OA_Ref_No
GO
CREATE PROCEDURE Usp_Getrow_By_OA_Ref_No
@OA_ID VARCHAR(32)
AS
SET NOCOUNT ON;
IF EXISTS(SELECT TOP 1 SPPB_NO FROM ORDR_ORDER_ACCEPTANCE OOA INNER JOIN ORDR_OA_BRANDPACK OOB ON OOB.OA_ID = OOA.OA_ID LEFT OUTER JOIN
SPPB_BRANDPACK SB ON SB.OA_BRANDPACK_ID = OOB.OA_BRANDPACK_ID WHERE OOB.OA_ID = @OA_ID  AND SB.SPPB_NO IS NOT NULL)
BEGIN
     SELECT TOP 1 OOA.OA_DATE,ISNULL(SB.SPPB_NO,'Undefined')AS SPPB_NO,ISNULL(SH.SPPB_DATE,GETDATE()) AS SPPB_DATE
     FROM ORDR_ORDER_ACCEPTANCE OOA INNER JOIN ORDR_OA_BRANDPACK OOB ON OOB.OA_ID = OOA.OA_ID LEFT OUTER JOIN
     SPPB_BRANDPACK SB ON SB.OA_BRANDPACK_ID = OOB.OA_BRANDPACK_ID LEFT OUTER JOIN SPPB_HEADER SH ON SB.SPPB_NO = SH.SPPB_NO
     WHERE OOB.OA_ID = @OA_ID AND SB.SPPB_NO IS NOT NULL;
END
ELSE
BEGIN
    SELECT TOP 1 OOA.OA_DATE,ISNULL(SB.SPPB_NO,'Undefined')AS SPPB_NO,ISNULL(SH.SPPB_DATE,GETDATE()) AS SPPB_DATE
    FROM ORDR_ORDER_ACCEPTANCE OOA INNER JOIN ORDR_OA_BRANDPACK OOB ON OOB.OA_ID = OOA.OA_ID LEFT OUTER JOIN
    SPPB_BRANDPACK SB ON SB.OA_BRANDPACK_ID = OOB.OA_BRANDPACK_ID LEFT OUTER JOIN SPPB_HEADER SH ON SB.SPPB_NO = SH.SPPB_NO
    WHERE OOB.OA_ID = @OA_ID;
END
GO
--exec Usp_Getrow_By_OA_Ref_No
--@OA_ID = '013/XII/PO-NI/CIJ/2012-00014905'
-------------------------------------------------------------------------------------------
----------------------BRANDPACK UNTUK DI BINDINGKAN DI GRDGONSEQUENCE COLUMNS BRANDPACK_NAME--
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Create_View_BrandPack_By_OA_Ref_No' AND TYPE = 'P')
DROP PROCEDURE Usp_Create_View_BrandPack_By_OA_Ref_No
GO
CREATE PROCEDURE Usp_Create_View_BrandPack_By_OA_Ref_No
@OA_REF_NO VARCHAR(32)
AS
SET NOCOUNT ON;
SELECT OPB.BRANDPACK_ID,BB.BRANDPACK_NAME FROM ORDR_PO_BRANDPACK OPB INNER JOIN ORDR_OA_BRANDPACK OOB
ON OOB.PO_BRANDPACK_ID = OPB.PO_BRANDPACK_ID INNER JOIN BRND_BRANDPACK BB ON OPB.BRANDPACK_ID = BB.BRANDPACK_ID 
WHERE OOB.OA_ID = @OA_REF_NO; 
GO
--EXEC Usp_Create_View_BrandPack_By_OA_Ref_No
--@OA_REF_NO = '013/XII/PO-NI/CIJ/2012-00014905'

-------------------------PROCEDURE UNTUK MEMBATASI SPPB_GON_QTY---------------------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Get_Gon_Sequence_NO' AND TYPE = 'P')
DROP PROCEDURE Usp_Get_Gon_Sequence_NO 
GO
CREATE PROCEDURE Usp_Get_Gon_Sequence_NO
@SPPB_NO VARCHAR(15),
@GON_SEQUENCE INT OUTPUT
AS
IF(SELECT ISNULL(SUM(GON_6_QTY),0) FROM SPPB_BRANDPACK WHERE SPPB_NO = @SPPB_NO) > 0
    BEGIN
	SET @GON_SEQUENCE = 6
    END
ELSE IF(SELECT ISNULL(SUM(GON_5_QTY),0) FROM SPPB_BRANDPACK WHERE SPPB_NO = @SPPB_NO) > 0
    BEGIN
	SET @GON_SEQUENCE = 5
    END	
ELSE IF (SELECT ISNULL(SUM(GON_4_QTY),0) FROM SPPB_BRANDPACK WHERE SPPB_NO = @SPPB_NO) > 0
    BEGIN
	SET @GON_SEQUENCE = 4
    END
ELSE IF (SELECT ISNULL(SUM(GON_3_QTY),0) FROM SPPB_BRANDPACK WHERE SPPB_NO = @SPPB_NO) > 0
    BEGIN
	SET @GON_SEQUENCE = 3
    END
ELSE IF (SELECT ISNULL(SUM(GON_2_QTY),0) FROM SPPB_BRANDPACK WHERE SPPB_NO = @SPPB_NO) > 0
    BEGIN
	SET @GON_SEQUENCE = 2
    END
ELSE IF (SELECT ISNULL(SUM(GON_1_QTY),0) FROM SPPB_BRANDPACK WHERE SPPB_NO = @SPPB_NO) > 0
    BEGIN
	SET @GON_SEQUENCE = 1
    END
ELSE 
   BEGIN
	SET @GON_SEQUENCE = 0
   END
GO
-------------------------------------------------------------------------------------------
---------------PROCEDURE UNTUK MENGECEK EXISTING PO_BRANDPACK-----------------------------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Check_Exixting_SPPB_BrandPack' AND TYPE = 'P')
DROP PROCEDURE Usp_Check_Exixting_SPPB_BrandPack
GO
CREATE PROCEDURE Usp_Check_Exixting_SPPB_BrandPack
@SPPB_BRANDPACK_ID VARCHAR(90)
AS
IF EXISTS(SELECT SPPB_BRANDPACK_ID FROM SPPB_BRANDPACK WHERE SPPB_BRANDPACK_ID = @SPPB_BRANDPACK_ID)
   BEGIN
	RAISERROR('Data has existed in DataBase',16,1)
	RETURN (1)
   END	
RETURN(0)
GO
---------------------------------------------------------------------------------------------
---------------PROCEDURE UNTUK MENGECEK REFERENCE SPPB BRANDPACK----------------------------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Check_Reference_SPPB_BrandPack' AND TYPE = 'P')
DROP PROCEDURE Usp_Check_Reference_SPPB_BrandPack
GO
CREATE PROCEDURE Usp_Check_Reference_SPPB_BrandPack
@OA_BRANDPACK_ID VARCHAR(75)
AS
IF EXISTS(SELECT OA_BRANDPACK_ID FROM OTP_DETAIL WHERE OA_BRANDPACK_ID = @OA_BRANDPACK_ID)
   	RETURN(1)
ELSE IF EXISTS(SELECT OA_BRANDPACK_ID FROM DO_TP_DETAIL WHERE OA_BRANDPACK_ID = @OA_BRANDPACK_ID)
   RETURN(2)
ELSE
RETURN(0)
GO
------------------------------------------------------------------------------------------------------
---------------------PROCEDURE UNTUK MENGAMBIL TOTAL OA_QTY ------------------------------------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Get_Total_OA_Qty' AND TYPE = 'P')
DROP PROCEDURE Usp_Get_Total_OA_Qty
GO
--sia sia deh gw dah rubah cape-cape ,procedure nya mesti di balikin lagi
CREATE PROCEDURE Usp_Get_Total_OA_Qty
@OA_BRANDPACK_ID VARCHAR(75),
@IsCheking  BIT,@REMARK VARCHAR(150) OUTPUT,
@ResultQty DECIMAL(18,3) OUTPUT
AS
DECLARE @V_BRANDPACK_ID VARCHAR(14),@V_PRICE_PO DECIMAL(16,2),@V_PO_REF_NO VARCHAR(30),
@V_PO_DATE SMALLDATETIME,@V_DISTRIBUTOR_ID VARCHAR(10),@V_PLANTATION_NAME VARCHAR(100),@V_DESCRIPTIONS VARCHAR(150);
SELECT TOP 1 @V_BRANDPACK_ID = BRANDPACK_ID,@V_PRICE_PO = PO_PRICE_PERQTY,@V_PO_REF_NO = PO_REF_NO,
@V_DESCRIPTIONS = DESCRIPTIONS FROM ORDR_PO_BRANDPACK 
WHERE PO_BRANDPACK_ID = (SELECT TOP 1 PO_BRANDPACK_ID FROM ORDR_OA_BRANDPACK WHERE OA_BRANDPACK_ID = @OA_BRANDPACK_ID)
AND PO_ORIGINAL_QTY > 0;

SELECT @V_PO_DATE = PO_REF_DATE, @V_DISTRIBUTOR_ID = DISTRIBUTOR_ID FROM ORDR_PURCHASE_ORDER WHERE PO_REF_NO = @V_PO_REF_NO ;

IF @V_DESCRIPTIONS IS NULL
   BEGIN
	IF EXISTS(SELECT TOP 1 PRICE FROM DIST_PLANT_PRICE WHERE PRICE = @V_PRICE_PO AND DISTRIBUTOR_ID = @V_DISTRIBUTOR_ID AND BRANDPACK_ID = @V_BRANDPACK_ID
	          AND START_DATE <= @V_PO_DATE ORDER BY START_DATE DESC)
	BEGIN 
		SELECT PLANTATION_ID FROM DIST_PLANT_PRICE WHERE PRICE = @V_PRICE_PO
		 AND DISTRIBUTOR_ID = @V_DISTRIBUTOR_ID AND BRANDPACK_ID = @V_BRANDPACK_ID
	        AND DATEDIFF(DAY,START_DATE,@V_PO_DATE) <= 31  ORDER BY START_DATE DESC;
		IF(@@ROWCOUNT > 1)
		BEGIN SET @V_PLANTATION_NAME = ''; END
		ELSE
		BEGIN
		 SET @V_PLANTATION_NAME = (SELECT PLANTATION_NAME FROM PLANTATION 
		 WHERE PLANTATION_ID = (SELECT TOP 1 PLANTATION_ID FROM DIST_PLANT_PRICE WHERE PRICE = @V_PRICE_PO
		 AND DISTRIBUTOR_ID = @V_DISTRIBUTOR_ID AND BRANDPACK_ID = @V_BRANDPACK_ID ORDER BY START_DATE DESC));
		END 
             SELECT @REMARK = 'PRICE FROM PLANTATION  ' + @V_PLANTATION_NAME ; 
        END
	ELSE IF EXISTS(SELECT TOP 1 PRICE FROM BRND_PRICE_HISTORY WHERE PRICE = @V_PRICE_PO AND BRANDPACK_ID = @V_BRANDPACK_ID 
               AND START_DATE <= @V_PO_DATE ORDER BY START_DATE DESC)
	BEGIN SELECT @REMARK = 'PRICE FROM FREE MARKET ' ; END
   END
ELSE
BEGIN SELECT @REMARK = '' +  @V_DESCRIPTIONS ; END	
IF (@IsCheking = 1)
  BEGIN
     SELECT @ResultQty = CAST((SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC WHERE OA_BRANDPACK_ID = @OA_BRANDPACK_ID) AS DECIMAL(18,3))
     + CAST((SELECT QTY_EVEN FROM ORDR_OA_BRANDPACK WHERE OA_BRANDPACK_ID = @OA_BRANDPACK_ID)AS DECIMAL(18,3));
  END
ELSE
  BEGIN
   SELECT @ResultQty = CAST((SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC WHERE OA_BRANDPACK_ID = @OA_BRANDPACK_ID) AS DECIMAL(18,3))
      + CAST((SELECT QTY_EVEN FROM ORDR_OA_BRANDPACK WHERE OA_BRANDPACK_ID = @OA_BRANDPACK_ID)AS DECIMAL(18,3));
  END
GO

----------------------------------------------------------------------------------------------------
-------------------PROCEDURE UNTUK MEMVIEW SPPB DI FRM THIRDPARTY-----------------------------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Create_View_SPPB_NO_ThirdParty_By_Distributor_ID' AND TYPE = 'P')
DROP PROCEDURE Usp_Create_View_SPPB_NO_ThirdParty_By_Distributor_ID
GO
CREATE PROCEDURE Usp_Create_View_SPPB_NO_ThirdParty_By_Distributor_ID
@DISTRIBUTOR_ID VARCHAR(10)
AS
SET NOCOUNT ON;SELECT TOP 100 SH.SPPB_NO,SH.SPPB_DATE FROM SPPB_HEADER SH WHERE PO_REF_NO IN(
SELECT PO_REF_NO FROM ORDR_PURCHASE_ORDER WHERE DISTRIBUTOR_ID = @DISTRIBUTOR_ID 
AND YEAR(PO_REF_DATE) >= YEAR(GETDATE())-1) 
ORDER BY RIGHT(SH.SPPB_NO,6) DESC
GO

-----------------------------------------------------------------------------------
----------PROCEDURE UNTUK SEARCH SPPB THIRD PARTY-------------------------------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME  = 'Usp_Search_ThirdParty_SPBB_NO' AND TYPE = 'P')
DROP PROCEDURE Usp_Search_ThirdParty_SPBB_NO
GO
CREATE PROCEDURE Usp_Search_ThirdParty_SPBB_NO
@SPPB_NO VARCHAR(15),
@DISTRIBUTOR_ID VARCHAR(10)
AS
SET NOCOUNT ON;
SELECT TOP 100 SH.SPPB_NO,SH.SPPB_DATE
FROM SPPB_HEADER SH WHERE PO_REF_NO IN(
SELECT PO_REF_NO FROM ORDR_PURCHASE_ORDER WHERE DISTRIBUTOR_ID = @DISTRIBUTOR_ID 
AND YEAR(PO_REF_DATE) >= YEAR(GETDATE()) -1)
AND SH.SPPB_NO LIKE + '%' + @SPPB_NO + '%'
ORDER BY RIGHT(SH.SPPB_NO,6) DESC
GO
--EXEC Usp_Search_SPPB_NO @DISTRIBUTOR_ID = 'AGR014IDR',@SPPB_NO = 'O'
---------------------------------------------------------------------------------------------------
---------------------PROCEDURE UNTUK MENGAMBIL DATA BERDASARKAN OTP_NO  UNTUK ENTRY DATA OTP_THIRD_PARTY
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Get_Data_PO_Third_Party' AND TYPE = 'P')
DROP PROCEDURE Usp_Get_Data_PO_Third_Party
GO
CREATE PROCEDURE Usp_Get_Data_PO_Third_Party
@OTP_NO VARCHAR(15)
AS
SELECT OPB.BRANDPACK_ID,OD.OTP_BRANDPACK,OD.OTP_NO,OD.OTP_NO, OD.OA_BRANDPACK_ID,OD.OTP_QTY,
OD.CREATE_BY,OD.CREATE_DATE,OD.MODIFY_BY,OD.MODIFY_DATE
FROM OTP_DETAIL OD INNER JOIN SPPB_BRANDPACK SB ON SB.OA_BRANDPACK_ID = OD.OA_BRANDPACK_ID
INNER JOIN ORDR_OA_BRANDPACK OOB ON OOB.OA_BRANDPACK_ID = SB.OA_BRANDPACK_ID
INNER JOIN ORDR_PO_BRANDPACK OPB ON OPB.PO_BRANDPACK_ID = OOB.PO_BRANDPACK_ID
WHERE OD.OTP_NO = @OTP_NO
GO
--EXEC Usp_Get_Data_PO_Third_Party @OTP_NO = 'PO10061500'
---------------------------------------------------------------------------------------------------
-----------------------PROCEDURE UNTUK MENGAMBIL DATA DO_THIRD_PARTI BERDASARKAN OTP_NO----------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Get_Data_DO_Third_Party' AND TYPE = 'P')
DROP PROCEDURE Usp_Get_Data_DO_Third_Party
GO
CREATE PROCEDURE Usp_Get_Data_DO_Third_Party
@OTP_NO VARCHAR(15)
AS
SELECT OPB.BRANDPACK_ID,DTD.DO_TP_BRANDPACK,DTD.DO_TP_NO,DTD.OA_BRANDPACK_ID,
DTD.DO_TP_QTY,DTD.CREATE_BY,DTD.CREATE_DATE,DTD.MODIFY_BY,DTD.MODIFY_DATE
FROM DO_TP_DETAIL DTD INNER JOIN OTP_DETAIL OD ON OD.OA_BRANDPACK_ID = DTD.OA_BRANDPACK_ID
INNER JOIN SPPB_BRANDPACK SB ON SB.OA_BRANDPACK_ID = OD.OA_BRANDPACK_ID
INNER JOIN ORDR_OA_BRANDPACK OOB ON SB.OA_BRANDPACK_ID = OOB.OA_BRANDPACK_ID
INNER JOIN ORDR_PO_BRANDPACK OPB ON OPB.PO_BRANDPACK_ID = OOB.PO_BRANDPACK_ID
WHERE OD.OTP_NO = @OTP_NO
GO
--EXEC Usp_Get_Data_DO_Third_Party @OTP_NO = 'PO10061500'
---------------------------------------------------------------------------------------
---------------------------PROCEDURE UNTUK INFLATE DATE DI MCBSPPB-----------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME  = 'Usp_Get_Item_Description_SPPB_NO' AND TYPE = 'P')
DROP PROCEDURE Usp_Get_Item_Description_SPPB_NO
GO
CREATE PROCEDURE Usp_Get_Item_Description_SPPB_NO
@SPPB_NO VARCHAR(15),
@O_OTP_NO VARCHAR(15)OUTPUT,@O_OTP_DATE DATETIME OUTPUT,
@O_DO_TP_NO VARCHAR(15) OUTPUT,
@O_DO_TP_DATE DATETIME OUTPUT
AS
--DECLARE @V_PO_REF_NO VARCHAR(25)
BEGIN
	--SET @V_PO_REF_NO = (SELECT PO_REF_NO FROM ORDR_ORDER_ACCEPTANCE WHERE OA_ID = @OA_REF_NO)
	SET @O_OTP_NO = (SELECT ISNULL(OTP_NO,'') FROM ORDR_OTP_HEADER WHERE SPPB_NO = @SPPB_NO)
	SET @O_OTP_DATE = (SELECT OTP_DATE FROM ORDR_OTP_HEADER WHERE SPPB_NO = @SPPB_NO)
	SET @O_DO_TP_NO = (SELECT ISNULL(DO_TP_NO,'') FROM DO_TP_HEADER WHERE OTP_NO = @O_OTP_NO)
	SET @O_DO_TP_DATE = (SELECT DO_TP_DATE FROM DO_TP_HEADER WHERE OTP_NO = @O_OTP_NO)
END
GO
-----------------------------------------------------------------------------------------------
--------------PROCEDURE UNTUK MENGECEK EXISTS/ TIDAKNYA OTP_BRANDPACK-------------------------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Check_Existing_OTP_BRANDPACK' AND TYPE = 'P')
DROP PROCEDURE Usp_Check_Existing_OTP_BRANDPACK 
GO
CREATE PROCEDURE Usp_Check_Existing_OTP_BRANDPACK
@OTP_BRANDPACK VARCHAR(90)
AS
IF EXISTS(SELECT OTP_BRANDPACK FROM OTP_DETAIL WHERE OTP_BRANDPACK = @OTP_BRANDPACK)
   RETURN(1)
ELSE
   RETURN(0)
GO
-----------------------PROCEDURE UNTUK MENGECEK EXISTS/TIDAKNYA DO_TP_BRANDPACK-------------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Check_Existing_DO_TP_BRANDPACK' AND TYPE  ='P')
DROP PROCEDURE Usp_Check_Existing_DO_TP_BRANDPACK
GO
CREATE PROCEDURE Usp_Check_Existing_DO_TP_BRANDPACK
@DO_TP_BRANDPACK VARCHAR(90)
AS
IF EXISTS(SELECT DO_TP_BRANDPACK FROM DO_TP_DETAIL WHERE DO_TP_BRANDPACK = @DO_TP_BRANDPACK)
	RETURN(1)
ELSE
    RETURN(0)
GO

--DECLARE @V_RETVAL INT
--SET @V_RETVAL = Usp_Check_Existing_DO_TP_BRANDPACK
----------------------------------------------------------------------------------------------
-------------PROCEDURE UNTUK MENGISI COLUMN BRANDPACK DI GRD OTP AND DRP DO DI FORM THIRD_PARTY---
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Get_BrandPack_ID_By_SPPB' AND TYPE = 'P')
DROP PROCEDURE Usp_Get_BrandPack_ID_By_SPPB
GO
CREATE PROCEDURE Usp_Get_BrandPack_ID_By_SPPB
@SPPB_NO VARCHAR(15)
AS
SELECT OPB.BRANDPACK_ID,BB.BRANDPACK_NAME FROM ORDR_PO_BRANDPACK OPB INNER JOIN
BRND_BRANDPACK BB ON OPB.BRANDPACK_ID = BB.BRANDPACK_ID INNER JOIN 
ORDR_OA_BRANDPACK OOB ON OOB.PO_BRANDPACK_ID = OPB.PO_BRANDPACK_ID
INNER JOIN SPPB_BRANDPACK SB ON SB.OA_BRANDPACK_ID = OOB.OA_BRANDPACK_ID
WHERE SB.SPPB_NO = @SPPB_NO
GO
 ------------------------------------------------------------------------------------------------
------------------PROCEDURE UNTUK MEMVIEW DISTRIBUTOR SPPB DI MCB DISTRIBUTOR FORM SPPB
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Create_View_Distributor_SPPB' AND TYPE = 'P')
DROP PROCEDURE Usp_Create_View_Distributor_SPPB
GO
CREATE PROCEDURE Usp_Create_View_Distributor_SPPB
AS
SET NOCOUNT ON;
SELECT DR.DISTRIBUTOR_ID,DR.DISTRIBUTOR_NAME FROM DIST_DISTRIBUTOR DR 
WHERE EXISTS(SELECT DISTRIBUTOR_ID FROM ORDR_PURCHASE_ORDER PO
INNER JOIN SPPB_HEADER SB ON SB.PO_REF_NO = PO.PO_REF_NO WHERE PO.DISTRIBUTOR_ID = DR.DISTRIBUTOR_ID);

--WHERE EXISTS(SELECT PO.DISTRIBUTOR_ID FROM ORDR_PURCHASE_ORDER PO
--WHERE EXISTS(SELECT PO_REF_NO FROM SPPB_HEADER WHERE PO_REF_NO = PO.PO_REF_NO)
--AND PO.DISTRIBUTOR_ID = DR.DISTRIBUTOR_ID)
GO 
--exec Usp_Create_View_Distributor_SPPB
--select * from ordr_oa_brandpack where oa_brandpack_id = '(020)19/02/09-1525(020)19/02/0900601001LD'
---------------------------------------------------------------------------------------------------
-------------------------PROCEDURE UNTUK MENGAMBIL GON_DATE BERDASARKAN GS_NO---------------------
----PROCEDURE INI DI PAKAI UNTUK TRAP MINDATE DTP_GON_DATE DI FORM SPP_ENTRY---------------------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Get_Gon_Date_By_GS_No' AND TYPE = 'P')
DROP PROCEDURE Usp_Get_Gon_Date_By_GS_No
GO
CREATE PROCEDURE Usp_Get_Gon_Date_By_GS_No
@GS_NO INT,
@SPPB_NO VARCHAR(15)
AS
SELECT RESULT =  
 CASE @GS_NO
        WHEN 1 THEN
             (SELECT SPPB_DATE  FROM SPPB_HEADER WHERE SPPB_NO = @SPPB_NO )
        WHEN 2 THEN
	     (SELECT TOP 1 GON_1_DATE FROM SPPB_BRANDPACK WHERE SPPB_NO = @SPPB_NO AND GON_1_DATE IS NOT NULL)
	WHEN 3 THEN		
	     (SELECT TOP 1 GON_2_DATE FROM SPPB_BRANDPACK WHERE SPPB_NO = @SPPB_NO AND GON_2_DATE IS NOT NULL)
	WHEN 4 THEN
	     (SELECT TOP 1 GON_3_DATE FROM SPPB_BRANDPACK WHERE SPPB_NO = @SPPB_NO AND GON_3_DATE IS NOT NULL)
	WHEN 5 THEN 
	     (SELECT TOP 1 GON_4_DATE FROM SPPB_BRANDPACK WHERE SPPB_NO =@SPPB_NO AND GON_4_DATE IS NOT NULL)
	WHEN 6 THEN
	     (SELECT TOP 1 GON_5_DATE FROM SPPB_BRANDPACK WHERE SPPB_NO = @SPPB_NO AND GON_5_DATE IS NOT NULL)
 END	
GO
----------------------------------------------------------------------------------------------- 
--EXEC Usp_Get_Gon_Date_By_GS_No @SPPB_NO = '10-11-003649',@GS_NO = 2

--SELECT * FROM SPPB_BRANDPACK WHERE SPPB_NO = '10-11-003649'

--SELECT TOP 1 GON_1_DATE FROM SPPB_BRANDPACK WHERE SPPB_NO = '10-11-003649' AND GON_1_DATE IS NOT NULL

---------------------------PROCEEDURE UNTUK MENGAMBIL GON_DATE & NO BERDASARKAN GS_NO------
---DIPAKAI BILA CMBGS_NO DI PILIH DIFORM SPPB ENTRY---------------------------------------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME  = 'Usp_Get_GON_No_And_Date'AND TYPE = 'P')
DROP PROCEDURE Usp_Get_GON_No_And_Date
GO
CREATE PROCEDURE Usp_Get_GON_No_And_Date
@GS_NO INT,
@SPPB_NO VARCHAR(15)
AS
SELECT GON_NO = 
      CASE @GS_NO
	   WHEN 1 THEN
		(SELECT TOP 1 GON_1_NO FROM SPPB_BRANDPACK WHERE SPPB_NO = @SPPB_NO AND GON_1_NO IS NOT NULL)
      	   WHEN 2 THEN	
		(SELECT TOP 1 GON_2_NO FROM SPPB_BRANDPACK WHERE SPPB_NO = @SPPB_NO AND GON_2_NO IS NOT NULL )
	   WHEN 3 THEN 
		(SELECT TOP 1 GON_3_NO FROM SPPB_BRANDPACK WHERE SPPB_NO = @SPPB_NO AND GON_3_NO IS NOT NULL)
	   WHEN 4 THEN
		(SELECT TOP 1 GON_4_NO FROM SPPB_BRANDPACK WHERE SPPB_NO = @SPPB_NO AND GON_4_NO IS NOT NULL)
	   WHEN 5 THEN
		(SELECT TOP 1 GON_5_NO FROM SPPB_BRANDPACK WHERE SPPB_NO = @SPPB_NO AND GON_5_NO IS NOT NULL)
	   WHEN 6 THEN
		(SELECT TOP 1 GON_6_NO FROM SPPB_BRANDPACK WHERE SPPB_NO = @SPPB_NO AND GON_6_NO IS NOT NULL)
      END,
        GON_DATE = 
	CASE @GS_NO
	     WHEN 1 THEN
		(SELECT TOP 1 GON_1_DATE FROM SPPB_BRANDPACK WHERE SPPB_NO = @SPPB_NO AND GON_1_DATE IS NOT NULL)
	     WHEN 2 THEN
		(SELECT TOP 1 GON_2_DATE FROM SPPB_BRANDPACK WHERE SPPB_NO = @SPPB_NO AND GON_2_DATE IS NOT NULL)
	     WHEN 3 THEN
		(SELECT TOP 1 GON_3_DATE FROM SPPB_BRANDPACK WHERE SPPB_NO = @SPPB_NO AND GON_3_DATE IS NOT NULL)
	     WHEN 4 THEN
		(SELECT TOP 1 GON_4_DATE FROM SPPB_BRANDPACK WHERE SPPB_NO = @SPPB_NO AND GON_4_DATE IS NOT NULL)
	     WHEN 5 THEN
   		(SELECT TOP 1 GON_5_DATE FROM SPPB_BRANDPACK WHERE SPPB_NO = @SPPB_NO AND GON_5_DATE IS NOT NULL)
	     WHEN 6 THEN
		(SELECT TOP 1 GON_6_DATE FROM SPPB_BRANDPACK WHERE SPPB_NO = @SPPB_NO AND GON_6_DATE IS NOT NULL)
	END
GO
-----------------------------------------------------------------------------------------
----------PROCEDURE UNTUK MEMVIEW DISTRIBUTOR YANG UDAH PO_SPPBB NYA SUDAH DI REGISTER
----------DI PAKAI DI CBDISTRIBUTOR FORM THRID PARTY--------------------------------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Create_View_Distributor_PO_DO_ThirdParty' AND TYPE ='P')
DROP PROCEDURE Usp_Create_View_Distributor_PO_DO_ThirdParty
GO
CREATE PROCEDURE Usp_Create_View_Distributor_PO_DO_ThirdParty
AS
SELECT DISTINCT(OPO.DISTRIBUTOR_ID),DR.DISTRIBUTOR_NAME FROM ORDR_PURCHASE_ORDER OPO INNER JOIN
DIST_DISTRIBUTOR DR ON OPO.DISTRIBUTOR_ID = DR.DISTRIBUTOR_ID 
INNER JOIN SPPB_HEADER SH ON OPO.PO_REF_NO = SH.PO_REF_NO
WHERE YEAR(OPO.PO_REF_DATE) >= YEAR(GETDATE()) -1
GO

-----------------------procedure untuk mengcek sppb_qty,di pkai di grdotp form thirdparty--
---------pada saat update dan insert-------------------------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Get_SPPB_Qty' AND TYPE = 'P')
DROP PROCEDURE Usp_Get_SPPB_Qty
GO
CREATE PROCEDURE Usp_Get_SPPB_Qty
@SPPB_BRANDPACK_ID VARCHAR(90)
AS
DECLARE @V_SPPB_QTY DECIMAL(18,3),@V_LEFT_OTP_QTY DECIMAL(18,3),@V_OA_BRANDPACK_ID VARCHAR(70)
SET @V_OA_BRANDPACK_ID =(SELECT OA_BRANDPACK_ID FROM SPPB_BRANDPACK WHERE SPPB_BRANDPACK_ID =@SPPB_BRANDPACK_ID)
SET @V_SPPB_QTY = CAST((SELECT ISNULL(SPPB_QTY,0) FROM SPPB_BRANDPACK WHERE SPPB_BRANDPACK_ID = @SPPB_BRANDPACK_ID)AS DECIMAL(18,3))
SET @V_LEFT_OTP_QTY = CAST((SELECT ISNULL(SUM(OTP_QTY),0) FROM OTP_DETAIL WHERE OA_BRANDPACK_ID = @V_OA_BRANDPACK_ID) AS DECIMAL(18,3))
SELECT (@V_SPPB_QTY - @V_LEFT_OTP_QTY) AS SPPB_QTY 

GO 


--EXEC Usp_Get_SPPB_Qty @SPPB_BRANDPACK_ID = '09.10-001588A/24/MK/NI/GOA/2010-4655A/24/MK/NI/GOA/201000602020LKH'
-------------------PROCEDURE UNTUK MENGECEK OTP_QTY ,DIPAKAI DI GRD_DO_TP QTY DI FORM THIRDPARTY
-------------DI GUNAKAN PADA SAAT DO_TP_QTY DI ISI / UPDATE
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Get_OTP_Qty' AND TYPE = 'P')
DROP PROCEDURE Usp_Get_OTP_Qty
GO
CREATE PROCEDURE Usp_Get_OTP_Qty
@OTP_BRANDPACK VARCHAR(90)
AS
SELECT ISNULL(OTP_QTY,0)AS OTP_QTY FROM OTP_DETAIL WHERE OTP_BRANDPACK = @OTP_BRANDPACK
GO
-------------------------procedure untuk memview distributor di mcndistributor form sppb---
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Create_View_Distributor_OA' AND TYPE = 'P')
DROP PROCEDURE Usp_Create_View_Distributor_OA
GO
CREATE PROCEDURE Usp_Create_View_Distributor_OA
@ISREGISTERED BIT
AS 
SET NOCOUNT ON;
IF(@ISREGISTERED = 0)
   BEGIN
	SELECT DR.DISTRIBUTOR_ID,DR.DISTRIBUTOR_NAME FROM DIST_DISTRIBUTOR DR 
	WHERE EXISTS (SELECT OPO.DISTRIBUTOR_ID FROM ORDR_PURCHASE_ORDER OPO
		      WHERE OPO.DISTRIBUTOR_ID = DR.DISTRIBUTOR_ID AND YEAR(OPO.PO_REF_DATE) >= YEAR(GETDATE()) -1)
    END
ELSE
   BEGIN
SELECT DR.DISTRIBUTOR_ID,DR.DISTRIBUTOR_NAME FROM DIST_DISTRIBUTOR DR 
	WHERE EXISTS (SELECT OPO.DISTRIBUTOR_ID FROM ORDR_PURCHASE_ORDER OPO
		      WHERE EXISTS(SELECT PO_REF_NO FROM SPPB_HEADER WHERE PO_REF_NO = OPO.PO_REF_NO)
	AND YEAR(OPO.PO_REF_DATE) >= YEAR(GETDATE()) -1
        AND OPO.DISTRIBUTOR_ID = DR.DISTRIBUTOR_ID)  
   END	
GO

--EXEC Usp_Create_View_Distributor_OA
--@ISREGISTERED = 1


--EXEC Usp_Check_Existing_DO_TP_BRANDPACK @DO_TP_BRANDPACK = 'werw001/AJ/PLG/I/2008-0021001/AJ/PLG/I/200800064001LD'

--------------PROCEDURE UNTUK MENGECEK KEBERADAAN OTP_NO------------------------------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Check_OTP_NO' AND TYPE = 'P')

DROP PROCEDURE Usp_Check_OTP_NO
GO
CREATE PROCEDURE Usp_Check_OTP_NO
@OTP_NO VARCHAR(15)
AS
SELECT COUNT(OTP_NO) FROM ORDR_OTP_HEADER WHERE OTP_NO = @OTP_NO
GO
-------------------------------------------------------------------------------------------
---------------------------PROCEDURE UNTUK MENGECEK KEBERADAAN DO_TP_NO------------------
IF EXISTS(SELECT NAME FROM  DBO.SYSOBJECTS WHERE NAME = 'Usp_Check_DO_TP_NO' AND TYPE = 'P')
DROP PROCEDURE Usp_Check_DO_TP_NO
GO
CREATE PROCEDURE Usp_Check_DO_TP_NO
@DO_TP_NO VARCHAR(15)
AS
SELECT COUNT(DO_TP_NO) FROM DO_TP_HEADER WHERE DO_TP_NO = @DO_TP_NO
GO


--SELECT *,[PO_ORIGINAL_QTY] * [PO_PRICE_PERQTY] AS TOTAL FROM ORDR_PO_BRANDPACK WHERE PO_REF_NO = ''