---PROCEDURE UNTUK MEMVIEW SHIP TO TERRITORY AREA DISTRIBUTOR UNTUK DI PAKE DI grdShipto--
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Create_View_Distributor_Territory' AND TYPE= 'P')
DROP PROCEDURE Usp_Create_View_Distributor_Territory
GO
CREATE PROCEDURE Usp_Create_View_Distributor_Territory
AS
BEGIN
	SELECT DD.DISTRIBUTOR_NAME,DST.DISTRIBUTOR_ID,DST.DIST_SHIP_TO_ID,DST.TERRITORY_ID,
	TER.TERRITORY_AREA,TERRITORY_DESCRIPTION FROM DIST_DISTRIBUTOR DD INNER JOIN DIST_SHIP_TO DST
	ON DD.DISTRIBUTOR_ID = DST.DISTRIBUTOR_ID INNER  JOIN TERRITORY TER
	ON DST.TERRITORY_ID = TER.TERRITORY_ID
	
END
GO 
-------------------------------------------------------------------------------------------
--PROCEDURE UNTUK MEMBUAT VIEW TERRITORY_AREA ---
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Select_Territory_Area' AND TYPE = 'P')
 DROP PROCEDURE Usp_Select_Territory_Area
GO
CREATE PROCEDURE Usp_Select_Territory_Area
AS
SELECT TERRITORY_ID,TERRITORY_AREA,TERRITORY_DESCRIPTION FROM TERRITORY
ORDER BY TERRITORY_ID DESC
GO
------------------------------------------------------------------------------------
--PROCEDURE UNTUK MEMVIEW DISTRIBUTOR_SHIPTO BERDASARKAN DISTRIBUTOR_ID--
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME  = 'Usp_Select_Territory_Area_By_Distributor_ID' AND TYPE = 'P')
DROP PROCEDURE Usp_Select_Territory_Area_By_Distributor_ID
GO
CREATE PROCEDURE Usp_Select_Territory_Area_By_Distributor_ID
@DISTRIBUTOR_ID VARCHAR(10)
AS
SELECT DST.TERRITORY_ID,TER.TERRITORY_AREA FROM DIST_SHIP_TO DST INNER JOIN TERRITORY TER
ON DST.TERRITORY_ID = TER.TERRITORY_ID
WHERE DST.DISTRIBUTOR_ID = @DISTRIBUTOR_ID
GO
-------------------------------------------------------------------------------------------
---------------PROCEDURE UNTUK MENAMPILKAN TERRITORY YANG BELUM DI RESERVED OLEH DISTRIBUTOR
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Select_Territory_UnReserved_by_Distributor' AND TYPE = 'P')
DROP PROCEDURE Usp_Select_Territory_UnReserved_by_Distributor
GO
CREATE PROCEDURE Usp_Select_Territory_UnReserved_by_Distributor
@DISTRIBUTOR_ID VARCHAR(10)
AS
SELECT TERRITORY_ID,TERRITORY_AREA FROM TERRITORY WHERE TERRITORY_ID NOT IN
(SELECT TERRITORY_ID FROM DIST_SHIP_TO WHERE DISTRIBUTOR_ID = @DISTRIBUTOR_ID)
GO

----PROCEDURE UNTUK MENGINSERT DATA KE TERRTIORY_AREA--------------------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Insert_Territory_Area' AND TYPE = 'P')
DROP PROCEDURE Usp_Insert_Territory_Area
GO
CREATE PROCEDURE Usp_Insert_Territory_Area
@TERRITORY_ID VARCHAR(10),
@TERRITORY_AREA VARCHAR(30),
@TERRITORY_DESCRIPTION VARCHAR(150),
@CREATE_BY VARCHAR(30)
AS
--CHECK DUPLICATE VALUE
IF (SELECT COUNT(TERRITORY_ID) FROM TERRITORY WHERE TERRITORY_ID = @TERRITORY_ID) > 0
    BEGIN
       RAISERROR('Can not insert Duplicate ID',16,1)  
    END
ELSE
    BEGIN
	INSERT INTO TERRITORY(TERRITORY_ID,TERRITORY_AREA,TERRITORY_DESCRIPTION,CREATE_BY,CREATE_DATE)
	VALUES(@TERRITORY_ID,@TERRITORY_AREA,@TERRITORY_DESCRIPTION,@CREATE_BY,GETDATE())
    END
GO
-------------------------------------------------------------------------------------------------
---------PROCEDURE UNTUK MENGUPDATE TERITORY AREA-------------------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Update_Territory_Area' AND TYPE = 'P')
DROP PROCEDURE Usp_Update_Territory_Area
GO
CREATE PROCEDURE Usp_Update_Territory_Area
@TERRITORY_ID VARCHAR(10),
@TERRITORY_AREA VARCHAR(30),
@TERRITORY_DESCRIPTION VARCHAR(150),
@MODIFY_BY VARCHAR(30)
AS
--CHECK REFERENCED DATA
  
      BEGIN
	UPDATE TERRITORY SET TERRITORY_AREA = @TERRITORY_AREA,TERRITORY_DESCRIPTION = @TERRITORY_DESCRIPTION
	,MODIFY_BY = @MODIFY_BY,MODIFY_DATE = GETDATE() WHERE TERRITORY_ID = @TERRITORY_ID
      END
 
GO
---------------------------------------------------------------------------
---PROCEDURE UNTUK MENDELETE TERRITORY_AREA ------------------------------------------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Delete_Territory_Area' AND TYPE = 'P')
DROP PROCEDURE Usp_Delete_Territory_Area
GO
CREATE PROCEDURE Usp_Delete_Territory_Area
@TERRITORY_ID VARCHAR(10)
AS
IF (SELECT COUNT(TERRITORY_ID) FROM DIST_SHIP_TO WHERE TERRITORY_ID  = @TERRITORY_ID) > 0
      BEGIN
	RAISERROR('Data Can not be deleted',16,1)
      END
         
ELSE
BEGIN
     DELETE FROM TERRITORY WHERE TERRITORY_ID = @TERRITORY_ID
END

GO
exec Usp_Delete_Territory_Area @TERRITORY_ID = '1111111111'

select * from TERRITORY WHERE TERRITORY_ID = '1111111111'

SELECT * FROM DIST_SHIP_TO WHERE TERRITORY_ID = '1111111111'

SELECT COUNT(TERRITORY_ID) FROM DIST_SHIP_TO WHERE TERRITORY_ID = '1111111111'
-------------------------------------------------------------------------------------------
-----PROCEDURE UNTUK MENGINSERT DIST_SHIP_TO-------------------------------------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Insert_Dist_Ship_To' AND TYPE = 'P')
DROP PROCEDURE Usp_Insert_Dist_Ship_To
GO
CREATE PROCEDURE Usp_Insert_Dist_Ship_To
@DIST_SHIP_TO_ID VARCHAR(20),
@DISTRIBUTOR_ID VARCHAR(10),
@TERRITORY_ID VARCHAR(10),
@CREATE_BY VARCHAR(30)
AS
INSERT INTO DIST_SHIP_TO(DIST_SHIP_TO_ID,DISTRIBUTOR_ID,TERRITORY_ID,CREATE_BY,CREATE_DATE)
VALUES(@DIST_SHIP_TO_ID,@DISTRIBUTOR_ID,@TERRITORY_ID,@CREATE_BY,GETDATE())
GO
--------------------------------------------------------------------------------------
--------PROCEDURE UNTUK MENDELETE DATA DIST_SHIP_TO-----------------------------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Delete_Dist_Ship_To' AND TYPE = 'P')
DROP PROCEDURE Usp_Delete_Dist_Ship_To
GO
CREATE PROCEDURE Usp_Delete_Dist_Ship_To
@DIST_SHIP_TO_ID VARCHAR(20)
AS
--CHECK APAKAH ADA REFERENCE_DATANYA
IF (SELECT COUNT(DIST_SHIP_TO_ID) FROM 	OA_SHIP_TO WHERE DIST_SHIP_TO_ID = @DIST_SHIP_TO_ID) > 0
   BEGIN
	RAISERROR ('Data can not be deleted',16,1)
   END
ELSE
   BEGIN
	DELETE FROM DIST_SHIP_TO WHERE DIST_SHIP_TO_ID = @DIST_SHIP_TO_ID
   END
GO


