SELECT * FROM TEMPDB..##T_HEADER_PO_Administrator

SELECT * FROM TEMPDB..##T_PO_DETAIL_Administrator

SELECT * FROM TEMPDB.. ##T_R_OA_BrandPack_Administrator

SELECT * FROM TEMPDB..##T_R_SPPB_Administrator
SELECT * FROM TEMPDB..##T_R_OA_SHIP_TO_Administrator

SELECT GD.SPPB_BRANDPACK_ID,SUM(GD.GON_QTY)AS TOTAL_GON_QTY,MAX(GH.GON_DATE)AS LAST_GON_DATE FROM  GON_HEADER GH LEFT OUTER JOIN GON_DETAIL GD 
             ON GD.GON_NO = GH.GON_NO WHERE GH.GON_DATE >= 'Sep  1 2013' GROUP BY GD.SPPB_BRANDPACK_ID
SELECT
--@FROM_DATE = 'Sep  1 2013', @UNTIL_DATE = 'Apr  1 2014'
SELECT * FROM GON_HEADER WHERE GON_DATE >=  'Sep  1 2013' ORDER BY GON_DATE DESC;

exec sp_executesql @stmt = N'SET NOCOUNT ON; 
IF EXISTS(SELECT [NAME] FROM TEMPDB..SYSOBJECTS WHERE [NAME] = ''##T_F_R_SPPB_Administrator'' AND TYPE = ''U'')
 BEGIN 
 SELECT * FROM TEMPDB..##T_F_R_SPPB_Administrator
 END '

SELECT * FROM SPPB_BRANDPACK WHERE SPPB_BRANDPACK_ID ='13-14-000221023/CS-PO/IX/2013-00017483023/CS-PO/IX/201300325025KD'

SELECT * FROM GON_DETAIL WHERE SPPB_BRANDPACK_ID ='13-14-000221023/CS-PO/IX/2013-00017483023/CS-PO/IX/201300325025KD'

SELECT * FROM GON_DETAIL 

SELECT GON_NO,COUNT(GON_NO)AS JUMLAH_GON INTO TEMPDB..##T_GON_CHECK FROM(
SELECT * FROM(
SELECT SPPB_NO,SPPB_BRANDPACK_ID,GON_1_NO AS GON_NO,GON_1_DATE AS GON_DATE,GON_1_QTY AS GON_QTY,GON_1_GT_ID AS GT_ID
FROM SPPB_BRANDPACK WHERE GON_1_NO IS NOT NULL AND GON_1_NO != '' AND GON_1_QTY > 0
UNION 
SELECT SPPB_NO,SPPB_BRANDPACK_ID,GON_2_NO AS GON_NO,GON_2_DATE AS GON_DATE,GON_2_QTY AS GON_QTY,GON_2_GT_ID AS GT_ID
FROM SPPB_BRANDPACK WHERE GON_2_NO IS NOT NULL AND GON_2_NO != ''  AND GON_2_QTY > 0
UNION
SELECT SPPB_NO,SPPB_BRANDPACK_ID,GON_3_NO AS GON_NO,GON_3_DATE AS GON_DATE,GON_3_QTY AS GON_QTY,GON_3_GT_ID AS GT_ID
FROM SPPB_BRANDPACK WHERE GON_3_NO IS NOT NULL AND GON_3_NO != ''  AND GON_3_QTY > 0
UNION
SELECT SPPB_NO,SPPB_BRANDPACK_ID,GON_4_NO AS GON_NO,GON_4_DATE AS GON_DATE,GON_4_QTY AS GON_QTY,GON_4_GT_ID AS GT_ID
FROM SPPB_BRANDPACK WHERE GON_4_NO IS NOT NULL AND GON_4_NO != ''  AND GON_4_QTY > 0
UNION 
SELECT SPPB_NO,SPPB_BRANDPACK_ID,GON_5_NO AS GON_NO,GON_5_DATE AS GON_DATE,GON_5_QTY AS GON_QTY,GON_5_GT_ID AS GT_ID
FROM SPPB_BRANDPACK WHERE GON_5_NO IS NOT NULL AND GON_5_NO != ''  AND GON_5_QTY > 0
UNION
SELECT SPPB_NO,SPPB_BRANDPACK_ID,GON_6_NO AS GON_NO,GON_6_DATE AS GON_DATE,GON_6_QTY AS GON_QTY,GON_6_GT_ID AS GT_ID
FROM SPPB_BRANDPACK WHERE GON_6_NO IS NOT NULL AND GON_6_NO != ''  AND GON_6_QTY > 0 )C ORDER BY GON_NO WHERE GON_DATE >=  'Sep  1 2013' )C1
--ORDER BY GON_DATE DESC
GROUP BY GON_NO
ORDER BY GON_NO
SELECT * FROM TEMPDB..##T_GON_CHECK TG
SELECT GH.* FROM GON_HEADER GH INNER JOIN  TEMPDB..##T_GON_CHECK TG
ON GH.GON_NO = TG.GON_NO ORDER BY GH.GON_DATE

SELECT GD.*  FROM  GON_HEADER GH LEFT OUTER JOIN GON_DETAIL GD 
             ON GD.GON_HEADER_ID = GH.GON_HEADER_ID WHERE GH.GON_DATE >= 'Sep  1 2013' GROUP BY GD.SPPB_BRANDPACK_ID

UPDATE SPPB_BRANDPACK SET REMARK = SUBSTRING(REMARK,1,CHARINDEX(REMARK,'(SHIPPED)'))

SELECT PO.PO_REF_NO,SB.SPPB_NO,SB.REMARK,SUBSTRING(SB.REMARK,1,CHARINDEX(SB.REMARK,'(SHIPPED)'))AS REMARK1 FROM SPPB_BRANDPACK SB
INNER JOIN SPPB_HEADER SH ON SB.SPPB_NO = SH.SPPB_NO INNER JOIN ORDR_PURCHASE_ORDER PO ON PO.PO_REF_NO = SH.PO_REF_NO
WHERE  SUBSTRING(SB.REMARK,1,CHARINDEX(SB.REMARK,'(SHIPPED)')) IS NOT NULL AND  SUBSTRING(SB.REMARK,1,CHARINDEX(SB.REMARK,'(SHIPPED)')) != ''

UPDATE SPPB_BRANDPACK SET REMARK = 'PRICE FROM FREE MARKET' WHERE SPPB_NO = '10-11-001663' 

SELECT * FROM SPPB_HEADER WHERE PO_REF_NO = '047.A/SMA/IX/13'

SELECT LEN('TEST_SPPB_001047.A/SMA/IX/13-00017647047.A/SMA/IX/1300010200MD')

SELECT * FROM GON_HEADER WHERE SPPB_NO LIKE '%TEST_SPPB%'
SELECT * FROM GON_DETAIL WHERE GON_HEADER_ID LIKE '%TEST_SPPB%'
DELETE FROM GON_HEADER WHERE SPPB_NO LIKE '%TEST_SPPB%'
DELETE FROM GON_DETAIL WHERE SPPB_BRANDPACK_ID LIKE '%TEST_SPPB%'

exec sp_executesql N'SET NOCOUNT ON;
 IF EXISTS(SELECT SPPB_BRANDPACK_ID FROM SPPB_BRANDPACK WHERE SPPB_NO = @SPPB_NO) 
 BEGIN 
SELECT SB.SPPB_BRANDPACK_ID,PB.BRANDPACK_ID,SB.SPPB_NO,BP.BRANDPACK_NAME,SB.SPPB_QTY,TOTAL_GON_QTY = ISNULL(GON.TOTAL_GON_QTY,0),SB.OA_BRANDPACK_ID,SB.STATUS,
''PO_CATEGORY'' = CASE WHEN (PB.PLANTATION_ID IS NOT NULL) THEN ''PLANTATATION'' 
                     WHEN (PB.PROJ_BRANDPACK_ID IS NOT NULL) THEN ''PROJECT'' 
                     ELSE ''FREE MARKET'' END,  SB.CREATE_DATE,SB.CREATE_BY,SB.MODIFY_DATE,SB.MODIFY_BY,
 SB.REMARK,SB.IsUpdatedBySystem FROM SPPB_BRANDPACK SB INNER JOIN ORDR_OA_BRANDPACK OOA ON OOA.OA_BRANDPACK_ID = SB.OA_BRANDPACK_ID INNER JOIN ORDR_PO_BRANDPACK PB 
ON PB.PO_BRANDPACK_ID = OOA.PO_BRANDPACK_ID 
INNER JOIN BRND_BRANDPACK BP ON BP.BRANDPACK_ID = PB.BRANDPACK_ID 
 LEFT OUTER JOIN(
                 SELECT SPPB_BRANDPACK_ID,ISNULL(SUM(GON_QTY),0)AS TOTAL_GON_QTY FROM GON_DETAIL WHERE SPPB_BRANDPACK_ID = ANY(SELECT SPPB_BRANDPACK_ID FROM 
SPPB_BRANDPACK 
                 WHERE SPPB_NO = @SPPB_NO) GROUP BY SPPB_BRANDPACK_ID 
                 )GON ON GON.SPPB_BRANDPACK_ID = SB.SPPB_BRANDPACK_ID WHERE SB.SPPB_NO = @SPPB_NO ;
 END 
 ELSE 
 BEGIN 
 SELECT SPPB_BRANDPACK_ID = @SPPB_NO + OOA.OA_BRANDPACK_ID,SPPB_NO = @SPPB_NO,PB.BRANDPACK_ID,BB.BRANDPACK_NAME,OOA.QTY_EVEN + ISNULL(OOB.TOTAL_DISC_QTY,0) AS 
SPPB_QTY,TOTAL_GON_QTY = CONVERT(DECIMAL(18,3),0),OOA.OA_BRANDPACK_ID,STATUS = ''--NEW SPPB--'',
 ''PO_CATEGORY'' = CASE WHEN (PB.PLANTATION_ID IS NOT NULL) THEN ''PLANTATATION'' 
                     WHEN (PB.PROJ_BRANDPACK_ID IS NOT NULL) THEN ''PROJECT'' 
                     ELSE ''FREE MARKET'' END,CREATE_DATE = @CREATE_DATE,CREATE_BY = @CREATE_BY, 
 MODIFY_BY = NULL,MODIFY_DATE = NULL,REMARK = '''',IsUpdatedBySystem = CONVERT(BIT,0) FROM ORDR_OA_BRANDPACK OOA INNER JOIN ORDR_PO_BRANDPACK PB ON 
PB.PO_BRANDPACK_ID = OOA.PO_BRANDPACK_ID 
 INNER JOIN BRND_BRANDPACK BB ON BB.BRANDPACK_ID = PB.BRANDPACK_ID 
 LEFT OUTER JOIN(
                 SELECT OA_BRANDPACK_ID,ISNULL(SUM(DISC_QTY),0) AS TOTAL_DISC_QTY FROM ORDR_OA_BRANDPACK_DISC 
                 WHERE OA_BRANDPACK_ID = ANY( 
                                             SELECT OA_BRANDPACK_ID FROM ORDR_OA_BRANDPACK 
                                             WHERE PO_BRANDPACK_ID = ANY(SELECT PO_BRANDPACK_ID FROM ORDR_PO_BRANDPACK WHERE PO_REF_NO = @PO_REF_NO)
                                             ) 
                 GROUP BY OA_BRANDPACK_ID 
                 )OOB ON OOB.OA_BRANDPACK_ID = OOA.OA_BRANDPACK_ID WHERE PB.PO_REF_NO = @PO_REF_NO 
 AND PB.PO_ORIGINAL_QTY > 0 ;
 END ', N'@SPPB_NO varchar(30),@PO_REF_NO varchar(30),@CREATE_DATE smalldatetime,@CREATE_BY varchar(100)', @SPPB_NO = 'TEST_SPPB_001', @PO_REF_NO = 
'047.A/SMA/IX/13', @CREATE_DATE = 'Mar  3 2014 12:00AM', @CREATE_BY = 'Admin'