008981KGSTS
00898001KITA
00898001KD

BEGIN
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
 BEGIN TRANSACTION
  UPDATE BRND_BRANDPACK SET DEVIDED_QUANTITY = 0.001
  WHERE BRANDPACK_ID = '008981KGSTS'
	IF (@@ERROR <> 0)
	  BEGIN
	    ROLLBACK TRANSACTION
	    RETURN
  	  END
    		
  UPDATE BRND_BRANDPACK SET DEVIDED_QUANTITY = 0.001
  WHERE BRANDPACK_ID = '00898001KITA'
	IF (@@ERROR <> 0)
	  BEGIN
	    ROLLBACK TRANSACTION
	    RETURN
  	  END
  UPDATE BRND_BRANDPACK SET DEVIDED_QUANTITY = 0.001
  WHERE BRANDPACK_ID = '00898001KD'
	IF (@@ERROR <> 0)
	  BEGIN
	    ROLLBACK TRANSACTION
	    RETURN	
  	  END
  COMMIT TRANSACTION
END
	




		