SELECT * FROM ORDR_PURCHASE_ORDER WHERE PO_REF_DATE = '11/31/2009'
AND DISTRIBUTOR_ID LIKE '%000'

SET ISOLATION LEVEL SERIALIZABLE
BEGIN TRANSACTION
UPDATE ORDR_PURCHASE_ORDER SET PO_REF_DATE = '03/02/2010'
WHERE PO_REF_NO IN(
SELECT PO_REF_NO FROM ORDR_PURCHASE_ORDER WHERE PO_REF_DATE = '03/01/2010'
AND DISTRIBUTOR_ID LIKE '%000')
IF(@@ERROR > 0)
BEGIN
	ROLLBACK TRANSACTION;RETURN;
END
UPDATE ORDR_PURCHASE_ORDER SET PO_REF_DATE = '11/29/2009'
WHERE PO_REF_NO IN(
SELECT PO_REF_NO FROM ORDR_PURCHASE_ORDER WHERE PO_REF_DATE = '11/30/2009'
AND DISTRIBUTOR_ID LIKE '%000')
IF(@@ERROR > 0)
BEGIN
	ROLLBACK TRANSACTION;RETURN;
END
COMMIT TRANSACTION

