Use Nufarm
GO
-- view untuk di multicolumn combo form distributor agreement
IF EXISTS (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS
      WHERE TABLE_NAME = 'VIEW_DISTRIBUTOR')
  DROP VIEW VIEW_DISTRIBUTOR
GO
CREATE VIEW VIEW_DISTRIBUTOR
AS
SELECT DR.DISTRIBUTOR_ID,DR.DISTRIBUTOR_NAME,DR.CONTACT,DR.PHONE,DR.INACTIVE,DR.TERRITORY_ID,TER.TERRITORY_AREA,
RG.REGIONAL_AREA FROM DIST_DISTRIBUTOR DR LEFT OUTER JOIN TERRITORY TER ON DR.TERRITORY_ID = TER.TERRITORY_ID
LEFT OUTER JOIN DIST_REGIONAL RG ON TER.REGIONAL_ID = RG.REGIONAL_ID
GO
--
-- view untuk di grid distributor agreement di form distributor agreement
IF EXISTS (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = 'VIEW_AGREEMENT')
DROP VIEW VIEW_AGREEMENT
GO
CREATE VIEW VIEW_AGREEMENT
AS
SELECT     TERRITORY.TERRITORY_ID, TERRITORY.TERRITORY_AREA, DISTRIBUTOR_AGREEMENT.DISTRIBUTOR_ID, 
                      DIST_DISTRIBUTOR.DISTRIBUTOR_NAME, DISTRIBUTOR_AGREEMENT.AGREEMENT_NO, AGREE_AGREEMENT.AGREEMENT_DESC, 
                      AGREE_AGREEMENT.START_DATE, AGREE_AGREEMENT.END_DATE, AGREE_AGREEMENT.QS_TREATMENT_FLAG
FROM         DISTRIBUTOR_AGREEMENT INNER JOIN
                      DIST_DISTRIBUTOR ON DISTRIBUTOR_AGREEMENT.DISTRIBUTOR_ID = DIST_DISTRIBUTOR.DISTRIBUTOR_ID INNER JOIN
                      AGREE_AGREEMENT ON DISTRIBUTOR_AGREEMENT.AGREEMENT_NO = AGREE_AGREEMENT.AGREEMENT_NO LEFT OUTER JOIN
                      TERRITORY ON DIST_DISTRIBUTOR.TERRITORY_ID = TERRITORY.TERRITORY_ID
GO
--
-- view untuk agreement brand_include
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = 'VIEW_AGREE_BRAND_INCLUDE')
DROP VIEW VIEW_AGREE_BRAND_INCLUDE
GO
CREATE VIEW VIEW_AGREE_BRAND_INCLUDE
AS
SELECT ABI.AGREE_BRAND_ID AS [ID],DR.TERRITORY_ID,DA.DISTRIBUTOR_ID,DR.DISTRIBUTOR_NAME,DA.AGREEMENT_NO,AA.QS_TREATMENT_FLAG,AA.AGREEMENT_DESC,
ABI.BRAND_ID,BR.BRAND_NAME,AA.START_DATE,AA.END_DATE,ABI.GIVEN_DISC_PCT AS [Given%],ABI.TARGET_Q1,
ABI.TARGET_Q2,ABI.TARGET_Q3,ABI.TARGET_Q4,ABI.TARGET_S1,ABI.TARGET_S2,ABI.TARGET_Q1_FM,ABI.TARGET_Q2_FM,ABI.TARGET_Q3_FM,ABI.TARGET_Q4_FM,ABI.TARGET_S1_FM,ABI.TARGET_S2_FM,
ABI.TARGET_Q1_PL,ABI.TARGET_Q2_PL,ABI.TARGET_Q3_PL,ABI.TARGET_Q4_PL,ABI.TARGET_S1_PL,ABI.TARGET_S2_PL,
ABI.TARGET_FMP1,ABI.TARGET_FMP2,ABI.TARGET_FMP3,ABI.TARGET_FMP_FM1,ABI.TARGET_FMP_FM2,ABI.TARGET_FMP_FM3,
ABI.TARGET_FMP_PL1,ABI.TARGET_FMP_PL2,ABI.TARGET_FMP_PL3,
CASE AA.QS_TREATMENT_FLAG WHEN 'S' THEN (ABI.TARGET_S1 + ABI.TARGET_S2) WHEN 'Q' THEN (ABI.TARGET_Q1 + ABI.TARGET_Q2 + ABI.TARGET_Q3 + ABI.TARGET_Q4) ELSE 0 END AS TARGET_YEAR,
CASE AA.QS_TREATMENT_FLAG WHEN 'S' THEN (ABI.TARGET_S1_FM + ABI.TARGET_S2_FM) WHEN 'Q' THEN (ABI.TARGET_Q1_FM + ABI.TARGET_Q2_FM + ABI.TARGET_Q4_FM) ELSE 0 END AS TARGET_YEAR_FM,
CASE AA.QS_TREATMENT_FLAG WHEN 'S' THEN (ABI.TARGET_S1_PL + ABI.TARGET_S2_PL) WHEN 'Q' THEN (ABI.TARGET_Q1_PL + ABI.TARGET_Q2_PL + ABI.TARGET_Q3_PL + ABI.TARGET_Q4_PL) ELSE 0 END AS TARGET_YEAR_PL,
ABI.COMB_AGREE_BRAND_ID AS COMBINED_BRAND
FROM AGREE_BRAND_INCLUDE ABI INNER JOIN AGREE_AGREEMENT AA ON ABI.AGREEMENT_NO = AA.AGREEMENT_NO
INNER JOIN BRND_BRAND BR ON ABI.BRAND_ID = BR.BRAND_ID INNER JOIN DISTRIBUTOR_AGREEMENT DA
ON DA.AGREEMENT_NO = AA.AGREEMENT_NO INNER JOIN DIST_DISTRIBUTOR DR ON DR.DISTRIBUTOR_ID = DA.DISTRIBUTOR_ID
GO
-----------------------------------------------------------------------------------
-- VIEW untuk AGREEMENT_BRAND_PACK_INCLUDE
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = 'VIEW_AGREE_BRANDPACK_INCLUDE')
DROP VIEW VIEW_AGREE_BRANDPACK_INCLUDE
GO
CREATE VIEW dbo.VIEW_AGREE_BRANDPACK_INCLUDE
WITH SCHEMABINDING 
AS
SELECT     dbo.DISTRIBUTOR_AGREEMENT.DISTRIBUTOR_ID, dbo.DISTRIBUTOR_AGREEMENT.AGREEMENT_NO, 
                      dbo.DIST_DISTRIBUTOR.DISTRIBUTOR_NAME, dbo.AGREE_AGREEMENT.AGREEMENT_DESC,dbo.AGREE_BRAND_INCLUDE.BRAND_ID, dbo.AGREE_BRAND_INCLUDE.AGREE_BRAND_ID, 
                      dbo.BRND_BRANDPACK.BRANDPACK_ID, dbo.BRND_BRANDPACK.BRANDPACK_NAME, dbo.AGREE_AGREEMENT.START_DATE, 
                      dbo.AGREE_AGREEMENT.END_DATE, dbo.AGREE_AGREEMENT.QS_TREATMENT_FLAG
FROM         dbo.AGREE_BRAND_INCLUDE INNER JOIN
                      dbo.AGREE_AGREEMENT ON dbo.AGREE_BRAND_INCLUDE.AGREEMENT_NO = dbo.AGREE_AGREEMENT.AGREEMENT_NO INNER JOIN
                      dbo.AGREE_BRANDPACK_INCLUDE ON 
                      dbo.AGREE_BRAND_INCLUDE.AGREE_BRAND_ID = dbo.AGREE_BRANDPACK_INCLUDE.AGREE_BRAND_ID INNER JOIN
                      dbo.BRND_BRANDPACK ON dbo.AGREE_BRANDPACK_INCLUDE.BRANDPACK_ID = dbo.BRND_BRANDPACK.BRANDPACK_ID INNER JOIN
                      dbo.DISTRIBUTOR_AGREEMENT ON dbo.AGREE_AGREEMENT.AGREEMENT_NO = dbo.DISTRIBUTOR_AGREEMENT.AGREEMENT_NO INNER JOIN
                      dbo.DIST_DISTRIBUTOR ON dbo.DISTRIBUTOR_AGREEMENT.DISTRIBUTOR_ID = dbo.DIST_DISTRIBUTOR.DISTRIBUTOR_ID

GO
-
----------------------------------------------------------------------------------------------
--VIEW BUAT PROJECT BRANDPACK_DETAIL
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = 'PROJECT_BRANDPACK_DETAIL')
DROP VIEW PROJECT_BRANDPACK_DETAIL
GO
CREATE VIEW PROJECT_BRANDPACK_DETAIL
AS
SELECT     PROJ_BRANDPACK.PROJ_BRANDPACK_ID, PROJ_BRANDPACK.BRANDPACK_ID, BRND_BRANDPACK.BRANDPACK_NAME, 
                      PROJ_BRANDPACK.PROJ_REF_NO, DIST_DISTRIBUTOR.DISTRIBUTOR_NAME AS SHIP_TO_DISTRIBUTOR, 
                      PROJ_BRANDPACK.MAX_ORDER, PROJ_BRANDPACK.APPROVED_DISC_PCT AS DISCOUNT,  
                      PROJ_BRANDPACK.CREATE_BY, PROJ_BRANDPACK.CREATE_DATE, 
                      PROJ_BRANDPACK.MODIFY_BY, PROJ_BRANDPACK.MODIFY_DATE
FROM         BRND_BRANDPACK INNER JOIN
                      PROJ_BRANDPACK INNER JOIN
                      DIST_DISTRIBUTOR ON PROJ_BRANDPACK.DISTRIBUTOR_ID = DIST_DISTRIBUTOR.DISTRIBUTOR_ID ON 
                      BRND_BRANDPACK.BRANDPACK_ID = PROJ_BRANDPACK.BRANDPACK_ID

GO

--
-----------------------------------------------------------------------------------------
--
--VIEW BUAT PROJECT_DISTRIBUTOR
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = 'PROJECT_DISTRIBUTOR')
DROP VIEW PROJECT_DISTRIBUTOR
GO
CREATE VIEW PROJECT_DISTRIBUTOR
AS

SELECT     PROJ_PROJECT.PROJ_REF_NO, PROJ_PROJECT.PROJECT_NAME, PROJ_PROJECT.PROJ_REF_DATE,PROJ_PROJECT.START_DATE,PROJ_PROJECT.END_DATE, PROJ_PROJECT.ADDRESS, 
                      PROJ_PROJECT.PHONE, PROJ_PROJECT.CONTACT, PROJ_PROJECT.FAX, PROJ_PROJECT.HP, 
                      DIST_DISTRIBUTOR.DISTRIBUTOR_NAME, DIST_DISTRIBUTOR.DISTRIBUTOR_ID
FROM         PROJ_PROJECT INNER JOIN
                      DIST_DISTRIBUTOR ON PROJ_PROJECT.DISTRIBUTOR_ID = DIST_DISTRIBUTOR.DISTRIBUTOR_ID

GO

--
-----------------------------------------------------------------------
--
-- VIEW UNTUK DATAGRID PROJECT_DISTRIBUTOR
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = 'PROJECT')
DROP VIEW PROJECT
GO
CREATE VIEW PROJECT
AS
SELECT     PROJECT_DISTRIBUTOR.PROJ_REF_NO, PROJECT_DISTRIBUTOR.PROJECT_NAME, PROJECT_DISTRIBUTOR.PROJ_REF_DATE, 
                      PROJECT_BRANDPACK_DETAIL.BRANDPACK_NAME, PROJECT_BRANDPACK_DETAIL.PROJ_BRANDPACK_ID, 
                      PROJECT_BRANDPACK_DETAIL.SHIP_TO_DISTRIBUTOR, PROJECT_BRANDPACK_DETAIL.MAX_ORDER, 
                      PROJECT_BRANDPACK_DETAIL.DISCOUNT, PROJECT_BRANDPACK_DETAIL.START_DATE, PROJECT_BRANDPACK_DETAIL.END_DATE, 
                      PROJECT_DISTRIBUTOR.ADDRESS, PROJECT_DISTRIBUTOR.PHONE, PROJECT_DISTRIBUTOR.FAX, 
                      PROJECT_DISTRIBUTOR.CONTACT, PROJECT_DISTRIBUTOR.HP, PROJECT_DISTRIBUTOR.DISTRIBUTOR_NAME, 
                      PROJECT_DISTRIBUTOR.DISTRIBUTOR_ID
FROM         PROJECT_DISTRIBUTOR LEFT OUTER JOIN
                      PROJECT_BRANDPACK_DETAIL ON PROJECT_DISTRIBUTOR.PROJ_REF_NO = PROJECT_BRANDPACK_DETAIL.PROJ_REF_NO

GO

--
-----------------------------------------------------------------------------
--
--VIEW UNTUK DISTRIBUTOR DI PO DIMANA AGREEMENT MASIH BERLAKU
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = 'VIEW_DIST_PO_AGREE_STILL_APPLY')
DROP VIEW VIEW_DIST_PO_AGREE_STILL_APPLY
GO
CREATE VIEW VIEW_DIST_PO_AGREE_STILL_APPLY
AS
SELECT DISTINCT ORDR_PURCHASE_ORDER.DISTRIBUTOR_ID
FROM         ORDR_PURCHASE_ORDER INNER JOIN
                      VIEW_AGREE_BRANDPACK_INCLUDE ON 
                      ORDR_PURCHASE_ORDER.DISTRIBUTOR_ID = VIEW_AGREE_BRANDPACK_INCLUDE.DISTRIBUTOR_ID
WHERE     (VIEW_AGREE_BRANDPACK_INCLUDE.END_DATE >= GETDATE())

GO

--
---------------------------------------------------------------------
--
--VIEW UNTUK PURCHASE ORDER
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME ='VIEW_PURCHASE_ORDER')
DROP VIEW VIEW_PURCHASE_ORDER
GO
CREATE  VIEW VIEW_PURCHASE_ORDER
AS
SELECT OPO.PO_REF_DATE,OPO.PROJ_REF_NO,OPO.DISTRIBUTOR_ID,OPB.PO_BRANDPACK_ID,BB.BRANDPACK_NAME,
OPB.PO_ORIGINAL_QTY AS QUANTITY,OPB.PO_PRICE_PERQTY AS [PRICE/QTY],
OPB.PO_ORIGINAL_QTY * OPB.PO_PRICE_PERQTY AS TOTAL,
OPB.BRANDPACK_ID,OPB.PO_REF_NO,OPB.GIVEN_PKPP_VALUE,OPB.DESCRIPTIONS,
OPB.CREATE_DATE,OPB.MODIFY_DATE
FROM ORDR_PO_BRANDPACK OPB INNER JOIN ORDR_PURCHASE_ORDER OPO
ON OPB.PO_REF_NO = OPO.PO_REF_NO INNER JOIN BRND_BRANDPACK BB
ON OPB.BRANDPACK_ID = BB.BRANDPACK_ID 
GO



--
-------------------------------------------------------------------------------------------------------
--VIEW UNTUK DI TAMPILKAN DI GRIDEX3 FORM PROGRAM
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = 'VIEW_STEPPING_DISCOUNT')
DROP VIEW VIEW_STEPPING_DISCOUNT
GO
CREATE VIEW VIEW_STEPPING_DISCOUNT
AS
SELECT     MRKT_STEPPING_DISCOUNT.PROG_BRANDPACK_DIST_ID, DIST_DISTRIBUTOR.DISTRIBUTOR_NAME, 
                      MRKT_STEPPING_DISCOUNT.MORE_THAN_QTY, MRKT_STEPPING_DISCOUNT.STEPPING_DISC_PCT, 
                      MRKT_BRANDPACK_DISTRIBUTOR.START_DATE, MRKT_BRANDPACK_DISTRIBUTOR.END_DATE
FROM         DIST_DISTRIBUTOR INNER JOIN
                      MRKT_BRANDPACK_DISTRIBUTOR ON 
                      DIST_DISTRIBUTOR.DISTRIBUTOR_ID = MRKT_BRANDPACK_DISTRIBUTOR.DISTRIBUTOR_ID INNER JOIN
                      MRKT_STEPPING_DISCOUNT ON 
                      MRKT_BRANDPACK_DISTRIBUTOR.PROG_BRANDPACK_DIST_ID = MRKT_STEPPING_DISCOUNT.PROG_BRANDPACK_DIST_ID

GO
--

--VIEW UNTUK DI DATAGRID PROGRAM DATAGRID1 
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = 'MRKT_PROGRAM_BRANDPACK')
DROP VIEW MRKT_PROGRAM_BRANDPACK
GO
CREATE VIEW MRKT_PROGRAM_BRANDPACK
AS
SELECT     MRKT_MARKETING_PROGRAM.PROGRAM_ID, MRKT_MARKETING_PROGRAM.PROGRAM_NAME, 
                      MRKT_MARKETING_PROGRAM.START_DATE, MRKT_MARKETING_PROGRAM.END_DATE, MRKT_BRANDPACK.BRANDPACK_ID, 
                      BRND_BRANDPACK.BRANDPACK_NAME, MRKT_BRANDPACK.START_DATE AS BRANDPACK_START_DATE, 
                      MRKT_BRANDPACK.END_DATE AS BRANDPACK_END_DATE, MRKT_BRANDPACK.PROG_BRANDPACK_ID
FROM         BRND_BRANDPACK INNER JOIN
                      MRKT_BRANDPACK ON BRND_BRANDPACK.BRANDPACK_ID = MRKT_BRANDPACK.BRANDPACK_ID RIGHT OUTER JOIN
                      MRKT_MARKETING_PROGRAM ON MRKT_BRANDPACK.PROGRAM_ID = MRKT_MARKETING_PROGRAM.PROGRAM_ID

GO
--
---------------------------------------------------------------------------------------------

-------------------------------------------------------------------------------------------
--VIEW UNTUK DI TAMPILKAN DI GRIDEX1 FROM AGREEMENT
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = 'VIEW_DISTRIBUTOR_AGREEMENT')
DROP VIEW VIEW_DISTRIBUTOR_AGREEMENT
GO
CREATE VIEW VIEW_DISTRIBUTOR_AGREEMENT
AS
SELECT     DISTRIBUTOR_AGREEMENT.DISTRIBUTOR_ID, DIST_DISTRIBUTOR.DISTRIBUTOR_NAME, 
                      DISTRIBUTOR_AGREEMENT.AGREEMENT_NO, AGREE_AGREEMENT.START_DATE, AGREE_AGREEMENT.END_DATE, 
                      BRND_BRAND.BRAND_NAME, AGREE_BRANDPACK_INCLUDE.BRANDPACK_ID, BRND_BRANDPACK.BRANDPACK_NAME
FROM         AGREE_BRAND_INCLUDE INNER JOIN
                      AGREE_AGREEMENT ON AGREE_BRAND_INCLUDE.AGREEMENT_NO = AGREE_AGREEMENT.AGREEMENT_NO INNER JOIN
                      BRND_BRAND ON AGREE_BRAND_INCLUDE.BRAND_ID = BRND_BRAND.BRAND_ID INNER JOIN
                      AGREE_BRANDPACK_INCLUDE ON AGREE_AGREEMENT.AGREEMENT_NO = AGREE_BRANDPACK_INCLUDE.AGREEMENT_NO AND 
                      AGREE_BRAND_INCLUDE.AGREE_BRAND_ID = AGREE_BRANDPACK_INCLUDE.AGREE_BRAND_ID INNER JOIN
                      BRND_BRANDPACK ON AGREE_BRANDPACK_INCLUDE.BRANDPACK_ID = BRND_BRANDPACK.BRANDPACK_ID AND 
                      BRND_BRAND.BRAND_ID = BRND_BRANDPACK.BRAND_ID INNER JOIN
                      DISTRIBUTOR_AGREEMENT ON AGREE_AGREEMENT.AGREEMENT_NO = DISTRIBUTOR_AGREEMENT.AGREEMENT_NO INNER JOIN
                      DIST_DISTRIBUTOR ON DISTRIBUTOR_AGREEMENT.DISTRIBUTOR_ID = DIST_DISTRIBUTOR.DISTRIBUTOR_ID
GO
-----------------------------------------------------------------------------------------------
--------------------------VIEW BUAT NGEJEMBRENGIN---------------REPORT PO-SPPB----------------
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = 'VIEW_SPPB_ALL')
DROP VIEW VIEW_SPPB_ALL
GO
CREATE VIEW VIEW_SPPB_ALL
AS
SELECT OPO.DISTRIBUTOR_ID,DR.DISTRIBUTOR_NAME,OPO.PO_REF_NO,OOA.OA_ID AS OA_REF_NO,ST.TERRITORY_AREA AS SHIP_TO,ST.MANAGER,
OPO.PO_REF_DATE,OPB.BRANDPACK_ID,B.BRAND_NAME,BB.BRANDPACK_NAME,OPB.PO_ORIGINAL_QTY,OPB.PO_PRICE_PERQTY AS PRICE,OOB.QTY_EVEN + ISNULL(OOBD.DISC_QTY,0) AS OA_QTY
,OOB.OA_BRANDPACK_ID,SB.SPPB_NO,SB.SPPB_DATE,ISNULL(SB.SPPB_QTY,0)AS SPPB_QTY,SB.CREATE_DATE,SB.RELEASE_DATE,SB.LEAD_TIME
,SB.GON_1_NO,SB.GON_1_DATE,SB.GON_1_QTY,SB.GON_1_GT_ID,GON_1_TRANSPORTER_NAME,
SB.GON_2_NO,SB.GON_2_DATE,SB.GON_2_QTY,SB.GON_2_GT_ID,GON_2_TRANSPORTER_NAME,
SB.GON_3_NO,SB.GON_3_DATE,SB.GON_3_QTY,SB.GON_3_GT_ID,GON_3_TRANSPORTER_NAME,
SB.GON_4_NO,SB.GON_4_DATE,SB.GON_4_QTY,SB.GON_4_GT_ID,GON_4_TRANSPORTER_NAME,
SB.GON_5_NO,SB.GON_5_DATE,SB.GON_5_QTY,SB.GON_5_GT_ID,GON_5_TRANSPORTER_NAME,
SB.GON_6_NO,SB.GON_6_DATE,SB.GON_6_QTY,SB.GON_6_GT_ID,GON_6_TRANSPORTER_NAME,
SB.STATUS,SB.BALANCE,SB.ISREVISION,SB.REMARK,OTP.OTP_NO,OTP.OTP_DATE,OTP.OTP_QTY,OTP.CREATE_DATE AS OTP_CREATE_DATE,DTP.DO_TP_NO,DTP.DO_TP_DATE,
DTP.DO_TP_QTY
FROM ORDR_PURCHASE_ORDER OPO INNER JOIN DIST_DISTRIBUTOR DR ON OPO.DISTRIBUTOR_ID = DR.DISTRIBUTOR_ID
  INNER JOIN ORDR_ORDER_ACCEPTANCE OOA ON OOA.PO_REF_NO = OPO.PO_REF_NO
INNER JOIN ORDR_PO_BRANDPACK OPB
ON OPO.PO_REF_NO = OPB.PO_REF_NO INNER JOIN BRND_BRANDPACK BB ON OPB.BRANDPACK_ID = BB.BRANDPACK_ID
INNER JOIN BRND_BRAND B ON B.BRAND_ID = BB.BRAND_ID
INNER JOIN ORDR_OA_BRANDPACK OOB ON OPB.PO_BRANDPACK_ID = OOB.PO_BRANDPACK_ID AND OOB.OA_ID = OOA.OA_ID
LEFT OUTER JOIN (SELECT SH.SPPB_NO,SH.SPPB_DATE,SB1.OA_BRANDPACK_ID,SB1.SPPB_QTY,SB1.CREATE_DATE,SB1.RELEASE_DATE, DATEDIFF(DAY,SB1.CREATE_DATE,ISNULL(SB1.RELEASE_DATE,SB1.CREATE_DATE)) AS LEAD_TIME,
				SB1.GON_1_NO,SB1.GON_1_DATE,SB1.GON_1_QTY,SB1.GON_1_GT_ID,SB1.GON_1_TRANSPORTER_NAME,
				SB1.GON_2_NO,SB1.GON_2_DATE,SB1.GON_2_QTY,SB1.GON_2_GT_ID,SB1.GON_2_TRANSPORTER_NAME,
				SB1.GON_3_NO,SB1.GON_3_DATE,SB1.GON_3_QTY,SB1.GON_3_GT_ID,SB1.GON_3_TRANSPORTER_NAME,
				SB1.GON_4_QTY,SB1.GON_4_NO,SB1.GON_4_DATE,SB1.GON_4_GT_ID,SB1.GON_4_TRANSPORTER_NAME,
				SB1.GON_5_NO,SB1.GON_5_DATE,SB1.GON_5_QTY,SB1.GON_5_GT_ID,SB1.GON_5_TRANSPORTER_NAME,
				SB1.GON_6_NO,SB1.GON_6_DATE,SB1.GON_6_QTY,SB1.GON_6_GT_ID,SB1.GON_6_TRANSPORTER_NAME,
				 SB1.STATUS,SB1.BALANCE,SB1.ISREVISION,SB1.REMARK FROM SPPB_HEADER SH INNER JOIN SPPB_BRANDPACK SB1 ON SH.SPPB_NO = SB1.SPPB_NO
                )SB
ON OOB.OA_BRANDPACK_ID = SB.OA_BRANDPACK_ID
LEFT OUTER JOIN (SELECT OOH.OTP_NO,OOH.OTP_DATE,OD.OTP_QTY,OD.CREATE_DATE,OD.OA_BRANDPACK_ID FROM ORDR_OTP_HEADER OOH INNER JOIN OTP_DETAIL OD
	         ON OD.OTP_NO = OOH.OTP_NO
                )OTP 
ON SB.OA_BRANDPACK_ID = OTP.OA_BRANDPACK_ID
LEFT OUTER JOIN (SELECT DTH.DO_TP_NO,DTH.DO_TP_DATE,DTD.DO_TP_QTY,DTD.OA_BRANDPACK_ID FROM DO_TP_HEADER DTH
		  INNER JOIN DO_TP_DETAIL DTD ON DTH.DO_TP_NO = DTD.DO_TP_NO
   		)DTP
ON OTP.OA_BRANDPACK_ID = DTP.OA_BRANDPACK_ID
LEFT OUTER JOIN (SELECT OST.OA_ID,TERR.TERRITORY_AREA,TM.MANAGER
                 FROM OA_SHIP_TO OST INNER JOIN SHIP_TO ST ON OST.SHIP_TO_ID = ST.SHIP_TO_ID
                 INNER JOIN TERRITORY TERR ON TERR.TERRITORY_ID = ST.TERRITORY_ID
                 INNER JOIN TERRITORY_MANAGER TM ON ST.TM_ID = TM.TM_ID
                 )ST
ON OOB.OA_ID = ST.OA_ID
LEFT OUTER JOIN(SELECT OA_BRANDPACK_ID,SUM(DISC_QTY)AS DISC_QTY FROM ORDR_OA_BRANDPACK_DISC
                WHERE GQSY_SGT_P_FLAG = 'RMOA'
		GROUP BY OA_BRANDPACK_ID HAVING SUM(DISC_QTY) > 0
                )OOBD
ON OOB.OA_BRANDPACK_ID = OOBD.OA_BRANDPACK_ID 
WHERE YEAR(OPO.PO_REF_DATE) >= YEAR(GETDATE()) -1
GO


----------------------------------------------------------------------------------
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = 'Uv_Kios')
DROP VIEW Uv_Kios
GO
CREATE VIEW Uv_Kios 
AS
SELECT K.IDApp,DM.REGIONAL_ID AS RegionalID,DM.REGIONAL_AREA AS RegionalArea,
TERR.TERRITORY_ID AS TerritoryID,TERR.TERRITORY_AREA AS TerritoryArea,
K.IDKios,K.Kios_Name,K.Kios_Owner,K.NPWP,K.Address,K.State As Province,K.City,
K.PhoneNumber,K.ContactMobile,K.CustomerType
FROM Kios K LEFT OUTER JOIN TERRITORY TERR ON K.TerritoryCode = TERR.TERRITORY_ID
LEFT OUTER JOIN DIST_REGIONAL DM ON TERR.REGIONAL_ID = DM.REGIONAL_ID
GO
------------------------------------------------------------------------------------
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = 'Uv_Price_Distributor')
DROP VIEW Uv_Price_Distributor
GO
CREATE VIEW Uv_Price_Distributor 
AS
SELECT DPP.IDApp,DPP.PRICE_TAG,DPP.BRANDPACK_ID,BP.BRANDPACK_NAME,DPP.DISTRIBUTOR_ID,DR.DISTRIBUTOR_NAME,
DPP.PLANTATION_ID,PL.PLANTATION_NAME,'PLANTATION_AREA' = CASE WHEN TER0.TERRITORY_AREA IS NOT NULL THEN TER0.TERRITORY_AREA ELSE DR2.TERRITORY_AREA END,
DPP.PRICE,DPP.START_DATE,DPP.END_DATE,DPP.IncludeDPD

FROM DIST_PLANT_PRICE DPP INNER JOIN BRND_BRANDPACK BP ON DPP.BRANDPACK_ID = BP.BRANDPACK_ID
INNER JOIN DIST_DISTRIBUTOR DR ON DPP.DISTRIBUTOR_ID = DR.DISTRIBUTOR_ID
INNER JOIN PLANTATION PL ON PL.PLANTATION_ID = DPP.PLANTATION_ID
LEFT OUTER JOIN(SELECT TER1.TERRITORY_AREA,PL1.PLANTATION_ID FROM TERRITORY TER1 INNER JOIN PLANTATION PL1 ON PL1.TERRITORY_ID = TER1.TERRITORY_ID)TER0
ON TER0.PLANTATION_ID = PL.PLANTATION_ID
LEFT OUTER JOIN(SELECT DR1.DISTRIBUTOR_ID,TER2.TERRITORY_AREA FROM DIST_DISTRIBUTOR DR1 INNER JOIN TERRITORY TER2 ON TER2.TERRITORY_ID = DR1.TERRITORY_ID)DR2
ON DR2.DISTRIBUTOR_ID = DR.DISTRIBUTOR_ID
GO

------------------------------------------------------------------------------------
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = 'Uv_Price')
DROP VIEW Uv_Price
GO
CREATE VIEW Uv_Price
AS
SELECT IDApp,BPP.PRICE_TAG,BPP.BRANDPACK_ID,BP.BRANDPACK_NAME,BPP.PRICE,BPP.START_DATE
FROM BRND_PRICE_HISTORY BPP INNER JOIN BRND_BRANDPACK BP ON BPP.BRANDPACK_ID
= BP.BRANDPACK_ID
GO
---------------------------------------------------------------------------------- 
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = 'MARKETING_BRANDPACK_DISTRIBUTOR')
DROP VIEW MARKETING_BRANDPACK_DISTRIBUTOR
GO
CREATE VIEW MARKETING_BRANDPACK_DISTRIBUTOR
AS
SELECT TER.TERRITORY_AREA,MBD.PROG_BRANDPACK_DIST_ID, MBD.PROG_BRANDPACK_ID, 
      MBD.DISTRIBUTOR_ID, DR.DISTRIBUTOR_NAME, 
      MBD.START_DATE, MBD.END_DATE, 
      MBD.GIVEN_DISC_PCT AS [Given %], MBD.TARGET_QTY, 
      MBD.TARGET_DISC_PCT AS [Target %], MBD.STEPPING_FLAG AS Stepping, 
      MBD.AGREE_BRANDPACK_ID,BB.BRANDPACK_NAME, 
      MB.PROGRAM_ID, MB.BRANDPACK_ID, MBD.PRICE_HK, 
      MBD.TARGET_HK, MBD.ISHK, 
      MBD.TARGET_DK, MBD.GIVEN_DK, 
      MBD.ISDK, MBD.TARGET_CP, 
      MBD.GIVEN_CP, MBD.ISCP, MBD.ISSCPD,
      MBD.TARGET_PKPP, MBD.GIVEN_PKPP, 
      MBD.BONUS_VALUE, 
      MBD.ISPKPP,
      MBD.ISRPK, MBD.ISCPR, 
      MBD.TARGET_CPR, MBD.GIVEN_CPR
FROM  DIST_DISTRIBUTOR DR INNER JOIN
      MRKT_BRANDPACK_DISTRIBUTOR MBD ON 
      DR.DISTRIBUTOR_ID = MBD.DISTRIBUTOR_ID INNER JOIN
      MRKT_BRANDPACK MB ON 
      MBD.PROG_BRANDPACK_ID = MB.PROG_BRANDPACK_ID INNER JOIN
      BRND_BRANDPACK BB ON MB.BRANDPACK_ID = BB.BRANDPACK_ID
      INNER JOIN TERRITORY TER ON TER.TERRITORY_ID = DR.TERRITORY_ID
GO
-----------------------------------------------------------------------------------------
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = 'VIEW_REFERENCE_INVOICE')
BEGIN DROP VIEW  VIEW_REFERENCE_INVOICE ; END
GO
CREATE VIEW VIEW_REFERENCE_INVOICE
AS
SELECT * FROM 
(
SELECT PO.PO_REF_DATE, PO.PO_REF_NO,OOA.OA_ID AS OA_REF_NO,PO.DISTRIBUTOR_ID,DR.DISTRIBUTOR_NAME,
OPB.BRANDPACK_ID,BB.BRANDPACK_NAME,OPB.PO_ORIGINAL_QTY,--ISNULL(INV.INVNUMBER,'UNDEFINED')AS INVNUMBER,
ISNULL(INV.REFERENCE,'UNDEFINED') AS INVREFERENCE
FROM Nufarm.DBO.ORDR_PURCHASE_ORDER PO INNER JOIN Nufarm.DBO.ORDR_PO_BRANDPACK OPB
ON PO.PO_REF_NO = OPB.PO_REF_NO INNER JOIN Nufarm.DBO.ORDR_ORDER_ACCEPTANCE OOA
ON OOA.PO_REF_NO = PO.PO_REF_NO
INNER JOIN Nufarm.DBO.DIST_DISTRIBUTOR DR ON DR.DISTRIBUTOR_ID = PO.DISTRIBUTOR_ID
INNER JOIN Nufarm.DBO.BRND_BRANDPACK BB ON BB.BRANDPACK_ID = OPB.BRANDPACK_ID
LEFT OUTER JOIN(
		SELECT ORD1.VALUE AS REFERENCE FROM NI87.DBO.OEORDHO ORD1 
		 INNER JOIN NI87.DBO.OEORDH ORD ON ORD.ORDUNIQ = ORD1.ORDUNIQ

-- NI87.DBO.OEINVH INVO
                --INVO.INVNUMBER,INVO.PONUMBER,
                --INNER JOIN NI87.DBO.OEINVD INVD ON INVO.INVUNIQ = INVD.INVUNIQ
                --ON ORD.ORDNUMBER = INVO.ORDNUMBER
                --INNER JOIN NI87.DBO.OEORDHO ORD1 
                WHERE RTRIM(ORD1.OPTFIELD) = 'DTSREF' AND LEN(RTRIM(ORD1.VALUE)) >= 4
 		AND LEFT(ORD.ORDDATE,4) >= 2010
--INVD.QTYSHIPPED > 0 --AND INVO.INVDATE > 20101101
                
  		)INV
ON (INV.REFERENCE = OOA.RUN_NUMBER)
WHERE PO.PO_REF_DATE >= '07/01/2010' AND PO.PO_REF_DATE <= GETDATE()
AND OPB.PO_ORIGINAL_QTY > 0
)INV 
WHERE INV.INVREFERENCE = 'UNDEFINED'
GO
   

--------------------------------------------------
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = 'VIEW_REFERENCE_INVOICE_1')
BEGIN DROP VIEW  VIEW_REFERENCE_INVOICE_1 ; END
GO
CREATE VIEW VIEW_REFERENCE_INVOICE_1
AS
SELECT * FROM 
(
SELECT  PO.PO_REF_DATE,PO.PO_REF_NO,OOA.OA_ID AS OA_REF_NO,PO.DISTRIBUTOR_ID,DR.DISTRIBUTOR_NAME,
OPB.BRANDPACK_ID,BB.BRANDPACK_NAME,OPB.PO_ORIGINAL_QTY,--ISNULL(INV.INVNUMBER,'UNDEFINED')AS INVNUMBER,
ISNULL(INV.REFERENCE,'UNDEFINED') AS INVREFERENCE
FROM Nufarm.DBO.ORDR_PURCHASE_ORDER PO INNER JOIN Nufarm.DBO.ORDR_PO_BRANDPACK OPB
ON PO.PO_REF_NO = OPB.PO_REF_NO INNER JOIN Nufarm.DBO.ORDR_ORDER_ACCEPTANCE OOA
ON OOA.PO_REF_NO = PO.PO_REF_NO
INNER JOIN Nufarm.DBO.DIST_DISTRIBUTOR DR ON DR.DISTRIBUTOR_ID = PO.DISTRIBUTOR_ID
INNER JOIN Nufarm.DBO.BRND_BRANDPACK BB ON BB.BRANDPACK_ID = OPB.BRANDPACK_ID
LEFT OUTER JOIN(
		SELECT ORD1.VALUE AS REFERENCE FROM NI87.DBO.OEORDHO ORD1 
		 INNER JOIN NI87.DBO.OEORDH ORD ON ORD.ORDUNIQ = ORD1.ORDUNIQ

-- NI87.DBO.OEINVH INVO
                --INVO.INVNUMBER,INVO.PONUMBER,
                --INNER JOIN NI87.DBO.OEINVD INVD ON INVO.INVUNIQ = INVD.INVUNIQ
                --ON ORD.ORDNUMBER = INVO.ORDNUMBER
                --INNER JOIN NI87.DBO.OEORDHO ORD1 
               WHERE RTRIM(ORD1.OPTFIELD) = 'DTSREF' AND LEN(RTRIM(ORD1.VALUE)) >= 4
 		AND LEFT(ORD.ORDDATE,4) >= 2009
--INVD.QTYSHIPPED > 0 --AND INVO.INVDATE > 20101101
                
  		)INV
ON (INV.REFERENCE = OOA.RUN_NUMBER)
WHERE PO.PO_REF_DATE >= '06/01/2009' AND PO.PO_REF_DATE <= '12/31/2010'
AND OPB.PO_ORIGINAL_QTY > 0
)INV 
WHERE INV.INVREFERENCE = 'UNDEFINED'
GO
--------------------------------------------------------------------------------------------- 
USE NI87
GO

IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = 'V_Acc_Budget')
BEGIN
DROP VIEW  V_Acc_Budget ;
END
GO
CREATE VIEW V_Acc_Budget
AS


SELECT AC.* FROM NI87.DBO.ACBUDGET AC WHERE AC.FORECASTON = ANY(
SELECT MAX(FORECASTON) FROM NI87.DBO.ACBUDGET) 

UNION 
SELECT AC.* FROM NI87.DBO.ACBUDGET AC WHERE AC.FORECASTON = ANY(
SELECT MAX(FORECASTON) FROM NI87.DBO.ACBUDGET WHERE CAST(YR AS NUMERIC) = 2013)
AND CAST(YR AS NUMERIC) = 2013

UNION
SELECT AC.* FROM NI87.DBO.ACBUDGET AC WHERE AC.FORECASTON = ANY(
SELECT MAX(FORECASTON) FROM NI87.DBO.ACBUDGET WHERE CAST(YR AS NUMERIC) = 2012)
AND CAST(YR AS NUMERIC) = 2012
 

UNION 
SELECT AC.* FROM NI87.DBO.ACBUDGET AC WHERE AC.FORECASTON = ANY(
SELECT MAX(FORECASTON) FROM NI87.DBO.ACBUDGET WHERE CAST(YR AS NUMERIC) = 2011)
AND CAST(YR AS NUMERIC) = 2011
 

UNION 
SELECT AC.* FROM NI87.DBO.ACBUDGET AC WHERE AC.FORECASTON = ANY(
SELECT MAX(FORECASTON) FROM NI87.DBO.ACBUDGET WHERE CAST(YR AS NUMERIC) = 2010)
AND CAST(YR AS NUMERIC) = 2010
SELECT MAX(FORECASTON) FROM NI87.DBO.ACBUDGET WHERE CAST(YR AS NUMERIC) = 2010)
 
GO

----------------------------------------
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = 'V_BO_Pur_PO')
BEGIN 
  DROP VIEW V_BO_Pur_PO ;
END
GO
CREATE VIEW V_BO_Pur_PO
AS
SELECT PH.PONUMBER,PH.[DATE],PH.ISCOMPLETE,PH.VDCODE,PH.CURRENCY,PH.RATE,PH.TERMSCODE,PTB.DUENBRDAYS,
PD.PORLREV, PD.ITEMEXISTS,
OFH.[VALUE] AS Incoterms,
PD.ITEMNO, PD.LOCATION, PD.OQOUTSTAND,PD.EXTENDED,PD.EXPARRIVAL
, OFD.[VALUE] AS CountryCode
FROM POPORH1 PH INNER JOIN APRTB PTB ON PH.TERMSCODE = PTB.TERMSCODE INNER JOIN
POPORL PD ON PH.PORHSEQ = PD.PORHSEQ 

LEFT OUTER JOIN
POPORLO OFD ON PD.PORHSEQ = OFD.PORHSEQ AND PD.PORLREV = OFD.PORLREV AND (RTRIM(LTRIM(OFD.OPTFIELD)) = 'COUNTRYCODE')
LEFT OUTER JOIN
POPORHO OFH ON PH.PORHSEQ = OFH.PORHSEQ AND (RTRIM(LTRIM(OFH.OPTFIELD)) = 'INCOTERMS')
WHERE (PD.ITEMEXISTS = 1 AND PH.ISCOMPLETE = 0)

GO
---------------------------------------------------------------------------
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = 'V_BO_Pur_Receipt')
BEGIN 
  DROP VIEW V_BO_Pur_Receipt ;
END
GO
CREATE VIEW V_BO_Pur_Receipt
AS
--PORCPH1
SELECT POH.VENDS,POH.RCPNUMBER,POH.[DATE],POH.PONUMBER,POH.TERMSCODE,
--APRTB
PTB.DUENBRDAYS,
POH.CURRENCY,POH.RATE,POH.FISCYEAR,POH.FISCPERIOD, 
--PORCPL
POD.PORLSEQ,POD.ITEMEXISTS,POD.ITEMNO,POD.LOCATION,POD.RQRECEIVED,POD.EXTENDED,
--ICILOC
IC.STDCOST,
--POPORHO
OFH.[VALUE] AS Incoterms
--POPORLO
,OFD.[VALUE] AS CountryCode
FROM PORCPH1 POH INNER JOIN
PORCPL POD ON POH.RCPHSEQ = POD.RCPHSEQ INNER JOIN
APRTB PTB ON POH.TERMSCODE = PTB.TERMSCODE INNER JOIN
ICITEM ICI ON POD.ITEMNO = ICI.FMTITEMNO INNER JOIN
ICILOC IC ON ICI.ITEMNO = IC.ITEMNO AND POD.LOCATION = IC.LOCATION
LEFT OUTER JOIN
POPORLO OFD ON POD.RCPHSEQ = OFD.PORHSEQ AND POD.RCPLREV = OFD.PORLREV AND (RTRIM(LTRIM(OFD.OPTFIELD)) = 'COUNTRYCODE')
LEFT OUTER JOIN
POPORHO OFH ON POH.RCPHSEQ = OFH.PORHSEQ AND (RTRIM(LTRIM(OFH.OPTFIELD)) = 'INCOTERMS')

WHERE  (RTRIM(LTRIM(POH.FISCYEAR)) >= '2013') AND (POD.ITEMEXISTS = 1)

GO
----------------
USE Nufarm
GO
-------------------------------------------------------------
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = 'DELTIME')
BEGIN 
  DROP VIEW DELTIME ;
END
GO
CREATE VIEW DELTIME
AS

SELECT PO.DISTRIBUTOR_ID,DR.DISTRIBUTOR_NAME,DR.ADDRESS,TERR.TERRITORY_AREA,SH.SPPB_NO,GON.GON_NO,YEAR(GON.GON_DATE) AS [YEAR],
MONTH(GON.GON_DATE) AS [MONTH],DATEDIFF(DAY,GON.GON_DATE,GRB.RETURNED_GON_DATE)AS LEAD_TIME, GON.GON_DATE,GRB.RETURNED_GON_DATE AS RECEIVED_GON_DATE,GRB.IS_SIGNED AS HAS_SIGNED,
GRB.IS_STAMPED AS HAS_STAMPED,DGR.GON_RECEIVER AS ACCEPTED_BY
FROM ORDR_PURCHASE_ORDER PO INNER JOIN DIST_DISTRIBUTOR DR ON PO.DISTRIBUTOR_ID = DR.DISTRIBUTOR_ID

INNER JOIN TERRITORY TERR ON TERR.TERRITORY_ID = DR.TERRITORY_ID
INNER JOIN SPPB_HEADER SH ON SH.PO_REF_NO = PO.PO_REF_NO 
INNER JOIN(
SELECT SPPB_NO,'GON_NO' = CASE WHEN (GON_1_NO IS NOT NULL AND GON_1_NO != '') THEN GON_1_NO END,
'GON_DATE' = CASE WHEN (GON_1_DATE IS NOT NULL) THEN GON_1_DATE END
FROM SPPB_BRANDPACK

UNION 
SELECT SPPB_NO,'GON_NO' = CASE WHEN (GON_2_NO IS NOT NULL AND GON_2_NO != '') THEN GON_2_NO END,
'GON_DATE' = CASE WHEN (GON_2_DATE IS NOT NULL) THEN GON_2_DATE END
FROM SPPB_BRANDPACK

UNION
SELECT SPPB_NO,'GON_NO' = CASE WHEN (GON_3_NO IS NOT NULL AND GON_3_NO != '') THEN GON_3_NO END,
'GON_DATE' = CASE WHEN (GON_3_DATE IS NOT NULL) THEN GON_3_DATE END
FROM SPPB_BRANDPACK

UNION
SELECT SPPB_NO,'GON_NO' = CASE WHEN (GON_4_NO IS NOT NULL AND GON_4_NO != '') THEN GON_4_NO END,
'GON_DATE' = CASE WHEN (GON_4_DATE IS NOT NULL) THEN GON_4_DATE END
FROM SPPB_BRANDPACK

UNION
SELECT SPPB_NO,'GON_NO' = CASE WHEN (GON_5_NO IS NOT NULL AND GON_5_NO != '') THEN GON_5_NO END,
'GON_DATE' = CASE WHEN (GON_5_DATE IS NOT NULL) THEN GON_5_DATE END
FROM SPPB_BRANDPACK

UNION
SELECT SPPB_NO,'GON_NO' = CASE WHEN (GON_6_NO IS NOT NULL AND GON_6_NO != '') THEN GON_6_NO END,
'GON_DATE' = CASE WHEN (GON_6_DATE IS NOT NULL) THEN GON_6_DATE END
FROM SPPB_BRANDPACK
)GON ON GON.SPPB_NO = SH.SPPB_NO 
LEFT OUTER JOIN GON_RECEIVED_BACK GRB ON GRB.GON_NO = GON.GON_NO
AND SH.SPPB_NO = GRB.SPPB_NO
LEFT OUTER JOIN DIST_GON_RECEIVER DGR ON DGR.GR_ID = GRB.GON_ACCEPTED_BY
WHERE GON.GON_NO IS NOT NULL AND GON.GON_DATE IS NOT NULL
--AND GRB.RETURNED_GON_DATE >=  GON.GON_DATE
GO
-------------------------------------------------------------------------
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = 'UV_DIST_REGIONAL')
BEGIN 
  DROP VIEW UV_DIST_REGIONAL ;
END
GO
CREATE VIEW UV_DIST_REGIONAL
AS

SELECT DR.DISTRIBUTOR_ID,DR.DISTRIBUTOR_NAME,TER.TERRITORY_ID,TER.TERRITORY_AREA,TER.REGIONAL_ID,REG.REGIONAL_AREA
FROM DIST_DISTRIBUTOR DR INNER JOIN TERRITORY TER ON TER.TERRITORY_ID = DR.TERRITORY_ID
INNER JOIN DIST_REGIONAL REG ON TER.REGIONAL_ID = REG.REGIONAL_ID
GO

-----------------------------------------------------------------------
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = 'UV_TERRITORIAL')
BEGIN 
  DROP VIEW UV_TERRITORIAL ;
END
GO
CREATE VIEW UV_TERRITORIAL
AS
SELECT TER.TERRITORY_ID,TER.TERRITORY_AREA,TER.REGIONAL_ID,REG.REGIONAL_AREA,TER.INACTIVE
FROM TERRITORY TER INNER JOIN DIST_REGIONAL REG ON TER.REGIONAL_ID = REG.REGIONAL_ID
GO
-----------------------------------------------------------------------------------------------------
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = 'UV_REGIONAL')
BEGIN 
  DROP VIEW UV_REGIONAL ;
END
GO
CREATE VIEW UV_REGIONAL
AS
SELECT REGIONAL_ID,REGIONAL_AREA,INACTIVE FROM DIST_REGIONAL
GO
---------------------------------------------------------------------------------------------------

IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = 'UV_BRAND')
BEGIN 
  DROP VIEW UV_BRAND ;
END
GO
CREATE VIEW UV_BRAND
AS
SELECT BRAND_ID,BRAND_NAME,ISACTIVE,ISOBSOLETE FROM BRND_BRAND WHERE  BRAND_NAME NOT LIKE '%OTHER%' AND BRAND_NAME NOT LIKE '%SPECIALITY PRODUCKS%'
AND BRAND_NAME NOT LIKE '%NUTURF%' AND BRAND_NAME NOT LIKE '%GARBAGES%' AND BRAND_NAME NOT LIKE '%-E' AND BRAND_NAME NOT LIKE '%EXPORT'
GO

--SELECT * FROM View_agree_brand_Include WHERE Year(START_DATE) >= 2013 AND AGREEMENT_NO = '409/NI/I/2003.13'
--
--
--SELECT * FROM View_agree_brand_Include WHERE Year(START_DATE) >= 2013 AND AGREEMENT_NO = '01122/NI/XI/2009-1L.13' 
--
--SELECT COUNT(DISTRIBUTOR_ID)AS TOTAL_AGREE,AGREEMENT_NO  FROM DISTRIBUTOR_AGREEMENT
-- WHERE AGREEMENT_NO = ANY(SELECT AGREEMENT_NO FROM AGREE_AGREEMENT WHERE START_DATE >= '08/01/2013'
--AND END_DATE <= '07/31/2014')GROUP BY AGREEMENT_NO 

--Q
--SELECT DISTRIBUTOR_ID,BRAND_ID,
--PO_Q1 = ISNULL(SUM(CASE WHEN PO_REF_DATE >= '08/01/2013' AND PO_REF_DATE <= '10/31/2013' THEN PO_QTY END),0),
--PO_Q2 = ISNULL(SUM(CASE WHEN PO_REF_DATE >= '11/01/2013' AND PO_REF_DATE <= '01/31/2014' THEN PO_QTY END),0),
--PO_Q3 =  ISNULL(SUM(CASE WHEN PO_REF_DATE >= '02/01/2014' AND PO_REF_DATE <= '04/30/2014' THEN PO_QTY END),0),
--PO_Q4 =  ISNULL(SUM(CASE WHEN PO_REF_DATE >= '05/01/2014' AND PO_REF_DATE <= '07/31/2014' THEN PO_QTY END),0)
--FROM TEMPDB..##T_ORI_PO GROUP BY DISTRIBUTOR_ID,BRAND_ID

--S
--SELECT DISTRIBUTOR_ID,BRAND_ID,
--PO_S1 =  ISNULL(SUM(CASE WHEN PO_REF_DATE >= '08/01/2013' AND PO_REF_DATE <= '01/31/2014' THEN PO_QTY END),0),
--PO_S2 = ISNULL(SUM(CASE WHEN PO_REF_DATE >= '02/01/2014' AND PO_REF_DATE <= '07/31/2014' THEN PO_QTY END),0)
--FROM TEMPDB..##T_ORI_PO GROUP BY DISTRIBUTOR_ID,BRAND_ID

--TYPE OF SHARING TARGET----
--SELECT COUNT(AGREEMENT_NO)AS TOTAL_AGREE,AGREEMENT_NO  FROM DISTRIBUTOR_AGREEMENT
-- WHERE AGREEMENT_NO = ANY(SELECT AGREEMENT_NO FROM AGREE_AGREEMENT WHERE START_DATE >= '08/01/2013'
--AND END_DATE <= '07/31/2014')GROUP BY AGREEMENT_NO 

--UV_PO_BY_Q
--SELECT * FROM View_agree_brand_Include WHERE Year(START_DATE) >= 2013 AND AGREEMENT_NO = '409/NI/I/2003.13'
--
--
--SELECT * FROM View_agree_brand_Include WHERE Year(START_DATE) >= 2013 AND AGREEMENT_NO = '01122/NI/XI/2009-1L.13' 
--
--SELECT COUNT(DISTRIBUTOR_ID)AS TOTAL_AGREE,AGREEMENT_NO  FROM DISTRIBUTOR_AGREEMENT
-- WHERE AGREEMENT_NO = ANY(SELECT AGREEMENT_NO FROM AGREE_AGREEMENT WHERE START_DATE >= '08/01/2013'
--AND END_DATE <= '07/31/2014')GROUP BY AGREEMENT_NO 

--Q
--SELECT DISTRIBUTOR_ID,BRAND_ID,
--PO_Q1 = ISNULL(SUM(CASE WHEN PO_REF_DATE >= '08/01/2013' AND PO_REF_DATE <= '10/31/2013' THEN PO_QTY END),0),
--PO_Q2 = ISNULL(SUM(CASE WHEN PO_REF_DATE >= '11/01/2013' AND PO_REF_DATE <= '01/31/2014' THEN PO_QTY END),0),
--PO_Q3 =  ISNULL(SUM(CASE WHEN PO_REF_DATE >= '02/01/2014' AND PO_REF_DATE <= '04/30/2014' THEN PO_QTY END),0),
--PO_Q4 =  ISNULL(SUM(CASE WHEN PO_REF_DATE >= '05/01/2014' AND PO_REF_DATE <= '07/31/2014' THEN PO_QTY END),0)
--FROM TEMPDB..##T_ORI_PO GROUP BY DISTRIBUTOR_ID,BRAND_ID

--S
--SELECT DISTRIBUTOR_ID,BRAND_ID,
--PO_S1 =  ISNULL(SUM(CASE WHEN PO_REF_DATE >= '08/01/2013' AND PO_REF_DATE <= '01/31/2014' THEN PO_QTY END),0),
--PO_S2 = ISNULL(SUM(CASE WHEN PO_REF_DATE >= '02/01/2014' AND PO_REF_DATE <= '07/31/2014' THEN PO_QTY END),0)
--FROM TEMPDB..##T_ORI_PO GROUP BY DISTRIBUTOR_ID,BRAND_ID

--TYPE OF SHARING TARGET----
--SELECT COUNT(AGREEMENT_NO)AS TOTAL_AGREE,AGREEMENT_NO  FROM DISTRIBUTOR_AGREEMENT
-- WHERE AGREEMENT_NO = ANY(SELECT AGREEMENT_NO FROM AGREE_AGREEMENT WHERE START_DATE >= '08/01/2013'
--AND END_DATE <= '07/31/2014')GROUP BY AGREEMENT_NO 

--UV_PO_BY_Q
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = 'UV_PO_BY_Q')
--DROP VIEW UV_PO_BY_Q
--GO
--CREATE VIEW UV_PO_BY_Q
--AS
--SELECT PO.PO_REF_NO,PO.PO_REF_DATE,PO.DISTRIBUTOR_ID,ABP.BRAND_ID,BR.BRAND_NAME,ABP.BRANDPACK_ID,ABP.BRANDPACK_NAME,OOAB.OA_ORIGINAL_QTY AS PO_QTY
--FROM VIEW_AGREE_BRANDPACK_INCLUDE ABP 
--INNER JOIN Nufarm.dbo.ORDR_PO_BRANDPACK OPB ON OPB.BRANDPACK_ID = ABP.BRANDPACK_ID  
--INNER JOIN Nufarm.dbo.ORDR_PURCHASE_ORDER PO  
--ON PO.PO_REF_NO = OPB.PO_REF_NO AND PO.DISTRIBUTOR_ID = ABP.DISTRIBUTOR_ID
--INNER JOIN Nufarm.dbo.ORDR_ORDER_ACCEPTANCE OOA  
--ON OOA.PO_REF_NO = PO.PO_REF_NO  
--INNER JOIN ORDR_OA_BRANDPACK OOAB ON OOA.OA_ID = OOAB.OA_ID AND OOAB.PO_BRANDPACK_ID = OPB.PO_BRANDPACK_ID  
--INNER JOIN BRND_BRAND BR ON BR.BRAND_ID = ABP.BRAND_ID
--WHERE (ABP.START_DATE >= '08/01/2013' AND ABP.END_DATE <= '07/31/2014' AND ABP.QS_TREATMENT_FLAG = 'Q')
--AND (PO.PO_REF_DATE >= '08/01/2013' AND PO.PO_REF_DATE <= '07/31/2014' AND OPB.PO_ORIGINAL_QTY > 0)  
--AND PO.DISTRIBUTOR_ID = ANY(SELECT DISTRIBUTOR_ID FROM DISTRIBUTOR_AGREEMENT 
--WHERE AGREEMENT_NO =	ANY(SELECT AGREEMENT_NO FROM AGREE_AGREEMENT
--WHERE START_DATE >= '08/01/2013'AND END_DATE <= '07/31/2014'))
--GO

--UV_PO_BY_S
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = 'UV_PO_BY_S')
--DROP VIEW UV_PO_BY_S
--GO
--CREATE VIEW UV_PO_BY_S
--AS
--SELECT PO.PO_REF_NO,PO.PO_REF_DATE,PO.DISTRIBUTOR_ID,ABP.BRAND_ID,BR.BRAND_NAME,ABP.BRANDPACK_ID,ABP.BRANDPACK_NAME,OOAB.OA_ORIGINAL_QTY AS PO_QTY
--FROM VIEW_AGREE_BRANDPACK_INCLUDE ABP 
--INNER JOIN Nufarm.dbo.ORDR_PO_BRANDPACK OPB ON OPB.BRANDPACK_ID = ABP.BRANDPACK_ID  
--INNER JOIN Nufarm.dbo.ORDR_PURCHASE_ORDER PO  
--ON PO.PO_REF_NO = OPB.PO_REF_NO AND PO.DISTRIBUTOR_ID = ABP.DISTRIBUTOR_ID
--INNER JOIN Nufarm.dbo.ORDR_ORDER_ACCEPTANCE OOA  
--ON OOA.PO_REF_NO = PO.PO_REF_NO  
--INNER JOIN ORDR_OA_BRANDPACK OOAB ON OOA.OA_ID = OOAB.OA_ID AND OOAB.PO_BRANDPACK_ID = OPB.PO_BRANDPACK_ID  
--INNER JOIN BRND_BRAND BR ON BR.BRAND_ID = ABP.BRAND_ID
--WHERE (ABP.START_DATE >= '08/01/2013' AND ABP.END_DATE <= '07/31/2014' AND ABP.QS_TREATMENT_FLAG = 'S')
--AND (PO.PO_REF_DATE >= '08/01/2013' AND PO.PO_REF_DATE <= '07/31/2014' AND OPB.PO_ORIGINAL_QTY > 0)  
--AND PO.DISTRIBUTOR_ID = ANY(SELECT DISTRIBUTOR_ID FROM DISTRIBUTOR_AGREEMENT 
--WHERE AGREEMENT_NO =	ANY(SELECT AGREEMENT_NO FROM AGREE_AGREEMENT
--WHERE START_DATE >= '08/01/2013'AND END_DATE <= '07/31/2014'))
--GO

---UV_SUM_BY_Q_DPD
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = 'UV_SUM_BY_Q_DPD')
--DROP VIEW UV_SUM_BY_Q_DPD
--GO
--CREATE VIEW UV_SUM_BY_Q_DPD
--AS
--SELECT AB.DISTRIBUTOR_ID,AB.AGREEMENT_NO,AB.DISTRIBUTOR_NAME,'SHARE_TARGET' = CASE
--WHEN DA.TOTAL_AGREE > 1 THEN 'YESS' ELSE 'NO' END,AB.BRAND_NAME,
--AB.TARGET_Q1,FS.PO_Q1,AB.TARGET_Q2,FS.PO_Q2,AB.TARGET_Q3,FS.PO_Q3,AB.TARGET_Q4,FS.PO_Q4
--FROM VIEW_AGREE_BRAND_INCLUDE AB
-- INNER JOIN(
--			SELECT DISTRIBUTOR_ID,BRAND_ID,
--			PO_Q1 = ISNULL(SUM(CASE WHEN PO_REF_DATE >= '08/01/2013' AND PO_REF_DATE <= '10/31/2013' THEN PO_QTY END),0),
--			PO_Q2 = ISNULL(SUM(CASE WHEN PO_REF_DATE >= '11/01/2013' AND PO_REF_DATE <= '01/31/2014' THEN PO_QTY END),0),
--			PO_Q3 =  ISNULL(SUM(CASE WHEN PO_REF_DATE >= '02/01/2014' AND PO_REF_DATE <= '04/30/2014' THEN PO_QTY END),0),
--			PO_Q4 =  ISNULL(SUM(CASE WHEN PO_REF_DATE >= '05/01/2014' AND PO_REF_DATE <= '07/31/2014' THEN PO_QTY END),0)
--			FROM(
--					SELECT PO.PO_REF_NO,PO.PO_REF_DATE,PO.DISTRIBUTOR_ID,ABP.BRAND_ID,ABP.BRANDPACK_ID,OOAB.OA_ORIGINAL_QTY AS PO_QTY
--					FROM VIEW_AGREE_BRANDPACK_INCLUDE ABP 
--					INNER JOIN Nufarm.dbo.ORDR_PO_BRANDPACK OPB ON OPB.BRANDPACK_ID = ABP.BRANDPACK_ID  
--					INNER JOIN Nufarm.dbo.ORDR_PURCHASE_ORDER PO  
--					ON PO.PO_REF_NO = OPB.PO_REF_NO AND PO.DISTRIBUTOR_ID = ABP.DISTRIBUTOR_ID
--					INNER JOIN Nufarm.dbo.ORDR_ORDER_ACCEPTANCE OOA  
--					ON OOA.PO_REF_NO = PO.PO_REF_NO  
--					INNER JOIN ORDR_OA_BRANDPACK OOAB ON OOA.OA_ID = OOAB.OA_ID AND OOAB.PO_BRANDPACK_ID = OPB.PO_BRANDPACK_ID  
--					WHERE (ABP.START_DATE >= '08/01/2013' AND ABP.END_DATE <= '07/31/2014' AND ABP.QS_TREATMENT_FLAG = 'Q')
--					AND (PO.PO_REF_DATE >= '08/01/2013' AND PO.PO_REF_DATE <= '07/31/2014' AND OPB.PO_ORIGINAL_QTY > 0)  
--					AND PO.DISTRIBUTOR_ID = ANY(SELECT DISTRIBUTOR_ID FROM DISTRIBUTOR_AGREEMENT 
--                    WHERE AGREEMENT_NO =	ANY(SELECT AGREEMENT_NO FROM AGREE_AGREEMENT
--                    WHERE START_DATE >= '08/01/2013'AND END_DATE <= '07/31/2014'))
--				 )PO 
--				 GROUP BY DISTRIBUTOR_ID,BRAND_ID
--			 )FS
--ON FS.DISTRIBUTOR_ID = AB.DISTRIBUTOR_ID AND FS.BRAND_ID = AB.BRAND_ID 
--INNER JOIN(
--			SELECT COUNT(AGREEMENT_NO)AS TOTAL_AGREE,AGREEMENT_NO  FROM DISTRIBUTOR_AGREEMENT
--			 WHERE AGREEMENT_NO = ANY(SELECT AGREEMENT_NO FROM AGREE_AGREEMENT WHERE START_DATE >= '08/01/2013'
--			AND END_DATE <= '07/31/2014')GROUP BY AGREEMENT_NO 
--		  )DA 
--ON DA.AGREEMENT_NO = AB.AGREEMENT_NO
--WHERE AB.QS_TREATMENT_FLAG = 'Q'
--GO

--SELECT COUNT(AGREEMENT_NO)AS TOTAL_AGREE,AGREEMENT_NO  FROM DISTRIBUTOR_AGREEMENT
-- WHERE AGREEMENT_NO = ANY(SELECT AGREEMENT_NO FROM AGREE_AGREEMENT WHERE START_DATE >= '08/01/2013'
--AND END_DATE <= '07/31/2014')GROUP BY AGREEMENT_NO 

---UV_SUM_BY_Q_DPD
--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = 'UV_SUM_BY_S_DPD')
--DROP VIEW UV_SUM_BY_S_DPD
--GO
--CREATE VIEW UV_SUM_BY_S_DPD
--AS
--SELECT AB.DISTRIBUTOR_ID,AB.AGREEMENT_NO,AB.DISTRIBUTOR_NAME,'SHARE_TARGET' = CASE
-- WHEN DA.TOTAL_AGREE > 1 THEN 'YESS' ELSE 'NO' END,AB.BRAND_NAME,
--AB.TARGET_S1,FS.PO_S1,AB.TARGET_S2,FS.PO_S2
--FROM VIEW_AGREE_BRAND_INCLUDE AB
-- INNER JOIN(
--			SELECT DISTRIBUTOR_ID,BRAND_ID,
--			PO_S1 =  ISNULL(SUM(CASE WHEN (PO_REF_DATE >= '08/01/2013' AND PO_REF_DATE <= '01/31/2014') THEN PO_QTY END),0),
--			PO_S2 = ISNULL(SUM(CASE WHEN (PO_REF_DATE >= '02/01/2014' AND PO_REF_DATE <= '07/31/2014') THEN PO_QTY END),0)
--			FROM(
--					SELECT PO.PO_REF_NO,PO.PO_REF_DATE,PO.DISTRIBUTOR_ID,ABP.BRAND_ID,ABP.BRANDPACK_ID,OOAB.OA_ORIGINAL_QTY AS PO_QTY
--					FROM VIEW_AGREE_BRANDPACK_INCLUDE ABP 
--					INNER JOIN Nufarm.dbo.ORDR_PO_BRANDPACK OPB ON OPB.BRANDPACK_ID = ABP.BRANDPACK_ID  
--					INNER JOIN Nufarm.dbo.ORDR_PURCHASE_ORDER PO  
--					ON PO.PO_REF_NO = OPB.PO_REF_NO AND PO.DISTRIBUTOR_ID = ABP.DISTRIBUTOR_ID
--					INNER JOIN Nufarm.dbo.ORDR_ORDER_ACCEPTANCE OOA  
--					ON OOA.PO_REF_NO = PO.PO_REF_NO  
--					INNER JOIN ORDR_OA_BRANDPACK OOAB ON OOA.OA_ID = OOAB.OA_ID AND OOAB.PO_BRANDPACK_ID = OPB.PO_BRANDPACK_ID  
--					WHERE (ABP.START_DATE >= '08/01/2013' AND ABP.END_DATE <= '07/31/2014' AND ABP.QS_TREATMENT_FLAG = 'S')
--					AND (PO.PO_REF_DATE >= '08/01/2013' AND PO.PO_REF_DATE <= '07/31/2014' AND OPB.PO_ORIGINAL_QTY > 0)  
--					AND PO.DISTRIBUTOR_ID = ANY(SELECT DISTRIBUTOR_ID FROM DISTRIBUTOR_AGREEMENT 
--                    WHERE AGREEMENT_NO =	ANY(SELECT AGREEMENT_NO FROM AGREE_AGREEMENT
--                    WHERE START_DATE >= '08/01/2013'AND END_DATE <= '07/31/2014'))
--				 )PO 
--				 GROUP BY DISTRIBUTOR_ID,BRAND_ID
--			 )FS
--ON FS.DISTRIBUTOR_ID = AB.DISTRIBUTOR_ID AND FS.BRAND_ID = AB.BRAND_ID 
--INNER JOIN(
--			SELECT COUNT(AGREEMENT_NO)AS TOTAL_AGREE,AGREEMENT_NO  FROM DISTRIBUTOR_AGREEMENT
--			 WHERE AGREEMENT_NO = ANY(SELECT AGREEMENT_NO FROM AGREE_AGREEMENT WHERE START_DATE >= '08/01/2013'
--			AND END_DATE <= '07/31/2014')GROUP BY AGREEMENT_NO 
--		  )DA 
--ON DA.AGREEMENT_NO = AB.AGREEMENT_NO
--WHERE AB.QS_TREATMENT_FLAG = 'S' 
--GO

--IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = 'UV_SUM_BY_Y_DPD')
--DROP VIEW UV_SUM_BY_Y_DPD
--GO
--CREATE VIEW UV_SUM_BY_Y_DPD
--AS
--SELECT TER.REGIONAL_ID,REG.REGIONAL_AREA,AB.TERRITORY_ID,TER.TERRITORY_AREA,AB.DISTRIBUTOR_ID,AB.QS_TREATMENT_FLAG AS FLAG,AB.AGREEMENT_NO,AB.DISTRIBUTOR_NAME,'SHARE_TARGET' = CASE
-- WHEN DA.TOTAL_AGREE > 1 THEN 'YESS' ELSE 'NO' END,AB.BRAND_NAME,
--AB.TARGET_YEAR,FS.TOTAL_PO AS TOTAL_YEAR_PO
--FROM VIEW_AGREE_BRAND_INCLUDE AB
-- INNER JOIN(
--			SELECT DISTRIBUTOR_ID,BRAND_ID,
--			TOTAL_PO =  ISNULL(SUM(CASE WHEN (PO_REF_DATE >= '08/01/2013' AND PO_REF_DATE <= '07/31/2014') THEN PO_QTY END),0)
--			FROM(
--					SELECT PO.DISTRIBUTOR_ID,PO.PO_REF_NO,PO.PO_REF_DATE,ABP.BRAND_ID,ABP.BRANDPACK_ID,OOAB.OA_ORIGINAL_QTY AS PO_QTY
--					FROM VIEW_AGREE_BRANDPACK_INCLUDE ABP 
--					INNER JOIN Nufarm.dbo.ORDR_PO_BRANDPACK OPB ON OPB.BRANDPACK_ID = ABP.BRANDPACK_ID  
--					INNER JOIN Nufarm.dbo.ORDR_PURCHASE_ORDER PO  
--					ON PO.PO_REF_NO = OPB.PO_REF_NO AND PO.DISTRIBUTOR_ID = ABP.DISTRIBUTOR_ID
--					INNER JOIN Nufarm.dbo.ORDR_ORDER_ACCEPTANCE OOA  
--					ON OOA.PO_REF_NO = PO.PO_REF_NO  
--					INNER JOIN ORDR_OA_BRANDPACK OOAB ON OOA.OA_ID = OOAB.OA_ID AND OOAB.PO_BRANDPACK_ID = OPB.PO_BRANDPACK_ID  
--					INNER JOIN DIST_DISTRIBUTOR DR ON DR.DISTRIBUTOR_ID = PO.DISTRIBUTOR_ID 
--					INNER JOIN TERRITORY TER ON TER.TERRITORY_ID = DR.TERRITORY_ID 
--					INNER JOIN DIST_REGIONAL REG ON REG.REGIONAL_ID = TER.REGIONAL_ID
--					WHERE (ABP.START_DATE >= '08/01/2013' AND ABP.END_DATE <= '07/31/2014')
--					AND (PO.PO_REF_DATE >= '08/01/2013' AND PO.PO_REF_DATE <= '07/31/2014' AND OPB.PO_ORIGINAL_QTY > 0)  
--					AND PO.DISTRIBUTOR_ID = ANY(SELECT DISTRIBUTOR_ID FROM DISTRIBUTOR_AGREEMENT 
--                    WHERE AGREEMENT_NO =	ANY(SELECT AGREEMENT_NO FROM AGREE_AGREEMENT
--                    WHERE START_DATE >= '08/01/2013'AND END_DATE <= '07/31/2014'))
--				 )PO 
--				 GROUP BY DISTRIBUTOR_ID,BRAND_ID
--			 )FS
--ON FS.DISTRIBUTOR_ID = AB.DISTRIBUTOR_ID AND FS.BRAND_ID = AB.BRAND_ID 
--INNER JOIN(
--			SELECT COUNT(AGREEMENT_NO)AS TOTAL_AGREE,AGREEMENT_NO  FROM DISTRIBUTOR_AGREEMENT
--			 WHERE AGREEMENT_NO = ANY(SELECT AGREEMENT_NO FROM AGREE_AGREEMENT WHERE START_DATE >= '08/01/2013'
--			AND END_DATE <= '07/31/2014')GROUP BY AGREEMENT_NO 
--		  )DA 
--ON DA.AGREEMENT_NO = AB.AGREEMENT_NO
--INNER JOIN TERRITORY TER ON TER.TERRITORY_ID = AB.TERRITORY_ID
--INNER JOIN DIST_REGIONAL REG ON REG.REGIONAL_ID = TER.REGIONAL_ID
--WHERE AB.START_DATE >= '08/01/2013' AND AB.END_DATE <= '07/31/2014'
--GO

--IF EXISTS(SELECT [TABLE_NAME] FROM INFORMATION_SCHEMA.VIEWs WHERE [TABLE_NAME] = 'View_Target_By_Month_2015') 
--BEGIN
--DROP VIEW View_Target_By_Month_2015
--END
--GO
--CREATE VIEW View_Target_By_Month_2015
--AS
--SELECT DR.REGIONAL_AREA,ABI.DISTRIBUTOR_NAME,ABI.BRAND_NAME,ABI.TARGET_S1,[AUGUST] = ABI.TARGET_S1/6,[SEPTEMBER] = ABI.TARGET_S1/6,[OCTOBER] = ABI.TARGET_S1/6,[NOVEMBER] = ABI.TARGET_S1/6,
--[DECEMBER] = ABI.TARGET_S1/6,[JANUARY] = ABI.TARGET_S1/6,ABI.TARGET_S2,[PEBRUARY] = ABI.TARGET_S2/6,[MARCH] = ABI.TARGET_S2/6,[APRIL] = ABI.TARGET_S2/6,
--[MEI] = ABI.TARGET_S2/6,[JUNE] = ABI.TARGET_S2/6,[JULY] = TARGET_S2/6
--FROM VIEW_AGREE_BRAND_INCLUDE ABI INNER JOIN TERRITORY TER ON TER.TERRITORY_ID = ABI.TERRITORY_ID
--INNER JOIN DIST_REGIONAL DR ON DR.REGIONAL_ID = TER.REGIONAL_ID 
--WHERE ABI.QS_TREATMENT_FLAG = 'S'  AND ABI.END_DATE = '07/31/2015'
-- GO


-- IF EXISTS(SELECT [TABLE_NAME] FROM INFORMATION_SCHEMA.VIEWs WHERE [TABLE_NAME] = 'View_Target_By_Month_2014') 
--BEGIN
--DROP VIEW View_Target_By_Month_2014
--END
--GO
--CREATE VIEW View_Target_By_Month_2014
--AS
--SELECT DR.REGIONAL_AREA,ABI.DISTRIBUTOR_NAME,ABI.BRAND_NAME,ABI.TARGET_S1,[AUGUST] = ABI.TARGET_S1/6,[SEPTEMBER] = ABI.TARGET_S1/6,[OCTOBER] = ABI.TARGET_S1/6,[NOVEMBER] = ABI.TARGET_S1/6,
--[DECEMBER] = ABI.TARGET_S1/6,[JANUARY] = ABI.TARGET_S1/6,ABI.TARGET_S2,[PEBRUARY] = ABI.TARGET_S2/6,[MARCH] = ABI.TARGET_S2/6,[APRIL] = ABI.TARGET_S2/6,
--[MEI] = ABI.TARGET_S2/6,[JUNE] = ABI.TARGET_S2/6,[JULY] = TARGET_S2/6
--FROM VIEW_AGREE_BRAND_INCLUDE ABI INNER JOIN TERRITORY TER ON TER.TERRITORY_ID = ABI.TERRITORY_ID
--INNER JOIN DIST_REGIONAL DR ON DR.REGIONAL_ID = TER.REGIONAL_ID 
--WHERE ABI.QS_TREATMENT_FLAG = 'S'  AND ABI.END_DATE = '07/31/2014'
-- GO

IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = 'UV_PO_By_Month')
DROP VIEW UV_PO_By_Month
GO
CREATE VIEW UV_PO_By_Month
AS

SELECT TOP 50000 
QR.REGIONAL_ID,REG.REGIONAL_AREA,QR.TERRITORY_ID,TER.TERRITORY_AREA,QR.DISTRIBUTOR_ID,DR.DISTRIBUTOR_NAME,
QR.BRAND_ID,BR.BRAND_NAME,QR.BRANDPACK_ID,BB.BRANDPACK_NAME,QR.AUG,QR.SEP,QR.OCT,QR.NOV,QR.DEC,QR.JAN,QR.FEB,QR.MAR,QR.APR,QR.JUN,QR.JUL
FROM
(SELECT REGIONAL_ID,TERRITORY_ID,DISTRIBUTOR_ID,BRAND_ID,BRANDPACK_ID,
SUM(aug)AS AUG,SUM(sep) AS SEP,SUM(oct)AS OCT,SUM(nov) AS NOV,SUM([dec]) AS DEC,SUM(jan)AS JAN,SUM(feb) AS FEB,SUM(mar)AS MAR,SUM(apr)AS APR,SUM(may)AS MAY,SUM(jun)AS JUN,SUM(jul)AS JUL  
FROM(
SELECT TER.REGIONAL_ID,DR.TERRITORY_ID,OPO.DISTRIBUTOR_ID,BB.BRAND_ID,OPB.BRANDPACK_ID,OPB.PO_ORIGINAL_QTY,left(datename(month,OPO.PO_REF_DATE),3)as [month], OPO.PO_REF_DATE,
(CAST((OOB.QTY_EVEN)AS DECIMAL(18,3)) + CAST((SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC WHERE GQSY_SGT_P_FLAG = 'RMOA' AND OA_BRANDPACK_ID = OOB.OA_BRANDPACK_ID)AS DECIMAL(18,3))) AS OA_QTY,
(CAST((OOB.QTY_EVEN)AS DECIMAL(18,3)) + CAST((SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC WHERE GQSY_SGT_P_FLAG = 'RMOA' AND OA_BRANDPACK_ID = OOB.OA_BRANDPACK_ID)AS DECIMAL(18,3))) + 
OOB.AGREE_DISC_QTY + OOB.PROG_DISC_QTY + OOB.PROJ_DISC_QTY + OOB.OTHER_DISC_QTY AS TOTAL,
(CAST((OOB.QTY_EVEN)AS DECIMAL(18,3)) + CAST((SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC WHERE GQSY_SGT_P_FLAG = 'RMOA' AND OA_BRANDPACK_ID = OOB.OA_BRANDPACK_ID)AS DECIMAL(18,3))) * OOB.OA_PRICE_PERQTY AS TOTAL_AMOUNT_SALES
FROM ORDR_PURCHASE_ORDER OPO INNER JOIN DIST_DISTRIBUTOR DR ON OPO.DISTRIBUTOR_ID = DR.DISTRIBUTOR_ID
INNER JOIN ORDR_PO_BRANDPACK OPB ON OPO.PO_REF_NO = OPB.PO_REF_NO INNER JOIN ORDR_ORDER_ACCEPTANCE OOA
ON OOA.PO_REF_NO = OPO.PO_REF_NO INNER JOIN ORDR_OA_BRANDPACK OOB ON OOB.OA_ID = OOA.OA_ID
AND OPB.PO_BRANDPACK_ID = OOB.PO_BRANDPACK_ID INNER JOIN BRND_BRANDPACK BB ON OPB.BRANDPACK_ID = BB.BRANDPACK_ID
INNER JOIN TERRITORY TER ON TER.TERRITORY_ID = DR.TERRITORY_ID 
INNER JOIN BRND_BRAND BR ON BR.BRAND_ID = BB.BRAND_ID 
WHERE OPO.PO_REF_DATE >= '08/01/2014' AND OPO.PO_REF_DATE <= '07/31/2015' )QRY

PIVOT(SUM(PO_ORIGINAL_QTY) FOR [MONTH] IN(aug,sep,oct,nov,[dec],jan,feb,mar,apr,may,jun,jul))AS PVT
GROUP BY  REGIONAL_ID,TERRITORY_ID,DISTRIBUTOR_ID,BRAND_ID,BRANDPACK_ID
)QR
INNER JOIN DIST_REGIONAL REG ON QR.REGIONAL_ID = REG.REGIONAL_ID 
INNER JOIN TERRITORY TER ON TER.TERRITORY_ID = QR.TERRITORY_ID 
INNER JOIN DIST_DISTRIBUTOR DR ON QR.DISTRIBUTOR_ID = DR.DISTRIBUTOR_ID
INNER JOIN BRND_BRANDPACK BB ON QR.BRANDPACK_ID = BB.BRANDPACK_ID 
INNER JOIN BRND_BRAND BR ON BR.BRAND_ID = QR.BRAND_ID 
go


IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS WHERE [TABLE_NAME] = 'viewOABrandPackTemporary')
DROP VIEW viewOABrandPackTemporary
GO
CREATE VIEW viewOABrandPackTemporary
AS
SELECT OPO.DISTRIBUTOR_ID,DR.DISTRIBUTOR_NAME,OPO.PO_REF_NO,OPO.PO_REF_DATE,
OOA.OA_ID AS OA_REF_NO,OOA.OA_DATE,BB.BRANDPACK_NAME,OOB.OA_ORIGINAL_QTY ,OOB.QTY_EVEN,
OOB.OA_PRICE_PERQTY AS PRICE,OOB.UNIT,OOB.REMARK,OA_DISC.REMAIND_QTY,OA_DISC.GIVEN_AGREEMENT,OA_DISC.[QUARTER],
OA_DISC.[SEMESTER],OA_DISC.YEARLY,OA_DISC.RPK,OA_DISC.CP_MRT,OA_DISC.DK,OA_DISC.CP_D,OA_DISC.CP_DK,OA_DISC.PKPP,OA_DISC.CP_R,
OA_DISC.OTHER,(OA_DISC.GIVEN_AGREEMENT * OOB.OA_PRICE_PERQTY) AS GIVEN_AMOUNT,
(OA_DISC.[QUARTER]* OOB.OA_PRICE_PERQTY) AS QUARTER_AMOUNT,
(OA_DISC.[SEMESTER] * OOB.OA_PRICE_PERQTY) AS SEMESTER_AMOUNT,
(OA_DISC.[YEARLY] * OOB.OA_PRICE_PERQTY) AS YEARLY_AMOUNT,
(OA_DISC.RPK * OOB.OA_PRICE_PERQTY) AS RPK_AMOUNT,
(OA_DISC.DK * OOB.OA_PRICE_PERQTY) AS DK_AMOUNT,
(OA_DISC.CP_D * OOB.OA_PRICE_PERQTY) AS CP_D_AMOUNT,
(OA_DISC.CP_DK * OOB.OA_PRICE_PERQTY) AS CP_DK_AMOUNT,
(OA_DISC.PKPP * OOB.OA_PRICE_PERQTY) AS PKPP_AMOUNT,
(OA_DISC.CP_R * OOB.OA_PRICE_PERQTY) AS CP_R_AMOUNT,
(OA_DISC.OTHER * OOB.OA_PRICE_PERQTY) AS OTHER_AMOUNT,
(OA_DISC.CP_MRT * OOB.OA_PRICE_PERQTY) AS CP_MRT_AMOUNT, 
(OOB.QTY_EVEN + ISNULL(OA_LEFT.TOTAL_DISC,0)) * OOB.OA_PRICE_PERQTY AS OA_AMOUNT,
((T_DISC.TOTAL_DISC - ISNULL(ADJUST.ADJUST_QTY,0)) * OOB.OA_PRICE_PERQTY) AS TOTAL_DISC_AMOUNT,
ISNULL(ADJUST.ADJUST_QTY,0) AS ADJUST_QTY, ISNULL(ADJUST.ADJUST_QTY,0) * OOB.OA_PRICE_PERQTY AS ADJUST_AMOUNT
FROM ORDR_PURCHASE_ORDER OPO INNER JOIN DIST_DISTRIBUTOR DR ON OPO.DISTRIBUTOR_ID = DR.DISTRIBUTOR_ID
 INNER JOIN ORDR_PO_BRANDPACK OPB ON OPB.PO_REF_NO = OPO.PO_REF_NO INNER JOIN ORDR_ORDER_ACCEPTANCE OOA
ON OOA.PO_REF_NO = OPB.PO_REF_NO
INNER JOIN ORDR_OA_BRANDPACK OOB ON OOB.PO_BRANDPACK_ID = OPB.PO_BRANDPACK_ID AND OOB.OA_ID = OOA.OA_ID
INNER JOIN BRND_BRANDPACK BB ON OPB.BRANDPACK_ID = BB.BRANDPACK_ID --INNER JOIN ORDR_OA_BRANDPACK_DISC OOBD ON OOBD.OA_BRANDPACK_ID = OOB.OA_BRANDPACK_ID
LEFT OUTER JOIN
               (
                 SELECT OA_BRANDPACK_ID,
                 SUM(CASE GQSY_SGT_P_FLAG WHEN 'RMOA' THEN DISC_QTY ELSE 0 END)AS REMAIND_QTY,
                 SUM(CASE GQSY_SGT_P_FLAG WHEN 'G'  THEN DISC_QTY ELSE 0 END)AS GIVEN_AGREEMENT, 
            	 SUM(CASE GQSY_SGT_P_FLAG WHEN 'Q1' THEN DISC_QTY WHEN 'Q2' THEN DISC_QTY WHEN 'Q3' THEN DISC_QTY
                                     	  WHEN 'Q4' THEN DISC_QTY ELSE 0 END)AS [QUARTER],
				 SUM(CASE GQSY_SGT_P_FLAG WHEN 'S1' THEN DISC_QTY WHEN 'S2' THEN DISC_QTY ELSE 0 END)AS [SEMESTER], 
           		 SUM(CASE GQSY_SGT_P_FLAG WHEN 'Y'  THEN DISC_QTY ELSE 0 END)AS YEARLY, 
           		 SUM(CASE GQSY_SGT_P_FLAG WHEN 'MG' THEN DISC_QTY ELSE 0 END)AS RPK,
				 SUM(CASE GQSY_SGT_P_FLAG WHEN 'DK' THEN DISC_QTY WHEN 'DN' THEN DISC_QTY ELSE 0 END)AS DK,
           		 SUM(CASE GQSY_SGT_P_FLAG WHEN 'CP' THEN DISC_QTY  WHEN 'TD' THEN DISC_QTY WHEN 'CA' THEN DISC_QTY ELSE 0 END)AS CP_D,
				 SUM(CASE GQSY_SGT_P_FLAG WHEN 'CS' THEN DISC_QTY  WHEN 'TS' THEN DISC_QTY ELSE 0 END)AS CP_DK,
				 SUM(CASE GQSY_SGT_P_FLAG WHEN 'CT' THEN DISC_QTY WHEN 'CD' THEN DISC_QTY ELSE 0 END)AS CP_MRT,
				 SUM(CASE GQSY_SGT_P_FLAG WHEN 'KP' THEN DISC_QTY ELSE 0 END)AS PKPP,
				 SUM(CASE GQSY_SGT_P_FLAG WHEN 'CR' THEN DISC_QTY ELSE 0 END) AS CP_R,
				 SUM(CASE GQSY_SGT_P_FLAG WHEN 'O'  THEN DISC_QTY ELSE 0 END)AS OTHER
				 FROM ORDR_OA_BRANDPACK_DISC GROUP BY OA_BRANDPACK_ID
           	)OA_DISC ON OA_DISC.OA_BRANDPACK_ID = OOB.OA_BRANDPACK_ID
LEFT OUTER JOIN(
                 SELECT OA_BRANDPACK_ID,ISNULL(SUM(DISC_QTY),0)AS TOTAL_DISC FROM ORDR_OA_BRANDPACK_DISC 
                 WHERE GQSY_SGT_P_FLAG != 'RMOA'
                 GROUP BY OA_BRANDPACK_ID
                )T_DISC ON OOB.OA_BRANDPACK_ID = T_DISC.OA_BRANDPACK_ID
LEFT OUTER JOIN( 
                 SELECT OA_BRANDPACK_ID,ISNULL(SUM(DISC_QTY),0)AS TOTAL_DISC FROM ORDR_OA_BRANDPACK_DISC 
                 WHERE GQSY_SGT_P_FLAG = 'RMOA'
                 GROUP BY OA_BRANDPACK_ID
                )OA_LEFT ON OA_LEFT.OA_BRANDPACK_ID = OOB.OA_BRANDPACK_ID 
LEFT OUTER JOIN (
				SELECT OOBD.OA_BRANDPACK_ID,ISNULL(SUM(AT.ADJ_DISC_QTY),0) AS ADJUST_QTY FROM ORDR_OA_BRANDPACK_DISC OOBD INNER JOIN ADJUSTMENT_TRANS AT 
				ON AT.OA_BRANDPACK_DISC_ID = OOBD.OA_BRANDPACK_DISC_ID WHERE OOBD.OA_BRANDPACK_ID = ANY(SELECT OA_BRANDPACK_ID FROM ORDR_OA_BRANDPACK WHERE OA_ID = 'SAP/5021/09-2595')
				GROUP BY OOBD.OA_BRANDPACK_ID
				)ADJUST
ON ADJUST.OA_BRANDPACK_ID = OOB.OA_BRANDPACK_ID				
WHERE OOA.OA_ID = 'SAP/5021/09-2595'
GO

IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS WHERE [TABLE_NAME] = 'viewSales2018_2019')
DROP VIEW viewSales2018_2019
GO
CREATE VIEW viewSales2018_2019
AS
SELECT 'Total Penjualan' AS Periode_2018_2019,CONVERT(numeric(18,4),[1]) as JANUARI, CONVERT(numeric(18,4),[2]) as FEBRUARI, 
CONVERT(numeric(18,4),[3]) as MARET, CONVERT(numeric(18,4),[4]) as APRIL,
CONVERT(numeric(18,4),[5]) as MEI, CONVERT(numeric(18,4),[6]) as JUNI,
CONVERT(numeric(18,4),[7]) as JULI,
CONVERT(numeric(18,4),[8]) as AGUSTUS, CONVERT(numeric(18,4),[9]) as SEPTEMBER, CONVERT(numeric(18,4),[10]) as [OKTOBER], 
CONVERT(numeric(18,4),[11]) AS NOVEMBER, CONVERT(numeric(18,4),[12]) AS DESEMBER
FROM
(SELECT MONTH(PO.PO_REF_DATE)AS BULAN,PB.PO_ORIGINAL_QTY * PB.PO_PRICE_PERQTY AS TOTAL FROM ORDR_PO_BRANDPACK PB
INNER JOIN ORDR_PURCHASE_ORDER PO ON PO.PO_REF_NO = PB.PO_REF_NO WHERE PO.PO_REF_DATE >= '08/01/2018'
AND PO.PO_REF_DATE <= '07/31/2019')AS O
PIVOT(SUM(TOTAL) FOR BULAN IN([1],[2],[3],[4],[5],[6],[7],[8],[9],[10],[11],[12]))AS PVT
GO

IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS WHERE [TABLE_NAME] = 'viewSales2017_2018')
DROP VIEW viewSales2017_2018
GO
CREATE VIEW viewSales2017_2018
AS
SELECT 'Total Penjualan' AS Periode_2018_2019,CONVERT(numeric(18,4),[1]) as JANUARI, CONVERT(numeric(18,4),[2]) as FEBRUARI, 
CONVERT(numeric(18,4),[3]) as MARET, CONVERT(numeric(18,4),[4]) as APRIL,
CONVERT(numeric(18,4),[5]) as MEI, CONVERT(numeric(18,4),[6]) as JUNI,
CONVERT(numeric(18,4),[7]) as JULI,
CONVERT(numeric(18,4),[8]) as AGUSTUS, CONVERT(numeric(18,4),[9]) as SEPTEMBER, CONVERT(numeric(18,4),[10]) as [OKTOBER], 
CONVERT(numeric(18,4),[11]) AS NOVEMBER, CONVERT(numeric(18,4),[12]) AS DESEMBER
FROM
(SELECT MONTH(PO.PO_REF_DATE)AS BULAN,PB.PO_ORIGINAL_QTY * PB.PO_PRICE_PERQTY AS TOTAL FROM ORDR_PO_BRANDPACK PB
INNER JOIN ORDR_PURCHASE_ORDER PO ON PO.PO_REF_NO = PB.PO_REF_NO WHERE PO.PO_REF_DATE >= '08/01/2017'
AND PO.PO_REF_DATE <= '07/31/2018')AS O
PIVOT(SUM(TOTAL) FOR BULAN IN([1],[2],[3],[4],[5],[6],[7],[8],[9],[10],[11],[12]))AS PVT
GO

IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS WHERE [TABLE_NAME] = 'uv_gon_separated')
DROP VIEW uv_gon_separated
GO
CREATE VIEW uv_gon_separated
AS
SELECT GSD.IApp, DR.DISTRIBUTOR_NAME AS SHIP_TO_CUSTOMER,GSH.PO_NUMBER,GSH.SPPB_NUMBER,GSH.GON_NUMBER,GSH.PO_DATE,GSH.SPPB_DATE,GSH.GON_DATE,
CASE GSH.WARHOUSE WHEN 'SRG' THEN 'SERANG' WHEN 'SBY' THEN 'SURABAYA' WHEN 'JKT' THEN 'JAKARTA' WHEN 'MRK' THEN 'MERAK' WHEN 'TGR' THEN 'TANGERANG' ELSE 'UNKNOWN' END AS WARHOUSE,
GT.TRANSPORTER_NAME, GSH.POLICE_NO_TRANS,GSH.DRIVER_TRANS,BP.BRANDPACK_NAME AS GON_ITEM,CONVERT(VARCHAR(20),GSD.QTY) + BP.UNIT AS QUANTITY,GSD.COLLY_BOX,GSD.COLLY_PACKSIZE,GSD.BATCH_NO,
GSD.CreatedBy,GSD.CreatedDate,GSD.ModifiedBy,GSD.ModifiedDate 
FROM DIST_DISTRIBUTOR DR INNER JOIN GON_SEPARATED_HEADER GSH ON DR.DISTRIBUTOR_ID = GSH.SHIP_TO 
INNER JOIN GON_TRANSPORTER GT ON GT.GT_ID = GSH.TRANSPORTER INNER JOIN GON_SEPARATED_DETAIL GSD ON GSH.IDApp = GSD.FKApp
INNER JOIN BRND_BRANDPACK BP ON BP.BRANDPACK_ID = GSD.ITEM
GO