--SELECT * FROM ORDR_PO_BRANDPACK WHERE PO_REF_NO LIKE '%POSMP/1012/0054%'
--SELECT * FROM ORDR_PO_BRANDPACK WHERE PO_REF_NO LIKE '%POSMP/1012/0067%'

--SELECT DESCRIPTIONS,LEN(DESCRIPTIONS) AS JUMLAH FROM ORDR_PO_BRANDPACK WHERE [DESCRIPTIONS] IS NOT NULL

SET TRANSACTION ISOLATION LEVEL Read committed ;
GO
DECLARE @V_PO_PRICE_PERQTY DECIMAL(18,2),@V_DISTRIBUTOR_ID VARCHAR(10),@V_PO_REF_DATE SMALLDATETIME,
@V_PLANTATION_NAME VARCHAR(150),@V_PLANTATION_ID VARCHAR(50),@V_PO_BRANDPACK_ID VARCHAR(40) 

DECLARE CursorPlantation CURSOR FOR 
SELECT OPB.PO_BRANDPACK_ID,PO_REF_DATE,PO.DISTRIBUTOR_ID,SUBSTRING(OPB.DESCRIPTIONS,24,100)AS PLANTATION,
OPB.PO_PRICE_PERQTY FROM ORDR_PO_BRANDPACK OPB 
INNER JOIN ORDR_PURCHASE_ORDER PO ON OPB.PO_REF_NO = PO.PO_REF_NO 
WHERE OPB.PLANTATION_ID IS NULL
AND NOT EXISTS(SELECT PLANTATION_ID FROM PLANTATION WHERE PLANTATION_ID = OPB.PLANTATION_ID) 
AND LEN(OPB.DESCRIPTIONS) >= 24 
--AND OPB.DESCRIPTIONS != 'PRICE FROM FREE MARKET'
AND OPB.DESCRIPTIONS LIKE 'PRICE FROM PLANTATION%';

OPEN CursorPlantation ;
FETCH NEXT FROM CursorPlantation INTO @V_PO_BRANDPACK_ID,@V_PO_REF_DATE,@V_DISTRIBUTOR_ID,@V_PLANTATION_NAME,@V_PO_PRICE_PERQTY ;
WHILE (@@FETCH_STATUS = 0)
BEGIN
SET @V_PLANTATION_ID = (SELECT TOP 1 DPL.PLANTATION_ID FROM DIST_PLANT_PRICE DPL INNER JOIN PLANTATION PL ON PL.PLANTATION_ID = DPL.PLANTATION_ID
WHERE DPL.DISTRIBUTOR_ID = @V_DISTRIBUTOR_ID AND DPL.START_DATE <= @V_PO_REF_DATE
AND DPL.PRICE = @V_PO_PRICE_PERQTY
AND LTRIM(RTRIM(PL.PLANTATION_NAME)) = LTRIM(RTRIM(@V_PLANTATION_NAME)));
IF (@V_PLANTATION_ID IS NOT NULL)
	BEGIN UPDATE ORDR_PO_BRANDPACK SET PLANTATION_ID = @V_PLANTATION_ID WHERE PO_BRANDPACK_ID = @V_PO_BRANDPACK_ID ; END

FETCH NEXT FROM CursorPlantation INTO @V_PO_BRANDPACK_ID,@V_PO_REF_DATE,@V_DISTRIBUTOR_ID,@V_PLANTATION_NAME,@V_PO_PRICE_PERQTY ;
END
CLOSE CursorPlantation ;
DEALLOCATE CursorPlantation ;
GO
IF @@TRANCOUNT > 0
BEGIN COMMIT TRANSACTION ; END
GO


--SELECT OPB.PO_BRANDPACK_ID,PO.PO_REF_DATE,PO.DISTRIBUTOR_ID,DR.DISTRIBUTOR_NAME,SUBSTRING(OPB.DESCRIPTIONS,24,100)AS PLANTATION,
--OPB.PLANTATION_ID,OPB.PO_PRICE_PERQTY,OPB.PO_REF_NO,OPB.CREATE_DATE,OPB.CREATE_BY ,OPB.DESCRIPTIONS FROM ORDR_PO_BRANDPACK OPB 
--INNER JOIN ORDR_PURCHASE_ORDER PO ON OPB.PO_REF_NO = PO.PO_REF_NO 
--INNER JOIN DIST_DISTRIBUTOR DR ON DR.DISTRIBUTOR_ID = PO.DISTRIBUTOR_ID WHERE LEN(OPB.PLANTATION_ID) IS  NULL 
--AND NOT EXISTS(SELECT PLANTATION_ID FROM PLANTATION WHERE PLANTATION_ID = OPB.PLANTATION_ID)
--AND LEN(OPB.DESCRIPTIONS) >= 24 
--AND OPB.DESCRIPTIONS != 'PRICE FROM FREE MARKET'
--AND OPB.DESCRIPTIONS LIKE 'PRICE FROM PLANTATION%'


--SELECT TOP 1 DPL.PLANTATION_ID FROM DIST_PLANT_PRICE DPL INNER JOIN PLANTATION PL ON PL.PLANTATION_ID = DPL.PLANTATION_ID
--WHERE DPL.DISTRIBUTOR_ID = 'BIN012000' AND DPL.START_DATE <= CAST('2012-10-22 00:00:00.000' AS SMALLDATETIME)
--AND DPL.PRICE = CAST(38000.00 AS DECIMAL(18,2))
--AND LTRIM(RTRIM(PL.PLANTATION_NAME)) = LTRIM(RTRIM('PUTRA PELITA JAYA (CAHAYA SAMBAS), PD'))



--SELECT * FROM PLANTATION WHERE PLANTATION_NAME LIKE '%PUTRA PELITA JAYA (CAHAYA SAMBAS), PD%';

--SELECT * FROM PLANTATION WHERE PLANTATION_ID = '023-00576';

--SELECT * FROM ORDR_PO_BRANDPACK WHERE DESCRIPTIONS = 'PRICE FROM PLANTATION  LANGGAM HARMONI,PT'



--SET @V_PLANTATION_ID = (SELECT TOP 1 DPL.PLANTATION_ID FROM DIST_PLANT_PRICE DPL INNER JOIN PLANTATION PL ON PL.PLANTATION_ID = DPL.PLANTATION_ID
--WHERE DPL.DISTRIBUTOR_ID = @V_DISTRIBUTOR_ID AND DPL.START_DATE <= @V_PO_REF_DATE
--AND DPL.PRICE = @V_PO_PRICE_PERQTY
--AND LTRIM(RTRIM(PL.PLANTATION_NAME)) = LTRIM(RTRIM(@V_PLANTATION_NAME)));

--UPDATE ORDR_PO_BRANDPACK SET PLANTATION_ID = @V_PLANTATION_ID WHERE PO_BRANDPACK_ID = @V_PO_BRANDPACK_ID ;