IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE [COLUMN_NAME] = 'END_DATE' AND [TABLE_NAME] = 'BRND_DISC_HEADER')
BEGIN
ALTER TABLE BRND_DISC_HEADER ADD END_DATE SMALLDATETIME NULL
END
GO


IF EXISTS(SELECT NAME FROM SYS.OBJECTS WHERE NAME = 'Usp_Get_Schema_Distributor_History_Other_Detail' AND TYPE = 'P')
DROP PROCEDURE Usp_Get_Schema_Distributor_History_Other_Detail
GO
CREATE PROCEDURE Usp_Get_Schema_Distributor_History_Other_Detail
@DISTRIBUTOR_ID VARCHAR(10)
AS
SET NOCOUNT ON;
SELECT BD.PROGRAM_DESC,BD.APPLY_DATE,END_DATE,APPLY_TO = 'ALL DISTRIBUTOR',BDL.BRAND_ID,BR.BRAND_NAME,BDP.BRANDPACK_ID,
BP.BRANDPACK_NAME,BDP.MoreThanQty AS TargetPO,BDP.Disc
FROM BRND_DISC_HEADER BD INNER JOIN BRND_DISC_LIST_BRAND BDL ON BD.IDApp = BDL.FKApp
INNER JOIN BRND_DISC_LIST_BRANDPACK BDLP ON BDLP.FKApp = BD.IDApp
INNER JOIN BRND_BRANDPACK BP ON BP.BRANDPACK_ID = BDLP.BRANDPACK_ID
INNER JOIN BRND_DISC_PROG BDP ON BDP.FKApp = BD.IDApp AND BDP.BRANDPACK_ID = BDLP.BRANDPACK_ID
INNER JOIN BRND_BRAND BR ON BR.BRAND_ID = BDL.BRAND_ID  
WHERE BD.APPLY_TO = 'AL' 
UNION
SELECT BD.PROGRAM_DESC,BD.APPLY_DATE,END_DATE,APPLY_TO = 'CERTAIN DISTRIBUTOR',BDL.BRAND_ID,BR.BRAND_NAME,BDP.BRANDPACK_ID,
BP.BRANDPACK_NAME,BDP.MoreThanQty AS TargetPO,BDP.Disc
FROM BRND_DISC_HEADER BD INNER JOIN BRND_DISC_LIST_BRAND BDL ON BD.IDApp = BDL.FKApp
INNER JOIN BRND_DISC_LIST_BRANDPACK BDLP ON BDLP.FKApp = BD.IDApp
INNER JOIN BRND_BRANDPACK BP ON BP.BRANDPACK_ID = BDLP.BRANDPACK_ID
INNER JOIN BRND_DISC_PROG BDP ON BDP.FKApp = BD.IDApp AND BDP.BRANDPACK_ID = BDLP.BRANDPACK_ID
INNER JOIN BRND_BRAND BR ON BR.BRAND_ID = BDL.BRAND_ID
INNER JOIN DIST_DISC_BRAND_LIST DDBL ON DDBL.FKApp = BD.IDApp 
WHERE BD.APPLY_TO = 'CD'  AND DDBL.DISTRIBUTOR_ID = @DISTRIBUTOR_ID
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE [COLUMN_NAME] = 'PROGRAM_ID' AND [TABLE_NAME] = 'BRND_DISC_HEADER')
BEGIN
ALTER TABLE BRND_DISC_HEADER ADD PROGRAM_ID VARCHAR(30) NULL
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE [COLUMN_NAME] = 'BRAND_ID' AND [TABLE_NAME] = 'BRND_DISC_PROG')
BEGIN
ALTER TABLE BRND_DISC_PROG ADD BRAND_ID VARCHAR(7) NULL
END
GO