--add column TARGET1_FMP,

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE [COLUMN_NAME] = 'TARGET_FMP1' AND [TABLE_NAME] = 'AGREE_BRAND_INCLUDE')
BEGIN
ALTER TABLE AGREE_BRAND_INCLUDE ADD TARGET_FMP1 DECIMAL(18,3) NULL
END
GO
IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE [COLUMN_NAME] = 'TARGET_FMP2' AND [TABLE_NAME] = 'AGREE_BRAND_INCLUDE')
BEGIN
ALTER TABLE AGREE_BRAND_INCLUDE ADD TARGET_FMP2 DECIMAL(18,3) NULL
END
GO
IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE [COLUMN_NAME] = 'TARGET_FMP3' AND [TABLE_NAME] = 'AGREE_BRAND_INCLUDE')
BEGIN
ALTER TABLE AGREE_BRAND_INCLUDE ADD TARGET_FMP3 DECIMAL(18,3) NULL
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE [COLUMN_NAME] = 'TARGET_FMP_FM1' AND [TABLE_NAME] = 'AGREE_BRAND_INCLUDE')
BEGIN
ALTER TABLE AGREE_BRAND_INCLUDE ADD TARGET_FMP_FM1 DECIMAL(18,3) NULL
END
GO
IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE [COLUMN_NAME] = 'TARGET_FMP_FM2' AND [TABLE_NAME] = 'AGREE_BRAND_INCLUDE')
BEGIN
ALTER TABLE AGREE_BRAND_INCLUDE ADD TARGET_FMP_FM2 DECIMAL(18,3) NULL
END
GO
IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE [COLUMN_NAME] = 'TARGET_FMP_FM3' AND [TABLE_NAME] = 'AGREE_BRAND_INCLUDE')
BEGIN
ALTER TABLE AGREE_BRAND_INCLUDE ADD TARGET_FMP_FM3 DECIMAL(18,3) NULL
END
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE [COLUMN_NAME] = 'TARGET_FMP_PL1' AND [TABLE_NAME] = 'AGREE_BRAND_INCLUDE')
BEGIN
ALTER TABLE AGREE_BRAND_INCLUDE ADD TARGET_FMP_PL1 DECIMAL(18,3) NULL
END
GO
IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE [COLUMN_NAME] = 'TARGET_FMP_PL2' AND [TABLE_NAME] = 'AGREE_BRAND_INCLUDE')
BEGIN
ALTER TABLE AGREE_BRAND_INCLUDE ADD TARGET_FMP_PL2 DECIMAL(18,3) NULL
END
GO
IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE [COLUMN_NAME] = 'TARGET_FMP_PL3' AND [TABLE_NAME] = 'AGREE_BRAND_INCLUDE')
BEGIN
ALTER TABLE AGREE_BRAND_INCLUDE ADD TARGET_FMP_PL3 DECIMAL(18,3) NULL
END
GO

UPDATE AGREE_BRAND_INCLUDE SET TARGET_FMP1 = 0,TARGET_FMP2 = 0,TARGET_FMP3 = 0,TARGET_FMP_PL1 = 0,TARGET_FMP_PL2 = 0,TARGET_FMP_PL3 = 0,
TARGET_FMP_FM1 = 0,TARGET_FMP_FM2 = 0,TARGET_FMP_FM3 = 0
GO

ALTER TABLE AGREE_BRAND_INCLUDE ADD DEFAULT 0 FOR TARGET_FMP1;
ALTER TABLE AGREE_BRAND_INCLUDE ADD DEFAULT 0 FOR TARGET_FMP2;
ALTER TABLE AGREE_BRAND_INCLUDE ADD DEFAULT 0 FOR TARGET_FMP3;
ALTER TABLE AGREE_BRAND_INCLUDE ADD DEFAULT 0 FOR TARGET_FMP_FM1;
ALTER TABLE AGREE_BRAND_INCLUDE ADD DEFAULT 0 FOR TARGET_FMP_FM2;
ALTER TABLE AGREE_BRAND_INCLUDE ADD DEFAULT 0 FOR TARGET_FMP_FM3;
ALTER TABLE AGREE_BRAND_INCLUDE ADD DEFAULT 0 FOR TARGET_FMP_PL1;
ALTER TABLE AGREE_BRAND_INCLUDE ADD DEFAULT 0 FOR TARGET_FMP_PL2;
ALTER TABLE AGREE_BRAND_INCLUDE ADD DEFAULT 0 FOR TARGET_FMP_PL3;
GO
ALTER TABLE AGREE_BRAND_INCLUDE ALTER COLUMN TARGET_FMP1 DECIMAL(18,3) NOT NULL
ALTER TABLE AGREE_BRAND_INCLUDE ALTER COLUMN TARGET_FMP2 DECIMAL(18,3) NOT NULL
ALTER TABLE AGREE_BRAND_INCLUDE ALTER COLUMN TARGET_FMP3 DECIMAL(18,3) NOT NULL

ALTER TABLE AGREE_BRAND_INCLUDE ALTER COLUMN TARGET_FMP_PL1 DECIMAL(18,3) NOT NULL
ALTER TABLE AGREE_BRAND_INCLUDE ALTER COLUMN TARGET_FMP_PL2 DECIMAL(18,3) NOT NULL
ALTER TABLE AGREE_BRAND_INCLUDE ALTER COLUMN TARGET_FMP_PL3 DECIMAL(18,3) NOT NULL
GO
ALTER TABLE AGREE_BRAND_INCLUDE ALTER COLUMN TARGET_FMP_FM1 DECIMAL(18,3) NOT NULL
ALTER TABLE AGREE_BRAND_INCLUDE ALTER COLUMN TARGET_FMP_FM2 DECIMAL(18,3) NOT NULL
ALTER TABLE AGREE_BRAND_INCLUDE ALTER COLUMN TARGET_FMP_FM3 DECIMAL(18,3) NOT NULL
GO

IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = 'VIEW_AGREE_BRAND_INCLUDE')
DROP VIEW VIEW_AGREE_BRAND_INCLUDE
GO
CREATE VIEW VIEW_AGREE_BRAND_INCLUDE
AS
SELECT ABI.AGREE_BRAND_ID AS [ID],DR.TERRITORY_ID,DA.DISTRIBUTOR_ID,DR.DISTRIBUTOR_NAME,DA.AGREEMENT_NO,AA.QS_TREATMENT_FLAG,AA.AGREEMENT_DESC,
ABI.BRAND_ID,BR.BRAND_NAME,AA.START_DATE,AA.END_DATE,ABI.GIVEN_DISC_PCT AS [Given%],ABI.TARGET_Q1,
ABI.TARGET_Q2,ABI.TARGET_Q3,ABI.TARGET_Q4,ABI.TARGET_S1,ABI.TARGET_S2,ABI.TARGET_Q1_FM,ABI.TARGET_Q2_FM,ABI.TARGET_Q3_FM,ABI.TARGET_Q4_FM,ABI.TARGET_S1_FM,ABI.TARGET_S2_FM,
ABI.TARGET_Q1_PL,ABI.TARGET_Q2_PL,ABI.TARGET_Q3_PL,ABI.TARGET_Q4_PL,ABI.TARGET_S1_PL,ABI.TARGET_S2_PL,
ABI.TARGET_FMP1,ABI.TARGET_FMP2,ABI.TARGET_FMP3,ABI.TARGET_FMP_FM1,ABI.TARGET_FMP_FM2,ABI.TARGET_FMP_FM3,
ABI.TARGET_FMP_PL1,TARGET_FP2 =  ABI.TARGET_FMP2 +ABI.TARGET_FMP_PL2,
CASE AA.QS_TREATMENT_FLAG WHEN 'S' THEN (ABI.TARGET_S1 + ABI.TARGET_S2) WHEN 'Q' THEN (ABI.TARGET_Q1 + ABI.TARGET_Q2 + ABI.TARGET_Q3 + ABI.TARGET_Q4) ELSE 0 END AS TARGET_YEAR,
CASE AA.QS_TREATMENT_FLAG WHEN 'S' THEN (ABI.TARGET_S1_FM + ABI.TARGET_S2_FM) WHEN 'Q' THEN (ABI.TARGET_Q1_FM + ABI.TARGET_Q2_FM + ABI.TARGET_Q4_FM) ELSE 0 END AS TARGET_YEAR_FM,
CASE AA.QS_TREATMENT_FLAG WHEN 'S' THEN (ABI.TARGET_S1_PL + ABI.TARGET_S2_PL) WHEN 'Q' THEN (ABI.TARGET_Q1_PL + ABI.TARGET_Q2_PL + ABI.TARGET_Q3_PL + ABI.TARGET_Q4_PL) ELSE 0 END AS TARGET_YEAR_PL,
ABI.COMB_AGREE_BRAND_ID AS COMBINED_BRAND
FROM AGREE_BRAND_INCLUDE ABI INNER JOIN AGREE_AGREEMENT AA ON ABI.AGREEMENT_NO = AA.AGREEMENT_NO
INNER JOIN BRND_BRAND BR ON ABI.BRAND_ID = BR.BRAND_ID INNER JOIN DISTRIBUTOR_AGREEMENT DA
ON DA.AGREEMENT_NO = AA.AGREEMENT_NO INNER JOIN DIST_DISTRIBUTOR DR ON DR.DISTRIBUTOR_ID = DA.DISTRIBUTOR_ID
GO
SET ANSI_PADDING OFF

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ACHIEVEMENT_HEADER]') AND type in (N'U'))
BEGIN
	CREATE TABLE [dbo].[ACHIEVEMENT_HEADER](
		[IDApp] [int] IDENTITY(1,1) NOT NULL,
		[ACH_HEADER_ID] [varchar](55) NOT NULL,
		[DISTRIBUTOR_ID] [varchar](10) NOT NULL,
		[AGREEMENT_NO] [varchar](25) NOT NULL,
		[BRAND_ID] [varchar](7) NOT NULL,
		[FLAG] [varchar](4) NOT NULL,
		[TOTAL_TARGET] [decimal](18, 3) NOT NULL,
		[TARGET_FM] [decimal](18, 3) NOT NULL,
		[TARGET_PL] [decimal](18, 3) NOT NULL,
		[TARGET_VALUE] [decimal](18, 4) NOT NULL,
		[TOTAL_PO] [decimal](18, 3) NOT NULL,
		[TOTAL_PO_VALUE] [decimal](18, 4) NOT NULL,
		[TOTAL_ACTUAL] [decimal](18, 3) NOT NULL,
		[BALANCE] [decimal](18, 3) NOT NULL,
		[ACH_DISRO] [decimal](18, 4) NOT NULL,
		[DISPRO] [decimal](18, 4) NOT NULL,
		[DISC_QTY] [decimal](18, 3) NOT NULL,
		[TOTAL_PBQ1] [decimal](18, 3) NOT NULL,
		[TOTAL_PBQ2] [decimal](18, 3) NOT NULL,
		[TOTAL_PBQ3] [decimal](18, 3) NOT NULL,
		[TOTAL_CPQ2] [decimal](18, 3) NOT NULL,
		[TOTAL_CPQ3] [decimal](18, 3) NOT NULL,
		[TOTAL_CPF1] [decimal](18, 3) NOT NULL,
		[TOTAL_CPF2] [decimal](18, 3) NOT NULL,
		[TOTAL_PBF3] [decimal](18, 3) NOT NULL,
		[CreatedDate] [smalldatetime] NOT NULL,
		[CreatedBy] [varchar](100) NOT NULL,
		[ModifiedDate] [smalldatetime] NULL,
		[ModifiedBy] [varchar](100) NULL,
	 CONSTRAINT [PK_ACHIEVEMENT_HEADER_1] PRIMARY KEY CLUSTERED 
	(
		[ACH_HEADER_ID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY];

	ALTER TABLE [dbo].[ACHIEVEMENT_HEADER] ADD  CONSTRAINT [DF_ACHIEVEMENT_HEADER_AVG_PRICE_FM]  DEFAULT ((0)) FOR [AVG_PRICE_FM];

	ALTER TABLE [dbo].[ACHIEVEMENT_HEADER] ADD  CONSTRAINT [DF_ACHIEVEMENT_HEADER_AVG_PRICE_PL]  DEFAULT ((0)) FOR [AVG_PRICE_PL];

	ALTER TABLE [dbo].[ACHIEVEMENT_HEADER] ADD  CONSTRAINT [DF_ACHIEVEMENT_HEADER_TOTAL_TARGET]  DEFAULT ((0)) FOR [TOTAL_TARGET];

	ALTER TABLE [dbo].[ACHIEVEMENT_HEADER] ADD  CONSTRAINT [DF_ACHIEVEMENT_HEADER_TARGET_FM]  DEFAULT ((0)) FOR [TARGET_FM];


	ALTER TABLE [dbo].[ACHIEVEMENT_HEADER] ADD  CONSTRAINT [DF_ACHIEVEMENT_HEADER_TARGET_PL]  DEFAULT ((0)) FOR [TARGET_PL];


	ALTER TABLE [dbo].[ACHIEVEMENT_HEADER] ADD  CONSTRAINT [DF_ACHIEVEMENT_HEADER_TARGET_VALUE]  DEFAULT ((0)) FOR [TARGET_VALUE];


	ALTER TABLE [dbo].[ACHIEVEMENT_HEADER] ADD  CONSTRAINT [DF_ACHIEVEMENT_HEADER_TOTAL_PO]  DEFAULT ((0)) FOR [TOTAL_PO];


	ALTER TABLE [dbo].[ACHIEVEMENT_HEADER] ADD  CONSTRAINT [DF_ACHIEVEMENT_HEADER_TOTAL_PO_VALUE]  DEFAULT ((0)) FOR [TOTAL_PO_VALUE];


	ALTER TABLE [dbo].[ACHIEVEMENT_HEADER] ADD  CONSTRAINT [DF_ACHIEVEMENT_HEADER_TOTAL_ACTUAL]  DEFAULT ((0)) FOR [TOTAL_ACTUAL];


	ALTER TABLE [dbo].[ACHIEVEMENT_HEADER] ADD  CONSTRAINT [DF_ACHIEVEMENT_HEADER_BALANCE]  DEFAULT ((0)) FOR [BALANCE];


	ALTER TABLE [dbo].[ACHIEVEMENT_HEADER] ADD  CONSTRAINT [DF_ACHIEVEMENT_HEADER_ACH_DISRO]  DEFAULT ((0)) FOR [ACH_DISRO];


	ALTER TABLE [dbo].[ACHIEVEMENT_HEADER] ADD  CONSTRAINT [DF_ACHIEVEMENT_HEADER_DISPRO]  DEFAULT ((0)) FOR [DISPRO];


	ALTER TABLE [dbo].[ACHIEVEMENT_HEADER] ADD  CONSTRAINT [DF_ACHIEVEMENT_HEADER_DISC_QTY]  DEFAULT ((0)) FOR [DISC_QTY];


	ALTER TABLE [dbo].[ACHIEVEMENT_HEADER] ADD  CONSTRAINT [DF_ACHIEVEMENT_HEADER_TOTAL_PBQ1]  DEFAULT ((0)) FOR [TOTAL_PBQ1];


	ALTER TABLE [dbo].[ACHIEVEMENT_HEADER] ADD  CONSTRAINT [DF_ACHIEVEMENT_HEADER_TOTAL_PBQ2]  DEFAULT ((0)) FOR [TOTAL_PBQ2];


	ALTER TABLE [dbo].[ACHIEVEMENT_HEADER] ADD  CONSTRAINT [DF_ACHIEVEMENT_HEADER_TOTAL_PBQ3]  DEFAULT ((0)) FOR [TOTAL_PBQ3];

	ALTER TABLE [dbo].[ACHIEVEMENT_HEADER] ADD  CONSTRAINT [DF_ACHIEVEMENT_HEADER_TOTAL_CPQ2]  DEFAULT ((0)) FOR [TOTAL_CPQ2];


	ALTER TABLE [dbo].[ACHIEVEMENT_HEADER] ADD  CONSTRAINT [DF_ACHIEVEMENT_HEADER_TOTAL_CPQ3]  DEFAULT ((0)) FOR [TOTAL_CPQ3];


	ALTER TABLE [dbo].[ACHIEVEMENT_HEADER] ADD  CONSTRAINT [DF_ACHIEVEMENT_HEADER_TOTAL_CPF1]  DEFAULT ((0)) FOR [TOTAL_CPF1];

	ALTER TABLE [dbo].[ACHIEVEMENT_HEADER] ADD  CONSTRAINT [DF_ACHIEVEMENT_HEADER_TOTAL_CPF2]  DEFAULT ((0)) FOR [TOTAL_CPF2];


	ALTER TABLE [dbo].[ACHIEVEMENT_HEADER] ADD  CONSTRAINT [DF_ACHIEVEMENT_HEADER_TOTAL_PBF3]  DEFAULT ((0)) FOR [TOTAL_PBF3];


	--ALTER TABLE [dbo].[ACHIEVEMENT_HEADER]  WITH CHECK ADD  CONSTRAINT [FK_ACHIEVEMENT_HEADER_ACHIEVEMENT_HEADER] FOREIGN KEY([DISTRIBUTOR_ID])
	--REFERENCES [dbo].[DIST_DISTRIBUTOR] ([DISTRIBUTOR_ID]);


	--ALTER TABLE [dbo].[ACHIEVEMENT_HEADER] CHECK CONSTRAINT [FK_ACHIEVEMENT_HEADER_ACHIEVEMENT_HEADER];


	--ALTER TABLE [dbo].[ACHIEVEMENT_HEADER]  WITH CHECK ADD  CONSTRAINT [FK_ACHIEVEMENT_HEADER_ACHIEVEMENT_HEADER1] FOREIGN KEY([ACH_HEADER_ID])
	--REFERENCES [dbo].[ACHIEVEMENT_HEADER] ([ACH_HEADER_ID]);


	--ALTER TABLE [dbo].[ACHIEVEMENT_HEADER] CHECK CONSTRAINT [FK_ACHIEVEMENT_HEADER_ACHIEVEMENT_HEADER1];

	--ALTER TABLE [dbo].[ACHIEVEMENT_HEADER]  WITH CHECK ADD  CONSTRAINT [FK_ACHIEVEMENT_HEADER_AGREE_AGREEMENT] FOREIGN KEY([AGREEMENT_NO])
	--REFERENCES [dbo].[AGREE_AGREEMENT] ([AGREEMENT_NO]);


	--ALTER TABLE [dbo].[ACHIEVEMENT_HEADER] CHECK CONSTRAINT [FK_ACHIEVEMENT_HEADER_AGREE_AGREEMENT];


	--ALTER TABLE [dbo].[ACHIEVEMENT_HEADER]  WITH CHECK ADD  CONSTRAINT [FK_ACHIEVEMENT_HEADER_BRND_BRAND] FOREIGN KEY([BRAND_ID])
	--REFERENCES [dbo].[BRND_BRAND] ([BRAND_ID]);

	--ALTER TABLE [dbo].[ACHIEVEMENT_HEADER] CHECK CONSTRAINT [FK_ACHIEVEMENT_HEADER_BRND_BRAND];

	EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'DISTRIBUTOR_ID|AGREEMENT_NOBRAND_ID|FLAG' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ACHIEVEMENT_HEADER', @level2type=N'COLUMN',@level2name=N'ACH_HEADER_ID'

END
GO

SET ANSI_PADDING OFF
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[[ACHIEVEMENT_DETAIL]]') AND type in (N'U'))
BEGIN
	CREATE TABLE [dbo].[ACHIEVEMENT_DETAIL](
		[IDApp] [int] NOT NULL,
		[ACH_DETAIL_ID] [varchar](70) NOT NULL,
		[ACH_HEADER_ID] [varchar](55) NOT NULL,
		[BRANDPACK_ID] [varchar](14) NOT NULL,
		[TOTAL_PO] [decimal](18, 3) NOT NULL,
		[TOTAL_ACTUAL] [decimal](18, 3) NOT NULL,
		[DISC_QTY] [decimal](18, 3) NOT NULL,
		[TOTAL_CPQ1] [decimal](18, 3) NOT NULL,
		[TOTAL_CPQ2] [decimal](18, 3) NOT NULL,
		[TOTAL_CPQ3] [decimal](18, 3) NOT NULL,
		[TOTAL_CPF1] [decimal](18, 3) NOT NULL,
		[TOTAL_CPF2] [decimal](18, 3) NOT NULL,
		[TOTAL_PBF3] [decimal](18, 3) NOT NULL,
		[DESCRIPTIONS] [varchar](200) NULL,
		[CreatedDate] [smalldatetime] NOT NULL,
		[CreatedBy] [nchar](10) NOT NULL,
		[ModifiedDate] [smalldatetime] NULL,
		[ModifiedBy] [nchar](10) NULL,
	 CONSTRAINT [PK_ACHIEVEMENT_DETAIL_1] PRIMARY KEY CLUSTERED 
	(
		[ACH_DETAIL_ID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]


	ALTER TABLE [dbo].[ACHIEVEMENT_DETAIL] ADD  CONSTRAINT [DF_ACHIEVEMENT_DETAIL_TOTAL_PO]  DEFAULT ((0)) FOR [TOTAL_PO]

	ALTER TABLE [dbo].[ACHIEVEMENT_DETAIL] ADD  CONSTRAINT [DF_ACHIEVEMENT_DETAIL_TOTAL_ACTUAL]  DEFAULT ((0)) FOR [TOTAL_ACTUAL]

	ALTER TABLE [dbo].[ACHIEVEMENT_DETAIL] ADD  CONSTRAINT [DF_ACHIEVEMENT_DETAIL_DISC_QTY]  DEFAULT ((0)) FOR [DISC_QTY]

	ALTER TABLE [dbo].[ACHIEVEMENT_DETAIL] ADD  CONSTRAINT [DF_ACHIEVEMENT_DETAIL_TOTAL_CPQ1]  DEFAULT ((0)) FOR [TOTAL_CPQ1]

	ALTER TABLE [dbo].[ACHIEVEMENT_DETAIL] ADD  CONSTRAINT [DF_ACHIEVEMENT_DETAIL_TOTAL_CPQ2]  DEFAULT ((0)) FOR [TOTAL_CPQ2]

	ALTER TABLE [dbo].[ACHIEVEMENT_DETAIL] ADD  CONSTRAINT [DF_ACHIEVEMENT_DETAIL_TOTAL_CPQ3]  DEFAULT ((0)) FOR [TOTAL_CPQ3]

	ALTER TABLE [dbo].[ACHIEVEMENT_DETAIL] ADD  CONSTRAINT [DF_ACHIEVEMENT_DETAIL_TOTAL_CPF1]  DEFAULT ((0)) FOR [TOTAL_CPF1]

	ALTER TABLE [dbo].[ACHIEVEMENT_DETAIL] ADD  CONSTRAINT [DF_ACHIEVEMENT_DETAIL_TOTAL_CPF2]  DEFAULT ((0)) FOR [TOTAL_CPF2]

	ALTER TABLE [dbo].[ACHIEVEMENT_DETAIL] ADD  CONSTRAINT [DF_ACHIEVEMENT_DETAIL_TOTAL_PBF3]  DEFAULT ((0)) FOR [TOTAL_PBF3]

END
GO

IF EXISTS(SELECT NAME FROM [sys].[objects] WHERE NAME = 'Usp_Get_Total_Qty_Brand_By_Invoice' AND TYPE = 'P')
DROP PROCEDURE Usp_Get_Total_Qty_Brand_By_Invoice
GO
CREATE PROCEDURE Usp_Get_Total_Qty_Brand_By_Invoice---TANGGAL DI CONVERSI JADI DECIMAL TAHUN BULAN TANGGAL
@AGREEMENT_NO VARCHAR(32),
@START_DATE SMALLDATETIME,
@END_DATE SMALLDATETIME,
@COMPUTERNAME VARCHAR(100)
AS
--PRT003 Setting referer invoice ke referencePO di InvoiceHeader ReferencePO = 1,NomorPO = 0
SET DEADLOCK_PRIORITY NORMAL;SET NOCOUNT ON; SET ARITHABORT OFF ; SET ANSI_WARNINGS OFF ;
DECLARE @Statement NVARCHAR(3000);
IF (SELECT AllowRules FROM RefBussinesRules WHERE CodeApp = 'RPT003') = 1
BEGIN
   SET @Statement = 'SELECT DISTRIBUTOR_ID,BRAND_ID,ISNULL(SUM(QTY),0) AS TOTAL_INVOICE, ISNULL(SUM(PO_AMOUNT),0) AS PO_AMOUNT_DISTRIBUTOR,
					ISNULL(SUM(INV_AMOUNT),0) AS ACTUAL_AMOUNT_DISTRIBUTOR,ISNULL(SUM(PO_ORIGINAL_QTY),0)AS TOTAL_PO
  					FROM( SELECT PO.DISTRIBUTOR_ID,PO.BRAND_ID,PO.BRANDPACK_ID,(ISNULL(INVOICE.QTY,0)/ISNULL(PO.SPPB_QTY,0)) * PO.PO_ORIGINAL_QTY AS QTY,
					PO.PO_AMOUNT,INVOICE.INV_AMOUNT,PO.PO_ORIGINAL_QTY
					 FROM tempdb..##T_MASTER_PO_' + @COMPUTERNAME + ' PO
					 INNER JOIN (SELECT INV.PONUMBER,INV.REFERENCE,Tmbp.BRANDPACK_ID_DTS AS BRANDPACK_ID,INV.QTY,INV.INV_AMOUNT 
							  FROM ##T_SELECT_INVOICE_' + @COMPUTERNAME + ' INV INNER JOIN COMPARE_ITEM Tmbp 
							  ON INV.BRANDPACK_ID =  Tmbp.BRANDPACK_ID_ACCPAC AND INV.QTY > 0
    			       				 )INVOICE
					 ON PO.BRANDPACK_ID = INVOICE.BRANDPACK_ID
					 AND ((PO.PO_REF_NO = INVOICE.PONUMBER)OR(PO.RUN_NUMBER = INVOICE.REFERENCE))
					 WHERE PO.DISTRIBUTOR_ID = SOME( SELECT DISTRIBUTOR_ID FROM Nufarm.DBO.DISTRIBUTOR_AGREEMENT WHERE AGREEMENT_NO = @V_AGREEMENT_NO )
					 AND PO.PO_REF_DATE >= @V_START_DATE AND PO.PO_REF_DATE <= @V_END_DATE AND PO.IncludeDPD = ''YESS''
		       )INV
		   GROUP BY DISTRIBUTOR_ID,BRAND_ID
		   OPTION(KEEP PLAN);'
EXECUTE Sp_Executesql @Statement,N'@V_START_DATE SMALLDATETIME,@V_END_DATE SMALLDATETIME,@V_AGREEMENT_NO VARCHAR(100)',
		      @START_DATE,@END_DATE,@AGREEMENT_NO 
END 
GO

IF EXISTS(SELECT NAME FROM [sys].[objects] WHERE NAME = 'Usp_Get_Changed_Invoice_By_Brand_ID' AND TYPE = 'P')
DROP PROCEDURE Usp_Get_Changed_Invoice_By_Brand_ID
GO
CREATE PROCEDURE Usp_Get_Changed_Invoice_By_Brand_ID         
@AGREEMENT_NO VARCHAR(32),
@FLAG VARCHAR(2),
@START_DATE SMALLDATETIME,
@END_DATE SMALLDATETIME,
@COMPUTERNAME VARCHAR(100)
AS
--PRT003 Setting referer invoice ke referencePO di InvoiceHeader ReferencePO = 1,NomorPO = 0
DECLARE @Stmt nVARCHAR(1000);
SET DEADLOCK_PRIORITY NORMAL;SET NOCOUNT ON; SET ARITHABORT OFF ; SET ANSI_WARNINGS OFF ;
IF (SELECT AllowRules FROM RefBussinesRules WHERE CodeApp = 'RPT003') = 1
BEGIN
SET @Stmt = 'IF EXISTS(SELECT * FROM ( 	     
					SELECT ACH.DISTRIBUTOR_ID,ACH.BRAND_ID,ACH.TARGET,ISNULL(INV.TOTAL_INVOICE,0)AS TOTAL_INVOICE,INV.PO_AMOUNT_DISTRIBUTOR,
					INV.INV_AMOUNT_DISTRIBUTOR
		  			FROM Nufarm.DBO.ACCRUED_HEADER ACH
		  			INNER JOIN Tempdb..##T_Agreement_Brand_' + @COMPUTERNAME + ' INV
		  			ON ACH.BRAND_ID = INV.BRAND_ID AND ACH.DISTRIBUTOR_ID = INV.DISTRIBUTOR_ID  
		  			WHERE ACH.AGREEMENT_NO = @V_AGREEMENT_NO AND ACH.ACTUAL_DISTRIBUTOR <> CAST((ISNULL(INV.TOTAL_INVOICE,0))AS DECIMAL(18,3)) AND ACH.FLAG = @V_FLAG
				      )C)
	     BEGIN 
	     SELECT ACH.DISTRIBUTOR_ID,ACH.BRAND_ID,ACH.TARGET,ISNULL(INV.TOTAL_INVOICE,0)AS TOTAL_INVOICE,INV.PO_AMOUNT_DISTRIBUTOR,INV.ACTUAL_AMOUNT_DISTRIBUTOR,ACH.TARGET_FM,ACH.TARGET_PL,INV.TOTAL_PO
		FROM Nufarm.DBO.ACCRUED_HEADER ACH
		LEFT OUTER JOIN Tempdb..##T_Agreement_Brand_' + @COMPUTERNAME + ' INV
		ON ACH.BRAND_ID = INV.BRAND_ID AND ACH.DISTRIBUTOR_ID = INV.DISTRIBUTOR_ID  
		WHERE ACH.AGREEMENT_NO = @V_AGREEMENT_NO AND ACH.FLAG = @V_FLAG ;
	     END' ;
    EXECUTE Sp_executesql @Stmt,N'@V_AGREEMENT_NO VARCHAR(100),@V_FLAG VARCHAR(2)',
				       @AGREEMENT_NO,@FLAG

END
GO 