IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Get_Target_DPD_FMP_Roundup' AND TYPE = 'P')
DROP PROCEDURE Usp_Get_Target_DPD_FMP_Roundup
GO
CREATE PROCEDURE Usp_Get_Target_DPD_FMP_Roundup
@START_DATE SMALLDATETIME,@END_DATE SMALLDATETIME
AS
SET NOCOUNT ON;
SELECT TER.TERRITORY_AREA,DR.DISTRIBUTOR_ID,DR.DISTRIBUTOR_NAME,AA.AGREEMENT_NO,AA.END_DATE,ABI.BRAND_ID,BN.BRAND_NAME,
PS_GROUP = CASE WHEN ABI.BRAND_ID = '00601' THEN 'SMALL PACK SIZE'--BIOSORB
				WHEN ABI.BRAND_ID = '0060200' THEN 'SMALL PACK SIZE'--BIOSORB
				WHEN ABI.BRAND_ID = '00604' THEN 'SMALL PACK SIZE'--BIOSORB

				WHEN ABI.BRAND_ID = '00681' THEN 'SMALL PACK SIZE'--POWER MAX
				WHEN ABI.BRAND_ID = '00684' THEN 'SMALL PACK SIZE'--POWER MAX

				WHEN ABI.BRAND_ID = '007801' THEN 'SMALL PACK SIZE'--TRANSORB
				WHEN ABI.BRAND_ID = '007804' THEN 'SMALL PACK SIZE'--TRANSORB
				WHEN ABI.BRAND_ID = '0078200' THEN 'SMALL PACK SIZE'--TRANSORB

				WHEN ABI.BRAND_ID = '006820' THEN 'BIG PACK SIZE'--POWER MAX
				WHEN ABI.BRAND_ID = '007820' THEN 'BIG PACK SIZE'--TRANSORB
				WHEN ABI.BRAND_ID = '006820' THEN 'BIG PACK SIZE'--BIOSORB
				ELSE 'UNKNOWN PACK SIZE'
		   END,
PROD_CATEGORY = CASE WHEN CHARINDEX('POWERMAX',BN.BRAND_NAME) > 0 THEN 'ROUNDUP POWERMAX'
					 WHEN CHARINDEX('TRANSORB',BN.BRAND_NAME) > 0 THEN 'ROUNDUP TRANSORB'
					 WHEN CHARINDEX('ROUNDUP',BN.BRAND_NAME) > 0 THEN 'ROUNDUP BIOSORB'
					 ELSE 'UNKNOW CATEGORY'
				END,
ISCombined = CASE 
                 WHEN ABI.COMB_AGREE_BRAND_ID IS NOT NULL THEN 'YES'
                 ELSE 'NO'
			 END,
ABI.TARGET_FMP1,ABI.TARGET_FMP2,ABI.TARGET_FMP3,(ABI.TARGET_FMP1 + ABI.TARGET_FMP2 + ABI.TARGET_FMP3) AS TARGET_YEAR_FMP,
ABI.TARGET_FMP_FM1,ABI.TARGET_FMP_FM1 * AVGP.AVGPRICE AS TARGET_FMP_FM1_VALUE,ABI.TARGET_FMP_FM2,ABI.TARGET_FMP_FM2 * AVGP.AVGPRICE AS TARGET_FMP_FM2_VALUE,
ABI.TARGET_FMP_FM3,ABI.TARGET_FMP_FM3 * AVGP.AVGPRICE AS TARGET_FMP_FM3_VALUE,
ABI.TARGET_FMP_PL1,ABI.TARGET_FMP_PL1 * AVGP.AVGPRICE AS TARGET_FMP_PL1_VALUE,ABI.TARGET_FMP_PL2,
ABI.TARGET_FMP_PL2 * AVGP.AVGPRICE AS TARGET_FMP_PL2_VALUE,
ABI.TARGET_FMP_PL3,ABI.TARGET_FMP_PL3 * AVGP.AVGPRICE AS TARGET_FMP_PL3_VALUE,

ABI.TARGET_FMP_FM1 + ABI.TARGET_FMP_FM2 + ABI.TARGET_FMP_FM3 AS TARGET_YEAR_FM_VALUE,
ABI.TARGET_FMP_PL1 + ABI.TARGET_FMP_PL2 + ABI.TARGET_FMP_PL3 AS TARGET_YEAR_PL_VALUE,
ABI.CREATE_DATE,ABI.CREATE_BY,ABI.MODIFY_BY,ABI.MODIFY_DATE 
FROM DIST_DISTRIBUTOR DR INNER JOIN DISTRIBUTOR_AGREEMENT DA ON DR.DISTRIBUTOR_ID = DA.DISTRIBUTOR_ID
INNER JOIN AGREE_AGREEMENT AA ON DA.AGREEMENT_NO = AA.AGREEMENT_NO
INNER JOIN AGREE_BRAND_INCLUDE ABI ON AA.AGREEMENT_NO = ABI.AGREEMENT_NO
INNER JOIN BRND_BRAND BN ON BN.BRAND_ID = ABI.BRAND_ID
INNER JOIN TERRITORY TER ON TER.TERRITORY_ID = DR.TERRITORY_ID
LEFT OUTER JOIN(
SELECT BRAND_ID,AVGPRICE,AVGPRICE_PL, START_PERIODE FROM BRND_AVGPRICE WHERE START_PERIODE >= @START_DATE
 )AVGP
 ON AVGP.START_PERIODE = AA.START_DATE AND AVGP.BRAND_ID = ABI.BRAND_ID
 AND BN.BRAND_ID = AVGP.BRAND_ID
WHERE AA.START_DATE >= @START_DATE AND AA.END_DATE <= @END_DATE
AND AA.QS_TREATMENT_FLAG IN('Q','F')
AND BN.BRAND_NAME LIKE 'ROUNDUP%'

--SELECT * FROM BRND_BRAND WHERE BRAND_NAME LIKE '%ROUNDUP%'

--SELECT CHARINDEX('LINDOMIN','ROUNDUP POWERMAX 660 SL - 01')