select * from ordr_po_brandpack where po_ref_no = '4616/Pes.PANL/IX/2009'


select * from ordr_po_brandpack where po_ref_no LIKE '%BNB/VII%'
SELECT * FROM ORDR_ORDER_ACCEPTANCE WHERE OA_ID LIKE '4604/Pes.PANL/IX/2009%'

SELECT * FROM ORDR_OA_BRANDPACK WHERE OA_ID = 'PO/TO/2009/06/0036-2595'




BEGIN
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRANSACTION 
DELETE FROM ORDR_OA_BRANDPACK_DISC WHERE OA_BRANDPACK_ID LIKE '4604/PES.PANL/IX/2009-2941%'

IF (@@ERROR <= 0)
    BEGIN
	
	DELETE FROM DO_TP_DETAIL WHERE OA_BRANDPACK_ID LIKE '4604/PES.PANL/IX/2009-2941%'

	DELETE FROM DO_TP_HEADER WHERE DO_TP_NO NOT IN(SELECT DO_TP_NO FROM DO_TP_DETAIL)

	DELETE FROM OTP_DETAIL WHERE OA_BRANDPACK_ID LIKE '4604/PES.PANL/IX/2009-2941%'
	DELETE FROM ORDR_OTP_HEADER WHERE OTP_NO NOT IN(SELECT OTP_NO FROM OTP_DETAIL)

	DELETE FROM SPPB_BRANDPACK WHERE OA_BRANDPACK_ID LIKE '4604/PES.PANL/IX/2009-2941%'
	DELETE FROM SPPB_HEADER WHERE PO_REF_NO = '4604/PES.PANL/IX/2009'

	DELETE FROM ORDR_OA_REMAINDING WHERE OA_BRANDPACK_ID LIKE '4604/PES.PANL/IX/2009-2941%'
	DELETE FROM MRKT_DISC_HISTORY WHERE OA_BRANDPACK_ID LIKE '4604/PES.PANL/IX/2009-2941%'
	
	DELETE FROM AGREE_DISC_HISTORY WHERE OA_BRANDPACK_ID LIKE '4604/PES.PANL/IX/2009-2941%'
	
 	DELETE FROM ORDR_OA_BRANDPACK WHERE OA_ID = '4604/PES.PANL/IX/2009-2941'
       
        DELETE FROM ORDR_ORDER_ACCEPTANCE WHERE OA_ID = '4604/PES.PANL/IX/2009-2941'

        DELETE FROM ORDR_PO_BRANDPACK WHERE PO_BRANDPACK_ID LIKE '4604/PES.PANL/IX/2009-2941%'

        DELETE FROM ORDR_PURCHASE_ORDER WHERE PO_REF_NO = '4604/PES.PANL/IX/2009'	
	IF (@@ERROR <= 0)
	   BEGIN
		
		COMMIT TRANSACTION
	   END
	else
	 begin
	     rollback transaction
 	end

    END
else
	rollback transaction
END

