IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Select_QTY_PO_BRANDPACK' AND TYPE = 'P')
DROP PROCEDURE Sp_Select_QTY_PO_BRANDPACK
GO
CREATE PROCEDURE Sp_Select_QTY_PO_BRANDPACK
@PO_BRANDPACK_ID VARCHAR(39),
@OA_ID VARCHAR(30),
@O_PO_ORIGINAL_QTY FLOAT OUTPUT,
@O_OA_ORIGINAL_QTY FLOAT OUTPUT,
@O_PRICE float OUTPUT,
@O_LEFT_QTY FLOAT OUTPUT,
@O_UNIT VARCHAR(10) OUTPUT
AS
BEGIN
  DECLARE @PO_REF_DATE DATETIME, @PRICE FLOAT,@START_DATE DATETIME
   	SET @PO_REF_DATE = CAST((SELECT ORDR_PURCHASE_ORDER.PO_REF_DATE FROM ORDR_PURCHASE_ORDER 
			   INNER JOIN  ORDR_PO_BRANDPACK ON ORDR_PURCHASE_ORDER.PO_REF_NO = ORDR_PO_BRANDPACK.PO_REF_NO
			   WHERE ORDR_PO_BRANDPACK.PO_BRANDPACK_ID = @PO_BRANDPACK_ID) AS DATETIME)
	SELECT PO_REF_DATE = @PO_REF_DATE
	SET @O_UNIT = (SELECT RIGHT(UNIT,5) FROM BRND_BRANDPACK WHERE BRANDPACK_ID = 
	(SELECT BRANDPACK_ID FROM ORDR_PO_BRANDPACK WHERE PO_BRANDPACK_ID = @PO_BRANDPACK_ID))--OORDR_OA_BRANDPACK WHERE OA_ID = @OA_ID)
	
	--DECLARE PRICE_CURSOR SCROLL CURSOR FOR
	SET @O_PRICE = (SELECT TOP 1 PRICE FROM BRND_PRICE_HISTORY WHERE BRANDPACK_ID = (SELECT BRANDPACK_ID
	FROM ORDR_PO_BRANDPACK WHERE PO_BRANDPACK_ID = @PO_BRANDPACK_ID) AND START_DATE <= @PO_REF_DATE
	ORDER BY START_DATE DESC)
	
		
      	IF EXISTS(SELECT PO_BRANDPACK_ID FROM ORDR_OA_BRANDPACK WHERE PO_BRANDPACK_ID = @PO_BRANDPACK_ID) 
           BEGIN
	       SET @O_OA_ORIGINAL_QTY = CAST((SELECT SUM(OA_ORIGINAL_QTY) FROM ORDR_OA_BRANDPACK WHERE PO_BRANDPACK_ID = @PO_BRANDPACK_ID)AS DECIMAL(10,3))
	       SET @O_PO_ORIGINAL_QTY = CAST((SELECT PO_ORIGINAL_QTY FROM ORDR_PO_BRANDPACK WHERE PO_BRANDPACK_ID = @PO_BRANDPACK_ID) AS DECIMAL(10,3)) 	
    	       SET @O_LEFT_QTY = (@O_PO_ORIGINAL_QTY - @O_OA_ORIGINAL_QTY)
	
           END
        ELSE
            BEGIN
 	         SET @O_PO_ORIGINAL_QTY = (SELECT PO_ORIGINAL_QTY FROM ORDR_PO_BRANDPACK WHERE PO_BRANDPACK_ID = @PO_BRANDPACK_ID)
	         SET @O_LEFT_QTY = @O_PO_ORIGINAL_QTY  
                 
 	    END
END
RETURN(1)
GO
----------------------------------------------------------------------------------------------------------------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_HasGenerated_MRK_OA_BRANDPACK_ID' AND TYPE = 'P')
DROP PROCEDURE Sp_HasGenerated_MRK_OA_BRANDPACK_ID
GO
CREATE PROCEDURE Sp_HasGenerated_MRK_OA_BRANDPACK_ID
@OA_BRANDPACK_ID VARCHAR(70),
@SGT_FLAG VARCHAR(5)
AS
BEGIN
IF (@SGT_FLAG IS NULL)
    BEGIN
    	IF EXISTS(SELECT OA_BRANDPACK_ID FROM MRKT_DISC_HISTORY WHERE OA_BRANDPACK_ID = @OA_BRANDPACK_ID
	   AND SGT_FLAG IS NULL)
	   RETURN(1)
    END
ELSE IF EXISTS(SELECT OA_BRANDPACK_ID FROM MRKT_DISC_HISTORY WHERE OA_BRANDPACK_ID = @OA_BRANDPACK_ID
AND SGT_FLAG = @SGT_FLAG)
    RETURN(2)
ELSE
    RETURN(0)
END
GO
-------------------------------------------------------------------------------------------------------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_GetSumPrice_Given_by_OA' AND TYPE = 'P')
DROP PROCEDURE Sp_GetSumPrice_Given_by_OA
GO
CREATE PROCEDURE Sp_GetSumPrice_Given_by_OA
@OA_ID VARCHAR(30),
@SUMPRICE FLOAT OUTPUT
AS
SET NOCOUNT ON
--DECLARE @V_DISC_QTY FLOAT,@V_OA_PRICE_PRQTY FLOAT
--SET @SUMPRICE = 0
BEGIN
	--DECLARE CURSOR_SUMPRICE CURSOR FOR
	--SELECT DISC_QTY,PRICE_PRQTY FROM ORDR_OA_BRANDPACK,ORDR_OA_BRANDPACK_DISC
	---WHERE ORDR_OA_BRANDPACK_DISC.OA_BRANDPACK_ID = ORDR_OA_BRANDPACK.OA_BRANDPACK_ID
	--AND ORDR_OA_BRANDPACK.OA_ID = @OA_ID AND ORDR_OA_BRANDPACK_DISC.GQSY_SGT_P_FLAG != 'RMOA'
	--OPEN CURSOR_SUMPRICE
	--FETCH NEXT FROM CURSOR_SUMPRICE INTO @V_DISC_QTY,@V_OA_PRICE_PRQTY
	--WHILE (@@FETCH_STATUS = 0)
	   --  BEGIN
	   -- SET @SUMPRICE = @SUMPRICE + (@V_DISC_QTY * @V_OA_PRICE_PRQTY)
		--FETCH NEXT FROM CURSOR_SUMPRICE INTO @V_DISC_QTY,@V_OA_PRICE_PRQTY 
	   --  END
	--CLOSE CURSOR_SUMPRICE
	--DEALLOCATE CURSOR_SUMPRICE

SET @SUMPRICE = (SELECT ISNULL((SUM(OOBD.DISC_QTY * OOBD.PRICE_PRQTY)),0) FROM ORDR_OA_BRANDPACK_DISC OOBD
INNER JOIN ORDR_OA_BRANDPACK OOB ON OOB.OA_BRANDPACK_ID = OOBD.OA_BRANDPACK_ID
WHERE OOBD.GQSY_SGT_P_FLAG != 'RMOA' AND OOB.OA_ID = @OA_ID)
--GROUP BY OOB.OA_BRANDPACK_ID)
	
	--PRINT 'TOTAL_PRICE = ' + CAST((@SUMPRICE) AS VARCHAR(100))
END
GO

--SELECT ISNULL((SUM(OOBD.DISC_QTY * OOBD.PRICE_PRQTY)),0) FROM ORDR_OA_BRANDPACK_DISC OOBD
--INNER JOIN ORDR_OA_BRANDPACK OOB ON OOB.OA_BRANDPACK_ID = OOBD.OA_BRANDPACK_ID
--WHERE OOBD.GQSY_SGT_P_FLAG != 'RMOA' AND OOB.OA_ID = '4683/PES.PANL/X/2009-3337'


--exec Sp_GetSumPrice_Given_by_OA
--@OA_ID = '65/SPP/NTG/2009-3332',
--@SUMPRICE = 0

--09-00397/PKNN/OP-3259
--09-00397/PKNN/OP-3259
--65/SPP/NTG/2009-3332
--------------------------------------------------------------------------------------------------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_HasGeneratad_AGREE_OA_BRANDPACK_ID' AND TYPE = 'P')
DROP PROCEDURE Sp_HasGeneratad_AGREE_OA_BRANDPACK_ID
GO
CREATE PROCEDURE Sp_HasGeneratad_AGREE_OA_BRANDPACK_ID
@OA_BRANDPACK_ID VARCHAR(70),
@GQSY_FLAG VARCHAR(5)
AS
SET NOCOUNT ON
BEGIN
     IF EXISTS(SELECT OA_BRANDPACK_ID FROM AGREE_DISC_HISTORY WHERE OA_BRANDPACK_ID = @OA_BRANDPACK_ID
     AND GQSY_FLAG = @GQSY_FLAG) 
	RETURN(1) 
END
RETURN(0)
GO
-----------------------------------------------------------------------------------------------------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Sp_Generetate_AGREE_GIVEN_DISCOUNT_STAGE_1' AND TYPE = 'P')
DROP PROCEDURE Sp_Generetate_AGREE_GIVEN_DISCOUNT_STAGE_1
GO
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Generetate_AGREE_GIVEN_DISCOUNT_STAGE_1' AND TYPE = 'P')
DROP PROCEDURE Usp_Generetate_AGREE_GIVEN_DISCOUNT_STAGE_1
GO
CREATE PROCEDURE Usp_Generetate_AGREE_GIVEN_DISCOUNT_STAGE_1
@OA_BRANDPACK_ID VARCHAR(70),
@DISTRIBUTOR_ID VARCHAR(10),
@PO_REF_NO VARCHAR(25),
@BRANDPACK_ID VARCHAR(14),
@O_AGREE_BRANDPACK_ID VARCHAR(39)OUTPUT,
@O_PO_REF_DATE DATETIME OUTPUT,
@O_AGREEMENT_NO VARCHAR(25)OUTPUT,
@O_AGREE_BRAND_ID VARCHAR(32) OUTPUT
AS
SET NOCOUNT ON
DECLARE @V_BRANDPACK_ID VARCHAR(14)
BEGIN
SET @O_PO_REF_DATE = (SELECT PO_REF_DATE FROM ORDR_PURCHASE_ORDER WHERE PO_REF_NO = @PO_REF_NO)
SET @O_AGREEMENT_NO = (SELECT TOP 1 ABI.AGREEMENT_NO FROM AGREE_BRANDPACK_INCLUDE ABI 
                       INNER JOIN AGREE_AGREEMENT AA ON ABI.AGREEMENT_NO = AA.AGREEMENT_NO
                       INNER JOIN DISTRIBUTOR_AGREEMENT DA ON DA.AGREEMENT_NO = AA.AGREEMENT_NO
                       WHERE DA.DISTRIBUTOR_ID = @DISTRIBUTOR_ID AND AA.END_DATE >= @O_PO_REF_DATE
                       AND AA.START_DATE <= @O_PO_REF_DATE AND ABI.BRANDPACK_ID = @BRANDPACK_ID )
SET @O_AGREE_BRANDPACK_ID = (@O_AGREEMENT_NO + '' + @BRANDPACK_ID)
SET @O_AGREE_BRAND_ID = (SELECT AGREE_BRAND_ID FROM AGREE_BRANDPACK_INCLUDE WHERE AGREE_BRANDPACK_ID = 
                         @O_AGREE_BRANDPACK_ID)

IF (@O_AGREEMENT_NO IS NULL)
    BEGIN
	RAISERROR('Could not find AgreementNo between periods',16,1)
    END
IF (@O_AGREE_BRAND_ID IS NULL)
    BEGIN
	RAISERROR('Could not find AgreementBrand between periods',16,1)
    END
END
IF (@O_AGREE_BRANDPACK_ID IS NULL)

    BEGIN
	RAISERROR('Could not find AgreementBrandPack between periods',16,1)
    END

GO


--SELECT * FROM AGREE_AGREEMENT WHERE AGREEMENT_NO = '1082/NI/X/08-4L.09'

--UPDATE AGREE_AGREEMENT SET START_DATE = '09/01/2009',END_DATE = '08/31/2010'
--WHERE AGREEMENT_NO = '1082/NI/X/08-4L.09'
