IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Usp_Create_View_Target_Reaching' AND TYPE = 'P')
DROP PROCEDURE Usp_Create_View_Target_Reaching
GO
CREATE PROCEDURE Usp_Create_View_Target_Reaching
@DISTRIBUTOR_ID VARCHAR(10),
@AGREEMENT_NO VARCHAR(25),
@FLAG VARCHAR(2)
AS
SET NOCOUNT ON
DECLARE @V_START_DATE DATETIME,@V_SUMDAYS INT,@V_LONG_DATE INT
SET @V_START_DATE = (SELECT START_DATE FROM AGREE_AGREEMENT WHERE AGREEMENT_NO = @AGREEMENT_NO)
SET @V_SUMDAYS = CAST((SELECT DATEDIFF(DAY,START_DATE,END_DATE) FROM AGREE_AGREEMENT WHERE AGREEMENT_NO = @AGREEMENT_NO)AS INT)
IF (@FLAG = 'Q1') 
  BEGIN
	SET @V_LONG_DATE = (@V_SUMDAYS/4)
	DECLARE @V_START_DATE_Q1 DATETIME,@V_END_DATE_Q1 DATETIME
	SET @V_START_DATE_Q1 = @V_START_DATE
	SET @V_END_DATE_Q1 = (SELECT DATEADD(DAY,90,@V_START_DATE))
 	IF (SELECT COUNT (DISTRIBUTOR_ID) FROM DISTRIBUTOR_AGREEMENT WHERE AGREEMENT_NO = @AGREEMENT_NO) <= 1
	    BEGIN
		SELECT ABI.BRAND_ID,BR_1.BRAND_NAME,ABI.TARGET_Q1,'TARGET_GROUP' = 'NO',ISNULL(BR.ACTUAL,0)AS ACTUAL,ISNULL(BR.ACTUAL,0) - ABI.TARGET_Q1 AS LEFT_QTY FROM AGREE_BRAND_INCLUDE ABI INNER JOIN BRND_BRAND BR_1
		ON ABI.BRAND_ID = BR_1.BRAND_ID 
        	LEFT OUTER JOIN(
	                        SELECT ABI_1.AGREE_BRAND_ID,ISNULL(SUM(OPO.ACTUAL),0)AS ACTUAL FROM AGREE_BRANDPACK_INCLUDE ABI_1
	                        INNER JOIN(
			                   SELECT ABI_2.AGREE_BRANDPACK_ID,ISNULL(SUM(OPB.PO_ORIGINAL_QTY),0) AS ACTUAL FROM ORDR_PO_BRANDPACK OPB INNER JOIN AGREE_BRANDPACK_INCLUDE ABI_2
	                                   ON ABI_2.BRANDPACK_ID = OPB.BRANDPACK_ID 
	                                   INNER JOIN ORDR_PURCHASE_ORDER OPO ON OPB.PO_REF_NO = OPO.PO_REF_NO
                                           WHERE OPO.PO_REF_DATE <= @V_END_DATE_Q1 AND OPO.PO_REF_DATE >= @V_START_DATE_Q1
	                                   AND ABI_2.AGREEMENT_NO = @AGREEMENT_NO AND OPO.DISTRIBUTOR_ID = @DISTRIBUTOR_ID GROUP BY ABI_2.AGREE_BRANDPACK_ID 
                                           )OPO 
			                    ON OPO.AGREE_BRANDPACK_ID = ABI_1.AGREE_BRANDPACK_ID  GROUP BY ABI_1.AGREE_BRAND_ID
            		       )BR	
                                ON BR.AGREE_BRAND_ID = ABI.AGREE_BRAND_ID 
		WHERE ABI.AGREEMENT_NO = @AGREEMENT_NO 
	    END
	 ELSE
	    BEGIN
		SELECT ABI.BRAND_ID,BR_1.BRAND_NAME,ABI.TARGET_Q1,'TARGET_GROUP' = 'YESS',ISNULL(BR.ACTUAL,0)AS ACTUAL_DISTRIBUTOR,ISNULL(BR.ACTUAL_GROUP,0) AS ACTUAL_GROUP,
                ISNULL(BR.ACTUAL_GROUP,0) - ABI.TARGET_Q1 AS LEFT_QTY FROM AGREE_BRAND_INCLUDE ABI INNER JOIN BRND_BRAND BR_1
		ON ABI.BRAND_ID = BR_1.BRAND_ID 
        	LEFT OUTER JOIN(
	                        SELECT ABI_1.AGREE_BRAND_ID,ISNULL(SUM(OPO.ACTUAL),0)AS ACTUAL,ISNULL(SUM(OPO_1.ACTUAL_GROUP),0) AS ACTUAL_GROUP FROM AGREE_BRANDPACK_INCLUDE ABI_1
	                        INNER JOIN(
			                   SELECT ABI_2.AGREE_BRANDPACK_ID,ISNULL(SUM(OPB.PO_ORIGINAL_QTY),0) AS ACTUAL FROM ORDR_PO_BRANDPACK OPB INNER JOIN AGREE_BRANDPACK_INCLUDE ABI_2
	                                   ON ABI_2.BRANDPACK_ID = OPB.BRANDPACK_ID 
	                                   INNER JOIN ORDR_PURCHASE_ORDER OPO ON OPB.PO_REF_NO = OPO.PO_REF_NO
                                           WHERE OPO.PO_REF_DATE <= @V_END_DATE_Q1 AND OPO.PO_REF_DATE >= @V_START_DATE_Q1 AND OPO.DISTRIBUTOR_ID = @DISTRIBUTOR_ID
				           AND ABI_2.AGREEMENT_NO = @AGREEMENT_NO
	                                    GROUP BY ABI_2.AGREE_BRANDPACK_ID
                                           )OPO 
                                            ON OPO.AGREE_BRANDPACK_ID = ABI_1.AGREE_BRANDPACK_ID  
			         INNER JOIN(
			                   SELECT ABI_2.AGREE_BRANDPACK_ID,ISNULL(SUM(OPB.PO_ORIGINAL_QTY),0) AS ACTUAL_GROUP FROM ORDR_PO_BRANDPACK OPB INNER JOIN AGREE_BRANDPACK_INCLUDE ABI_2
	                                   ON ABI_2.BRANDPACK_ID = OPB.BRANDPACK_ID 
	                                   INNER JOIN ORDR_PURCHASE_ORDER OPO ON OPB.PO_REF_NO = OPO.PO_REF_NO
                                           WHERE OPO.PO_REF_DATE <= @V_END_DATE_Q1 AND OPO.PO_REF_DATE >= @V_START_DATE_Q1 AND 
					   OPO.DISTRIBUTOR_ID IN(SELECT DISTRIBUTOR_ID FROM DISTRIBUTOR_AGREEMENT WHERE AGREEMENT_NO = @AGREEMENT_NO)
				           AND ABI_2.AGREEMENT_NO = @AGREEMENT_NO
	                                    GROUP BY ABI_2.AGREE_BRANDPACK_ID
                                           )OPO_1 
                                          ON OPO_1.AGREE_BRANDPACK_ID = ABI_1.AGREE_BRANDPACK_ID  
                                  GROUP BY ABI_1.AGREE_BRAND_ID  					    
                        	 )BR	
                                ON BR.AGREE_BRAND_ID = ABI.AGREE_BRAND_ID 
		WHERE ABI.AGREEMENT_NO = @AGREEMENT_NO 
            END		
	PRINT ' @V_START_DATE_Q1 = ' + CAST((@V_START_DATE_Q1)AS VARCHAR(30))
	PRINT ' @V_END_DATE_Q1 = ' + CAST((@V_END_DATE_Q1)AS VARCHAR(30))
   END
ELSE IF(@FLAG = 'Q2')
   BEGIN
	SET @V_LONG_DATE = @V_SUMDAYS/4
	DECLARE @V_START_DATE_Q2 DATETIME,@V_END_DATE_Q2 DATETIME
	SET @V_START_DATE_Q2 = (SELECT DATEADD(DAY,@V_LONG_DATE,@V_START_DATE))
	SET @V_END_DATE_Q2 = (SELECT DATEADD(DAY,90,@V_START_DATE_Q2))
	IF (SELECT COUNT (DISTRIBUTOR_ID) FROM DISTRIBUTOR_AGREEMENT WHERE AGREEMENT_NO = @AGREEMENT_NO) <= 1
	    BEGIN
		SELECT ABI.BRAND_ID,BR_1.BRAND_NAME,ABI.TARGET_Q2,'TARGET_GROUP' = 'NO',ISNULL(BR.ACTUAL,0)AS ACTUAL,ISNULL(BR.ACTUAL,0) - ABI.TARGET_Q2 AS LEFT_QTY FROM AGREE_BRAND_INCLUDE ABI INNER JOIN BRND_BRAND BR_1
		ON ABI.BRAND_ID = BR_1.BRAND_ID 
        	LEFT OUTER JOIN(
	                        SELECT ABI_1.AGREE_BRAND_ID,ISNULL(SUM(OPO.ACTUAL),0)AS ACTUAL FROM AGREE_BRANDPACK_INCLUDE ABI_1
	                        INNER JOIN(
			                   SELECT ABI_2.AGREE_BRANDPACK_ID,ISNULL(SUM(OPB.PO_ORIGINAL_QTY),0) AS ACTUAL FROM ORDR_PO_BRANDPACK OPB INNER JOIN AGREE_BRANDPACK_INCLUDE ABI_2
	                                   ON ABI_2.BRANDPACK_ID = OPB.BRANDPACK_ID 
	                                   INNER JOIN ORDR_PURCHASE_ORDER OPO ON OPB.PO_REF_NO = OPO.PO_REF_NO
                                           WHERE OPO.PO_REF_DATE <= @V_END_DATE_Q2 AND OPO.PO_REF_DATE >= @V_START_DATE_Q2
	                                   AND ABI_2.AGREEMENT_NO = @AGREEMENT_NO AND OPO.DISTRIBUTOR_ID = @DISTRIBUTOR_ID GROUP BY ABI_2.AGREE_BRANDPACK_ID 
                                           )OPO 
			                    ON OPO.AGREE_BRANDPACK_ID = ABI_1.AGREE_BRANDPACK_ID  GROUP BY ABI_1.AGREE_BRAND_ID
            		       )BR	
                                ON BR.AGREE_BRAND_ID = ABI.AGREE_BRAND_ID 
		WHERE ABI.AGREEMENT_NO = @AGREEMENT_NO 
	    END
	 ELSE
	    BEGIN
		SELECT ABI.BRAND_ID,BR_1.BRAND_NAME,ABI.TARGET_Q2,'TARGET_GROUP' = 'YESS',ISNULL(BR.ACTUAL,0)AS ACTUAL_DISTRIBUTOR,ISNULL(BR.ACTUAL_GROUP,0) AS ACTUAL_GROUP,
                ISNULL(BR.ACTUAL_GROUP,0) - ABI.TARGET_Q2 AS LEFT_QTY FROM AGREE_BRAND_INCLUDE ABI INNER JOIN BRND_BRAND BR_1
		ON ABI.BRAND_ID = BR_1.BRAND_ID 
        	LEFT OUTER JOIN(
	                        SELECT ABI_1.AGREE_BRAND_ID,ISNULL(SUM(OPO.ACTUAL),0)AS ACTUAL,ISNULL(SUM(OPO_1.ACTUAL_GROUP),0) AS ACTUAL_GROUP FROM AGREE_BRANDPACK_INCLUDE ABI_1
	                        INNER JOIN(
			                   SELECT ABI_2.AGREE_BRANDPACK_ID,ISNULL(SUM(OPB.PO_ORIGINAL_QTY),0) AS ACTUAL FROM ORDR_PO_BRANDPACK OPB INNER JOIN AGREE_BRANDPACK_INCLUDE ABI_2
	                                   ON ABI_2.BRANDPACK_ID = OPB.BRANDPACK_ID 
	                                   INNER JOIN ORDR_PURCHASE_ORDER OPO ON OPB.PO_REF_NO = OPO.PO_REF_NO
                                           WHERE OPO.PO_REF_DATE <= @V_END_DATE_Q2 AND OPO.PO_REF_DATE >= @V_START_DATE_Q2 AND OPO.DISTRIBUTOR_ID = @DISTRIBUTOR_ID
				           AND ABI_2.AGREEMENT_NO = @AGREEMENT_NO
	                                    GROUP BY ABI_2.AGREE_BRANDPACK_ID
                                           )OPO 
                                            ON OPO.AGREE_BRANDPACK_ID = ABI_1.AGREE_BRANDPACK_ID  
			         INNER JOIN(
			                   SELECT ABI_2.AGREE_BRANDPACK_ID,ISNULL(SUM(OPB.PO_ORIGINAL_QTY),0) AS ACTUAL_GROUP FROM ORDR_PO_BRANDPACK OPB INNER JOIN AGREE_BRANDPACK_INCLUDE ABI_2
	                                   ON ABI_2.BRANDPACK_ID = OPB.BRANDPACK_ID 
	                                   INNER JOIN ORDR_PURCHASE_ORDER OPO ON OPB.PO_REF_NO = OPO.PO_REF_NO
                                           WHERE OPO.PO_REF_DATE <= @V_END_DATE_Q2 AND OPO.PO_REF_DATE >= @V_START_DATE_Q2 AND 
					   OPO.DISTRIBUTOR_ID IN(SELECT DISTRIBUTOR_ID FROM DISTRIBUTOR_AGREEMENT WHERE AGREEMENT_NO = @AGREEMENT_NO)
				           AND ABI_2.AGREEMENT_NO = @AGREEMENT_NO
	                                    GROUP BY ABI_2.AGREE_BRANDPACK_ID
                                           )OPO_1 
                                          ON OPO_1.AGREE_BRANDPACK_ID = ABI_1.AGREE_BRANDPACK_ID  
                                  GROUP BY ABI_1.AGREE_BRAND_ID  					    
                        	 )BR	
                                ON BR.AGREE_BRAND_ID = ABI.AGREE_BRAND_ID 
		WHERE ABI.AGREEMENT_NO = @AGREEMENT_NO 
            END
	PRINT ' @V_START_DATE_Q2 = ' + CAST((@V_START_DATE_Q2)AS VARCHAR(30))
	PRINT ' @V_END_DATE_Q2 = ' + CAST((@V_END_DATE_Q2)AS VARCHAR(30))
   END
ELSE IF(@FLAG = 'Q3')
   BEGIN
	SET @V_LONG_DATE = @V_SUMDAYS/4
	DECLARE @V_START_DATEQ2 DATETIME,@V_START_DATE_Q3 DATETIME,@V_END_DATE_Q3 DATETIME
	SET @V_START_DATEQ2 = (SELECT DATEADD(DAY,@V_LONG_DATE,@V_START_DATE)) 
	
	SET @V_START_DATE_Q3 = (SELECT DATEADD(DAY,91, @V_START_DATEQ2)) 
	SET @V_END_DATE_Q3 = (SELECT DATEADD(DAY,90,@V_START_DATE_Q3))

	IF (SELECT COUNT (DISTRIBUTOR_ID) FROM DISTRIBUTOR_AGREEMENT WHERE AGREEMENT_NO = @AGREEMENT_NO) <= 1
	    BEGIN
		SELECT ABI.BRAND_ID,BR_1.BRAND_NAME,ABI.TARGET_Q3,'TARGET_GROUP' = 'NO',ISNULL(BR.ACTUAL,0)AS ACTUAL,ISNULL(BR.ACTUAL,0) - ABI.TARGET_Q3 AS LEFT_QTY FROM AGREE_BRAND_INCLUDE ABI INNER JOIN BRND_BRAND BR_1
		ON ABI.BRAND_ID = BR_1.BRAND_ID 
        	LEFT OUTER JOIN(
	                        SELECT ABI_1.AGREE_BRAND_ID,ISNULL(SUM(OPO.ACTUAL),0)AS ACTUAL FROM AGREE_BRANDPACK_INCLUDE ABI_1
	                        INNER JOIN(
			                   SELECT ABI_2.AGREE_BRANDPACK_ID,ISNULL(SUM(OPB.PO_ORIGINAL_QTY),0) AS ACTUAL FROM ORDR_PO_BRANDPACK OPB INNER JOIN AGREE_BRANDPACK_INCLUDE ABI_2
	                                   ON ABI_2.BRANDPACK_ID = OPB.BRANDPACK_ID 
	                                   INNER JOIN ORDR_PURCHASE_ORDER OPO ON OPB.PO_REF_NO = OPO.PO_REF_NO
                                           WHERE OPO.PO_REF_DATE <= @V_END_DATE_Q3 AND OPO.PO_REF_DATE >= @V_START_DATE_Q3
	                                   AND ABI_2.AGREEMENT_NO = @AGREEMENT_NO AND OPO.DISTRIBUTOR_ID = @DISTRIBUTOR_ID GROUP BY ABI_2.AGREE_BRANDPACK_ID 
                                           )OPO 
			                    ON OPO.AGREE_BRANDPACK_ID = ABI_1.AGREE_BRANDPACK_ID  GROUP BY ABI_1.AGREE_BRAND_ID
            		       )BR	
                                ON BR.AGREE_BRAND_ID = ABI.AGREE_BRAND_ID 
		WHERE ABI.AGREEMENT_NO = @AGREEMENT_NO 
	    END
	 ELSE
	    BEGIN
		SELECT ABI.BRAND_ID,BR_1.BRAND_NAME,ABI.TARGET_Q3,'TARGET_GROUP' = 'YESS',ISNULL(BR.ACTUAL,0)AS ACTUAL_DISTRIBUTOR,ISNULL(BR.ACTUAL_GROUP,0) AS ACTUAL_GROUP,
                ISNULL(BR.ACTUAL_GROUP,0) - ABI.TARGET_Q3 AS LEFT_QTY FROM AGREE_BRAND_INCLUDE ABI INNER JOIN BRND_BRAND BR_1
		ON ABI.BRAND_ID = BR_1.BRAND_ID 
        	LEFT OUTER JOIN(
	                        SELECT ABI_1.AGREE_BRAND_ID,ISNULL(SUM(OPO.ACTUAL),0)AS ACTUAL,ISNULL(SUM(OPO_1.ACTUAL_GROUP),0) AS ACTUAL_GROUP FROM AGREE_BRANDPACK_INCLUDE ABI_1
	                        INNER JOIN(
			                   SELECT ABI_2.AGREE_BRANDPACK_ID,ISNULL(SUM(OPB.PO_ORIGINAL_QTY),0) AS ACTUAL FROM ORDR_PO_BRANDPACK OPB INNER JOIN AGREE_BRANDPACK_INCLUDE ABI_2
	                                   ON ABI_2.BRANDPACK_ID = OPB.BRANDPACK_ID 
	                                   INNER JOIN ORDR_PURCHASE_ORDER OPO ON OPB.PO_REF_NO = OPO.PO_REF_NO
                                           WHERE OPO.PO_REF_DATE <= @V_END_DATE_Q3 AND OPO.PO_REF_DATE >= @V_START_DATE_Q3 AND OPO.DISTRIBUTOR_ID = @DISTRIBUTOR_ID
				           AND ABI_2.AGREEMENT_NO = @AGREEMENT_NO
	                                    GROUP BY ABI_2.AGREE_BRANDPACK_ID
                                           )OPO 
                                            ON OPO.AGREE_BRANDPACK_ID = ABI_1.AGREE_BRANDPACK_ID  
			         INNER JOIN(
			                   SELECT ABI_2.AGREE_BRANDPACK_ID,ISNULL(SUM(OPB.PO_ORIGINAL_QTY),0) AS ACTUAL_GROUP FROM ORDR_PO_BRANDPACK OPB INNER JOIN AGREE_BRANDPACK_INCLUDE ABI_2
	                                   ON ABI_2.BRANDPACK_ID = OPB.BRANDPACK_ID 
	                                   INNER JOIN ORDR_PURCHASE_ORDER OPO ON OPB.PO_REF_NO = OPO.PO_REF_NO
                                           WHERE OPO.PO_REF_DATE <= @V_END_DATE_Q3 AND OPO.PO_REF_DATE >= @V_START_DATE_Q3 AND 
					   OPO.DISTRIBUTOR_ID IN(SELECT DISTRIBUTOR_ID FROM DISTRIBUTOR_AGREEMENT WHERE AGREEMENT_NO = @AGREEMENT_NO)
				           AND ABI_2.AGREEMENT_NO = @AGREEMENT_NO
	                                    GROUP BY ABI_2.AGREE_BRANDPACK_ID
                                           )OPO_1 
                                          ON OPO_1.AGREE_BRANDPACK_ID = ABI_1.AGREE_BRANDPACK_ID  
                                  GROUP BY ABI_1.AGREE_BRAND_ID  					    
                        	 )BR	
                                ON BR.AGREE_BRAND_ID = ABI.AGREE_BRAND_ID 
		WHERE ABI.AGREEMENT_NO = @AGREEMENT_NO 
            END
	PRINT ' @V_START_DATE_Q3 = ' + CAST((@V_START_DATE_Q3)AS VARCHAR(30))
	PRINT ' @V_END_DATE_Q3 = ' + CAST((@V_END_DATE_Q3)AS VARCHAR(30))
   END
ELSE IF (@FLAG = 'Q4')
   BEGIN
	SET @V_LONG_DATE = @V_SUMDAYS/4
	DECLARE @V_START_Q2 DATETIME,@V_START_DATE_Q4 DATETIME,@V_END_DATE_Q4 DATETIME,@V_START_DATEQ3 DATETIME
	SET @V_START_Q2 = (SELECT DATEADD(DAY,@V_LONG_DATE,@V_START_DATE)) 
	
	SET @V_START_DATEQ3 = (SELECT DATEADD(DAY,91, @V_START_Q2)) 
	
	
	SET @V_START_DATE_Q4 = (SELECT DATEADD(DAY,91,@V_START_DATEQ3)) 
	SET @V_END_DATE_Q4 = (SELECT END_DATE FROM AGREE_AGREEMENT WHERE AGREEMENT_NO = @AGREEMENT_NO )

	IF (SELECT COUNT (DISTRIBUTOR_ID) FROM DISTRIBUTOR_AGREEMENT WHERE AGREEMENT_NO = @AGREEMENT_NO) <= 1
	    BEGIN
		SELECT ABI.BRAND_ID,BR_1.BRAND_NAME,ABI.TARGET_Q4,'TARGET_GROUP' = 'NO',ISNULL(BR.ACTUAL,0)AS ACTUAL,ISNULL(BR.ACTUAL,0) - ABI.TARGET_Q4 AS LEFT_QTY FROM AGREE_BRAND_INCLUDE ABI INNER JOIN BRND_BRAND BR_1
		ON ABI.BRAND_ID = BR_1.BRAND_ID 
        	LEFT OUTER JOIN(
	                        SELECT ABI_1.AGREE_BRAND_ID,ISNULL(SUM(OPO.ACTUAL),0)AS ACTUAL FROM AGREE_BRANDPACK_INCLUDE ABI_1
	                        INNER JOIN(
			                   SELECT ABI_2.AGREE_BRANDPACK_ID,ISNULL(SUM(OPB.PO_ORIGINAL_QTY),0) AS ACTUAL FROM ORDR_PO_BRANDPACK OPB INNER JOIN AGREE_BRANDPACK_INCLUDE ABI_2
	                                   ON ABI_2.BRANDPACK_ID = OPB.BRANDPACK_ID 
	                                   INNER JOIN ORDR_PURCHASE_ORDER OPO ON OPB.PO_REF_NO = OPO.PO_REF_NO
                                           WHERE OPO.PO_REF_DATE <= @V_END_DATE_Q4 AND OPO.PO_REF_DATE >= @V_START_DATE_Q4
	                                   AND ABI_2.AGREEMENT_NO = @AGREEMENT_NO AND OPO.DISTRIBUTOR_ID = @DISTRIBUTOR_ID GROUP BY ABI_2.AGREE_BRANDPACK_ID 
                                           )OPO 
			                    ON OPO.AGREE_BRANDPACK_ID = ABI_1.AGREE_BRANDPACK_ID  GROUP BY ABI_1.AGREE_BRAND_ID
            		       )BR	
                                ON BR.AGREE_BRAND_ID = ABI.AGREE_BRAND_ID 
		WHERE ABI.AGREEMENT_NO = @AGREEMENT_NO 
	    END
	 ELSE
	    BEGIN
		SELECT ABI.BRAND_ID,BR_1.BRAND_NAME,ABI.TARGET_Q4,'TARGET_GROUP' = 'YESS',ISNULL(BR.ACTUAL,0)AS ACTUAL_DISTRIBUTOR,ISNULL(BR.ACTUAL_GROUP,0) AS ACTUAL_GROUP,
                ISNULL(BR.ACTUAL_GROUP,0) - ABI.TARGET_Q4 AS LEFT_QTY FROM AGREE_BRAND_INCLUDE ABI INNER JOIN BRND_BRAND BR_1
		ON ABI.BRAND_ID = BR_1.BRAND_ID 
        	LEFT OUTER JOIN(
	                        SELECT ABI_1.AGREE_BRAND_ID,ISNULL(SUM(OPO.ACTUAL),0)AS ACTUAL,ISNULL(SUM(OPO_1.ACTUAL_GROUP),0) AS ACTUAL_GROUP FROM AGREE_BRANDPACK_INCLUDE ABI_1
	                        INNER JOIN(
			                   SELECT ABI_2.AGREE_BRANDPACK_ID,ISNULL(SUM(OPB.PO_ORIGINAL_QTY),0) AS ACTUAL FROM ORDR_PO_BRANDPACK OPB INNER JOIN AGREE_BRANDPACK_INCLUDE ABI_2
	                                   ON ABI_2.BRANDPACK_ID = OPB.BRANDPACK_ID 
	                                   INNER JOIN ORDR_PURCHASE_ORDER OPO ON OPB.PO_REF_NO = OPO.PO_REF_NO
                                           WHERE OPO.PO_REF_DATE <= @V_END_DATE_Q4 AND OPO.PO_REF_DATE >= @V_START_DATE_Q4 AND OPO.DISTRIBUTOR_ID = @DISTRIBUTOR_ID
				           AND ABI_2.AGREEMENT_NO = @AGREEMENT_NO
	                                    GROUP BY ABI_2.AGREE_BRANDPACK_ID
                                           )OPO 
                                            ON OPO.AGREE_BRANDPACK_ID = ABI_1.AGREE_BRANDPACK_ID  
			         INNER JOIN(
			                   SELECT ABI_2.AGREE_BRANDPACK_ID,ISNULL(SUM(OPB.PO_ORIGINAL_QTY),0) AS ACTUAL_GROUP FROM ORDR_PO_BRANDPACK OPB INNER JOIN AGREE_BRANDPACK_INCLUDE ABI_2
	                                   ON ABI_2.BRANDPACK_ID = OPB.BRANDPACK_ID 
	                                   INNER JOIN ORDR_PURCHASE_ORDER OPO ON OPB.PO_REF_NO = OPO.PO_REF_NO
                                           WHERE OPO.PO_REF_DATE <= @V_END_DATE_Q4 AND OPO.PO_REF_DATE >= @V_START_DATE_Q4 AND 
					   OPO.DISTRIBUTOR_ID IN(SELECT DISTRIBUTOR_ID FROM DISTRIBUTOR_AGREEMENT WHERE AGREEMENT_NO = @AGREEMENT_NO)
				           AND ABI_2.AGREEMENT_NO = @AGREEMENT_NO
	                                    GROUP BY ABI_2.AGREE_BRANDPACK_ID
                                           )OPO_1 
                                          ON OPO_1.AGREE_BRANDPACK_ID = ABI_1.AGREE_BRANDPACK_ID  
                                  GROUP BY ABI_1.AGREE_BRAND_ID  					    
                        	 )BR	
                                ON BR.AGREE_BRAND_ID = ABI.AGREE_BRAND_ID 
		WHERE ABI.AGREEMENT_NO = @AGREEMENT_NO 
            END

	PRINT ' @V_START_DATE_Q4 = ' + CAST((@V_START_DATE_Q4)AS VARCHAR(30))
	PRINT ' @V_END_DATE_Q4 = ' + CAST((@V_END_DATE_Q4)AS VARCHAR(30))
   END
ELSE IF(@FLAG = 'S1')
     BEGIN
	SET @V_LONG_DATE = @V_SUMDAYS/2
	DECLARE @V_START_DATE_S1 DATETIME,@V_END_DATE_S1 DATETIME
	SET @V_START_DATE_S1 = @V_START_DATE
	SET @V_END_DATE_S1 = (SELECT DATEADD(DAY,@V_LONG_DATE - 1,@V_START_DATE_S1))
	PRINT ' @V_START_DATE_S1 = ' + CAST((@V_START_DATE_S1)AS VARCHAR(30))
	PRINT ' @V_END_DATE_S1 = ' + CAST((@V_END_DATE_S1)AS VARCHAR(30))
	IF (SELECT COUNT (DISTRIBUTOR_ID) FROM DISTRIBUTOR_AGREEMENT WHERE AGREEMENT_NO = @AGREEMENT_NO) <= 1
	    BEGIN
		SELECT ABI.BRAND_ID,BR_1.BRAND_NAME,ABI.TARGET_S1,'TARGET_GROUP' = 'NO',ISNULL(BR.ACTUAL,0)AS ACTUAL,ISNULL(BR.ACTUAL,0) - ABI.TARGET_S1 AS LEFT_QTY FROM AGREE_BRAND_INCLUDE ABI INNER JOIN BRND_BRAND BR_1
		ON ABI.BRAND_ID = BR_1.BRAND_ID 
        	LEFT OUTER JOIN(
	                        SELECT ABI_1.AGREE_BRAND_ID,ISNULL(SUM(OPO.ACTUAL),0)AS ACTUAL FROM AGREE_BRANDPACK_INCLUDE ABI_1
	                        INNER JOIN(
			                   SELECT ABI_2.AGREE_BRANDPACK_ID,ISNULL(SUM(OPB.PO_ORIGINAL_QTY),0) AS ACTUAL FROM ORDR_PO_BRANDPACK OPB INNER JOIN AGREE_BRANDPACK_INCLUDE ABI_2
	                                   ON ABI_2.BRANDPACK_ID = OPB.BRANDPACK_ID 
	                                   INNER JOIN ORDR_PURCHASE_ORDER OPO ON OPB.PO_REF_NO = OPO.PO_REF_NO
                                           WHERE OPO.PO_REF_DATE <= @V_END_DATE_S1 AND OPO.PO_REF_DATE >= @V_START_DATE_S1
	                                   AND ABI_2.AGREEMENT_NO = @AGREEMENT_NO AND OPO.DISTRIBUTOR_ID = @DISTRIBUTOR_ID GROUP BY ABI_2.AGREE_BRANDPACK_ID 
                                           )OPO 
			                    ON OPO.AGREE_BRANDPACK_ID = ABI_1.AGREE_BRANDPACK_ID  GROUP BY ABI_1.AGREE_BRAND_ID
            		       )BR	
                                ON BR.AGREE_BRAND_ID = ABI.AGREE_BRAND_ID 
		WHERE ABI.AGREEMENT_NO = @AGREEMENT_NO 
	    END
	 ELSE
	    BEGIN
		SELECT ABI.BRAND_ID,BR_1.BRAND_NAME,ABI.TARGET_S1,'TARGET_GROUP' = 'YESS',ISNULL(BR.ACTUAL,0)AS ACTUAL_DISTRIBUTOR,ISNULL(BR.ACTUAL_GROUP,0) AS ACTUAL_GROUP,
                ISNULL(BR.ACTUAL_GROUP,0) - ABI.TARGET_S1 AS LEFT_QTY FROM AGREE_BRAND_INCLUDE ABI INNER JOIN BRND_BRAND BR_1
		ON ABI.BRAND_ID = BR_1.BRAND_ID 
        	LEFT OUTER JOIN(
	                        SELECT ABI_1.AGREE_BRAND_ID,ISNULL(SUM(OPO.ACTUAL),0)AS ACTUAL,ISNULL(SUM(OPO_1.ACTUAL_GROUP),0) AS ACTUAL_GROUP FROM AGREE_BRANDPACK_INCLUDE ABI_1
	                        INNER JOIN(
			                   SELECT ABI_2.AGREE_BRANDPACK_ID,ISNULL(SUM(OPB.PO_ORIGINAL_QTY),0) AS ACTUAL FROM ORDR_PO_BRANDPACK OPB INNER JOIN AGREE_BRANDPACK_INCLUDE ABI_2
	                                   ON ABI_2.BRANDPACK_ID = OPB.BRANDPACK_ID 
	                                   INNER JOIN ORDR_PURCHASE_ORDER OPO ON OPB.PO_REF_NO = OPO.PO_REF_NO
                                           WHERE OPO.PO_REF_DATE <= @V_END_DATE_S1 AND OPO.PO_REF_DATE >= @V_START_DATE_S1 AND OPO.DISTRIBUTOR_ID = @DISTRIBUTOR_ID
				           AND ABI_2.AGREEMENT_NO = @AGREEMENT_NO
	                                    GROUP BY ABI_2.AGREE_BRANDPACK_ID
                                           )OPO 
                                            ON OPO.AGREE_BRANDPACK_ID = ABI_1.AGREE_BRANDPACK_ID  
			         INNER JOIN(
			                   SELECT ABI_2.AGREE_BRANDPACK_ID,ISNULL(SUM(OPB.PO_ORIGINAL_QTY),0) AS ACTUAL_GROUP FROM ORDR_PO_BRANDPACK OPB INNER JOIN AGREE_BRANDPACK_INCLUDE ABI_2
	                                   ON ABI_2.BRANDPACK_ID = OPB.BRANDPACK_ID 
	                                   INNER JOIN ORDR_PURCHASE_ORDER OPO ON OPB.PO_REF_NO = OPO.PO_REF_NO
                                           WHERE OPO.PO_REF_DATE <= @V_END_DATE_S1 AND OPO.PO_REF_DATE >= @V_START_DATE_S1 AND 
					   OPO.DISTRIBUTOR_ID IN(SELECT DISTRIBUTOR_ID FROM DISTRIBUTOR_AGREEMENT WHERE AGREEMENT_NO = @AGREEMENT_NO)
				           AND ABI_2.AGREEMENT_NO = @AGREEMENT_NO
	                                    GROUP BY ABI_2.AGREE_BRANDPACK_ID
                                           )OPO_1 
                                          ON OPO_1.AGREE_BRANDPACK_ID = ABI_1.AGREE_BRANDPACK_ID  
                                  GROUP BY ABI_1.AGREE_BRAND_ID  					    
                        	 )BR	
                                ON BR.AGREE_BRAND_ID = ABI.AGREE_BRAND_ID 
		WHERE ABI.AGREEMENT_NO = @AGREEMENT_NO 
            END
	
     END
ELSE IF (@FLAG = 'S2')
     BEGIN
	SET @V_LONG_DATE = @V_SUMDAYS/2
	DECLARE @V_START_DATE_S2 DATETIME,@V_END_DATE_S2 DATETIME
	SET @V_START_DATE_S2 = (SELECT DATEADD(DAY,@V_LONG_DATE,@V_START_DATE)) 
	SET @V_END_DATE_S2 = (SELECT END_DATE FROM AGREE_AGREEMENT WHERE AGREEMENT_NO = @AGREEMENT_NO)
	PRINT ' @V_START_DATE_S2 = ' + CAST((@V_START_DATE_S2)AS VARCHAR(30))
	PRINT ' @V_END_DATE_S2 = ' + CAST((@V_END_DATE_S2)AS VARCHAR(30))
	IF (SELECT COUNT (DISTRIBUTOR_ID) FROM DISTRIBUTOR_AGREEMENT WHERE AGREEMENT_NO = @AGREEMENT_NO) <= 1
	    BEGIN
		SELECT ABI.BRAND_ID,BR_1.BRAND_NAME,ABI.TARGET_S2,'TARGET_GROUP' = 'NO',ISNULL(BR.ACTUAL,0)AS ACTUAL,ISNULL(BR.ACTUAL,0) - ABI.TARGET_S2 AS LEFT_QTY FROM AGREE_BRAND_INCLUDE ABI INNER JOIN BRND_BRAND BR_1
		ON ABI.BRAND_ID = BR_1.BRAND_ID 
        	LEFT OUTER JOIN(
	                        SELECT ABI_1.AGREE_BRAND_ID,ISNULL(SUM(OPO.ACTUAL),0)AS ACTUAL FROM AGREE_BRANDPACK_INCLUDE ABI_1
	                        INNER JOIN(
			                   SELECT ABI_2.AGREE_BRANDPACK_ID,ISNULL(SUM(OPB.PO_ORIGINAL_QTY),0) AS ACTUAL FROM ORDR_PO_BRANDPACK OPB INNER JOIN AGREE_BRANDPACK_INCLUDE ABI_2
	                                   ON ABI_2.BRANDPACK_ID = OPB.BRANDPACK_ID 
	                                   INNER JOIN ORDR_PURCHASE_ORDER OPO ON OPB.PO_REF_NO = OPO.PO_REF_NO
                                           WHERE OPO.PO_REF_DATE <= @V_END_DATE_S2 AND OPO.PO_REF_DATE >= @V_START_DATE_S2
	                                   AND ABI_2.AGREEMENT_NO = @AGREEMENT_NO AND OPO.DISTRIBUTOR_ID = @DISTRIBUTOR_ID GROUP BY ABI_2.AGREE_BRANDPACK_ID 
                                           )OPO 
			                    ON OPO.AGREE_BRANDPACK_ID = ABI_1.AGREE_BRANDPACK_ID  GROUP BY ABI_1.AGREE_BRAND_ID
            		       )BR	
                                ON BR.AGREE_BRAND_ID = ABI.AGREE_BRAND_ID 
		WHERE ABI.AGREEMENT_NO = @AGREEMENT_NO 
	    END
	 ELSE
	    BEGIN
		SELECT ABI.BRAND_ID,BR_1.BRAND_NAME,ABI.TARGET_S2,'TARGET_GROUP' = 'YESS',ISNULL(BR.ACTUAL,0)AS ACTUAL_DISTRIBUTOR,ISNULL(BR.ACTUAL_GROUP,0) AS ACTUAL_GROUP,
                ISNULL(BR.ACTUAL_GROUP,0) - ABI.TARGET_S2 AS LEFT_QTY FROM AGREE_BRAND_INCLUDE ABI INNER JOIN BRND_BRAND BR_1
		ON ABI.BRAND_ID = BR_1.BRAND_ID 
        	LEFT OUTER JOIN(
	                        SELECT ABI_1.AGREE_BRAND_ID,ISNULL(SUM(OPO.ACTUAL),0)AS ACTUAL,ISNULL(SUM(OPO_1.ACTUAL_GROUP),0) AS ACTUAL_GROUP FROM AGREE_BRANDPACK_INCLUDE ABI_1
	                        INNER JOIN(
			                   SELECT ABI_2.AGREE_BRANDPACK_ID,ISNULL(SUM(OPB.PO_ORIGINAL_QTY),0) AS ACTUAL FROM ORDR_PO_BRANDPACK OPB INNER JOIN AGREE_BRANDPACK_INCLUDE ABI_2
	                                   ON ABI_2.BRANDPACK_ID = OPB.BRANDPACK_ID 
	                                   INNER JOIN ORDR_PURCHASE_ORDER OPO ON OPB.PO_REF_NO = OPO.PO_REF_NO
                                           WHERE OPO.PO_REF_DATE <= @V_END_DATE_S2 AND OPO.PO_REF_DATE >= @V_START_DATE_S2 AND OPO.DISTRIBUTOR_ID = @DISTRIBUTOR_ID
				           AND ABI_2.AGREEMENT_NO = @AGREEMENT_NO
	                                    GROUP BY ABI_2.AGREE_BRANDPACK_ID
                                           )OPO 
                                            ON OPO.AGREE_BRANDPACK_ID = ABI_1.AGREE_BRANDPACK_ID  
			         INNER JOIN(
			                   SELECT ABI_2.AGREE_BRANDPACK_ID,ISNULL(SUM(OPB.PO_ORIGINAL_QTY),0) AS ACTUAL_GROUP FROM ORDR_PO_BRANDPACK OPB INNER JOIN AGREE_BRANDPACK_INCLUDE ABI_2
	                                   ON ABI_2.BRANDPACK_ID = OPB.BRANDPACK_ID 
	                                   INNER JOIN ORDR_PURCHASE_ORDER OPO ON OPB.PO_REF_NO = OPO.PO_REF_NO
                                           WHERE OPO.PO_REF_DATE <= @V_END_DATE_S2 AND OPO.PO_REF_DATE >= @V_START_DATE_S2 AND 
					   OPO.DISTRIBUTOR_ID IN(SELECT DISTRIBUTOR_ID FROM DISTRIBUTOR_AGREEMENT WHERE AGREEMENT_NO = @AGREEMENT_NO)
				           AND ABI_2.AGREEMENT_NO = @AGREEMENT_NO
	                                    GROUP BY ABI_2.AGREE_BRANDPACK_ID
                                           )OPO_1 
                                          ON OPO_1.AGREE_BRANDPACK_ID = ABI_1.AGREE_BRANDPACK_ID  
                                  GROUP BY ABI_1.AGREE_BRAND_ID  					    
                        	 )BR	
                                ON BR.AGREE_BRAND_ID = ABI.AGREE_BRAND_ID 
		WHERE ABI.AGREEMENT_NO = @AGREEMENT_NO 
            END
	
     END
ELSE IF(@FLAG = 'Y')
     BEGIN
	DECLARE @V_END_DATE DATETIME
	SET @V_END_DATE = (SELECT END_DATE FROM AGREE_AGREEMENT WHERE AGREEMENT_NO = @AGREEMENT_NO)
 	
        IF (SELECT COUNT (DISTRIBUTOR_ID) FROM DISTRIBUTOR_AGREEMENT WHERE AGREEMENT_NO = @AGREEMENT_NO) <= 1
	    BEGIN
		SELECT ABI.BRAND_ID,BR_1.BRAND_NAME,ABI.TARGET_Q1 + ABI.TARGET_Q2 + ABI.TARGET_Q3 + ABI.TARGET_Q4
                + ABI.TARGET_S1 + ABI.TARGET_S2 AS TARGET_YEAR,'TARGET_GROUP' = 'NO',ISNULL(BR.ACTUAL,0)AS ACTUAL,
		ISNULL(BR.ACTUAL,0) - (ABI.TARGET_Q1 + ABI.TARGET_Q2 + ABI.TARGET_Q3 + ABI.TARGET_Q4
                + ABI.TARGET_S1 + ABI.TARGET_S2) AS LEFT_QTY FROM AGREE_BRAND_INCLUDE ABI INNER JOIN BRND_BRAND BR_1
		ON ABI.BRAND_ID = BR_1.BRAND_ID 
        	LEFT OUTER JOIN(
	                        SELECT ABI_1.AGREE_BRAND_ID,ISNULL(SUM(OPO.ACTUAL),0)AS ACTUAL FROM AGREE_BRANDPACK_INCLUDE ABI_1
	                        INNER JOIN(
			                   SELECT ABI_2.AGREE_BRANDPACK_ID,ISNULL(SUM(OPB.PO_ORIGINAL_QTY),0) AS ACTUAL FROM ORDR_PO_BRANDPACK OPB INNER JOIN AGREE_BRANDPACK_INCLUDE ABI_2
	                                   ON ABI_2.BRANDPACK_ID = OPB.BRANDPACK_ID 
	                                   INNER JOIN ORDR_PURCHASE_ORDER OPO ON OPB.PO_REF_NO = OPO.PO_REF_NO
                                           WHERE OPO.PO_REF_DATE <= @V_END_DATE AND OPO.PO_REF_DATE >= @V_START_DATE
	                                   AND ABI_2.AGREEMENT_NO = @AGREEMENT_NO AND OPO.DISTRIBUTOR_ID = @DISTRIBUTOR_ID GROUP BY ABI_2.AGREE_BRANDPACK_ID 
                                           )OPO 
			                    ON OPO.AGREE_BRANDPACK_ID = ABI_1.AGREE_BRANDPACK_ID  GROUP BY ABI_1.AGREE_BRAND_ID
            		       )BR	
                                ON BR.AGREE_BRAND_ID = ABI.AGREE_BRAND_ID 
		WHERE ABI.AGREEMENT_NO = @AGREEMENT_NO 
	    END
	 ELSE
	    BEGIN
		SELECT ABI.BRAND_ID,BR_1.BRAND_NAME,ABI.TARGET_Q1 + ABI.TARGET_Q2 + ABI.TARGET_Q3 + ABI.TARGET_Q4
                + ABI.TARGET_S1 + ABI.TARGET_S2 AS TARGET_YEAR,'TARGET_GROUP' = 'YESS',ISNULL(BR.ACTUAL,0)AS ACTUAL_DISTRIBUTOR,ISNULL(BR.ACTUAL_GROUP,0) AS ACTUAL_GROUP,
                ISNULL(BR.ACTUAL_GROUP,0) - (ABI.TARGET_Q1 + ABI.TARGET_Q2 + ABI.TARGET_Q3 + ABI.TARGET_Q4
                + ABI.TARGET_S1 + ABI.TARGET_S2) AS LEFT_QTY FROM AGREE_BRAND_INCLUDE ABI INNER JOIN BRND_BRAND BR_1
		ON ABI.BRAND_ID = BR_1.BRAND_ID 
        	LEFT OUTER JOIN(
	                        SELECT ABI_1.AGREE_BRAND_ID,ISNULL(SUM(OPO.ACTUAL),0)AS ACTUAL,ISNULL(SUM(OPO_1.ACTUAL_GROUP),0) AS ACTUAL_GROUP FROM AGREE_BRANDPACK_INCLUDE ABI_1
	                        INNER JOIN(
			                   SELECT ABI_2.AGREE_BRANDPACK_ID,ISNULL(SUM(OPB.PO_ORIGINAL_QTY),0) AS ACTUAL FROM ORDR_PO_BRANDPACK OPB INNER JOIN AGREE_BRANDPACK_INCLUDE ABI_2
	                                   ON ABI_2.BRANDPACK_ID = OPB.BRANDPACK_ID 
	                                   INNER JOIN ORDR_PURCHASE_ORDER OPO ON OPB.PO_REF_NO = OPO.PO_REF_NO
                                           WHERE OPO.PO_REF_DATE <= @V_END_DATE AND OPO.PO_REF_DATE >= @V_START_DATE AND OPO.DISTRIBUTOR_ID = @DISTRIBUTOR_ID
				           AND ABI_2.AGREEMENT_NO = @AGREEMENT_NO
	                                    GROUP BY ABI_2.AGREE_BRANDPACK_ID
                                           )OPO 
                                            ON OPO.AGREE_BRANDPACK_ID = ABI_1.AGREE_BRANDPACK_ID  
			         INNER JOIN(
			                   SELECT ABI_2.AGREE_BRANDPACK_ID,ISNULL(SUM(OPB.PO_ORIGINAL_QTY),0) AS ACTUAL_GROUP FROM ORDR_PO_BRANDPACK OPB INNER JOIN AGREE_BRANDPACK_INCLUDE ABI_2
	                                   ON ABI_2.BRANDPACK_ID = OPB.BRANDPACK_ID 
	                                   INNER JOIN ORDR_PURCHASE_ORDER OPO ON OPB.PO_REF_NO = OPO.PO_REF_NO
                                           WHERE OPO.PO_REF_DATE <= @V_END_DATE AND OPO.PO_REF_DATE >= @V_START_DATE AND 
					   OPO.DISTRIBUTOR_ID IN(SELECT DISTRIBUTOR_ID FROM DISTRIBUTOR_AGREEMENT WHERE AGREEMENT_NO = @AGREEMENT_NO)
				           AND ABI_2.AGREEMENT_NO = @AGREEMENT_NO
	                                    GROUP BY ABI_2.AGREE_BRANDPACK_ID
                                           )OPO_1 
                                          ON OPO_1.AGREE_BRANDPACK_ID = ABI_1.AGREE_BRANDPACK_ID  
                                  GROUP BY ABI_1.AGREE_BRAND_ID  					    
                        	 )BR	
                                ON BR.AGREE_BRAND_ID = ABI.AGREE_BRAND_ID 
		WHERE ABI.AGREEMENT_NO = @AGREEMENT_NO 
            END

	PRINT '@V_START_DATE = ' + CAST((@V_START_DATE)AS VARCHAR(30))
	PRINT '@V_END_DATE = ' + CAST((@V_END_DATE)AS VARCHAR(30))
     END

GO
--EXEC Usp_Create_View_Target_Reaching
--@DISTRIBUTOR_ID = 'ABA001IDR',
--@AGREEMENT_NO = '092/NI/I/2005',
--@flag = 's1'
--RAISERROR