'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.9168
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''Represents a strongly typed in-memory cache of data.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
 Global.System.Serializable(),  _
 Global.System.ComponentModel.DesignerCategoryAttribute("code"),  _
 Global.System.ComponentModel.ToolboxItem(true),  _
 Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema"),  _
 Global.System.Xml.Serialization.XmlRootAttribute("DSGON"),  _
 Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")>  _
Partial Public Class DSGON
    Inherits Global.System.Data.DataSet
    
    Private tabletbl_rep_gon As tbl_rep_gonDataTable
    
    Private _schemaSerializationMode As Global.System.Data.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Sub New()
        MyBase.New
        Me.BeginInit
        Me.InitClass
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler MyBase.Relations.CollectionChanged, schemaChangedHandler
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
        MyBase.New(info, context, false)
        If (Me.IsBinarySerialized(info, context) = true) Then
            Me.InitVars(false)
            Dim schemaChangedHandler1 As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
            AddHandler Me.Tables.CollectionChanged, schemaChangedHandler1
            AddHandler Me.Relations.CollectionChanged, schemaChangedHandler1
            Return
        End If
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(String)),String)
        If (Me.DetermineSchemaSerializationMode(info, context) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet
            ds.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("tbl_rep_gon")) Is Nothing) Then
                MyBase.Tables.Add(New tbl_rep_gonDataTable(ds.Tables("tbl_rep_gon")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.Browsable(false),  _
     Global.System.ComponentModel.DesignerSerializationVisibility(Global.System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property tbl_rep_gon() As tbl_rep_gonDataTable
        Get
            Return Me.tabletbl_rep_gon
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.BrowsableAttribute(true),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Visible)>  _
    Public Overrides Property SchemaSerializationMode() As Global.System.Data.SchemaSerializationMode
        Get
            Return Me._schemaSerializationMode
        End Get
        Set
            Me._schemaSerializationMode = value
        End Set
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Tables() As Global.System.Data.DataTableCollection
        Get
            Return MyBase.Tables
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Relations() As Global.System.Data.DataRelationCollection
        Get
            Return MyBase.Relations
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Sub InitializeDerivedDataSet()
        Me.BeginInit
        Me.InitClass
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Overrides Function Clone() As Global.System.Data.DataSet
        Dim cln As DSGON = CType(MyBase.Clone,DSGON)
        cln.InitVars
        cln.SchemaSerializationMode = Me.SchemaSerializationMode
        Return cln
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As Global.System.Xml.XmlReader)
        If (Me.DetermineSchemaSerializationMode(reader) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Me.Reset
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet
            ds.ReadXml(reader)
            If (Not (ds.Tables("tbl_rep_gon")) Is Nothing) Then
                MyBase.Tables.Add(New tbl_rep_gonDataTable(ds.Tables("tbl_rep_gon")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXml(reader)
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function GetSchemaSerializable() As Global.System.Xml.Schema.XmlSchema
        Dim stream As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
        Me.WriteXmlSchema(New Global.System.Xml.XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return Global.System.Xml.Schema.XmlSchema.Read(New Global.System.Xml.XmlTextReader(stream), Nothing)
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Overloads Sub InitVars()
        Me.InitVars(true)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Overloads Sub InitVars(ByVal initTable As Boolean)
        Me.tabletbl_rep_gon = CType(MyBase.Tables("tbl_rep_gon"),tbl_rep_gonDataTable)
        If (initTable = true) Then
            If (Not (Me.tabletbl_rep_gon) Is Nothing) Then
                Me.tabletbl_rep_gon.InitVars
            End If
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Sub InitClass()
        Me.DataSetName = "DSGON"
        Me.Prefix = ""
        Me.Namespace = "http://tempuri.org/DSGON.xsd"
        Me.EnforceConstraints = true
        Me.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
        Me.tabletbl_rep_gon = New tbl_rep_gonDataTable
        MyBase.Tables.Add(Me.tabletbl_rep_gon)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Function ShouldSerializetbl_rep_gon() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As Global.System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = Global.System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Shared Function GetTypedDataSetSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
        Dim ds As DSGON = New DSGON
        Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType
        Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence
        Dim any As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
        any.Namespace = ds.Namespace
        sequence.Items.Add(any)
        type.Particle = sequence
        Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
        If xs.Contains(dsSchema.TargetNamespace) Then
            Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
            Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
            Try 
                Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                dsSchema.Write(s1)
                Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                Do While schemas.MoveNext
                    schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                    s2.SetLength(0)
                    schema.Write(s2)
                    If (s1.Length = s2.Length) Then
                        s1.Position = 0
                        s2.Position = 0
                        
                        Do While ((s1.Position <> s1.Length)  _
                                    AndAlso (s1.ReadByte = s2.ReadByte))
                            
                            
                        Loop
                        If (s1.Position = s1.Length) Then
                            Return type
                        End If
                    End If
                    
                Loop
            Finally
                If (Not (s1) Is Nothing) Then
                    s1.Close
                End If
                If (Not (s2) Is Nothing) Then
                    s2.Close
                End If
            End Try
        End If
        xs.Add(dsSchema)
        Return type
    End Function
    
    Public Delegate Sub tbl_rep_gonRowChangeEventHandler(ByVal sender As Object, ByVal e As tbl_rep_gonRowChangeEvent)
    
    '''<summary>
    '''Represents the strongly named DataTable class.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
     Global.System.Serializable(),  _
     Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")>  _
    Partial Public Class tbl_rep_gonDataTable
        Inherits Global.System.Data.DataTable
        Implements Global.System.Collections.IEnumerable
        
        Private columnDISTRIBUTOR_NAME As Global.System.Data.DataColumn
        
        Private columnADDRESS As Global.System.Data.DataColumn
        
        Private columnPO_REF_NO As Global.System.Data.DataColumn
        
        Private columnPO_REF_DATE As Global.System.Data.DataColumn
        
        Private columnSPPB_NO As Global.System.Data.DataColumn
        
        Private columnSPPB_DATE As Global.System.Data.DataColumn
        
        Private columnGON_NO As Global.System.Data.DataColumn
        
        Private columnVAR_GON_NO As Global.System.Data.DataColumn
        
        Private columnGON_DATE As Global.System.Data.DataColumn
        
        Private columnWARHOUSE As Global.System.Data.DataColumn
        
        Private columnTRANSPORTER_NAME As Global.System.Data.DataColumn
        
        Private columnBRANDPACK_NAME As Global.System.Data.DataColumn
        
        Private columnQUANTITY As Global.System.Data.DataColumn
        
        Private columnCOLLY_BOX As Global.System.Data.DataColumn
        
        Private columnCOLLY_PACKSIZE As Global.System.Data.DataColumn
        
        Private columnBATCH_NO As Global.System.Data.DataColumn
        
        Private columnVAR_DIST_ADDRESS As Global.System.Data.DataColumn
        
        Private columnPOREF_NO_AND_DATE As Global.System.Data.DataColumn
        
        Private columnSPPB_NO_AND_DATE As Global.System.Data.DataColumn
        
        Private columnVAR_GON_DATE_STR As Global.System.Data.DataColumn
        
        Private columnPOLICE_NO_TRANS As Global.System.Data.DataColumn
        
        Private columnDRIVER_TRANS As Global.System.Data.DataColumn
        
        Private columnVAR_WARHOUSE As Global.System.Data.DataColumn
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New()
            MyBase.New
            Me.TableName = "tbl_rep_gon"
            Me.BeginInit
            Me.InitClass
            Me.EndInit
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub New(ByVal table As Global.System.Data.DataTable)
            MyBase.New
            Me.TableName = table.TableName
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
            MyBase.New(info, context)
            Me.InitVars
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DISTRIBUTOR_NAMEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDISTRIBUTOR_NAME
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property ADDRESSColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnADDRESS
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property PO_REF_NOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPO_REF_NO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property PO_REF_DATEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPO_REF_DATE
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property SPPB_NOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnSPPB_NO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property SPPB_DATEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnSPPB_DATE
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property GON_NOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnGON_NO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property VAR_GON_NOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnVAR_GON_NO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property GON_DATEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnGON_DATE
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property WARHOUSEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnWARHOUSE
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property TRANSPORTER_NAMEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnTRANSPORTER_NAME
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property BRANDPACK_NAMEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnBRANDPACK_NAME
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property QUANTITYColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnQUANTITY
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property COLLY_BOXColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCOLLY_BOX
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property COLLY_PACKSIZEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCOLLY_PACKSIZE
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property BATCH_NOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnBATCH_NO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property VAR_DIST_ADDRESSColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnVAR_DIST_ADDRESS
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property POREF_NO_AND_DATEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPOREF_NO_AND_DATE
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property SPPB_NO_AND_DATEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnSPPB_NO_AND_DATE
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property VAR_GON_DATE_STRColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnVAR_GON_DATE_STR
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property POLICE_NO_TRANSColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPOLICE_NO_TRANS
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DRIVER_TRANSColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDRIVER_TRANS
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property VAR_WARHOUSEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnVAR_WARHOUSE
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count() As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Default ReadOnly Property Item(ByVal index As Integer) As tbl_rep_gonRow
            Get
                Return CType(Me.Rows(index),tbl_rep_gonRow)
            End Get
        End Property
        
        Public Event tbl_rep_gonRowChanging As tbl_rep_gonRowChangeEventHandler
        
        Public Event tbl_rep_gonRowChanged As tbl_rep_gonRowChangeEventHandler
        
        Public Event tbl_rep_gonRowDeleting As tbl_rep_gonRowChangeEventHandler
        
        Public Event tbl_rep_gonRowDeleted As tbl_rep_gonRowChangeEventHandler
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overloads Sub Addtbl_rep_gonRow(ByVal row As tbl_rep_gonRow)
            Me.Rows.Add(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overloads Function Addtbl_rep_gonRow( _
                    ByVal DISTRIBUTOR_NAME As String,  _
                    ByVal ADDRESS As String,  _
                    ByVal PO_REF_NO As String,  _
                    ByVal PO_REF_DATE As Date,  _
                    ByVal SPPB_NO As String,  _
                    ByVal SPPB_DATE As Date,  _
                    ByVal GON_NO As String,  _
                    ByVal VAR_GON_NO As String,  _
                    ByVal GON_DATE As Date,  _
                    ByVal WARHOUSE As String,  _
                    ByVal TRANSPORTER_NAME As String,  _
                    ByVal BRANDPACK_NAME As String,  _
                    ByVal QUANTITY As String,  _
                    ByVal COLLY_BOX As String,  _
                    ByVal COLLY_PACKSIZE As String,  _
                    ByVal BATCH_NO As String,  _
                    ByVal VAR_DIST_ADDRESS As String,  _
                    ByVal POREF_NO_AND_DATE As String,  _
                    ByVal SPPB_NO_AND_DATE As String,  _
                    ByVal VAR_GON_DATE_STR As String,  _
                    ByVal POLICE_NO_TRANS As String,  _
                    ByVal DRIVER_TRANS As String,  _
                    ByVal VAR_WARHOUSE As String) As tbl_rep_gonRow
            Dim rowtbl_rep_gonRow As tbl_rep_gonRow = CType(Me.NewRow,tbl_rep_gonRow)
            Dim columnValuesArray() As Object = New Object() {DISTRIBUTOR_NAME, ADDRESS, PO_REF_NO, PO_REF_DATE, SPPB_NO, SPPB_DATE, GON_NO, VAR_GON_NO, GON_DATE, WARHOUSE, TRANSPORTER_NAME, BRANDPACK_NAME, QUANTITY, COLLY_BOX, COLLY_PACKSIZE, BATCH_NO, VAR_DIST_ADDRESS, POREF_NO_AND_DATE, SPPB_NO_AND_DATE, VAR_GON_DATE_STR, POLICE_NO_TRANS, DRIVER_TRANS, VAR_WARHOUSE}
            rowtbl_rep_gonRow.ItemArray = columnValuesArray
            Me.Rows.Add(rowtbl_rep_gonRow)
            Return rowtbl_rep_gonRow
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overridable Function GetEnumerator() As Global.System.Collections.IEnumerator Implements Global.System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overrides Function Clone() As Global.System.Data.DataTable
            Dim cln As tbl_rep_gonDataTable = CType(MyBase.Clone,tbl_rep_gonDataTable)
            cln.InitVars
            Return cln
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function CreateInstance() As Global.System.Data.DataTable
            Return New tbl_rep_gonDataTable
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub InitVars()
            Me.columnDISTRIBUTOR_NAME = MyBase.Columns("DISTRIBUTOR_NAME")
            Me.columnADDRESS = MyBase.Columns("ADDRESS")
            Me.columnPO_REF_NO = MyBase.Columns("PO_REF_NO")
            Me.columnPO_REF_DATE = MyBase.Columns("PO_REF_DATE")
            Me.columnSPPB_NO = MyBase.Columns("SPPB_NO")
            Me.columnSPPB_DATE = MyBase.Columns("SPPB_DATE")
            Me.columnGON_NO = MyBase.Columns("GON_NO")
            Me.columnVAR_GON_NO = MyBase.Columns("VAR_GON_NO")
            Me.columnGON_DATE = MyBase.Columns("GON_DATE")
            Me.columnWARHOUSE = MyBase.Columns("WARHOUSE")
            Me.columnTRANSPORTER_NAME = MyBase.Columns("TRANSPORTER_NAME")
            Me.columnBRANDPACK_NAME = MyBase.Columns("BRANDPACK_NAME")
            Me.columnQUANTITY = MyBase.Columns("QUANTITY")
            Me.columnCOLLY_BOX = MyBase.Columns("COLLY_BOX")
            Me.columnCOLLY_PACKSIZE = MyBase.Columns("COLLY_PACKSIZE")
            Me.columnBATCH_NO = MyBase.Columns("BATCH_NO")
            Me.columnVAR_DIST_ADDRESS = MyBase.Columns("VAR_DIST_ADDRESS")
            Me.columnPOREF_NO_AND_DATE = MyBase.Columns("POREF_NO_AND_DATE")
            Me.columnSPPB_NO_AND_DATE = MyBase.Columns("SPPB_NO_AND_DATE")
            Me.columnVAR_GON_DATE_STR = MyBase.Columns("VAR_GON_DATE_STR")
            Me.columnPOLICE_NO_TRANS = MyBase.Columns("POLICE_NO_TRANS")
            Me.columnDRIVER_TRANS = MyBase.Columns("DRIVER_TRANS")
            Me.columnVAR_WARHOUSE = MyBase.Columns("VAR_WARHOUSE")
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Private Sub InitClass()
            Me.columnDISTRIBUTOR_NAME = New Global.System.Data.DataColumn("DISTRIBUTOR_NAME", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDISTRIBUTOR_NAME)
            Me.columnADDRESS = New Global.System.Data.DataColumn("ADDRESS", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnADDRESS)
            Me.columnPO_REF_NO = New Global.System.Data.DataColumn("PO_REF_NO", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPO_REF_NO)
            Me.columnPO_REF_DATE = New Global.System.Data.DataColumn("PO_REF_DATE", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPO_REF_DATE)
            Me.columnSPPB_NO = New Global.System.Data.DataColumn("SPPB_NO", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnSPPB_NO)
            Me.columnSPPB_DATE = New Global.System.Data.DataColumn("SPPB_DATE", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnSPPB_DATE)
            Me.columnGON_NO = New Global.System.Data.DataColumn("GON_NO", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnGON_NO)
            Me.columnVAR_GON_NO = New Global.System.Data.DataColumn("VAR_GON_NO", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnVAR_GON_NO)
            Me.columnGON_DATE = New Global.System.Data.DataColumn("GON_DATE", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnGON_DATE)
            Me.columnWARHOUSE = New Global.System.Data.DataColumn("WARHOUSE", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnWARHOUSE)
            Me.columnTRANSPORTER_NAME = New Global.System.Data.DataColumn("TRANSPORTER_NAME", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnTRANSPORTER_NAME)
            Me.columnBRANDPACK_NAME = New Global.System.Data.DataColumn("BRANDPACK_NAME", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnBRANDPACK_NAME)
            Me.columnQUANTITY = New Global.System.Data.DataColumn("QUANTITY", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnQUANTITY)
            Me.columnCOLLY_BOX = New Global.System.Data.DataColumn("COLLY_BOX", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCOLLY_BOX)
            Me.columnCOLLY_PACKSIZE = New Global.System.Data.DataColumn("COLLY_PACKSIZE", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCOLLY_PACKSIZE)
            Me.columnBATCH_NO = New Global.System.Data.DataColumn("BATCH_NO", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnBATCH_NO)
            Me.columnVAR_DIST_ADDRESS = New Global.System.Data.DataColumn("VAR_DIST_ADDRESS", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnVAR_DIST_ADDRESS)
            Me.columnPOREF_NO_AND_DATE = New Global.System.Data.DataColumn("POREF_NO_AND_DATE", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPOREF_NO_AND_DATE)
            Me.columnSPPB_NO_AND_DATE = New Global.System.Data.DataColumn("SPPB_NO_AND_DATE", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnSPPB_NO_AND_DATE)
            Me.columnVAR_GON_DATE_STR = New Global.System.Data.DataColumn("VAR_GON_DATE_STR", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnVAR_GON_DATE_STR)
            Me.columnPOLICE_NO_TRANS = New Global.System.Data.DataColumn("POLICE_NO_TRANS", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPOLICE_NO_TRANS)
            Me.columnDRIVER_TRANS = New Global.System.Data.DataColumn("DRIVER_TRANS", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDRIVER_TRANS)
            Me.columnVAR_WARHOUSE = New Global.System.Data.DataColumn("VAR_WARHOUSE", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnVAR_WARHOUSE)
            Me.columnDISTRIBUTOR_NAME.AllowDBNull = false
            Me.columnADDRESS.AllowDBNull = false
            Me.columnADDRESS.DefaultValue = CType("-",String)
            Me.columnPO_REF_NO.AllowDBNull = false
            Me.columnPO_REF_DATE.AllowDBNull = false
            Me.columnBATCH_NO.MaxLength = 250
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Newtbl_rep_gonRow() As tbl_rep_gonRow
            Return CType(Me.NewRow,tbl_rep_gonRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function NewRowFromBuilder(ByVal builder As Global.System.Data.DataRowBuilder) As Global.System.Data.DataRow
            Return New tbl_rep_gonRow(builder)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function GetRowType() As Global.System.Type
            Return GetType(tbl_rep_gonRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowChanged(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.tbl_rep_gonRowChangedEvent) Is Nothing) Then
                RaiseEvent tbl_rep_gonRowChanged(Me, New tbl_rep_gonRowChangeEvent(CType(e.Row,tbl_rep_gonRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowChanging(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.tbl_rep_gonRowChangingEvent) Is Nothing) Then
                RaiseEvent tbl_rep_gonRowChanging(Me, New tbl_rep_gonRowChangeEvent(CType(e.Row,tbl_rep_gonRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowDeleted(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.tbl_rep_gonRowDeletedEvent) Is Nothing) Then
                RaiseEvent tbl_rep_gonRowDeleted(Me, New tbl_rep_gonRowChangeEvent(CType(e.Row,tbl_rep_gonRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowDeleting(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.tbl_rep_gonRowDeletingEvent) Is Nothing) Then
                RaiseEvent tbl_rep_gonRowDeleting(Me, New tbl_rep_gonRowChangeEvent(CType(e.Row,tbl_rep_gonRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Removetbl_rep_gonRow(ByVal row As tbl_rep_gonRow)
            Me.Rows.Remove(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Shared Function GetTypedTableSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
            Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType
            Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence
            Dim ds As DSGON = New DSGON
            Dim any1 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
            any1.Namespace = "http://www.w3.org/2001/XMLSchema"
            any1.MinOccurs = New Decimal(0)
            any1.MaxOccurs = Decimal.MaxValue
            any1.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any1)
            Dim any2 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
            any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1"
            any2.MinOccurs = New Decimal(1)
            any2.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any2)
            Dim attribute1 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute
            attribute1.Name = "namespace"
            attribute1.FixedValue = ds.Namespace
            type.Attributes.Add(attribute1)
            Dim attribute2 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute
            attribute2.Name = "tableTypeName"
            attribute2.FixedValue = "tbl_rep_gonDataTable"
            type.Attributes.Add(attribute2)
            type.Particle = sequence
            Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
            If xs.Contains(dsSchema.TargetNamespace) Then
                Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
                Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
                Try 
                    Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                    dsSchema.Write(s1)
                    Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                    Do While schemas.MoveNext
                        schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                        s2.SetLength(0)
                        schema.Write(s2)
                        If (s1.Length = s2.Length) Then
                            s1.Position = 0
                            s2.Position = 0
                            
                            Do While ((s1.Position <> s1.Length)  _
                                        AndAlso (s1.ReadByte = s2.ReadByte))
                                
                                
                            Loop
                            If (s1.Position = s1.Length) Then
                                Return type
                            End If
                        End If
                        
                    Loop
                Finally
                    If (Not (s1) Is Nothing) Then
                        s1.Close
                    End If
                    If (Not (s2) Is Nothing) Then
                        s2.Close
                    End If
                End Try
            End If
            xs.Add(dsSchema)
            Return type
        End Function
    End Class
    
    '''<summary>
    '''Represents strongly named DataRow class.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")>  _
    Partial Public Class tbl_rep_gonRow
        Inherits Global.System.Data.DataRow
        
        Private tabletbl_rep_gon As tbl_rep_gonDataTable
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub New(ByVal rb As Global.System.Data.DataRowBuilder)
            MyBase.New(rb)
            Me.tabletbl_rep_gon = CType(Me.Table,tbl_rep_gonDataTable)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DISTRIBUTOR_NAME() As String
            Get
                Return CType(Me(Me.tabletbl_rep_gon.DISTRIBUTOR_NAMEColumn),String)
            End Get
            Set
                Me(Me.tabletbl_rep_gon.DISTRIBUTOR_NAMEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ADDRESS() As String
            Get
                Return CType(Me(Me.tabletbl_rep_gon.ADDRESSColumn),String)
            End Get
            Set
                Me(Me.tabletbl_rep_gon.ADDRESSColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property PO_REF_NO() As String
            Get
                Return CType(Me(Me.tabletbl_rep_gon.PO_REF_NOColumn),String)
            End Get
            Set
                Me(Me.tabletbl_rep_gon.PO_REF_NOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property PO_REF_DATE() As Date
            Get
                Return CType(Me(Me.tabletbl_rep_gon.PO_REF_DATEColumn),Date)
            End Get
            Set
                Me(Me.tabletbl_rep_gon.PO_REF_DATEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SPPB_NO() As String
            Get
                Try 
                    Return CType(Me(Me.tabletbl_rep_gon.SPPB_NOColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'SPPB_NO' in table 'tbl_rep_gon' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tabletbl_rep_gon.SPPB_NOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SPPB_DATE() As Date
            Get
                Try 
                    Return CType(Me(Me.tabletbl_rep_gon.SPPB_DATEColumn),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'SPPB_DATE' in table 'tbl_rep_gon' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tabletbl_rep_gon.SPPB_DATEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property GON_NO() As String
            Get
                Try 
                    Return CType(Me(Me.tabletbl_rep_gon.GON_NOColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'GON_NO' in table 'tbl_rep_gon' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tabletbl_rep_gon.GON_NOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property VAR_GON_NO() As String
            Get
                Try 
                    Return CType(Me(Me.tabletbl_rep_gon.VAR_GON_NOColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'VAR_GON_NO' in table 'tbl_rep_gon' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tabletbl_rep_gon.VAR_GON_NOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property GON_DATE() As Date
            Get
                Try 
                    Return CType(Me(Me.tabletbl_rep_gon.GON_DATEColumn),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'GON_DATE' in table 'tbl_rep_gon' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tabletbl_rep_gon.GON_DATEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property WARHOUSE() As String
            Get
                Try 
                    Return CType(Me(Me.tabletbl_rep_gon.WARHOUSEColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'WARHOUSE' in table 'tbl_rep_gon' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tabletbl_rep_gon.WARHOUSEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property TRANSPORTER_NAME() As String
            Get
                Try 
                    Return CType(Me(Me.tabletbl_rep_gon.TRANSPORTER_NAMEColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'TRANSPORTER_NAME' in table 'tbl_rep_gon' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tabletbl_rep_gon.TRANSPORTER_NAMEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property BRANDPACK_NAME() As String
            Get
                Try 
                    Return CType(Me(Me.tabletbl_rep_gon.BRANDPACK_NAMEColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'BRANDPACK_NAME' in table 'tbl_rep_gon' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tabletbl_rep_gon.BRANDPACK_NAMEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property QUANTITY() As String
            Get
                Try 
                    Return CType(Me(Me.tabletbl_rep_gon.QUANTITYColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'QUANTITY' in table 'tbl_rep_gon' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tabletbl_rep_gon.QUANTITYColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property COLLY_BOX() As String
            Get
                Try 
                    Return CType(Me(Me.tabletbl_rep_gon.COLLY_BOXColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'COLLY_BOX' in table 'tbl_rep_gon' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tabletbl_rep_gon.COLLY_BOXColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property COLLY_PACKSIZE() As String
            Get
                Try 
                    Return CType(Me(Me.tabletbl_rep_gon.COLLY_PACKSIZEColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'COLLY_PACKSIZE' in table 'tbl_rep_gon' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tabletbl_rep_gon.COLLY_PACKSIZEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property BATCH_NO() As String
            Get
                Try 
                    Return CType(Me(Me.tabletbl_rep_gon.BATCH_NOColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'BATCH_NO' in table 'tbl_rep_gon' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tabletbl_rep_gon.BATCH_NOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property VAR_DIST_ADDRESS() As String
            Get
                Try 
                    Return CType(Me(Me.tabletbl_rep_gon.VAR_DIST_ADDRESSColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'VAR_DIST_ADDRESS' in table 'tbl_rep_gon' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tabletbl_rep_gon.VAR_DIST_ADDRESSColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property POREF_NO_AND_DATE() As String
            Get
                Try 
                    Return CType(Me(Me.tabletbl_rep_gon.POREF_NO_AND_DATEColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'POREF_NO_AND_DATE' in table 'tbl_rep_gon' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tabletbl_rep_gon.POREF_NO_AND_DATEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SPPB_NO_AND_DATE() As String
            Get
                Try 
                    Return CType(Me(Me.tabletbl_rep_gon.SPPB_NO_AND_DATEColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'SPPB_NO_AND_DATE' in table 'tbl_rep_gon' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tabletbl_rep_gon.SPPB_NO_AND_DATEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property VAR_GON_DATE_STR() As String
            Get
                Try 
                    Return CType(Me(Me.tabletbl_rep_gon.VAR_GON_DATE_STRColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'VAR_GON_DATE_STR' in table 'tbl_rep_gon' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tabletbl_rep_gon.VAR_GON_DATE_STRColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property POLICE_NO_TRANS() As String
            Get
                Try 
                    Return CType(Me(Me.tabletbl_rep_gon.POLICE_NO_TRANSColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'POLICE_NO_TRANS' in table 'tbl_rep_gon' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tabletbl_rep_gon.POLICE_NO_TRANSColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DRIVER_TRANS() As String
            Get
                Try 
                    Return CType(Me(Me.tabletbl_rep_gon.DRIVER_TRANSColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'DRIVER_TRANS' in table 'tbl_rep_gon' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tabletbl_rep_gon.DRIVER_TRANSColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property VAR_WARHOUSE() As String
            Get
                Try 
                    Return CType(Me(Me.tabletbl_rep_gon.VAR_WARHOUSEColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'VAR_WARHOUSE' in table 'tbl_rep_gon' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tabletbl_rep_gon.VAR_WARHOUSEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsSPPB_NONull() As Boolean
            Return Me.IsNull(Me.tabletbl_rep_gon.SPPB_NOColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetSPPB_NONull()
            Me(Me.tabletbl_rep_gon.SPPB_NOColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsSPPB_DATENull() As Boolean
            Return Me.IsNull(Me.tabletbl_rep_gon.SPPB_DATEColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetSPPB_DATENull()
            Me(Me.tabletbl_rep_gon.SPPB_DATEColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsGON_NONull() As Boolean
            Return Me.IsNull(Me.tabletbl_rep_gon.GON_NOColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetGON_NONull()
            Me(Me.tabletbl_rep_gon.GON_NOColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsVAR_GON_NONull() As Boolean
            Return Me.IsNull(Me.tabletbl_rep_gon.VAR_GON_NOColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetVAR_GON_NONull()
            Me(Me.tabletbl_rep_gon.VAR_GON_NOColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsGON_DATENull() As Boolean
            Return Me.IsNull(Me.tabletbl_rep_gon.GON_DATEColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetGON_DATENull()
            Me(Me.tabletbl_rep_gon.GON_DATEColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsWARHOUSENull() As Boolean
            Return Me.IsNull(Me.tabletbl_rep_gon.WARHOUSEColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetWARHOUSENull()
            Me(Me.tabletbl_rep_gon.WARHOUSEColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsTRANSPORTER_NAMENull() As Boolean
            Return Me.IsNull(Me.tabletbl_rep_gon.TRANSPORTER_NAMEColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetTRANSPORTER_NAMENull()
            Me(Me.tabletbl_rep_gon.TRANSPORTER_NAMEColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsBRANDPACK_NAMENull() As Boolean
            Return Me.IsNull(Me.tabletbl_rep_gon.BRANDPACK_NAMEColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetBRANDPACK_NAMENull()
            Me(Me.tabletbl_rep_gon.BRANDPACK_NAMEColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsQUANTITYNull() As Boolean
            Return Me.IsNull(Me.tabletbl_rep_gon.QUANTITYColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetQUANTITYNull()
            Me(Me.tabletbl_rep_gon.QUANTITYColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsCOLLY_BOXNull() As Boolean
            Return Me.IsNull(Me.tabletbl_rep_gon.COLLY_BOXColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetCOLLY_BOXNull()
            Me(Me.tabletbl_rep_gon.COLLY_BOXColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsCOLLY_PACKSIZENull() As Boolean
            Return Me.IsNull(Me.tabletbl_rep_gon.COLLY_PACKSIZEColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetCOLLY_PACKSIZENull()
            Me(Me.tabletbl_rep_gon.COLLY_PACKSIZEColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsBATCH_NONull() As Boolean
            Return Me.IsNull(Me.tabletbl_rep_gon.BATCH_NOColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetBATCH_NONull()
            Me(Me.tabletbl_rep_gon.BATCH_NOColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsVAR_DIST_ADDRESSNull() As Boolean
            Return Me.IsNull(Me.tabletbl_rep_gon.VAR_DIST_ADDRESSColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetVAR_DIST_ADDRESSNull()
            Me(Me.tabletbl_rep_gon.VAR_DIST_ADDRESSColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsPOREF_NO_AND_DATENull() As Boolean
            Return Me.IsNull(Me.tabletbl_rep_gon.POREF_NO_AND_DATEColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetPOREF_NO_AND_DATENull()
            Me(Me.tabletbl_rep_gon.POREF_NO_AND_DATEColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsSPPB_NO_AND_DATENull() As Boolean
            Return Me.IsNull(Me.tabletbl_rep_gon.SPPB_NO_AND_DATEColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetSPPB_NO_AND_DATENull()
            Me(Me.tabletbl_rep_gon.SPPB_NO_AND_DATEColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsVAR_GON_DATE_STRNull() As Boolean
            Return Me.IsNull(Me.tabletbl_rep_gon.VAR_GON_DATE_STRColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetVAR_GON_DATE_STRNull()
            Me(Me.tabletbl_rep_gon.VAR_GON_DATE_STRColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsPOLICE_NO_TRANSNull() As Boolean
            Return Me.IsNull(Me.tabletbl_rep_gon.POLICE_NO_TRANSColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetPOLICE_NO_TRANSNull()
            Me(Me.tabletbl_rep_gon.POLICE_NO_TRANSColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDRIVER_TRANSNull() As Boolean
            Return Me.IsNull(Me.tabletbl_rep_gon.DRIVER_TRANSColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDRIVER_TRANSNull()
            Me(Me.tabletbl_rep_gon.DRIVER_TRANSColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsVAR_WARHOUSENull() As Boolean
            Return Me.IsNull(Me.tabletbl_rep_gon.VAR_WARHOUSEColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetVAR_WARHOUSENull()
            Me(Me.tabletbl_rep_gon.VAR_WARHOUSEColumn) = Global.System.Convert.DBNull
        End Sub
    End Class
    
    '''<summary>
    '''Row event argument class
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")>  _
    Public Class tbl_rep_gonRowChangeEvent
        Inherits Global.System.EventArgs
        
        Private eventRow As tbl_rep_gonRow
        
        Private eventAction As Global.System.Data.DataRowAction
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New(ByVal row As tbl_rep_gonRow, ByVal action As Global.System.Data.DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Row() As tbl_rep_gonRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Action() As Global.System.Data.DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
