/*
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Trigger_Update_OA_BrandPack'
	AND TYPE = 'TR')
DROP TRIGGER Trigger_Update_OA_BrandPack
GO
CREATE TRIGGER Trigger_Update_OA_BrandPack ON ORDR_OA_BRANDPACK
AFTER UPDATE
AS
      IF UPDATE(PROG_DISC_QTY)
	SET NOCOUNT ON
	GO
	SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
	GO
       BEGIN
	DECLARE @SUM_PROG_DISC_QTY DECIMAL(18,3),@OA_BRANDPACK_ID VARCHAR(70),@PROG_DISC_QTY DECIMAL(18,3)
	SET @OA_BRANDPACK_ID = (SELECT OA_BRANDPACK_ID FROM UPDATED)
	SET @PROG_DISC_QTY = CAST((SELECT PROG_DISC_QTY FROM UPDATED) AS DECIMAL(18,3))
	SET @SUM_PROG_DISC_QTY = CAST((SELECT ISNULL(SUM(ORDR_OA_BRANDPACK_DISC.DISC_QTY),0)
	WHERE OA_BRANDPACK_ID = @OA_BRANDPACK_ID AND GQSY_SGT_P_FLAG = 'MG') AS DECIMAL(18,3)) + 
	CAST((SELECT ISNULL(SUM(ORDR_OA_BRANDPACK_DISC.DISC_QTY),0)
	WHERE OA_BRANDPACK_ID = @OA_BRANDPACK_ID AND GQSY_SGT_P_FLAG = 'MS') AS DECIMAL(18,3)) +
	CAST((SELECT ISNULL(SUM(ORDR_OA_BRANDPACK_DISC.DISC_QTY),0)
	WHERE OA_BRANDPACK_ID = @OA_BRANDPACK_ID AND GQSY_SGT_P_FLAG = 'MT') AS DECIMAL(18,3)) +
	CAST((SELECT ISNULL(SUM(ORDR_OA_BRANDPACK_DISC.DISC_QTY),0)
	WHERE OA_BRANDPACK_ID = @OA_BRANDPACK_ID AND GQSY_SGT_P_FLAG = 'KP') AS DECIMAL(18,3)) +
	CAST((SELECT ISNULL(SUM(ORDR_OA_BRANDPACK_DISC.DISC_QTY),0)
	WHERE OA_BRANDPACK_ID = @OA_BRANDPACK_ID AND GQSY_SGT_P_FLAG = 'DK') AS DECIMAL(18,3)) +
	CAST((SELECT ISNULL(SUM(ORDR_OA_BRANDPACK_DISC.DISC_QTY),0)
	WHERE OA_BRANDPACK_ID = @OA_BRANDPACK_ID AND GQSY_SGT_P_FLAG = 'CP') AS DECIMAL(18,3))
       	  IF (@PROG_DISC_QTY <> @SUM_PROG_DISC_QTY)
		
		BEGIN TRANSACTION
		BEGIN
		    UPDATE ORDR_OA_BRANDPACK SET PROG_DISC_QTY = @SUM_PROG_DISC_QTY
		    WHERE OA_BRANDPACK_ID = @OA_BRANDPACK_ID
		    IF (@@ERROR <> 0)
			BEGIN
			RAISERROR('can not be matched due to unknown error',16,1)
			ROLLBACK TRANSACTION
			END
		    ELSE
			COMMIT TRANSACTION

		END
	END
GO

       ELSE IF UPDATE(AGREE_DISC_QTY)
	  BEGIN
	    SET NOCOUNT ON
	    GO
	    SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
	    GO
	    DECLARE @SUM_AGREE_DISC_QTY DECIMAL(18,3),@AGREE_DISC_QTY DECIMAL(18,3)
	    SET @AGREE_DISC_QTY = CAST((SELECT AGREE_DISC_QTY FROM FROM UPDATED) AS DECIMAL(18,3)
	    SET @SUM_AGREE_DISC_QTY = CAST((SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC
	    WHERE OA_BRANDPACK_ID = @OA_BRANDPACK_ID AND GQSY_SGT_P_FLAG = 'G') AS DECIMAL(18,3)) + 
	    CAST((SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC WHERE OA_BRANDPACK_ID
	    = @OA_BRANDPACK_ID AND GQSY_SGT_P_FLAG = 'Y') AS DECIMAL(18,3)) +
	    CAST((SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC
	    WHERE OA_BRANDPACK_ID = @OA_BRANDPACK_ID AND GQSY_SGT_P_FLAG = 'Q1') AS DECIMAL(18,3)) +
	    CAST((SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC
	    WHERE OA_BRANDPACK_ID = @OA_BRANDPACK_ID AND GQSY_SGT_P_FLAG = 'Q2') AS DECIMAL(18,3)) +
	    CAST((SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC
	    WHERE OA_BRANDPACK_ID = @OA_BRANDPACK_ID AND GQSY_SGT_P_FLAG = 'Q3') AS DECIMAL(18,3)) +
	    CAST((SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC
	    WHERE OA_BRANDPACK_ID = @OA_BRANDPACK_ID AND GQSY_SGT_P_FLAG = 'Q4') AS DECIMAL(18,3)) + 
            CAST((SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC
	    WHERE OA_BRANDPACK_ID = @OA_BRANDPACK_ID AND GQSY_SGT_P_FLAG = 'Q4') AS DECIMAL(18,3)) +
	    CAST((SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC
	    WHERE OA_BRANDPACK_ID = @OA_BRANDPACK_ID AND GQSY_SGT_P_FLAG = 'S1') AS DECIMAL(18,3)) +
	    CAST((SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC
	    WHERE OA_BRANDPACK_ID = @OA_BRANDPACK_ID AND GQSY_SGT_P_FLAG = 'S2') AS DECIMAL(18,3)) +
	    CAST((SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC
	    WHERE OA_BRANDPACK_ID = @OA_BRANDPACK_ID AND GQSY_SGT_P_FLAG = 'Y') AS DECIMAL(18,3))
	    IF (@AGREE_DISC_QTY <> @SUM_AGREE_DISC_QTY)
	      	BEGIN TRANSACTION
		BEGIN
		   UPDATE ORDR_OA_BRANDPACK SET AGREE_DISC_QTY = @SUM_AGREE_DISC_QTY
		    WHERE OA_BRANDPACK_ID = @OA_BRANDPACK_ID
		    IF (@@ERROR <> 0)
			RAISERROR(@OA_BRANDPACK_ID + 'can not be matched due to unknown error'
		       ROLLBACK TRANSACTION
		    ELSE
			COMMIT TRANSACTION
		END
	   END
       ELSE IF UPDATE(OTHER_DISC_QTY)
	   BEGIN
	    DECLARE @SUM_OTHER_DISC_QTY DECIMAL(18,3),@OTHER_DISC_QTY DECIMAL(18,3)
	     SET @OTHER_DISC_QTY = CAST((SELECT OTHER_DISC_QTY FROM UPDATED) AS DECIMAL(18,3))
	     SET @SUM_OTHER_DISC_QTY = CAST((SELECT ISNULL(SUM(DISC_QTY),0) FROM ORDR_OA_BRANDPACK_DISC
	     WHERE OA_BRANDPACK_ID = @OA_BRANDPACK_ID AND GQSY_SGT_P_FLAG = 'O') AS DECIMAL(18,3))      
	     IF (@OTHER_DISC_QTY <> @SUM_OTHER_DISC_QTY)
		
		BEGIN TRANSACTION
		BEGIN
	  
		   UPDATE ORDR_OA_BRANDPACK SET OTHER_DISC_QTY = @SUM_OTHER_DISC_QTY
		   WHERE OA_BRANDPACK_ID = @OA_BRANDPACK_ID
		   IF (@@ERROR <> 0)
		     RAISERROR(@OA_BRANDPACK_ID + 'can not be matched due to unknown error'
		     ROLLBACK TRANSACTION
		   ELSE
		     COMMIT TRANSACTION
		END
	   END
        ELSE IF UPDATE(PROJ_DISC_QTY) 
	   BEGIN
	     DECLARE @SUM_PROJ_DISC_QTY DECIMAL(18,3),@PROJ_DISC_QTY DECIMAL(18,3)
	     SET @PROJ_DISC_QTY = CAST((SELECT PROJ_DISC_QTY FROM UPDATED) AS DECIMAL(18,3))
             SET @SUM_PROJ_DISC_QTY = CAST((SELECT ISNULL(SUM(DISC_QTY),0)
	        FROM ORDR_OA_BRANDPACK_DISC WHERE OA_BRANDPACK_ID = @OA_BRANDPACK_ID AND
	        GQSY_SGT_P_FLAG = 'P')AS DECIMAL(18,3))
	       IF(@PROJ_DISC_QTY <> @SUM_PROJ_DISC_QTY)
		
		BEGIN TRANSACTION
		BEGIN
		   UPDATE ORDR_OA_BRANDPACK SET PROJ_DISC_QTY = @PROJ_DISC_QTY
		   WHERE OA_BRANDPACK_ID = @OA_BRANDPACK_ID
		   IF (@@ROWCOUNT <> 0)
		     RAISERROR(@OA_BRANDPACK_ID + 'can not be matched due to unknown error'
		     ROLLBACK TRANSACTION
		   ELSE
		     COMMIT TRANSACTION
		END		 
	   END

	
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Trigered_SPPB_QTY' AND TYPE = 'TR')
DROP TRIGGER Trigered_SPPB_QTY
GO
CREATE TRIGGER Trigered_SPPB_QTY ON OA_BRANDPACK AFTER UPDATE
AS
IF (SELECT SPPB_QTY*/
