--------------------TRIGER BUAT SPPB_QTY----------------------------
IF EXISTS(SELECT NAME FROM DBO.SYSOBJECTS WHERE NAME = 'Trigger_Revisi_SPPB_QTY'
	AND TYPE = 'TR')
DROP TRIGGER Trigger_Revisi_SPPB_QTY
GO
CREATE TRIGGER Trigger_Revisi_SPPB_QTY ON SPPB_BRANDPACK FOR INSERT,UPDATE 
AS
DECLARE @rc INT,@V_SPPB_QTY DECIMAL(18,3),@V_OA_BRANDPACK_ID VARCHAR(70)
SET @rc = @@rowcount
IF @rc = 0
BEGIN
  PRINT 'No rows affected'
  RETURN
END
IF EXISTS(SELECT * FROM inserted)
BEGIN
  IF EXISTS(SELECT * FROM deleted)
  BEGIN
    --PRINT 'UPDATE identified',
      SET @V_OA_BRANDPACK_ID = (SELECT OA_BRANDPACK_ID FROM Inserted)
      SET @V_SPPB_QTY = (SELECT SPPB_QTY FROM Inserted)
       --print '@V_SPPB_QTY = ' + CAST((@V_SPPB_QTY)AS VARCHAR(13)) 
	--UPDATE PO_THIRD_PARTY JIKA ADA
	--UPDATE DO THIRD PARTY JIKA ADA 
	IF EXISTS(SELECT OTP_BRANDPACK FROM OTP_DETAIL WHERE OA_BRANDPACK_ID = @V_OA_BRANDPACK_ID AND OTP_QTY > 0)
	   BEGIN
	   	UPDATE OTP_DETAIL SET OTP_QTY = @V_SPPB_QTY,MODIFY_DATE = GETDATE()
		WHERE OA_BRANDPACK_ID = @V_OA_BRANDPACK_ID
	   END
	IF EXISTS(SELECT DO_TP_BRANDPACK FROM DO_TP_DETAIL WHERE OA_BRANDPACK_ID = @V_OA_BRANDPACK_ID
		AND DO_TP_QTY > 0)
	   BEGIN
		UPDATE DO_TP_DETAIL SET DO_TP_QTY = @V_SPPB_QTY,MODIFY_DATE = GETDATE()
		WHERE OA_BRANDPACK_ID = @V_OA_BRANDPACK_ID
	   END
	IF (@@ROWCOUNT > 0)
	   BEGIN
		PRINT 'Data Updated Succesfully'  
	   END
	
   END
END
GO
SELECT NAME FROM DBO.SYSOBJECTS WHERE TYPE = 'TR'



--ORIGINAL SPPB_QTY 550.490

--UPDATE SPPB_BRANDPACK SET SPPB_QTY = 550.490
--WHERE SPPB_BRANDPACK_ID = '21013/DMS/JKT/05-08-0662013/DMS/JKT/05-0807230001KD'

--SELECT * FROM DO_TP_DETAIL






